### ISSUE TITLE
Unfinished manual update should install on quit

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#1007]
In non-automatic installs, where the status window with "install and relaunch" is shown, it's easy to forget to relaunch the app (user may switch to doing something else when the download takes a long time or the user doesn't want to immediately restart).

Quitting the app in such state throws away the update, which is a double loss: waste of a download, and will cause user to be nagged again.

We could improve it by installing the update when the app quits.

**Comment by zorgiepoo** [comment]
My fork already does this.
