### ISSUE TITLE
Use NSProgress

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#1015]
I wonder if we can prevent user from relaunching the app while the new version is being installed (maybe cause of #441) by using file progress, which would disable the item in Finder.

https://developer.apple.com/reference/foundation/progress.fileoperationkind

**Comment by zorgiepoo** [comment]
Not too familiar with the APIs, but as long as user can't be locked out if something awry happens and e.g. Autoupdate halts/crashes anywhere.

**Comment by prasha6** [comment]
Hello, is there any plan to include this fix in the next release ?

**Comment by pornel** [comment]
No, this hasn't been done yet.

**Comment by zorgiepoo** [comment]
I'm not convinced this is applicable to automatically replacing bundles which we do now since this was reported.
