### ISSUE TITLE
Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle

### ISSUE THREAD

**Issue by vitor251093** [sparkle-project/Sparkle#1019]
In advance, my Sparkle version is 1.14.0 and I'm using Xcode 8.2.1 in macOS 10.12.2 (Sierra), however that bug also happened with Xcode 7 in macOS 10.11. I'm not sure if that bug was already solved in later releases, but since I haven't seen any issue similar to that one I guess it wasn't.

I'm not sure if that's a problem in my application or with Sparkle, so I decide to submit an issue anyway. In case it's my application fault, then at least other people with the same problem will find out as well. 

Some of my users ran my application from volumes (I'm not sure if they are DMGs or flash drives, I'm only sure that this problem only happens when they are inside volumes), and in these cases the app crashes. That's the crash:

```
Process: MyApp [13747]
Path: /Volumes/VOLUME/*/MyApp.app/Contents/MacOS/MyApp
Identifier: com.mycompany.MyApp
Version: ???
Code Type: X86-64 (Native)
Parent Process: ??? [1]
Responsible: MyApp [13747]
User ID: -

Date/Time: 2017-01-25 18:18:05.175 -0800
OS Version: Mac OS X 10.12.2 (16C68)
Report Version: 12
Anonymous UUID: -

Sleep/Wake UUID: -

Time Awake Since Boot: 73000 seconds
Time Since Wake: 2200 seconds

System Integrity Protection: enabled

Crashed Thread: 0

Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY

Termination Reason: DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
Referenced from: /Volumes/VOLUME/*/MyApp.app/Contents/MacOS/MyApp
Reason: image not found

Binary Images:
0x10a0a2000 - 0x10a13eff7 +MyApp (0) /var/folders/*/MyApp.app/Contents/MacOS/MyApp
0x116b0a000 - 0x116b47267 dyld (421.2) <947FC440-80F9-32F7-A773-6FC418FE1AB7> /usr/lib/dyld
0x7fffab2ab000 - 0x7fffab46affb com.apple.avfoundation (2.0 - 1187.11.13) <0D0BB4A4-F987-381B-885E-88A81F50FD50> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
0x7fffb47e7000 - 0x7fffb49e2ff7 com.apple.QuartzCore (1.11 - 449.41.15) <32D80183-DCE4-34A7-AA46-DD1DE0DAA859> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
0x7fffb5692000 - 0x7fffb5703ff7 com.apple.SystemConfiguration (1.14 - 1.14) /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
```

I thought it could a problem in my app, but since the problem only happens inside volumes I'm confused. There is some special way that I should configure my app in order to find Sparkle when my app is inside a volume?

At the moment, the Sparkle.framework is added in the _Embedded Binaries_ list and in the _Linked Frameworks and Libraries_ list. It's also in my _Build Phases_ on _Link Binary With Libraries_, has Required, and in _Embed Frameworks_, copying to the Frameworks folder and signing.

Thanks in advance.

**Comment by pornel** [comment]
In Build Settings tab set “Runpath Search Paths” to @loader_path/../Frameworks

**Comment by vitor251093** [comment]
> You must configure your project: In Build Settings tab set “Runpath Search Paths” to `@loader_path/../Frameworks`

I'm not sure if being in a volume is enough to make it crash, but in case it's the problem is solved now :) 

Thanks!

**Comment by anan131435** [comment]
have you solved your problem ? I  have the save question
