### ISSUE TITLE
generate_appcast fails

### ISSUE THREAD

**Issue by GoodMorningCall** [sparkle-project/Sparkle#1020]
## Where
Distribution disk image (DMG) includes /Applications symlink.

## Reason
The tool assumes that the fist object in the DMG is the app.

## Source File
- generate_appcast/ArchiveItem.swift
### function
- convenience init(fromArchive archivePath: URL, unarchivedDir: URL) throws
### Code
line#68

`let appPath = items[0];`

## Update Suggestion
`let appPath = apps[0];`

**Comment by pornel** [comment]
Good catch!
