### ISSUE TITLE
Pulling in sandboxing/2.0 branch

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#1023]
`master` and `ui-separation-and-xpc` are still in good synchronization with each other, so I figure this would be more important to discuss and make a decision on earlier rather than later.

There's more than one branching model, but the one I [believe in](https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/) is making `master` the development branch, and older releases are branched from older points from `master`. 

Which would mean that, perhaps after some review and consideration but better decided sooner than later (and before other PR's are merged), is that the 2.0 branch should just be merged into master. Just using the green  "merge" button, not removing any useful back history, not involving any fancy rebasing.

The Sparkle version in the newer version btw should change to 2.0. The Read Me may need to change, and should indicate that it is a *major development* branch with a link to the latest production release/branch. Also cleaning the Xcode build directory before running tests on generate_appcast or what not can be done, but that can be prioritized later.

Because we push the pod spec for cocoa pods ourselves, I don't think an issue will arise from cocoa pods.

[edit]:
Why have the master branch reflect the latest version? Because I believe it's important that contributors know that the development is going on in a more visible way. Future contributors will realize differences between the development & production releases. This also reduces effort; changes applied to the development branch do not necessarily need to be back ported to an older release, especially if they are just convenience worthy and not critical issues but carry significant changes along. However, if changes are made to an older release, that of course needs to be compatible with the development version, and needs to be considered carefully for every big change.

**Comment by pornel** [comment]
Yes, that makes sense
