### ISSUE TITLE
Hidden localizable strings?

### ISSUE THREAD

**Issue by Yann-R** [sparkle-project/Sparkle#1027]
At second launch of an app (Cyberduck) that use Sparkle framework, I observed the (usal) attached warning which contains un-consistent French translations of the same English workd `"Check"`.
<img width="438" alt="image_01" src="https://cloud.githubusercontent.com/assets/319418/22739274/3e379b12-ee0b-11e6-82b8-c06ea6567159.png">

My question is: where are the localizable texts for the two buttons of the dialog box? (that mean `"Don't check"` and `"Check automatically"`)
The string for the dialog body is available in `sparkle-projet/Sparkle/Sparkle/fr.lproj/Sparkle.strings`.
But the two dialog button texts seem not available in that file.

**Comment by pornel** [comment]
Some text is in .xib files. You need to open them in Xcode to edit them.

**Comment by pornel** [comment]
Have you been able to find them? I can generate another stirngs file if that's helpful

**Comment by Yann-R** [comment]
Oh yes, forgive me. I've been able to find them after your answer.

At first I wondered why those specific strings were not indeed handled in another string file as you propose (like the body of the dialog box which is defined "outside" the xib file, and only the button texts are "inside" the xib file).

I guess it's better to keep those specific text inside since I guess it allows the localizer adapt the button sizes and other things in the xib file this way. So I think defining a new string file would not be recommended...

**Comment by pornel** [comment]
OK. What about the text? Does it need fixing? Do you need help fixing it?

**Comment by Yann-R** [comment]
Yes, I did the little fixes. I had no time to supply the result, but I will do asap.
