### ISSUE TITLE
generate_appcast not working with different folder structures

### ISSUE THREAD

**Issue by SPDEX** [sparkle-project/Sparkle#1029]
generate_appcast not working when folders are above App.app file. Error Domain=SUSparkleErrorDomain Code=1001 "No usable archives found in ..."

Examples:
**Not** **ok** (Error: No usable archives found):
folder1
folder2
folder3
MyApp.app

**Ok**:
MyApp.app
zfolder1
zfolder2
zfolder3

**Comment by pornel** [comment]
Perhaps that's dupe of #1020 

Can you check with master branch?

**Comment by SPDEX** [comment]
Thank you,

It's fixed in 1.17.0b1
