### ISSUE TITLE
Enforcing SSL pinning

### ISSUE THREAD

**Issue by the-st0rm** [sparkle-project/Sparkle#1030]
I was wondering if there is a way to enforce SSL pinning in the update process of Sparkle?

**Comment by pornel** [comment]
We don't do SSL ourselves, but rely on macOS to handle it, so we can't do it unless NSURLRequest supports it.

However, we do not rely on SSL alone. The update *must* be signed with another key, either with a DSA key, or developer's private key for Apple Code Signing. I think this achieves similar effect to SSL pinning.

**Comment by the-st0rm** [comment]
IS the signature validation enabled by default or is it an opt-in feature?

Can you point me to the code that checks the signature and if there is any configuration I need to set to enable the signature validation. 

PS: Thank you for the quick reply :)

**Comment by pornel** [comment]
Signature validation is always mandatory.
