### ISSUE TITLE
generate_appcast: consider adding `sparkle:releaseNotesLink` to item

### ISSUE THREAD

**Issue by digitalmoksha** [sparkle-project/Sparkle#1033]
It would be great if `generate_appcast` could automatically add the releaseNotesLink, based on defined formula, such as `release_notes.version_string.html`

Maybe if a file with that name exists, add it to the appcast, otherwise not.

**Comment by pornel** [comment]
That sounds good. Would you be able to make a pull request with that improvement?

**Comment by digitalmoksha** [comment]
No problem.  I decided it's better to use the archive's name, rather than something like "release_notes" - it makes sense to keep it named the same, just with the .html extension.
