### ISSUE TITLE
myapp 1.0.1 is now available - you have 1.0.2

### ISSUE THREAD

**Issue by Shasoosh** [sparkle-project/Sparkle#1035]
It seems like i'm doing something wrong. Sparkle will offer to update for an older version
my app 1.0.1 is now available - you have 1.0.2

            <enclosure url="myurl" 
                sparkle:version="1.0.1" 
                type="application/octet-stream" 
                sparkle:dsaSignature="sig==" />
            <sparkle:minimumSystemVersion>10.12</sparkle:minimumSystemVersion>

Any idea why this is happening?

Maybe sparkle is comparing CFBundleVersion? I've read the documentation and couldn't find anything related to this. 

I'm using 1.15.1

**Comment by pornel** [comment]
Yes, sparkle is always comparing `CFBundleVersion`. The short version string is only for display to users and could be like 95, 98, 2000, xp, 7, …

**Comment by Shasoosh** [comment]
Thanks for the reply. 

Is this documented anywhere? I read most of the docs and still banged my head around this yesterday.
