### ISSUE TITLE
Sparkle refuses updates compressed using Path Finder

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#104]
_**Eightt Software (0-software)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/798480) on' 2011-06-17:*

This specific incompatibility hints at Sparkle's pickiness about update
archive formats. I recently released an update according to all the
standard protocols, and light tests indicated all was well. Users,
though, began complaining that they were getting "Improperly Signed"
errors. I traced this down to the fact that the most recent update was
compressed using Path Finder (http://www.cocoatech.com/) rather than
Apple's Finder; I re-rolled the application using the Finder, and all
was well.

Interestingly, both files--the dysfunctional Path Finder one and the
functional Finder one--were supposedly vanilla .zip files. When Path
Finder compresses, it shows a little "Powered by StuffIt™" notice at the
bottom, though I'm not sure how that should invalidate the update.

In case you're interested in investigating the problem, my appcast is at
    http://fountainpen.sourceforge.net/versioninfo/sparkle.xml

The original, inoperative Path Finder package can be found at
    http://fountainpen.sourceforge.net/update/Leland-PathFinder0.7.1.zip
With the DSA sig. that should have worked:
    MC4CFQC8qAvDwGV0bhzxLiAVa8Nk7SoIpAIVAJ/fZljiGFifAP5vePVXaS2j5zZU

And the new, Finder-compressed package is at
    http://fountainpen.sourceforge.net/update/Leland-FP0.7.1.zip

Again, my specific issues have been resolved, but this is an interesting
oddity.

**Comment by pornel** [comment]
We support only zip files that the system unzip tool supports.
