### ISSUE TITLE
Touch ID support

### ISSUE THREAD

**Issue by adrianthomas** [sparkle-project/Sparkle#1040]
We use Sparkle to update our app and the process needs admin privileges for… reasons.
If you run Apple's Installer directly, it can use Touch ID to fetch the admin authorization, but as Sparkle fetches root first and then runs the installer, you don't get the nice Touch ID magic.

Would it be possible to change that behaviour so users can authorize with Touch ID in those cases?

(Apologies for the lack of specificity, product manager not developer here :) )

Thanks!
![screen shot 2017-02-22 at 17 44 11](https://cloud.githubusercontent.com/assets/388183/23222081/1a81ca40-f927-11e6-8658-407e390f2b46.png)

**Comment by pornel** [comment]
Does that work with headless installers too, or only the GUI ones?

If you use [*.sparkle_interactive.pkg](https://sparkle-project.org/documentation/package-updates/), do you get the desired effect?

**Comment by Cyberbeni** [comment]
https://developer.apple.com/forums/thread/106386

Apple checks for code signature and only allows Touch ID for binaries signed by Apple. IIRC using NSTask to do the same thing through CLI will allow the usage of Touch ID but will display a different app name. (for example osascript if you want to run an applescript with admin priviliges)

**Comment by zorgiepoo** [comment]
This needs proper support from Apple in the Authorization framework, not something that only works with Apple signed binaries. And for non pkg installs needing authorization too.
