### ISSUE TITLE
Failed to change owner & group authorization tool error

### ISSUE THREAD

**Issue by dokterdok** [sparkle-project/Sparkle#1043]
We're getting the following error randomly (about 50% of the time) after the update is downloaded, extracted, and asked for privileges: "Failed to change owner & group on <our app.app> to match <our app.app> with authorization" (see screenshot). The update doesn't complete and disappears after that. Running the auto-update again usually works fine, which is puzzling. Any ideas?

![image](https://cloud.githubusercontent.com/assets/5354424/23329414/1f16f9b4-fb38-11e6-85a1-e072f20ce43a.png)

By digging into the console output, it seems that Sparkle fails to run its auth tool:

`default	15:36:19.947114 +0100	Autoupdate	PID to listen: 5339`

`default	15:36:23.837088 +0100	authd	Succeeded authorizing right 'system.privilege.admin' by client '/Users/ddewit/Library/Caches/ch.tripmode.TripMode/org.sparkle-project.Sparkle/Autoupdate.app' [5368] for authorization created by '/Users/ddewit/Library/Caches/ch.tripmode.TripMode/org.sparkle-project.Sparkle/Autoupdate.app' [5368] (13,0)`

`error	15:36:23.838957 +0100	Autoupdate	Failed to change owner and group of new app at /var/folders/v4/y1wdn6m13psd4cgpllvxx95m0000gn/T/TemporaryItems/(A Document Being Saved By Autoupdate)/TripMode.app to match old app at /Applications/TripMode.app`

`error	15:36:23.947574 +0100	Autoupdate	Failed to perform final installation Error: Error Domain=SUSparkleErrorDomain Code=4001 "Failed to change owner & group on TripMode.app to match TripMode.app with authorization." UserInfo={NSLocalizedDescription=Failed to change owner & group on TripMode.app to match TripMode.app with authorization., NSUnderlyingError=0x7fb4e8c4a210 {Error Domain=SUSparkleErrorDomain Code=4001 "Failed to run authorization tool." UserInfo={NSLocalizedDescription=Failed to run authorization tool.}}}`

Sources reference:
https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/SUFileManager.m#L749
https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/SUPlainInstaller.m#L115 (this is the if to patch)

**Comment by pornel** [comment]
I've added a bit more info to the error in e54748ac87377321e6a264e5cc407fdda9ceb1f0

I'm not sure what's going on here. Is it some race condition? Is it possible for `chown` to be flaky? If we ignore this error, will it leave the update in a broken state with invalid permissions?

I haven't seen this happen before. How is your app different? What format do you use for distributing updates?

**Comment by kjsakata** [comment]
@dokterdok 

I got same problem and error message when installed from Pkg and running.
You also using Pkg and postinstall script "open /Applications/Xxx.app"?

**Comment by gnachman** [comment]
I'm getting bug reports from users where the cause is that my document bundle is under "A Document Being Saved By Autoupdate". When it's in that location some kind of security check fails and I can't fork & exec. If anyone has a clue what might be going on I would love to know.

**Comment by zorgiepoo** [comment]
The change owner / group issue shouldn't bring up an auth dialog or be hard failure in Sparkle 2. The path should never be hit for pkg updates.

Sparkle uses "A Document Being Saved By Autoupdate" temporary directories before moving the updated app to its final destination, but should never run the app from the temporary location, but sounds like a different issue.
