### ISSUE TITLE
Always silently update

### ISSUE THREAD

**Issue by arsenik** [sparkle-project/Sparkle#1047]
I have a Cocoa app. 

I would like to never display (even at first run) the Software Update window and always download and install new release of my app.

With this config, I still get at first run the Software Update window. Do I miss an option?

Info.list
```
SUEnableAutomaticChecks = YES
SUScheduledCheckInterval = 3600
SUAllowsAutomaticUpdates = NO
```

AppDelegate.swift
```
func applicationDidFinishLaunching(_ aNotification: Notification)  {
    SUUpdater.shared().automaticallyDownloadsUpdates = true
    ....
}
````

**Comment by arsenik** [comment]
Just found ```installUpdatesIfAvailable``` , it downloads and installs the new version. 
Now I have,

Info.list
```
SUEnableAutomaticChecks YES
SUAllowsAutomaticUpdates YES
```
AppDelegate.swift
```
func applicationDidFinishLaunching(_ aNotification: Notification)  {
    SUUpdater.shared().automaticallyDownloadsUpdates = true
    SUUpdater.shared().installUpdatesIfAvailable()
    ....
}
```

1. Update and Install are not silent, an update window is showing progress. Any option to make silent?

2. After installed is completed, a window asks "Check for update automatically?" I thought ```SUAllowsAutomaticUpdates YES``` will not trigger this. Any way to not ask the user?

**Comment by pornel** [comment]
Please avoid using `installUpdatesIfAvailable`. That function is a really bad hack. We shouldn't have added it :(

The behavior you want is built-in into normal operation of Sparkle. Set `SUAutomaticallyUpdate` to `YES` in `Info.plist`.

**Comment by arsenik** [comment]
How would I update on start up without using calling ```installUpdatesIfAvailable```? 

I tried the following, but not sure if I to wait 1 hour to get the app updated automatically without user action.

```
SUEnableAutomaticChecks = YES
SUScheduledCheckInterval = 3600
SUAutomaticallyUpdate = YES
```

```
func applicationDidFinishLaunching(_ aNotification: Notification)  {
    SUUpdater.shared().automaticallyDownloadsUpdates = true
    SUUpdater.shared().automaticallyChecksForUpdates = true
    ....
}
```

**Comment by pornel** [comment]
Once `SUEnableAutomaticChecks ` is enabled, Sparkle makes a check on startup by default. The interval is since last check, not since last startup.

**Comment by pornel** [comment]
BTW, last actions and everything you change programmatically are set in `NSUserDefaults`, so you may want to clear them if you want to re-test fresh start.

**Comment by arsenik** [comment]
Thanks Pornel, it does not work still. Maybe I am not writing something correcly or maybe it is this ```NSUserDefaults``` I am not familiar with. 
Is it something I need to clear on my building machine prior making a new build? I am changing SUFeedURL in Info.plist but change is never reflected in appcast.xml generated with command generate_appcast. Is it linked to ```NSUserDefaults```?

**Comment by pornel** [comment]
If you set feed URL via `SUUpdater`, it will be saved in user defaults and Info.plist will be ignored.

**Comment by arsenik** [comment]
This is unrelated to silent install , but since we talk about NSUserDefaults : 
I use ```./generate_appcast key_dir/ update_dir/ ```
update_dir contains the DMG I just build and which has in Info.plist SUFeedURL a new URL. 
It creates an appcast.xml with an old enclosure URL. 
Is that something to do with NSUserDefaults?

**Comment by pornel** [comment]
`generate_appcast` doesn't use NSUserDefaults. It reads everything from `Info.plist`. Enclosure URL is based on URL of `SUFeedURL` in `Info.plist`.

**Comment by mdhari** [comment]
Just to confirm, the "Silent Update" feature is downloading the next update in background with the app's current session, but the new update doesn't get used unless the user explicitly closes and reopens the app correct? If the user typically doesn't turn off their machine or close the app, then the update never actually happens?

**Comment by pornel** [comment]
Yes. The update is never installed while the app is running, because that would break the running app.

**Comment by arsenik** [comment]
On a fresh machine, I run my app which has a version lower than the last version on the update server. 
Info list has
```
SUAutomaticallyUpdate Boolean YES
SUEnableAutomaticChecks Boolean YES
SUScheduleCheckInterval Number 3600
SUPublicDSAKeyFile String xxx.pem
SUFeedURL String https://domain.com/appcast.xml
```
When the app runs for the fist time I get this window : 
**A new version of xxx is available!**
xxx 1.3 is now available-you have 1.2. Would you like to download it now? 
[Skip this version] [Remind Me Later] [Install Update]

I don't want to show any update window, SUAutomaticallyUpdate was supposed to install the update in the background?

**Comment by pornel** [comment]
Sorry, I was mistaken and there's a bug in the documentation. `SUAutomaticallyUpdate` still requires user to opt-in via checkbox in the update alert. 

I'll fix that in the next release.

**Comment by arsenik** [comment]
How would I not show this window at all without the hack with installUpdatesIfAvailable() ?

**Comment by pornel** [comment]
You'd have to change Sparkle's code `- (BOOL)automaticallyDownloadsUpdates` to always return `NO`
or override user preference:

```objc
[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"SUAutomaticallyUpdate"]
```

**Comment by arsenik** [comment]
```SUAutomaticallyUpdate Boolean	Default: NO.```

Enables automatic download and installation of updates. If set to YES, users will not be informed about updates, and updates will be silently installed when the app quits.

If my app terminates itself by calling ```exit(0)``` (swift3) , the update is supposed to occur?

**Comment by pornel** [comment]
No. Sparkle supports only graceful termination via Cocoa notification.

**Comment by arsenik** [comment]
does ```NSApplication.shared().terminate(self)``` is considered graceful?

**Comment by pornel** [comment]
Yes, Cocoa's terminate should be fine.

**Comment by pornel** [comment]
For a short-running background app it may be better to force installation (`installUpdatesIfAvailable`), since auto install will run only if it had enough time to prepare the installation.

**Comment by arsenik** [comment]
Thanks, I do see now the app connecting to the webserver and getting the next version of the app. All that silently.

The app is stopped, I check the version with Get Info but new version is not installed. 
(The app is in /Applications)

Is there some log I can turn on to debug the install?

**Config**

LSBackgroundOnly YES
SUPublicDSAKeyFile dsa_pub.pem
SUFeedURL https://mydomain.com/app/appcast.xml

```
func applicationDidFinishLaunching(_ aNotification: Notification) {
	UserDefaults.standard.set(true, forKey: "SUAutomaticallyUpdate")
	UserDefaults.standard.synchronize()
	SUUpdater.shared().automaticallyDownloadsUpdates = true
	SUUpdater.shared().automaticallyChecksForUpdates = true
	...
	NSApplication.shared().terminate(self)
}
```

**Comment by pornel** [comment]
If there's any logged information, it will be in Console.app.

**Comment by arsenik** [comment]
Do you see anything suspicious?

```
default	02:35:58.142169 -0700	myapp	Failed to connect (window) outlet from (myapp.AppDelegate) to (NSWindow): missing setter or instance variable
default	02:35:58.387742 -0700	myapp	Faulting in NSHTTPCookieStorage singleton
default	02:35:58.387826 -0700	myapp	Faulting in CFHTTPCookieStorage singleton
default	02:35:58.387871 -0700	myapp	Creating default cookie storage with process/bundle identifier
default	02:35:58.414461 -0700	myapp	UNIX error exception: 17
default	02:35:58.415712 -0700	myapp	0x60000027d040 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	02:35:58.418064 -0700	myapp	UNIX error exception: 17
default	02:35:58.419515 -0700	myapp	UNIX error exception: 17
default	02:35:58.420679 -0700	myapp	UNIX error exception: 17
default	02:35:58.422076 -0700	myapp	UNIX error exception: 17
default	02:35:58.422963 -0700	myapp	UNIX error exception: 17
default	02:35:58.424323 -0700	myapp	0x600000460140 opened /Users/julien/Library/Keychains/login.keychain-db: 116684 bytes
default	02:35:58.448550 -0700	myapp	0x600000462680 opened /Library/Keychains/System.keychain: 33888 bytes
default	02:35:58.464834 -0700	myapp	TIC TCP Conn Start [1:0x60800018dc30]
default	02:35:58.507153 -0700	myapp	TIC TCP Conn Event [1:0x60800018dc30]: 1 Err(0)
default	02:35:58.507496 -0700	myapp	TIC TCP Conn Connected [1:0x60800018dc30]: Err(0)
default	02:35:58.507867 -0700	myapp	TIC Enabling TLS [1:0x60800018dc30]
default	02:35:58.535894 -0700	myapp	TIC TLS Event [1:0x60800018dc30]: 2, Pending(0)
default	02:35:58.537180 -0700	myapp	TIC TLS Event [1:0x60800018dc30]: 11, Pending(0)
default	02:35:58.537909 -0700	myapp	UNIX error exception: 17
default	02:35:58.538574 -0700	myapp	UNIX error exception: 17
default	02:35:58.539855 -0700	myapp	TIC TLS Event [1:0x60800018dc30]: 12, Pending(0)
default	02:35:58.539954 -0700	myapp	TIC TLS Event [1:0x60800018dc30]: 14, Pending(0)
default	02:35:58.553403 -0700	myapp	TIC TLS Trust Result [1:0x60800018dc30]: 0
default	02:35:58.641171 -0700	myapp	TIC TLS Event [1:0x60800018dc30]: 20, Pending(0)
default	02:35:58.642662 -0700	myapp	TIC TCP Conn Event [1:0x60800018dc30]: 8 Err(0)
default	02:35:58.643173 -0700	myapp	TIC TLS Handshake Complete [1:0x60800018dc30]
default	02:35:58.745584 -0700	myapp	TIC TCP Conn Start [2:0x6000001905a0]
default	02:35:58.791471 -0700	myapp	TIC TCP Conn Event [2:0x6000001905a0]: 1 Err(0)
default	02:35:58.791527 -0700	myapp	TIC TCP Conn Connected [2:0x6000001905a0]: Err(0)
default	02:35:58.791788 -0700	myapp	TIC Enabling TLS [2:0x6000001905a0]
default	02:35:58.825057 -0700	myapp	TIC TLS Event [2:0x6000001905a0]: 2, Pending(0)
default	02:35:58.825192 -0700	myapp	TIC TLS Event [2:0x6000001905a0]: 11, Pending(0)
default	02:35:58.825840 -0700	myapp	TIC TLS Event [2:0x6000001905a0]: 12, Pending(0)
default	02:35:58.825887 -0700	myapp	TIC TLS Event [2:0x6000001905a0]: 14, Pending(0)
default	02:35:58.974029 -0700	myapp	TIC TLS Trust Result [2:0x6000001905a0]: 0
default	02:35:59.093244 -0700	myapp	TIC TLS Event [2:0x6000001905a0]: 20, Pending(0)
default	02:35:59.101429 -0700	myapp	TIC TCP Conn Event [2:0x6000001905a0]: 8 Err(0)
default	02:35:59.101859 -0700	myapp	TIC TLS Handshake Complete [2:0x6000001905a0]
````

**Comment by arsenik** [comment]
I tried also without ```SUUpdater.shared().installUpdatesIfAvailable()``` but can't see any ```Autoupdate``` process in Console.app. 
The new dmg (which is signed) is being downloaded but that's it.

**Comment by pornel** [comment]
Does your code signing work correctly? "UNIX error exception: 17" is a  security exception.

**Comment by arsenik** [comment]
I think so, I let xcode sign the app , then I create a dmg which I sign with the same Developer ID xcode is using. 

Then I generate the appcast.

Both app and dmg tested with ```codesign ---depp -vvvv``` 
Result is ```valid on disk``` and ```satisfies its Designated Requirement```


I signed DMGs with ```codesign --force --sign "Developer ID Application: XXXX YYY (ZZZZ)" 0.1.dmg```

I also remove delta entries from appcast.xml just so I am sure it downloads the 0.2.dmg which is signed.

There is one thing I am not sure about and I don't know where to verify is this from the doc: 

> Note that embedding the Sparkle.framework into the bundle of a Developer ID application requires that you code-sign the framework with your Developer ID keys. Xcode should do this automatically if you let it “Code Sign on Copy” Sparkle’s framework.

**Comment by arsenik** [comment]
So I tried RB AppCheckerLite and found that myapp.app is signed correctly , Sparkle.framework as well signed correcly with the same Identity than myapp.app.

BUT it founds on Sparkle.framework, 2 auxiliary executables unsigned which are  
```
Autoupdate.app/
Autoupdate.app/Contents/MacOS/fileop
```
I will try to sign these and let you know.

**Comment by arsenik** [comment]
I don't need to run ```sign_update```, ```generate_appcast``` is signing  the update (dmg) right?

**Comment by arsenik** [comment]
So the problem is not signature. 
I tested with

```
SUAutomaticallyUpdate Boolean YES
SUEnableAutomaticChecks Boolean YES
SUScheduleCheckInterval Number 3600
SUPublicDSAKeyFile String xxx.pem
SUFeedURL String https://domain.com/appcast.xml
```
And with empty app which does not terminate (for update testing) 
```
func applicationDidFinishLaunching(_ aNotification: Notification) {
	if let appDomain = Bundle.main.bundleIdentifier {
		UserDefaults.standard.removePersistentDomain(forName: appDomain)
	}
}
```
I got the popup asking to install, I click ok install and relaunch, the new version is installed. 

So now, yes my app is short lived like 5 seconds and is a background app. The user has no interactions with it.

So I tried the following: tell the app to automatically update, wait 30 sec and terminate. 
```
func applicationDidFinishLaunching(_ aNotification: Notification) {
	if let appDomain = Bundle.main.bundleIdentifier {
		UserDefaults.standard.removePersistentDomain(forName: appDomain)
	}
	UserDefaults.standard.set(true, forKey: "SUAutomaticallyUpdate")
	sleep(30) // long enough to let app prepare the update
	...
	NSApplication.shared().terminate(self)
}
```

I was expecting to see at least a call to appcast.xml on first start. ( but did not happened)
I was expecting then at second start the update to happen. (but it did not)


Then I tried the following: force install , wait 30 seconds for install to complete and terminate
```
func applicationDidFinishLaunching(_ aNotification: Notification) {
	if let appDomain = Bundle.main.bundleIdentifier {
		UserDefaults.standard.removePersistentDomain(forName: appDomain)
	}
	SUUpdater.shared().installUpdatesIfAvailable()
	sleep(30) // long enough to let app prepare the update
	...
	NSApplication.shared().terminate(self)
}
```

But nothing happened, the app started, 30 sec later terminates.

I am not sure sleep is good solution to let the  auto install enough time to prepare installation. Maybe it is just blocking everything including autoupdate app. 
But why did I not see any call to the webserver in both cases?

**Comment by arsenik** [comment]
HA! it works now, I had to delay terminate. The app was terminating too fast. 

_Swift 3 cocoa app UI-less_
```
SUAutomaticallyUpdate Boolean YES
SUEnableAutomaticChecks Boolean YES
SUScheduleCheckInterval Number 3600
SUPublicDSAKeyFile String xxx.pem
SUFeedURL String https://domain.com/appcast.xml


func applicationDidFinishLaunching(_ aNotification: Notification) {
	if let appDomain = Bundle.main.bundleIdentifier {
		UserDefaults.standard.removePersistentDomain(forName: appDomain)
	}

	UserDefaults.standard.set(true, forKey: "SUAtomaticallyUpdate")
	SUUpdater.shared().automaticallyDownloadsUpdates = true
	SUUpdater.shared().automaticallyChecksForUpdates = true

	.....

	self.perform(#selector(callTerminate), with: nil, afterDelay: 30.0)
}

func callTerminate() {
	NSApplication.shared().terminate(self)
}
```

Thanks for the support @pornel!

**Comment by pornel** [comment]
Great you've got it!

In general the problem was that you never allowed your app to properly start, because you did not return from `applicationDidFinishLaunching`. AFAIK `sleep()` and any other synchronous blocking call will block the event loop and prevented background downloads from running.

**Comment by mixtly87** [comment]
> 

@arsenik  There's a spelling error here? You typed `SUAtomaticallyUpdate` when `SUAutomaticallyUpdate` is expected. And did it work for you with mispelled term?

**Comment by zorgiepoo** [comment]
Use the Info.plist key for `SUAutomaticallyUpdate` [as per documentation](https://sparkle-project.org/documentation/customization/).

This thread is rather old and has outdated information. Sparkle 2 supports any type of termination. Don't use NSUserDefaults directly. Prefer to use info.plist keys for initial behavior over methods on the updater instance, which should only be used for dynamic changes.
