### ISSUE TITLE
SUFileManager.m warning with 1.17.0

### ISSUE THREAD

**Issue by kainjow** [sparkle-project/Sparkle#1053]
With 1.17.0 I get this warning now:

> /Sparkle/Sparkle/SUFileManager.m:173:162: warning: using %s directive in NSString which is being passed as a formatting argument to the formatting method [-Wcstring-format-directive]

Looks like it was introduced with e54748ac87377321e6a264e5cc407fdda9ceb1f0.

**Comment by kainjow** [comment]
Looks like converting to an NSString fixes it:

    *error = [NSError errorWithDomain:SUSparkleErrorDomain code:SUAuthenticationFailure userInfo:@{ NSLocalizedDescriptionKey:[NSString stringWithFormat:@"Failed to run authorization tool %@ (%d).", [NSString stringWithUTF8String:toolPath], (int)runStatus] }];

I found this, seems like %s in NS format strings is deprecated? https://reviews.llvm.org/rL217467

**Comment by pornel** [comment]
I'd rather silence the error, because the formatting string is not a mistake, and it does exactly what it's supposed to.
