### ISSUE TITLE
The update will be rejected

### ISSUE THREAD

**Issue by raheem52** [sparkle-project/Sparkle#1054]
I am using Xamarin to make a MAC application.
Ihave signed old built and new build and included public in both.
But still i receive error  "The update archive isn't signed with a DSA key, and the old app hasn't been signed with app Code Signing. At least one method of signature verification must be valid. The update will be rejected"

**Comment by pornel** [comment]
It is exactly what it says - you don't have DSA signature, and don't have code signing.

Please go through the docs security section and implement DSA signatures: https://sparkle-project.org/documentation/

**Comment by raheem52** [comment]
I have dsa_pub.pem in Resource folder and SUDSAPublicKeyFile as dsa_pub.pem in info.plist.
Then i use ditto command to generate a zip with my MyApp.app.
Then I use ./bin/generate_appcast to genrate a xml file for server.
Then i upload both zip and xml file to server.
When trying to update, it gave me error “Could not read public DSA key”.

**Comment by pornel** [comment]
That's good, but you also need to put the signature in the appcast. You can use generate_appcast tool to do that for you, or sign_appcast to do manually.

**Comment by raheem52** [comment]
I have used ./bin/generate_appcast /path/to/your/dsa_priv.pem /path/to/your/updates_folder/

It gives a xml file which has dsaSignature="SOMERANDOMSTRING", I am uploading this xml to server also. Now I am not sure why I have “Could not read public DSA key”.

**Comment by pornel** [comment]
Oh, so that should work. Do you see more Sparkle errors in Console.app?

**Comment by pornel** [comment]
You've mentioned you have `SUDSAPublicKeyFile` key, but the name is `SUPublicDSAKeyFile`.

**Comment by raheem52** [comment]
That did the trick pornel .. thanks alot, was scratching my head over it from two days :)
