### ISSUE TITLE
does not correctly percent-encode custom profile fields in the URL

### ISSUE THREAD

**Issue by jeromectm** [sparkle-project/Sparkle#1059]
when adding parameters containing an & character to [SUUpdaterDelegate feedParametersForUpdater:sendingSystemProfile:], the URL is not correctly percent-encoded.

Proposed change for [SUUpdater parameterizedFeedURL:]:

    for (NSDictionary *currentProfileInfo in parameters) {
        // characters allowed in a single parameter key or value = characters allowed in the query, less = ? &
        #if 0
            // requires macOS 10.9
            NSMutableCharacterSet *allowedCharacters=[[NSCharacterSet URLQueryAllowedCharacterSet] mutableCopy];
		    [allowedCharacters removeCharactersInString:@"=?&"];
            [parameterStrings addObject:[NSString stringWithFormat:@"%@=%@", [[[currentProfileInfo objectForKey:@"key"] description] stringByAddingPercentEncodingWithAllowedCharacters:allowedCharacters], [[[currentProfileInfo objectForKey:@"value"] description] stringByAddingPercentEncodingWithAllowedCharacters:allowedCharacters]]];
        #else
            NSString *key=[[[currentProfileInfo objectForKey:@"key"] description] stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
            key=[key stringByReplacingOccurrencesOfString:@"=" withString:@"%3d"];
            key=[key stringByReplacingOccurrencesOfString:@"?" withString:@"%3f"];
            key=[key stringByReplacingOccurrencesOfString:@"&" withString:@"%26"];
            NSString *value=[[[currentProfileInfo objectForKey:@"value"] description] stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding];
            value=[value stringByReplacingOccurrencesOfString:@"=" withString:@"%3d"];
            value=[value stringByReplacingOccurrencesOfString:@"?" withString:@"%3f"];
            value=[value stringByReplacingOccurrencesOfString:@"&" withString:@"%26"];
            [parameterStrings addObject:[NSString stringWithFormat:@"%@=%@", key, value]];
        #endif
    }

**Comment by pornel** [comment]
Please try  89acca1 and see if it works for you

**Comment by jeromectm** [comment]
You're true, ? does not need to be encoded; however, it seems that + should, or it will be translated to a space on the other side. So escapeURLComponent would be:

static NSString *escapeURLComponent(NSString *str) {
    return [[[[str stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]
             stringByReplacingOccurrencesOfString:@"=" withString:@"%3d"]
             stringByReplacingOccurrencesOfString:@"&" withString:@"%26"]
             stringByReplacingOccurrencesOfString:@"+" withString:@"%2b"];
}

**Comment by pornel** [comment]
Good point. Fixed.
