### ISSUE TITLE
Code signing - macOS Sierra - Xcode 8.3

### ISSUE THREAD

**Issue by bryanc-nz** [sparkle-project/Sparkle#1060]
I checked my app with RB App Checker Lite and found that the Autoupdate application embedded in the Sparkle framework (1.17.0) remains unsigned.

Yes - I do have codesign on copy checked in Xcode

Is this a bad thing?
If so - what do I need to do to correct it.

**Comment by pornel** [comment]
It's OK for it to be unsigned. See discussion: #546 #822
