### ISSUE TITLE
Debugging Sparkle

### ISSUE THREAD

**Issue by sinosoidal** [sparkle-project/Sparkle#1065]
Hi,

I was using a really old version of Sparkle and now I'm trying to catch the train and use the latest. My project is not Xcode based. Instead I use a Qt project and the SUUpdater is encapsulated inside a SparkleAutoUpdater class. This used to work.

Using the latest version, the code compiles fine and the checkForUpdatesInBackground is being called. However I don't have any kind of feedback on console output, Console.app or update prompt. I'm in a complete darkness.

How can I have more info of what is going on so that I can fix this issue and use the latest version of Sparkle?

Attached are the C++ wrappers.

**Comment by pornel** [comment]
We've changed logging to use the new `os_log` or ASL:

https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/SULog.m

You could try editing that file and use something else instead.

**Comment by sinosoidal** [comment]
What do you mean by using something else instead? I'm just trying to find out more information on why I don't have any kind of information. I'm not looking for implementing a new log backend. How do I defined the log level? Where should I look for log output? Thx

**Comment by pornel** [comment]
I mean if Qt has its own logging facility, you could try using that. Or try using NSLog. Or use breakpoints and step in debugger.

I'm not familiar with Qt. @jakepetroules should be able to help.

**Comment by sinosoidal** [comment]
Ok, I understand but imagine that I have a normal Xcode application. How can I ensure that Sparkle is fetching the appcast and doing something? Because right now I can't see nothing and I'm completely in the dark. Where should I start my debug in this situations?

**Comment by pornel** [comment]
In a normal Xcode application you get lots of logging, which is visible in both Xcode's debug log as well as via Console.app.

**Comment by jakepetroules** [comment]
I'm not sure why you're not seeing log output. This shouldn't really have anything to do with Qt. What version of macOS, what version of Qt, and can you attach your project somewhere or at least a minimal example project which reproduces the problem?

**Comment by sinosoidal** [comment]
Thanks for your reply. I will try to make a minimal example. I find it weird also. I will get back here ASAP.

**Comment by sinosoidal** [comment]
I have made a small isolated example and it prompted the update to the new version. I guess the problem lies somewhere in my app. I need to investigate it further.
