### ISSUE TITLE
Cannot read file with dsa key

### ISSUE THREAD

**Issue by alexuaua** [sparkle-project/Sparkle#1066]
I've updated Sparkle from 1.13 to latest build,  and found that each time I call checkForUpdates: the error is displayed - For security reasons, the file "dsa_pub.pem" indicated by the 'SUPublicDSAKeyFile' key needs to exist in the bundle's Resources.
I've double checked the app bundle - dsa_pub.pem is present in the Resources. Tried to remove and add again (+ checked the BuildPhases, to verify that the file is copied) - same issue. When I do `[[NSBundle mainBundle] pathForResource:@"dsa_pub.pem" ofType:nil];` in my code it returns the path without any issue. Just in case, I've removed the framework and added it again, no luck.
When I simply replace the framework in the bundle with older versions - everything works ok.

While I'm trying to debug the publicDSAKey function in SUHost to figure out if the issue may be relate to getting the bundle path, I wonder if something changed for the DSA file format?

**Comment by pornel** [comment]
The message pops up because we can't find the info.plist `SUPublicDSAKeyFile` key (we get `nil` when we read it)

**Comment by pornel** [comment]
Is it possible that you have `SUPublicDSAKey` (not `SUPublicDSAKeyFile`) in your plist?

**Comment by pornel** [comment]
Uh, that error case is more complex than I initially thought. The code is here:

https://github.com/sparkle-project/Sparkle/blob/629c42d62d45edf8ec6fdefc2ee4fd2541ffabb8/Sparkle/SUUpdater.m#L138,L147

So somehow we see your plist key, but can't load the file. Is the file empty? Does it have non-ASCII text?

**Comment by alexuaua** [comment]
@pornel thanks for so prompt reply, in my plist I have:
`<key>SUFeedURL</key>
	<string>SU_URL</string>
	<key>SUPublicDSAKeyFile</key>
	<string>SU_PUBLIC_KEY</string>`
Where the last two variables are defined as 
        #define SU_URL "https://....."
        #define SU_PUBLIC_KEY "dsa_pub.pem"
And compiled bundle has following plist
`<key>SUFeedURL</key>
	<string>"https://"</string>
	<key>SUPublicDSAKeyFile</key>
	<string>"dsa_pub.pem"</string>`

But I've found that when I replace 
`        #define SU_PUBLIC_KEY "dsa_pub.pem"` with `        #define SU_PUBLIC_KEY dsa_pub.pem` (i.e. remove double quotes), everything now works ok. So I think it is mine issue, while version 1.13 worked ok with quotes (and I suppose I just took double quotes from some example). I only not sure if I should leave quotes in the the URL, but so far everything is ok, so sorry for bothering.

**Comment by pornel** [comment]
OK, no problem.
