### ISSUE TITLE
 Freezes on “Installing update…”

### ISSUE THREAD

**Issue by Meniny** [sparkle-project/Sparkle#1068]
check for updates->downloading->installing updates...
and the installing step never get done.

**Comment by kornelski** [comment]
Please check Console.app for more information about the install progress.

**Comment by wangshugaung** [comment]
Thank you! I found the error using Console. App.

**Comment by kornelski** [comment]
Is there anything more after that?

Quarantine failures generally aren't a problem.

**Comment by wangshugaung** [comment]
Except for this error, there is no other output in console. App.
e.g，I used version 1.19。I signed it with dsa and my.app signed it。

**Comment by kornelski** [comment]
Other options:

* Attach debugger and see what Sparkle is doing

* Try another archive format (in case it freezes during decompression)

**Comment by wangshugaung** [comment]
I'm going to compress the.app into.zip is that a problem?

**Comment by kornelski** [comment]
App bundle in a ZIP file generally works fine.

**Comment by wangshugaung** [comment]
Yeah, My application uses a sandBox. I closed the sandbox works fine. I use sndbox and I should refer to that document？Thank You @kornelski .

**Comment by kornelski** [comment]
Oh, that's a very different thing. Are you using Sparkle 2.0? 1.x doesn't work in sandboxed applications.

**Comment by wangshugaung** [comment]
I’m sorry! I using sparkle 1.19. So I change to sparkle 2.0.

**Comment by kornelski** [comment]
Yes. It's in this branch:

https://github.com/sparkle-project/Sparkle/tree/ui-separation-and-xpc
