### ISSUE TITLE
Is there a process for changing the DSA key?

### ISSUE THREAD

**Issue by kainjow** [sparkle-project/Sparkle#1070]
I help maintain an app where the Sparkle private key was generated years ago and is apparently lost (and was never really used). I am able to generate a new private key going forward, but my understanding is this will only work for users who use the app that contains the new public key. Users using the older version will not be able to auto-update.

Is the best way to handle this is to just inform users in the release notes that are using the version with the old key that they'll have to manually update?

**Comment by pornel** [comment]
You can change the DSA key if Apple Code Signing identity matches.

**Comment by kainjow** [comment]
But if the DSA key is set in the Info.plist, won't it always try to validate against that? Or, can I leave out the dsa key in the appcast and it will skip it?

**Comment by pornel** [comment]
You can never have half-broken DSA. If you add a key, but don't sign the update, we'll always reject it.

But you can have fully properly integrated DSA with correct signature. In that case we'll allow different key, as long Code Signing is also correct and matches.

**Comment by kainjow** [comment]
OK, got it. Thanks!
