### ISSUE TITLE
Removing "Remind me Later" Button for Critical Update

### ISSUE THREAD

**Issue by gsrinivasanbjn** [sparkle-project/Sparkle#1073]
We have a minimum version of our application and would like to disable the "Remind Me Later" in addition to the "Skip this update" button. It doesn't seem to be  part of the effects from setting <sparkle:criticalUpdate/>. 

Is this behavior possible? 

Thank you so much!

**Comment by pornel** [comment]
There's no such option currently. I suppose it would make sense to add it. Could you make a pull request with the change?

**Comment by kennethjohnsen** [comment]
We have the same requirement.
I guess I could make a pull request.
Would it be OK to make it as two new entries in info.plist, where you can set YES or NO for enabling/disabling each button?

Just note that it's still possible to just close the window by clicking the red dot in the titlebar of the window.

**Comment by kornelski** [comment]
Thanks for offering the PR.

I think it's fine if it's a hardcoded behavior. We trust when developer says it's critical, it really is.

**Comment by kennethjohnsen** [comment]
I have created PR #1480 for this.
