### ISSUE TITLE
Support for new EULA?

### ISSUE THREAD

**Issue by drootang** [sparkle-project/Sparkle#1074]
Is there a way to ensure that the user sees there is an updated EULA for the application prior to updating? 

The only option I can see is to embed the release notes in the update dialog and clearly state there that there is a EULA update with the new version. However, automatic updates would bypass this completely

**Comment by pornel** [comment]
No, we don't have support for such things. I recommend building it into the application, e.g. make the app show EULA on startup and set preference key when it's accepted. This way both automatic and manual update will show it.

**Comment by drootang** [comment]
Thank you for the fast response. Your recommendation is my current approach, but it is not ideal since the application is already upgraded by the time the user sees the new EULA. If the user does not agree they may need to downgrade to access documents stored in the application, for example.

The problem is certainly mitigated by a clear warning in embedded release notes, so the only corner case is a user auto-updating. A parameter in the appcast to prevent auto-update for a specific version number seems the simplest enhancement.

**Comment by pornel** [comment]
Yes, I'm thinking about adding something like that: #961
