### ISSUE TITLE
App can't install new updates

### ISSUE THREAD

**Issue by OscarSwanros** [sparkle-project/Sparkle#1077]
The app I'm working on seems to have lost the ability to install new updates.

This is what's showing on the Console.app: 

```
Couldn't copy relauncher ((null)) to temporary path ((null))!  (URL (null))
```

I've ran out of ideas. Any pointers would be greatly appreciated. The version that's running the updater is using Sparkle 1.17.

**Comment by pornel** [comment]
It looks like there's something very broken with your app bundle or the framework. I've added more logging in 1.18.0b1 that should help pinpoint the cause. Please try it.

**Comment by OscarSwanros** [comment]
Thanks @pornel, I'll try it out and report back.

**Comment by endore8** [comment]
Hi @OscarSwanros ,
I've run into the same problem, and not sure how to fix it. Did you solve it for yourself?

**Comment by kornelski** [comment]
If you're a user of an app that displays such error, then you have to manually download a new version of the app from the app's website.

If you're a developer, you need to upgrade Sparkle.framework to a not-so-outdated 1.x version (this bug has been fixed **years ago**).
