### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by overtake** [sparkle-project/Sparkle#1083]
Hey, how to choose custom localization? i didn't found  the way for choose custom localization when app is running.

**Comment by pornel** [comment]
Localization in Sparkle is 100% handled by macOS. We don't choose languages, macOS does it for us. If you want to change Sparkle's language, you must make macOS change it.

You can add new languages to the project by creating *.lproj directory and adding resources to Xcode project file.

**Comment by overtake** [comment]
I was created simple wrapper for localization. If you want i can create pull request of them.

**Comment by pornel** [comment]
Thanks, but I don't think we need a wrapper. Using macOS native localization is the right solution for Sparkle.
