### ISSUE TITLE
appcast: sparkle:os="os_name" seems to be ignored

### ISSUE THREAD

**Issue by Memphiz** [sparkle-project/Sparkle#1088]
As the title says. I have a windows item in my appcast and have a sparkle:os="windows" attribute in the enclosure tag. Yet osx shows me this item as update and tries to download an exe file.

Is this meant to work in current master?

**Comment by pornel** [comment]
No, unfortunately this part never got implemented :(

**Comment by Memphiz** [comment]
extra appcast it is then - no biggy :)
