### ISSUE TITLE
-feedURLStringForUpdater: delegate method called twice

### ISSUE THREAD

**Issue by Eitot** [sparkle-project/Sparkle#1095]
I noticed that this delegate method is executed twice. I think this happens because this method [is called in the getter `feedURL`](https://github.com/sparkle-project/Sparkle/blob/3e45211bbebb2ef0fea74a69bbb5534c57091490/Sparkle/SUUpdater.m#L449) in SUUpdater.m, which itself is called in `-checkIfConfiguredProperly:` and in the getter `parameterizedFeedURL`, both [via `-checkForUpdatesWithDriver:`](https://github.com/sparkle-project/Sparkle/blob/3e45211bbebb2ef0fea74a69bbb5534c57091490/Sparkle/SUUpdater.m#L344-L346).

**Comment by pornel** [comment]
Is this causing problems?

I think trying to avoid calling it more than once would require us to hold a cached copy, which may be an unnecessary complication.

**Comment by Eitot** [comment]
Not a problem per se. I just wanted to bring this to your attention.

**Comment by pornel** [comment]
I see. Thanks. I'll keep it as-is then.
