### ISSUE TITLE
Delegate methods for stopping and starting associated extensions/daemons

### ISSUE THREAD

**Issue by AppTyrant** [sparkle-project/Sparkle#1096]
I'm considering embedding a Finder Sync extension in my application but have a concern that a running instance could prevent Sparkle from updating the main app, perhaps with an error like this:

![screen shot 2017-06-21 at 6 07 43 pm](https://user-images.githubusercontent.com/17223914/27448850-4ee12908-5754-11e7-82f7-1c5a57ac0674.png)

I haven't tested with updating an app with an embedded and running Finder Sync extension, but it seems likely that this could cause an issue.

I don't believe it would be possible to check for running instances of app extensions and terminate them before updating, since Finder could try to launch another instance at any time. I believe in the case of Finder Sync extensions the documentation says that multiple instances could be running at the same time too. 

Perhaps it would be possible to programmatically turn off the extension preference, update, and then turn it back on after (if appropriate). But I don't believe there is public API to do that.

**Comment by pornel** [comment]
I think the "in use" behavior is only a high-level thing faked by Finder. Low-level Unix APIs don't have a concept of files in use, and are happy to delete them. 

In current versions of Sparkle we don't use Trash. We rename and delete the old app copy instead.

Is the extension going to be OK with its host app updating itself? I think you may need to find a way to restart it. Ideally you should restart the extension on app *startup*, because Sparkle update runs after your app quits.

**Comment by AppTyrant** [comment]
It seems that it'd possible to avoid an issue by using the [PluginKit](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man8/pluginkit.8.html) command line tool. Apparently you can enable/disable Finder Sync extensions with this tool (so long the main app is not sandboxed). 

So it should be possible to see if the Finder Sync extension is enabled in the SUUpdaterDelegate method that gets called just before updating, then mark whether or not to re-enable the Finder Sync extension on relaunch. 

Would having an optional entry for devs to add in an Info.plist to specify a plugin bundle identifier for Sparkle to automatically check, be a feature you'd consider adding in the Framework? Not sure how good of an idea that is though since it seems PluginKit is barely documented.

**Comment by pornel** [comment]
I don't think Finder Sync extensions are popular enough to have dedicated code in Sparkle.

The problem of stopping/restarting bundled apps and daemons is common, but I don't know what Sparkle can do here to help. 

Maybe we could have a dedicated delegate method to run on the first app startup after upgrade?

**Comment by AppTyrant** [comment]
A dedicated delegate method would improve the situation IMO. Right now I think I'd have to check whether or not to restart the extension on every launch. Would be cleaner to do it in a delegate method like updaterDidRelaunchApplication:

**Comment by AppTyrant** [comment]
Cool. I'm not really familiar with the Sparkle source, I just took a quick look. Would something like this work?  

https://github.com/AppTyrant/Sparkle/commit/2310cad603357c5a6df5a6b60065acfa59fb59c9

**Comment by pornel** [comment]
That's good!

I'd prefer it without exposing isUpdaterRelaunching, to keep just one way to do it. Could you make a PR for just the delegate callback?

**Comment by AppTyrant** [comment]
Sure thing! Thanks!
