### ISSUE TITLE
Does Sparkle respect update interval when application is left running, or only on startup?

### ISSUE THREAD

**Issue by frankrei** [sparkle-project/Sparkle#1101]
Hi,

I usually write applications that people do not let running indefinitely, but my latest app is an "always on" app. It is configured to check for updates every day, but in the field it does not seem to do so.

Have I misunderstood how it works and it this interval in fact not "once a day" but "when restarted more than a day after it has last been launched"?

Best regards,

Frank

**Comment by pornel** [comment]
It also checks when the app is running for a long time.

It installs only when the app quits (because the app cannot be changed while it is running).

**Comment by frankrei** [comment]
Thanks.
