### ISSUE TITLE
Distracting by design

### ISSUE THREAD

**Issue by ricburton** [sparkle-project/Sparkle#1106]
I really dislike the way Sparkle leaves a pop-up hanging in front of all my windows with a distracting loading bar. With larger app updates, my eyes are constantly shifting to the moving bar and my workflow is completely ruined. I would love to see a better-designed solution that put the updating bar into the app it’s updating or even the ability to dismiss it while it updates.

When the App Store updates apps, it does so quietly. I would like Sparkle to be similarly muted.

**Comment by pornel** [comment]
Do you have a suggestion how a good UI for this would look like?

**Comment by DivineDominion** [comment]
I thought this kind of discussion was somewhere else, already; a less obstrusive suggestion would be to utilize the Mac Notification Center. 1Password and GitUp notify users of updates this way, and it's way less "in your face", especially for menu bar apps that run all the time.

**Comment by ricburton** [comment]
I could nick up a few ideas. I'd love to see it embedded into the app as a percentage bar.

**Comment by zorgiepoo** [comment]
Probably #924
