### ISSUE TITLE
Unnecessary request for admin privileges

### ISSUE THREAD

**Issue by lapcat** [sparkle-project/Sparkle#1108]
At SUFileManager.m:736, Sparkle compares the group id of the source and target, and if the group id doesn't match, Sparkle requests admin privileges to change it. This is unnecessary, however, if the owner is the user but the group is wheel (group id 0). It's rarely necessary to worry about the group as long as the owner is the same.

This problem was introduced in commit 984c3dc0e17a897d78e4c9bf2160521353520f22

I've been seeing admin requests for SourceTree updates, because the app happens to have wheel group on my Mac. I also see this with the Sparkle test app on my system, because my source file directories also have wheel group.

**Comment by bdb** [comment]
Are you in group wheel? Sparkle looks to be changing the app owner AND group to match the owner and group of anything it's overwriting. Trying to change the group of a file to any group you don't belong to will require root (Admin). Normal users do not belong to group wheel by default. If SourceTree for some reason installs itself the first time with wheel then that's the problem.

**Comment by lapcat** [comment]
I'm not in group wheel, but various directories on the system can have group wheel for various reasons, and when you unzip the download, the app inherits the group from the enclosing directory.

**Comment by bdb** [comment]
OK, so to me this doesn't sound unnecessary than. Sparkle is prompting for admin privileges because it must to make sure the permissions of the original version are set on the new version.

**Comment by lapcat** [comment]
> it must to make sure the permissions of the original version are set on the new version.

Must it? Why? As I said,

> It's rarely necessary to worry about the group as long as the owner is the same.

If the owner is the same, but the group is wheel, this seems like a very good reason to make an exception and not put such a strict requirement on the group. Frankly, it's probably a bad idea for Sparkle to _ever_ request admin privileges. Too much danger there.

**Comment by jkbullard** [comment]
>> it must to make sure the permissions of the original version are set on the new version.
Must it? Why? As I said,

> It's rarely necessary to worry about the group as long as the owner is the same.

So sometimes it _is_ necessary.

> Frankly, it's probably a bad idea for Sparkle to ever request admin privileges. Too much danger there.

I disagree. For Sparkle to update an application that is "protected" (owner:group of root:wheel, for example), Sparkle **must** get admin privileges to update the application. If Sparkle doesn't do that, the application can't use Sparkle for updating.

[Tunnelblick](https://tunnelblick.net) is an example of such an application. Parts of Tunnelblick run as root to perform privileged network operations, so the entire application must be root:wheel or an unprivileged user could modify parts of it and gain root access to the system (a/k/a "escalation of privilege").

**Comment by lapcat** [comment]
> I disagree.
That's fine. It was just an offhand comment, not directly applicable to this ticket.

> the entire application must be root:wheel or an unprivileged user could modify parts of it and gain root access to the system

If the application is root owned, then Sparkle will need to request admin anyway, in which case the group can easily be matched. What I'm suggesting is simply that if the owner of the application is not root, then there is no need to request admin simply to change the group.

**Comment by pornel** [comment]
In general I'd like to reduce number of admin prompts we have, but is it safe and reliable?

If the ownership is `$USER:some_other_group`, is it safe to change it to `$USER:$USER`?

**Comment by jkbullard** [comment]
If a file is owned by $USER with group "wheel" with permissions 0770, the file cannot be read or modified by anyone who is not $USER and is not a member of the "wheel" group.

If the file's group is changed to "staff" (for example), then all members of the "staff" group can read or modify the file.

Unless the group of the original file is preserved by Sparkle, an update will cause the file to be readable and modifiable by people who were not allowed to read or modify it before the update.

Not safe.

**Comment by lapcat** [comment]
> If a file is owned by $USER with group "wheel" with permissions 0770, the file cannot be read or modified by anyone who is not $USER and is not a member of the "wheel" group.

There's no app on my Mac with 0770. Most apps are 0755, which means only the owner can modify, and anyone can run.

**Comment by jkbullard** [comment]
But Sparkle doesn't just update applications, it also updates bundles, which often have peculiar owner:group and permissions designed specifically to restrict access to their internal data.

**Comment by lapcat** [comment]
Sure, but it could check the perms. If non-root 0755, then don't request admin privileges.

**Comment by jkbullard** [comment]
That starts to get complicated and won't work for all the current uses of Sparkle.

The original problem you are trying to solve is "admin requests for SourceTree update" on your computer. Either you have modified SourceTree so it has group wheel, or SourceTree has set their application up that way.
 * If you did it, undo it.
 * If they've done it, ask them why they do it in the original application -- perhaps they have a good reason! If they don't, have them fix the problem on their end.  (Or change it on your computer yourself.)

**Comment by lapcat** [comment]
This isn't about me, and it's not about SourceTree either. I mentioned SourceTree as an example simply because that's how I discovered the problem. I can easily change the group of that app on my Mac, and I said it happens with the Sparkle Test App too, not just SourceTree. This is about a bug: Sparkle unexpectedly and unnecessarily requests admin privileges for no apparent reason. And it took me a long debugging session to discover the real reason. Ordinary users would have no way of knowing why they're getting an admin request.

I didn't set the group. SourceTree didn't set the group. As I said before, "I'm not in group wheel, but various directories on the system can have group wheel for various reasons, and when you unzip the download, the app inherits the group from the enclosing directory."

I'm reporting an undesirable behavior in the framework, I'm not asking for technical support.

**Comment by bdb** [comment]
Is the behavior undesirable though? That's the real question here. It could be argued that Sparkle should preserve the permissions exactly as they are set in the version it's replacing. That may be critical not just to the app but to the environment the app is running in. (Think a managed environment.) I'd lean towards the current behavior being the "correct" behavior. And leave it up to the app devs and/or sys admin to change that (which can be done easily by either).

**Comment by lapcat** [comment]
> Think a managed environment.

A professionally managed environment wouldn't even use Sparkle. The administrator would manually download updates, validate them, and deploy them to local machines. They might even use firewall rules to block the apps from phoning home.

> And leave it up to the app devs

How would the apps devs change this? They'd have to modify the source code as I'm suggesting.

I suspect that many app devs embedding Sparkle don't even realize it requests admin. The majority of devs don't want their apps to ever request admin. Also, the current implementation doesn't even tell the user exactly why it's requesting admin, which is a big problem. If I get an admin request out of the blue for no apparent reason, I'm not going to enter my credentials, and we shouldn't be training users to blindly do it.
