### ISSUE TITLE
Code signing fails with keychain saying: An error has occurred. Unable to import an item.

### ISSUE THREAD

**Issue by Ghosty141** [sparkle-project/Sparkle#1109]
When I try to codesign: "open sign_update <path to .dmg> <path to dsa_priv.dmg>" it opens the keychain with a dialog: "An error has occurred. Unable to import an item. The contents of this item cannot be retrieved." I followed every step and I'm pretty sure I didn't skip anything.

The console shows "Broken Pipe" for a split seconds before closing and opening the .dmg archive I'm trying to sign.

Any ideas why this occurs?

Sierra 10.12.4
Sparkle 1.18.0

**Comment by pornel** [comment]
`open` is for launching GUI apps. Don't use it to run command-line scripts.

Run

```sh
./sign_update dmg key
```

instead.

**Comment by Ghosty141** [comment]
Oh god thanks! I haven't used OS X in a while, completely forgot that!
