### ISSUE TITLE
Can't select delta update with non-delta fallback when bestValidUpdateInAppcast is implemented

### ISSUE THREAD

**Issue by AlienCowEatCake** [sparkle-project/Sparkle#1110]
It seems like in SUAppcast the result for the function

```- (SUAppcast *)copyWithoutDeltaUpdates;```

isn't as expected. I tried to implement

```- (nullable SUAppcastItem *)bestValidUpdateInAppcast:(SUAppcast *)appcast forUpdater:(SUUpdater *)updater;```

but there are never delta updates in ```[appcast items]```, there are delta updates for some item in ```[someItem deltaUpdates]```. Therefore, when I select one of the items from ```[someItem deltaUpdates]```, the next call of bestValidUpdateInAppcast will contain ```[appcast items]``` with no changes at all. This will lead to selecting the same item with delta update. When I select an item from ```[appcast items]```, I can't select delta update.

**Comment by pornel** [comment]
Do you have a solution in mind?

**Comment by AlienCowEatCake** [comment]
I don't know how it was designed to be but here are a couple options off the top of my head for how it might work:

1. copyWithoutDeltaUpdates must actually create a copy of appcast  without delta updates items. Meaning, ```[item deltaUpdates]``` should be an empty dictionary for each item.
2. The first call of bestValidUpdateInAppcast may be sent a modified copy of the appcast, which will contain the suitable delta updates exactly in ```[appcast items]```. The second call may be sent the original appcast.

The first option looks more flexible to customize.

**Comment by zorgiepoo** [comment]
Logic in 2.x now figures out the appropriate delta update and requires the client to pick a regular item from the appcast.
