### ISSUE TITLE
Setting up project with Sparkle

### ISSUE THREAD

**Issue by JorgenAndreasson** [sparkle-project/Sparkle#1113]
I'm trying to set up Sparkle for my macOS project, but not having much luck.
I am serving the upgrades from a DropBox (DB) folder so I will have a https:// URL. Hopefully that is OK to do.

I created the dsa, dsa.pub and dsa_priv.pem in the .ssh folder. I have put the dsa.pub into the Resource folder in my project. I have a .xml file in the DB folder. I also have a zipped up version of the app there.

```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"  xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>BF4L Coach</title>
    <link>http://sparkle-project.org/files/BF4L_Coach.xml</link>
    <description>Most recent changes with links to updates.</description>
    <language>en</language>
      <item>
        <title>Version 1.0.1</title>
        <description>
          <![CDATA[
            <ul>
              <li>Som new fix.</li>
              <li>Another new fix.</li>
              <li>New feature 1.</li>
              <li>Another new feature.</li>
            </ul>
          ]]>
        </description>
        <pubDate>Fri, 28 Jul 2017 09:00:00 +0000</pubDate>
        <enclosure url="https://www.dropbox.com...._Coach.zip" sparkle:version="1.0.1" length="4687480" type="application/octet-stream" sparkle:dsaSignature="some signature==" />
      </item>
      <item>
    <title>Version 1.0.1</title>
    <sparkle:minimumSystemVersion>10.12</sparkle:minimumSystemVersion>
</item>
  </channel>
</rss>
```

But I keep getting "An error occurred in retrieving update information. Please try again later."

Where have I gone wrong?

Any help would be most appreciated

**Comment by pornel** [comment]
Whenever anything goes wrong, Sparkle writes log with detailed information, which you can see via Console.app (or the console log in Xcode if you run from Xcode).

**Comment by pornel** [comment]
BTW, try the `generate_appcast` app. It handles XML generation and signing for you, so there are less things that can go wrong.

**Comment by JorgenAndreasson** [comment]
I tried, but end up with this..

-bash: ./bin/generate_appcast: No such file or directory

In which directory should that be?

**Comment by JorgenAndreasson** [comment]
Does this make any sense to you?

2017-07-31 20:12:45.821717+0100 BF4L Coach[21872:1320172] [Sparkle] Error: An error occurred in retrieving update information. Please try again later. An error occurred while parsing the update feed. (URL (null))
2017-07-31 20:12:45.821781+0100 BF4L Coach[21872:1320172] [Sparkle] Error: An error occurred while parsing the update feed. (null) (URL (null))
2017-07-31 20:12:45.821807+0100 BF4L Coach[21872:1320172] [Sparkle] Error: Line 43: xmlParseEntityRef: no name
 (null) (URL (null))

**Comment by JorgenAndreasson** [comment]
Also the second line in the xml looks strange. 

<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"  xmlns:dc="http://purl.org/dc/elements/1.1/">

**Comment by JorgenAndreasson** [comment]
Also the second line looks weird to me.

`<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"  xmlns:dc="http://purl.org/dc/elements/1.1/">`

**Comment by JorgenAndreasson** [comment]
From which directory should I run the 'generate_appcast' command? 
If I try it in the project directory I get an error: No such file or directory.

**Comment by pornel** [comment]
It is there in the Sparkle release archive. Try specifying the full path to it.

**Comment by JorgenAndreasson** [comment]
Hi

My problem is that I cannot find that directory.

 

I have gone to the Sparkle folder inside ‘Pods’ on my project and tried to run ‘generate_appcast’ from there – “command not found”

 

 

 

 

Best regards

Jörgen

**Comment by pornel** [comment]
It's in https://github.com/sparkle-project/Sparkle/releases/download/1.18.0/Sparkle-1.18.0.tar.bz2

I don't know why CocoaPods doesn't build/bundle it.

**Comment by JorgenAndreasson** [comment]
Ah! That makes sense.

Onwards and upwards…

 

 

Best regards

Jörgen

**Comment by JorgenAndreasson** [comment]
Thanks. Now I can run it.
Unfortunately not with success. It can't find the 'dsa_priv.pem' it says.

```
jorgen@xx .ssh $ ls
dsa					id_rsa					
dsa.pub					id_rsa.pub				
dsa_priv.pem				id_rsa_mim				known_hosts
jorgen@xx .ssh $ cd Downloads/Sparkle-1.18.0
-bash: cd: Downloads/Sparkle-1.18.0: No such file or directory
jorgen@x .ssh $ cdx
jorgen@xx ~ $ cd Downloads/Sparkle-1.18.0
jorgen@xxSparkle-1.18.0 $ ./bin/generate_appcast ~/.ssh/dsa_priv.pem https://www.dropbox.com/xxxxxx?dl=0
Private DSA key could not be imported -50
Unable to load DSA private key from /Users/jorgen/.ssh/dsa_priv.pem 
 Error Domain=SUSparkleErrorDomain Code=3001 "(null)"
```
Doing a 'ls' in the .ssh directory show that I have the dsa_priv.pem file there.
But it can't be imported with a -50 error.

Any idea?

**Comment by pornel** [comment]
The file exists and has been read from disk OK. This error complains that content of the file is not valid.

I have no idea what Apple thinks the error -50 is.

**Comment by JorgenAndreasson** [comment]
Cheers

I’ll have a go at making a new one.

 

 

Best regards

Jörgen

**Comment by JorgenAndreasson** [comment]
Sorry about this, but still having problems.
I re-created the dsa files, this time with the Sparkle command.
Running 'generate_appcast' now works fine.

```
jorgen@xxx Sparkle-1.18.0 $ ./bin/generate_appcast dsa_priv.pem ~/DropBox/BF4L_Coach
Written /Users/jorgen/DropBox/BF4L_Coach/BF4L_Coach.xml based on 1 updates
```
I have the new dsa_pub.pem in the Resource folder in Xcode. (see attached)
But when I run the "Check for Updates" command in the app I end up with an error. (see attached)

![screen shot 2017-08-02 at 07 56 59](https://user-images.githubusercontent.com/6663405/28861516-270168d8-7759-11e7-9d43-0a7e2e1e4a26.png)
![screen shot 2017-08-02 at 07 59 54](https://user-images.githubusercontent.com/6663405/28861517-270543d6-7759-11e7-89b6-fa0da9153be6.png)

The log tells me this;
```
2017-08-02 08:04:35.921340+0100 BF4L Coach[46215:2948637] [Sparkle] Error: An error occurred in retrieving update information. Please try again later. An error occurred while parsing the update feed. (URL (null))
2017-08-02 08:04:35.921426+0100 BF4L Coach[46215:2948637] [Sparkle] Error: An error occurred while parsing the update feed. (null) (URL (null))
2017-08-02 08:04:35.921440+0100 BF4L Coach[46215:2948637] [Sparkle] Error: Line 43: xmlParseEntityRef: no name
 (null) (URL (null))

```

I have not been able to sign the .dmg. Could that be the problem?

**Comment by pornel** [comment]
The problem you have now is that Sparkle does not know URL to your feed. You have to upload that feed to some HTTPS server, and specify SUFeedURL in Info.plist

**Comment by JorgenAndreasson** [comment]
I have it on my DropBox, inside a folder. Is that good enough?

 

 

Best regards

Jörgen

**Comment by pornel** [comment]
Sparkle needs to know the URL, and the URL must be publicly accessible from the public Internet.

If it's just a file in your dropbox, then you'll be the only person who can check updates :)

**Comment by JorgenAndreasson** [comment]
You are a star!
Moved it to my public folder in the DropBox and changed the URLs.
All working perfect.
Thank you for sticking with it.

**Comment by pornel** [comment]
Great
