### ISSUE TITLE
cocoapods install error

### ISSUE THREAD

**Issue by Alonso-Feng** [sparkle-project/Sparkle#1114]
pod install

Analyzing dependencies
Downloading dependencies
Installing Sparkle (1.18.0)

[!] Error installing Sparkle
[!] /usr/bin/curl -f -L -o /var/folders/pk/cqywbmhd1v3fchgsvrdgt2yw0000gn/T/d20170803-41619-1rlavom/file.tbz https://github.com/sparkle-project/Sparkle/releases/download/1.18.0/Sparkle-1.18.0.tar.bz2 --create-dirs --netrc-optional

Warning: ignoring SSL_CERT_DIR environment variable, not supported by libcurl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   610    0   610    0     0    657      0 --:--:-- --:--:-- --:--:--   656
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (35) Server aborted the SSL handshake

what can I do?

**Comment by pornel** [comment]
Looks like your system has an old version of curl that doesn't support up-to-date version of TLS. Try upgrading/fixing curl.
