### ISSUE TITLE
Guided package installation freezes on Mac OS X 10.7

### ISSUE THREAD

**Issue by AlienCowEatCake** [sparkle-project/Sparkle#1121]
In case of update using guided package on Mac OS X 10.7.5, the installation freezes. According to the log, the installation was performed correctly, but the /usr/sbin/installer process doesn't end and stays running on the process list. Progress in the autoupdate window is at 0 during the whole time. Starting ```/usr/sbin/installer -verboseR -pkg ${PKGNAME} -target /``` manually ends successfully.

This repeats since 1.18.0a1 version, 1.17.0 works fine. Looks like it got broken on the 2a644672ca7939c50466507f28d4ee9f349edc6a commit - reverting it fixes the problem, the installation works correctly.

**Comment by pornel** [comment]
Thank you for the report. Is output of `-verboseR` different on 10.7 than later versions?

**Comment by AlienCowEatCake** [comment]
The verbose output has the same format as in the later versions: [stdout_10.7.txt](https://github.com/sparkle-project/Sparkle/files/1272478/stdout_10.7.txt), [stdout_10.11.txt](https://github.com/sparkle-project/Sparkle/files/1272479/stdout_10.11.txt).

It seems that the bug is not stable. It is rarely reproducible on another mac with 10.7.5.

**Comment by zorgiepoo** [comment]
Probably not an issue in Sparkle 2, don't know about top of 1.x branch, recent OS versions could have fixed this.
