### ISSUE TITLE
Sparkle 1.18.1 cannot be compiled with macOS SDK smaller than 10.12

### ISSUE THREAD

**Issue by dfuhrmann** [sparkle-project/Sparkle#1122]
Due to recently added support of os_log in SULog.m, Sparkle is now able to log to the 10.12 native logging framework.

Those new API was introduced into the newest 10.12 SDK only. While the file has runtime fallbacks to older mechanisms, the included header "<os/log.h>" is unguarded.
This means that sparkle cannot be compiled with any older SDK than 10.12.

This should be fixed by guarding the header to allow compilation with 10.11. Alternatively, documentation should be updated if sparkle needs to be compiled with 10.12 now (which would be very sad).

**Comment by jkbullard** [comment]
>This should be fixed by guarding the header to allow compilation with 10.11.

+1

> Alternatively, documentation should be updated if sparkle needs to be compiled with 10.12 now (which would be very sad).

-1

**Comment by pornel** [comment]
Thanks for the report. 

Yes, indeed, we should keep backwards compatibility.

Could you add these guards? I don't have an old SDK to test it with.

**Comment by dfuhrmann** [comment]
Hi pornel,

I tried to fix compilation with Xcode 7 and macOS 10.11 SDK here in my branch: https://github.com/dfuhrmann/Sparkle/commits/xcode-7-macOS-10.11-compatibility

While fixing the SULog issue is relatively easy, I found out that all of the current XIB files are stored in Xcode 8 format. Xcode 8 only allows to store in that format by default, and there seems to be no easy way to use Xcode 8 with a backward-compatible Xcode 7 format, for whatever reason. If you only open a xib file in Xcode 8, it will be converted into that format.

Unfortunately, Xcode 8 only ships with 10.12 SDK (as far as I know).

So in order to allow compilation with 10.11 SDK and Xcode 7, all xib files would need to be stored in Xcode 7 format, and also Xcode 7 would need to be used as the main developement platform.
We are facing that situation as well with our VLC developement, and it is quite annoying as it currently stands.

Therefore, can you please clarify for the Sparkle project what your minimum supported development platform is or is intended to be? If it is Xcode 7, then you probably need to continue using Xcode 7 for xib editing. If it is Xcode 8, then compilation is limited to a quite new setup, only.

**Comment by pornel** [comment]
Is the xib format a big deal? I presume compiled nib is more backwards compatible. Would you be able to use precompiled Sparkle?

**Comment by jkbullard** [comment]
The xib format is a problem when building Sparkle from source using Xcode 7.

Tunnelblick still builds with Xcode 7 because of problems with the code generated by Xcode 8. (The precompiled Sparkle doesn't work for us because we want signed appcasts.)

To repeat @dfuhrmann's question:

> Therefore, can you please clarify for the Sparkle project what your minimum supported development platform is or is intended to be?

**Comment by dfuhrmann** [comment]
> Is the xib format a big deal? I presume compiled nib is more backwards compatible. Would you be able to use precompiled Sparkle?

Unfortunately, yes, it is a problem. In VLC, we want to compile all our dependencies from source by ourselves, for various reasons (e.g. having a fix reference to source code and thus control over what is actually part of the compilation, having the ability to tweak compilation settings).

For us, it would be a bit bigger deal to switch to Xcode 8 and macOS 10.12 development only, as all the developers would be forced to update (people might want to make changes on older macOS releases), as well CI / build systems would need to be updated.

**Comment by pornel** [comment]
OK, I think we can temporarily downgrade. Could you make a pull request?

We can keep XCode 7-compatible files until we need to apply major translation changes.
