### ISSUE TITLE
Fail in Sandbox mode(using branch ui-separation-and-xpc)

### ISSUE THREAD

**Issue by vicalloy** [sparkle-project/Sparkle#1125]
While testing it in Sandbox mode (with the Sandbox branch) I'm seeing the following error come up after 'Extracting..'

`
Update Error!
An error occurred while running the updater. Please try again later.
`

Branch: ui-separation-and-xpc
XCode: 8.3.3
macOS: 10.12.5

**log**

```
default	11:04:11.082051 +0800	kernel	SandboxViolation: SSH Proxy(90171) deny(1) mach-lookup com.codinn.sshproxy-spks
default	11:04:11.124118 +0800	SSH Proxy	0x600000465a00 opened /var/folders/l4/ypb3l3d97vzgczv_tb65jr7c0000gn/C/com.codinn.sshproxy//mds/mdsObject.db: 4636 bytes
default	11:04:11.124502 +0800	SSH Proxy	0x6000006675c0 opened /var/folders/l4/ypb3l3d97vzgczv_tb65jr7c0000gn/C/com.codinn.sshproxy//mds/mdsDirectory.db: 50744 bytes
default	11:09:53.854535 +0800	kernel	SandboxViolation: SSH Proxy(90171) deny(1) authorization-right-obtain config.add.com.codinn.sshproxy.sparkle-auth
default	11:09:53.854620 +0800	authd	Sandbox denied authorizing right 'config.add.com.codinn.sshproxy.sparkle-auth' by client '/Users/huxiaomao/Desktop/SSH Proxy 2017-09-14 14-38-52/SSH Proxy.app' [90171]
default	11:09:53.858447 +0800	kernel	SandboxViolation: SSH Proxy(90171) deny(1) authorization-right-obtain com.codinn.sshproxy.sparkle-auth
default	11:09:53.858487 +0800	authd	Sandbox denied authorizing right 'com.codinn.sshproxy.sparkle-auth' by client '/Users/huxiaomao/Desktop/SSH Proxy 2017-09-14 14-38-52/SSH Proxy.app' [90171]
default	11:09:56.550297 +0800	kernel	SandboxViolation: SSH Proxy(90171) deny(1) mach-lookup com.codinn.sshproxy-spks
```

**Comment by core-code** [comment]
i am seeing the same:

UI Message: "Update Error!" "An error occurred while launching the installer. Please try again later." "Cancel Update"

Console Messages:
`default	16:02:32.897514 +0100	kernel	Sandbox: MKV2MP4(2603) deny(1) system-fsctl 4a0e
error	16:02:32.902276 +0100	sandboxd	Sandbox: MKV2MP4(2603) deny system-fsctl 0x4a0e
Violation:       deny system-fsctl 0x4a0e 
MetaData: {"build":"Mac OS X 10.13.3 (17D102)","action":"deny","target":["0x4a0e"],"hardware":"Mac","platform_binary":"no","profile":"unknown","process":"MKV2MP4","op":"system-fsctl"}

Process:         MKV2MP4 [2603]
Path:            /Applications/_Apps/MKV2MP4-HP.app/Contents/MacOS/MKV2MP4
Load Address:    0x1094d4000
Identifier:      com.corecode.MKV2MP4
Version:         1743 (1.4.7)
Code Type:       x86_64 (Native)
Parent Process:  launchd [1]
Responsible:     /Applications/_Apps/MKV2MP4-HP.app/Contents/MacOS/MKV2MP4 [2603]
User ID:         501

Date/Time:       2018-03-09 16:02:32.887 GMT+1
OS Version:      Mac OS X 10.13.3 (17D102)
Report Version:  8

Thread 0 (id: 50234):
0   libsystem_kernel.dylib        	0x00007fff77d21a72 fsctl + 10
1   DesktopServicesPriv           	0x00007fff646a330c TDeepCFURLIterator::RecordClone(std::__1::unordered_set<unsigned long long, std::__1::hash<unsigned long long>, std::__1::equal_to<unsigned long long>, std::__1::allocator<unsigned long long> >*, TRef<TCFURLInfo*, TInternalRefCountPolicy<TCFURLInfo> >&) + 52
2   DesktopServicesPriv           	0x00007fff646a2cea TDeepCFURLIterator::NextInternal(TRef<TCFURLInfo*, TInternalRefCountPolicy<TCFURLInfo> >&, int&, int&, bool&, bool&, TRef<TCFURLInfo*, TInternalRefCountPolicy<TCFURLInfo> >&, bool&, TRef<TCFURLInfo*, TInternalRefCountPolicy<TCFURLInfo> >&) + 358
3   DesktopServicesPriv           	0x00007fff646a29a7 TDeepCFURLIterator::Next(TRef<TCFURLInfo*, TInternalRefCountPolicy<TCFURLInfo> >&, int&, int&, bool&, bool&, TRef<TCFURLInfo*, TInternalRefCountPolicy<TCFURLInfo> >&, bool&, TRef<TCFURLInfo*, TInternalRefCountPolicy<TCFURLInfo> >&) + 75
4   DesktopServicesPriv           	0x00007fff6462688d TOperationSizer::StartSizing() + 301
5   DesktopServicesPriv           	0x00007fff64625cb9 TOperationSizer::ComputeSize() + 435
6   DesktopServicesPriv           	0x00007fff6468605f TFSCopyOperation::CopyPreflight(unsigned long long&, unsigned long long&, unsigned long long&) + 433
7   DesktopServicesPriv           	0x00007fff64685010 TFSCopyOperation::DoCopy(TRef<TCFURLInfo*, TInternalRefCountPolicy<TCFURLInfo> > const&) + 364
8   DesktopServicesPriv           	0x00007fff64684e43 TFSCopyOperation::Run() + 93
9   DesktopServicesPriv           	0x00007fff6466e466 _NodeOperationV3 + 434
10  DesktopServicesPriv           	0x00007fff6466e2a5 _NodeOperation + 133
11  CarbonCore                    	0x00007fff5146a6e5 _FSOperateOnObjectSync + 435
12  Sparkle                       	0x000000010958069d -[SUFileManager copyItemAtURL:toURL:error:] + 1289
13  Sparkle                       	0x0000000109586c42 __158-[SUInstallerLauncher launchInstallerWithHostBundlePath:authorizationPrompt:installationType:allowingDriverInteraction:allowingUpdaterInteraction:completion:]_block_invoke + 629
14  libdispatch.dylib             	0x00007fff77b9f591 _dispatch_call_block_and_release + 12
15  libdispatch.dylib             	0x00007fff77b97d50 _dispatch_client_callout + 8
16  libdispatch.dylib             	0x00007fff77ba332d _dispatch_main_queue_callback_4CF + 1148
17  CoreFoundation                	0x00007fff502f8929 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
18  CoreFoundation                	0x00007fff502babea __CFRunLoopRun + 2586
19  CoreFoundation                	0x00007fff502b9f43 CFRunLoopRunSpecific + 483
20  HIToolbox                     	0x00007fff4f5d1e26 RunCurrentEventLoopInMode + 286
21  HIToolbox                     	0x00007fff4f5d1b96 ReceiveNextEventCommon + 613
22  HIToolbox                     	0x00007fff4f5d1914 _BlockUntilNextEventMatchingListInModeWithFilter + 64
23  AppKit                        	0x00007fff4d89cf5f _DPSNextEvent + 2085
24  AppKit                        	0x00007fff4e032b4c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
25  AppKit                        	0x00007fff4d891d6d -[NSApplication run] + 764
26  AppKit                        	0x00007fff4d860f1a NSApplicationMain + 804
27  MKV2MP4                       	0x00000001094ddcd2 main + 33
28  libdyld.dylib                 	0x00007fff77bd1115 start + 1
29  MKV2MP4                       	0x0000000000000001

Thread 1 (id: 50343, com.apple.NSEventThread):
0   libsystem_kernel.dylib        	0x00007fff77d177c2 mach_msg_trap + 10
1   CoreFoundation                	0x00007fff502bb575 __CFRunLoopServiceMachPort + 341
2   CoreFoundation                	0x00007fff502ba8c7 __CFRunLoopRun + 1783
3   CoreFoundation                	0x00007fff502b9f43 CFRunLoopRunSpecific + 483
4   AppKit                        	0x00007fff4d9da3c8 _NSEventThread + 184
5   libsystem_pthread.dylib       	0x00007fff77e5c6c1 _pthread_body + 340
6   libsystem_pthread.dylib       	0x00007fff77e5c56d _pthread_body + 0
7   libsystem_pthread.dylib       	0x00007fff77e5bc5d thread_start + 13

Thread 2 (id: 50360, com.apple.NSURLConnectionLoader):
0   libsystem_kernel.dylib        	0x00007fff77d177c2 mach_msg_trap + 10
1   CoreFoundation                	0x00007fff502bb575 __CFRunLoopServiceMachPort + 341
2   CoreFoundation                	0x00007fff502ba8c7 __CFRunLoopRun + 1783
3   CoreFoundation                	0x00007fff502b9f43 CFRunLoopRunSpecific + 483
4   CFNetwork                     	0x00007fff4f432f84 -[__CoreSchedulingSetRunnable runForever] + 722
5   Foundation                    	0x00007fff52399ee8 __NSThread__start__ + 1197
6   libsystem_pthread.dylib       	0x00007fff77e5c6c1 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff77e5c56d _pthread_body + 0
8   libsystem_pthread.dylib       	0x00007fff77e5bc5d thread_start + 13

Thread 3 (id: 50525):
0   libsystem_kernel.dylib        	0x00007fff77d20cee __psynch_cvwait + 10
1   libc++.1.dylib                	0x00007fff75c06cb0 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
2   JavaScriptCore                	0x00007fff53df8b16 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 86
3   JavaScriptCore                	0x00007fff53df8a4b bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 139
4   JavaScriptCore                	0x00007fff53df8d78 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 40
5   libsystem_pthread.dylib       	0x00007fff77e5c6c1 _pthread_body + 340
6   libsystem_pthread.dylib       	0x00007fff77e5c56d _pthread_body + 0
7   libsystem_pthread.dylib       	0x00007fff77e5bc5d thread_start + 13

Thread 4 (id: 54213):
0   libsystem_kernel.dylib        	0x00007fff77d21562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff77e5bc4d start_wqthread + 13
2                                 	0x4058504320000000

Thread 5 (id: 54411):
0   libsystem_kernel.dylib        	0x00007fff77d21562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff77e5bc4d start_wqthread + 13
2   libxpc.dylib                  	0x00007fffb0c36298 _xpc_type_serializer + 0

Thread 6 (id: 54426):
0   libsystem_kernel.dylib        	0x00007fff77d21562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff77e5bc4d start_wqthread + 13

Thread 7 (id: 54427):
0   libsystem_kernel.dylib        	0x00007fff77d21562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff77e5bc4d start_wqthread + 13

Thread 8 (id: 54429):
0   libsystem_kernel.dylib        	0x00007fff77d21562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff77e5bc4d start_wqthread + 13

Thread 9 (id: 54597):
0   libsystem_kernel.dylib        	0x00007fff77d21562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff77e5bc4d start_wqthread + 13

Thread 10 (id: 56225):
0   libsystem_kernel.dylib        	0x00007fff77d21562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff77e5bc4d start_wqthread + 13

Thread 11 (id: 56248):
0   libsystem_kernel.dylib        	0x00007fff77d21562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff77e5bc4d start_wqthread + 13

Thread 12 (id: 56318):
0   libsystem_kernel.dylib        	0x00007fff77d21562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff77e5bc4d start_wqthread + 13

Binary Images:
       0x1094d4000 -        0x109510ff7  com.corecode.MKV2MP4 (1.4.7 - 1743) <2a87bbfe-606b-3318-a65b-ebae7072ffaf> /Applications/_Apps/MKV2MP4-HP.app/Contents/MacOS/MKV2MP4
       0x10955c000 -        0x1095a3fff  org.sparkle-project.Sparkle (1.18.1 - 1.18.1) <b26caff2-16a1-3ace-9bc7-621118b95e93> /Applications/_Apps/MKV2MP4-HP.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
    0x7fff4d85b000 -     0x7fff4e6b8fff  com.apple.AppKit (6.9 - 1561.20.106) <af59a3cf-e3c3-3046-86d9-0c9145e60ce4> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff4f1f6000 -     0x7fff4f588fff  com.apple.CFNetwork (893.13.1 - 893.13.1) <3ecc6ad0-b47d-38d2-bf26-496b34847d25> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff4f5a2000 -     0x7fff4f8a7ff7  com.apple.HIToolbox (2.1.1) <d1a799bc-146a-35e8-86ff-e36273123006> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff50235000 -     0x7fff506d5fe7  com.apple.CoreFoundation (6.9 - 1451) <7afe9c8f-a562-3afc-8402-117aa02f57e9> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff5140b000 -     0x7fff516e2ff7  com.apple.CoreServices.CarbonCore (1178.2 - 1178.2) <a1fe74f8-953b-371e-a8ac-e87b30fb79c6> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff5236b000 -     0x7fff52730fff  com.apple.Foundation (6.9 - 1451) <b99f94e7-117e-39cc-a65d-b7aea8998481> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff532d7000 -     0x7fff53e92fff  com.apple.JavaScriptCore (13604 - 13604.5.6) <5541e211-3248-3b89-9ae9-d5fe413f12d1> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff645f8000 -     0x7fff64727fff  com.apple.desktopservices (1.12.2 - 1.12.2) <8e068af7-fb72-38e2-948e-6c13f359c69d> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff75c00000 -     0x7fff75c56fff  libc++.1.dylib (400.9) <fcf5e1f6-2b04-3545-8004-f3ab32fed172> /usr/lib/libc++.1.dylib
    0x7fff77b96000 -     0x7fff77bcfff7  libdispatch.dylib (913.30.4) <7d0e3183-282b-3fee-a734-2c0adc092084> /usr/lib/system/libdispatch.dylib
    0x7fff77bd0000 -     0x7fff77bedff7  libdyld.dylib (519.2.2) <c50d02bc-a333-3313-b787-02f255a6783f> /usr/lib/system/libdyld.dylib
    0x7fff77d05000 -     0x7fff77d2aff7  libsystem_kernel.dylib (4570.41.2) <5155a4c3-825b-3178-ac51-0d2d2f2a6618> /usr/lib/system/libsystem_kernel.dylib
    0x7fff77e59000 -     0x7fff77e64fff  libsystem_pthread.dylib (301.30.1) <aba848e1-6978-3b42-a3a7-608b2c36fa93> /usr/lib/system/libsystem_pthread.dylib
    0x7fff77e8e000 -     0x7fff77ebaff7  libxpc.dylib (1205.30.29) <f7e5f1bc-614b-39cb-b6ce-92a9c7b7ec0b> /usr/lib/system/libxpc.dylib
error	16:02:32.903402 +0100	sandboxd	Sandbox: MKV2MP4(2603) deny system-fsctl 0x4a0e [Duplicate; no report will be generated.]
default	16:02:32.908339 +0100	kernel	Sandbox: MKV2MP4(2603) deny(1) system-fsctl 4a0e

default	16:02:32.953903 +0100	trustd	could not enable test hierarchy: no UAT pinning preferences set
default	16:02:32.957612 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	16:02:32.959877 +0100	authd	MacOS error: -67050
default	16:02:32.961070 +0100	authd	MacOS error: -67050
default	16:02:32.970176 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	16:02:32.972536 +0100	authd	MacOS error: -67050
default	16:02:32.974087 +0100	authd	MacOS error: -67050
default	16:02:32.975872 +0100	kernel	Sandbox: MKV2MP4(2603) deny(1) authorization-right-obtain config.add.com.corecode.MKV2MP4.sparkle-auth
error	16:02:32.975883 +0100	authd	Sandbox denied authorizing right 'config.add.com.corecode.MKV2MP4.sparkle-auth' by client '/Applications/_Apps/MKV2MP4-HP.app' [2603]
error	16:02:32.976000 +0100	MKV2MP4	Failed to make auth right set
default	16:02:32.984148 +0100	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	16:02:32.986619 +0100	authd	MacOS error: -67050
default	16:02:32.987712 +0100	authd	MacOS error: -67050
default	16:02:32.989230 +0100	kernel	Sandbox: MKV2MP4(2603) deny(1) authorization-right-obtain com.corecode.MKV2MP4.sparkle-auth
error	16:02:32.989242 +0100	authd	Sandbox denied authorizing right 'com.corecode.MKV2MP4.sparkle-auth' by client '/Applications/_Apps/MKV2MP4-HP.app' [2603]
error	16:02:32.989348 +0100	MKV2MP4	Failed copying system domain rights: -60005
error	16:02:32.989286 +0100	authd	copy_rights: authorization failed
error	16:02:32.989518 +0100	MKV2MP4	Failed to submit installer job
error	16:02:32.990581 +0100	MKV2MP4	Error: Failed to gain authorization required to update target
`

**Comment by sweetppro** [comment]
I just started getting this error today for all my apps too?
