### ISSUE TITLE
generate_appcast with *.pkg file

### ISSUE THREAD

**Issue by hateom** [sparkle-project/Sparkle#1130]
Hi,

I'm having issues generating appcast from a zip file containing *.pkg package (Mac). Sometimes it works and sometimes it doesn't. I tried for the exact same file and managed to get it working once and then get the failure for every other try.
What might be the problem?

**Comment by pornel** [comment]
Sorry, generate_appcast doesn't support pkg at all. Only .app in .zip or .tar. This is because it needs to read version information from Info.plist, but it doesn't know how to get that from a .pkg file.
