### ISSUE TITLE
Fails on case-sensitive APFS fs on High Sierra

### ISSUE THREAD

**Issue by CamJN** [sparkle-project/Sparkle#1133]
I get the following messages from apps that use the Sparkle Framework:
```
Update Error!

Tower can’t be updated when it’s running from a read-only volume like a disk image or an optical drive. Move Tower to your Applications folder, relaunch it from there, and try again.
```

```
Update Error!

Sketch can’t be updated when it’s running from a read-only volume like a disk image or an optical drive. Move Sketch to your Applications folder, relaunch it from there, and try again.
```

My filesystem is read/write but it is case-sensitive.

**Comment by pornel** [comment]
Are you sure its the filesystem, not the quarantine? Did you get that on an app that you've compiled, or a downloaded one?

**Comment by CamJN** [comment]
Ah it could be the new gatekeeper translocation thing (https://developer.apple.com/library/content/releasenotes/MacOSX/WhatsNewInOSX/Articles/OSXv10.html), sounds similar to this bug: https://github.com/potionfactory/LetsMove/issues/56

**Comment by CamJN** [comment]
Ok, deleting the quarantine xattr fixes the issue.
