### ISSUE TITLE
Updates install only when I start from console open -a Application.app

### ISSUE THREAD

**Issue by mn1aC** [sparkle-project/Sparkle#1136]
When I launch the app by double clicking it in the applications folder, it does not download updates. When I launch from console the application does the update...

**Comment by pornel** [comment]
When you launch the normal way, do you get any errors in Console.app?

In the application's preferences file `~/library/preferences/<bundle id>.plist` is the date of the last check correct?

**Comment by mn1aC** [comment]
The only error I could find on the SUUpdater

SandboxViolation: Optios(5169) deny mach-lookup com.apple.nsurlstorage-cache
Violation:       deny mach-lookup com.apple.nsurlstorage-cache 
Process:         Optios [5169]
Path:            /Applications/Optios.app/Contents/MacOS/Optios
Load Address:    0x1060b7000
Identifier:      net.optios.optios
Version:         1 (???)
Code Type:       x86_64 (Native)
Parent Process:  launchd [1]
Responsible:     /Applications/Optios.app/Contents/MacOS/Optios [5169]
User ID:         501

**Comment by mn1aC** [comment]
I cannot find a date for the last check in the ~/library/preferences/net.optios.client.plist file

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CDVUUID</key>
	<string>8416772D-BF85-4E25-9F31-E2D7D769C2E7</string>
	<key>WebKitCacheModelPreferenceKey</key>
	<integer>1</integer>
	<key>WebKitLocalStorageDatabasePathPreferenceKey</key>
	<string>/Users/svencornelis/Library/Application Support/net.optios.client</string>
</dict>
</plist>

**Comment by mn1aC** [comment]
I could not find the date in the .plist file

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CDVUUID</key>
	<string>8416772D-BF85-4E25-9F31-E2D7D769C2E7</string>
	<key>WebKitCacheModelPreferenceKey</key>
	<integer>1</integer>
	<key>WebKitLocalStorageDatabasePathPreferenceKey</key>
	<string>/Users/svencornelis/Library/Application Support/net.optios.client</string>
</dict>
</plist>`

**Comment by mn1aC** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CDVUUID</key>
	<string>8416772D-BF85-4E25-9F31-E2D7D769C2E7</string>
	<key>WebKitCacheModelPreferenceKey</key>
	<integer>1</integer>
	<key>WebKitLocalStorageDatabasePathPreferenceKey</key>
	<string>/Users/svencornelis/Library/Application Support/net.optios.client</string>
</dict>
</plist>`

**Comment by mn1aC** [comment]
<img width="904" alt="schermafbeelding 2017-10-12 om 12 17 41" src="https://user-images.githubusercontent.com/576657/31491466-b4b9393c-af47-11e7-86fb-cd4633fe15d3.png">

**Comment by mn1aC** [comment]
Is there any video tutorial available?
Because the doc is confusing imho: https://sparkle-project.org/documentation/

**Comment by pornel** [comment]
Is your app using sandboxing? If so, Sparkle 1.x will not work at all.  

We have an experimental version of Sparkle 2.x that supports sandboxing: https://github.com/sparkle-project/Sparkle/tree/ui-separation-and-xpc

**Comment by mn1aC** [comment]
I think the application doesn't need a sandbox. But I cannot disable it in xcode?
