### ISSUE TITLE
Callbacks and logging

### ISSUE THREAD

**Issue by jcredland** [sparkle-project/Sparkle#1138]
I've just managed to get Sparkle working with a C++ JUCE based project.  It was challenging, partially because of my poor Objective C but also because the instructions assume you are using an Xcode project file (click here, select that...).  So I've had to figure out how to do most of this from the command line.  Things are working though which is exciting.

I have some remaining issues though...

- Is there a callback when a log message is generated.  We have centralised logging and analytics. It would be nice to include the Sparkle logs.
- I'm not getting any Sparkle logs in my ~/Library/Logs either - should I be?
- Is there some way of finding out that it's Sparkle trying to quit the app?  We have some exit code that doesn't need to run if the user is updating - the user gets prompted about quitting twice at the moment.

**Comment by jcredland** [comment]
This issue needs a better title..

**Comment by bdb** [comment]
Sparkle uses the system log API so logs go there (the Console app, or the log CLI util on 10.12+).

There's a delegate callback to let you know that Sparkle will perform an install, you could assume that will cause the host app to be quit.

**Comment by jcredland** [comment]
Okay - All this stuff?  https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/SUUpdaterDelegate.h  Will figure it out!
