### ISSUE TITLE
Simplest way to bypass download functionality

### ISSUE THREAD

**Issue by vadi2** [sparkle-project/Sparkle#1140]
I already have the UI workflow and downloading functionality sorted out, and all I'd like Sparkle to do is replace the old application given a new .dmg. What is the simplest way I can go about making this happen?

I'm coding a cross-platform C++ app so I've got no experience with Objective-C++, so would like to keep that to a minimum.

**Comment by pornel** [comment]
Unfortunately we don't support such pick-and-mix functionality. There are separate classes that perform installation, so probably it wouldn't be too hard to rip them out if you were familiar with Objective-C.

However, keep in mind that Sparkle's protection against injection of malware into updates relies on DSA signatures present in the feed. If you're replacing that, be careful not to break/bypass the cryptographic verification of the downloads.

**Comment by vadi2** [comment]
Alright - thanks.
