### ISSUE TITLE
Update is extracted but can't be installed

### ISSUE THREAD

**Issue by vadi2** [sparkle-project/Sparkle#1143]
Continuing on from the pretty arduous journey of embedding this in a C++ app, I'm pretty close to make it work. It downloads the update, it unpacks the update, but it can't install it. It says the update will be available on a relaunch, but it isn't:

![](https://user-images.githubusercontent.com/110988/32006985-8d444f48-b9a8-11e7-91db-e96179a1fd2f.png)

Console.log says the following:
![](https://user-images.githubusercontent.com/110988/32006804-034170b4-b9a8-11e7-8bc3-02d67ee6bcb8.png)

I'm not sure why it thinks this, Sparkle seems to be working fine and I'm using the latest available release: 1.18.1.

The 3.5.0 version should update to a 3.5.2 version is freely available here: https://www.dropbox.com/s/zhkebbeabg8044o/Mudlet-3.5.0.dmg?dl=0

Any ideas what's going wrong?

**Comment by pornel** [comment]
The error message is unfortunately correct. The 3.5.0 lacks Autoupdate.app in Sparkle.framework's resources.

Is it your custom build? Autoupdate.app is in present our [official build](https://github.com/sparkle-project/Sparkle/releases/tag/1.18.1). 

I've seen this report before. Do you know what could have caused removal of the internal app?

**Comment by vadi2** [comment]
Yeah, a `.gitignore` file. Easy fix...
