### ISSUE TITLE
Are truly automatic updates possible?

### ISSUE THREAD

**Issue by vadi2** [sparkle-project/Sparkle#1145]
Are truly automatic, no user intervention updates - like Chrome on Windows - possible? I looked through the customisation options but didn't get a sense that it's available.

If they are, how can I also show the latest changelog manually after such an update has been performed?

**Comment by pornel** [comment]
It behaves like Chrome after user checks the box "automatically download and install all updates in the future" in the update window.

**Comment by pornel** [comment]
IIRC you can also enable that programmatically via `SUUpdater.automaticallyDownloadsUpdates = true`

**Comment by vadi2** [comment]
Awesome - and can I manually pull up the changelog for the user upon an update?

**Comment by pornel** [comment]
If user invokes "check for updates" manually, then a regular update window will open (or a one with "update is ready to install" if we manage to download the package before that).

but other than that the updates will be completely silent and changelog won't be shown.

**Comment by vadi2** [comment]
OK. Does Sparkle provide me with any facilities to check if an application was silently updated so I can pull up a changelog?

**Comment by pornel** [comment]
We've added exact method for this recently: #1115

**Comment by vadi2** [comment]
Great, thank you.
