### ISSUE TITLE
Update Old version of sparkle with Latest Sparkle version in My Application but Failed installation

### ISSUE THREAD

**Issue by praveen27Kmr** [sparkle-project/Sparkle#1148]
Hi,
I have an application with old sparkle version, i want to update sparkle with new version, but there is an error log with crash

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Applications/XXXX.app/Contents/MacOS/XXXX
  Reason: image not found 

 working correctly if Host application and Update application both have latest framwork 

my old framwork have identifier :- org.andymatuschak.Sparkle
![oldsparkleinfo](https://user-images.githubusercontent.com/21966068/32312275-0d8f453e-bfc3-11e7-9a2d-b72e0b8843cf.png)

Latest sparkle info plist
![newsparkleinfoplist](https://user-images.githubusercontent.com/21966068/32312257-ed2f9d8e-bfc2-11e7-98fe-8efa56a1a873.png)

**Comment by pornel** [comment]
In Build Settings tab set “Runpath Search Paths” to @loader_path/../Frameworks

**Comment by praveen27Kmr** [comment]
@pornel  i have already added -- 
I have already added  in my host application “Runpath Search Paths” to @loader_path/../Frameworks

**Comment by pornel** [comment]
Are you just replacing the Sparkle.framework and using an old executable? If so, that won't work. The change to search paths needs to be compiled into an executable. It means the old app must stay with old Sparkle forever.

**Comment by praveen27Kmr** [comment]
Hey Pornel,
Thanks for your response.
I want to clear some doubt, please provide me solution.

I have an App that have old version of Sparkle Framework as I mention in previous (1st) comment box.
I have release App update many time successfully.
Now I want to release App update with latest version of Sparkle ( I Mean my App's Update should have latest Sparkle Framework), is it possible or my App stay with old version of Sparkle forever.

Can I include the latest version of Sparkle in App Update build?

Thanks

**Comment by pornel** [comment]
If you compile a new version of the app, then you can use new version of Sparkle. 

The error you're getting (the app can't find Sparkle.framework) seems like you haven't done the configuration steps: https://sparkle-project.org/documentation/

If you've already set the rpath, then also ensure you have copying steps, etc. It's possible that Xcode has deleted your previous build steps if you're removed old sparkle from your app's project.

**Comment by praveen27Kmr** [comment]
Hi Pornel

My issue resolve now  when i change in  BUILD PHASE 
i only change App BUILD PHASE <copy  files > sparkle destination from frameworks to executables its working fine , is this ok to add sparkle framework from Frameworks to Executable folder of application

1. Its not working  when destination is Frameworks 

![screen shot 2017-11-03 at 5 08 25 pm](https://user-images.githubusercontent.com/21966068/32372302-47323696-c0ba-11e7-862a-a55ef31bfd44.png)


2. Its working fine when only change destination to executable
![screen shot 2017-11-03 at 5 14 20 pm](https://user-images.githubusercontent.com/21966068/32372360-7a7c04d2-c0ba-11e7-95a5-dae502462d6c.png)

**Comment by pornel** [comment]
If it works from executables folder, but not framework folder, it means you haven't set the rpath properly. Please double-check the Runpath Search Paths is set in the right place to the right value.

**Comment by praveen27Kmr** [comment]
this is Application configuration
![screen shot 2017-11-06 at 1 22 18 pm](https://user-images.githubusercontent.com/21966068/32430506-8e427d4c-c2f5-11e7-956f-e5a8bdead22e.png)

Sparkle configuration
![screen shot 2017-11-06 at 11 58 03 am](https://user-images.githubusercontent.com/21966068/32430584-f002a1ec-c2f5-11e7-979d-c5c7024fbb08.png)

I have set configuration setting but it showing me error what was before, please help pornel , i have done all configuration

**Comment by praveen27Kmr** [comment]
Hi pornel, when i build application there is sparkle frame work in build application , but when i used this application as a update On previous version of Application .The Application are used as root in Update pkg maker installer , when Installer going to install this application then installer shows failed error.

And Application with
 Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle

**Comment by praveen27Kmr** [comment]
Hi pornel,

PackageKit: Skipping component "org.sparkle-project.Sparkle" (*-1.18.1-*-*) because the version 1.5.0-313.0.0-*-* is already installed at /Applications/XXXX.app/Contents/Frameworks/Sparkle.framework.

this is the reason  which was stopping me to run my build 


PackageKit: Skipping component "org.sparkle-project.Sparkle" (*-1.18.1-*-*) because the version 1.5.0-313.0.0-*-* is already installed at /Applications/Advanced Mac Cleaner.app/Contents/Frameworks/Sparkle.framework.

**Comment by pornel** [comment]
Every app is supposed to have its own copy of Sparkle. Can you force PackageKit to include it?

**Comment by praveen27Kmr** [comment]
HI, pornel
i appreciate your work , my problem resolved now.

thanks
