### ISSUE TITLE
Best practice for including Sparkle in version control

### ISSUE THREAD

**Issue by vadi2** [sparkle-project/Sparkle#1150]
What's the best practice for including Sparkle in version control? Unzipping the latest release seems pretty heavyweight.

**Comment by pornel** [comment]
Personally I use it as a git submodule and Xcode subproject, although that compiles Sparkle from source for the project.

**Comment by pornel** [comment]
The alternative is to use CocoaPods to manage libraries, and then you only need to commit a podfile.

**Comment by vadi2** [comment]
Nice, thanks!
