### ISSUE TITLE
Installer Stuck after accepting update - Select A Destination

### ISSUE THREAD

**Issue by sleman** [sparkle-project/Sparkle#1152]
Been using sparkle for a long time with no issues. Now for my latest update, users get the update app within my app, accept it, my package is downloaded, the installer starts but gets stuck at Select A Destination (see attached). The strange thing is if I run the installer directly, it works fine and does not get stuck.
![select-a-destination](https://user-images.githubusercontent.com/976380/32983459-e7865fba-cc62-11e7-9d12-5f0e54772a11.png)

My package is built using productbuild. ```productbuild --component myAppName.app /Applications --sign "Developer ID Installer: XXX (YYY)" myAppName.pkg'```

**Comment by pornel** [comment]
Does it log anything to Console.app?

Does it install OK if you run `installer` from command line? (Sparkle's "guided" installer option)?

**Comment by sleman** [comment]
Good question. My earlier version of the app was sandboxed by mistake and when the installer ran from within the app, it didn't have rights to read the disk system. When is Sparkle going to handle sandboxed apps? I see a branch out there that has the work all done and tested but has not been merged to master.

```SandboxViolation: Installer(3180) deny mach-lookup com.apple.diskmanagementd
Violation:       deny mach-lookup com.apple.diskmanagementd 
Process:         Installer [3180]
Path:            /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
Load Address:    0x1014ef000
Identifier:      com.apple.installer
Version:         909 (6.2.0)
Code Type:       x86_64 (Native)
Parent Process:  dslrBooth [3177]
Responsible:     /Applications/dslrBooth.app/Contents/MacOS/dslrBooth [3177]
User ID:         501

Date/Time:       2017-11-20 10:30:43.108 EST
OS Version:      Mac OS X 10.12.6 (16G29)
Report Version:  8
```

**Comment by pornel** [comment]
OK, mystery solved.

As for sandbox. The 1.x branch does not support it and never will. The 2.x branch does support it, but we lack resources to finish it. Also it requires a newer macOS, so we may need to support both for a while.
