### ISSUE TITLE
generate_appcast generates appcast file with wrong information

### ISSUE THREAD

**Issue by MasonChien** [sparkle-project/Sparkle#1153]
Hi. I got a problem while using 1.18.1 Sparkle.

I have already set up all necessary setting in Xcode including DSA signature by the steps in https://sparkle-project.org/documentation/.

Then, I used generate_appcast to generate appcast file automatically.

Here's some information about my setup:

1. My app is packed into zip.
2. Appcast file and zip are received via http currently.
3. With DSA signature.

While generating the first appcast file, it worked fine. But it went wrong while generating files after (zip name is the same as the one in first generation).

The 'enclosure url', 'version' and other information in that line remained as the same as the information in the first appcast. But the information, 'pubDate' is correct.

It seemed that generate_appcast uses cache to generate files. I tried to modify the name of the directory where I put the zip, but it still generate wrong information.

Did I miss any step? Or is there a way to clean the cache for generate_appcast?

**Comment by pornel** [comment]
It does have a cache. It's `./.tmp` directory in the archive directory you give it.

It also tries to update the appcast in-place preserving other (manual) changes. You can try deleting the appcast to have it rebuilt from scratch.

**Comment by MasonChien** [comment]
Few hours after asking this question, I found the cache by myself. So I closed this question.

Still thanks for your reply. It's really a handy and great tool for me.

**Comment by kornelski** [comment]
In later Sparkle versions it's in `~/Library/Caches`
