### ISSUE TITLE
BinaryDelta create fails on network mounted NAS Device due to sym link permissions

### ISSUE THREAD

**Issue by sagecook** [sparkle-project/Sparkle#1156]
Symbolic links created on a drive mounted (AFP) from a NAS device are always created with 777 permissions meaning that "BinaryDelta create" will always reject them and fail.  Since the real files and directories have the correct 755 or 644 permissions it seems to me the symlinks should be ignored as they will effectively take on those permissions.  If we do not change BinaryDelta so it ignores symbolic link permissions it is unusable for network mounted directories.

**Comment by pornel** [comment]
Yeah, it should be skipping permissions for symlinks entirely.

**Comment by sagecook** [comment]
After thinking some more about this, there might still be a problem.  I have migrated all the old release directories to a NAS device which means all the old symlinks now have 777 (wish I could fix that).  Will new deltas fail to update if the symlinks are 755 in the field and 777 in the delta?  In other words, if the permission/mode of a symlink on a customer's machine does not match will that fail the install?  Or, can we have that check skipped as well?

**Comment by pornel** [comment]
symlinks just don't have permissions. They're always 777, and setting anything else doesn't do anything. Does NAS change this behavior?

**Comment by sagecook** [comment]
Here is what happens.  Say I have a directory on a local disk with permissions of 755.  When I go to the parent directory and make a symlink pointing to this directory the symlink will get the same permissions - 755.  Now I recursively copy this directory to a remotely mounted disk from my NAS device (mounted using AFP).  The directory on this disk has the same 755 permissions.  However, when I go to the parent directory and make a symlink pointing to this directory the symlink will now get 777 permissions.  I have tried "chmod -h 755" on the symlink which does nothing.  So, a symlink on a remotely mounted disk always gets 777 for some crazy reason.

**Comment by sagecook** [comment]
Let me add that the parent directory for the second scenario is also on the NAS.

**Comment by sagecook** [comment]
I have a fix.  How do I get permission to push a branch as a basis for a pull request?  I am very new to this.

**Comment by kornelski** [comment]
Pull request doesn't require any permissions in this project. First, create your **fork**, and then push changes to your fork.

**Comment by sagecook** [comment]
Very helpful.  I made the pull request.  If this is accepted and verified who would close this issue?

Thanks.

**Comment by zorgiepoo** [comment]
macOS file systems track/preserve permissions on symlinks. Some linux file systems don't (hence 0777). And some other file systems (eg FAT) don't support file permissions on any sort of file/directory. 

We can continue to ignore symlink permissions in general to appease linux or other based file systems that don't track that. There is no hope for file systems that don't store file permissions at all (everything is 0777).

But really, it's best to create deltas on macOS file systems. So we generate warnings when encountering odd file permissions, in case anything may be wrong. Refs #2061
