### ISSUE TITLE
Update downloaded as a HTML, can't extract

### ISSUE THREAD

**Issue by ncatta** [sparkle-project/Sparkle#1157]
Hello,

I setup sparkle for my MacOS app, the update is detected, but at the end of the update, I have this error : 
"Update Error!
Failed to extract update."
In the console, I have the following error : 
Error: No valid unarchiver for /Users/ncatta/Library/Caches/com.ncatta.appname/org.sparkle-project.Sparkle/appname 1216/appname.dmg.html

Seems that it is trying to interpret the file as HTML.
Here is my item in appcast.xml
```xml
<item>
<title>0.1.b6</title>
<pubDate>Thu, 30 Nov 2017 16:46:14 +0100</pubDate>
<sparkle:minimumSystemVersion>10.11</sparkle:minimumSystemVersion>
<enclosure url="https://company.com/update/appname/appname.dmg" sparkle:version="1216" sparkle:shortVersionString="0.1.b6" length="14912685" type="application/octet-stream" sparkle:dsaSignature="MCwCFFgi7IHRAAO9jqgzzzzz6q4UjKK0lC8TaTA=="/>
</item> 
```
Do you see anything that is wrong ? Here, the type tag seems ok...

Thanks by advance !

**Comment by pornel** [comment]
Check your server's configuration — use `curl -I https://…` to check the headers. Ensure the URL is valid and doesn't redirect to an HTML page, and is not sent as text/html.

**Comment by ncatta** [comment]
Thanks for the hint, actually, I redirect the URL to another one, that should be the problem !
I'll check that tomorrow !

Thanks again !
