### ISSUE TITLE
How would automatic update work?

### ISSUE THREAD

**Issue by vadi2** [sparkle-project/Sparkle#1159]
Following on from https://github.com/sparkle-project/Sparkle/issues/1145, I've set `SUEnableAutomaticChecks`, `SUAllowsAutomaticUpdates`, and `SUAutomaticallyUpdate` all to `true` to ensure that automatic updates are on by default. The .dmg that has these settings is [Mudlet 3.6.0](https://www.mudlet.org/wp-content/files/Mudlet-3.6.0.dmg) and there is 3.6.1 available [according to the feed](https://feeds.dblsqd.com/MKMMR7HNSP65PquQQbiDIw/release/mac/x86_64/appcast).

I've left the application on all day, and when I came back there were no updates presented - or applied when I restarted the application.

As I've never seen it work before I'm not sure if I did anything wrong, so, how are truly automated updates supposed to ideally work?

**Comment by pornel** [comment]
It's not clear, but all these options still require user to opt in by checking a checkbox "automatically download and install updates in the future". They exist only to disable that checkbox.

**Comment by vadi2** [comment]
Hm. Thats unfortunate, I would like to see automated updates by default ala browsers.

Thanks for clarifying.
