### ISSUE TITLE
Instructions in INSTALL need to be improved

### ISSUE THREAD

**Issue by guidedways** [sparkle-project/Sparkle#1164]
The instructions need to be exhaustive, so newbies are able to follow each step in order to have their MAS (+ externally distributed) Sandboxed apps working in both scenarios. As it stands, the instructions gloss over details and the 'Documentation' page still links back to v1.x and contains no useful instructions on how to properly have their Sandboxed apps setup with Sparkle.

**Comment by pornel** [comment]
Yes, indeed. The docs are not done yet.

**Comment by guidedways** [comment]
Is there an unofficial guide somewhere that I could follow to set this up? I've had no success in getting my app hooked up with Sparkle. I feel there's an assumption that new users would just know how Sparkle works. The old documentation would potentially suffice, however I've had no success in hooking this up with a sandboxed app, yet everyone else seems to be happy with this branch.

**Comment by kornelski** [comment]
No, I'm sorry, docs for the sandbox-compatible version are just not written yet.

**Comment by zorgiepoo** [comment]
New website documentation has been updated here.
