### ISSUE TITLE
Scheduling the NSURLDownload loader is no longer supported.

### ISSUE THREAD

**Issue by spogra** [sparkle-project/Sparkle#1166]
Unable to download appcast.xml because of NSURLDownload is no longer supported.

**Comment by pornel** [comment]
Compile with earlier version of macOS as the deployment target.

Apart from that it's a know issue, and a fix is coming: #1165

**Comment by spogra** [comment]
I had tried with 10.7 as a deployment target but still getting  same issue.

**Comment by victorct** [comment]
Any update on this?

**Comment by kornelski** [comment]
It's done in master

**Comment by victorct** [comment]
@kornelski  Awesome, is there any release that contains the fix?

**Comment by kornelski** [comment]
https://github.com/sparkle-project/Sparkle/releases/tag/1.19.1rc1
