### ISSUE TITLE
Provide a different appcast item depending on the current app version 

### ISSUE THREAD

**Issue by 1024jp** [sparkle-project/Sparkle#1168]
Is there any way to provide a different appcast `item` depending on the current application version?

For example:
- when the current application version is under 2.0.0 (200), provide the first item with a special release note page and avoid direct download from the Sparkle window (but just a link to a download page).
- otherwise, provide the second item with normal release notes and download.   

```
<channel>
<item>
	<title>MyApp 2.0.1</title>
	<sparkle:releaseNotesLink>https://example.com/new_featues.html</sparkle:releaseNotesLink>
	<pubDate>Mon, 1 Jan 2018 12:00:00</pubDate>
	<sparkle:shortVersionString>2.0.1</sparkle:shortVersionString>
	<sparkle:version>201</sparkle:version>
	<link>https://example.com/download/</link>
</item>

<item>
	<title>MyApp 2.0.1</title>
	<sparkle:releaseNotesLink>https://example.com/releasenotes.html</sparkle:releaseNotesLink>
	<pubDate>Mon, 1 Jan 2018 12:00:00</pubDate>
	<enclosure url="https://example.com/download/MyApp_2.0.1.dmg"
	           sparkle:version="2.0.1"
	           sparkle:dsaSignature="XXXXXXXXXX="
	           length="512"
	           type="application/octet-stream" />
</item>
</channel>
```

In my case, the web server accepts only static pages. Therefore, I cannot dynamically build an appcast file by a user agent.

**Comment by kornelski** [comment]
You can do it server-side using user-agent sniffing.

Sparkle puts "app name/version" in User-Agent header. You can process appcast responses using some server-side tech (e.g. rewrite the appcast URL to be handled a PHP file) and serve different versions of the appcast file (or dynamically generate one).

**Comment by 1024jp** [comment]
Thank you for the answer.
It seems I should provide another appcast for upper versions and let them target the new one to fulfill my needs.
Anyway, thanks.
