### ISSUE TITLE
Why can't sparkle update the app when the app is located in ~/Downloads folder

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#1169]
Sparkle is not able to update an app, when the location of the app is in the Downloads folder. It shows the following error.

"App can't be updated when it's running from a read-only volume like a disk image or an optical drive. Move Microsoft Bing Ads Editor to your Applications folder, relaunch it from there, and try again."

I don't think Downloads folder is a read-only folder either. Any suggestions on the best way to fix this?

Any help is appreciated!

Thank you!

**Comment by kornelski** [comment]
We've updated the message in a later version of Sparkle to explain what happens exactly. 

Apple added a security feature that when you run an app that wasn't copied using Finder to app folder or other permanent location, it is silently run from a read-only jail.

**Comment by prasha6** [comment]
May I know what is the fix in the latest version of sparkle?  Would the latest version of Sparkle prevent the app from being translocated or would it just provide a user -friendly message of what has happened and let the user know how to work around it ?

If it is just the message that has been updated, could you point me to the Pull Request of this change? I want to know what the updated message is.

**Comment by kornelski** [comment]
Sparkle can't do anything about it. It's a security measure imposed by macOS.

The only difference is that latest version just tells the user to use Finder to copy the app.

**Comment by kornelski** [comment]
#1057
