### ISSUE TITLE
The identity of the developer cannot be confirmed.

### ISSUE THREAD

**Issue by prakashjat** [sparkle-project/Sparkle#1173]
Hello,
My Application not opened, showing the popup "App name" can’t be opened because the identity of the developer cannot be confirmed.

I Found that Sparkle.framework 's info.plst don't have key "CFBundleSupportedPlatforms".

Now What will I do? Please response as soon as possible, My Application is live as in  DMG file. 

![screen shot 2018-01-24 at 9 18 28 pm](https://user-images.githubusercontent.com/35773534/35341796-81503a62-014c-11e8-8e6f-06fcf5d6be8e.png)

One more thing if I used Sparkle.framework updated version then my app that having old Sparkle.framework, will not update.

**Comment by prakashjat** [comment]
@kornelski Please reply as soon as possible

**Comment by uranusjr** [comment]
This is not about Sparkle. You need to pay ~ransom~ developer registration fee to Apple, get a certificate, and codesign your app.

**Comment by prakashjat** [comment]
Certificate and codesign are up to date.
we found that a key CFBundleSupportedPlatforms is not present in sparkle framework that I used.

sparkle framework version 
Bundle versions string, short = 1.5 Beta 6

**Comment by kornelski** [comment]
You can't use Sparkle 1.5 on modern macOS.

**Comment by prakashjat** [comment]
Hi kornelski 
Thanks for reply, I use latest version in new apps,
But the issue with my exiting app, How to resolved this issue in exiting application.

**Comment by kornelski** [comment]
You have to make a new version of your app with new a version of Sparkle, and release that.

**Comment by prakashjat** [comment]
Hi kornelski

RE: You have to make a new version of your app with new a version of Sparkle, and release that.

In this case, If I release an update of My app then, App is not update over old Sparkle with new version of Sparkle.

**Comment by kornelski** [comment]
Sorry, I don't understand your question.
