### ISSUE TITLE
This method must be called on main thread: [suUpdater setFeedURL: [NSURL URLWithString:@"my-url"]];

### ISSUE THREAD

**Issue by jonadiazz** [sparkle-project/Sparkle#1175]
Hi,
I am having a difficult time to implement Sparkle with a Java app.

Currently, I have a Java Native Interface to connect with an Objective-C class which then calls Sparkle. My issue is that it always tells me 

```
*** Terminating app due to uncaught exception 'SUThreadException', reason: 'This method must be called on the main thread'
```

This is the piece that throws the exception: 

`[suUpdater setFeedURL: [NSURL URLWithString:@"my-url"]];`

**What I did:** 

-  Checked if I am calling from Java Main thread which I am.
-  Used `performSelectorOnMainThread:@selector(setFeedURL)` but it tells me is an invalid argument

Any help or pointers to solve this issue will be much appreciated

**Comment by jkbullard** [comment]
@jonadiazz - Try

`[suUpdater performSelectorOnMainThread:@selector(setFeedURL:) withObject:[NSURL URLWithString:@"my-url"] waitUntilDone:NO];`

Note the colon after "setFeedURL". Depending on your situation, you might want `…waitUntilDone:YES…`.

You might have to do this with other methods, too. If a method doesn't take any arguments, you just use `…@selector(foo) withObject:nil…` (where foo -- without the colon -- is the name of the method that doesn't take any arguments).

The only glitch might be if Java is blocking the executable's main thread. I'm not sure what you do if that's the situation.

**Comment by jonadiazz** [comment]
```[suUpdater performSelectorOnMainThread:@selector(setFeedURL:) withObject:[NSURL URLWithString:@"my-url"] waitUntilDone:NO];```

I was indeed not using semicolon to indicate it takes parameters. Big thanks @jkbullard 

As of now, I am not the main thread is not getting blocked BTW
