### ISSUE TITLE
Preferred way of changing maintainer of a project [Advice needed]

### ISSUE THREAD

**Issue by ifeherva** [sparkle-project/Sparkle#1176]
Project A's original developer decided to stop working on the project but happy to pass the ownership to me. He is open to help in the transition process, not beyond that, meaning he is okay signing the next 1-2 releases, but not more.

The app is originally signed only by his official Developer ID, no extra DSA keys are used.

What would be the preferred way of transferring the ability of creating releases without breaking the update chain for the users?

**Comment by kornelski** [comment]
Release an update that has:

* Original developer's Apple Signing ID
* Your DSA public key
* DSA signature with your private key
* *New appcast URL*

And leave that update available for a long time (indefinitely).

Under the new appcast URL you can start releasing apps with your DSA signature and your Apple Signing ID.

**Comment by jleclanche** [comment]
Hey @kornelski thanks for the reply. Let me clarify: The appcast URL isn't changing (we're hosting the appcast ourselves on a custom domain already), only the signing key. We have a signing key/id org.original.foo, changing to org.new.foo. We have access to both signing keys but want to transfer to the new one.
What we did was cross-sign the update with the original signing ID + @ifeherva's DSA key, then planning to release a new update afterwards cross-signed with @ifeherva's DSA key and the new signing key. But step 1 did not work, so we're trying to figure out if we're doing it wrong.

Does the appcast URL actually need to change for this transition to happen? (Why?)

**Comment by kornelski** [comment]
I suggest changing the URL (you can keep the domain, but change filename or something). This is to keep old clients checking the old URL and finding only the specific transitional update. Otherwise you won't be able to release a *second* release after the transition without locking out clients that skipped a version.

**Comment by kornelski** [comment]
We never tested changes of bundle ID. I don't think it will work.

**Comment by kornelski** [comment]
See Console.app for explanation why signing didn't work.

**Comment by ifeherva** [comment]
So what we did was that the original developer used his Apple Dev certificate to sign the app but we included my public dsa key in the resources folder (+plist key) as described in the docs. The error we get now is the following:

> DSA signature validation failed. The update has a public DSA key and is signed with a DSA key, but the new public key shipped with the update doesn't match the signature. The update will be rejected.

**Comment by kornelski** [comment]
This is what it says. Sign again, making sure you use correct private key.

**Comment by ifeherva** [comment]
So the original developer is supposed to sign it with my private DSA key? Sorry, I am quite confused.

**Comment by kornelski** [comment]
No, you should sign with your private key.

The error you get could be because:

* the app contains public part of a wrong key
* the app was signed using wrong private key
* the signature wasn't copied correctly into the appcast

Try generate_appcast app if you haven't already.

**Comment by ifeherva** [comment]
I tried re-generating the appcast which was a good idea since it was missing the DSA part. Now I get this error message:

Code signature of the new version doesn't match the old version: anchor apple generic and identifier "be.michotte.hstracker" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists / or certificate 1[field.1.2.840.113635.100.6.2.6] / exists / and certificate leaf[field.1.2.840.113635.100.6.1.13] / exists */ and certificate leaf[subject.OU] = GZ37WWWK6W). Please ensure that old and new app is signed using exactly the same certificate.

Is this because we changed the bundle id?

**Comment by kornelski** [comment]
I've checked the code, and it has two options:

* You deliver update as a `.pkg` installer that is entirely responsible for updating the app. In such case you can change the bundle identifier, but it's 100% up to you to figure out what and how to update.

* Or Sparkle looks for a bundle with exactly the same bundle ID. If it can't find it, it fails with `SUMissingUpdateError`. So there's no way to change bundle ID using update containing `.app` bundle (zip/tar/dmg *can't change bundle ID*).

So please never ever change bundle identifier as this fucks things up badly.

**Comment by C4Framework** [comment]
@kornelski ☝️ Is this all still relevant today?

**Comment by kornelski** [comment]
Yes, changing bundle ID is still a terrible idea and is going to break stuff.

**Comment by C4Framework** [comment]
@kornelski Thanks, really helpful.
