### ISSUE TITLE
Branch: "ui-separation-and-xpc" wants to update to beta releases

### ISSUE THREAD

**Issue by core-code** [sparkle-project/Sparkle#1178]
1.) download MongoHub [https://github.com/jeromelebel/MongoHub-Mac] from its official download [https://mongohub.s3.amazonaws.com/MongoHub.zip]

2.) launch MongoHub and check for updates ... you get the message "MongoHub 3.1.4 is currently the newest version available."  which is absolutely correct.

3.) download the "ui-separation-and-xpc" branch and build sparkle-cli...if you use it to check MongoHub, it incorrectly claims there is an update to 3.1.5b1 available. if you use to to update it tries to update to 3.1.5b. since 3.1.5b is marked as 'beta' in the channel it should be ignored like previous versions of sparkle did. please restore that behaviour

**Comment by kornelski** [comment]
That is unintentional, and it's surprising, because code that compares versions didn't change.

**Comment by core-code** [comment]
i figured as much, because neither that branch nor the old one actually seem to contain something that handles 'beta' versions, so i am not sure what goes on here. that said, it would be nice if beta versions could be ignored unless otherwise specified.

**Comment by core-code** [comment]
furthermore, the CLI tool from the 'ui-separation-and-xpc' branch sometimes downgrades releases:

1.) download Transmission 2.93 from here https://github.com/transmission/transmission-releases/raw/master/Transmission-2.93.dmg
2.) run 'sparkle --verbose --check-immediately Transmission.app' ....
3.) it tries to downgrade to 2.84: 
Checking for Updates...
Found new update! (2.84)
Downloading Update...
Release notes:


note that the built in -check for updates in 2.93 does not do that.

**Comment by core-code** [comment]
same for the 'Localization Suite' downloadable here ( http://www.loc-suite.org/pub/stable/Localization%20Suite.tbz ) ... the CLI tool wants to 'update' (from 12.10) to the oldest item in the feed, version 3.0rc

**Comment by core-code** [comment]
forgot to mention, here the in-app check also doesn't have the problem so its tied to the XPC branch

**Comment by zorgiepoo** [comment]
Version of Transmission here uses strange CFbundleVersion (3c5870d4f5) so no surprises. Apps can use custom version comparators that external updater would have no idea about. Closing out as I believe these are all such edge cases.
