### ISSUE TITLE
Update downloads delta AND full archive

### ISSUE THREAD

**Issue by yanone** [sparkle-project/Sparkle#1179]
Hi all,

I've successfully got my Sparkle integration up and running, including delta generation and inclusion in the `appcast.xml`.

On update, the installer first downloads the delta (1.3MB), and instantly afterwards the full archive (over 30MB), then installs successfully.

This is with `Sparkle-1.19.0rc1`. I tried `1.18` earlier, but it had that segmentation fault issue for delta generation.

What am I doing wrong?

Here's my appcast.xml:

```
<?xml version="1.0" standalone="yes"?>
<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
<channel>
<title>Type.World</title>

<item>
	<title>0.1.1</title>
	<pubDate>Wed, 31 Jan 2018 20:01:14 +0000</pubDate>
	<sparkle:minimumSystemVersion>10.7</sparkle:minimumSystemVersion>
	<enclosure url="https://type.world/downloads/guiapp/TypeWorldApp.0.1.1.dmg" sparkle:version="0.1.1" sparkle:shortVersionString="0.1.1" length="38733695" sparkle:dsaSignature="MEUCIQDiuL1XoreYOecGPRUHX2HUpdRqVMYAjq8jEFClOYsk1QIgSROmcGfg2Aq76ZfWdIyVT3f60pjkDviMQLwV4SJCaMM=" type="application/octet-stream" />
	<sparkle:deltas>
		<enclosure url="https://type.world/downloads/guiapp/Type.World0.1.1-0.1.0.delta" sparkle:version="0.1.1" sparkle:shortVersionString="0.1.1" sparkle:deltaFrom="0.1.0" length="1251235" sparkle:dsaSignature="MEUCIF+GKGyvfHt6RH6m0lqS7L2bTqkGXmgjhabdrwKOZ/ScAiEAjSeS2csduVP28fiVMHINXGapBYh8CWZ7QBGZ5ENe0do=" type="application/octet-stream" />
	</sparkle:deltas>
</item>

<item>
	<title>0.1.0</title>
	<pubDate>Wed, 31 Jan 2018 19:59:15 +0000</pubDate>
	<sparkle:minimumSystemVersion>10.7</sparkle:minimumSystemVersion>
	<enclosure url="https://type.world/downloads/guiapp/TypeWorldApp.0.1.0.dmg" sparkle:version="0.1.0" sparkle:shortVersionString="0.1.0" length="38732777" sparkle:dsaSignature="MEQCIEDJGze2OFf3KsUdFJq91ounZzSwYRCKt1qvEmzuPmndAiBvYUVmOzMdTIMU4IbsiNyfgWYqNba2S6s4dobM6nFWnw==" type="application/octet-stream" />
</item>

</channel>
</rss>
```

**Comment by kornelski** [comment]
Full archive will be downloaded if the delta fails to apply cleanly.  That's almost always because the app bundle on user's disk is not identical to the app bundle used to create the delta archive.

**Comment by kornelski** [comment]
BTW, did you generate the appcast using the `generate_appcast` tool? It makes delta archives using Sparkle's internal functions, so it should be pretty robust.

**Comment by yanone** [comment]
I generated the deltas with `generate_appcast`, but then wrote the `appcast.xml` through my own script, as `generate_appcast` doesn’t add deltas to `appcast.xml`, nor dsa signatures, not speaking of metadata like release notes.

I'm fairly sure that the app is identical. I put it in dmgs, sign the dmg with `sign_update`, generate deltas, then sign the deltas. 

Here's the Console output since I started the update process until after the full archive was downloaded:

```
standard	08:34:46.682387 +0200	Type.World	TIC Enabling TLS [2:0x604000169a80]
standard	08:34:46.682421 +0200	Type.World	TIC TCP Conn Start [2:0x604000169a80]
standard	08:34:46.682589 +0200	Type.World	Task <DFE469B5-2351-47BB-9504-6ECE643D0EF3>.<1> setting up Connection 2
standard	08:34:48.009043 +0200	Type.World	TIC TLS Event [2:0x604000169a80]: 1, Pending(0)
standard	08:34:48.134775 +0200	Type.World	TIC TLS Event [2:0x604000169a80]: 2, Pending(0)
standard	08:34:48.136461 +0200	Type.World	TIC TLS Event [2:0x604000169a80]: 11, Pending(0)
standard	08:34:48.137975 +0200	Type.World	TIC TLS Event [2:0x604000169a80]: 12, Pending(0)
standard	08:34:48.138584 +0200	Type.World	TIC TLS Event [2:0x604000169a80]: 14, Pending(0)
standard	08:34:48.144830 +0200	Type.World	TIC TLS Trust Result [2:0x604000169a80]: 0
standard	08:34:48.263007 +0200	Type.World	TIC TLS Event [2:0x604000169a80]: 20, Pending(0)
standard	08:34:48.263213 +0200	Type.World	TIC TCP Conn Connected [2:0x604000169a80]: Err(16)
standard	08:34:48.263481 +0200	Type.World	TIC TCP Conn Event [2:0x604000169a80]: 1
standard	08:34:48.263515 +0200	Type.World	TIC TCP Conn Event [2:0x604000169a80]: 8
standard	08:34:48.263556 +0200	Type.World	TIC TLS Handshake Complete [2:0x604000169a80]
standard	08:34:48.264209 +0200	Type.World	Task <DFE469B5-2351-47BB-9504-6ECE643D0EF3>.<1> now using Connection 2
standard	08:34:48.264314 +0200	Type.World	Task <DFE469B5-2351-47BB-9504-6ECE643D0EF3>.<1> sent request, body N
standard	08:34:48.366781 +0200	Type.World	Task <DFE469B5-2351-47BB-9504-6ECE643D0EF3>.<1> received response, status 200 content K
standard	08:34:50.207312 +0200	Type.World	Task <DFE469B5-2351-47BB-9504-6ECE643D0EF3>.<1> response ended
standard	08:34:50.220395 +0200	Type.World	CSSM Exception: -2147415792 CSSMERR_CSP_INVALID_KEY
standard	08:34:50.399462 +0200	Type.World	TIC Enabling TLS [3:0x6000001684c0]
standard	08:34:50.399488 +0200	Type.World	TIC TCP Conn Start [3:0x6000001684c0]
standard	08:34:50.399581 +0200	Type.World	Task <4FF56956-3771-4F03-BDFB-57BE8E099D05>.<1> setting up Connection 3
standard	08:34:50.510385 +0200	Type.World	TIC TLS Event [3:0x6000001684c0]: 1, Pending(0)
standard	08:34:50.623809 +0200	Type.World	TIC TLS Event [3:0x6000001684c0]: 2, Pending(0)
standard	08:34:50.627936 +0200	Type.World	TIC TLS Event [3:0x6000001684c0]: 11, Pending(0)
standard	08:34:50.629846 +0200	Type.World	TIC TLS Event [3:0x6000001684c0]: 12, Pending(0)
standard	08:34:50.630894 +0200	Type.World	TIC TLS Event [3:0x6000001684c0]: 14, Pending(0)
standard	08:34:50.639733 +0200	Type.World	TIC TLS Trust Result [3:0x6000001684c0]: 0
standard	08:34:50.751544 +0200	Type.World	TIC TLS Event [3:0x6000001684c0]: 20, Pending(0)
standard	08:34:50.751751 +0200	Type.World	TIC TCP Conn Connected [3:0x6000001684c0]: Err(16)
standard	08:34:50.752067 +0200	Type.World	TIC TCP Conn Event [3:0x6000001684c0]: 1
standard	08:34:50.752123 +0200	Type.World	TIC TCP Conn Event [3:0x6000001684c0]: 8
standard	08:34:50.752185 +0200	Type.World	TIC TLS Handshake Complete [3:0x6000001684c0]
standard	08:34:50.752889 +0200	Type.World	Task <4FF56956-3771-4F03-BDFB-57BE8E099D05>.<1> now using Connection 3
standard	08:34:50.753014 +0200	Type.World	Task <4FF56956-3771-4F03-BDFB-57BE8E099D05>.<1> sent request, body N
standard	08:34:50.846892 +0200	Type.World	Task <4FF56956-3771-4F03-BDFB-57BE8E099D05>.<1> received response, status 200 content K
standard	08:34:55.409617 +0200	Type.World	TIC TCP Conn Event [1:0x604000166d80]: 2
standard	08:34:55.409732 +0200	Type.World	TIC TCP Conn Cancel [1:0x604000166d80]
standard	08:35:10.720162 +0200	Type.World	TIC TCP Conn Event [2:0x604000169a80]: 2
standard	08:35:10.720236 +0200	Type.World	TIC TCP Conn Cancel [2:0x604000169a80]
standard	08:35:40.060487 +0200	Type.World	Task <4FF56956-3771-4F03-BDFB-57BE8E099D05>.<1> response ended
standard	08:35:42.075794 +0200	kernel	hfs: mounted Type.World App on device disk3s1
standard	08:35:42.178855 +0200	Type.World	copyItemAtPath:/Volumes/989C9BEB-6074-4E19-9785-D9544AB2115C/Type.World.app toPath:/Users/yanone/Library/Caches/world.type.guiapp/org.sparkle-project.Sparkle/PersistentDownloads/qIk16i3Fm/Type.World 0.1.1/Type.World.app
standard	08:35:42.988015 +0200	kernel	hfs: unmount initiated on Type.World App on device disk3s1
```

What comes to attention is this line: `CSSM Exception: -2147415792 CSSMERR_CSP_INVALID_KEY`.
Can you make any sense of that?

**Comment by yanone** [comment]
Btw, I signed my app using `codesign`, and it verifies and loads fine on MacOS. However, I didn't sign that app itself using your `sign_update`, as I didn't find that written anywhere. I only sign the dmg and delta files.

**Comment by kornelski** [comment]
DSA signatures for DMG and delta are fine. 

I'm surprised that `generate_appcast` didn't sign them - it totally should. It also should make delta updates if you give it folder with archives of multiple versions of the app, and the delta files are 15%+ smaller than the full archive.

**Comment by kornelski** [comment]
The log unfortunately doesn't show anything abnormal (the CSSM stuff is not Sparkle's)

**Comment by yanone** [comment]
> I'm surprised that generate_appcast didn't sign them - it totally should.

How can I tell?
The point here is that it doesn't fill any signatures into the `appcast.xml`, so I'm blind to what their signatures are.

> It also should make delta updates if you give it folder with archives of multiple versions of the app, and the delta files are 15%+ smaller than the full archive.

It does. But again, it doesn't include that information into the `appcast.xml`, so I wrote myself a script for both the above inclusions, and more.

So there's nothing I can look for?

**Comment by kornelski** [comment]
generate_appcast adds signatures to the appcast in the form of `sparkle::dsaSignature` attributes whenever it's able to make them, i.e. if it is given the private key and signing succeeds.

**Comment by kornelski** [comment]
https://github.com/sparkle-project/Sparkle/blob/3afa47b09202389db600cbeb1e8c8797acbb97b9/generate_appcast/Appcast.swift#L86-L104

So it should print an error if signing of the delta failed.

**Comment by yanone** [comment]
Okay, I found more feedback.
The command `~/Code/Sparkle/bin/generate_appcast ~/Code/dsa_priv.pem ~/Code/TypeWorldApp/dmg` yields the following output:

```
Type.World0.1.1-0.1.0.delta Error Domain=Internal CSSM error Code=-2147416063 "Internal error #80010801 at SignTransform_block_invoke /BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-58286.31.2/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:276" UserInfo={NSDescription=Internal error #80010801 at SignTransform_block_invoke /BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-58286.31.2/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:276, Originating Transform=CoreFoundationObject}
file:///Users/yanone/Code/TypeWorldApp/dmg/TypeWorldApp.0.1.1.dmg 0.1.1 Error Domain=Internal CSSM error Code=-2147416063 "Internal error #80010801 at SignTransform_block_invoke /BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-58286.31.2/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:276" UserInfo={NSDescription=Internal error #80010801 at SignTransform_block_invoke /BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-58286.31.2/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:276, Originating Transform=CoreFoundationObject}
file:///Users/yanone/Code/TypeWorldApp/dmg/TypeWorldApp.0.1.0.dmg 0.1.0 Error Domain=Internal CSSM error Code=-2147416063 "Internal error #80010801 at SignTransform_block_invoke /BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-58286.31.2/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:276" UserInfo={NSDescription=Internal error #80010801 at SignTransform_block_invoke /BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-58286.31.2/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:276, Originating Transform=CoreFoundationObject}
Written /Users/yanone/Code/TypeWorldApp/dmg/appcast.xml based on 2 updates
```

**Comment by yanone** [comment]
Google says, the above error message hints at problems with accessing a private key in Mac's keychain. But as far as I know, this keychain shouldn't be involved in the creation of the deltas or signing the dmgs and deltas with the private dsa key.
:/

**Comment by yanone** [comment]
I got it to work.
Instead of using `generate_appcast` to calculate the deltas, I'm now using `BinaryDelta`, which yields a 2.2MB delta instead of 1.3MB from earlier. There are no error messages regarding keychain stuff.
I sign all files using `sign_update`, then create my own `appcast.xml`.

Now the delta installs cleanly.

This clearly hints at `generate_appcast` being broken. The rest is on you, mate. 

Regardless of the errors, I find `generate_appcast` not very useful. It doesn't allow control over the amount of versions included in delta generation. I think I want to provide deltas for up to 10 versions, maybe, tops. If I do everything manually, I have full control over how many deltas to make.
Then, `generate_appcast` doesn't allow inclusion of release notes or the likes, so I have to meddle with the `appcast.xml` anyway, either changing its XML tree or rewriting it from scratch. So personally I'm happy to do it all step by step.

Please close this issue at your own discretion. Personally I'm done here.
Thanks for the amazing work, though.
