### ISSUE TITLE
How to know if AutoUpdate.app has launched successfully

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#1182]
Hi,

I am currently having a problem, where a silent update (automatically download updates) is getting downloaded but not installed.

I understand that Sparkle launches AutoUpdate.app before the app quits, and the AutoUpdate.app waits for the host app to terminate and then installs the update.

I am suspecting the AutoUpdate.app may not be launched at the first place at all, causing this problem. How do I know if AutoUpdate.app is launched or not? Perhaps, I can add some logging to find this, but what would be the right place to add this logging?

PS: However, when AutomaticallyDownloadUpdates is false, and the update is installed through the Sparkle UI, I am able to install the update.

**Comment by kornelski** [comment]
Everything Sparkle does, or fails to do, is logged to the Console.app, so look there for clues.

**Comment by kornelski** [comment]
Another issue may be that auto updates are installed only when the app gracefully quits via Cocoa's termination mechanism. If you kill the app, `exit()`, reboot your system, or such, then autoupdate won't have chance to run.

**Comment by prasha6** [comment]
When auto download of updates is turned off, and updates are installed through the Sparkle UI by clicking on 'Install Updates'- is the same workflow of launching AutoUpdate.app followed ?

**Comment by kornelski** [comment]
Yes

**Comment by ruslanmin** [comment]
Hi,

I have the same problem on MacOS High Sierra, the update is downloaded with GUI and after I click on "Install update" it just stuck and do nothing, and Console says me:

**Failed to release quarantine on /Users/username/Library/Containers/...../org.sparkle-project.Sparkle/NameOfTheApp (Autoupdate).app with error Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedDescription=Failed to remove file quarantine on NameOfTheApp (Autoupdate).app.}**

In the folder "/Users/username/Library/Containers/...../org.sparkle-project.Sparkle/" I don't have any app with name "NameOfTheApp (Autoupdate).app", I have app called NameOfTheApp.app

Why it happens? Is it bug in Sparkle? 

Thanks 
Ruslan

**Comment by kornelski** [comment]
Sparkle's Autoupdate.app is copied to a temporary folder under a name of host's app + (Autoupdate).app. This is done to make admin auth prompt, etc. do display a familiar name rather than a generic Autoupdate.app name.

It's not necessary a problem if quarantine removal fails. Do you get other errors?

**Comment by DarkDust** [comment]
I'm seeing the same issue: "Install update" is just stuck, in the console I get "Failed to release quarantine" (exactly like @ruslanmin) and nothing else in Console.app. 

Trying to launch `MyApp (Autoupdate).app` in the Finder or Terminal fails. Finder simply says the app can't be opened, when I try to `open "MyApp (Autoupdate).app"` in Terminal I get:

> LSOpenURLsWithRole() failed with error -54 for the file /path/to/MyApp (Autoupdate).app

Trying to directly call `MyApp (Autoupdate).app/Contents/MacOS/Autoupdate` in the Terminal also fails with "operation not permitted".

I then removed the quarantine via `xattr  -r -d com.apple.quarantine "MyApp (Autoupdate).app"` and then tried to run it again, but it still fails:

> LSOpenURLsWithRole() failed with error -10810 for the file /path/to/MyApp (Autoupdate).app

This is happening on High Sierra and Mojave.

Is there additional data you need for this issue?

**Comment by DarkDust** [comment]
Oh, I also seen an exception `launch path not accessible` being raised.

**Comment by DarkDust** [comment]
OMG… reading through other issues: does Sparkle 1.20 still not support sandboxed apps? Since there was no mention of sandbox in README.md I was under the impression that we don't need to use the old `ui-separation-and-xpc` branch any more. That's… unpleasant. 😩

**Comment by kornelski** [comment]
* The 1.x version will never support sandboxed apps.

* Currently we have no volunteers who would like to continue developing 2.x with sandbox support (I don't use sandboxing, and I'm busy with many other projects, so I have more pressing issues than working on a feature I don't use).

**Comment by DarkDust** [comment]
I understand and like to apologize for the my rude tone. Would you mind putting a note in the README.md about missing Sandbox support? It would have saved me a few hours of work. Thanks.

**Comment by kornelski** [comment]
Sure

**Comment by digitalmoksha** [comment]
> Currently we have no volunteers who would like to and are available to continue developing 2.x with sandbox support (I don't use sandboxing, and I'm busy with many other projects, so I have more pressing issues than working on a feature I don't use).

Oh that's a bummer.  And I can only imagine how busy you are.

I've been meaning to update my build of that branch - is it still working?

Is there a set of (or one) issue that lays out what we need to do for a V2?  Maybe the community can start contributing towards that.

**Comment by kornelski** [comment]
V2 branch needs documentation. It may be the biggest blocker. If you could contribute to the website repo with install guide, that would be super helpful. 

Beyond that it needs testing and merge of changes from master. 

One big thing missing is the recent addition of EdDSA keys.

**Comment by digitalmoksha** [comment]
>V2 branch needs documentation. It may be the biggest blocker. If you could contribute to the website repo with install guide, that would be super helpful.
>
> Beyond that it needs testing and merge of changes from master.
>
> One big thing missing is the recent addition of EdDSA keys


I'll try to do what I can, I'm having trouble freeing up time as well 😄
