### ISSUE TITLE
Sparkle Launching GUI Installer

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#1185]
My app uses Sparkle, and I have distributed an app update recently.

The usual experience is when I click on "Install and Relaunch", the update gets installed and the updated app is relaunched.

However, I noticed in a machine where the user was taken through a guided installation using the macOS’s built-in GUI installer. why is that ?

Thanks,
Prashanth

**Comment by kornelski** [comment]
You can choose whether GUI is shown or not:

https://sparkle-project.org/documentation/package-updates/

**Comment by prasha6** [comment]
@kornelski 

Hi Kornel, I am pretty sure that we don't have a *.sparkle_interactive.pkg in the app archive. 

I want to understand the root cause for this issue. I am using Sparkle version 1.14.1 for my app.

Here is the situation:

We did some random upgrade testing within our team, and it turned out that one user in our team was taken through guided mac os wizard installer. All the other users were able to install the update and relaunch the application without any UI interruptions.  Now, I am anxious to know whether any of our actual customers would be facing a similar issue. 

I am trying to find out why is it that for this particular user, a guided installation is seen while for others, it is not.

**Comment by kornelski** [comment]
Older versions of Sparkle don't support hiding of the installer, so it's possible that some of your users that have old version of the app with old version of Sparkle will get the old behaviour.
