### ISSUE TITLE
Delta Updates with .pkg files

### ISSUE THREAD

**Issue by ghost** [sparkle-project/Sparkle#1187]
Hi,
I am trying to provide delta update functionality in one of my Mac Application. But, Every time I run the below command it removes the .pkg file of the old/previous application.

Command :- ./BinaryDelta create --verbose /Users/amit.palo/Desktop/iManage\ 10.1 /Users/amit.palo/Desktop/iManage\ 10.2 patch.delta

Also please find attached the screenshot of the terminal for the same.

Could you please suggest how to create a batch/delta update for .pkg file.

Thanks & Regards,
Amit Palo
<img width="843" alt="screen shot 2018-03-08 at 2 25 00 am" src="https://user-images.githubusercontent.com/36535557/37117894-7d3c9c8e-2278-11e8-98c2-4fc0924c3a5e.png">

**Comment by AmitPaloGlobant** [comment]
Hi Kornelski,

Thanks for the response. Is there any alternative solution to achieve this batch update functionality for pkg installer or maybe be you can provide any support for the same.

Regards,
Amit Palo

**Comment by kornelski** [comment]
No. There's no hope for pkg installers.

**Comment by kornelski** [comment]
DMG containing `.app` bundle are OK.

**Comment by jozsef-vesza** [comment]
Oh I see. I created a [follow-up](#1217 ) issue then.
