### ISSUE TITLE
Use HFS+ compression

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#1194]
There's `ditto --hfsCompression src dst` command that creates files with HFS compression, reducing amount of disk space taken by the files. The compression is entirely transparent.

It would be neat if we used it (or equivalent API) when updating apps to automatically save disk space taken by apps.

**Comment by gingerbeardman** [comment]
Just an aside, HFS+ compression has been supported since 2009 when it was introduced in Mac OS X 10.6 (Snow Leopard) and it continues to be fully supported today on High Sierra and APFS filesystem.

**Comment by kornelski** [comment]
This sheds a bit of light on the implementation of the compression:

https://opensource.apple.com/source/copyfile/copyfile-138/copyfile.c.auto.html

but it seems that there's no official API for this:

https://stackoverflow.com/q/49362070/27009

so actually calling `ditto` may be required.

**Comment by michelf** [comment]
Compression as a feature might be supported since 10.6, but it would seem compressed files are not all backward compatible in that way. Quoting the comments from the "copyfile.c" file linked above:

> Types 7->10 were added in 10.10, Types 11 & 12 were added in 10.11.

So if you are on 10.10 and try to read a file compressed by 10.11 you might be out of luck, or not, depending on which compression type was used. Probably better not to compress things if installing on a removable drive where the app might end up getting read by an older OS.

**Comment by gingerbeardman** [comment]
But types 3 & 4 have been around since Snow Leopard?

**Comment by michelf** [comment]
No idea, but 3 & 4 were probably there from the start. More importantly, how do you know which type `ditto` will use? The man page has this to say about the option:

      --hfsCompression
                   When copying files or extracting content from an archive, if the destination
                   is an HFS+ volume that supports compression, all the content will be com-
                   pressed if appropriate. This is only supported on Mac OS X 10.6 or later, and
                   is only intended to be used in installation and backup scenarios that involve
                   system files. Since files using HFS+ compression are not readable on versions
                   of Mac OS X earlier than 10.6, this flag should not be used when dealing with
                   non-system files or other user-generated content that will be used on a ver-
                   sion of Mac OS X earlier than 10.6.

I read this as a warning not to use the option for non-system files. It'd make sense they are always using the newest type available on the current OS.

**Comment by gingerbeardman** [comment]
Also, recently added types have been backported. 

Types 11 & 12 from 10.11 to 10.10.2 (early 2015)

Types 7 & 8 from 10.10 to 10.9.5 (late 2014)

Updated kexts are in the respective combo update.

**Comment by gingerbeardman** [comment]
> I read this as a warning not to use the option for non-system files

I've been using it for personal files since ~2010 mainly using Clusters but recently using a tool of my own. 

If an app has a minimum OS in its info.plist then sparkle could honour that, picking the respective type. 

Finally, copying and compressed file across volumes, zipping, extracting,  would all decompress the app. so a scenario where you end up with an app compressed with a new type on an old system would be quite difficult to achieve in normal use.

**Comment by kornelski** [comment]
@gingerbeardman You've mentioned your own tool for this. Is there an implementation we could use?

**Comment by gingerbeardman** [comment]
I either wrap `ditto` or [afsctool](https://github.com/RJVB/afsctool) depending

**Comment by zorgiepoo** [comment]
There's nothing Sparkle needs to do here for regular updates. Updates should be applied appropriately if developers opt into HFS+ compression and use an archive format that "preserves" those on a per file basis. It seems like bsdtar / libarchive does that these days so you can eg create a .tar.xz and I presume on decompression the filesystem compression kicks in.

We do lose this compression when applying delta updates however. I am thinking of recording if file compression is being used at creation time, and then on applying just use `ditto --hfsCompression` to copy/compress the entire output app. We could do this on a file-by-file basis but then we'd have to NSTask out on such a frequent basis.. Some [details here](https://stackoverflow.com/a/49368770/871119) about detecting the special extended attributes for this.

**Comment by zorgiepoo** [comment]
>  It seems like bsdtar / libarchive does that these days so you can eg create a .tar.xz and I presume on decompression the filesystem compression kicks in (note: there may be compatibility implications with older OS's I have not tested)

It's supported on 10.15+. On decompression, bsdtar will re-apply FS compression, but on older systems this additional metadata will just be ignored and FS compression won't be applied, so it is still compatible in that sense. Of course DMG goes even further back compatibility wise.

**Comment by zorgiepoo** [comment]
Do note ditto intelligently discards applying compression to files where there will be no or minimal gains (eg already compressed files, small files). Changes to delta format have now been integrated for this. Absent of some documentation in the future this is done.
