### ISSUE TITLE
Merge some missing pull-requests also to ui-separation-and-xpc branch

### ISSUE THREAD

**Issue by 1024jp** [sparkle-project/Sparkle#1195]
Although the latest pull-requests were merged to both main and ui-separation-and-xpc branchs, some pull-requests in the last year, such as #1141 and #1154, seem to be just forgotten and ignored.
Could you also merge them to ui-separation-and-xpc branch?

**Comment by kornelski** [comment]
We shouldn't need to re-merge every pull request individually. Merge of master into the branch should automatically include *everything* that was merged before.

If some changes are missing, that could have been due to a mistake in resolution of merge conflicts.

**Comment by 1024jp** [comment]
Ok, then that's no problem.
I just worried you'd forgotten.
Thank you for the reply.
