### ISSUE TITLE
Sparkle asking for password on every app update

### ISSUE THREAD

**Issue by prohtex** [sparkle-project/Sparkle#1196]
I recently set up a new iMac Pro with High Sierra 10.13.3. For some reason, all my apps that use Sparkle to update are now asking for authentication before updating, something that never happened before. Any ideas about why this is happening and what I can do to resolve? Entering valid user credentials works, but getting authenticated with every app update doesn't appear to be normal behavior.

![autoupdate](https://user-images.githubusercontent.com/12946938/37635540-5d630246-2bb9-11e8-8113-edf0443579b1.jpeg)

**Comment by kornelski** [comment]
Is it possible that apps in `/Applications` are read-only for you? See "Get Info" on a few apps in Finder.

Alternatively, if this dialog is a mistake, check out Console.app. Sparkle should print more information there explaining why it needs it.

**Comment by prohtex** [comment]
It seems you are correct. This is really weird. How did this happen?

`drwxr-xr-x    3 501    staff    96B Mar 19 20:54 Swinsian.app`

<img width="512" alt="screen shot 2018-03-20 at 5 39 58 pm" src="https://user-images.githubusercontent.com/12946938/37690044-d7eae04a-2c65-11e8-8fc4-8eda21316577.png">

This dialog seems to say "Fetching" in perpetuity.

**Comment by prohtex** [comment]
In my case, I created a user (501), installed some applications, then removed that user. The new user (504), had read only permissions on many of those apps, whereas the original user (501), had full permissions. It seemed like the right move to chown my app bundles to the new user, which is what I did. If the issue isn't resolved, I'll post again!
