### ISSUE TITLE
Lost previous Developer ID key. How to update with new one?

### ISSUE THREAD

**Issue by OleksandrRakovets** [sparkle-project/Sparkle#1197]
Hello!

I have switched from one Apple account to another and currently have only keys from the new one.

My live app is signed with previous key and currently fails to apply update signed with the new key.

Is there any workable solution to enable updates? I haven't used DSA previously. Attempts to apply it now don't help.

**Comment by kornelski** [comment]
If you didn't already have a valid DSA key in the old version of the application, then there's no way to change the Apple Code Signing identity. All your auto-updates will be rejected, and there's no way around it.

You need to instruct your users to download a new version of your app manually.

The best you can is to make appcast without `<enclosure>` and just shout in release notes that updates are broken.

**Comment by OleksandrRakovets** [comment]
Thanks Kornel!
