### ISSUE TITLE
Minor annoyance when updating Script debugger (which uses Sparkle)

### ISSUE THREAD

**Issue by jcbeatty** [sparkle-project/Sparkle#1200]
I went to upgrade Script Debugger on y March by launching v6 and selecting the Check for Updates menu item, and was rewarded with the error dialog shown in attached file 1 ("...can't be updated when it's running from a read-only volume...").

Script Debugger v6 is stashed in a folder at the top level on a non-boot partition of my iMac’s internal SSD whose root permissions are shown in attached file 2 (775). The folder's permissions are shown in attached file 3 (777).

So it’s not clear what the actual problem is. I’ve seen this error with perhaps half a dozen or so other apps, so it's probably a problem with Sparkle.

Incidentally, I do this (install non-apple apps in a non-boot-partition folder) because my standard procedure is to have more than one boot partition for reasons you can probably imagine, and this way I don’t have multiple copies of all apps on mounted disks & in backups.

I contacted the developer of Script Debugger, who said  he'd look into it, but also suggested I file a bug report with Sparkle. So...

Not a big deal, but a bit of a nuisance.

![pastedgraphic-1](https://user-images.githubusercontent.com/16481257/37878093-8cd4edc4-3018-11e8-9d93-86463c409d94.png)

![pastedgraphic-3](https://user-images.githubusercontent.com/16481257/37878096-92798780-3018-11e8-869d-2b2582289a4d.png)

![pastedgraphic-4](https://user-images.githubusercontent.com/16481257/37878097-980141d4-3018-11e8-8de3-4c9b0e5ff6ba.png)

**Comment by kornelski** [comment]
Most likely it's caused by macOS Quarantine. macOS will secretly run all downloaded apps from a hidden read-only volume, unless you copy them using Apple's original Finder (not PathFinder, not terminal, not anything else).

**Comment by kornelski** [comment]
#923 #1192
