### ISSUE TITLE
Download link for updating the plugin is not showing up

### ISSUE THREAD

**Issue by JakeKwon** [sparkle-project/Sparkle#1202]
My appcast file currently looks like this:
```
<item>
        <title>Version 0.0.3</title>
        <pubDate>Mon, 28 Jan 2013 14:30:00 +0500</pubDate>
        <sparkle:version>0.0.3</sparkle:version>
        <link>https://sparkle-project.org/documentation/publishing/#publishing-an-update</link>
    </item>
```

However, when I go to the plugin manager, only update button shows up (instead of the download site link) and clicking the button doesnt do anything... Is there anything I'm missing here??

**Comment by kornelski** [comment]
Which version of Sparkle is shipped with the version of the app that is being updated?
