### ISSUE TITLE
CheckForUpdatesInBackground doesn't work sometime and pops up the UI

### ISSUE THREAD

**Issue by gaocan1992** [sparkle-project/Sparkle#1203]
I use pkg installer to install the app and after installation it will use postinstall script and do open "$2"
in which $2 is the Target location to open my app. 
However it will pop up the UI which tells me there is a new version available. But if I open app directly from Applications, it won't show the UI and update silently.
This is very weird, anyone knows why?

And first I doubt that the command `open "$2"` is related to this issue.
But I have moved application bundle to Applications folder and run this `open "{my app location}"`
It open the app and update silently too.

Is that because of the pkg installer?

**Comment by gaocan1992** [comment]
After reading the source code I think it can only happen when updater calls "checkForUpdatesInBackground". 
"automaticallyDownloadsUpdates" is still false and it chooses **SUScheduledUpdateDriver** (which implements "**SUUIBasedUpdateDriver**") instead of **SUAutomaticUpdateDriver** which implements **SUBasedUpdateDriver**

I also found in [Customizing Sparkle](https://sparkle-project.org/documentation/customization/).

> "There is a risk of race conditions. If you want to make sure these settings are changed before the first automatic update check, you should do this in the NSApplication delegate method -applicationWillFinishLaunching:. For a non-app bundle you should then make the changes immediately after you first create the SUUpdater instance in your code."

And I set automaticallyDownloadsUpdates equal to true in applicationDidFinishLaunching which causes the race condition.
@kornelski Could you verify this, I try to make sure my Sparkle 100% UI less.

**Comment by kornelski** [comment]
If you're updating an app, the best way to set settings is in `Info.plist`.

If you want to rely on the delegate for the settings, try creating updater instance programmatically, not via xib.

**Comment by kornelski** [comment]
If `Info.plist` works for you, that's the best method.

You don't need a delegate if you only set same Sparkle settings for everyone. Delegates are only for complex/advanced cases where you have to change settings dynamically/per user. We copy Sparkle settings you set to app's `NSUserDefaults`. I'm not sure why, to be honest :)

**Comment by Sunil-P** [comment]
Hey, Im facing the same issue with my auto updater app.
I have already set those 3 keys as YES in the info.plist.
Also manually set SUUpdater setAutomaticallyDownloadsUpdates and SUUpdater setAutomaticallyChecksForUpdates to YES.
But immediately after setting the value if I query 

        NSLog(@"BOOL AUTOMATIC UPDATES INSTALL : %@", [updater automaticallyDownloadsUpdates] ? @"YES" : @"NO");

It returns NO. Any idea why this behavior is  happening. This does not occur if I launch the app from Xcode, only occurs when app is launched after build and install.

**Comment by gaocan1992** [comment]
@Sunil-P Have you checked App's NSUserDefaults.
What are the values inside?

**Comment by Sunil-P** [comment]
Yes, these settings are there in info.plist

<key>SUEnableAutomaticChecks</key>
	<true/>
	<key>SUAllowsAutomaticUpdates</key>
	<true/>
	<key>SUAutomaticallyUpdate</key>
<true/>
