### ISSUE TITLE
Doesn't update for any app versioned over 1.0

### ISSUE THREAD

**Issue by AlGoreRythms** [sparkle-project/Sparkle#1204]
I've created my appcast xml and zip (version 1.0 of my app) and thrown both onto my servers.

If I run a build of my app at version 0.9 and check for updates, sparkle correctly asks if I want to update to 1.0.

If I create an appcast xml and zip for a version 1.0.1, 1.1, or even 2, and run a build of my app at version 1.0 and check for updates, I get nothing. It says I'm up to date.

Any ideas?

**Comment by kornelski** [comment]
Do you update both version fields in your Info.plist? There's user-visible version `CFBundleShortVersionString` and build version `CFBundleVersion`.

Did you try using `generate_appcast` tool? It can help avoid mistakes in the appcast.

**Comment by AlGoreRythms** [comment]
Hey, thanks for your response!

Yeah, I threw a zipped version of my 1.0 app into a folder and used generate_appcast. Then I set my CFBundleVersion and CFBundleShortVersionString in my info.plist to 0.9 and built and ran my app. Update triggered great.

Then I set my CFBundleVersion and CFBundleShortVersionString to 1.0.1 (and later 1.1 and 2.0), built my app, replaced the zip, generated the appcast, uploaded to my server, and rebuilt my xcode project to 1.0 and ran. Tried to update and it said 1.0 is the latest version, over and over again.

Weird thing is, if I set my version to 0.9 again and try to update, it always works.

**Comment by AlGoreRythms** [comment]
Also of note, I did change the build slightly each time in order to change the app's checksum.

**Comment by kornelski** [comment]
If you have problem with Sparkle seeing an update over and over again, it's caused by the ZIP being out of sync with the appcast, and "new" downloaded app actually containing an old one.

**Comment by AlGoreRythms** [comment]
Oh, it's the opposite problem. It didn't see the update at all.

**Comment by kornelski** [comment]
There's nothing special in Sparkle around 0.9/1.0 versions. What you're describing seems most likely by uploading wrong file, or using URLs to files that you didn't upload. Check URLs in the appcast, as well as appcast URL in Info.plist, and NSUserDefaults if you ever reconfigured them dynamically.
