### ISSUE TITLE
generate_appcast should support localized Release Notes

### ISSUE THREAD

**Issue by UliZappe** [sparkle-project/Sparkle#1205]
For an app archive called **myApp.1.10.2.zip generate_appcast** will automatically add release notes if there is a file named **myApp.1.10.2.html**. This is great but doesn’t really help if you use localized release notes.

It would be great if **generate_appcast** would also add localized release notes (German in my example) sticking to the naming convention **myApp.1.10.2.de.html** (or maybe **myApp.1.10.2.html.de**?).

**Comment by kornelski** [comment]
Yes, `.$language-code.html`  is a great idea. 

Would you be able to make a pull request for it?

**Comment by UliZappe** [comment]
> Would you be able to make a pull request for it?

Unfortunately, currently not; sorry! Very little time and I’d rather not touch anything written in Swift … :innocent:
