### ISSUE TITLE
Incorrect binding in SUUpdateAlert.xib

### ISSUE THREAD

**Issue by UliZappe** [sparkle-project/Sparkle#1206]
In **SUUpdateAlert.xib**, the *Automatically download and …* check box is bound to the user defaults instead of the **automaticallyDownloadsUpdates** property of the shared **SUUpdater** instance.

As a result, if you implement a corresponding check box in the app preferences and bind it to the shared **SUUpdater** instance (as the documentation says you should, as opposed to the user defaults), this check box isn’t properly updated if the user changes this setting in the **SUUpdateAlert** panel.

So I think the check box in **SUUpdateAlert.xib** should be bound to **SUUpdater**, but I’m no sure if there are any undesired side effects (and the current binding was established on purpose).

**Comment by kornelski** [comment]
I think that's fine. The standard defaults can be observed for changes, but this property in SUUpdater is not KVO-compatible.

The property gives final, computed result, but the checkbox represents user preference (which could be overriden by other settings).

**Comment by UliZappe** [comment]
> The property gives final, computed result, but the checkbox represents user preference (which could be overriden by other settings).

But couldn’t this overwriting result in confusion?

I mean, the user selects automatic updates, but they still do not happen, without the user being aware of that?

Shouldn’t the property and the checkbox not always be identical? If file permissions do not allow automatic updates, the checkbox should be deselected and disabled, to make clear to the user that automatic updates do not work in her/his configuration.

**Comment by kornelski** [comment]
We hide the checkbox when automatic updates are disabled by the application.

**Comment by UliZappe** [comment]
Yes, I know. But if automatic updates are enabled by the application (i.e. the **Info.plist** value) and `SUSystemUpdateInfo +systemAllowsAutomaticUpdatesForHost:` returns `NO`, no automatic updates will take place, but the check box is still visible and can be selected by the user.

My point is that the user preference should *not* – as you wrote – be overwritten by other settings. Instead, it should not be possible for the user to select this option if it cannot be performed, anyway.

Consequently, the `automaticallyDownloadsUpdates` property of the shared **SUUpdater** instance would always be consistent with the User Defaults value.
