### ISSUE TITLE
Branch: "ui-separation-and-xpc" picks up releases it should not

### ISSUE THREAD

**Issue by core-code** [sparkle-project/Sparkle#1213]
1.) download latest sparkleCLI tool from latest "ui-separation-and-xpc" Branch
2.) download latest Toast16 from here http://softwareupdates.roxio.com/downloads/toast/16/patches/toast_16_4867.pkg
3.) run CLI tool on Toast: sparkle.app/Contents/MacOS/sparkle --verbose --probe /Applications/Toast\ Titanium.app 
=> Update available!

it picks up an update although the version is fully up-to-date, the bundleVersion is the same as in the appcast feed and the sparkle version built-into Toast16 does not pick up any update

this may or may not be connected to issue #1178

also, when trying to actually update using '--check-immediately' there is a weird failure, i'm going to file another bug report for it

**Comment by core-code** [comment]
this also happens with TeamViewer 13.1.4170:
```
sparkle.app/Contents/MacOS/sparkle --verbose --probe --feed-url "https://download.teamviewer.com/download/update/macupdates.xml?id=0&lang=en&version=13.1.4170&os=macos&osversion=10.13.4&type=1" /Applications/TeamViewer.app/
Update available!
```

**Comment by zorgiepoo** [comment]
Behaves expectably for TeamViewer I believe. CFBundleVersion of TeamViewer is 1, version (at this time of writing) of sparkle:version is 15.2.2756. TeamViewer could possibly have a custom version comparator. sparkle-cli is not perfect; apps can override things for custom behavior (eg feed url delegation, version comparator) that aren't extractable externally.

**Comment by zorgiepoo** [comment]
Toast's 19 (as of writing) does something similar. So behaves correctly.
