### ISSUE TITLE
Branch: "ui-separation-and-xpc" CLI tool fails to update some apps

### ISSUE THREAD

**Issue by core-code** [sparkle-project/Sparkle#1214]
1.) download latest sparkleCLI tool from latest "ui-separation-and-xpc" Branch
2.) download latest Toast16 from here http://softwareupdates.roxio.com/downloads/toast/16/patches/toast_16_4867.pkg
3.) run CLI tool on Toast: sparkle.app/Contents/MacOS/sparkle --verbose --check-immediately /Applications/Toast\ Titanium.app 

=> Error: Update has failed: An error occurred while running the updater. Please try again later.
 and in the Console:

default	13:31:18.404083 +0200	Autoupdate	Extracting using '/usr/bin/ditto' '-x' '-k' '-' < '/Users/ente/Library/Caches/com.roxio.Toast/org.sparkle-project.Sparkle/Installation/rpJpSRyLM/Toast_Titanium.zip' '/Users/ente/Library/Caches/com.roxio.Toast/org.sparkle-project.Sparkle/Installation/rpJpSRyLM'
default	13:31:19.865444 +0200	Autoupdate	UNIX error exception: 17
default	13:31:19.873495 +0200	Autoupdate	UNIX error exception: 17
default	13:31:19.880044 +0200	Autoupdate	CSSM Exception: -2147415792 CSSMERR_CSP_INVALID_KEY
default	13:31:19.883542 +0200	Autoupdate	UNIX error exception: 17
default	13:31:19.886891 +0200	Autoupdate	UNIX error exception: 17
default	13:31:20.817083 +0200	Autoupdate	UNIX error exception: 17
error	13:31:20.828341 +0200	Autoupdate	Error: Failed to create installer instance with error: Error Domain=SUSparkleErrorDomain Code=4005 "Found guided package installer but 'sparkle:installationType=package' was probably missing in the appcast item enclosure" UserInfo={NSLocalizedDescription=Found guided package installer but 'sparkle:installationType=package' was probably missing in the appcast item enclosure}

**Comment by zorgiepoo** [comment]
This decision was made consciously against compatibility of 1.x pkg updates with some sort of security concern back then.. It's in the readme of the 2.x branch:

> A sparkle:installationType="package" or sparkle:installationType="interactive-package" tag is also now required in the appcast enclosure item for package based installs.

**Comment by core-code** [comment]
thanks!
