### ISSUE TITLE
I am not enable to use silent mode update

### ISSUE THREAD

**Issue by zyves72** [sparkle-project/Sparkle#1215]
Hello.
I'm a beginner with sparkle. I've read the documentation and apply it to my projet and it seems to work.
Now ,I 'd like to use sparkle update in a silent mode.
I have modified my info.plist to add :

SUFeedURL : https://xxxxxxx/appcast.xml
SUEnableAutomaticChecks : YES
SUAutomaticallyUpdate : YES
SUScheduledCheckInterval : 3605
SUPublicDSAKeyFile : publicKey.pem

but it doesn't work : I still have the update popup. Can you help me please ?
What did i misunderstand ?

Thanks

**Comment by kornelski** [comment]
There is a popup once. User has to tick "Automatically download and install all updates in the background." checkbox.

**Comment by zyves72** [comment]
Is there possible to never show this popup and always check update in silent mode ?
Is there possible to check the checkbox by default ?

Thanks.

**Comment by kornelski** [comment]
Currently it's not possible. You would have to modify Sparkle source code and ship a custom version.

**Comment by zyves72** [comment]
Thanks for your answer.
