### ISSUE TITLE
Delta patch provided, app still downloads full update

### ISSUE THREAD

**Issue by jozsef-vesza** [sparkle-project/Sparkle#1217]
As a follow-up to this [comment](https://github.com/sparkle-project/Sparkle/issues/1187#issuecomment-383555532):

I'm trying to add delta update support to an app distributed as a DMG, but somehow the app always downloads the full update even if delta packages are available/accessible. Here's what I've done so far (according to [this guide](https://sparkle-project.org/documentation/delta-updates/)):

- Make a release build of the current version of the app
- Make a minor change, update version number of the app (`CFBundleVersion` and `CFBundleShortVersion` changes).
- Create a patch file with the BinaryDelta tool, then verify that it successfully applies
- Update the appcast file
- Upload the update, patch, and the appcast to our S3 bucket

When I launch the app, Sparkle notices that an update is available, but when I click Download, it always starts downloading the full package. I checked `~/Library/Logs/SparkleUpdateLog.log` for logs, and didn't find anything related, there's no sign of an error.

Even though everything is served over HTTPS, I experimented with signing the update/patch files as well (following [this guide](https://sparkle-project.org/documentation/#segue-for-security-concerns)) but it didn't help either.

Is there something obvious I'm missing? Can I debug this somehow? 

Thanks in advance!

**Comment by kornelski** [comment]
Try `generate_appcast` tool. It makes deltas, signs them and adds them to the appcast correctly.

**Comment by jozsef-vesza** [comment]
👍 okay, that seemed to help, thanks! One additional question: is there some requirement for the number of available updates? The script didn't generate a delta patch when only two DMGs were present in the same folder, but worked well, when I added a third one.

**Comment by kornelski** [comment]
It limits maximum. It shouldn't have a limit on the minimum. 

However, it skips deltas that are almost as large as the full app.
