### ISSUE TITLE
Documentation for security model?

### ISSUE THREAD

**Issue by riastradh-brave** [sparkle-project/Sparkle#1218]
The [Sparkle web page](https://sparkle-project.org/) (retrieved 2018-04-23) says that Sparkle

> Secure
> ---
>
> Supports traditional Sparkle DSA signatures as well as Apple Code Signing, for ultra-secure updates. Sparkle also supports authentication for installing in secure locations. Support for sandboxing is currently under development.

Is the security model for Sparkle documented anywhere?

There are hints about it, such as https://sparkle-project.org/documentation/#apple-code-signing (retrieved 2018-04-23):

> If you both code-sign your application and include a public DSA key for signing your update archive, Sparkle allows issuing a new update that changes either your code signing certificate or your DSA keys. Note however this is a last resort and should _only_ be done if you lose access to one of them.

But I don't see any document outlining the legitimate usage, the threat model, how Sparkle addresses the threat model, and the obligations of the developer to get any security from Sparkle.  In particular, I would be interested in seeing a document answering the following questions, to which I have added some sketches of candidate answers to start:

- Application: Who are the legitimate users, what resources do they have at their disposal, and what are they trying to accomplish?
  - Legitimate users: application developers, application users.
  - Resources: developers' machines, servers hosting app distributions, users' machines, the internet to connect them, &c.
  - Goal: run the most up-to-date version of the software from the developers on the users' machines.
- Threat model: What are the capabilities of adversaries -- which resources or parties _can_ they monitor or subvert, versus which ones are out of scope?
  - MITM on internet?
  - Compromised development machine?
  - Compromised server distributing updates?
- Security properties: What do we hope to make sure the adversary _cannot_ do in spite of those powers of subversion?
  - Users shouldn't run any applications the developers did not intend to publish.
  - If a user has witnessed a newer version of an application, the software should refuse to automatically run an older version.
  - Users should not get stuck with versions that cannot be updated.
- Implementation: How does Sparkle provide the advertised security properties to defend against the threat model posited above?  Ideally, this would be answered with specific code references, and strong review guidelines about any changes to the critical parts of the code.
  - Maybe Sparkle, or the operating system, verifies Apple code signatures before it will install or execute applications.  (What exactly do Apple code signatures cover?  How far into Sparkle's logic can forgeries pass before this verification?)
  - Maybe Sparkle verifies Sparkle-specific DSA signatures on binary delta updates.
    - (But DSA and SHA-1 are not confidence-inspiring!)
- Obligations for the security contract: What does an application developer have to do in order to get the advertised security properties?  What choices can an application developer make, and what impact do they have?
  - Obviously developer must keep private signing keys secret, but there's more:
  - If a developer uses Apple code signatures _and_ Sparkle DSA signatures, compromising _either one_ is enough to compromise both, so Sparkle provides the security of the _weaker of the two_ if application developers use both.  So rather than guard _at least_ one of the private keys, the developers must guard _both_ of them.
  - Developers must provide entropy for every DSA signature or risk leaking the private key.  For example, they must not make DSA signatures in a virtual machine whose state is ever rolled back (unless there's [RFC 6979](https://tools.ietf.org/html/rfc6979) mitigation).

These answers are not exhaustive, or necessarily even correct -- they are just the first things that come to mind when looking at Sparkle.  For reference, The Update Framework has a [brief page of security notes](https://theupdateframework.github.io/security.html) (retrieved 2018-04-23) and a detailed [specification](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md).  Does Sparkle have any corresponding design documentation?

**Comment by kornelski** [comment]
We protect against:

* Attacks from the network. MITM of the network between update server and the user cannot cause arbitrary code execution.
* Automated distribution of malware via hacked servers. Replacement of the archives on the server cannot cause arbitrary code execution. We have proven track record on this. When servers get hacked, attackers infect new downloads, but not Sparkle updates.

We don't protect against:

* Phishing from *hacked* servers. We depend on TLS to prevent phishing via feeds/release notes.
* Leak of DSA or Developer ID private keys. It's not game over — there's still TLS as an extra layer of security, but security is weakened if you leak your private keys.
* Malware already on victim's computer. 
* Potential vulnerabilities in Apple's crypto, including Apple Code Signing ([which uses SHA-1](https://developer.apple.com/library/content/technotes/tn2206/_index.html)).
* Evil developers. The app author can ship whatever code they want.

To uphold Sparkle's security:

* Don't embed attacker-supplied malware in your code. OR if you do embed the malware, add at least 10 random bytes to the first file in your archive.
* Don't have malware running on the system where you build and sign your app.
