### ISSUE TITLE
Sparkle force update in root mode not in user

### ISSUE THREAD

**Issue by zyves72** [sparkle-project/Sparkle#1220]
Hello,

I'm using sparkle in an .app. For installing this application in /Application i use a pkg because i need to install file in special folder too. In /Application my app belong to root:wheel.
With my user, when a new critical version is detected, a frame is showned to ask update with "not now" or "install".
When i launch my app in root mode (sudo), the frame ask me to "update and reload" or "update when quit".
Can you explain me why is not the same frame ?
Is it possible with my user to  have the frame with "update and reload" or "update when quit" in order to force update ?

**Comment by kornelski** [comment]
We download and prepare automatic updates when the current user has ability to update the app without needing to enter admin login in permission prompt. 

If the current user does not have write permission for the app, we don't download updates automatically and ask before downloading instead.

**Comment by zyves72** [comment]
event if i put 777 rights on each file/directory in the /Application/myApp folder, i don't have the same frame (root /user mode).
Is there a control on the owner of the directory ?
What do i misunderstand  ?

**Comment by kornelski** [comment]
Another possibility is NSUserDefaults is different per user. Perhaps one account has configured automatic updates and the other hasn't?

Please use Console.app to see what Sparkle is doing

**Comment by zyves72** [comment]
I have only one user on my Mac. In this case does i have 1 NSUserDefaults pour my user and 1 another in sudo mode ? I have only 1 file  /User/xxxx/Library/Preferesces/app.plist.  
I don't have anything in my ~/Library/Logs/SparkeUpdateLog.log
I don't see something strange in Console.app. What can i search in console.app to have more information ?

**Comment by kornelski** [comment]
`root` is another user.

**Comment by zyves72** [comment]
How can i see the root NSUserDefaults ?

In my configuration, i can see the checkbox to automatic update only when i launch my app in sudo mode.  So you should have right about the 2 differents NSUserDefaults.
I only have the checkbox to auto uptade with my user only when i copy app manually in /Application.

**Comment by kornelski** [comment]
I don't know. Generally, you shouldn't be running GUI applications as root at all. The apps should use regular user's account and elevate privileges when needed.

**Comment by zyves72** [comment]
By changing directory's owner to my user, i've got the frame i'm looking for.

I have another question : during my tests i put language into french and i noticed that some text are not translate and that a button in a frame is too short to show the all label .
I add the missed translations, make the button larger in the frame and rebuild it. It works as I want in my project. Can you tell me how to give you these changes, in order to integrate them into sparkle project ( i haven't use github before) ?

**Comment by zyves72** [comment]
OK. I made it.
Hope i 've done it correctly.

**Comment by kornelski** [comment]
Thanks.

Sparkle now prints to Console.app why it needs authorization, so maybe that will help.
