### ISSUE TITLE
After updating a Sketch Plugin through Sparkle, executables files inside assets/ lose executable rights 

### ISSUE THREAD

**Issue by JakeKwon** [sparkle-project/Sparkle#1221]
Hi,

Im doing Sketch Plugin Development with Spark, and found this weird behavior. 

Executable files within assets/ folder somehow lose executable rights and become read-only file. 

This doesnt happen when the plugin is updated directly through installing zipfile, but does happen when the update is done through Sparkle. 

It's a pretty minor issue, but do you have any idea why this might happen? Thanks!

**Comment by kornelski** [comment]
Are you distributing the update using zip, too? Are you using delta updates?

**Comment by JakeKwon** [comment]
Yes, I am distributing the update thruogh zip like:
<enclosure sparkle:version="<version_number_here>" url="<zip_link_here>"/>

And, I am not really sure of what delta updates are, so I guess i am not using them..

**Comment by funfungo** [comment]
same problem

**Comment by kornelski** [comment]
To unzip, we use:

```sh
/usr/bin/ditto -x -k archive.zip
```

Does this create app bundle with correct permissions?

**Comment by funfungo** [comment]
I just tried ditto to unzip file, it works well.

**Comment by kornelski** [comment]
Hm, in that case it may be the code that copies/moves the app out of temp, or corrects the permissions.

**Comment by funfungo** [comment]
so how can this problem be fixed, I am really confused

**Comment by funfungo** [comment]
> Hm, in that case it may be the code that copies/moves the app out of temp, or corrects the permissions.

so how can this problem be fixed, I am really confused

**Comment by kornelski** [comment]
I hoped it'd be something simple with the zip file, but if unzipping works correctly, then the problem may be more complex, and I don't know how to fix it.

If you're comfortable with debuggers, maybe step through Sparkle during installation and check where it goes wrong?

**Comment by zorgiepoo** [comment]
Perhaps worth assessing on recent OS versions and recent Sparkle version. Depending how the zip was created may contribute to this too.
