### ISSUE TITLE
Allowing downloaded installer package to manage the existing app?

### ISSUE THREAD

**Issue by gutley** [sparkle-project/Sparkle#1223]
We have an installer pkg for our product that installs multiple items in various locations (e.g /Applications, kernel extensions, launchctl plists etc etc) and it already has pre and post-install scripts to handle tearing down the existing suite of apps, and restarting them all as needed. As such, Sparkle's own moving/quitting/relaunch abilities are unwanted.

I have not found any configuration options or delegate methods that allow the installer package to be 'plain' launched by AutoUpdate without it attempting to do its own relaunching etc 

Before I dive too deeply into the code, have I missed something?

I tried implementing pathToRelaunchForUpdater: and just getting it to return nil, but in that case it gets ignored. 

Ideally either a delegate or plist key along the lines of "SUInstallerPackageManagesLifecycle" that could be set to prevent AutoUpdate doing anything other than ask for admin rights and then run installer would be ideal.

On a side note, to fit in better with our existing tools for preparing the appcast I have modified Sparkle's source to allow a pkg file to be used directly as the downloaded binary without needing to embed it in a zip file. Happy to create a Pull request for that change if you think its useful in the general case.

**Comment by kornelski** [comment]
No, we don't have ability not to restart the app. Our logic is hardcoded to quit first then start install.
