### ISSUE TITLE
.pkg file updates clears all data from Userdefaults in MacOS App

### ISSUE THREAD

**Issue by ghost** [sparkle-project/Sparkle#1226]
I am using the .pkg file for distributing my app. But, updating the .pkg file removes all the User settings from UserDefaults.

Please suggest how to retain UserDefault Information on updating the app.

**Comment by kornelski** [comment]
Please verify that bundle identifier of your app doesn't change.

**Comment by AmitPaloGlobant** [comment]
We are following the below directory structure:- 

iManage Folder -> iManage Apps/Binaries

Please find attached the screenshot for the same.

<img width="882" alt="screen shot 2018-05-04 at 7 01 13 pm" src="https://user-images.githubusercontent.com/36535557/39630704-c130b178-4fcd-11e8-811e-a485c8deb3a6.png">

Do you think this might be an issue???

**Comment by AmitPaloGlobant** [comment]
No, We don't have "LSFileQuarantineEnabled" key in our Info.plist file. Is this the one you are talking bout???

**Comment by kornelski** [comment]
No, quarantine is `com.apple.quarantine` `xattr`

**Comment by AmitPaloGlobant** [comment]
Ok. I have verified through terminal command
:- "xattr /Applications/iManage/iManage\ Agent.app"
But it didn't display anything.

Screenshot:- 
<img width="682" alt="screen shot 2018-05-04 at 7 29 48 pm" src="https://user-images.githubusercontent.com/36535557/39632093-ba604c60-4fd1-11e8-93c3-fe1fed97181d.png">

It should have displayed "com.apple.quarantine". Is it so?

**Comment by kornelski** [comment]
Yes, indeed. In that case I don't know why macOS doesn't choose to give you the old defaults :(
