### ISSUE TITLE
Unable to generate appcast.xml file using "./bin/generate_appcast" for .pkg files

### ISSUE THREAD

**Issue by ghost** [sparkle-project/Sparkle#1227]
I am running the below command in the terminal but I am unable to generate appcast.xml file for .pkg files

I have even tried by creating .zip file of .pkg file but still no luck.

It gives me the below error message:- 

Error generating appcast from directory /Users/amit.palo/Desktop/iManage Build 
 Error Domain=SUSparkleErrorDomain Code=1001 "No usable archives found in /Users/amit.palo/Desktop/iManage Build" UserInfo={NSLocalizedDescription=No usable archives found in /Users/amit.palo/Desktop/iManage Build}

Command :- "./bin/generate_appcast /path/to/your/dsa_priv.pem /path/to/your/updates_folder/"

**Comment by kornelski** [comment]
Sorry, `generate_appcast` does not support pkg at all. It works only with .app in an archive like zip, tarball, dmg. 

If you use pkg you have to write appcasts yourself.
