### ISSUE TITLE
Downgrading using older version

### ISSUE THREAD

**Issue by drobati** [sparkle-project/Sparkle#1228]
I wanted to know if Sparkle supports downgrading.

Does the default comparator check if the appcast version does not equal the app version, or does it check to see the appcast version is greater than the app version?

**Comment by kornelski** [comment]
It intentionally doesn't allow downgrading.

**Comment by wo52616111** [comment]
Could you please explain the reason in more detail?

I found the following related content, and want to know:

Can I use the downgrade function without worry by turning `SPARKLE_AUTOMATED_DOWNGRADES` on? What risks will I face if I really need downgrading?

https://github.com/sparkle-project/Sparkle/blob/9ae7224a4732963b65d4d1f913b0b8310f38acf7/Configurations/ConfigCommon.xcconfig#L9-L11

https://github.com/sparkle-project/Sparkle/blob/b42642690535a43f459511e175716d5ad17fc5b8/Sparkle/SUPlainInstaller.m#L225-L248

https://github.com/sparkle-project/Sparkle/blob/9ae7224a4732963b65d4d1f913b0b8310f38acf7/CHANGELOG#L374-L379

**Comment by kornelski** [comment]
The key part is security. If you ever have a security issue with your application, and release a patch for it, you don't want attackers to be able to downgrade your users back to an old insecure version. Sparkle has signing of packages, but not signing of the feeds, so it needs to protect itself from a potentially-malicious feed.

The other thing is preventing errors. If you accidentally publish an old feed, break latest version's item in the feed, leaving only old ones working, etc. then nothing bad will happen. If Sparkle downgraded, then a mistake in the feed could downgrade your users by accident. And if an old version of your app wasn't compatible with the latest macOS, that could even "brick" it for your users!

**Comment by bfxzyn** [comment]
Could you please help me to answer this question?
Assume I only have Apple code signing but not using EdDSA signature with DMG distribution. If I have the newer version number in the Appcast file but attacker swap the expected newer version binary file with the old version binary file. Does Sparkle still able to update? In another word, does Sparkle use the version number in Appcast or it checks the downloaded binary file version? Thank you.

**Comment by kornelski** [comment]
It checks both.

When you swap binary you also must update signature in the appcast.

**Comment by bfxzyn** [comment]
Wow, thanks for quick response. I'm not using DSA or EdDSA signature but only Apple code signing which means no signature in the Appcast file. 
If I understand correctly, as long as it checks both, attacker is not able to swap the newer binary file with the old one.

**Comment by wo52616111** [comment]
Thank you for your long answer. @kornelski 

How can an attacker downgrade my app if I didn't use silent downgrade but downgrade after user confirmation?

If I set `SPARKLE_AUTOMATED_DOWNGRADES  = true`, can I use the downgrade function?
Or this function is no longer available at all.

If I have a way to tell if a version is secure (currently known), for example, get it via an HTTP request, can I safely let users downgrade to the allowed version?

**Comment by kornelski** [comment]
You can enable downgrades if you want. You will have to compile Sparkle yourself.

Signatures in Sparkle add an extra layer of protection on top of what HTTPS provides. If your server gets hacked, or DNS gets hijacked, then HTTPS won't be able to stop unauthorized updates, but the extra signature will. This is not a theoretical problem, such hacks have happened.

**Comment by wo52616111** [comment]
Hmm, thanks. It may be a better idea to provide users with a download link that specifies an older version?

**Comment by kornelski** [comment]
Yup, that sounds like a good option

**Comment by wo52616111** [comment]
Thank you for all your replies, and the hard work for this project : )
