### ISSUE TITLE
Modifying strings in source code has no effect

### ISSUE THREAD

**Issue by Touchcore** [sparkle-project/Sparkle#1231]
I am trying to change the text for certain alert messages. When I edit the strings in code and build the framework, I still see the default text in the alert messages. 
For example: I changed the "Update Error!" string to say "Missing Update Url!". When I compile the sparkle framework and add it to my app, it still shows "Update Error!"

What do I have to do to make my changes effective when I compile?

**Comment by kornelski** [comment]
If you're modifying messages that have a translation, make sure to modify the .strings' file translated side, not the source code.

Also double-check that you're actually embedding your modified framework. For example, are you building debug version, but copying from release products folder?

**Comment by Touchcore** [comment]
<img width="250" alt="screen shot 2018-05-16 at 9 31 38 am" src="https://user-images.githubusercontent.com/11425045/40119987-141d7714-58ec-11e8-8d83-2c6d82f5526d.png">

I am building and then copying the framework file from the product folder into my project

**Comment by kornelski** [comment]
Try deleting your project's build products dir. Maybe Xcode doesn't update the app bundle if it has the framework already. Or as I mentioned previously, make Xcode copy it itself.

**Comment by Touchcore** [comment]
Got it figured out. Thanks a lot!
