### ISSUE TITLE
App running as root restarts as non-root user

### ISSUE THREAD

**Issue by ech0matrix** [sparkle-project/Sparkle#1232]
I have a launch daemon running as root. However, I noticed that when it updates and restarts, it is running as my logged-in (non-root) user. How can I get it to restart as root (the user it was previously running as)?

I'm currently causing the restart using the delegate "updater:willInstallUpdateOnQuit:immediateInstallationInvocation:".

**Comment by kornelski** [comment]
I'm afraid running as root is untested in Sparkle, and it's not explicitly supported.

Can your daemon fix it by itself? e.g. use a helper with setuid bit, or restart itself if it's not run as the right user?

**Comment by ech0matrix** [comment]
Maybe, though right now I can't figure out how to get my app to shut itself down but still apply the update. `NSApplication.SharedApplication.Terminate(NSApplication.SharedApplication);` doesn't seem to be stopping it, and invoking "launchctl unload" on my daemon doesn't appear to apply the update.

**Comment by kornelski** [comment]
Does the daemon have to handle updates for itself?

If you have a main non-daemon app, then the solution is to:

0. bundle daemon in the `Resources` of the regular app
1. when the regular app gets an update (delegate callback), it stops the daemon 
2. the app with its resources is updated, so daemon too
3. when the regular app is restarted, it restarts the daemon

**Comment by ech0matrix** [comment]
The problem is that the Sparkle relaunch tool doesn't restart the app with the same permissions that it previously was.

I got my app to gracefully terminate and install the update (I had to call Terminate from the main thread). Now I suppose I just need to write a new helper app to start my app back up.

**Comment by ech0matrix** [comment]
I was able to use launchd to monitor and restart my app.
