### ISSUE TITLE
generate_appcast fails on Mac OS 10.13

### ISSUE THREAD

**Issue by Dave-K9** [sparkle-project/Sparkle#1240]
I have a successfully signed app that passes all Apple tests (codesign -v, and spctl -a).  Even the dmg distribution file signs fine.

There seems to be a problem with the bin/generate_appcast code.  I have no problem generating the dsa public and private keys (pem files).  I follow the online documentation exactly.  But, I get the following error when trying to generate an appcast xml file:

Error Domain=Internal CSSM error Code=-2147416063 "Internal error #80010801 at SignTransform_block_invoke /BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-58286.51.6/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:276" UserInfo={NSDescription=Internal error #80010801 at SignTransform_block_invoke /BuildRoot/Library/Caches/com.apple.xbs/Sources/Security/Security-58286.51.6/OSX/libsecurity_transform/lib/SecSignVerifyTransform.c:276, Originating Transform=CoreFoundationObject}

It then dumps a minimal xml file, but without any DSA key.  I was able to get a working appcast xml file by following the instructions for manually creating one.  I just thought someone should know that the generate_appcast routine is broken, at least on Mac OS.

**Comment by daizhirui** [comment]
You can build these tools on 10.11 and copy them to 10.13. Apple replaces OpenSSH tools on 10.13. So this is the only method you can do.

**Comment by hplusb** [comment]
I had the same problem described here with same error code while following the normal instructions on first documentations page, and went for manually creating one by using sign_update and it worked. Just letting know
MacOS: 10.13.6
