### ISSUE TITLE
Shell Script Invocation Error 

### ISSUE THREAD

**Issue by ZEUSOFCS** [sparkle-project/Sparkle#1242]
I've integrated Sparkle to my Xcode Project but when I try to archive the application I receive this error.

What did I do wrong?

<img width="1118" alt="screen shot 2018-06-01 at 9 30 25 pm-annotated" src="https://user-images.githubusercontent.com/19171147/40869111-45ed5e0e-65e3-11e8-820d-6a1cbaed2758.png">

**Comment by kornelski** [comment]
Do you have build phase that copies the framework to the app bundle? 
Is it a broken symlink?

**Comment by ZEUSOFCS** [comment]
Yes, issue resolved thanks! 

Issue:
I had Sparkle Cocoapods installed and Sparkle installed manually at the same time which were duplicates of the framework.

Solution:
Removed one of the frameworks.
