### ISSUE TITLE
Abort Application Update Manually

### ISSUE THREAD

**Issue by ghost** [sparkle-project/Sparkle#1243]
Is there any way to abort the application update process if any specific condition is not satisfied through code.

**Comment by kornelski** [comment]
Maybe some of the delegate methods will suffice:

https://sparkle-project.org/documentation/customization/

```
- (BOOL)updater:(SUUpdater *)updater
        shouldPostponeRelaunchForUpdate:(SUAppcastItem *)update
        untilInvoking:(NSInvocation *)invocation;
```

or `updaterShouldRelaunchApplication` delegate callbaxk
