### ISSUE TITLE
.pkg file with "Require some application to be closed before installation" not working when trying to update with sparkle framework.

### ISSUE THREAD

**Issue by AmitPaloGlobant** [sparkle-project/Sparkle#1246]
I have a scenario where I need to close some applications before the update of my application is being done. While creating .pkg file with the help of "Packages.app" there an option to specify the bundle identifier of those apps that needs to be closed before the update. But, it does not work with sparkle framework.
<img width="1312" alt="screen shot 2018-06-04 at 7 19 54 pm" src="https://user-images.githubusercontent.com/36535557/40921332-cad7f296-682c-11e8-9ab7-3beb3f9e15bf.png">

**Comment by kornelski** [comment]
Try version that shows the full UI (see sparkle_guided in docs)

Maybe the installer wants user to agree to this.

**Comment by AmitPaloGlobant** [comment]
I have renamed my .pkg file name to "iManage_Work_for_Mac.sparkle_interactive.pkg.zip" and have also added "sparkle:install="interactive"" in the appcast.xml file. But still it's not working.
<img width="1279" alt="screen shot 2018-06-04 at 8 06 06 pm" src="https://user-images.githubusercontent.com/36535557/40923571-c02f15b2-6832-11e8-997e-3606fc6549ac.png">

**Comment by kornelski** [comment]
Sparkle doesn't look at the URL. It looks at name *inside* the ZIP file.

**Comment by AmitPaloGlobant** [comment]
I got It. Thanks a lot for your help.
