### ISSUE TITLE
Always up-to-date

### ISSUE THREAD

**Issue by janssoner** [sparkle-project/Sparkle#1248]
My project always shows 'up-to-date'. The console shows:
   launchservicesd  CHECKIN:0x0-0xc50c5 8563 TestCompany.TestApp
   TestApp  Faulting in NSHTTPCookieStorage singleton
   TestApp  Faulting in CFHTTPCookieStorage singleton
   TestApp  Creating default cookie storage with process/bundle identifier
   TestApp  TIC TCP Conn Start [1:0x604000164080]
   TestApp  Task <B6A9CFCB-9935-465F-BBCB-705950A61EA6>.<1> setting up Connection 1
   TestApp  [1 <private> <private>] start
   TestApp  TIC TCP Conn Connected [1:0x604000164080]: Err(16)
   TestApp  TIC TCP Conn Event [1:0x604000164080]: 1
   TestApp  Task <B6A9CFCB-9935-465F-BBCB-705950A61EA6>.<1> now using Connection 1
   TestApp  Task <B6A9CFCB-9935-465F-BBCB-705950A61EA6>.<1> sent request, body N
   TestApp  Task <B6A9CFCB-9935-465F-BBCB-705950A61EA6>.<1> received response, status 301 content C
   TestApp  Task <B6A9CFCB-9935-465F-BBCB-705950A61EA6>.<1> response ended
   TestApp  Task <B6A9CFCB-9935-465F-BBCB-705950A61EA6>.<1> now using Connection 1
   TestApp  Task <B6A9CFCB-9935-465F-BBCB-705950A61EA6>.<1> sent request, body N
   TestApp  Task <B6A9CFCB-9935-465F-BBCB-705950A61EA6>.<1> received response, status 403 content C
   TestApp  Task <B6A9CFCB-9935-465F-BBCB-705950A61EA6>.<1> response ended

appcast.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
  <channel>
    <title>Test Application</title>
    <link>https://www.mycompany.com/osxupdate/appcast.xml</link>
    <description>Most recent changes with links to updates.</description>
    <language>en</language>
    <item>
      <title>Version 1.0.3 Test (2 bugs fixed; 3 new features)</title>
      <pubDate>Tue, 12 Jun 2018 14:47:27 -0400</pubDate>
      <enclosure
        url="https://www.mycompany.com/osxupdate/TestApp.20180612144727.dmg"
        sparkle:version="7"
        sparkle:shortVersionString="1.0.7 Test"
        length="2529240"
        type="application/octet-stream"
        sparkle:dsaSignature="MEQCIEkMfe9rygddCNUtTqr5vhxR/6mdclEN3Lsa7jA1dBaLAiBibgesyQCpreaG7foXKpEIy6ZdYPt2EdDrgotuPiK/uQ=="
      />
    </item>
  </channel>
</rss>

Info.plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIconFile</key>
	<string>PCMaticMac.icns</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0.3 Test</string>
	<key>CFBundleVersion</key>
	<string>3</string>
	<key>LSMinimumSystemVersion</key>
	<string>$(MACOSX_DEPLOYMENT_TARGET)</string>
	<key>LSUIElement</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
		</dict>
	</dict>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © . All rights reserved.</string>
	<key>NSMainStoryboardFile</key>
	<string>Main</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>SUEnableAutomaticChecks</key>
	<true/>
	<key>SUFeedURL</key>
	<string>https://www.mycompany.com//osxupdate/appcast.xml</string>
	<key>SUPublicDSAKeyFile</key>
	<string>dsa_pub.pem</string>
</dict>
</plist>
```

Created a smaller app, all it does is check for updates and that works using the same https address.

**Comment by janssoner** [comment]
More readable Info.plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIconFile</key>
	<string>PCMaticMac.icns</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0.3 Test</string>
	<key>CFBundleVersion</key>
	<string>3</string>
	<key>LSMinimumSystemVersion</key>
	<string>$(MACOSX_DEPLOYMENT_TARGET)</string>
	<key>LSUIElement</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSIncludesSubdomains</key>
				<true/>
				<key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
				<false/>
			</dict>
		</dict>
	</dict>
	<key>NSHumanReadableCopyright</key>
	<string>Copyright © 2018  All rights reserved.</string>
	<key>NSMainStoryboardFile</key>
	<string>Main</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
	<key>SUEnableAutomaticChecks</key>
	<true/>
	<key>SUFeedURL</key>
	<string>https:/www.MyCompany.com/osxupdate/appcast.xml</string>
	<key>SUPublicDSAKeyFile</key>
	<string>dsa_pub.pem</string>
</dict>
</plist>

**Comment by janssoner** [comment]
More readable appcast.xml
![image](https://user-images.githubusercontent.com/35817646/41314598-3fff8a96-6e5b-11e8-872b-e598d6a85f51.png)

**Comment by kornelski** [comment]
On github please format code:

`````
```
like this
```
`````

instead of pasting screenshots.

**Comment by kornelski** [comment]
The "more readable appcast" shows version 3, same as the app bundle, so it works as it should.

Consider using `generate_appcast` tool instead of manually editing XML.

**Comment by kornelski** [comment]
This happens frequently, and the usual causes are of "forgot to update a field", "forgot to upload new version"

Please double check the fields and that files that you look at are the exact same files that Sparkle is told to download.

**Comment by janssoner** [comment]
Believe me, I have checked.  Like I said I used the exact same script & procedure to build the simple version of the program and that works.  Is it possible for a dmg to be too big?  Does the console errors mean anything?  Been working on this over a week.

**Comment by kornelski** [comment]
The console fragment doesn't look like any message from Sparke, so I don't think it's relevant. If Sparkle got 403 response, it'd complain about it and show "can't update" kind of error instead of up-to-date.

**Comment by kornelski** [comment]
The dmg is not used to decide if the app is up to date. It's not even downloaded before deciding which version to download.

**Comment by janssoner** [comment]
Finally fixed this my just changing CFBundleIdentifier (PRODCUT_BUNDLE_IDENTIFIER).  After a lot of debugging and searching found that there is another mini plist file $(CFBundleIdentifier).plist in /Library/Preferences.  This one had a different SUFeedURL.  Our Info.plist had "https://www.mycompany.com//osxupdate/appcast.xml", this one had "http://www.mycompany.com//osxupdate" (notice "https" changed to "http" and stripped "appcast.xml").
I tried editing this file, even deleted it and it always comes back wrong.  But changing CFBundleIdentifier fixed this, NewCFBundleIdentifier.plist did not have any SUFeedURL.
Any idea why?

**Comment by kornelski** [comment]
It looks like you've set a different feed url using programmatic API, and when you do that, we save the feed URL in NSUserDefaults.

Change of bundle identifier "fixed" this, because there are separate NSUserDefaults for every bundle identifier.

**Comment by janssoner** [comment]
Don't really understand.  This was our first attempt at Sparkle, so we do not have another app changing SUFeedURL.  Did not even know you could programmatically change it.  What is the function to change it and I will look for it.

**Comment by kornelski** [comment]
Oh, that's interesting. The method is `[updater feedURL:]`, but it's only for advanced usage, since it requires fully manual control of the updater. Otherwise, when combined with the recommended method of using Sparkle from xib, it could cause race conditions.
