### ISSUE TITLE
Is there an option to require a restart if an update is needed?

### ISSUE THREAD

**Issue by janssoner** [sparkle-project/Sparkle#1254]

**Comment by kornelski** [comment]
All updates require a restart. If silent automatic updates are disabled, then user will be prompted.

There's no option to force a restart, we never do that.

**Comment by kornelski** [comment]
I see. In that case there's no support for that. Sparkle is geared towards regular apps. The closest what you can do is to ship update as a pkg installer and use `sparkle_interactive` naming convention to force the installer UI, and then make the installer package require a reboot:

https://sparkle-project.org/documentation/package-updates/
