### ISSUE TITLE
Issues with Spanish localisation

### ISSUE THREAD

**Issue by kenohori** [sparkle-project/Sparkle#1259]
Hi,

There are a few issues with the Spanish localisation:
- Uses formal version of "you" (usted) and its related verb conjugations, contrary to the informal tú that is used throughout macOS.
- Weird abbreviations for B, KB, MB and GB. Not strictly incorrect, but not really the preferred form since the 90s.
- Sometimes doesn't say the same as the English counterpart. Extra text in some places, missing text in others.
- Key words that would make things clearer are missing here and there (e.g. currently).
- Inconsistent words for the same text in different strings.
- The App name is always referred to using the masculine form. It would be better to use always feminine since application (aplicación) is feminine.

Mind if I rewrite the Spanish localisation strings and submit a pull request?

**Comment by kornelski** [comment]
Yes, please!

Our goals for localization are:

 - use the same terminology and phrases as Apple in macOS, where possible.
 - use gender-neutral forms when referring to the application user.

**Comment by kornelski** [comment]
This has been released
