### ISSUE TITLE
How to programmatically determine if a new version is available?

### ISSUE THREAD

**Issue by patrickkidd** [sparkle-project/Sparkle#1260]
Hello!

For my beta test phase I want to programmatically disable my app if a new version is available, forcing an update. What is the correct synchronous API call to determine if a new version is available?

It appears as though SUUpdater.h is the only api documentation that exists?

Thanks!

**Comment by kornelski** [comment]
For applications that strongly insist on being always-up-to-date we have this:

https://github.com/sparkle-project/Sparkle/blob/639b6df47b9e9bf567a74fafaa3b4acfa2ea3d77/Sparkle/SUUpdater.h#L177-L205
