### ISSUE TITLE
Embedded Command Line Tool - does not update app

### ISSUE THREAD

**Issue by janssoner** [sparkle-project/Sparkle#1262]
We have an app that also has an Xcode Command Line Tool (C++) embedded.  This "service" will start at boot time and needs to be constantly running.  I put Sparkle code into an objective-c++ (.mm) file to initialize/check for Sparkle update.  While the main app does find and will load an update when I check for update, the "service" does not complain but does not download anything.  I put the Sparkle initialization as the first thing in the "service".  I put some displays to see what is happening and it all looks good, just does nothing.

Here is the code from the .mm file:
  suupdater = [[SUUpdater sharedUpdater] init];
  [suupdater resetUpdateCycle];
  [suupdater setAutomaticallyChecksForUpdates:YES];   // SUEnableAutomaticChecks
  [suupdater setAutomaticallyDownloadsUpdates:YES];   // SUAutomaticallyUpdate (silent)
  
  // check Sparkle
  std::cout << "AutomaticallyCheck :" <<
    ([suupdater automaticallyChecksForUpdates] ? "YES" : "NO") << std::endl;
  std::cout << "AutomaticallyDownload :" <<
    ([suupdater automaticallyDownloadsUpdates] ? "YES" : "NO") << std::endl;
  std::cout << "Update in Progress :" <<
    ([suupdater updateInProgress] ? "YES" : "NO") << std::endl;
  
  [suupdater checkForUpdatesInBackground];
  std::cout << "Update in Progress :" <<
    ([suupdater updateInProgress] ? "YES" : "NO") << std::endl;
  [suupdater installUpdatesIfAvailable];

Here is output when I start service:
 MacBook-Pro:tmp me$ sudo ./MyCompanyApp.dst/Applications/MyCompanyApp.app/Contents/MacOS/service
 Password:
 AutomaticallyCheck :YES
 AutomaticallyDownload :YES
 Update in Progress :YES
 Update in Progress :YES

**Comment by kornelski** [comment]
Do you have Cocoa's main runloop running in the service?

Generally Sparkle doesn't support running inside CLI commands. If you have a main .app, then put the CLI inside the .app bundle. This way update of the main app bundle will also update your CLI/daemon executable. You can use delegate hooks to stop the daemon before the update.

**Comment by janssoner** [comment]
Cocoa is not running in service, that is why I wanted silent. The service is part of the main .app.  I thought I've seen other people who put Sparkle into non-Cocoa apps.  
What is it doing, it links and runs ok and it returns updateInProgress?

**Comment by kornelski** [comment]
We depend on Cocoa. It doesn't matter if it's silent or not — without main runloop we can't do any timers, background tasks or networking.
