### ISSUE TITLE
Failed granting authorization rights with status code

### ISSUE THREAD

**Issue by sateeshkumardamera** [sparkle-project/Sparkle#1263]
Hi.. I am just trying to use this library and not having much knowledge on it.

I am trying execute a package file inside my bundle by calling 
[fileManager executePackageAtURL:pkgPath progressBlock:nil error:&error];

But it is failing with Failed granting authorization rights with status code -60005 i.e., errAuthorizationDenied. 

What could be the problem  here ?

**Comment by kornelski** [comment]
Can you provide more context? 

How does your appcast look like? Does that fail during a normal update process, or are you trying to use `fileManager` yourself in your code? Do you get auth prompt?

**Comment by sateeshkumardamera** [comment]
I am trying to use fileManager directly in my code to see how it works. I am not getting auth prompt.

**Comment by sateeshkumardamera** [comment]
This is what I am doing right now.

 NSURL *pkgPath = [NSURL URLWithString:[[NSBundle mainBundle] pathForResource:@"Installer_1.1.1B26R" ofType:@"pkg"]];
    NSString *fileOperationToolPath = [[[[NSBundle mainBundle] executablePath] stringByDeletingLastPathComponent] stringByAppendingPathComponent:@""];
    SUFileManager *fileManager = [SUFileManager fileManagerWithAuthorizationToolPath:fileOperationToolPath];
    NSError *error = nil;
    [fileManager executePackageAtURL:pkgPath progressBlock:nil error:&error];

**Comment by kornelski** [comment]
Sorry, we don't support that API. It's a private implementation detail. It's not documented and it's likely to be changed in breaking ways in later versions.

The only way to install a PKG with sparkle is to make appcast XML with it.
