### ISSUE TITLE
A ghost of ImageOptim and: How to check if Sparkle is running?

### ISSUE THREAD

**Issue by haltlos** [sparkle-project/Sparkle#1265]
Hello, I am not a developer, but aware of Sparkle through the many apps that incorporate it. Something strange happened that one of you may want to address: On a macOS 10.13.5 Mac mini, I do not yet use apps with Sparkle, at least not that I am aware of. On an external drive connected to the Mac mini, there is a volume with a clone of my home folder from a previous OS X 10.6.8 system. See this screenshot:

![sparkle2](https://user-images.githubusercontent.com/4324234/42401095-627e2844-8174-11e8-8afb-9afafb17ccf4.png)

You can see that ImageOptim was one of the apps using Sparkle. I do NOT have ImageOptim installed on the High Sierra system.

This is what happened:

1. Connected a camera to the Mac mini

2. Opened Image Capture in order to download photos from the camera

3. In the bottom left, clicked on "Connecting this camera opens"

![screen shot 2018-07-06 at 23 12 27 3](https://user-images.githubusercontent.com/4324234/42401349-8b76516c-8175-11e8-8cd7-99b50952dfc6.png)
![screen shot 2018-07-06 at 23 11 52 3](https://user-images.githubusercontent.com/4324234/42401350-8d9ea264-8175-11e8-9ee7-a0d5bed0c472.png)

4. ImageOptim was listed in the apps to choose from. I could not believe it, because it is NOT installed. How can it be listed there?

5. Out of curiousity, I selected it.

6. Upon selecting it, nothing should have happened. Instead, a Sparkle dialogue opened, informing me that a newer version of ImageOptim is available. I closed that dialogue.

Isn't this really strange? 

The next day, I tried to reproduce this issue, but ImageOptim does not appear in ImageCapture any longer. Still, I think this is worth sharing. At least, I would like to know, which places I can check to see if Sparkle is in fact on the High Sierra system. Please tell me. 

Then one of you developers may want to figure out if what I saw is a security issue.

**Comment by kornelski** [comment]
This was a bug in old version of Sparkle that was in an old version of ImageOptim. 

Both were fixed years ago, but since ImageOptim will never have any update for 10.6, 10.6 is doomed to suffer this forever.
