### ISSUE TITLE
Mojave - Quit with no warning

### ISSUE THREAD

**Issue by bryanc-nz** [sparkle-project/Sparkle#1267]
I just spent a couple of hours trying to figure out why a user had reported my app to be crashing on Mojave.
Eventually I though to ask him if it was running from either /Applications or ~/Applications. It wasnt - moving to ~/Applications fixed his "crash". Sparkle had been shutting him down as soon as a check for updates request was made.
I had come across this in the past but I was pretty sure Sparkle generated a dialog to explain why it was terminating the app. If not, how can I intercept Sparkle's shutdown request and put up my own dialog.

**Comment by bryanc-nz** [comment]
Hmmm - and when I try to create the problem I do indeed get a crash. I did 'Check for Update' - Autoupdate is disabled. This the trace from the Xcode console. I can generate a full crashdump if required.

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff31cbd93b __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff5dc98a18 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff31cbd839 -[NSException raise] + 9
	3   AppKit                              0x00007fff2f1b8d1a -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 324
	4   AppKit                              0x00007fff2f1b8825 -[NSView(NSInternal) _updateDragRegionForHiddenStateChange] + 73
	5   AppKit                              0x00007fff2f1d397a -[NSView(NSInternal) _setHidden:setNeedsDisplay:] + 1236
	6   AppKit                              0x00007fff2f5d3275 -[NSButtonCell _updateBackgroundViewWithFrame:inView:] + 598
	7   AppKit                              0x00007fff2f5d3659 -[NSButtonCell _updateSubviewsInView:includeTitleTextField:] + 127
	8   AppKit                              0x00007fff2f655b33 __35-[NSControl _windowChangedKeyState]_block_invoke + 46
	9   AppKit                              0x00007fff2f2759e8 +[NSAppearance _performWithCurrentAppearance:usingBlock:] + 84
	10  AppKit                              0x00007fff2f232b41 -[NSControl _windowChangedKeyState] + 138
	11  AppKit                              0x00007fff2f232c4b -[NSView _windowChangedKeyState] + 253
	12  AppKit                              0x00007fff2f232c4b -[NSView _windowChangedKeyState] + 253
	13  AppKit                              0x00007fff2f232c4b -[NSView _windowChangedKeyState] + 253
	14  AppKit                              0x00007fff2f232c4b -[NSView _windowChangedKeyState] + 253
	15  AppKit                              0x00007fff2f232c4b -[NSView _windowChangedKeyState] + 253
	16  AppKit                              0x00007fff2f2b4aeb -[NSThemeFrame _windowChangedKeyState] + 46
	17  AppKit                              0x00007fff2f2b49e4 +[NSWindow _enableKeyStateChangeNotifications] + 355
	18  AppKit                              0x00007fff2f2af34f -[NSWindow _changeKeyAndMainLimitedOK:] + 1332
	19  AppKit                              0x00007fff2f31c40b -[NSWindow _orderOutAndCalcKeyWithCounter:stillVisible:docWindow:] + 1249
	20  AppKit                              0x00007fff2f2b1b99 NSPerformVisuallyAtomicChange + 132
	21  AppKit                              0x00007fff2fa2bb4e -[NSWindow _doWindowOrderOutWithWithKeyCalc:forCounter:orderingDone:docWindow:] + 80
	22  AppKit                              0x00007fff2fa2cf3b -[NSWindow _reallyDoOrderWindowOutRelativeTo:findKey:forCounter:force:isModal:] + 435
	23  AppKit                              0x00007fff2f2b8fe5 -[NSWindow _reallyDoOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 172
	24  AppKit                              0x00007fff2f2b7e46 -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 283
	25  AppKit                              0x00007fff2f2b7cb1 -[NSWindow orderWindow:relativeTo:] + 152
	26  AppKit                              0x00007fff2fa2ab27 -[NSWindow _finishClosingWindow] + 461
	27  AppKit                              0x00007fff2f3e59f2 -[NSWindow _close] + 364
	28  Sparkle                             0x0000000100cdbd57 -[SUUserInitiatedUpdateDriver closeCheckingWindow] + 122
	29  Sparkle                             0x0000000100cdc1fe -[SUUserInitiatedUpdateDriver appcastDidFinishLoading:] + 80
	30  Sparkle                             0x0000000100caeee1 -[SUAppcast downloaderDidFinishWithTemporaryDownloadData:] + 181
	31  Sparkle                             0x0000000100cc871f -[SPUDownloader downloadDidFinishWithData:] + 124
	32  Sparkle                             0x0000000100cbca06 -[SPUDownloaderSession downloadDidFinish] + 440
	33  Sparkle                             0x0000000100cbc271 -[SPUDownloaderSession URLSession:downloadTask:didFinishDownloadingToURL:] + 140
	34  CFNetwork                           0x00007fff30cd9ddb __82-[NSURLSession delegate_downloadTask:didFinishDownloadingToURL:completionHandler:]_block_invoke + 38
	35  Foundation                          0x00007fff34062bdb __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	36  Foundation                          0x00007fff34062a3f -[NSBlockOperation main] + 68
	37  Foundation                          0x00007fff34061003 -[__NSOperationInternal _start:] + 763
	38  Foundation                          0x00007fff3405d21b __NSOQSchedule_f + 227
	39  libdispatch.dylib                   0x00000001018f639b _dispatch_call_block_and_release + 12
	40  libdispatch.dylib                   0x00000001018f74c1 _dispatch_client_callout + 8
	41  libdispatch.dylib                   0x00000001018fa94d _dispatch_continuation_pop + 576
	42  libdispatch.dylib                   0x00000001018f9a21 _dispatch_async_redirect_invoke + 780
	43  libdispatch.dylib                   0x000000010190a068 _dispatch_root_queue_drain + 334
	44  libdispatch.dylib                   0x000000010190ab37 _dispatch_worker_thread2 + 125
	45  libsystem_pthread.dylib             0x0000000101972022 _pthread_wqthread + 623
	46  libsystem_pthread.dylib             0x0000000101971d45 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by kornelski** [comment]
Are you using version 1.20.0b1?

**Comment by bryanc-nz** [comment]
No - I am using 1.19.0 - current released version

**Comment by kornelski** [comment]
OK, I'll release the fixed version soon

**Comment by bryanc-nz** [comment]
I just tested with 1.20.0 and the problem is fixed. Thanks for the quick response.
