### ISSUE TITLE
Support the redesigned interface by Lennart Ziburski

### ISSUE THREAD

**Issue by glebd** [sparkle-project/Sparkle#127]
It would be great if Sparkle supported a re-designed app update interface described by Lennart Ziburski in _edit: updated dead link_ https://dribbble.com/shots/364911-Mac-Updating-UI-Redesign

**Comment by zorgiepoo** [comment]
I created a UI influenced from this in my [fork](https://github.com/zorgiepoo/Sparkle) just for testing purposes, except it was designed by me, who isn't any good at creating a good UI :). The 10.10 supported API to achieve this is by using `NSTitlebarAccessoryViewController`
