### ISSUE TITLE
SUAutomaticallyUpdate on a case by case basis

### ISSUE THREAD

**Issue by leovallet** [sparkle-project/Sparkle#1272]
Hi,

I want the user to view the update interface for some updates and to have a silent update for specifics updates. I didn't find a way to do that as SUAutomaticallyUpdate is NO or YES. Is there is a way to specify that in the item of the update inside the Appcast.xml ?

Thanks

**Comment by kornelski** [comment]
No, unfortunately the setting is global.

**Comment by zorgiepoo** [comment]
This is supported only for major upgrades through minimumAutoupdateVersion https://sparkle-project.org/documentation/publishing/
