### ISSUE TITLE
BoringSSL SSL_ERROR_ZERO_RETURN console warnings with Sparkle 1.19.0

### ISSUE THREAD

**Issue by lostminds** [sparkle-project/Sparkle#1276]
I have two projects using sparkle and I recently updated to start using version 1.19.0 (at the same time I also updated to XCode 9.4.1 and macOS 10.13.6) and since then, the first time after launch I trigger a check for updates in sparkle using checkForUpdatesInBackground or checkForUpdates: I get three of these warnings in the console:

[BoringSSL] Function boringssl_session_errorlog: line 2881 [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert

Trying the check for updates again seems to work fine and doesn't yield any further warnings.

As far as I can tell they don't seem to be causing any problems (the checks/connections/downloads seem to be working fine), and the warnings come a second or two after the check, so I'm guessing they're related to something not being closed correctly. Any idea of what might be causing this? Took me a while to track the problem down to Sparkle, so they might be causing other people confusion as well.

**Comment by kornelski** [comment]
We don't use BoringSSL, so I don't know where that's coming from.

**Comment by lostminds** [comment]
That's really strange, I don't use BoringSSL anywhere in my code either, and the warning messages only appear when triggering Sparkle updates, not when doing any other network access in my code. 

After doing some research it seems that in macOS 10.13 Apple may have started using a branch of BoringSSL internally, and this could be the origin of the warning messages. So even if Sparkle doesn't directly use BoringSSL, using system calls may indirectly result in BoringSSL use by the system, in turn triggering the warnings in some situations?

**Comment by kornelski** [comment]
Ah yes, that sounds plausible. But I'm not sure if there's anything we need to do about it, since we're using high level cocoa APIs.

**Comment by lostminds** [comment]
An update, and perhaps a clue to what is causing these warnings.:

I just upgraded to Sparkle 1.21 and now I can report that when just checking for new versions (and not finding one) I now no longer get these BoringSSL warnings as I did before. However, I still get the same warning message (three times) if I check for new versions and Sparkle finds a new version and shows the dialogue with the version update notes.
So, perhaps it's something you've now changed in the way Sparkle handles the connection getting the appcast xml file since 1.19, but you haven't changed in the way you get the version sparkle:releaseNotesLink content?

**Comment by kode54** [comment]
Speaking of BoringSSL errors, I'm now finding that Sparkle can't even check for updates, at all. My update file is beyond a 301 redirect message, and when it goes to fetch the file from the redirect, BoringSSL throws a whole lot of:

```
error	23:27:59.483167-0800	Cog	Connection 6: unable to determine interface type without an established connection
```

**Comment by zorgiepoo** [comment]
BoringSSL errors are probably red herrings / unrelated to Sparkle.
