### ISSUE TITLE
File not found - sparkle XML namespace link

### ISSUE THREAD

**Issue by grahammiln** [sparkle-project/Sparkle#1282]
The Sparkle namespace URL <http://www.andymatuschak.org/xml-namespaces/sparkle> currently redirects to <https://sparkle-project.org/appcast>. Then the **sparkle-project.org** URL returns a 404: file not found error.

https://github.com/sparkle-project/Sparkle/blob/8b88183c7d889a50fb9393f0b15492ee208cece4/generate_appcast/FeedXML.swift#L43

While the XML namespace URL [*need* not return anything specific](https://stackoverflow.com/questions/5758041/why-are-urls-in-xml-namespaces), could we better use this URL to link to something that benefits/explains/documents the Sparkle project?

**Comment by kornelski** [comment]
Fixed
