### ISSUE TITLE
generate_appcast does not add dsaSignature in Sparkle 1.20.0

### ISSUE THREAD

**Issue by mirkokiefer** [sparkle-project/Sparkle#1284]
I'm running the generate_appcast tool like this:

```
./bin/generate_appcast ./dsa_priv.pem ./releases/
```

For each release I'm getting a console log with 

```
releases/xxx-1.0.0-rc.3.zip -- file:///xxx/ 1.0.0-rc.3 __NSCFError
```

The resulting appcast.xml seems complete except for the missing dsaSignature properties. Actually the entire delta section is missing as well although the .delta file gets generated.

I don't see any other error output so pretty hard to debug for me.

The sign_update tool is working fine though - so I'm manually adding the missing properties at the moment. Appreciate any help!

**Comment by kornelski** [comment]
It's probably a problem with private key being generated with parameters that macOS doesn't support: #1180

Try generating the private key on an older OS. Sorry for the trouble :/
