### ISSUE TITLE
Problems with 1.20.0 (initial release)

### ISSUE THREAD

**Issue by bryanc-nz** [sparkle-project/Sparkle#1287]
On 18 July I downloaded Sparkle1.20.0, compiled it into my software and released my software with the 'latest' version of Sparkle.

Unfortunately this version of Sparkle was broken and re-released several days later with an identical version number, fixing the issues (missing localized files).

Now I am faced with the problem of how users can update my software. The version of my software that includes the broken Sparkle 1.20.0 does not seem to work with my newly updated appcast.xml.

Versions of my software that were released with Sparkle 1.19.x are working fine and happily read and update themselves using my latest appcast.

Is there anything I can put in the appcast file that will enable the 'broken' version to recognise and install the latest version of my software.

As an aside - Please guys - always update version numbers when you release new versions - no matter how trivial the change.

**Comment by kornelski** [comment]
Sorry about that.

I'm not even sure what exactly was the problem with that package. Missing localized files should just fall back to English. The package was built in the same way as the previous versions.

**Comment by bryanc-nz** [comment]
OK - I guess there is no solution to the missing resources in my released code. Thanks for the reply and I hope processes re version numbers will improve in the future.
Regards
Bryan

**Comment by kornelski** [comment]
OK, I'll remember about that.
