### ISSUE TITLE
How to properly use Sparkle for background app

### ISSUE THREAD

**Issue by billziss-gh** [sparkle-project/Sparkle#1289]
I have a background app ([EnergyBar](https://github.com/billziss-gh/EnergyBar)) and I want to use Sparkle to autoupdate it.

The app does not normally have any UI other than what is displayed in the Touch Bar. (There is a Settings dialog, but it is not normally visible.) In normal use the app is installed as a "Login Item"; it starts when the user logs in and closes when the user logs out or the machine shuts down.

I am trying to understand how to best use Sparkle in this scenario. Ideally I want updates to be performed in the background without any user interaction (controllable by a user setting/checkbox). My understanding is that normally Sparkle performs background updates when the app quits, which may not be possible in my case as the system may be shutting down. For this reason updates should happen when the application starts (or "just before it starts").

In more detail:
- The application has a checkbox: "Automatically download and install updates". If this is unchecked none of the following applies.
- The application upon startup checks whether an update has been downloaded. If yes, the update is installed and the application is restarted. No UI is presented.
- The application periodically checks (e.g. once a day or once a week) whether an update exists. If one exists it is downloaded, but **not** installed. Furthermore It is **never** installed during quit time, because the machine may be shutting down.
- It would also be nice if there was the possibility to determine if an update has been downloaded and is pending. This could be used to show an "Update pending" message in the app's Settings if the user does open them.

Please let me know if this is not the right forum for asking such questions.

**Comment by kornelski** [comment]
See delegate callbacks. If I remember correctly there is one that you get when the app is ready to restart.

**Comment by billziss-gh** [comment]
Thanks for your answer.

Are you talking about `updaterDidRelaunchApplication`? Unless I misunderstand this happens after an update has already happened and the application relaunches, so I am not sure how it would be useful in my scenario.

My scenario is really that I want automatic downloads while the app is running, but I do not want them installed when the app quits but rather when it starts up next time, because there is a high likelihood that the system is shutting down when the app quits.

**Comment by kornelski** [comment]
It's not that. I'm on mobile so I can't check, but there's one before restart that gives you a callback to invoke.

**Comment by billziss-gh** [comment]
I was not able to find the relevant information. But thank you for your help. Closing this.
