### ISSUE TITLE
Check when download is done

### ISSUE THREAD

**Issue by janssoner** [sparkle-project/Sparkle#1290]
By experimentation, I have found that CheckForUpdatesInBackground will only do the update if I exit the program after the download is complete.  I fixed this by putting a timer "pause" before exiting. I don't like to have an arbitrary number of seconds since different conditions can effect downloads.
Is there any way to check that download is complete?  I noticed while running in the debugger that the download complete is logged to debugger output window.

All the program does is basically below. It runs as an agent every 10 minutes and works.

  suupdater = [SUUpdater updaterForBundle:nsbAppBundle]; // updating main bundle
  [suupdater setAutomaticallyChecksForUpdates:YES];  // SUEnableAutomaticChecks
  [suupdater setAutomaticallyDownloadsUpdates:YES];   // SUAutomaticallyUpdate (silent)
   
  [suupdater checkForUpdatesInBackground];
  [NSTimer scheduledTimerWithTimeInterval:30.0f
                                   target:self
                                 selector:@selector(handleTimer:)
                                 userInfo:nil
                                  repeats:NO];
......
- (void) handleTimer:(NSTimer *)timer
{
  [NSApp terminate:nil];
}

**Comment by kornelski** [comment]
That's very unusual. What are you trying to do?

It's your program not a cocoa GUI app?

**Comment by janssoner** [comment]
It is a cocoa Gui app that does no GUI.  It is part of a bundle with another app, service, and a kext built in.  So it runs every 10 minutes (as an agent) if there is an update everything in bundle gets updated if necessary.  It works fine, just don't like the arbitrary 30-second wait.  I found out with debugging that the download is done in a separate thread.  If I exit before the thread is done the update does not happen.  So I would like a downloadIsFinished or nothngToDownload function etc.

code:
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification
{
  [NSApp hide:nil];
   CheckForSparkleUpdates();
  [NSTimer scheduledTimerWithTimeInterval:30.0f
                                   target:self
                                 selector:@selector(handleTimer:)
                                 userInfo:nil
                                  repeats:NO];
  
}

**Comment by janssoner** [comment]
I ended up using delegate willInstallUpdateOnQuit which seems to get called when the download is finished.
