### ISSUE TITLE
Appcast title tag ignored?

### ISSUE THREAD

**Issue by lanamelach** [sparkle-project/Sparkle#1291]
I am wondering what the purpose of the "title" tag is. Regardless of what is written there, when the update notification pops up it shows "A new version of _app name_ is available" and the next line says "_App name_ _new version_ is now available -- you have _old version_. Would you like to download it now?" So the title text from the appcast does not seem to appear anywhere. Is it a bug or it is supposed to work that way?

**Comment by kornelski** [comment]
The appcast is an extension of RSS feed format, so it inherits a bunch of fields that are not used for updates and are relevant only to regular RSS feed readers. `<title>` is one of them.
