### ISSUE TITLE
Can I run Autoupdate.app with command line?

### ISSUE THREAD

**Issue by kenchan0130** [sparkle-project/Sparkle#1292]
I wanted to confirm that Autoupdate.app is processing.
So, I run a script with command line like:

```bash
/path/to/Autoupdate.app/Contents/MacOS/Autoupdate /Applications/xxx.app /Applications/xxx.app "processId" "MyApp Folder" 0 0
```

However, it seemed that the process did not end, maybe hanging.
What is the cause of this?

---

My environment is below.
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1510
```

**Comment by kornelski** [comment]
This is our internal helper that cannot be run without the rest of Sparkle setting up environment for it.
