### ISSUE TITLE
Could Sparkle be installing the update when the previous version of the app has not exited completely.

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#1295]
Hello,

We are encountering the following issue sporadically:

Our app is crashing with an error message:

> Exception: EXC_BAD_INSTRUCTION  reason: this class is not key value coding-compliant for the key LabelText 

Such error happens when there is a failure in binding.  After looking into our telemetry and instrumentation, we found three things that are common among these error occurrences in the event log : 

1.  There is an app upgrade event that was recorded after this error event. 
2.  The key for the binding (as indicated in the error above) has been newly added in the version that the app is being updated to.
3. The occurrence of the crash in the previous version of the app, and the launch of the app after the upgrade happens in a time span of 30 seconds.

This makes me believe that the app upgrade (installing the latest version) is in process while the previous version of the app hasn't been completely exited. Since, the previous version of the app has not exited, it might be referencing to the UI from the updated app (that requires the binding key), while referencing to the ViewModel from the previous version of the app(which does not have the binding key).

Although this issue had occurred minimally,  Could this situation be possible in Sparkle?  We are using Sparkle version 1.14.1. 

Any help is appreciated.

**Comment by kornelski** [comment]
We wait for the app to quit before starting installation. We use kpoll and check pid for this, which should be accurate. 

We don't prevent user from starting the app again while the installation is in progress.

Is your app a daemon that could be automatically started again? Or is it large enough that user would have time to reopen it manually while installation is in progress?

Does your app need long time to quit?
