### ISSUE TITLE
Xcode 10 notarization error about Hardened Runtime for Autoupdate.app and fileop

### ISSUE THREAD

**Issue by hplusb** [sparkle-project/Sparkle#1297]
As Apple introduced new notarization process for apps distributing outside of Mac App Store, I am getting this error when I try to submit my application for notarization, which has Sparkle framework installed via CocoaPods.

![screen shot 2018-10-16 at 11 45 15](https://user-images.githubusercontent.com/33025255/47077730-48578000-d20a-11e8-8365-845733fbc2d4.png)

The error was first encountered for all bundles included in my app (helper app and other frameworks), however they all went away except these two mentioned bundles of Sparkle, after I enable Hardened Runtime with exceptions shown below through Project editor.

![screen shot 2018-10-16 at 13 05 25](https://user-images.githubusercontent.com/33025255/47077731-48578000-d20a-11e8-86fc-9a1824ce0b6e.png)

I am not well informed about the guidelines of this new notarization, as it just went out and I have already seen WWDC 2018 presentation about it but could not find any other documentation.

Any ideas how to enable hardened runtime for Sparkle's Autoupdate.app and fileop? Or is it just impossible for Sparkle like enabling sandbox, as the auto update procedure requires access to other apps?

**Comment by adib** [comment]
You can re-sign the Sparkle auto-updater app and apply hardened runtime to it in the process:

```
codesign --verbose --force --deep -o runtime \
--sign "${EXPANDED_CODE_SIGN_IDENTITY_NAME}" \
"${BUILT_PRODUCTS_DIR}/${WRAPPER_NAME}/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/AutoUpdate.app"
```

I've [written a post](https://cutecoder.org/programming/enable-hardened-runtime-sparkle/) on this issue, having encountered the problem myself.
