### ISSUE TITLE
You can't save file "applicationName (incomplete Update)" because the volume "91B89473-66c0-45F2-AFBA-605098BAE76A" is read only.

### ISSUE THREAD

**Issue by wangshugaung** [sparkle-project/Sparkle#1298]
![1539916580](https://user-images.githubusercontent.com/12858397/47194715-f7bb6080-d38a-11e8-9c3d-2dc136fd2cae.jpg)

**Comment by wangshugaung** [comment]
What causes this problem? @kornelski

**Comment by kornelski** [comment]
It looks like something has been broken by Apple's translocation: when you launch an app in macOS, it's not launched from where you think it is. It's copied to a hidden disk image and launched from there instead. https://lapcatsoftware.com/articles/app-translocation.html

**Comment by wangshugaung** [comment]
thanks,it's reason the app could copy itself to /Applications.

**Comment by wangshugaung** [comment]
thanks,it's reason the app could copy itself to /Applications.
