### ISSUE TITLE
Support Apple Hardened Runtime,  submitting app to Apple to be notarized

### ISSUE THREAD

**Issue by R0uter** [sparkle-project/Sparkle#1299]
> 2018-10-21 05:37:02 +0000  Distribution items ineligible: Error Domain=IDEDistributionMethodDeveloperIDErrorDomain Code=1 "Hardened Runtime is not enabled." UserInfo={NSLocalizedDescription=Hardened Runtime is not enabled., NSLocalizedRecoverySuggestion="Autoupdate.app" and "fileop" must be rebuilt with support for the Hardened Runtime. Enable the Hardened Runtime capability in the project editor, then test your app, rebuild your archive, and upload again.}

So, do you guys have recived apple's email to notify that we need notarized or macOS app?

> macOS Mojave is here. Give Mac users even more confidence in your software distributed outside the Mac App Store by submitting it to Apple to be notarized. When users on macOS Mojave first open a notarized app, installer package, or disk image, they’ll see a more streamlined Gatekeeper dialog and have confidence that it is not known malware. 
> 
> Download Xcode 10 and submit your software today. In an upcoming release of macOS, Gatekeeper will require Developer ID–signed software to be notarized by Apple. 
> 
> Learn about getting your software notarized https://developer.apple.com/developer-id/

**Comment by kornelski** [comment]
Please see #1266

**Comment by R0uter** [comment]
thx，Im closing it.
