### ISSUE TITLE
Issues with non-app bundles

### ISSUE THREAD

**Issue by sennap** [sparkle-project/Sparkle#1300]
Hi, I am having some major issues with non app bundles. The updates for new versions keep getting ignored. Is there much support for this, outside of the documentation specific to non-app bundles? Any help would be much appreciated! 

SUUpdater *updaterObj = [SUUpdater updaterForBundle:[NSBundle bundleForClass:[self class]]];
[updaterObj resetUpdateCycle];

**Comment by kornelski** [comment]
How are they ignored? Is it a problem with the timer that does the check? Is it a problem with downloading/parsing feed? Is it a problem with not running the installer?

**Comment by sennap** [comment]
Hey thanks for getting back to me and sorry for the late response. After some more debugging I have narrowed down what I believe is the issue. I'm getting an NSURL error : NSURLErrorCannotFindHost

**Comment by sennap** [comment]
Oh no actually the hostname can't be resolved. That's so strange. Thank you for the tip.
