### ISSUE TITLE
applyBinaryDelta reports Source hash mismatch when source and dest trees are identical

### ISSUE THREAD

**Issue by sagecook** [sparkle-project/Sparkle#1301]
Recently we have had our update fail to use our delta files, resorting to the full download.  The console.app reports this:

2018-10-26 17:40:31 +0000: ===== Starry Night Pro Plus 7.app =====
2018-10-26 17:40:31 +0000: Applying delta patch failed with error: Error Domain=NSCocoaErrorDomain Code=256 "Source doesn't have expected hash (f8043bddb4f6ab29baa1a6bd9f886e8871a8e68e != 76f168266f201cd709734a646541e79c17c7cf21).  Giving up." UserInfo={NSLocalizedDescription=Source doesn't have expected hash (f8043bddb4f6ab29baa1a6bd9f886e8871a8e68e != 76f168266f201cd709734a646541e79c17c7cf21).  Giving up.}

I don't see how this can happen as the xxx.app directory on the target machine is identical to the xxx.app directory on the build machine where we make the deltas.  I verified this by pulling down a copy of the build machine app directory and running a diff -rq with the one installed on my mac.
It might be relevant that I recently started making the deltas using a directory structure mounted from the NAS device.
I just ran a tar c <app dir> | shasum on both the build machine and my mac where the app is installed and the values are different.  If the files and directories are identical why would the shas be different?  Can we use something a little less sensitive?

**Comment by kornelski** [comment]
We include file metadata (permissions) in the hash.

**Comment by sagecook** [comment]
Ah, didn't know that.  This is related then to issue 1268 which I raised and closed.  On the NAS device all symbolic links in the xxx.app folder get 777 permissions whereas on the local mac filesystem (local HDD) they will get 755 permissions.
I am wondering if it is as easy as adding another test in the latestMinorVersionForMajorVersion() function which will continue in a case where ent->fts_info indicates it is a symbolic link.  Also, would there be any other function which also generates the tree hash I should modify?

**Comment by kornelski** [comment]
Interesting about symlinks.

So I think this bit could be modified:

```c
        if (MAJOR_VERSION_IS_AT_LEAST(majorVersion, SUBeigeMajorVersion)) {
            uint16_t mode = ent->fts_statp->st_mode;
            uint16_t type = ent->fts_info;
            uint16_t permissions = mode & PERMISSION_FLAGS;

            CC_SHA1_Update(&hashContext, &type, sizeof(type));
            CC_SHA1_Update(&hashContext, &permissions, sizeof(permissions));
        }
```

to use fake 755 permissions if the entry is a symlink.
