### ISSUE TITLE
XPC branch: Uncaught exception when closing update window in Mojave

### ISSUE THREAD

**Issue by teologov** [sparkle-project/Sparkle#1307]
Hi, I've just migrated to the `ui-separation-and-xpc` branch. Everything works well expect the next failure when closing the update window:
`*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer  for the key path "effectiveAppearance" from  because it is not registered as an observer.'`

It might be related to #1288.

**Comment by michelf** [comment]
I think this was fixed in #1293 and #1294. Is your version recent enough?

**Comment by kornelski** [comment]
I've hacked around it

**Comment by teologov** [comment]
Cool, thanks!
