### ISSUE TITLE
Delta updates using edDSA

### ISSUE THREAD

**Issue by Florrr** [sparkle-project/Sparkle#1308]
In order to support signing, i've implemented the 1.21.0a2 release.
Normal updating works fine using  edDSA (had to change my developer-id -therefore I needed to add signing)
Now I'm trying to implement delta updates using the "BinaryDelta" script. When trying to install, sparkle changes to a full update, with the console message:
`Failed to validate update before unarchiving because no DSA public key was found in the old app`

Is there anything, I'm doing wrong?

**Comment by kornelski** [comment]
The error means there's no additional `edDSASignature=""` attribute on *delta* update feed elements.

Have you tried using the `generate_appcast` tool to make the delta updates? It should be signing everything for you automatically.

**Comment by Florrr** [comment]
I've now created the appcast using `generate_appcast` - unfortunately the same error occured

my appcast looks like that:
`<item>
      <title>1.1.0.4</title>
      <pubDate>Mon, 12 Nov 2018 23:37:42 +0100</pubDate>
      <sparkle:minimumSystemVersion>10.13</sparkle:minimumSystemVersion>
      <enclosure url="{LINKFULL}" sparkle:version="1.1.0.4" sparkle:shortVersionString="1.1.0.4" length="15335122" type="application/octet-stream" sparkle:edSignature="{KEY}"/>
      <sparkle:deltas>
          <enclosure url="{LINKDELTA}" sparkle:version="1.1.0.4" sparkle:shortVersionString="1.1.0.4" sparkle:deltaFrom="1.1.0.3" length="831139" type="application/octet-stream" sparkle:edSignature="{KEYDELTA}"/></sparkle:deltas>
  </item>
  <item>`

(The script generates an xml entry named `edSignature` instead of `edDSASignature` - is there a difference?

**Comment by kornelski** [comment]
The `edSignature` attr is the correct one. I've made a typo in my previous comment. 

BTW: you *must* use your *old* Apple ID to add EdDSA or DSA signature. You can only change one identity at a time. It's not possible to change Apple ID identity of an app that didn't have DSA signature already in the old version.

**Comment by weevilgenius** [comment]
I'm seeing the same message with delta updates and it appears to be due to the absence of a DSA (not EdDSA) public key in my Info.plist.

It appears that SUUpdateValidator still requires a public DSA key to be present before it will validate a delta update.

https://github.com/sparkle-project/Sparkle/blob/d430c33bf49e1ab7fcb4430b01f3ca2122af9005/Sparkle/SUUpdateValidator.m#L52-L62

**Comment by kornelski** [comment]
Oh, that's a bug! Thanks for noticing.

**Comment by kornelski** [comment]
Fixed on master.
