### ISSUE TITLE
XPC branch: segmentation fault in generate_appcast on macOS Mojave

### ISSUE THREAD

**Issue by teologov** [sparkle-project/Sparkle#1309]
Hi, I've faced one more issue when ran generate_appcast in `ui-separation-and-xpc` branch. It fails with next error: `segmentation fault`.
Here are some details:
```
Process 37880 launched: './bin/generate_appcast' (x86_64)
Process 37880 stopped
* thread #4, queue = 'com.apple.root.default-qos', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001004bef9f generate_appcast`swift_getObjectType + 47
generate_appcast`swift_getObjectType:
->  0x1004bef9f <+47>: andq   (%rbx), %rax
    0x1004befa2 <+50>: testq  %rax, %rax
    0x1004befa5 <+53>: jne    0x1004befb9               ; <+73>
    0x1004befa7 <+55>: jmp    0x1004befcb               ; <+91>
Target 0: (generate_appcast) stopped.
```

**Comment by kornelski** [comment]
Are you able to build & run this tool yourself? If so, could you try it in Debug mode, so that it will print more details about the crash?

**Comment by teologov** [comment]
Yes, I successfully built it following the doc. How can I run it in Debug mode?

**Comment by teologov** [comment]
I am creating the signed with my identity .dmg file using https://github.com/LinusU/node-appdmg.

**Comment by teologov** [comment]
@kornelski, it seems it's something very similar to #1155. I managed to make it work with 1028 byte key (Sparkle 1.20.0):
```
openssl gendsa <(openssl dsaparam 1028) -out dsa_priv.pem
openssl dsa -in dsa_priv.pem -pubout -out dsa_pub.pem
```

**Comment by kornelski** [comment]
This is …unexpected! If I specify size 2047, it generates a 2048-bit key, but with an older digest algorithm (that's probably what macOS wants).

**Comment by kornelski** [comment]
So I think this issue may be fixed in the XPC branch.

1. I've copied some generate_appcast changes from master, so it now reports errors better

2. The "2047-bit" key hack

**Comment by teologov** [comment]
Got it. Ok, I'll test it again tonight. Thanks!

**Comment by teologov** [comment]
I've just generated keys again and tried to run `generate_appcast`. Everything works well. Thanks,  @kornelski!
