### ISSUE TITLE
generate_appcast just generates version 1.0

### ISSUE THREAD

**Issue by freman** [sparkle-project/Sparkle#1315]
So I have my updates directory (admittedly just dumped on my desktop for now)

```
$ ls updates
appcast.xml    stv.1.0.zip stv.1.1.zip
```

I run generate_appcast
```
$ ~/Documents/Xcode/stv/Pods/Sparkle/bin/generate_appcast ./updates
Written /Users/user/Desktop/stv/appcast.xml based on 2 updates
```

But when I look inside

`cat updates/appcast.xml`

```xml
<?xml version="1.0" standalone="yes"?><rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
<channel>
<title>stv</title>
<item>
<title>1.0</title>
<pubDate>Mon, 19 Nov 2018 14:11:21 +1000</pubDate>
<sparkle:minimumSystemVersion>10.14</sparkle:minimumSystemVersion>
<enclosure url="https://stv.internal/osx/stv.1.0.zip" sparkle:version="1" sparkle:shortVersionString="1.0" length="21018319" type="application/octet-stream" sparkle:edSignature="VbWYnZ2z0b8KvAigrrrsmxjsZvQQQQqNmwYC8OEzTGTlkUA+Ax7P3mxI3JUF3yIliFQlFtaUQIqVy7/BoGezAQ=="/>
</item>
</channel></rss>
```

But the plist has the right version in it?
```
$ mkdir tmp
$ cd tmp
$ unzip ../stv.1.1.zip
$ grep -A1 -iE "bundle.*version" stv.app/Contents/Info.plist
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
--
	<key>CFBundleShortVersionString</key>
	<string>1.1</string>
--
	<key>CFBundleVersion</key>
	<string>1.1</string>
```

**Comment by kornelski** [comment]
Is the zip file in ./updates folder?

**Comment by kornelski** [comment]
That `sparkle:version="1"` is suspicious. Does version 1.0 have the right `CFBundleVersion`?

**Comment by freman** [comment]
No it had this.
I'll change it to 1.0 and retry.

```
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
--
	<key>CFBundleVersion</key>
	<string>1</string>
```

**Comment by freman** [comment]
Here are the plists, for reference.

[Info.1.0.plist.txt](https://github.com/sparkle-project/Sparkle/files/2597450/Info.1.0.plist.txt)
[Info.1.1.plist.txt](https://github.com/sparkle-project/Sparkle/files/2597452/Info.1.1.plist.txt)

**Comment by kornelski** [comment]
Try deleting `~/Library/Caches/Sparkle_generate_appcast/`. There may be a cache of an older version of the app that had wrong plist.

**Comment by ProfDrLuigi** [comment]
I had exact the same Problem. Deleting Cache solved it. Added 
`rm -r ~/Library/Caches/Sparkle_generate_appcast/*`
to my Updatescript now.

**Comment by bendinwire** [comment]
Removing the cache worked for me as well. Thanks!

**Comment by zorgiepoo** [comment]
#1582 is supposed to be smarter about invalidating caches.
