### ISSUE TITLE
Administrator a

### ISSUE THREAD

**Issue by Ashton-W** [sparkle-project/Sparkle#1316]
I'm using a Mac with a user account that has restricted access to `/Applications`. I can install and run applications from my home directory, but I've noticed apps that use Sparkle autoupdate seem to require administrator access to install updates.
I think this is a bug because the path where the update actually needs to be applied is in my home directory, and I can make any modifications manually to the apps there. I've been able to find the patched app with the update applied in a temporary directory used by Sparkle and move it to the correct location myself, so Sparkle should be able to do that too.

My reproduction with any app that uses Sparkle for self updates:

1. Have `/Applications` not writeable by the current user 
1. Install app into `~/Applications`
1. Open app and check for updates with an update available (update with Sparkle)
1. Downloading update... completes
1. Click 'Install and Relaunch'
1. Installing update... Administrator User Name and Password dialog appears. "Sherlock (Autoupdate) wants to make changes" for example.

**Comment by kornelski** [comment]
You can see Console.app for details why we needed to ask for admin rights.

**Comment by sfsam** [comment]
@Ashton-W Did you figure this out? I have a user of my app who is reporting this same behavior. He is also using ~/Applications and running as a non-admin user.

**Comment by Ashton-W** [comment]
I didn’t @sfsam, I’m not sure where the problem is. Comment above suggests Sparkle needs to ask?

**Comment by sfsam** [comment]
@Ashton-W It's weird. The user says his other apps that use Sparkle don't give this prompt, but mine does.

**Comment by Ashton-W** [comment]
@sfsam I never noticed that but it’s possible.
Different versions of Sparkle in those apps? Different ways to use Sparkle in the application code? I’d be happy to try those apps if they are free.

**Comment by kornelski** [comment]
For example, Sparkle always prompts for password when you use `.pkg` updates. Also it prompts if your `.app` is owned by root.

**Comment by sfsam** [comment]
My app (https://www.mowglii.com/itsycal/) is in a `.zip`. Most users, including myself, don't get prompted for a password. I'm running as admin and using /Applications. The user who reported this is running as a standard non-admin user and is using ~/Applications. This is what they see:

![screen-shot 2019-06-08 at 20 11 56](https://user-images.githubusercontent.com/118104/59292372-ccdf8e80-8c31-11e9-81cf-c9df9846d956.jpg)

**Comment by kornelski** [comment]
I think Sparkle's behavior is correct. I can't do anything other than again refer you to Console.app to learn why Sparkle asked for permissions in this case.

**Comment by zorgiepoo** [comment]
Sparkle 2 might be better about this, not currently actionable.
