### ISSUE TITLE
Support kSecUseKeychain in generate_appcast

### ISSUE THREAD

**Issue by maleetz** [sparkle-project/Sparkle#1318]
It would be nice to add a parameter to generate_appcast that lets the user specify which keychain to add the private key. This can be done using the [kSecUseKeychain](https://developer.apple.com/documentation/security/ksecusekeychain) dictionary key passed to SecAddItem.

**Comment by zorgiepoo** [comment]
Custom keychain management APIs are deprecated, we shouldn't pursue them now.
