### ISSUE TITLE
Update codesign script for Hardened Runtime

### ISSUE THREAD

**Issue by kolpanic** [sparkle-project/Sparkle#1319]
Based on my experience building Sparkle for use in a sandboxed & notarized app (https://github.com/sparkle-project/Sparkle/issues/1266#issuecomment-440789584 and subsequent discussion), the script used to `codesign` the XPCs should be updated to use the `-o runtime` flag. In addition, the script should also `codesign` the executables embedded in Sparkle.framework.

1. ~The [command in `codesign_xpc`](/sparkle-project/Sparkle/blob/ui-separation-and-xpc/bin/codesign_xpc#L13) should have `"-o", "runtime"` added to its arguments.~
2. Rename `codesign_xpc` to `codesign_embedded_executable`
3. Rename [`xpc_service(s)`](/sparkle-project/Sparkle/blob/ui-separation-and-xpc/bin/codesign_xpc#L40) to `executable(s)`.
4. Update the [installation instructions](/sparkle-project/Sparkle/blob/ui-separation-and-xpc/INSTALL.markdown) with the new script name and the necessity to sign the executables embedded in Sparkle.framework

**Comment by dreadsword** [comment]
Mojave 10.14.5 will require non Mac App Store apps to be hardened.

**Comment by kolpanic** [comment]
In that case, the `runtime` argument shouldn't be optional. I'll update the issue description.

**Comment by kornelski** [comment]
Can you make a PR with this?

**Comment by kolpanic** [comment]
I'd love to, but I already have a customized fork under my personal account for [Coruscation](/kolpanic/Coruscation), and I don't want to update it.

(I'd fork to our work org. but I don't have the permission. We also want to try to get the ui-separation-and-xpc branch synced with master so we can use EdDSA signing and build with Xcode 10.2.)

**Comment by chess92** [comment]
Is there a time estimate when this will be added to the release version of Sparkle? Or a solution that works on the master branch?

I have attempted to build / archive Sparkle with Hardened runtime with no success (using the latest master branch). The only two targets with the Capabilities tab are "Sparkle Test App" and "Autoupdate" and I have them both set to Hardened Runtime.

**Comment by kolpanic** [comment]
@chess92 This is the procedure I used to get Sparkle built for our apps with sandboxing and hardened runtime.
https://github.com/sparkle-project/Sparkle/issues/1266#issuecomment-440789584

**Comment by chess92** [comment]
ok thank you, I will check it out

**Comment by kolpanic** [comment]
Looks like point 1 was taken care of by #1391.

We were able to fork the repo to our work org., so I'll do the other points.

**Comment by dreadsword** [comment]
Will this update be available via cocoapods?
