### ISSUE TITLE
Cannot check update every time app start

### ISSUE THREAD

**Issue by fpfengpan** [sparkle-project/Sparkle#1321]
I am using the 1.21.0 version. It cannot check update every time I start my app. It can check the updates when manually click 'check for update' in MainMenu. Is there anything I need to do when app start?

**Comment by kornelski** [comment]
We intentionally don't check *every* time. We check once a day.

You can set `SUScheduledCheckInterval` in `Info.plist` to something else to check more often.

**Comment by fpfengpan** [comment]
So if the app keep running several days(without quit), it will still check every day, right?

**Comment by kornelski** [comment]
Yes, there's a timer that checks even if the app is long-running.
