### ISSUE TITLE
Delta not applied, downloads delta first, then the whole app

### ISSUE THREAD

**Issue by mortenjust** [sparkle-project/Sparkle#1322]
I'm using generate_appcast and edSignature. When users download the update, the progress reporting is weird, see the attached gif. First, it seems, it downloads the delta, and then it goes into this strange state where the "total file size" label grows as the user downloads. 

I am testing with only changing the bundle versions in plist.info 

![sparkleupdatedelta](https://user-images.githubusercontent.com/1548468/49639001-1c869880-fa0a-11e8-972c-a2dd292d7c79.gif)

**Comment by mortenjust** [comment]
I'm hosting the update on Netflify, and it seems they don't set the total size header correctly, as Safari also can't see the total file size. 

So this issue is now about not patching the delta after downloading it initially

**Comment by kornelski** [comment]
In the `Console.app` put "Sparkle" in the search box to filter out all the other noise that's there.

If it downloads delta, and then downloads the entire app, it means the delta failed for some reason, and the whole app is used as a fallback. 

Given that the whole app fails to apply too, it's probably a problem with the signatures in both cases.

Have you used `generate_appcast` tool to sign the update?

**Comment by mortenjust** [comment]
Yeah, I used `generate_appcast`. Meanwhile I've switched to using Sparkle through DevMate, and deltas are working perfectly, so most likely an error on my side.
