### ISSUE TITLE
sign_update via ssh: "Unable to access required key in the Keychain"?

### ISSUE THREAD

**Issue by quantonganh** [sparkle-project/Sparkle#1323]
- Sparkle-1.21.0
- OS X 10.11

`generate_appcast` doesn't work with `.dmg` file:

```
Error generating appcast from directory /Users/quanta/Downloads/updates
 Error Domain=SUSparkleErrorDomain Code=1001 "No usable archives found in /Users/quanta/Downloads/updates" UserInfo={NSLocalizedDescription=No usable archives found in /Users/quanta/Downloads/updates}
```

So, I have to create `appcast.xml` manually:

```
<?xml version="1.0" standalone="yes"?>
<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
    <channel>
        <title>x</title>
        <item>
            <title>1.0.0.2891</title>
            <pubDate>Thu, 06 Dec 2018 17:25:26 +0800</pubDate>
            <sparkle:minimumSystemVersion>10.7</sparkle:minimumSystemVersion>
            <enclosure url="https://domain.com/x.dmg" sparkle:version="1.0.0.2891" sparkle:shortVersionString="1.0.0.2891" length="86454539" type="application/octet-stream"/>
        </item>
    </channel>
</rss>
```

Got this error when testing:

>DSA signature validation of the package failed. The update contains an installer package, and valid DSA signatures are mandatory for all installer packages. The update will be rejected. Sign the installer with a valid DSA key or use an .app bundle update instead.

First time running `sign_update`, I choose "Always allow", so it does not ask for password in the next time.

But I still got this error when running via ssh:

```
$ ~/Downloads/Sparkle-1.21.0/bin/sign_update /path/to/x.dmg
ERROR! Unable to access required key in the Keychain -25308 (you can look it up at osstatus.com)
```

I know that we can use `openssl` to do the same thing: https://github.com/sparkle-project/Sparkle/blob/master/bin/old_dsa_scripts/sign_update

but how can I export `dsa_priv.pem` from my keychain?

**Comment by kornelski** [comment]
Did you run `generate_keys`?

**Comment by kornelski** [comment]
The error 25308 is for "Interaction with the Security Server is not allowed." 

So it looks like macOS is blocking access to the keychain. Maybe you have security settings set to allow only Mac App Store applications? Or the keychain is locked?

**Comment by kornelski** [comment]
I've codesigned the tools in Sparkle 1.21.1. See if that helps.

**Comment by kornelski** [comment]
One more thing to try is: open Keychain Access tool, find the key:

<img width="843" alt="keychain access tool" src="https://user-images.githubusercontent.com/72159/49734047-016e8f80-fc7b-11e8-93f8-c7f3bd7243e0.png">

and try removing or re-adding the tools to the access list:

<img width="646" alt="tools" src="https://user-images.githubusercontent.com/72159/49734070-08959d80-fc7b-11e8-839f-861eb2cc3bc5.png">

**Comment by quantonganh** [comment]
> The error 25308 is for "Interaction with the Security Server is not allowed."

I know.

> Maybe you have security settings set to allow only Mac App Store applications?

No, the current setting is "Mac App Store and identified developers".

> Or the keychain is locked?

Please note that, `sign_update` works fine if I run it directly (not via `ssh`).

**Comment by kornelski** [comment]
Ahh, SSH. That's probably because there's no UI session to ask for password, etc. 

Back in the days this could be worked around by launching a shell script via applescript:

```sh
osascript -e 'do shell script "foo.sh"'
```

**Comment by quantonganh** [comment]
> That's probably because there's no UI session to ask for password, etc.

As I said, I choose "Always allow" at the first time running, so it doesn't ask for password from 2nd time.

**Comment by quantonganh** [comment]
> I've codesigned the tools in Sparkle 1.21.1. See if that helps.

Now the error is:

```
$ Sparkle-1.21.1/bin/sign_update /path/to/x.dmg
ERROR! The operating system has blocked access to the Keychain.
```

**Comment by quantonganh** [comment]
> Back in the days this could be worked around by launching a shell script via applescript:

Same error.

1.21.0:

```
$ osascript -e 'do shell script "/Users/admin/Downloads/sign_update.sh"'
0:55: execution error: ERROR! Unable to access required key in the Keychain -25308 (you can look it up at osstatus.com) (1)
```

1.21.1:

```
$ osascript -e 'do shell script "/Users/admin/Downloads/sign_update.sh"'
0:55: execution error: ERROR! The operating system has blocked access to the Keychain. (1)
```

**Comment by quantonganh** [comment]
> and try removing or re-adding the tools to the access list:

How can does this help? I tried and nothing changes.

**Comment by kornelski** [comment]
So it seems like macOS just won't allow it over SSH. I don't have any control over it. You will have to use GUI terminal (or try the applescript hack to upgrade SSH session to a GUI session).

**Comment by quantonganh** [comment]
> Or the keychain is locked?

You was right. keychain is locked when running via ssh session. I have to unlock it before using `sign_update`:

```
security unlock-keychain -p "$pa55w0rd" /Users/admin/Library/Keychains/login.keychain
```
