### ISSUE TITLE
How to use SUPackageInstaller to specify a custom installer?

### ISSUE THREAD

**Issue by quantonganh** [sparkle-project/Sparkle#1324]
We have 2 `.pkg` files in `.dmg`: one to install and another to uninstall.

Problem: after extracting, Sparkle runs `Uninstall version 2898.pkg`:

>Sparkle: Authorization required to run pkg installer file:///Users/quanta/Library/Caches/ui.id/org.sparkle-project.Sparkle/PersistentDownloads/QACyWtEtT/x%201.0.0.2898/Uninstall%20version%202898.pkg

I found something here: https://stackoverflow.com/a/17437689/631612

Question: how to use `SUPackageInstaller` to run `Install version 2898.pkg`?

**Comment by kornelski** [comment]
Put the uninstall one in a folder. If I recall correctly, we're scanning the top-level directory.

**Comment by kornelski** [comment]
Alternatively, don't use the DMG for updates. Use regular ZIP instead. It'll be faster, more reliable and you'll only need to ship the main installer.

**Comment by quantonganh** [comment]
@kornelski Thanks.

It's ok now if I just zip the `installer.pkg` file:

```
ditto -c -k --sequesterRsrc dmgbuild/"${installer_signed_filename}" sparkle/"${sparkle_filename}"
```
