### ISSUE TITLE
generate_appcast doesn't work with non-app bundles?

### ISSUE THREAD

**Issue by glouel** [sparkle-project/Sparkle#1330]
Hi everyone

I'm trying to integrate Sparkle into a MacOS Screensaver (https://github.com/JohnCoates/Aerial). I understand this is very much an edge case but we've seen that Sparkle can handle non-app bundles now in the documentation : https://sparkle-project.org/documentation/bundles/ 

That part of the documentation looks fine (we had an issue with cocoapods not adding the "[CP] Embed Pods Frameworks" step that copies the Sparkle.framework in the .saver too, but adding that copy step manually fixed things), I do have an issue generating the appcast though using /bin/generate_appcast, I get: 

```
Error generating appcast from directory /Users/glouel/Desktop/AerialBuilds
 Error Domain=SUSparkleErrorDomain Code=1001 "No usable archives found in /Users/glouel/Desktop/AerialBuilds" UserInfo={NSLocalizedDescription=No usable archives found in /Users/glouel/Desktop/AerialBuilds}
```

I've looked at the documentation but didn't find much, the closest thing I found is this : https://github.com/sparkle-project/Sparkle/issues/1227#issuecomment-386830218

which says that you need a .app in a .zip. In our case, a screensaver is with the .saver extension. 

Renaming the .saver to .app fixes the issue. 

Am I correct in assuming that generate_appcast won't work in our case and that I should generate the appcast myself ? This is very much a minor issue in any case. 

Thanks !

**Comment by kornelski** [comment]
It *almost* works in your case. It's just it has a naive check for `*.app` extension. You could fix it by making a smarter check for ~~app~~ bundles.

**Comment by glouel** [comment]
@kornelski thanks for your quick reply. Following your message, I had a look at the project and it looks like this line here is the issue : https://github.com/sparkle-project/Sparkle/blob/0480b9bb2518c09e7eeff24404e1ab9328a4542e/generate_appcast/ArchiveItem.swift#L72

I guess adding .saver in the filter should probably do it. Would you be interested in a PR or that's too much of an edge case ? If so I'll try to make one later this week. Thanks !

**Comment by kornelski** [comment]
Changing it to also allow saver (and ideally a few others) would be good. It would be the best if used some smarter way of checking (check for `Info.plist` inside maybe? maybe there's macOS that checks them all?)

**Comment by glouel** [comment]
I tried to look it up, the common name for those plug-ins is loadable bundles in Apple Documentation : https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/LoadingCode/Concepts/AboutLoadableBundles.html#//apple_ref/doc/uid/20001268-BCIDBAEJ

They say this regarding available extensions:

> OS X defines the extension .bundle to identify loadable bundles. You can also define your own extension (and associated icon) for a particular type of bundle.

So not very helpful. 

Checking if the file is a directory, and if so looking inside for the existence of Contents/Info.plist would probably be the way to go ? An extra check to make sure it's a Loadable Bundle would be to look for the presence of a CFBundleExecutable field. 

>CFBundleExecutable: the name of the executable, typically the same as the bundle directory without the extension

That may be a convoluted solution though.

**Comment by kornelski** [comment]
Interesting find with `mdls`. However, bringing Spotlight and UTIs into this feels heavy. Compared to this, checking for `Contents/Info.plist` seems fine :)

**Comment by Wevah** [comment]
A `UTTypeConformsTo()` check should only be a few lines of code; no Spotlight required.

**Comment by Wevah** [comment]
Here's a quick go at it, which I haven't tested yet: https://github.com/Wevah/Sparkle/tree/generate-appcast-bundle-check

My Swift-fu is also not that great, so if my code Swiftiness is wrong, let me know!

**Comment by kornelski** [comment]
That's a neat idea!

**Comment by kornelski** [comment]
@glouel Can you check the version from the master branch and see if it works for you now?

**Comment by glouel** [comment]
@kornelski sorry I didn't get back earlier, I'll check master today and let you know.

**Comment by glouel** [comment]
@kornelski maybe I misunderstood what you meant, I did check this project master branch and it didn't look like you had merged @Wevah 's changes. I added his changes manually and indeed, yes it works correctly !

```
glouel@iMac-de-Guillaume-2:~/Library/Developer/Xcode/DerivedData/Sparkle-dzrzqljsugjwwweeccpprtunazha/Build/Products/Release$ ./generate_appcast ~/Desktop/AerialBuilds/
Written /Users/glouel/Desktop/AerialBuilds/appcast.xml based on 1 updates
```

Thanks to @Wevah & you for following up on this!

**Comment by kornelski** [comment]
Oops, I forgot to press the merge button :)

**Comment by kornelski** [comment]
It is merged now. Good to know it works.

**Comment by glouel** [comment]
No worries, thanks a lot again !

**Comment by Wevah** [comment]
I have a small patch that fixes a few nits; will file a PR.
