### ISSUE TITLE
EdDSA support in 1.21 introduced new warnings (-Wdirect-ivar-access)

### ISSUE THREAD

**Issue by akempgen** [sparkle-project/Sparkle#1334]
Xcode Version 10.1 (10B61)
Sparkle Version 1.21.1

/Colloquy/Colloquy/Carthage/Checkouts/Sparkle/Sparkle/SUSignatures.m:42:38: Instance variable 'ed25519_signature' is being directly accessed
/Colloquy/Colloquy/Carthage/Checkouts/Sparkle/Sparkle/SUSignatures.m:43:19: Instance variable 'ed25519_signature' is being directly accessed
/Colloquy/Colloquy/Carthage/Checkouts/Sparkle/Sparkle/SUSignatures.m:44:26: Instance variable 'ed25519_signature' is being directly accessed
/Colloquy/Colloquy/Carthage/Checkouts/Sparkle/Sparkle/SUSignatures.m:80:38: Instance variable 'ed25519_public_key' is being directly accessed
/Colloquy/Colloquy/Carthage/Checkouts/Sparkle/Sparkle/SUSignatures.m:81:19: Instance variable 'ed25519_public_key' is being directly accessed
/Colloquy/Colloquy/Carthage/Checkouts/Sparkle/Sparkle/SUSignatures.m:82:26: Instance variable 'ed25519_public_key' is being directly accessed

**Comment by akempgen** [comment]
@kornelski cc

**Comment by akempgen** [comment]
nm, I see that they're already suppressed in #1331, so we only need a new release

**Comment by kornelski** [comment]
Yup.
