### ISSUE TITLE
An error occurred while downloading the update. Please try again later.

### ISSUE THREAD

**Issue by mentalmushroom** [sparkle-project/Sparkle#1335]
As the title suggests, I began to face this error when trying to update my application. I have checked ~/Library/Logs/SparkleUpdateLog.log, but there are only two lines, not really meaningful:
2018-12-17 15:02:46 +0000: ===== Autoupdate =====
2018-12-17 15:02:46 +0000: mdimporting

What could be the reason? 

I am using Sparkle 1.20 on Mac OS X 10.14 Mojave.

**Comment by kornelski** [comment]
I can't find "mdimporting" in 1.20's source code. The last version to say it was 1.14, which is rather old now.
