### ISSUE TITLE
Unable to successfully sign update using DSA key

### ISSUE THREAD

**Issue by colincameron** [sparkle-project/Sparkle#1336]
I have an application that has been in use for a number of years now, successfully using Sparkle for updates. I need to be able to change the Code Signing identity to a new company due to a change in our company structure. This was back in June 2018. At the time, I discovered it would be a 2-step process, with the first update having to be distributed using the old code signing identity, but including a DSA key, and the second update distributed using the new code signing identity, with my update zip file signed, and a `sparkle:dsaSignature` field in the appcast.

I distributed the first update, containing the public key in June, and I'm now at the stage of distributing the second update, which needs to be signed by the new Code Signing identity.

Since a recent update to Sparkle has deprecated DSA keys in favour of EdDSA, I used the `sign_update` script from version 1.18.1 using my private key generated in June. Running this gives a different signature every time, and when I published my appcast using this signature, the end-user isn't able to install the update. The error given in Console.app is "The update archive isn't signed with a DSA key, and the app is signed with a new Code Signing identity that doesn't match code signing of the original app".

I've tried updating to the latest version of Sparkle (1.21.0), and using the `generate_appcast` tool, providing my private key, but the generated xml file doesn't contain `sparkle:dsaSignature`.

How can I successfully sign my update using the DSA keys that I already have?

**Comment by kornelski** [comment]
If `generate_appcast` doesn't put DSA signature, it means either:

* you haven't specified your private key on the command line, or
* the app bundle's Info.plist doesn't have filename that points to a public DSA key

**Comment by colincameron** [comment]
> the app bundle's Info.plist doesn't have filename that points to a public DSA key

This is what was causing the issue - I thought I had added this key but I hadn't. Thanks for the help.
