### ISSUE TITLE
User reports updating never finishes

### ISSUE THREAD

**Issue by gnachman** [sparkle-project/Sparkle#1339]
See the original report here:

https://gitlab.com/gnachman/iterm2/issues/7397#note_127920128

It looks like the installer never finishes running. He found a bunch of messages in Console.app but they didn't look like errors to me. Are there any additional steps I can advise him to take to provide more diagnostics?

**Comment by kornelski** [comment]
Does the installer, when run from command line, work?

This is what we run:

```sh
/usr/sbin/installer -verboseR -pkg path-to-update.pkg -target /
```

**Comment by gnachman** [comment]
What's the proper value for `path-to-update.pkg`? Is that the zip file I publish in my appcast?

**Comment by kornelski** [comment]
In your bug you've said installer, I assumed you mean Apple's `installer` command that installs `.pkg` packages. 

So the `path-to-update.pkg` is the unzipped `.pkg` from the update.

**Comment by kornelski** [comment]
Which version of Sparkle are you using?

**Comment by gnachman** [comment]
I'm on 1.17.

**Comment by fujisoft** [comment]
Looks to be a duplicate of https://github.com/sparkle-project/Sparkle/issues/1079

**Comment by zorgiepoo** [comment]
Might not be an issue anymore and no diagnostics to go off here, I assume this was not referring to pkg updates.
