### ISSUE TITLE
Update non-sandboxed app to sandboxed with hardened runtime enabled

### ISSUE THREAD

**Issue by Mortennn** [sparkle-project/Sparkle#1342]
Will it be a problem to update an app from non-sandboxed to sandboxed with hardened runtime enabled? More specific, will this break the update functionallity in version 1.21.2?

**Comment by kornelski** [comment]
Sparkle v1.x works fine with hardened runtime, but it doesn't work inside sandboxed apps.

Sparkle v1.x can upgrade to an app using Sparkle v2.x.

So make sure to switch to Sparkle 2.x in the sandboxed app.

**Comment by Mortennn** [comment]
Thank you for clarifying!
