### ISSUE TITLE
User can't be notified that new updates are not available for their system

### ISSUE THREAD

**Issue by simonwagner** [sparkle-project/Sparkle#1345]
Currently, if we make an update available, which is no longer available for older versions of macOS, users that are still using our app won't get notified that there is an update available.

If they check for an update, they will only see Sparkle's "You're up-to-date!" message and think that they are using the current version.

We would like to show them a message, that there is an update available, but it is not installable on their machine. At the moment we have users, who are confused that they see the "You're up-to-date!" message, although there is a newer version downloadable from our website. We would also like to push our users into the direction of updating their OS so that they can use the newer version.

Therefore we would like to be able to implement a SUUpdaterDelegate method that would allow us to modify the "You're up-to-date!" message when there is an uninstallable update available.

Of course we could just modify the Sparkle code to our needs, but I would prefer if we could continue using "stock" Sparkle. I have already implemented the pull request #1344 that might be acceptable for you, which implements our needed functionality.

**Comment by kornelski** [comment]
That's a very good point. I think it may be a common problem, so we should modify Sparkle itself to always warn about an update for a newer OS.
