### ISSUE TITLE
Handling opt-in beta updates in existing app

### ISSUE THREAD

**Issue by ianbytchek** [sparkle-project/Sparkle#1348]
I want to introduce beta updates, but only for users who opt-in. Is there a way to issue beta updates on existing app with enabled automatic updates and not trigger the beta update before the user opts-in? To illustrate this, there're a bunch of versions in the wild, like 1.0 and 2.0, and the new 3.0-beta. I don't want users with 1.0-2.0 to get beta installed on their machines without getting their consent first.

My current strategy in mind is:
1. Create `beta-appcast.xml` with 3.0-beta.
2. Create new version 2.1 with beta opt-in user preference.
3. Check for beta updates in `beta-appcast.xml` if user has 2.1 and opted-in for beta program.

Or something along these lines, which involves another `appcast.xml` file to ensure existing users don't get beta installed automatically.

I want to know if there's another way of doing this without introducing a second `appcast.xml`, like a `minAppVersion` constraint for example, to enable autoupdating to beta only from version 2.1 where the opt-in was introduced and which handles the auto-update behaviour.

**Comment by kornelski** [comment]
Currently a second appcast is the only way.
