### ISSUE TITLE
Software update dialog is set at frontmost window, unable to get any other application's dialog on top of it

### ISSUE THREAD

**Issue by SyamalaHari** [sparkle-project/Sparkle#1349]
In my Mac Application written in swift, I am making below call to get software update window suUpdate?.checkForUpdates(sender)
Software update window is coming as front most, I am not able to switch the focus to other applications dialog. I am using 1.21.2 latest version of sparkle.

 Thanks

**Comment by kornelski** [comment]
This is intended behavior. We don't want the update window blocking user's work.

**Comment by syammala** [comment]
No, Its blocking other windows to become front most window

**Comment by kornelski** [comment]
Oh, sorry. I misread your message.

Is your application a regular app that is visible in the Dock?

**Comment by syammala** [comment]
Yes it appears in Dock, I am calling suUpdate?.checkForUpdates(sender) as one of the menuItem action of statusmenu. When I click on it software update window will become front order window and will not allow any window to be the front most. Thanks

**Comment by zorgiepoo** [comment]
#924
