### ISSUE TITLE
Store last found version along with last check date

### ISSUE THREAD

**Issue by lostminds** [sparkle-project/Sparkle#1359]
I think it could be useful if Sparkle saved the version number of any new versions found when checking for updates, in case the user decides not to update (dismissing the dialogue). 

This found version could then be exposed like the last check date on the Updater object (perhaps a last found update version) to be used by apps for reminders to users that there is a new version available that they just haven't updated to yet.

I'm not sure if this is a big problem, but sometimes I think users will just quickly dismiss update dialogues because they pop up at bad times, which might mean they miss out on the update for a long time.

**Comment by zorgiepoo** [comment]
We have delegate methods for what option is chosen from the user.
