### ISSUE TITLE
Upgrading to EdDSA, key safety and consequences of loosing it

### ISSUE THREAD

**Issue by ianbytchek** [sparkle-project/Sparkle#1360]
While figuring out the new EdDSA mechanism I noticed the following line in the documentation, pretty sure it was relevant with earlier DSA too:
> You don’t need to do anything with it, but don’t lose access to your Mac’s Keychain. If you lose it, you may not be able to issue any new updates!

Then I came across #1355 and got a little confused:
1. Doesn't the new signature mean that the old appcast.xml no longer can be used and users must upgrade manually? This seems like a huge condition not mentioned anywhere? 
2. Should I export the EdDSA and keep it else where in case of loosing access to the keychain? Any recommendations / best practices with that?

**Comment by kornelski** [comment]
1. No. The appcast can have both DSA and EdDSA signatures at the same time, so both older and newer versions can use it.

2. You can back up `login.keychain` file that is encrypted using your Mac account's password (and then don't forget Mac account's password).

**Comment by ianbytchek** [comment]
I like what I'm hearing! 😄 So, both means I need to create DSA and EdDSA signatures for the update, correct? ~~Can existing tools be used for that? `sign_update` refuses to work with explicitly provided DSA key and looks like only…~~ Okay, finally decided to check and it looks like the previous `sign_update` has moved into `old_dsa_scripts`. Great!

So, what's the strategy in the long-run? Stop using DSA in a few releases and either ignore users with pre-EdDSA signatures or add intermediary version with final DSA support with an alternative solution, like manual download & install?

**Comment by kornelski** [comment]
To be honest, we haven't worked out the long-term migration strategy yet #1355 

It might be like this:

1. I need to release Sparkle that stops caring whether there's old DSA or not
2. Change appcast URL in the new app, so that you keep an old DSA appcast for old DSA apps "forever"
3. Start using new appcast URL with new EdDSA signatures only

**Comment by ianbytchek** [comment]
Got you. Thanks for confirming this. One final thing, Sparkle sends `User-Agent: MyApp/1.2.3 Sparkle/1.21.2` header with the `appcast.xml` request. Do you remember roughly how long has this been around and if it might change in the future? Want to know how reliable this in dynamic appcast requests.

**Comment by kornelski** [comment]
It's been forever, and it's reliable except that the app name is localized, so you get ? for non-ASCII names if you localize your file name.

**Comment by ianbytchek** [comment]
Ah, that's a very good point! Thanks for the insight Kornel! Much appreciated! 👍

**Comment by ianbytchek** [comment]
@kornelski Out of curiosity, wont signing the dmg file with DSA and EdDSA produce a conflict or override one another? Or are two independent of each other?

**Comment by kornelski** [comment]
Both can coexist. There's a new RSS attribute for EdDSA.
