### ISSUE TITLE
How to Store private key for signing sparkle updates which is in keychain?

### ISSUE THREAD

**Issue by premkolindala** [sparkle-project/Sparkle#1364]
I have few questions regarding EdDSA signatures
1. I am already using sparkle for updates with apple code signing but not EdDSA .Now i want add EdDSA to latest update is that possible?
2.If i want to  EdDSA i need to add `SUPublicEDKey` in info plist  `./bin/generate_keys` what ever the private key is generated in keychain can store it for safety.
3.when generating appcast `generate_appcast ` everytime it is creating new `sparkle:edSignature="xxxxxxx"` is this the expected behaviour .

**Comment by kode54** [comment]
Bonus points: How do I export this key for use on multiple machines? Or am I simply expected to run this stupid `generate_keys` tool every single time I reformat my machine, thus breaking my chain of trust?

**Comment by kornelski** [comment]
Latest version has (not yet documented) flags for exporting the keys and using them from command line.

Other than that use Keychain Access app to export and import Sparkle's keychain item.

**Comment by yanone** [comment]
> Latest version has (not yet documented) flags for exporting the keys and using them from command line.

Could you describe how this works? I’m having the same problem as I want to move my app build into AppVeyor and expect that I can’t use the keychain in a fully automated build script.

**Comment by JamaicanRumCream** [comment]
I too would like more information. I can't "export" the key/password from Keychain, but I can copy it to the pasteboard and save it in a text file. So, how would I then use this in the future if I get a new computer or need to start from scratch etc?

**Comment by kode54** [comment]
I would advice storing that text file, if you do that, somewhere encrypted, or somewhere safe. Basically, you need to keep the "comment" and the "password" fields of the password entry. Then you can just generate a new one on another machine and stuff the comment and password fields you saved into that machine.

**Comment by zorgiepoo** [comment]
We have EdDSA migration docs on the website now.

generate_keys has flags for exporting/importing keys now (for a while).

generate_keys has a better --help/documentation page in 2.x
