### ISSUE TITLE
Error -10810

### ISSUE THREAD

**Issue by andymik** [sparkle-project/Sparkle#1366]
Hi,
I changes my Xojo Development to 64bit. In order to work with the 
Sparkle Updater, I downloaded the newest version. 
All messaging works well and I'm able to download the new version.
But the I get an error "Can't open the update program. Error -10810"
I've no Idea what to do. Does anyone ave an Idea what I can change?
Best regards
Andy

**Comment by kornelski** [comment]
This message doesn't seem to come from Sparkle.

Can you provide precise steps that I could follow to reproduce the problem on a brand new Mac?

**Comment by andymik** [comment]
Thanks for your quick reply.
Would it help to send you the appcast.xml?
I'd like to send it by email...Can you send me your email address?

**Comment by kornelski** [comment]
It's very unlikely to be related to the appcast at all.

Can you trace what is generating that message?

Can you search for Sparkle in Console.app?
