### ISSUE TITLE
ui-separation-and-xpc: Sandboxing XPC Services?

### ISSUE THREAD

**Issue by svenemtell** [sparkle-project/Sparkle#1372]
I am building a (mostly) sandboxed, hardened app which has succeeded notarization.

I did not sandbox the XPC Services since I got all kinds of sandboxing violations that seemed hard to fix.
I have two questions:
- Which `Autoupdate` and `Updater.app` is used, the ones inside `Sparkle.framework` or the ones inside `org.sparkle-project.InstallerLauncher.xpc` or all four?
- Is it possible to sandbox the XPC Services (or at least the `Autoupdate` and `Updater.app` inside `org.sparkle-project.InstallerLauncher.xpc`)?

This is what I did if someone's interested:

I started out building the Sparkle.framework and the XPC Services (with Xcode 10 on macOS 10.14.3).
Then I signed the app parts like this:

\# Sign binaries inside Sparkle.framework
codesign --sign "\<identity\>" -v --options runtime --entitlements \<entitlements-file\> My.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate
codesign --deep --sign "\<identity\>" -v --options runtime --entitlements \<entitlements-file\> My.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Updater.app
\# Sign the XPC Services
codesign --deep --sign "\<identity\>" -v --options runtime My.app/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc
codesign --deep --sign "\<identity\>" -v --options runtime My.app/Contents/XPCServices/org.sparkle-project.LauncherConnection.xpc
codesign --deep --sign "\<identity\>" -v --options runtime My.app/Contents/XPCServices/org.sparkle-project.StatusConnection.xpc
\# Sign the rest of the app including the Sparkle.framework (without the binaries that were signed above)
codesign --deep --sign "\<identity\>" -v --options runtime --entitlements \<app-entitlements-file\> My.app

The `app-entitlements-file` contains all kinds of entitlements while the `entitlements-file` looks like this:

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.inherit</key>
    <true/>
</dict>
</plist>

**Comment by zorgiepoo** [comment]
The website docs have been updated regarding XPC Services integration. The XPC Services aren't normally sandboxed except for the downloader one (which is optional). The other ones in theory *might* be sandbox-able with temporary exceptions but in practice nobody is trying this.
