### ISSUE TITLE
NSURLDownload based downloader does not call cleanup

### ISSUE THREAD

**Issue by hofman** [sparkle-project/Sparkle#1374]
SPUDownloaderDeprecated does not call -cleanup when the download finishes successfully. This can lead to serious problems, as the delegate is not released and automatic termination is not re-enabled. Note that unlike session based downloads no separate completion delegate method is called.

**Comment by kornelski** [comment]
Thanks for the report. Could you make a PR with the fix?

**Comment by hofman** [comment]
I haven't worked with git on github before, so I am not sure what to do. The change should be really easy, just a call to `[self cleanup] ` the end of `-[SPUDownloaderDeprecated downloadDidFinish:]`

**Comment by hofman** [comment]
I think I created a PR for this from hofman:Sparkle
