### ISSUE TITLE
ed25519 sources are missing in distribution

### ISSUE THREAD

**Issue by hofman** [sparkle-project/Sparkle#1378]
The content of the ed25519 directory are missing in the source code in the release distributions.

**Comment by lostminds** [comment]
Ran into the same problem, I just tried to download master and make a build to get a hardened runtime sparkle build I can include in my app and get it notarized, and the the build fails reporting some missing files:

/Sparkle-master/ed25519/src/add_scalar.c
/Sparkle-master/ed25519/src/fe.c
/Sparkle-master/ed25519/src/keypair.c
/Sparkle-master/ed25519/src/key_exchange.c
/Sparkle-master/ed25519/src/sc.c
/Sparkle-master/ed25519/src/ge.c
/Sparkle-master/ed25519/src/sign.c

**Comment by kornelski** [comment]
If you've used GitHub's link to download source as a ZIP or TAR, **it's a GitHub's bug we can't fix**. 

GitHub only offers you incomplete source downloads without submodules, we have no way to disable those broken links.

Please use `git clone --recursive https://github.com/sparkle-project/Sparkle` to get the complete source code. 

If you've already cloned without `--recursive`, then run:

```sh
git submodule update --init
```

**Comment by lostminds** [comment]
Ah, thanks, cloning from terminal worked better and the files were no longer missing. However, I was still unable to build a version that had the required hardened runtime to let me submit my app for notorization. So for now I guess I'll just have to wait until there is a new update to Sparkle with hardened runtime enabled from the start.

**Comment by zorgiepoo** [comment]
I removed the submodule on top of 2.x
