### ISSUE TITLE
Could not create delta update 

### ISSUE THREAD

**Issue by evanslify** [sparkle-project/Sparkle#1383]
Hello. We're using Sparkle with our automated delivery process.

It works for full update. However, as Sparkle could generate delta updates, so we put different versions of our app in workspace and call `generate_appcast` on the folder. It will fail and show errors like this:

```
Could not create delta update <file route> (only permissions with modes 0755 and 0644 are supported)" UserInfo={NSLocalizedDescription=Invalid file permissions after-tree on file /Users/<username>/Library/Caches/Sparkle_generate_appcast/<file route> (only permissions with modes 0755 and 0644 are supported)}
```

Folder consists of multiple different versions of `.app` and compressed with `ditto`.
I tried to extract `.app` and check the file in question, and its permission does exactly look like `755` or `644`.

Anywhere I can investigate further into this?

**Comment by kornelski** [comment]
I've removed that check. We shouldn't stop delta updates because of this. The version on master will now ignore unexpected permissions and use 0755 instead.
