### ISSUE TITLE
Build fails, macOS 10.14.4, Xcode 10.2

### ISSUE THREAD

**Issue by sfsam** [sparkle-project/Sparkle#1387]
I've just cloned Sparkle and am trying to build with `make release`.

I get the following output:

```
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/sanjay/Dev/github/Sparkle/sign_update/main.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal x86_64 /Users/sanjay/Dev/github/Sparkle/generate_keys/main.swift
	CompileSwift normal x86_64
(4 failures)
make: *** [release] Error 65
```

I'm on macOS 10.14.4 using Xcode 10.2. I haven't make any changes to the code. I've simply cloned the repository and run `make release`.

Here's a gist of the full build output:
https://gist.github.com/sfsam/0819f56b24a4dd97f153ca5226856c30

**Comment by xocialize** [comment]
Did you find a resolution for this?

**Comment by sfsam** [comment]
I did. My fault. I initially did `git clone` instead of `git clone --recursive`. When I pulled in the submodule it worked fine. Maybe the README should mention it?
