### ISSUE TITLE
Unable to Build Application When try to Build For Notarization

### ISSUE THREAD

**Issue by praveen27Kmr** [sparkle-project/Sparkle#1388]
Hi ,

I am trying Notarize  application With Xcode ,but unable to do with sparkle 1.18.1 version , I have Already Added Code in My "Script Phase"

"
LOCATION="${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"

# By default, use the configured code signing identity for the project/target
IDENTITY="${CODE_SIGN_IDENTITY}"
if [ "$IDENTITY" == "" ]
then
# If a code signing identity is not specified, use ad hoc signing
IDENTITY="-"
fi
codesign --verbose --force --deep -o runtime --sign "$IDENTITY" "$LOCATION/Sparkle.framework/Versions/A/Resources/AutoUpdate.app"
codesign --verbose --force -o runtime --sign "$IDENTITY" "$LOCATION/Sparkle.framework/Versions/A"

"
 

But I am Getting the Error

its happened After Successfully Uploaded for notarization And When Get back the response after processing is Display a Message "Distribution failed"

Log is there:-

"logFormatVersion": 1,
  "jobId": "482f8cbc-5447-4e81-afce-22a",
  "status": "Invalid",
  "statusSummary": "Archive contains critical validation errors",
  "statusCode": 4000,
  "archiveFilename": "MYAPPNAME.zip",
  "uploadDate": "2019-05-29T07:51:21Z",
  "sha256": "ad76875608d6f1e9775d4e017bf684081a69fdb76ec",
  "ticketContents": null,
  "issues": [
    {
      "severity": "error",
      "code": null,
      "path": "MYAPPNAME.zip/MYAPPNAME.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/MacOS/Autoupdate",
      "message": "The contents of the bundle at MYAPPNAME.zip/MYAPPNAME.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/MacOS/Autoupdate could not be extracted.",
      "docUrl": null,
      "architecture": null
    }
  ]

I have also checked Sparkle in content of Application is Also Signed , What can I do that I can able to Do Noterize My Application with current sparkle

**Comment by praveen27Kmr** [comment]
> Hi ,
> 
> I am trying build application and want to submit for Notarization,but unable to do with sparkle what I was previously added, but now if I go for Notarization than I need some extra configuration for Notarization ? or need to change sparkle with updated version

**Comment by OlexandrLynda** [comment]
@praveen27Kmr Hi there, I have the issue with codesigning the Autoupdate.app, could you provide the solution you found or why you closed the issue?

**Comment by OlexandrLynda** [comment]
Have this error: app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/MacOS: bundle format unrecognized, invalid, or unsuitable

**Comment by praveen27Kmr** [comment]
> Have this error: app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/MacOS: bundle format unrecognized, invalid, or unsuitable



> @praveen27Kmr Hi there, I have the issue with codesigning the Autoupdate.app, could you provide the solution you found or why you closed the issue?

Hello OlexandrLynda, I have close issue because my issue is resolved by Apple . They have the issue during notarization process but now that issue resolve by Apple
