### ISSUE TITLE
 I don't know how to configure XPC Service

### ISSUE THREAD

**Issue by 435129214** [sparkle-project/Sparkle#1395]
### Do you use Sandboxing in your app?
YES
### Version of `Sparkle.framework` in the latest version of your app
ui-separation-and-xpc 
### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
N
### Sparkle's output from Console.app
NO
```

```

### Steps to reproduce the behavior
My app is a sandbox program. I downloaded https://github.com/sparkle-project/Sparkle/tree/ui-separation-and-xpc to sign and configure app step by step, but app can not be updated properly. When I checked out the new version of app archive, I clicked on the update and prompted An error occurred while running the updater. Please try again later. I don't know where the problem is. In fact, my main problem is that I don't know how to configure XPC Service. The main project of sparle is too big, and the source code is also in it. Can you spend a few minutes to explain how to create a small demo, especially the one of integrating XPC service? Thank you very much. When I first came into contact with Mac development, I was too big to solve the problem. The non-sandbox app configuration was successful.

**Comment by kornelski** [comment]
It's very odd that Sparkle has shown an error, but didn't log the error to the console. Can you search the console again? If you're running from inside Xcode, it may be in the debug log pane.

**Comment by 435129214** [comment]
If it runs in Xcode, the update will be suspended. I see the instructions on the document also say that the Archive program is necessary. I searched the source code for this error and saw it in the setUpConnection method in the SPUInstallerDriver file. The code is as follows:
_ weak SPUInstallerDriver * weak Self = self;
[self.installer Connection setInvalidation Handler:]^{
Dispatch_async (dispatch_get_main_queue(),,^{
SPUInstallerDriver * strongSelf = weakSelf;
If (strongSelf. installer Connection!= nil & & &! StrongSelf. aborted){
NSError * remoteError=
[NSError
Eror With Domain: SUSparkle Error Domain
Code: SUInstallation Error
UserInfo:@{
NSLocalized Description Key: SU Localized String (@ "An error occurred while running the updater. Please try again later.", nil)
NSLocalized Failure Reason ErrorKey:@ "The remote port connection was invalidated from the updater"
}
];
[StrongSelf.delegate installer IsRequesting Abort Install WithError: remoteError];
}
};
]

I want to repeat my integration steps. Sign Sparkle. frame, XPC services, copy them to the project, set them step by step, without adding a line of code. The final version is released for version upgrade testing. The latest Spakle library, using pod mode, no sandbox app can be quickly integrated and successfully used.

**Comment by 435129214** [comment]
Can the latest sparkle code support sandbox? If you can also use pod
That would be great if you supported it.

**Comment by 435129214** [comment]
If you have time, I would like to ask you to see if my small project is misconfigured. My project address is https://github.com/435129214/sparkleTest. Thank you very much.

**Comment by digitalmoksha** [comment]
@435129214 I'm not an expert,  but maybe this helps a little:  https://github.com/sparkle-project/Sparkle/issues/363#issuecomment-401559017

> My build process is quite different than most (RubyMotion), but at the end of the day, you need the `.xpc` services in the `XPCServices` folder:
>
> ```
> MyApp.app
>    Contents
>      ...
>      Frameworks
>         ...
>         Sparkle.framework
>      XPCServices
>         org.sparkle-project.InstallerConnection.xpc
>         org.sparkle-project.InstallerLauncher.xpc
>         org.sparkle-project.InstallerStatus.xpc
>  ```

You also need to make sure you're `XPC` services are signed - I usually use the `--deep` flag to ensure that they are all signed.

**Comment by 435129214** [comment]
@digitalmoksha Thank you very much for your reply. I checked the app file you said, the structure is the same as what you said. Both frameworks and XPC are correct. As for code sign, I use Sparkle tools to sign in advance and then add to the project. I have tried that if the integration is not signed, the compilation will not be successful. Only the XPC files that have been signed can be compiled successfully. If you have time to see my demo, it's best. I really don't know what the problem is.

**Comment by 435129214** [comment]
@kornelski I have already answered your question above. I need more help from you. Thank you.

**Comment by igillespie** [comment]
I seem to running into this exact same problem. I have verified that the XPC services are signed and my app is being notarized successfully by Apple before I zip it up, then use the generate_appcast tool to make the appcast file. When I try to do an update (making sure to launch deployment build from /Applications) the process fails with the same error message, "An error occurred while running the updater. Please try again later." which is traced back to the same line of code the author of this post mentioned.

@435129214, did you ever get this working?

**Comment by lvandal** [comment]
Same here. Console logs not very helpful either:

> Oct 23 08:05:27 iMac-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): com.acme.MyApp-sparkle-updater (lint): Assuming EnablePressuredExit=false given EnableTransactions=false.
Oct 23 08:05:27 iMac-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): com.acme.MyApp-sparkle-progress (lint): Assuming EnablePressuredExit=false given EnableTransactions=false.
Oct 23 08:05:28 iMac-Pro com.apple.xpc.launchd[1] (com.acme.MyApp-sparkle-updater[8479]): Service exited with abnormal code: 1
Oct 23 08:05:28 iMac-Pro com.apple.xpc.launchd[1] (com.acme.MyApp-sparkle-progress[8481]): Service exited with abnormal code: 1

**Comment by danielpunkass** [comment]
I think these issues probably have something to do with code signing. You'll need to double, triple check that all the XPC services are being signed by the same identity as the container app. I have also run into them a lot when I tried to get XPC/Sparkle working but I can't remember any specific details except to continue making sure signing is right.

**Comment by samdeane** [comment]
I am seeing the same error, and I also suspect that it's code-signing related.

The weird thing for me is that it was working, and I don't believe that I've changed anything. Furthermore, it seems as though previously working binaries (zipped archives of old versions of my app) are no longer working. I am confident that these used to work (though I can't prove it right now without rolling back my system).

I am wondering if there has been a subtle security change recently (eg in 10.15.4 - which is what I'm testing against), which could have caused some security validation that was previously working to now fail when launching the xpc.

**Comment by zygoat** [comment]
I'm having this same problem, building from 2.x 08a7122 on 10.15.7. It simply fails after downloading the update. I've made certain that everything (the host app, the Sparkle.framework, the XPC services) are all codesigned identically. I'm at a loss.

**Comment by zorgiepoo** [comment]
Can you also check https://sparkle-project.org/documentation/sandboxing/ (also under "Testing") to see if you're running into issue where XPC services can't be debugged in the debugger? (I intend to make this specific error more obvious..)

**Comment by zygoat** [comment]
@zorgiepoo: thanks for the tip. I didn't have any EdDSA setup going on at that point, and when I found Autoupdate's messages in Console, I realized that seemed to be the problem. I set up EdDSA, and then… it all worked! Woohoo.

Nonetheless, my understanding from the docs was that the absence of EdDSA should be tolerated provided that both apps were signed the same. (Maybe I had screwed up and the signing was not in fact identical?)

The log messages emitted by the host app don't indicate the Autoupdate failure, and only proclaim that the XPC connection died. That sent me down a false path on trying to diagnose XPC problems.

**Comment by zorgiepoo** [comment]
> Nonetheless, my understanding from the docs was that the absence of EdDSA should be tolerated provided that both apps were signed the same. (Maybe I had screwed up and the signing was not in fact identical?)

It should but EdDSA support was tacked on later and not using Ed(DSA) keys emits a deprecation warning, so I haven't looked at that path in a while. I should take a second look at it though. It may not work if you are using ad-hoc signatures for development.

Yeah Autoupdate should probably be renamed to sparkle-installer or something more obvious at least, and we should look into better error reporting.

**Comment by zorgiepoo** [comment]
Lots have changed here in terms of documentation and error logging.
