### ISSUE TITLE
XCode "Distribution" build scheme builds debug build instead of release

### ISSUE THREAD

**Issue by lostminds** [sparkle-project/Sparkle#1397]
I cloned the repository to build sparkle on my own (to get a hardened runtime build for notorization support) the included readme mentions you can build the distribution package from XCode with the Distribution scheme in the Xcode UI. However, when I tried it it builds a debug version and not the release version. So if you use it in your project you get a warning not to use it. In the end I had to build from the command line with "make release" to get the release version I could use.

Not sure if this is something that can be fixed by setting up the target differently in XCode or if it's just a matter of changing the readme to just say you need to build from the command line.

**Comment by zorgiepoo** [comment]
It is set using Release configuration.
