### ISSUE TITLE
State of the `ui-separation-and-xpc` branch: CocoaPods and EdDSA support?

### ISSUE THREAD

**Issue by MrMage** [sparkle-project/Sparkle#1398]
I am thinking of migrating to the `ui-separation-and-xpc` branch in order to allow my helper app to update the main app. However, I am currently using CocoaPods.

1. Is it possible to use the  `ui-separation-and-xpc` branch with CocoaPods already, given that there are no binary releases yet for the new branch AFAICT?
2. If CocoaPods is not yet supported, what is the recommended process for updating the Sparkle framework? Simply pull new commits and run `make release` from time to time? (I have ready https://github.com/sparkle-project/Sparkle/blob/ui-separation-and-xpc/INSTALL.markdown.)
3. Does the  `ui-separation-and-xpc` branch support EdDSA yet? If not, is there a timeline for that?

**Comment by MrMage** [comment]
@kornelski do you have any insights into these questions? I'm trying to determine whether switching to the `ui-separation-and-xpc` branch is a viable option already.

**Comment by kornelski** [comment]
Sorry, I have little time to maintain it. 

I currently don't have any plans to publish it as a CocoaPod.

It needs to support EdDSA. That's on my todo list. Perhaps someone can help porting the code to get it done sooner?

**Comment by MrMage** [comment]
Thank you for the reply! I will go ahead with using that branch without CocoaPods, then. EdDSA support is much less urgent to me.

**Comment by zorgiepoo** [comment]
There are swift package manager / cocoa pods pre-releases now for 2.x
