### ISSUE TITLE
Testing for Hardware configuration?

### ISSUE THREAD

**Issue by patrickcusack** [sparkle-project/Sparkle#1399]
I currently use the Sparkle.Framework and would like to know how to best handle a hardware condition test. I can test for a minimum version in my app cast, but I need to now check for hardware that supports Metal. The following delegate method makes sense:

- (nullable SUAppcastItem *)bestValidUpdateInAppcast:(SUAppcast *)appcast forUpdater:(SUUpdater *)updater;

But, looking at the code (SUBasicUpdateDriver.m), if I return nil, then Sparkle will choose the best item. How have others handled this?

**Comment by zorgiepoo** [comment]
> But, looking at the code (SUBasicUpdateDriver.m), if I return nil, then Sparkle will choose the best item. How have others handled this?

Pick the "worst" item, which Sparkle will ignore if it's less than the current app version.

I can't think of a better approach for if a developer runs into this sort of situation, but this also highlights a potential issue with this API. This scenario would also require needing enough preparation baked into already shipped releases.

(Two feeds does work too of course).
