### ISSUE TITLE
Autoupdate app hangs after download of .pkg

### ISSUE THREAD

**Issue by Jazeido** [sparkle-project/Sparkle#1400]
I'm trying to deploy an update which requires a .pkg installer with Sparkle 1.21.3 on Mojave. The download finishes and the .pkg ends up in ~/Library/Caches/.../org.sparkle-project.Sparkle/... The Autoupdate app launches and asks for an admin password (I don't know why this is necessary but it's okay with me). After authorization the Autoupdater freezes (shows "Installing update…" with empty progress bar). Apparently the downloaded .pkg is okay (works correctly when opened from Finder).

There seems to be no relevant output from Autoupdate on the Console. No output in ~/Library/Logs/SparkleUpdateLog.log either.

I did the same on a second machine using High Sierra with identical results.

I tried to build a debug version of Sparkle, but the build fails with this error:

`error: Build input file cannot be found: '.../Sparkle-1.21.3/ed25519/src/keypair.c'`

Does anyone have an advice how to proceed? It is extremely important to get this resolved. Thanks.

**Comment by kornelski** [comment]
You can't build Sparkle from zip/tar that GitHub offers. That's a GitHub bug.

You have to clone Sparkle's source code with `--recursive` flag or run `git submodule init`.

**Comment by pparekh7** [comment]
I am seeing the same issue on Mojave 10.14.6 consistently but not seeing it on Catalina (10.15.6). I have not tested on MacOS older than Mojave.

It appears the fileop never finishes running leaving autoupdate waiting for it to complete. The app however does get updated so it looks like the installer ran but there was no feedback that it finished?

Is anyone else seeing this?

**Comment by pparekh7** [comment]
I started a new issue because I didn't know if this one was the same. #1650

**Comment by zorgiepoo** [comment]
If there's still issues, retry with Sparkle 2. Auth model in sparkle 1 is fragile.
