### ISSUE TITLE
Running sparkle in the debugger

### ISSUE THREAD

**Issue by antoineazar** [sparkle-project/Sparkle#1401]
We've written a bit of a funky Sparkle implementation, where we manually run fully silent checks and updates in the background for an app that looks more like a service. It's also a cross-platform app, so we're trying to fit Sparkle's model in the defined interfaces for the update classes.

Is it possible to run the code and test the update in the debugger? I'm guessing that because the app is not signed, Sparkle will always return the "ALERT: Insecure update error!" error. Issue is that when I produce a signed app, the update doesn't work, so i know there's a bug somewhere in the code. How should I go about this?

**Comment by kornelski** [comment]
When something is wrong with signing, you should always get a precise explanation of what is wrong in the console (either Xcode's debug console, or Console.app).

AFAIK Xcode does code-sign debug builds. We have [test app](https://github.com/sparkle-project/Sparkle/tree/master/TestApplication) that works in debug (we do a bit of gymnastics to get appcast generated on the fly, but you don't need that in a real app).
