### ISSUE TITLE
Update alert delegate? SUUpdateAlertDelegate

### ISSUE THREAD

**Issue by aonez** [sparkle-project/Sparkle#1404]
I'm just looking for a way to know if the Update Alert has splashed and the result of that alert so [I can quit the host application only if this alert is not shown](https://github.com/aonez/Keka/issues/408). I'm seeing the protocol [`SUUpdateAlertDelegate`](https://github.com/sparkle-project/Sparkle/blob/b42642690535a43f459511e175716d5ad17fc5b8/Sparkle/SUUpdateAlert.h#L15) but seems it's not in use. There's any API for that? Should it be done?

If the install button is pressed all download/installation methods in `SPUUpdaterDelegate` are called after the alert has closed, so I can't safely determine if the update started before detecting the alert closed.

Thanks in advance!

**Comment by zorgiepoo** [comment]
I wasn't able to reproduce the linked issue recently when I was trying to implement applicationShouldTerminateAfterLastWindowClosed:

in the case that is still an issue, `SPUStandardUserDriverDelegate` has appropriate methods now, i.e, `-standardUserDriverWillHandleShowingUpdate:forUpdate:state:` and `-standardUserDriverWillFinishUpdateSession`
