### ISSUE TITLE
Any way to customize download directory path?

### ISSUE THREAD

**Issue by AnuragS149** [sparkle-project/Sparkle#1406]
By default Sparkle framework use bundle identifier for creating a path for downloading the new <Product name>.app binary while upgrading to new version. Like "~/Library/Caches/<Bundle Identifier>/Sparkle/<Product folder>" 
Currently we are using Sparkle version 1.14.0

Is there any way to customize the download directory path to which Sparkle will download the new binary <Product name>.app rather than using bundle identifier path?

**Comment by kornelski** [comment]
No, we don't support such customization.
