### ISSUE TITLE
Endless "Installing update"

### ISSUE THREAD

**Issue by mediym41** [sparkle-project/Sparkle#1407]
Is sparkle works for SanboxApp? When i use without sandbox, it works and vice versa

**Comment by kornelski** [comment]
Sparkle 1.x doesn't work with sandboxed apps.

There's an experimental Sparkle 2.x branch for sandboxed apps.

**Comment by mediym41** [comment]
Is Sparkle 2.x available now?

**Comment by mediym41** [comment]
Can not find this branch. Is it available now?

**Comment by michelf** [comment]
It's the [ui-separation-and-xpc](https://github.com/sparkle-project/Sparkle/tree/ui-separation-and-xpc) branch.
