### ISSUE TITLE
Wait for app termination if multiple instances of the process are running

### ISSUE THREAD

**Issue by antoineazar** [sparkle-project/Sparkle#1408]
Our app spawns another instance of its own process, so we have at all times two processes running of the same executable. One of these processes will check for updates and invoke the update process. Our second process is configured to listen to the first process exiting, and exiting as well. This can take a few seconds.

How will Sparkle behave in this scenario? Will it see that we have another identical process running and wait for it to exit as well? Will it just wait for its own process to quit and attempt the update, potentially failing because there's another process running?

**Comment by kornelski** [comment]
Sparkle waits only for its own process. You could implement delegate which is notified just before the restart, and try to stop the other process then.

**Comment by antoineazar** [comment]
Thanks for the reply! Would you know if it would break the update if the other process is still running while the update happens?

**Comment by kornelski** [comment]
Replacing of a bundle of a running process can cause it to crash (Cocoa may reload resources in the bundle and not take it well when they're suddenly missing or changed).

**Comment by antoineazar** [comment]
Got it. Alternatively, is there any way to download the update in one process, exit the process, and have the second process pick up the downloaded update and install it? From what I see in the source code, the entire download folder is wiped before every update attempt.

**Comment by kornelski** [comment]
We do this cross-process dance already with the Autoupdate.app, but it's Sparkle's implementation detail and not exposed to the host app.

**Comment by zorgiepoo** [comment]
We send termination requests to all matching running instances but only observe one of them for waiting when they get killed. Normally applications should only have one instance of their app running which is what I think should be supported.
