### ISSUE TITLE
Sparkle does not work as expected in long-running apps & background apps

### ISSUE THREAD

**Issue by core-code** [sparkle-project/Sparkle#1414]
over the past years there have been many claims that Sparkle does not work properly in long-running apps and background apps that are launched just once, but there has never been a definitive confirmation of any issue.

i believe i can confirm that there is a bug, and can also explain the cause and offer a solution here.

the way Sparkle works is this: if it is initialised (normally at app launch), it checks if the last check has been longer ago than the "checking interval". if thats the case, it checks for updates immediately, which works fine. this is the case that is important for normal apps that are launched on-demand. however, in the other case it schedules a timer, so that the update check is done at the right moment. this is the important case for all long-running apps as its unlikely to find an update at launch, and finding updates 'while running' should also work.

scheduling a timer is done like this in Sparkle/Sparkle/SUUpdater.m

`    self.checkTimer = [NSTimer scheduledTimerWithTimeInterval:delayUntilCheck target:self selector:@selector(checkForUpdatesInBackground) userInfo:nil repeats:NO]; // Timer is non-repeating, may have invalidated itself, so we had to retain it.
`

however, this only works perfectly if the Mac never goes to sleep! 
as is commonly known and has been documented often, NSTimer does only work properly for long running timers if the Mac never goes to sleep [1]. if the Mac sleeps, the fire date is delayed for the 'amount of sleep'. in concrete terms this means, if your app has been configured to check for updates every 5 days, but the Mac sleeps 66% of the time, the update check will actually only be performed every 15 days. if your updates are quite important this can lead to a big problem as updates aren't delivered to users in a timely manner, especially on Macs that are only used a few hours per day or week.

the normal way to fix NSTimer behaviour for long-running timers despite the 'sleep problem' is to rebuild timers after sleep, e.g. by observing 'NSWorkspaceDidWakeNotification' [2]. we have used a special timer class for this for years [3].

[1]
https://www.noodlesoft.com/blog/2010/07/01/playing-with-nstimer/
https://stackoverflow.com/a/16597866/1259710
https://forums.developer.apple.com/thread/106199
http://openradar.appspot.com/13760797

[2]
technically, NSTimers are /also/ broken if the system clock is changed, which can be observed with 'NSSystemClockDidChangeNotification'. however since this is far less common than a Mac sleeping, i won't go into this here

[3]
https://github.com/core-code/CoreLib/blob/master/Mac/JMCorrectTimer.m

**Comment by Wevah** [comment]
It might be worth looking into `NSBackgroundActivityScheduler`.

**Comment by kornelski** [comment]
That's a nice find.

However, I'm not sure if it's bad enough to warrant workarounds. Long-running apps that depend on timely updates can overcompensate by using a short interval. We could add a warning in the docs.

**Comment by core-code** [comment]
hm.  some Macs sleep never, some Macs sleep 90% of the time. compensating by a constant factor is bound to be wrong everywhere, sometimes by a lot. if you don't talk about your update-check interval, this might still be 'ok', but in our case this is directly selectable by the user. and i don't want to give users a selectable option, only to 'not obey it'.

our workaround currently is to perform the check every time the main window of the app is opened - if Sparkle didn't do it due to sleep time:

```

if (@"SUEnableAutomaticChecks".defaultInt)
	NSDate *sparkleCheckDate = @"SULastCheckTime".defaultObject;
	if (sparkleCheckDate && [sparkleCheckDate isKindOfClass:NSDate.class] && [NSDate.date timeIntervalSinceDate:sparkleCheckDate] > @"SUScheduledCheckInterval".defaultInt)
		[updater checkForUpdates];

```

i agree that code bases should not be littered and complicated to handle very obscure situations, but i still believe this should be fixed:
1.) Sparkle is already more than 10kloc
2.) a fix for this is probably less than 10 lines
3.) while it affects only a small minority of apps (those that are never re-launched), it is actually a quite bad bug there, that significantly impacts the core functionality "check for updates".

i'd be willing to work on this and send a PR to fix this in the next few weeks.

**Comment by core-code** [comment]
i think this should do it 
[sleep.patch.txt](https://github.com/sparkle-project/Sparkle/files/3340123/sleep.patch.txt)

**Comment by core-code** [comment]
should i send the patch as a PR instead?

**Comment by kornelski** [comment]
Yes, please
