### ISSUE TITLE
sparkle:version issue

### ISSUE THREAD

**Issue by alexkartsev-classpass** [sparkle-project/Sparkle#1415]
### Description of the problem
```
<item>
<title>2.1.2</title>
<enclosure url="https://arcraftimages.s3.us-east-2.amazonaws.com/MakeML/MakeML_2.1.2.dmg" sparkle:version="2" sparkle:shortVersionString="2.1.2" length="29982596" type="application/octet-stream"/>
<sparkle:deltas>
<enclosure url="https://arcraftimages.s3.us-east-2.amazonaws.com/MakeML/MakeML2-1.delta" sparkle:version="2" sparkle:shortVersionString="2.1.2" sparkle:deltaFrom="1" length="156919" type="application/octet-stream"/></sparkle:deltas>
</item>

<item>
<title>2.1.3</title>
<enclosure url="https://arcraftimages.s3.us-east-2.amazonaws.com/MakeML/MakeML_2.1.3.dmg" sparkle:version="1" sparkle:shortVersionString="2.1.3" length="29638532" type="application/octet-stream" />
</item>
```

CFBundleVersion for 2.1.2 version is 2
CFBundleVersion for 2.1.3 version is 8
I use ./bin/generate_appcast for generating app cast.xml

Why sparkle:version for 2.1.2 is 2, and for 2.1.3 is 1?
When I check updates in 2.1.3, Sparkle suggest to update to 2.1.2.
Could you please help with this issue?

### Do you use Sandboxing in your app?
NO
### Version of `Sparkle.framework` in the latest version of your app
1.21.3

**Comment by zorgiepoo** [comment]
Possibly generate appcast had cached unarchived copy in ~/Library/Caches/Sparkle_generate_appcast and 2.1.3 was updated after the fact again.
