### ISSUE TITLE
Atomic updates behavior

### ISSUE THREAD

**Issue by antoineazar** [sparkle-project/Sparkle#1416]
What logic does Sparkle follow to actually update an app? Does it install the new app, then uninstall the previous one? Does it uninstall the previous one then install the new one? Or overwrite existing files?

If the power cord is pulled from the computer while Sparkle is updating, what's the expected outcome?

Thanks!

**Comment by kornelski** [comment]
It creates a new directory and then swaps it with the old one. It's as close to atomic as we can get.

**Comment by michelf** [comment]
You can atomic-swap directories on APFS, using `renameatx_np`. And NSFileManager's `replaceItemAtURL` will try that first if [the open-source version](https://github.com/apple/swift-corelibs-foundation/blob/75fa8e0a0f4dd6d6570cfa51cd6d0901870c9162/Foundation/FileManager%2BPOSIX.swift#L1225) has any similarity with the one that ships with macOS.

Is there a reason not to use that?

**Comment by antoineazar** [comment]
thank you @kornelski !

**Comment by zorgiepoo** [comment]
Keeping in case we ever adopt NSFileManager or APFS rename API for atomic-directory swap. Currently Sparkle can end up in a situation where neither old or new app is present in the destination, although this ought to be very rare.

One problem of changing the file operations code is the test matrix: OS version X local mount X secondary mount X SMB x AFP mounts X USB drives.

**Comment by kornelski** [comment]
We're currently using `URLForDirectory:NSItemReplacementDirectory inDomain:NSUserDomainMask appropriateForURL:directoryURL`, so hopefully it should be possible to swap most of the time, right?

**Comment by zorgiepoo** [comment]
We are but we also need to use the companion API `replaceItemAtURL:withItemAtURL:backupItemName:options:resultingItemURL:error:` which boils down to `if (volume_is_apfs_and_can_atomic_directory_replace) { /* do atomic-safe apfs directory replacement */ } else { /* remove old app directory, move new app in its place */ }`. Or we could manually call out the apfs API and capability check ourselves which might be less risky. Note it's a directory replacement, not a swap, which is partly why I removed the code that moved the old app to the trash so long ago ;).
