### ISSUE TITLE
Update podspec file to 1.22.0

### ISSUE THREAD

**Issue by antoineazar** [sparkle-project/Sparkle#1417]
Hey guys, someone should update the podspec file to 1.22.0 :-) Would send a PR myself but won't be able to until next week at the latest.

**Comment by DivineDominion** [comment]
At the moment only 1.21.x is part of the GitHub releases, or am I missing something?

**Comment by rbugajewski** [comment]
@DivineDominion Yes, that’s true.

Is there an official release schedule for 1.22.0 though? For us it’s quite important, because of the fix for the timer drifting issue in previous versions. Please let me know if I can help.
