### ISSUE TITLE
Updated keys

### ISSUE THREAD

**Issue by mentalmushroom** [sparkle-project/Sparkle#1424]
I've been using Sparkle for quite a long time. In this period signing tools and security requirements have changed many times. So I have a couple of questions:

1. The current version of Sparkle doesn't allow me to use previously generated key pair stored in .pem files. I was asked to run generate_keys first. But that means I can't use the old keys whereas the documentation warns not to lose the private key. So I am wondering what should I do in this case?

2. After running generate_keys the key was added to the keychain, but I can't find it. When I run generate_keys again, it finds the key in the keychain and prints the public key as expected. But what if I need to sign the update from another machine? Or if I reinstall the OS? Am I supposed to run generate_keys on those machines or do I need to transfer the key from the first machine where generate_keys was run?

**Comment by kornelski** [comment]
The current version of Sparkle still allows you to use the old .pem key. The old tools for this have been moved to another directory.

1. You got this message from a new signing tool that supports *both* new and old keys, and wants you to generate a new key, so that you can migrate from the old to the new.

2. Search for Sparkle in the keychain. The tool has store the key as "application-specific password" kind, because macOS natively supports only older key formats like RSA.

**Comment by mentalmushroom** [comment]
I guess you mean old_dsa_scripts folder? Are these scripts used for DSA or EdDSA signatures? I have already updated DSA to EdDSA in my last update. So would it be the recommended to use the old or the new tools in this case?

> You got this message from a new signing tool that supports both new and old keys, and wants you to generate a new key, so that you can migrate from the old to the new.

Could you elaborate on how to use the new signing tools with the old keys? For instance, I've got a test.dmg and the dsa_priv.pem file (EdDSA generated by signing tools from Sparkle v1.20). When I try to sign the dmg with my old key I get the following:
`./sign_update test.dmg dsa_priv.pem 
Usage: ./sign_update <archive to sign>
Privavte EdDSA (ed25519) key is automatically read from the Keychain.`
So it looks like the new signing script doesn't even let me specify the old key as an argument.

**Comment by kornelski** [comment]
Sorry, I forgot that `sign_update` didn't take the old DSA key as an argument. I updated `generate_appcast` to support both old and new DSA at the same time, and forgot to do the same for the new `sign_update. That's an oversight. `sign_update` should be accepting the old DSA key, too.

**Comment by mentalmushroom** [comment]
Ok, I hope it will be fixed in the next version.

**Comment by xp-xp-xp** [comment]
So what if I want to change another machine to package my app， what should I do about the private key chain?

**Comment by kornelski** [comment]
Keychain Access app allows you to create new keychain files, copy items there (search for Sparkle), and copy the keychain file over to a new machine.
