### ISSUE TITLE
[ui-separation-and-xpc] XPC Services not closed?

### ISSUE THREAD

**Issue by DivineDominion** [sparkle-project/Sparkle#1426]
I am switching to the XPC branch. I lowered my app's version temporarily to check if the XPC services are launched and pick up the update feed's info. This works 👍

However, the XPC services are never invalidated/closed. After fetching the feed, both the "Downloader" and "InstallerStatus" services keep on running for about 15mins now.

I don't have much real-world experience with handling XPC services, so I wonder if this is the expected behavior. Wouldn't it make sense to shut the services down that do not periodically check for updates, like the "Downloader" (if I understand its purpose correctly)?

![XPC Services keep on running](https://user-images.githubusercontent.com/59080/60160651-1913fc80-97f6-11e9-8576-817dcab3adc2.png)

**Comment by kornelski** [comment]
Yes, shutting them down seems sensible.

**Comment by DivineDominion** [comment]
I'm not yet very familiar with the new code base and find navigating around a bit tricky at times (my mental model doesn't yet match the project group structure :)) -- is there a place/type this would fit easily (aka I could give it a shot), or would we have to change a lot of the architecture?

**Comment by kornelski** [comment]
I'm not sure myself.

**Comment by zorgiepoo** [comment]
XPC services are left idly running unless the OS decides it needs to close them. If requests need to be made again it's more efficient for them to be left open.

`sudo memory_pressure -S -l critical`

Simulates critical memory pressure to the system and if the services aren't being used (no outstanding reply blocks, and automatic termination isn't disabled (-[NSProcessInfo disableAutomaticTermination:]), they should be terminated, in theory.
