### ISSUE TITLE
Feature request: Sparkle update service to update multiple apps at once

### ISSUE THREAD

**Issue by houchin** [sparkle-project/Sparkle#143]
Hi Andy,

As an end user of many Sparkle using apps, I thank you very much for developing this solution, as by making it easier for developers to produce self-updating applications, it makes my life easier in keeping my Macs up to date.

I would like to propose one feature: It would be great if either an Sparkle application or the end user could install a tool to update all the Sparkle apps on a system at once, without having to start each application and let it check for updates.

For some apps, this might seem unimportant, as if it is infrequently used, it would just update the next time I run it. However, in some cases, it's at that time when really need that app that I am least likely to want to go through the update process.

In my case, I have both a Mac Pro and MacBook Pro at work. For most of the time, the MacBook Pro is just used as a file server; it's on the network and booted, but I'm not logged in. I mount my documents folder from the Mac Pro so that I don't have any file syncing issues when I go mobile. So I tend to have a lot of outdated apps on that system.

Anyway, something to think about it.

**Comment by marcheimendinger** [comment]
I just had the same idea. Any news on this?

A small Sparkle utility with notificaitons and mimicking the Mac App Store updates tab for all apps using Sparkle would be something very useful.

**Comment by kornelski** [comment]
It won't happen until someone writes it :)

**Comment by zorgiepoo** [comment]
#2090
