### ISSUE TITLE
Do we allowed to edit or add translations text for upgrade alert in our app which are not done by Sparkle?

### ISSUE THREAD

**Issue by AnuragS149** [sparkle-project/Sparkle#1434]
**Do we allowed to edit or add translations text for upgrade alert in our app which are not done by Sparkle?**

Please update me on above query as we have urgency on this.

Here are the list of strings which are not translated in sparkle 1.21.3 :
1. https://github.com/sparkle-project/Sparkle/blob/1.21.3/Sparkle/cs.lproj/Sparkle.strings
    a. "Learn More..."

2. https://github.com/sparkle-project/Sparkle/blob/1.21.3/Sparkle/da.lproj/Sparkle.strings
    a. "%@ %@ is now available--you have %@. Would you like to learn more about this update on the web?"

3. https://github.com/sparkle-project/Sparkle/blob/1.21.3/Sparkle/el.lproj/Sparkle.strings
    a. "%@ %@ is now available--you have %@. Would you like to learn more about this update on the web?"
    b. "Learn More..."

4. https://github.com/sparkle-project/Sparkle/blob/1.21.3/Sparkle/fi.lproj/Sparkle.strings
    a. "%@ %@ is now available--you have %@. Would you like to learn more about this update on the web?"
    b. “Skip This Version”
    c. “Remind Me Later”
    d. “Learn More…”

5. https://github.com/sparkle-project/Sparkle/blob/1.21.3/Sparkle/it.lproj/Sparkle.strings
    a. "%@ %@ is now available--you have %@. Would you like to learn more about this update on the web?"

**Comment by kornelski** [comment]
If you have translations for the missing strings, please make pull requests.

**Comment by AnuragS149** [comment]
Sure... I will make pull request for above.
Actually we have release in next few days and i believe till that time Sparkle will not be releasing any new version which have above changes.
**is it allowed to do above changes by us in our product directly?** 
We will release our product with these changes and later when these changes available in upcoming Sparkle release, then we will use latest Sparkle version.
Please let me know your thoughts on this.

**Comment by kornelski** [comment]
You can make any changes you want, and compile Sparkle yourself.
