### ISSUE TITLE
Podspec doesn't work

### ISSUE THREAD

**Issue by evanwalsh** [sparkle-project/Sparkle#1438]
Hello! I'm trying to use the repo's `Sparkle.podspec` and it doesn't work because it tries to download the source using the spec's version ([see line 22](https://github.com/sparkle-project/Sparkle/blob/f8971098be2034a5a0577a0ce634090f6ecf16ee/Sparkle.podspec#L22)).

The GitHub release for 1.22.0 doesn't currently exist (only one for 1.22.0rc1). Is 1.22.0 officially released? If so, a tag for it should be made. Otherwise, the podspec should probably be updated. Let me know and I'll help by making any necessary PRs! Thanks for your hard work on Sparkle ❤️

**Comment by kornelski** [comment]
1.22.0 is not released yet, there's only the RC version.

**Comment by yichengchen** [comment]
> 1.22.0 is not released yet, there's only the RC version.

seems 1.22.0 is released but not push to cocopods yet, when will can we push it?

**Comment by kornelski** [comment]
Hmmm, I thought I pushed it :(

**Comment by kornelski** [comment]
Should be pushed now
