### ISSUE TITLE
Document command line options to generate_appcast

### ISSUE THREAD

**Issue by bdenckla-ua** [sparkle-project/Sparkle#1446]
AFAICT, command-line options for generate_appcast are only "documented" in the source.

For example I was interested to infer, from the sources, the following syntax:
> generate_appcast -s _private_key_ _updates_dir_

But wish I had found it earlier in the docs, without needing to discover/infer it.

It would be great to document these command line features in a place that is external to the source.

Perhaps they are already and I just couldn't find the docs?

**Comment by zorgiepoo** [comment]
2.x re-wrote the argument parsing recently, documenting the command line options in the --help page.
