### ISSUE TITLE
Generate Appcast seems to use SUFeedURL for the appcast file name

### ISSUE THREAD

**Issue by Neoster** [sparkle-project/Sparkle#1450]
I am currently encountering some behaviour of which I am not sure this is expected.

In our app we want to send system profiling data along with the update request, so we did set our SUFeedURL to https://update.someserver.nl/update.php
In our update.php we filter out the profiling data and forward to appcast.xml.
We did test this and so far this is functioning correct.

Now, when the .app is zipped and generate_appcast is ran, the script generates a file called update.php instead of appcast.xml. The generated file's content is a correct appcast xml. If I rename the file to appcast.xml and upload the file to the correct location, all is fine.

Is this behaviour intended? Can I somehow set the preferred output appcast file name?

**Comment by kornelski** [comment]
It uses `SUFeedURL` for the file name indeed. It assumes it's a static file and wants to generate directory ready for upload as-is. PHP is an unfortunate exception to this. 

It'd make sense to reset name to appcast.xml if the extension is php. Would you like to make a PR for this?

**Comment by Neoster** [comment]
Sure, will look into it

**Comment by Neoster** [comment]
This is my first open source project I am about to contribute to.
I did clone the Sparkle repo using GitHub Desktop.
Did create a new branch, but before I can make a PR, I have to publish the branch but I am not allowed to. What is the correct way to create a PR for the Sparkle Repo?
@kornelski

**Comment by kornelski** [comment]
Use Fork option in Github

```sh
git remote add my <ssh url of your fork>
git push my <name of the branch>
```

BTW, you may also need to run 

    git submodule update --init --recursive

in case git didn't clone all of the source.

**Comment by zorgiepoo** [comment]
This was done at some point.
