### ISSUE TITLE
Sparkle-1.22.0rc1 XPC Services

### ISSUE THREAD

**Issue by garethwatsonuk** [sparkle-project/Sparkle#1452]
Hello,

I am new to Sparkle and Git, so please excuse if this is obvious.  I have downloaded the 1.22.0rc1 source and ran make release, but I do not get any XPC files.  I also notice in the download assets (Sparkle-1.22.0rc1.tar.bz2) of the release section this has no XPC files.

Have I missed something as I cannot  get these from following the install instructions

**Comment by kornelski** [comment]
Version 1.x does not support XPC. You have to clone `ui-separation-and-xpc` branch instead.

**Comment by igwatson** [comment]
@kornelski Thanks, I now see what I have done!  

Am I correct in thinking that ui-separation-and-xpc branch does not used EdDSA (ed25519), as it has only been merged to 1.20.0?

**Comment by kornelski** [comment]
Correct. There's still work to do on the XPC branch.

**Comment by kornelski** [comment]
https://github.com/sparkle-project/Sparkle/pull/1423

**Comment by zorgiepoo** [comment]
In 2.x branch now.
