### ISSUE TITLE
No way to manually sign EdDSA binary

### ISSUE THREAD

**Issue by chockenberry** [sparkle-project/Sparkle#1453]
We currently have a series of scripts that prepare a release for distribution. One script is responsible for generating the appcast from notarized binaries. It looks like this:

```sh
SIGNATURE=$(/usr/bin/openssl dgst -sha1 -binary < "$ARCHIVE_UPLOAD" | openssl dgst -dss1 -sign /tmp/sparkle.key | openssl enc -base64)
```

After SIGNATURE is written to the `sparkle:dsaSignature` attribute in the output XML, the temporary key file is removed.

I'm currently using 1.22.0rc1 and `generate_appcast` doesn't work for this scenario:

1. It assumes that the private key is in the keychain. This either ties the build to one machine or make is difficult/insecure to exchange a private key.
2. It assumes that the archive and the appcast are in the same place. Ours are on separate servers with separate version control repositories (hence these scripts.)

Ideally, there would be some way to sign these builds with EdDSA without needing `ed25519_sign()` library function.

**Comment by kornelski** [comment]
[`sign_update`](https://github.com/sparkle-project/Sparkle/blob/master/sign_update/main.swift) is supposed to do this. 

Keychain dependence is indeed a problem, see: #1447

**Comment by chockenberry** [comment]
On Catalina with the binary in the 1.22.0rc1 distribution:

![Screen Shot 2019-08-12 at 4 27 39 PM](https://user-images.githubusercontent.com/254585/62905198-43763680-bd1e-11e9-95cc-9021da6c4eeb.png)

**Comment by kornelski** [comment]
No, it's just code-signing or notarization being annoying as usual. Try compiling it yourself.

**Comment by chockenberry** [comment]
Why does `generate_keys` and `generate_appcast` work OK then?

**Comment by kornelski** [comment]
I don't know. I don't see any significant differences in their build config or the release script.

**Comment by rsesek** [comment]
I wrote a small Go program to generate an Ed25519 keypair in PEM format without Keychain, and to sign/verify with PEM-encoded keys: https://github.com/rsesek/MacGDBp/blob/87ab5e8b514bb822ac2d0586d2f6b095ceb56e6e/dev/signer-ed25519.go

**Comment by zorgiepoo** [comment]
Arguments to sign_update were recently added to pass a signing key.
