### ISSUE TITLE
Master is broken after commit 2db2fff

### ISSUE THREAD

**Issue by LeoNatan** [sparkle-project/Sparkle#1455]
Hi guys,

Master seems to be currently broken due to a bad PR that has landed:

https://github.com/sparkle-project/Sparkle/commit/2db2fffab9917ffc0020d03a2929a25b55ee25c0#diff-c622917364e021ecfd07b9695bab10c1R167

How did this pass review?

**Comment by kornelski** [comment]
Thanks for catching this. Can you submit a PR with a fix?

**Comment by LeoNatan** [comment]
Sure. Just not sure which of the sector variants is the desired one?

**Comment by kornelski** [comment]
the one with `updater:` is the correct one.

**Comment by LeoNatan** [comment]
Great. I’ll submit one soon.
