### ISSUE TITLE
Does it not work at all with HTTP?

### ISSUE THREAD

**Issue by JoeriBultheel** [sparkle-project/Sparkle#1460]
In the documentation it states that it is 'recommended' to use https to serve the updates. That phrasing is quite ambiguous as in another document it states: 

Since 10.11, macOS has App Transport Security policy which blocks apps from using insecure HTTP connections. This restriction applies to Sparkle as well, so you will need to serve your appcast and the update files over HTTPS.

So my question is: can we serve over HTTP when we set the App Transport Security to false in the info.plist? 

Thnx

**Comment by kornelski** [comment]
You can, if you disable ATS.

We recommend against it, but won't stop you from doing it.

**Comment by JoeriBultheel** [comment]
I had put NSAppTransportSecurity with a value of <false/> instead of 
<dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
</dict>
So probably my own fault. Anyway, in the mean time I got my SSL certificates so now I'm doing everything with https :) 

Thnx for the awesome project!
