### ISSUE TITLE
appcast's enclosure url is using http but my SUFeedURL is https ?

### ISSUE THREAD

**Issue by JoeriBultheel** [sparkle-project/Sparkle#1461]
The 'appcast' xml file created by running the 'generate_appcast' script has for the 'Enclosure Url' key a string-url which starts with http://, but my SUFeedURL starts with https://.

When downloading the new build an error comes warning about Transport Security reading an unencrypted url and it blocks. 

I can perfectly circumvent this issue by changing the value in the xml file to https manually. Then everything is working fine. So my question is why or from where is it extracting this http value? 

edit: The SUFeedURL was once starting with http, but after changing it to https I cleared the Defaults by running 'defaults delete com.xxxx.xxxx'.

Thnx

**Comment by dataexcess** [comment]
Hey there,

I still have this issue. Now when I run the appcast script it is writing a lot of old (cached) information (build version, application name) of a previous build I ran with the appcast script. 
So somehow somewhere Sparkle is caching values. 

Why? and how to prevent caching?

Thank you

**Comment by dataexcess** [comment]
I believe I can answer my own question here: 

Run the generate_appcast command from within the Sparkle's Pod directory (use in your xcode project) not the initial clone'd Sparkle location! At least this did the trick for me. Could be described a bit better in the documentation imho.

Cheers

**Comment by dataexcess** [comment]
when I make a second 'higher' version appcast now - the results of the previous one is cached :(
Why does this happen - and how can I fix it.

**Comment by ltetak** [comment]
It may be cached - see this thread for better answer https://github.com/sparkle-project/Sparkle/issues/1315

**Comment by zorgiepoo** [comment]
#1582 is supposed to be smarter about invalidating caches.
