### ISSUE TITLE
sparkle:shortVersionString seems ignored

### ISSUE THREAD

**Issue by marcobambini** [sparkle-project/Sparkle#1464]
I am using Sparkle version https://github.com/sparkle-project/Sparkle/releases/tag/1.21.3 and I think to have correctly setup a xml file: https://media.creolabs.com/release/appcast.xml

I added to it both sparkle:version and sparkle:shortVersionString but I continue to be notified using the internal version bundle (as you can see from the screenshot).

What I am doing wrong?
<img width="532" alt="Screenshot 2019-09-07 at 16 17 11" src="https://user-images.githubusercontent.com/11838145/64490831-ed5dbb80-d215-11e9-8efc-2518cb551599.png">

**Comment by kornelski** [comment]
I think this bug has been fixed on master.

**Comment by marcobambini** [comment]
Thanks
