### ISSUE TITLE
Minor grammar change to up-to-date

### ISSUE THREAD

**Issue by ryanfrancesconi** [sparkle-project/Sparkle#1466]
I believe that "up-to-date" should actually not be hyphenated in your messages.

🍔
****

Up to date
The common phrase up to date is hyphenated when it precedes the noun it modifies—for example:

Having an up-to-date inventory of the contents of your home can help speed the payment of an insurance claim. [Chicago Tribune]

The highest-rated services have up-to-date guides that explain the options and filter tools to help identify appropriate funds. [Financial Times]

When the phrase functions as a predicate adjective coming after what it modifies, it is not hyphenated—for example:

I take it to mean that your emergency preparedness plans should be up to date. [Wired]

But now you’ve got a fully functional Ubuntu system, with everything up to date from the get-go. [Lifehacker]

And when up to date functions adverbially, it does not need to be hyphenated—for example:

Keeping up to date on the barrage of medical information available online can be daunting. [Globe and Mail]

Sure, there’s paperwork, but more importantly, you must stay up to date with the laws. [News.com.au]

**Comment by kornelski** [comment]
Thanks
