### ISSUE TITLE
Notarization issue, any help?

### ISSUE THREAD

**Issue by marcobambini** [sparkle-project/Sparkle#1467]
Anyone know how to fix the missing profile issue for the Autoupdate.app application?

<img width="1312" alt="Screenshot 2019-09-12 at 14 54 11" src="https://user-images.githubusercontent.com/11838145/64824034-c84aaf00-d56d-11e9-9d52-5e422acacacc.png">
<img width="1216" alt="Screenshot 2019-09-12 at 14 54 19" src="https://user-images.githubusercontent.com/11838145/64824035-c84aaf00-d56d-11e9-92a6-37fa455bbe1e.png">

**Comment by zsh7887** [comment]
I have this situation too. Have you solved the problem

**Comment by megabitsenmzq** [comment]
> I have this situation too. Have you solved the problem

It seems you can just select “None” for these targets.
