### ISSUE TITLE
Error: hardened runtime service kTCCServiceAppleEvents requires entitlement 

### ISSUE THREAD

**Issue by gblazex** [sparkle-project/Sparkle#1468]
Trying to debug why my users don't get updated.

I'm getting this error in console.

> Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: org.sparkle-project.Sparkle.Autoupdate, PID[27746], auid: 501, euid: 501, binary path: '/Users/galambalazs/Library/Caches/com.galambalazs.SmoothScroll/org.sparkle-project.Sparkle/SmoothScroll (Autoupdate).app/Contents/MacOS/Autoupdate'}, REQ:{ID: com.apple.appleeventsd, PID[76], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}

Can this be the problem?

**Comment by kornelski** [comment]
I haven't seen this error before. I don't think we're using AppleEvents, unless they're implicitly used by some other Cocoa API.

Are you using AppleEvents in your host app?

**Comment by lwouis** [comment]
I'm seeing the same error. I'm on Catalina, and Sparkle 1.23.0:

```
Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for RESP:{ID: org.sparkle-project.Sparkle.Autoupdate, PID[69257], auid: 182020437, euid: 182020437, responsible path: '/Users/louis.pontoise/git_clones/alt-tab-macos/DerivedData/alt-tab-macos/Build/Products/Debug/AltTab.app/Contents/MacOS/AltTab', binary path: '/Users/louis.pontoise/Library/Caches/com.lwouis.alt-tab-macos/org.sparkle-project.Sparkle/AltTab (Autoupdate).app/Contents/MacOS/Autoupdate'}, ACC:{ID: org.sparkle-project.Sparkle.Autoupdate, PID[69257], auid: 182020437, euid: 182020437, binary path: '/Users/louis.pontoise/Library/Caches/com.lwouis.alt-tab-macos/org.sparkle-project.Sparkle/AltTab (Autoupdate).app/Contents/MacOS/Autoupdate'}, REQ:{ID: com.apple.appleeventsd, PID[448], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}
```

**Comment by gblazex** [comment]
I ended up adding the mentioned entitlement to my project (even tho it needed none before)

Now it works and updates were smooth

Hope it helps 

Blaze

**Comment by lwouis** [comment]
@gblazex could you please share what the symptoms were before the change you made? You say the updates are smooth now but what was the issue before?

**Comment by gblazex** [comment]
There were no issues I just wanted for the message to go away.

By smooth I just meant users’ systems didn’t have a problem with a new update having a new entitlement 


Blaze

**Comment by jaxony** [comment]
Also seeing this error on macOS 11.2.3, Sparkle 2 beta.6. The App cannot update.

```
Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for accessing={identifier=org.sparkle-project.Sparkle.Updater, pid=25312, auid=501, euid=501, binary_path=/Users/xxxx/Library/Caches/xxxx/org.sparkle-project.Sparkle/Launcher/zxym4oaDM/Updater.app/Contents/MacOS/Updater}, requesting={identifier=com.apple.appleeventsd, pid=369, auid=55, euid=55, binary_path=/System/Library/CoreServices/appleeventsd}
```

**Comment by zorgiepoo** [comment]
That is a red herring. I see that message on successful updates.

There should be actual error logs under your app using Sparkle or for Autoupdate. Please file a new issue if you're able to find the logs, or share a binary repro case, and can't figure out the issue.
