### ISSUE TITLE
How to check for beta versions

### ISSUE THREAD

**Issue by marcobambini** [sparkle-project/Sparkle#1469]
Is there a way to configure Sparkle to check for beta versions of my app?
Some users should have access to beta while others to release only builds.

**Comment by glouel** [comment]
@marcobambini the way I do it is by using two separate `appcast.xml` feeds. You can then switch with that line of code when a user wants betas, I do it at startup just after initializing SUUpdater : 

```
sparkleUpdater?.feedURL = URL(string: "https://path.to.you/beta-appcast.xml")
```
