### ISSUE TITLE
[Feature request] Swift Package manager support.

### ISSUE THREAD

**Issue by xjbeta** [sparkle-project/Sparkle#1474]
It's easier to add a library with SPM in Xcode 11.

**Comment by kornelski** [comment]
That would be nice, but last time I looked, it wasn't clear to me if SPM supports ObjC frameworks too.

If you know how to make SPM packages, can you make a pull request?

**Comment by xjbeta** [comment]
`.....  contains mixed language source files; feature not supported`

**Comment by liamrosenfeld** [comment]
I'm looking into creating an SPM package and it appears the `contains mixed language source files; feature not supported` error is just caused by `CheckLocalizations.swift` being stored inside of `Sparkle/` instead of anywhere else
