### ISSUE TITLE
Could not find 1.22.0 in CocoaPods

### ISSUE THREAD

**Issue by yichengchen** [sparkle-project/Sparkle#1475]
the latest version in [CocoaPods](https://github.com/CocoaPods/Specs/tree/master/Specs/7/c/d/Sparkle) is 1.21.3, do I miss something? I tried specify git repo and tag 1.22.0 in my pod file, but it seem's not working.

**Comment by yichengchen** [comment]
Maybe it should be a good idea to add `pod trunk push` in our CI Configuration?

**Comment by gregcotten** [comment]
doesn't appear to be pushed
