### ISSUE TITLE
Sparkle 2: checkForUpdates does nothing when automatic update is in progress

### ISSUE THREAD

**Issue by jakob** [sparkle-project/Sparkle#1478]
In the ui-separation-and-xpc branch, calling `checkForUpdates` does nothing if an automatic update is already in progress / scheduled to install.

In the master branch, it seems that this issue has been fixed already (see issue #970), but I'm not sure how this fix could be adopted for Sparle 2?

**Comment by diaslane** [comment]
Did you call checkForUpdatesInBackground before calling checkForUpdates? I used background checking when my app started and got the same problem. But When I remove that one, checkForUpdates responded. Guess they are sharing one background executing flag and make the other one silent.

**Comment by zorgiepoo** [comment]
Like 1.x, multiple update checks can't be done simultaneously. If the update check calls are spaced out enough, it should work. An update check does not leave the update driver running indefinitely and 2.x can resume updates so #970 isn't applicable. #1726 adds/migrates a property indicating if updates can be checked for clarity.

**Comment by zorgiepoo** [comment]
Sparkle 2 adds delegate method for when the update cycle finishes (and then sessionInProgress is false)

Sparkle cannot run an update check when an update cycle is already in progress. Chances are you shouldn't be calling checkForUpdates manually unless canCheckForUpdates is true; that's intended to be a user-initiated check, not one that happens while updates are being checked in the background.
