### ISSUE TITLE
Sparkle doesn't properly eject disk images that are APFS formatted

### ISSUE THREAD

**Issue by core-code** [sparkle-project/Sparkle#1481]
Sparkle has had the ability to update apps from .DMG disk images for years. It also takes care to 'clean up' after itself, ejecting the disk image that had to be mounted. The corresponding lines are in 'SUDiskImageUnarchiver.m':

```
            task.launchPath = @"/usr/bin/hdiutil";
            task.arguments = @[@"detach", mountPoint, @"-force"];
```

However, this is not enough anymore with the advent and prevalence of 'APFS' formatted disk images, which are created by default these days. After updating an app that uses Sparkle and which is delivered on an APFS .DMG, you'll still see the devices hanging around in the device list (which can e.g. be seen with `diskutil list` ).

You can also reproduce the problem yourself manually:
1.) download or create an APFS disk image. i took this: https://download.calibre-ebook.com/4.0.0/calibre-4.0.0.dmg
2.) mount the image just as Sparkle is doing it
`mkdir test;hdiutil attach calibre-4.0.0.dmg -mountpoint test  -nobrowse -noautoopen`
3.) unmount the image just as Sparkle is doing it:
`hdiutil detach -force test
`
4.) inspect the device list:
`diskutil list` 
5.) see that this procedure has left behind not only one but two device nodes:
```
/dev/disk4 (disk image):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        +432.3 MB   disk4
   1:                 Apple_APFS Container disk5         432.2 MB   disk4s1

/dev/disk5 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +432.2 MB   disk5
                                 Physical Store disk4s1
   1:                APFS Volume calibre-4.0.0           379.5 MB   disk5s1
```

Proposed Solution:
Check the 'hdiutil attach' text output and If it contains 'Apple_APFS' then the 'hdiutil detach' command should not eject the mountpoint but the device node corresponding to the 'GUID_partition_scheme' line in the attach output. I can provide a patch.

Notes:
it sounds to me like this is basically a bug in 'hdiutil detach', it won't fully clean up when 1.) specifying the mountpoint and 2.) the DMG in question is APFS. feel free to file a bug report with them but at this point i have given up there and won't do it myself.

**Comment by core-code** [comment]
proposed fix - insert this above mountedSuccessfully = YES:

```
        unmountPoint = mountPoint;
        if ([resultStr contains:@"Apple_APFS"])
        {
            for (NSString *line in [resultStr componentsSeparatedByString:@"\n"])
            {
                if ([line rangeOfString:@"GUID_partition_scheme"].location != NSNotFound && [line rangeOfString:@"/dev/disk"].location != NSNotFound)
                    unmountPoint = [[line stringByReplacingOccurrencesOfString:@"GUID_partition_scheme" withString:@""]  stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
            }
        }
```

of course the eject line needs to be adapted:

`            task.arguments = @[@"detach", mountPoint, @"-force"];
`=>
`            task.arguments = @[@"detach", unmountPoint, @"-force"];
`

i can confirm this fixes the issue

**Comment by zorgiepoo** [comment]
I don't believe I saw this as an issue on Big Sur.
