### ISSUE TITLE
generate_appcast doesn't generate the latest app version

### ISSUE THREAD

**Issue by dexterleng** [sparkle-project/Sparkle#1487]
I have a new version in a file called `vimac-0.2.3.app.zip`, with an increased bundle version. `generate_appcast` doesn't add it to the appcast. However, if I rename the file to `vimac-0.2.3a.app.zip` it works as expected.

Any idea why is happens?

**Comment by kornelski** [comment]
Unarchived files are cached in ~/Library/Caches/Sparkle. It assumes archive never changes.

**Comment by dexterleng** [comment]
@kornelski how does this explain why the new version isn't added to `appcast.xml`?

**Comment by kornelski** [comment]
I assume you've called the command before when the archive had an older version, and it got cached with that version.
