### ISSUE TITLE
An error occurred while extracting the archive. Please try again later.

### ISSUE THREAD

**Issue by gee1k** [sparkle-project/Sparkle#1488]
### Description of the problem
After install and relaunch : An error occurred while extracting the archive. Please try again later.

From the error message, the signature is incorrect. However, it has been normal in previous versions. I also signed a separate signature for each version.

AppCast: https://svend.cc/uPic/appcast.xml

![image](https://user-images.githubusercontent.com/12059800/66880959-b7231100-eff7-11e9-95f4-95378f4fa889.png)

### Do you use Sandboxing in your app?
no
### Version of `Sparkle.framework` in the latest version of your app
1.22.0
### Sparkle's output from Console.app
```
Error: An error occurred while extracting the archive. Please try again later. The update is improperly signed. (URL (null))
```

**Comment by kornelski** [comment]
Have you tried using `generate_appcast` tool? It guarantees the signatures are correct.

**Comment by kornelski** [comment]
Also the log should contain more messages before this one about why the signature is wrong.

**Comment by gee1k** [comment]
I have never used `generate_appcast ` to generate `appcast`, which is generated by GitHub jekyll automatically reading the release. And there has been no problem before, this is the first time I have encountered this problem.
I am not sure if it is related to my upgrade to `macos catalina `
