### ISSUE TITLE
Providing private key as argument still doesn't work

### ISSUE THREAD

**Issue by puhach** [sparkle-project/Sparkle#1491]
I am reading this line in the list of improvements for Sparkle 1.22: "Support providing private key as argument (Yakuhzi)".

In fact, sign_update accepts only the archive name: 
```
Usage: ./sign_update <archive to sign>
```

**Comment by kornelski** [comment]
This has been fixed https://github.com/sparkle-project/Sparkle/blob/master/sign_update/main.swift#L70
