### ISSUE TITLE
Unable to import a private key to keychain

### ISSUE THREAD

**Issue by puhach** [sparkle-project/Sparkle#1492]
I've been trying to sign the update with an existing private key generated by a previous Sparkle version. The key is contained in a .pem file. When I try to import it to the keychain, it fails with the following message: 

> An error has occurred. Unable to import an item. 
> 
> The contents of this item cannot be retrieved.

**Comment by kornelski** [comment]
macOS doesn't support ED25519 keys, so we're not storing the key as a key, but instead as an "application-specific password". Try creating the keychain entry manually by copying and pasting the "password".

**Comment by kornelski** [comment]
Only the old DSA system used pem files. The new EdDSA doesn't.

Our new keys don't exist in the form of files. I don't know if it's even possible to put them in a pem file, but we certainly don't support them in the pem format.

The ed25519 keys are generated for you in the Keychain, and stored there as a relatively short base64-encoded string, similar to a password. They're never written to disk as a file. They can't be exported to a file. They can't be read from a file.

**Comment by puhach** [comment]
Ok, are there any guidelines for migration from existing keys stored in .pem to a new format?

Also I'm wondering how to transfer the new EdDSA key to another machine? Or am I supposed to generate a new key pair for every new machine I use for building the project?

**Comment by kornelski** [comment]
There is no migration from the `pem` format. The old DSA with pem still works exactly the same as it always worked. 
The new EdDSA is a new, separate system, with no connection to the old (apart from 3 letters in the name. That's all they have in common). 

Both can work at the same time (you sign twice, using two keys, `generate_appcast` knows how to do it), so you can support old clients.

To move it to another machine, you could try using Keychain Access app to create a new keychain file, move "Private key for signing Sparkle updates" item to that keychain, and load that keychain on another Mac.

For CI and such, read the key ("password" field) from the "Private key for signing Sparkle updates" item and set it as an argument for `sign_update` or `generate_appcast` executables (support for this is recent, so try version on master).

**Comment by puhach** [comment]
Thank you
