### ISSUE TITLE
"(You are currently running version %3$@.)" even in other languages than english

### ISSUE THREAD

**Issue by kennethjohnsen** [sparkle-project/Sparkle#1493]
When checking for updates when there are none, the user will get a message saying what the current version is (in my case in Danish). But right after that, it says "(You are currently running version ...)" (in English).

Should these be translated to the user's language? The same string is present in many files, so it's not just for Danish.

I can provide the text for Danish, but unfortunately I can't help with the other languages.

**Comment by kornelski** [comment]
They should be. We've had to add a new string and don't have translations for it yet.

**Comment by kennethjohnsen** [comment]
Is it OK if I submit a PR with just the Danish translation, or should it be done for all languages at the same time?

**Comment by kornelski** [comment]
It's OK. Please submit a PR.
