### ISSUE TITLE
How to include Build Number in Update Alert

### ISSUE THREAD

**Issue by ProfDrLuigi** [sparkle-project/Sparkle#1496]
Hi Folx.

I´m trying to display the Buildnumber as well in the Update Alert. I have an App which has V 2.4 (359). Only the v 2.4 is showing. How to include the (359) too?

**Comment by kornelski** [comment]
Sparkle uses `CFBundleShortVersionString` from `Into.plist` to display the version to the user. You can also add `sparkle:shortVersionString` to the appcast.

**Comment by ProfDrLuigi** [comment]
I already have
sparkle:version="359" sparkle:shortVersionString="2.4"
in the appcast. But 359 is not showing.

**Comment by michelf** [comment]
From my observations, I believe the build number is only shown when the two short version strings are identical, like if update from from 2.4 (358) to version 2.4 (359). If the update takes you from 2.4 to 2.5, build numbers are not shown.

**Comment by ProfDrLuigi** [comment]
Yes michelf. You are right. Now it´s working.

**Comment by kornelski** [comment]
`sparkle:version` is not for display, but for comparison which version is newer.

**Comment by michelf** [comment]
@kornelski That's true in general. But when the normal display version is the same it'll be shown, as the code says here: https://github.com/sparkle-project/Sparkle/blob/0cfedd45166c2750f688307728fc38c9f897a66b/Sparkle/SUUpdateAlert.m#L308
