### ISSUE TITLE
Multiple applications & developers

### ISSUE THREAD

**Issue by macmule** [sparkle-project/Sparkle#1497]
With the move from DSA to EdDSA, what's the recommend workflows for using Sparkle across multiple apps & with multiple developers?

**Comment by kornelski** [comment]
What's your current workflow? Do you want multiple developers to have ability to sign it? Do you want separate apps to use separate private keys?

**Comment by macmule** [comment]
Honestly only used Sparkle for my projects until yesterday.

Decided to share the keychain item & use the same key across the team across apps.

Just wouldn’t mind some guidance on if a good process or not.

**Comment by kornelski** [comment]
Yeah, moving Sparkle's key to a separate keychain file that is shared seems fine.

If you have a dedicated machine for making releases, the key should live there.

**Comment by macmule** [comment]
thanks
