### ISSUE TITLE
Failed to change owner & group on ...

### ISSUE THREAD

**Issue by LidiaMirkin** [sparkle-project/Sparkle#1498]
I am running with last stable Sparkle.
I constantly started to get message "Failed to change owner & group on..." since update to Catalina at the end of update, just after Sparkle asks for admin password.
Log is attached.

Could you advice please ?
Thanks a lot.

**Comment by LidiaMirkin** [comment]
[log.pdf](https://github.com/sparkle-project/Sparkle/files/3828653/log.pdf)

**Comment by kornelski** [comment]
This seem to be correct behavior. The OS is refusing to let autoupdate adjust permissions without authorization. I don't think there is any other solution.

**Comment by LidiaMirkin** [comment]
Hello again,
Probably i did not explain well : there is dialog asking for password, and when valid administrator password entered (the same one used to install application), dialog with "Failed to change owner & group on..." appears.
