### ISSUE TITLE
EdDSA key rotation or replacement?

### ISSUE THREAD

**Issue by geraldcombs** [sparkle-project/Sparkle#1501]
Is it possible to rotate or replace your EdDSA key? The documentation seems to indicate that this isn't the case.

The OpenBSD project [signs each release using a unique EdDSA key via the signify utility](https://www.openbsd.org/papers/bsdcan-signify.html), and they include the public key for release x.y+1 with each x.y release. Note that they also stick to a 6-month release schedule, which effectively means they rotate keys twice a year.

Given that appcast includes a pubDate element, it seems like something similar could be accomplished with Sparkle by adding multiple datestamped signing keys to Info.plist. For example, if Info.plist contained

```
<key>SUPublicEDKey2020</key>
...
<key>SUPublicEDKey2021</key>
...
```

and the current appcast.xml contained

```
<pubDate>Thu Jan 14 12:00:00 UTC 2020</pubDate>
```

Sparkle could determine that it would need to validate using the SUPublicEDKey2020 key.

**Comment by kornelski** [comment]
If you use Apple Code Signing, you can change EdDSA key as long as Code Signing identity stays the same.

**Comment by zorgiepoo** [comment]
Supported via code signing as noted above.
