### ISSUE TITLE
Sparkle update very slow (2 minutes)

### ISSUE THREAD

**Issue by 01CGAT** [sparkle-project/Sparkle#1502]
Since I enabled Hardened Runtime and upgraded Sparkle to 1.22 (through CocoaPods) to get Notarized for MacOS Catalina, an update of the app through Sparkle (on Catalina) takes about 2 minutes. It seems for a long time nothing is happening and the update process got stuck/crashed. Eventually the app starts again with the new update. Somewhere in logging you can find the infamous "Death sentinel fired" too.
The app has a HelperTool to start an openvpn connection and setup firewall rules etc.

### Do you use Sandboxing in your app?

No.

### Version of `Sparkle.framework` in the latest version of your app

1.22

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)

1.21

### Sparkle's output from Console.app

default	21:54:45.244044+0100	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask%20(Autoupdate).app/Contents/, NSFilePath=/Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask (Autoupdate).app/Contents/PlugIns, NSUnderlyingError=0x7fb359430980 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	21:54:45.253948+0100	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask%20(Autoupdate).app/Contents/, NSFilePath=/Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask (Autoupdate).app/Contents/PlugIns, NSUnderlyingError=0x7fb359444b70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	21:54:45.254005+0100	lsd	- 45683955: Checking whether application is managed at file:///Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask%20(Autoupdate).app/org.sparkle-project.Sparkle.Autoupdate
default	21:54:45.264955+0100	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask%20(Autoupdate).app/Contents/, NSFilePath=/Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask (Autoupdate).app/Contents/PlugIns, NSUnderlyingError=0x7fb359535560 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	21:54:45.265387+0100	lsd	- 45683955: Checking whether application is managed at file:///Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask%20(Autoupdate).app/org.sparkle-project.Sparkle.Autoupdate
default	21:54:45.300379+0100	dmd	Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs =     (
        "org.sparkle-project.Sparkle.Autoupdate"
    );
    isPlaceholder = 0;
}
default	21:54:45.300530+0100	dmd	Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs =     (
        "org.sparkle-project.Sparkle.Autoupdate"
    );
    isForcedUpdate = 1;
    isPlaceholder = 0;
}
default	21:55:45.583031+0100	Autoupdate	FRONTLOGGING: version 1
default	21:55:45.583064+0100	Autoupdate	Registering, pid=45791
default	21:55:45.584799+0100	Autoupdate	CHECKIN: pid=45791
default	21:55:45.598143+0100	Autoupdate	CHECKEDIN: pid=45791 asn=0x0-0x10b10b foreground=0
default	21:55:45.597172+0100	launchservicesd	CHECKIN:0x0-0x10b10b 45791 org.sparkle-project.Sparkle.Autoupdate
default	21:55:45.599215+0100	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Autoupdate
default	21:55:45.619963+0100	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask%20(Autoupdate).app/Contents/, NSFilePath=/Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask (Autoupdate).app/Contents/PlugIns, NSUnderlyingError=0x7fd6b3702350 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	21:55:45.620143+0100	lsd	- 45683955: Checking whether application is managed at file:///Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask%20(Autoupdate).app//org.sparkle-project.Sparkle.Autoupdate
default	21:55:45.620621+0100	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask%20(Autoupdate).app/Contents/, NSFilePath=/Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask (Autoupdate).app/Contents/PlugIns, NSUnderlyingError=0x7fb359715450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	21:55:45.620767+0100	lsd	- 45683955: Checking whether application is managed at file:///Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask%20(Autoupdate).app//org.sparkle-project.Sparkle.Autoupdate
default	21:55:45.643246+0100	nehelper	Handling an apps installed notification with bundle IDs (
    "org.sparkle-project.Sparkle.Autoupdate"
)
default	21:55:45.644233+0100	runningboardd	Resolved pid 45791 to [executable<Autoupdate(501)>:45791]
default	21:55:45.645726+0100	runningboardd	[executable<Autoupdate(501)>:45791] This process will not be managed.
default	21:55:45.645770+0100	runningboardd	Now tracking process: [executable<Autoupdate(501)>:45791]
default	21:55:45.646323+0100	runningboardd	Acquiring assertion targeting executable<Autoupdate(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:264] with description <RBSAssertionDescriptor; uielement:45791; ID: 450-264-1307; target: 45791> attributes = {
    <RBSDomainAttribute: 0x7ffc30a0e110; domain: com.apple.launchservicesd; name: RoleUserInteractive; sourceEnvironment: 0x0>;
}
default	21:55:45.646490+0100	runningboardd	Assertion 450-264-1307 (target:executable<Autoupdate(501)>) will be created as active
default	21:55:45.647087+0100	runningboardd	[executable<Autoupdate(501)>:45791] Ignoring jetsam update because this process is not memory-managed
default	21:55:45.647119+0100	runningboardd	Acquiring assertion targeting executable<Autoupdate(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:264] with description <RBSAssertionDescriptor; uielement:45791; ID: 450-264-1308; target: 45791> attributes = {
    <RBSDomainAttribute: 0x7ffc2f715d00; domain: com.apple.launchservicesd; name: RoleUserInteractive; sourceEnvironment: 0x0>;
}
default	21:55:45.647357+0100	runningboardd	[executable<Autoupdate(501)>:45791] Ignoring resume because this process is not lifecycle managed
default	21:55:45.647540+0100	runningboardd	Assertion 450-264-1308 (target:executable<Autoupdate(501)>) will be created as active
default	21:55:45.647543+0100	runningboardd	[executable<Autoupdate(501)>:45791] Set darwin role to: UserInteractive
default	21:55:45.647650+0100	runningboardd	Finished acquiring assertion 450-264-1307 (target:executable<Autoupdate(501)>)
default	21:55:45.647722+0100	runningboardd	[executable<Autoupdate(501)>:45791] Ignoring GPU update because this process is not GPU managed
default	21:55:45.648534+0100	runningboardd	Finished acquiring assertion 450-264-1308 (target:executable<Autoupdate(501)>)
default	21:55:45.648544+0100	runningboardd	Invalidating assertion 450-264-1307 (target:executable<Autoupdate(501)>) from originator 264
default	21:55:45.649367+0100	Autoupdate	Registered, pid=45791 ASN=0x0,0x10b10b
default	21:55:45.649514+0100	Autoupdate	Registered, pid=45791 cgConnectionID=b147b
default	21:55:45.650707+0100	Autoupdate	BringForward: pid=45791 asn=0x0-0x10b10b bringForward=0 foreground=0 uiElement=1 launchedByLS=0 modifiersCount=0 allDisabled=0
default	21:55:45.651400+0100	Autoupdate	Current system appearance, (HLTB: 2), (SLS: 1)
default	21:55:45.657535+0100	Autoupdate	Post-registration system appearance: (HLTB: 2)
default	21:55:45.671830+0100	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: org.sparkle-project.Sparkle.Autoupdate token: f4268 pid: 45791
default	21:55:45.679368+0100	Autoupdate	SetFrontProcess: asn=0x0-0x10b10b options=1
default	21:55:45.680514+0100	Autoupdate	Received configuration update from daemon (initial)
default	21:55:45.681293+0100	runningboardd	Acquiring assertion targeting executable<Autoupdate(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:264] with description <RBSAssertionDescriptor; frontmost:45791; ID: 450-264-1310; target: 45791> attributes = {
    <RBSDomainAttribute: 0x7ffc2f515940; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
default	21:55:45.681611+0100	runningboardd	Assertion 450-264-1310 (target:executable<Autoupdate(501)>) will be created as active
default	21:55:45.683470+0100	Autoupdate	PID to listen: 41552
default	21:55:45.682694+0100	runningboardd	Finished acquiring assertion 450-264-1310 (target:executable<Autoupdate(501)>)
default	21:55:45.684355+0100	Autoupdate	Registering for test daemon availability notify post.
default	21:55:45.682862+0100	runningboardd	[executable<Autoupdate(501)>:45791] Ignoring jetsam update because this process is not memory-managed
default	21:55:45.684529+0100	Autoupdate	notify_get_state check indicated test daemon not ready.
default	21:55:45.683883+0100	runningboardd	[executable<Autoupdate(501)>:45791] Set darwin role to: UserInteractiveFocal
default	21:55:45.684504+0100	runningboardd	[executable<Autoupdate(501)>:45791] Ignoring GPU update because this process is not GPU managed
default	21:55:45.697901+0100	Autoupdate	SignalReady: pid=45791 asn=0x0-0x10b10b
default	21:55:45.698554+0100	Autoupdate	SIGNAL: pid=45791 asn=0x0x-0x1093899
error	21:55:45.776635+0100	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for RESP:{ID: org.sparkle-project.Sparkle.Autoupdate, PID[45791], auid: 501, euid: 501, responsible path: '/Applications/WifiMask.app/Contents/MacOS/WifiMask', binary path: '/Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask (Autoupdate).app/Contents/MacOS/Autoupdate'}, ACC:{ID: org.sparkle-project.Sparkle.Autoupdate, PID[45791], auid: 501, euid: 501, binary path: '/Users/username/Library/Caches/com.wifimask.macos/org.sparkle-project.Sparkle/WifiMask (Autoupdate).app/Contents/MacOS/Autoupdate'}, REQ:{ID: com.apple.appleeventsd, PID[478], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}
default	21:55:45.834394+0100	Autoupdate	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 0
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600002098400
 (
    "<NSDarkAquaAppearance: 0x600002092b00>",
    "<NSSystemAppearance: 0x600002092380>"
)>
default	21:55:45.849286+0100	distnoted	register name: com.apple.nsquiet_safe_quit_give_reason object: org.sparkle-project.Sparkle.Autoupdate token: f4291 pid: 45791
default	21:55:45.934851+0100	Autoupdate	Metal API Validation Enabled
default	21:55:45.993016+0100	hidd	Connection added: IOHIDEventSystemConnection uuid:C6339340-24FE-4317-89C4-591D151FE93E pid:45791 process:Autoupdate type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1 events:0 mask:0x0
default	21:55:46.033265+0100	Autoupdate	bundle 0x1d9c mod date changed from Sun Nov 17 21:05:45 2019 to Sun Nov 17 21:55:45 2019
default	21:55:46.033440+0100	Autoupdate	bundle 0x1d9c node has changed
default	21:55:46.042203+0100	Autoupdate	bundle 0x1d9c mod date changed from Sun Nov 17 21:05:45 2019 to Sun Nov 17 21:55:45 2019
default	21:55:46.042296+0100	Autoupdate	bundle 0x1d9c node has changed
default	21:55:46.133609+0100	Autoupdate	Found application WifiMask to open application file:///Applications/WifiMask.app
default	21:55:46.145163+0100	Autoupdate	<PKDiscoveryDriver:0x600002ab81e0> created discovery driver
default	21:55:46.145236+0100	Autoupdate	[d 5204FE1C-F292-400F-9028-936395C1050F] <PKHost:0x600001baef00> Beginning discovery for flags: 0, point: multiple
default	21:55:46.145374+0100	Autoupdate	<PKDiscoveryDriver:0x600002ab82a0> created discovery driver
default	21:55:46.145415+0100	Autoupdate	[d 17329F3C-275B-47EB-A113-227631D03B7A] <PKHost:0x600001baef00> Beginning discovery for flags: 0, point: com.apple.FinderSync
default	21:55:46.201086+0100	Autoupdate	[d 5204FE1C-F292-400F-9028-936395C1050F] <PKHost:0x600001baef00> Completed discovery. Final # of matches: 21
default	21:55:46.201152+0100	Autoupdate	<PKDiscoveryDriver:0x600002ab81e0> delivering update to host (21 plugins)
default	21:55:46.201198+0100	Autoupdate	[d 17329F3C-275B-47EB-A113-227631D03B7A] <PKHost:0x600001baef00> Completed discovery. Final # of matches: 0
default	21:55:46.201253+0100	Autoupdate	<PKDiscoveryDriver:0x600002ab82a0> delivering update to host (0 plugins)
default	21:55:46.201359+0100	Autoupdate	<PKDiscoveryDriver:0x600002ab82a0> installing watchers for continuous discovery
default	21:55:46.248771+0100	Autoupdate	_LSLaunch('/Applications/WifiMask.app')
default	21:55:46.250015+0100	Autoupdate	LAUNCHING:0x0-0x10c10c WifiMask foreground=0 bringForward=0 seed=885 userActivityCount=0
default	21:55:46.250053+0100	Autoupdate	<PKDiscoveryDriver:0x600002ab81e0> installing watchers for continuous discovery
default	21:55:46.396523+0100	Autoupdate	OSStatus _LSLaunch(LSContext *, FSNode *, LSLaunchFlags, void *, CFArrayRef, const AppleEvent *, const AEDescList *, CFArrayRef, CFDictionaryRef, LSBundleID, const audit_token_t *, const _LSOpen2Options *, ProcessSerialNumber *, Boolean *, NSError **): launching '/Applications/WifiMask.app' result=0
default	21:55:47.757591+0100	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/WifiMask.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/, NSFilePath=/Applications/WifiMask.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/PlugIns, NSUnderlyingError=0x7fb359714600 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	21:55:47.757643+0100	lsd	- 45683955: Checking whether application is managed at file:///Applications/WifiMask.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app//org.sparkle-project.Sparkle.Autoupdate
default	21:55:47.772425+0100	dmd	Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs =     (
        "org.sparkle-project.Sparkle.Autoupdate"
    );
    isForcedUpdate = 1;
    isPlaceholder = 0;
}
default	21:55:47.784974+0100	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/WifiMask.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/, NSFilePath=/Applications/WifiMask.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/PlugIns, NSUnderlyingError=0x7fb35a907490 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	21:55:47.785125+0100	lsd	- 45683955: Checking whether application is managed at file:///Applications/WifiMask.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app//org.sparkle-project.Sparkle.Autoupdate
default	21:55:47.802092+0100	dmd	Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs =     (
        "org.sparkle-project.Sparkle.Autoupdate"
    );
    isForcedUpdate = 1;
    isPlaceholder = 0;
}
default	21:55:51.450448+0100	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: Autoupdate__WSWindow__WSWindowDrag **** frame data ****
default	21:55:51.450572+0100	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: Autoupdate__WSWindow__WSWindowDrag __frames/s (IntervalRate)__ 84.9
default	21:55:51.450820+0100	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: Autoupdate__WSWindow__WSWindowDrag __frames/s (IntervalRateIgnoringDelay)__ 100.2
default	21:55:51.450928+0100	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: Autoupdate__WSWindow__WSWindowDrag __ms (OperationDuration)__ 11.8
default	21:55:51.451153+0100	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: Autoupdate__WSWindow__WSWindowDrag __ms/frame (AverageDuration)__ 1.5
default	21:55:51.451318+0100	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: Autoupdate__WSWindow__WSWindowDrag __ms/frame (StandardDeviation)__ 0.0
default	21:55:51.451373+0100	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: Autoupdate__WSWindow__WSWindowDrag __ms (DelayFromOperationStart)__ 1.8
default	21:55:51.451464+0100	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: Autoupdate__WSWindow__WSWindowDrag __frames (IntervalCount)__ 1.0
default	21:55:51.451508+0100	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: Autoupdate__WSWindow__WSWindowDrag **** Slow WS Update data ****
default	21:55:51.451539+0100	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: Autoupdate__WSWindow__WSWindowDrag __updates (Slow WS Update count)__ 0
default	21:55:52.431190+0100	runningboardd	Invalidating assertion 450-264-1310 (target:executable<Autoupdate(501)>) from originator 264
default	21:55:52.540576+0100	runningboardd	[executable<Autoupdate(501)>:45791] Ignoring jetsam update because this process is not memory-managed
default	21:55:52.540693+0100	runningboardd	[executable<Autoupdate(501)>:45791] Set darwin role to: UserInteractive
default	21:55:52.540970+0100	runningboardd	[executable<Autoupdate(501)>:45791] Ignoring GPU update because this process is not GPU managed
default	21:55:56.245850+0100	Autoupdate	LSExceptions shared instance invalidated for timeout.
default	21:56:16.452811+0100	hidd	Connection added: IOHIDEventSystemConnection uuid:9BA08397-8D00-4D23-9827-011997AEFB8D pid:45791 process:Autoupdate type:Passive entitlements:0x0 caller:HIServices: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1 events:0 mask:0x0
default	21:56:16.979127+0100	hidd	Connection removed: IOHIDEventSystemConnection uuid:9BA08397-8D00-4D23-9827-011997AEFB8D pid:45791 process:Autoupdate type:Passive entitlements:0x0 caller:HIServices: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1 events:0 mask:0x0
default	21:56:16.979182+0100	hidd	Connection removed: IOHIDEventSystemConnection uuid:C6339340-24FE-4317-89C4-591D151FE93E pid:45791 process:Autoupdate type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1 events:0 mask:0x0
default	21:56:16.983280+0100	runningboardd	[executable<Autoupdate(501)>:45791] Death sentinel fired!
default	21:56:16.986948+0100	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Autoupdate, _appTrackingState = 2
default	21:56:16.987265+0100	runningboardd	Invalidating assertion 450-264-1308 (target:executable<Autoupdate(501)>) from originator 264
default	21:56:17.093051+0100	runningboardd	Removing process: [executable<Autoupdate(501)>:45791]
default	21:56:17.093636+0100	runningboardd	Removing assertions for terminated process: [executable<Autoupdate(501)>:45791]
error	21:56:17.101715+0100	runningboardd	RBSStateCapture remove item called for untracked item 450-264-1308 (target:executable<Autoupdate(501)>)

**Comment by 01CGAT** [comment]
Does anyone have an idea in what direction I should look for to solve this problem?

**Comment by kornelski** [comment]
Can you pause the application in the debugger to see what it is waiting for?

Does it waiting for the old app to quit? Is the launch of the new app taking that long?

**Comment by 01CGAT** [comment]
A firewall rule was the cause. To keep the user safe while my VPN app exited for an update after which it would reconnect to a VPN server again, I had setup firewall rules to prevent any leaking of data. When removing the firewall rules the updates are going smoothly again. 
Maybe an idea to show a message when the internet connection is lost during an update after some short timeout, like 5 seconds.

**Comment by 01CGAT** [comment]
Oh, I didn't mean to close this issue yet.

**Comment by 01CGAT** [comment]
I'm wondering btw, is it possible to somehow add a script in the new downloaded update which gets executed before anything else? This way I could edit firewall rules before the real update process starts.

**Comment by kornelski** [comment]
Sparkle doesn't have APIs for running code after update. Relying on such logic could create a behavior that is not compatible with app updates done by users manually (without Sparkle). I recommend just checking on startup whether the app needs to initialize anything.

**Comment by 01CGAT** [comment]
Thank you, I will close the issue now as my questions are answered.
