### ISSUE TITLE
Support for `package.swift`?

### ISSUE THREAD

**Issue by CharlesJS** [sparkle-project/Sparkle#1506]
Are there any plans to add support for `package.swift` to the Sparkle repo, so that it can be used via the Swift Package Manager? The CocoaPods support is nice, but the Swift PM is much more convenient to use from Xcode.

**Comment by kornelski** [comment]
As far as I can tell, Swift Package Manager completely forbids havin any ObjC code, so Sparkle is not allowed to use it.

**Comment by CharlesJS** [comment]
This is not true:

https://developer.apple.com/documentation/swift_packages

> Swift packages are reusable components of Swift, Objective-C, Objective-C++, C, or C++ code that developers can use in their projects.

**Comment by CharlesJS** [comment]
What does appear to be true (for now) is that Swift and Objective-C can't be combined within a single Swift package, but you can work around that by breaking the Objective-C parts out and using dependencies:

https://medium.com/@joesusnick/swift-package-manager-with-a-mixed-swift-and-objective-c-project-part-1-2-19fbb43d0460

**Comment by sindresorhus** [comment]
You *can* mix Swift and Objective-C in the same package, but not in the same target. So you can have a Swift target that depends on the Objective-C target. 

Example: https://github.com/sindresorhus/ExceptionCatcher/blob/b5eb74b6c9e01cf51c3619928abdb13af4a73505/Package.swift#L20-L29 (The `Internal` target there is the Objective-C part)

**Comment by sindresorhus** [comment]
@kornelski Would you accept a PR that adds support for the Swift Package Manager?

**Comment by kornelski** [comment]
Yes, I'd love to.
