### ISSUE TITLE
Send to Apple notary service, Notarization issue?

### ISSUE THREAD

**Issue by zsh7887** [sparkle-project/Sparkle#1507]
Developer ID - Send to Apple notary service 
![708B2A326784E4249A4B00D4A6FAA2DB](https://user-images.githubusercontent.com/16081449/69607392-20b72600-1060-11ea-892a-2e77deba6f58.jpg)
Autoupdate.app no Profile.

![9A0FDC0AFC27255B860C17D195BF8765](https://user-images.githubusercontent.com/16081449/69607514-5c51f000-1060-11ea-88d1-f9d7187d046f.jpg)
Upload failure.

**Comment by kornelski** [comment]
Try signing the Autoupdate app with your ID.

**Comment by zsh7887** [comment]
How to operate？
I am like this ：
`pod install`
