### ISSUE TITLE
Idea: add custom NSURLSession for downloader

### ISSUE THREAD

**Issue by Odirb** [sparkle-project/Sparkle#1509]
Since the implementation of the new SPDownloaderSession, it's not possible anymore to register a subclass of NSURLProtocol via registerClass method.

My idea is to add an optional NSURLSession property to the SUUpdater object, that will be used in the startDownloadWithRequest function to create the downloadSession.

Do you think my solution acceptable? If so I will try to implement it and send a PR.

**Comment by kornelski** [comment]
I did not realize it was possible before. What's the use-case for this?

**Comment by Odirb** [comment]
Your question is very relevant.
I took over a project I didn't write myself, and I discover that the NSURLProtocol was use as a hack to use Sparkle without sending http requests (update rules are managed on the server side).

So basically my need is to skip Appcast rss and zip update download, but keep other steps (extract, validation and install with tools). I found the issue https://github.com/sparkle-project/Sparkle/issues/155 with a similar demand, but it didn't seems to be implemented so far.

**Comment by kornelski** [comment]
I see it would be useful to split Sparkle to allow use of part of its functionality, but unfortunately that's more work than I can spare for Sparkle, so it probably won't happen anytime soon.

If you'd like to dynamically control Sparkle's behavior from the server, I suggest generating appcast XML dynamically. It doesn't have to be a static file.
