### ISSUE TITLE
xcodebuild on .gitlab-ci.yml failed

### ISSUE THREAD

**Issue by stackJolin** [sparkle-project/Sparkle#1517]
I invoke Sparkle by cocoapods，when I push code to remote(CI server)，xcodebuild failed。please help me。Here is my .yml code:
```
- xcodebuild -workspace CSC-OSX/CSC-OSX.xcworkspace CODE_SIGN_IDENTITY="-" -scheme CSC-OSXTestScheme test | xcpretty
```

and error info:
![image](https://user-images.githubusercontent.com/14361098/70793301-f393a300-1dd5-11ea-8a46-70050bebb923.png)

**Comment by kornelski** [comment]
Are you sure it's a Sparkle problem? I don't see anything Sparkle-related in the log.
