### ISSUE TITLE
EdDSA issues with new setup

### ISSUE THREAD

**Issue by crewshin** [sparkle-project/Sparkle#1521]
### Description of the problem
AppCast seems to work fine. My app downloads the app and prompts the user to install. This is where it fails.

### Do you use Sandboxing in your app?
10.14 deploy target created with Xcode 11.2.1. I believe sandboxing is the only way apple allows at this point.

### Version of `Sparkle.framework` in the latest version of your app
1.22.0 installed via cocoapods

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
1.22.0 installed via cocoapods. The app is unreleased at this point so all versions can have the same sparkle setup.

### Sparkle's output from Console.app
```
There is no DSA signature in the update
There is no EdDSA signature in the update, but the app is capable of verifying them
The update has a public (Ed)DSA key, but the public key shipped with the update doesn't match the signature. To prevent future problems, the update will be rejected.
Error: An error occurred while extracting the archive. Please try again later. The update is improperly signed. (URL (null))
Sandbox: logd(126) System Policy: deny(1) file-read-data /Users/meeee/Downloads/Sparkle-1.22.0/bin/generate_appcast
```

I also tried building and distributing the app without the EdDSA in the Info.plist because I am signing the app with an apple `development` profile. When I did that I got some different console results.

```
Launch path not accessible
Then it seems to crash and hang with some PerfLogging... frame data stack trace info.
``` 

### Steps to reproduce the behavior
This app is unreleased so to test this... I'm archiving with `development` via the organizer for *both* versions old and new (same version just different version numbers). Uploading my appcast and new version to S3 and testing the update.

In my `Info.plist` file I've included the `SUFeedURL` which points to my S3 hosted AppCast file. This obviously contains a link to the .zip which is also hosted on S3 in the same bucket. I've also included the `SUPublicEDKey` key and it's corresponding public key value but honestly it would be nice to omit this since I'm signing with my apple account and don't want to deal with moving/sharing that private key around the office.

**Comment by kornelski** [comment]
Sparkle 1.x will not work with sandboxing at all. 

If your app is sandboxed, you must use the beta version of Sparkle 2.x instead. Sparkle 2.x doesn't have EdDSA keys yet.

If the issue is just about signing, use `generate_appcast` app which ensures all signatures are correctly inserted.

**Comment by crewshin** [comment]
Ok I just removed sandboxing from the project (didn't know that was a possibility these days). Re-tried with 1.22 and same issue.

```
There is no DSA signature in the update
There is no EdDSA signature in the update, but the app is capable of verifying them
There is no DSA signature in the update
The update has a public (Ed)DSA key, but the public key shipped with the update doesn't match the signature. To prevent future problems, the update will be rejected.
Error: An error occurred while extracting the archive. Please try again later. The update is improperly signed. (URL (null))
```


Fwiw, I pointed cocoapods to the 2.x branch and it pulled **1.20** for some odd reason. Didn't like the look of that so I tried again with the above ^

**Comment by kornelski** [comment]
The log looks like a complete failure to add any sort of signature. 

Did you follow installation instructions? Does the app in the update archive have required Sparkle config keys in Info.plist?

Does `generate_appcast` tool work with your updates? I strongly recommend using `generate_appcast` to verify that the archive is correct and the appcast is well-formed.

**Comment by crewshin** [comment]
Ok I got it. I was screwing up by not having the "sparkle:edSignature=" key in the **OLD** version in the AppCast. Thanks for the help!
