### ISSUE TITLE
Issue when using the sparkle framework from 'ui-separation-and-xpc' branch with App Sandbox

### ISSUE THREAD

**Issue by KumarRajith** [sparkle-project/Sparkle#1533]
HI,

I have an issue when using the sparkle framework from ui-separation-and-xpc branch with App Sandbox

1.I have dragged the entire sparkle project into my application.
![Screenshot 2020-01-16 at 3 32 39 PM](https://user-images.githubusercontent.com/59958086/72516445-b3fa2400-3877-11ea-999c-f3f40ef62adc.png)

2.Added The XPC Service in dependencies
![Screenshot 2020-01-16 at 2 57 04 PM](https://user-images.githubusercontent.com/59958086/72516487-c4aa9a00-3877-11ea-84c5-582b23f18d5a.png)

3.Created a file phase and added the XPC Services
![Screenshot 2020-01-16 at 2 58 58 PM](https://user-images.githubusercontent.com/59958086/72516518-d12ef280-3877-11ea-9cd2-f72254878d26.png)

4.Added Run Script
![Screenshot 2020-01-16 at 3 37 24 PM](https://user-images.githubusercontent.com/59958086/72516538-d9872d80-3877-11ea-83d7-456099b86546.png)

5.Added below line of codes in AppDelegate to check for update

Added the delegates SPUUpdaterDelegate,SPUStandardUserDriverDelegate

        let updaterNew = SPUStandardUpdaterController.init(updaterDelegate: self, userDriverDelegate: self)
        updaterNew.updater?.automaticallyChecksForUpdates = true
        updaterNew.updater?.checkForUpdatesInBackground()

When running the application  I am getting Time Out issue
Please advice me to find out the mistake I have done, any extra thing have to do to get it working.

Branch: ui-separation-and-xpc
Xcode: 11.1
macOS: 10.15.2

Log:
[Sparkle] Timed out while probing installer progress

**Comment by edualm** [comment]
I am having the same problem on the `2.x` branch.

Is this a known issue / has a known fix?

**Comment by vuvantoan95** [comment]
@KumarRajith  How did you fix it?

**Comment by zorgiepoo** [comment]
This caveat pertaining to when debugging in Xcode is now documented in https://sparkle-project.org/documentation/sandboxing/ under "Testing" (and has other setup info)
