### ISSUE TITLE
How to migrate from old DSA Sparkle version to the new EdDSA Sparkle version

### ISSUE THREAD

**Issue by mbsanchez** [sparkle-project/Sparkle#1536]
I'm trying to updated Sparkle from version 1.19 to version 1.22, however when i tried to sign the installer file i've got this message.

> Usage: ../../Sparkle/bin/sign_update <archive to sign>
> Privavte EdDSA (ed25519) key is automatically read from the Keychain.

I was researching about this issue and I found that Sparkle changed its sign method from DSA to EdDSA. However, it seems that you didn't provide enough information about how to migrate current applications using the old Sparkle version to the new one. Moreover some users say that we must generate a new EdDSA key, and add several appcast.xml files in order to accomplish the migration process.

Can you explain a simple way to migrate my application? I think that the method commented in https://github.com/sparkle-project/Sparkle/issues/1355 could have many problems. For instance, if a user have many days without using the application, when he opens it the update will fail.

Thank you in advance!

**Comment by rgbworld** [comment]
Please explain what needs to be included in a _transitional.xml_ file. Per the documentation 

> both DSA and EdDSA may be used together

What exactly needs to be in the _transitional.xml_ file to accommodate both DSA and EdDSA? 

Specifically, is it required to include:
- 2 `<enclosure>` elements?
- 2 complete `<rss>` elements?
- 2 signature attributes (`sparkle:dsaSignature` and `sparkle:edSignature`) ?

My migration plan is to use the same `SUFeedURL` in _all_ versions of my app and then use `header("Location: ".$appcast_url);` to redirect to the actual `appcast.xml` depending on the version of the app performing the update request.

For applications in the wild (containing only DSA key), I plan to redirect to _transitional.xml_ which will have both signature attributes and deliver a _transitional.app_. The _transitional.app_ will contain both `SUPublicDSAKeyFile` and `SUPublicEDKey` keys in app's info.plist. 

When the _transitional.app_ checks for updates, it will redirect to _modern.xml_ that contains only `sparkle:edSignature` and deliver _modern.app_. The _modern.app_ will contain only `SUPublicEDKey`, and when checking for updates, the request will be redirected to _modern.xml_

It seems that only 2 apps are required (besides the app that is already distributed). _Transitional.app_ and _Modern.app_. Is this the recommended migration approach?

Thank you!

**Comment by rgbworld** [comment]
I managed to answer my own question via trial and error. In order to support _both_ DSA and EdDSA signatures in a single appcast.xml file, it is only necessary to include both `sparkle:dsaSignature` and `sparkle:edSignature` in the `enclosure` tag.

This makes the most sense. It allows for a single `enclosure` node that contains both signatures without having to duplicate other nodes/tags.

Thank you!

**Comment by zorgiepoo** [comment]
We have website documentation on migration now.
