### ISSUE TITLE
Cloned Vendor directory ed25519 is empty and 10 Warnings

### ISSUE THREAD

**Issue by pteeson** [sparkle-project/Sparkle#1537]
Xcode 9.2, macOS Sierra 10.12.6
I am using Kurt Revis MIDIApps workspace and found 10 Warnings in Sparkle, See attached.
[Sparkle Warnings.txt](https://github.com/sparkle-project/Sparkle/files/4099874/Sparkle.Warnings.txt)

Digging into this I forked and cloned the Sparkle project. The cloned project directory Vendor/ed25519 is empty. When I looked at the Sparkle source Vendor dir I saw this:
 	ed25519 @ 7fa6712 Move ed25519 dependency to the Vendor directory

Q1: Is this why the contents were not  cloned?
Q2: Why are there the above Warnings in the MIDIApps build of Sparkle?

**Comment by kornelski** [comment]
You need to clone with `--recursive` or run `git submodule init`.

**Comment by pteeson** [comment]
Thanks for then answer to Q1 - still newish to Git
I redid the clone and compared the contents of the cloned ed25519 dir and the one in the MIDIApps WS.  They are identical..

Re Q2: Don't understand the meaning of the Warnings. 
Nor what to do about them. Of course I can ignore them.
But why not try to fix them?

**Comment by kornelski** [comment]
These warnings are harmless and are due to Xcode being told to compile .h files. I don't know why you're getting these. Did you add any files manualy?

**Comment by pteeson** [comment]
No all I did was download the entire MIDIApps WS and build the two  applications.
They both use Sparkle to update. Prior to doing the build step I followed the instructions to 
git submodule update --init --recursive.

I contacted Mr Revis with the issues and he said I could ignore them and that it might be a Sparkle configuration issue.

I'm long retired from SW dev but like to keep my hand in and learn things. So I thought to dig into this and see if I could get rid of the warnings.

Should I look at the Xcode Build settings for Sparkle as the place where it's told to compile the .h files?  Or would it be elsewhere in Sparkle?

**Comment by pteeson** [comment]
The problem is that there are .h files in the Build Phases. Thank you stackoverflow:
"Click on your project, and check that this file is not present in the tab Build Phases. Normally no header files should stay here. Clean and build it again, it should work!"

Since I have a clone of Sparkle all setup I'll checkout, setup upstream, origin, create a branch, make and test, and file a pull request.

Thanks for your patience....

**Comment by pteeson** [comment]
All done and pill request filed

**Comment by pteeson** [comment]
Closing this thread since pull request has been merged.
Thanks to Kornelski
