### ISSUE TITLE
There is no (Ed)DSA signature in the update, but the app is capable of verifying them

### ISSUE THREAD

**Issue by strudra** [sparkle-project/Sparkle#1541]
### Description of the problem

I went through all the steps from the website. I archived the app, compressed it, published the appcast configuration AND downloaded the Sparkle and ran the `sign_update` utility after getting the keys from `generate_keys` utility. Please note that I haven't used any of other targets (I had issues with them, for example with Distribution target). I wrote my own appcast.

I also have SUPublicEDKey set in Info plist.

### Do you use Sandboxing in your app?

No

### Version of `Sparkle.framework` in the latest version of your app

1.22.0

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)

N/A

### Sparkle's output from Console.app

Mentioned above
```
App[48557:1599362] [Sparkle] There is no EdDSA signature in the update, but the app is capable of verifying them
App[48557:1599362] [Sparkle] There is no DSA signature in the update
App[48557:1599362] [Sparkle] There is no EdDSA signature in the update, but the app is capable of verifying them
App[48557:1599362] [Sparkle] There is no DSA signature in the update
App[48557:1599362] [Sparkle] The update has a public (Ed)DSA key, but the public key shipped with the update doesn't match the signature. To prevent future problems, the update will be rejected.
```

**Comment by kornelski** [comment]
You haven't put the signature in your appcast (or you've put it with invalid syntax).

Try `generate_appcast` tool. It signs things correctly.

**Comment by strudra** [comment]
When I try to run `generate_appcast` it gives me how I should use it (`generate_appcast ./my-app-release-zipfiles/`), but `gemerate_appcast` from terminal is not in scope. Where to specify the argument?

**Comment by strudra** [comment]
@kornelski I managed to solve it by correcting this appcast.xml file. I will close the issue.

**Comment by kornelski** [comment]
You use full path to the executable. You can drag'n'drop it from Finder to Terminal
