### ISSUE TITLE
Update error - An error occurred while relaunching.

### ISSUE THREAD

**Issue by kennethjohnsen** [sparkle-project/Sparkle#1542]
# Description of the problem

I get "Update error. An error occurred while relaunching MYAPP, but the new version will be available next time you run MYAPP." after the new version has been downloaded, when I click "Install and relaunch".

However, the app has not been updated when I relaunch it.

I cannot find any info in Console.app. The only two lines I can find, are in "Log reports" and then "SparkleUpdateLog.log", and those are very old:

2019-11-05 07:03:32 +0000: ===== Autoupdate =====
2019-11-05 07:03:32 +0000: mdimporting

### Do you use Sandboxing in your app?

No.

### Version of `Sparkle.framework` in the latest version of your app
1.22

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
1.22

### Sparkle's output from Console.app

No output in Console.app.

**Comment by kornelski** [comment]
I'm not sure what happens there. Maybe try adding more logging to the code?

**Comment by kennethjohnsen** [comment]
I found the error. There was actually some info in Console.app: "Sparkle.framework is damaged, Autoupdate is missing.", which indeed it was.
After building Sparkle again, it works. My mistake...
I am closing the issue.
