### ISSUE TITLE
Raise Minimum macOS Version for 2.x?

### ISSUE THREAD

**Issue by bdkjones** [sparkle-project/Sparkle#1546]
Issue #1510 mentioned that Sparkle 2.x is set to support macOS 10.9+

I'm suggesting that this minimum version be raised before 2.x officially launches. There are several reasons:

1. 97.39% of Mac users are running a version newer than 10.9: https://gs.statcounter.com/macos-version-market-share/desktop/worldwide Raising the target to 10.12+ would cover 87.88% of users.

2. Bumping the minimum macOS version eases development because newer APIs become available, such as the improved webView replacement, block-based APIs that provide neater encapsulation.

3. Apps that wish to support older versions of macOS will always have the 1.x legacy version of Sparkle to rely on until they raise their own minimum deployment target.

4. Once 2.x is made official, dropping support for older releases of macOS becomes a very, very tough thing to do.

**Comment by kornelski** [comment]
Agreed.
