### ISSUE TITLE
2.x Build Retains Wrong 1.x Version Number

### ISSUE THREAD

**Issue by bdkjones** [sparkle-project/Sparkle#1547]
When running `make release` on the `2.x` branch, I was surprised to see a Finder window open with `Sparkle-1.20.0.tar.bz2` highlighted. Inspecting the `info.plist` in the compiled Framework, it lists the old 1.x version number as well.

**Comment by bdkjones** [comment]
The Framework contains the new `SPU` prefixed headers, so I assume it built the 2.x branch correctly. It would be very embarrassing if I just built the wrong branch...

**Comment by kornelski** [comment]
Just an oversight
