### ISSUE TITLE
Sparkle 1.22.0 doesn't contain the private key arg in sign_update

### ISSUE THREAD

**Issue by lwouis** [sparkle-project/Sparkle#1548]
### Description of the problem

Release 1.22.0 release notes says:

> Support providing private key as argument (Yakuhzi)

However, the release was made on Sep 22, and the commit that adds the arg is from Oct 18, so it's pretty clear that it's missing. Here is the commit I need: https://github.com/sparkle-project/Sparkle/commit/531b767c0b070acc5ef544c7f77eee28e0344dcb

I tried to use `pod 'Sparkle', :git => 'https://github.com/sparkle-project/Sparkle.git', :commit => '531b767'` but the `bin` directory contains only a bogus `old_dsa_scripts/sign_update`.

Should I wait for 1.23.0? What's the ETA for that version? Otherwise would you recommend I use the 2.x branch?

Thank you!

**Comment by kornelski** [comment]
I've released 1.23.0 now.

**Comment by lwouis** [comment]
Wow what a fast reply and solution! Thank you very much @kornelski! I think it fixed my issue :)
