### ISSUE TITLE
Stop this Auto-update not configured popup

### ISSUE THREAD

**Issue by Mizzlr** [sparkle-project/Sparkle#1549]
I want to stop this pop up on my mac. It periodically occurs throughout the day on my mac with frequency of twice every hour.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/8148804/74272007-e4789500-4d33-11ea-9602-0316fd321be6.png">

It tried this but clueless what to do with sign_update
<img width="844" alt="image" src="https://user-images.githubusercontent.com/8148804/74272066-007c3680-4d34-11ea-80d3-b5cd7452b54c.png">

I found these apps on my mac have/use Sparkle.framework
<img width="688" alt="image" src="https://user-images.githubusercontent.com/8148804/74272119-12f67000-4d34-11ea-9cff-d70d3b606400.png">

I had recently installed kite for mac.
https://kite.com/

It uses Sparkle.framework, please see ther dmg file https://kite.com/download/

I was fed up of how crappy kite is. Firstly is slows all my IDEs, Atom, Intellij and Pycharm. Secondly I can't seem to cleanly uninstall the plugins from my IDE. I feels like a virus on my mac.

So I had searched every file that was about kite and removed it.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/8148804/74272687-12120e00-4d35-11ea-90c7-9926bfed69de.png">

Since then this pop up keeps coming. It bother me and goes away on clicking OK. What is the point of this?

I guess it has to do with the some improper/violent removal of files. Really the message in the doesn't help.

**Comment by Mizzlr** [comment]
By the way, I tried following this whole discussion here https://github.com/sparkle-project/Sparkle/issues/1149

Still not clear how to find out what to do? What is the message is the pop up really about talking about.

As you could guess I am a developer, but not an expert in Objective-C or Sparkle.framework. Any help here is much appreciated.

**Comment by Mizzlr** [comment]
I had created an issue with kite as well here https://github.com/kiteco/plugins/issues/173

I really don't know where is the problem or whose fault it is. Sparkle.framework or kite. 😞

**Comment by miclgael** [comment]
+1!
This sucks. I had no idea what this pop-up was coming from until I saw this issue and that you mention kite. holy smokes.

**Comment by EmilStenstrom** [comment]
I've been getting this popup too. Time to throw away Kite!

**Comment by kornelski** [comment]
This has been fixed in the latest version of Sparkle. We don't have a time machine, so we can't fix this message in your old app.
