### ISSUE TITLE
My key reset by generate_key，old key is different to new key，update failed

### ISSUE THREAD

**Issue by stackJolin** [sparkle-project/Sparkle#1552]
My key reset by generate_key，old key is different to new key，update failed

How I can deal with it

**Comment by stackJolin** [comment]
@kornelski 
My mac machine's key was reset by generate_key，the online's public key is not equal to the latest version，'update' failed，how I can do?

**Comment by stackJolin** [comment]
@andreb 
Help me，if the old key is reset , old software how to autoupdate

**Comment by kornelski** [comment]
Were you using DSA keys or EdDSA keys? 

Do you have backups? 

Try sending update without (Ed)DSA signature at all. If Apple Code Signing identity will match, it will still allow an update.

Otherwise there's no way. You're locked out.

**Comment by stackJolin** [comment]
> still

I use EdDSA keys。How to find backups? how to find generate_keys's output?

I sending update without set EdDSA signatrue in appasset.xml，but get "unarchive" error

**Comment by stackJolin** [comment]
> Were you using DSA keys or EdDSA keys?
> 
> Do you have backups?
> 
> Try sending update without (Ed)DSA signature at all. If Apple Code Signing identity will match, it will still allow an update.
> 
> Otherwise there's no way. You're locked out.

I use EdDSA keys。How to find backups? how to find generate_keys's output?

I sending update without set EdDSA signatrue in appasset.xml，but get "unarchive" error

**Comment by kornelski** [comment]
The key is stored in your Login keychain. If you have backup of your home directory's ~/Library/Keychains, you can get the key from an old login.keychain file.

**Comment by kornelski** [comment]
BTW: EdDSA `generate_keys` does **not** overwrite the key, so it's likely that you have the right key, you just didn't configure it correctly.

**Comment by stackJolin** [comment]
> BTW: EdDSA `generate_keys` does **not** overwrite the key, so it's likely that you have the right key, you just didn't configure it correctly. If you use `generate_appcast` tool, it will sign correctly for you.

Yes，But I delete the EdDSA public pwd from keychain because of misoperation, and I can't find it from old.keychain-db。
