### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#1556]
I don't have enough energy to give this project attention it needs. I'm also mostly developing in Rust these days, so Sparkle doesn't "scratch my itch" any more.

This project is quite important for security and health of non-walled-garden apps for macOS.

I need your help in getting Sparkle 2 out of the door.

**Comment by Frizlab** [comment]
I might be able to help, though my time is limited. What should I start with?

**Comment by Wevah** [comment]
I’m also willing to help, though I’m also not sure how much of the whole load I could take on.

**Comment by michelf** [comment]
Regarding the work to do, this looks like a good place to start with:
https://github.com/sparkle-project/Sparkle/issues/1523

Right now the 1.x and 2.x branches (2.x was formerly ui-separation-and-xpc) have diverged, and continuing to accept pull requests on both is contributing to this divergence. I think making 2.x the official one should be the priority so future efforts from occasional contributors are not split in two.

**Comment by mRs-** [comment]
I will talk to my "Boss" about this. Maybe I can spent some time to maintain this repository in my work time. We would like to switch from Squirrel anyway.

**Comment by kornelski** [comment]
Thank you for offering help.

Indeed, the next step is to make Sparkle 2.x feature-complete and production-ready.

**Comment by Deadpikle** [comment]
I don't have time to help out here, unfortunately, but I do want to thank you, @kornelski, for maintaining this project over the years. Thank you for all you've done, here! 👏

**Comment by mbasaralusrinivasa** [comment]
Happy to help!

**Comment by burgerbecky** [comment]
I’d be happy to maintain this.

**Comment by burgerbecky** [comment]
I'm on it!
