### ISSUE TITLE
generate_appcast should invalidate cache better

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#1559]
Currently generate_appcast extracts bundles to a folder per version, but that breaks it when developers try to re-release the same version. 

Instead, it should use hash of the archive file as the unarchiving folder name, so that any change to the archive updates the appcast.

**Comment by Wevah** [comment]
What hash do we want to use? SHA256?

**Comment by Wevah** [comment]
Also, you can assign this to me. 🙂

**Comment by Wevah** [comment]
Alternatively, we could clean up the caches folder when we're done.

**Comment by kornelski** [comment]
Caches are there to make multiple runs faster, so cleaning them after one execution would be counterproductive.

But the sha fix should be good enough.

**Comment by Wevah** [comment]
> Caches are there to make multiple runs faster, so cleaning them after one execution would be counterproductive.
> 
> But the sha fix should be good enough.
Gotcha.
