### ISSUE TITLE
updateInProgress SUUpdater is giving false positive

### ISSUE THREAD

**Issue by prasann-1433** [sparkle-project/Sparkle#1560]
We have a mac app and has been using sparkle from a long time, so far we have been using the old version 1.14.0. So we thought of upgrading to 1.23.0 the latest version. Everything seems to be working fine except one issue, which i got while testing the app with latest sparkle. 

During the background update, Sparkle is not able to pull the updated build from server. The reason being `checkForUpdatesWithDriver` has a check `if [self updateInProgress]` then return. 

So i debugged further to code and found that, this is getting me false positive for a previous request which has already been completed. 

ex: First call we make is to get `checkForUpdateInformation` to get the version of our app and to see if its needs an update. And then we call `checkForUpdatesInBackground` when we have checked the version and we find we need to do a background update. 

Now when first call is made i.e  `checkForUpdateInformation` even though it responds back to delegate and the second call is happening immediately the flag `updateInProgress` is not yet re-set. Now if i add a delay to second call say 1 sec, it finds the flag to be reset and worked fine this time and download and update my app with latest build. 

I think framework should provide a mechanism by which app can know if the  `updateInProgress` is been reset so that next call can be made. Otherwise we need to keep on polling the status of `updateInProgress` and then make a next call which i feel is not a good way of development. 

Thanks 
Prasann

**Comment by prasann-1433** [comment]
any updates on this please..

**Comment by zorgiepoo** [comment]
These methods in Sparkle 2 should help:

[-[SPUUpdater sessionInProgress]](https://sparkle-project.github.io/documentation/api-reference/Classes/SPUUpdater.html#/c:objc(cs)SPUUpdater(py)sessionInProgress)
[-[SPUUpdaterDelegate updater:didFinishUpdateCycleForUpdateCheck:error:]](https://sparkle-project.github.io/documentation/api-reference/Protocols/SPUUpdaterDelegate.html#/c:objc(pl)SPUUpdaterDelegate(im)updater:didFinishUpdateCycleForUpdateCheck:error:)
