### ISSUE TITLE
How to set app icon in the alert view?

### ISSUE THREAD

**Issue by NathanYu1124** [sparkle-project/Sparkle#1562]
Sorry to bother you! I will appreciate it if you can tell me how to set the app icon in the alert view. I use Sparkle in my application and it works well. But the icon of the alert view is nil and I can't find the tutorial in the documents of Sparkle. I hope you can give me a hint, thank you in advance.

**Comment by kornelski** [comment]
You don't set it. It's supposed to automatically copy your app's icon.

**Comment by NathanYu1124** [comment]
> You don't set it. It's supposed to automatically copy your app's icon.

The icon appears on the alert view after I set all the app icon of different size. Thank you for your answer and your wonderful Sparkle framework.

**Comment by macrael** [comment]
To be explicit, Sparkle uses "Mac 128pt" icon for its alert views, if you don't have one set it will display a blank document.
