### ISSUE TITLE
[Question] Is Sparkle needed if I publish my app on the Apple App Store?

### ISSUE THREAD

**Issue by rampatra** [sparkle-project/Sparkle#1563]
Pardon me for asking a trivial question. I am completely new to Mac OS app development. I was wondering whether I need to use Sparkle or similar libraries if I plan to publish my app on the official mac app store?

I am asking because I do have some Android apps on the play store and they take care of all the future updates, etc. without me worrying about it.

Appreciate your help.

**Comment by jeff-h** [comment]
No, you'll only need Sparkle if you intend to ship outside the MAS.

**Comment by rampatra** [comment]
Thanks a lot for the clarification, Jeff.
