### ISSUE TITLE
Sparkle can't parse release note html file

### ISSUE THREAD

**Issue by NathanYu1124** [sparkle-project/Sparkle#1564]
I write a release note html file and it could show the content rightly on my computer. Then I use a github respository to save the html file and appcast.xml file. However, the alert view can't parse the html file and it only shows the source code of the html file.  What should I do to solve the problem?

<img width="622" alt="bug" src="https://user-images.githubusercontent.com/24695525/77243631-3839a080-6c47-11ea-9a56-f4c83c12b109.png">

**Comment by jeff-h** [comment]
If it's not private, could you post the URL of your HTML file here?

**Comment by NathanYu1124** [comment]
> If it's not private, could you post the URL of your HTML file here?

Here is the url of my html file: https://raw.githubusercontent.com/NathanYu1124/TempServer/master/updates/2.0.1.html

**Comment by Wevah** [comment]
It's because the `Content-Type` is sent as `text/plain` when you use the GitHub raw URL. A quick fix could be to host the page on a github.io site (or elswhere).

**Comment by NathanYu1124** [comment]
> It's because the `Content-Type` is sent as `text/plain` when you use the GitHub raw URL. A quick fix could be to host the page on a github.io site (or elswhere).

Thanks for your answer and I will put the release-note html file on a commercial server when I finish my project. For now, I find another solution to the problem. When I insert the html code in the [!CDATA] label of appcast.xml file and it works well.  “Bug” fixed! 😄
