### ISSUE TITLE
Sparkle 1.22.0rc1 integration for delta results in failed subsequent delta updates

### ISSUE THREAD

**Issue by cocoadev03** [sparkle-project/Sparkle#1565]
Sparkle Issue with Delta Update
Premise : 
We have a mac app which uses Sparkle to do subsequent updates. With the release of Delta Capabilities inside Sparkle, we decided to integrate delta update with our App. As we started testing, we find a very interesting observation that, after the first update, the subsequent delta updates are failing. 

Delta Creation : 
Binary Delta tool v-2.2

To create the delta, we code sign the new to build and download the previous build that we want as a from build using the full download of its own appcast release. Then use these two to create deltas of each other, and create the EDDSA signature of the delta, and host both of them and specifying the downloads in the new to build's appcast. in order to create the deltas from the two builds, we use the BinaryDelta tool from the same code base that the client framework is using to ensure there is no version miss match.

However, while creating a delta diff on our servers, we get following error : 

Diffing code signed extended attributes are not supported. Detected extended attribute in after-tree on file ../TestApp.app/Contents/Frameworks/InternalFramework.framework/Versions/A/XPCServices/com.testApp.InternalFramework.internal-service.xpc/Contents/Frameworks/somecrypto.a

Issue : 
With the integration of new sparkle framework release (1.22.0rc1) in our project we enabled delta update for our app. The delta update works fine the first update but the subsequent updates, fail all the time.

The error give out is : 
Source doesn't have expected hash (be4615cf1a97779f9d0da0c924e6e33aaa0fd747 != 3263ca5b92039d3d635b31b384ee8d5f3d527a86).  Giving up

We traced this issue to source code(SUBinaryDeltaApply.m) which is throwing this error and found that the check is basically around the mis-match of the source file on which this delta is being applied.

Debugging some more and we found that the source package(delta to be applied on) does not have following directories/files : 
_CodeSigning
embeddedProvisioning Profile
CodeResources

Question : 
Is this an intended behavior for delta update? 
Do we need to run a command to code sign the delta update to restore or maintain CodeSigning?

### Do you use Sandboxing in your app?
No

### Version of `Sparkle.framework` in the latest version of your app
Yes

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
1.22.0rc1

### Sparkle's output from Console.app
Source doesn't have expected hash (be4615cf1a97779f9d0da0c924e6e33aaa0fd747 != 3263ca5b92039d3d635b31b384ee8d5f3d527a86).  Giving up.

### Steps to reproduce the behavior
Integrate Sparkle framework with the app 
Generate v1.0 & v2.0 create deltas for the update patch.delta
Successfully apply patch.delta on v1.0 
Generate v3.0 and create delta between v2.0 & v3.0 as patch1.delta
Apply patch patch1.delta on v2.0

### Expected Result
The subsequent update works fine and applies correctly

### Observed result 
The subsequent update form v2.0 -> v3.0 fails with following error : 
Source doesn't have expected hash (be4615cf1a97779f9d0da0c924e6e33aaa0fd747 != 3263ca5b92039d3d635b31b384ee8d5f3d527a86).  Giving up.

**Comment by kornelski** [comment]
Apple's code signing has two ways of operation: with an explicit file on disk, or by adding HFS extended attribute to a file.

HFS extended attributes are very problematic. They don't survive in tar.gz files. They can't be stored in standard zip files. Therefore, they are not supported.

I've noticed Apple uses attributes if you ask them to sign a bash script, but not when signing binary executables.

Try signing your app differently, to make codesign tool use regular files instead of extended filesystem attributes.

**Comment by cocoadev03** [comment]
How do we make the code sign tool store the signing info in files instead of extended attributes?

**Comment by kornelski** [comment]
I don't know to be honest. I've seen it use attributes for bash scripts, so in my case the solution was not to include bash scripts in the bundle.

**Comment by zorgiepoo** [comment]
You can't put non-binaries in directories that only expect binaries. In your example that is `somecrypto.a` is `Frameworks`. [Signing guide](https://developer.apple.com/library/archive/technotes/tn2206/_index.html)
