### ISSUE TITLE
Provide option to specify download url for generate_appcast

### ISSUE THREAD

**Issue by D0miH** [sparkle-project/Sparkle#1569]
Hey everyone,

first of all thanks for this awesome project of yours🙏🏼.

I am currently developing an app for osx and which I distribute over GitHub. My `appcast.xml` is also saved in the GitHub repository. So my SUFeedUrl is something like `https://raw.githubusercontent.com/...`.
Everytime I want to release a new version I archive my app, move it into the `updates` folder of sparkle and run `./generate_appcast <updates_folder>`. However because Sparkle is supposed to download the zipped app from the GitHub releases page (`https://github.com/<user>/<project>/releases/download/`). So everytime I ran the command I need to edit my `appcast.xml` and revert the changes to the urls of each version that were made by `generate_appcast`.

So my suggestion is to add an option to `generate_appcast` such that the user can provide the beginning of the url (which I think should be the same for all releases?!) as a command line option.
For example I could then call the command `./generate_appcast <updates_folder> --app-url https://github.com/<user>/<project>/releases/download` and the script would insert the versions and the file names of the application zip files.

What do you think about this idea?

**Comment by kornelski** [comment]
Yes, it would be good to have reliable handling of this.

Could you make a pull request for this?

**Comment by D0miH** [comment]
Hey @kornelski,

sure, I will make a pull request for this:)

**Comment by D0miH** [comment]
Sorry to bother you again @kornelski 🙈 

While looking though the code that writes the appcast.xml file, a question came up.
When detecting a `<sparkle:releaseNotesLink>` node the node is deleted at [this](https://github.com/sparkle-project/Sparkle/blob/01b48d44e8c9f019d49cba669624f84823c89310/generate_appcast/FeedXML.swift#L121) line if no corresponding html file for this archive is found. The same is done for the release notes for a specific language at [this](https://github.com/sparkle-project/Sparkle/blob/01b48d44e8c9f019d49cba669624f84823c89310/generate_appcast/FeedXML.swift#L128) line.

But why is this done? Wouldn't it be easier to preserve every manually edited changes the user made to the file?

**Comment by kornelski** [comment]
I think the problem is that it's unclear what is manually edited, and what is an out-of-date leftover from a previous run of `generate_appcast`.

**Comment by D0miH** [comment]
Ah ok! Thanks:)

**Comment by D0miH** [comment]
I created a PR now. Happy to hear feedback from you guys @kornelski @zorgiepoo
