### ISSUE TITLE
Forcing update if user doesn't have current version even if version is older

### ISSUE THREAD

**Issue by maxisme** [sparkle-project/Sparkle#1570]
Hello,

I accidentally released a version `11` instead of `1.1` is there a way to now have users download `1.2` even though it is `< 11`?

Thank you

**Comment by maxisme** [comment]
my rss looks like this:
```
    <?xml version="1.1" encoding="utf-8"?>
	<rss version="1.1" xmlns:sparkle="https://%[1]s/xml-namespacessSparkle" xmlns:dc="https://%[1]s/dc/elements/1.1/">
	  <channel>
		<item>
			<title>Version %[2]s</title>
			<description><![CDATA[
				%[3]s
			]]>
			</description>
			<sparkle:version>%[2]s</sparkle:version>
			<pubDate>%[4]s</pubDate>
			<enclosure url="https://%[1]s/download" sparkle:version="%[2]s"/>
		</item>
	  </channel>
	</rss>
```

**Comment by kornelski** [comment]
Sparkle intentionally blocks downgrades. This is in case you released a security fix, and an attacker tried to downgrade users to insecure version using a previously-signed old release.

You have two options:

1. Sparkle and macOS support showing a different version to users (`shortVersionString`) than app bundle version used for version checks. So you can adopt your new `11` versioning scheme, and keep showing `1.x` to users.

2. You can compile Sparkle from source without downgrade block, then release it as v12 *with a new appcast URL in the bundle*, then release 1.2 under the new appcast URL. The change of appcast URL helps ensure that all users will always update to the downgrade-allowing version first, even after you release newer versions (elsewhere).

**Comment by maxisme** [comment]
Awesome, great options - thank you for getting back to me!
