### ISSUE TITLE
Sparkle 2 and sandboxed app update extraction error.

### ISSUE THREAD

**Issue by skavans** [sparkle-project/Sparkle#1573]
Hi there,

I'm now implementing the updating feature of my sandboxed app. The app also contains the Safari extension.

I'm successfully done with adding the Framework and XPC services and with a codesigning.
I'm successfully notarized the app and then add it to a ZIP archive for distributing.
Then, I generate the appcast.xml using `./bin/generate_appcast` tool and everything is OK there too.

Then I try to run the older version to check the update process.
The first issue there is that the auto-update doesn't work despite I set `SUEnableAutomaticChecks` to `YES` in my `Info.plist`.
The second **main** issue is that when I run the `Check for Updates...` manually, the Sparkle locates the new version correctly, but when I try to `Install Update`, the following error arises:
`An error occurred while extracting the archive. Please try again later.`

Below are the only related Console.app logs:
```
Apr 10 11:47:22 iMac-skavans com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100008.Aqua): com.skavans.test-sparkle-updater (lint): Assuming EnablePressuredExit=false given EnableTransactions=false.
Apr 10 11:47:22 iMac-skavans com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100008.Aqua): com.skavans.test-sparkle-progress (lint): Assuming EnablePressuredExit=false given EnableTransactions=false.
Apr 10 11:47:29 iMac-skavans com.apple.xpc.launchd[1] (com.skavans.test-sparkle-updater[15397]): Service exited with abnormal code: 1
Apr 10 11:47:29 iMac-skavans com.apple.xpc.launchd[1] (com.skavans.test-sparkle-progress[15398]): Service exited with abnormal code: 1
```

If I try to run the update process under debugging, I see the following also:
```
2020-04-10 11:35:19.899082+0300 Test[15035:21848765] [Sparkle] DEPRECATION: Serving updates without a DSA key is now deprecated and may be removed from a future release. See Sparkle's documentation for more information.
2020-04-10 11:35:26.900669+0300 Test[15035:21848765] [Sparkle] Timed out while probing installer info data
2020-04-10 11:35:37.917087+0300 Test[15035:21848765] [Sparkle] Timed out while probing installer progress
```

Can you please help me with what I missed?

**Comment by skavans** [comment]
Oh, I found other issues in the Console.app:

```
ошибка	12:10:36.274185+0300	Autoupdate	Failed to validate update before unarchiving because no DSA key was found
ошибка	12:10:36.502667+0300	Test	Warning: Downloader's expected content length (178) != Appcast item's length (7037514)
ошибка	12:10:36.517009+0300	Autoupdate	Error: No valid unarchiver for /Users/skavans/Library/Caches/com.skavans. Test/org.sparkle-project.Sparkle/Installation/x7ZdCigkx/Test-1.1.4.zip.html
ошибка	12:10:58.620697+0300	Test	Error: An error occurred while extracting the archive. Please try again later. (null) (URL (null))
ошибка	12:10:58.620896+0300	Autoupdate	Invalidation on remote port being called, and installation is not close enough to completion!
ошибка	12:10:58.621398+0300	Updater	Error: Agent Invalidating without having the chance to reply to installer
```

Apologies, It seems that's my bad somewhere.

**Comment by skavans** [comment]
My main error was that the static update ZIP-files were unable to be readen by nginx 🤦‍♂️

**Comment by giladlu** [comment]
Hi @skavans 

Do you now if the safari app extension can be auto updated without the main app being opened? 
I mean after you first install the safari app extension you open the app in order to install it, and then you dont need to open the app to use the extension anymore. So I was wondering if Sparkle will work event if the main app isn't open?

Also, are you using the new version of Sparkle (2.x) because the safari app extension requires to be sandboxed?

Thank you!

**Comment by skavans** [comment]
Hey @giladlu,

1. Sorry, I don't know anything about it.
2. Yes, I use the 2.x version and it works good for both my app and embedded Safari extension.
3. I distribute the app using DMG, not PKG so I can't answer this question. I read somewhere that the PKG is supported but I didn't try it.

**Comment by giladlu** [comment]
thanks @skavans 

Did you embed Sparkle in the app itself or in the safari extension inner app?

thanks

**Comment by skavans** [comment]
@giladlu,

I embedded it in the app itself.

**Comment by skavans** [comment]
@giladlu,

If I'm not mistaken, I used the following article to make things working:
https://christiantietze.de/posts/2019/06/sparkle-xpc-setup/

**Comment by giladlu** [comment]
@skavans thanks!! I will take a look
