### ISSUE TITLE
Fatal Error: Could not cast value of type '__NSCFNumber'  to 'NSString'

### ISSUE THREAD

**Issue by mhdhejazi** [sparkle-project/Sparkle#1574]
Well, let me go straight to the issue:
`profileArray` is defined here as `NSMutableArray<NSDictionary<NSString *, NSString *> *>`:
https://github.com/sparkle-project/Sparkle/blob/2db0d8cb379920b76b9ab4090f8b73d5e35bfe52/Sparkle/SUSystemProfiler.m#L45

But here, an `NSNumber` object (`value`) is added to the dictionary:
https://github.com/sparkle-project/Sparkle/blob/2db0d8cb379920b76b9ab4090f8b73d5e35bfe52/Sparkle/SUSystemProfiler.m#L69

Which causes a crash when the dictionary is bridged to Swift:
>Could not cast value of type '__NSCFNumber' (0x7fff8ea49558) to 'NSString' (0x7fff8efc2100).

And the same thing is repeated multiple times in the same method.

**Comment by kornelski** [comment]
Can you make a PR with the string conversion?

**Comment by mhdhejazi** [comment]
Doing this may break any code that is expecting the value for `SUSystemProfilerCPUCountKey`, for example, to be a number, which makes sense.
Maybe changing the type of dictionary would be a safer option?

Also, searching for `@\(\w+\)` in the codebase reveals many cases where an `NSNumber` is treated as a string or assigned to a string variable.

**Comment by kornelski** [comment]
I think it's mostly a private struct, so there's low risk of breaking. That info is not useful on the host, only after it's being sent to the server.

**Comment by mhdhejazi** [comment]
I switched to another solution since then, so I won't be able to revisit this again. I'm sorry I wasn't able to help with a PR.
