### ISSUE TITLE
Install on Quit in applications that never quit

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#1576]
Sparkle has an option to install updates when the app quits, either when it's a background auto-update, or when user chooses this option.

The problem is, some applications can stay open for _months_. iTerm2 nighties even have a custom warning about the app being more than 30 days old, despite having 1-day auto update. I keep getting that warning!

The problem is that Sparkle _very patiently_ and quietly sits and waits for the chance to install an update on quit, and that chance may not come.

Should Sparkle be more aggressive about this? 

For example, it could pop-up update prompt _again_ every X number of days of waiting for the app to quit.

**Comment by zorgiepoo** [comment]
Sparkle 2.x's re-architectured scheduler already does this, via `SUImpatientUpdateCheckInterval` which is set to 1 week.

I honestly thought 1.x had something like this, but I guess not.

**Comment by zorgiepoo** [comment]
Oh, it is `SUAutomaticUpdatePromptImpatienceTimer` in the SUAutomaticUpdateDriver of the 1.x branch.

**Comment by zorgiepoo** [comment]
Ah I see, but 1.x doesn't re-prompt. Either way, this is done in 2.x.

**Comment by 011235813** [comment]
> Sparkle 2.x's re-architectured / resumable scheduler already does this, via `SUImpatientUpdateCheckInterval` which is set to 1 week.
> 
> I honestly thought 1.x had something like this, but I guess not.

Can this `SUImpatientUpdateCheckInterval` be changed via the Info.plist?
