### ISSUE TITLE
How to use Sparkle with cmake command 

### ISSUE THREAD

**Issue by xp-xp-xp** [sparkle-project/Sparkle#1577]
How to use Sparkle with cmake command 
```
find_library(SPARKLE Sparkle)
include_directories(${SPARKLE})
```

**Comment by kornelski** [comment]
In macOS terminology, Sparkle is a framework, not a library. I don't know if cmake supports that.

**Comment by ManuelSchneid3r** [comment]
@xp-xp-xp have you been able to integrate it seamlessly?
