### ISSUE TITLE
 install update error occurred. code = - 67030

### ISSUE THREAD

**Issue by iyxcCode** [sparkle-project/Sparkle#1578]
### Description of the problem
Hello, when I click Install update, I can't install it. 

- The error prompt is "an error occurred while extracting the archive. Please try again against later." 
- The console prints "error domain = nsosstatuserrordomain code = - 67030" (null) "userinfo = {seccsarchitecture = x86_". Please help me to see why this happens

### Do you use Sandboxing in your app?
NO

### Version of `Sparkle.framework` in the latest version of your app
1.23.0

**Comment by kornelski** [comment]
The status is:

https://www.osstatus.com/search/results?platform=all&framework=all&search=67030

which means:

https://developer.apple.com/documentation/security/errseccsinfoplistfailed

> errSecCSInfoPlistFailed

> The Info.plist file or the signature has been modified.

which means something has modified your app after signing, but before archive was made. Maybe it was a tool that edits info plist, or a bug in the program you've used to compress the archive.
