### ISSUE TITLE
Pedantic: Swift lines shouldn't end in semicolons

### ISSUE THREAD

**Issue by Wevah** [sparkle-project/Sparkle#1581]
Certainly not a priority, but Swift lines don't need to end in semicolons (and probably shouldn't).

**Comment by kornelski** [comment]
If Swift has equivalent of gofmt, I wouldn't mind using it

**Comment by Wevah** [comment]
There's a `swiftlint` command; I thought it came with Xcode but I must have built it myself.

**Comment by rajivshah3** [comment]
SwiftLint is made by Realm (https://github.com/realm/SwiftLint)
