### ISSUE TITLE
On hold: Update swift helpers to use Swift Argument Parser

### ISSUE THREAD

**Issue by Wevah** [sparkle-project/Sparkle#1583]
The fairly recent [Swift Argument Parser](https://github.com/apple/swift-argument-parser) makes parsing arguments a lot more simple and straightforward.

(I'll take this issue.)

**Comment by Wevah** [comment]
I just realized this might require Swift 5.0 so maybe it should be put off for now.

**Comment by Wevah** [comment]
Is there a reason to stay with Swift 4.2? Making sure the tools compile on older Xcodes?

**Comment by kornelski** [comment]
Personally I don't care about old Swift versions. I'm not sure if some users aren't stuck with older versions of Xcode if they require older SDKs or something.

**Comment by Wevah** [comment]
I’ll start a branch for this so it’s in reserve.

**Comment by Wevah** [comment]
The distributed binaries are currently distributed without the Swift runtime embedded, so it's likely ok to bump the Swift version.

**Comment by Wevah** [comment]
The concern I have is that the argument parser package compiles to something like 2 MB; I'm not sure if keeping the binary size of the CLI tools down is a priority or not.

(I also need to rebase.)

**Comment by kornelski** [comment]
Size of the CLI tools isn't a very big concern. They're already embarassingly large due to Swift runtime :)

**Comment by Wevah** [comment]
Oh yeah, I forgot they still need to target OSs < 10.14. ¬_¬
