### ISSUE TITLE
Update file fully download but can not update with error 

### ISSUE THREAD

**Issue by yunmin1130** [sparkle-project/Sparkle#1585]
Hello

I setup sparkle to my app, and detected update file and download pkg file successfully, but at the end of the update I have this error:
"Update Error! Failed to extract update"

In Console, I got this error : 
[Sparkle] Error: No valid unarchiver for /Users/user/Library/Caches/com.companyCorp.Myapp/org.sparkle-project.Sparkle/PersistentDownloads/ddjRwG4sM/Myapp 1.1.0/Myapp.pkg!

I already check SUFeedURL, it works well.

Here is my XML file 

```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/">
    <channel>
        <title>Test for Sparkle</title>
        <item>
            <title>Version 2.0 (2 bugs fixed; 3 new features)</title>
            <sparkle:releaseNotesLink>
                http://you.com/app/2.0.html
            </sparkle:releaseNotesLink>
            <pubDate>Wed, 29 Apr 2020 17:20:11 +0000</pubDate>
            <!-- Sparkle 1.21+ uses sparkle::edSignature="ed25519" instead of sparkle::dsaSignature="deprecated DSA" -->
            <enclosure url="https://localhost:8443/myFolder/MyApp.pkg" sparkle:version="1.1.0" sparkle:shortVersionString="1.1.0" length="218676727" type="application/octet-stream" sparkle:edSignature="aI5CO3/txgSoFwmkId6Q0nXJMVfiYcaS42h6Rz/Sh4s=" />
        </item>
    </channel>
</rss>
```

**Comment by kornelski** [comment]
Put the pkg in a zip.

**Comment by yunmin1130** [comment]
@kornelski  Thank you. It works but after download and click "Install and restart" button I got another error log

```
```

**Comment by kornelski** [comment]
SUPublicKey is only half of the work you need to do. You also must use it to generate update-specific signature every time.

Use `generate_appcast` tool to have the signatures done for you.

**Comment by yunmin1130** [comment]
I use `generate_appcast` but i could not unarchive pkg file. It doesn't support archive and even with zip file end with "No usable archives found in folder"

**Comment by kornelski** [comment]
Ah yes, sorry. `generate_appcast` doesn't support pkg.

**Comment by kornelski** [comment]
So the error log tells you exactly what it sees. If it says there's no signature in the update, make sure your appcast entry has one and the syntax is exactly correct.

**Comment by yunmin1130** [comment]
@kornelski Thank you I didn't check correct edSignature
