### ISSUE TITLE
EdDSA signature does not match. 

### ISSUE THREAD

**Issue by waquarahmad** [sparkle-project/Sparkle#1587]
Errors i get in in xcode 

-->EdDSA signature does not match. Data of the update file being checked is different than data that has been signed, or the public key and the private key are not from the same set.

-->The update has a public (Ed)DSA key, but the public key shipped with the update doesn't match the signature. To prevent future problems, the update will be rejected.

i have added  SUPublicEDkey in info.plist using terminal

<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
<channel>
<title><rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
<channel>
<title>InTimeDeskApp</title>
<item>
<title>2.0</title>
<pubDate>Tue, 12 May 2020 16:41:03 +0530</pubDate>
<sparkle:minimumSystemVersion>10.15</sparkle:minimumSystemVersion>
<enclosure url="https://intimeprosstorage.blob.core.windows.net/intimeprosdeskappmac/InTimeDeskApp%20(3).zip" sparkle:version="1" sparkle:shortVersionString="2.0" length="4377533" type="application/octet-stream" sparkle:edSignature="XYpAe/dsnwrZ9xBbldRzZCWbbkYyyaYhGPt7t0VkKKmZgO6wrYUKvKXxknXdSSaNuN6sTAhPvV7bV/+ql9Q3BQ=="/>
</item>
</channel>
</rss></title>
<item>
<title>2.0</title>
<pubDate>Tue, 12 May 2020 16:41:03 +0530</pubDate>
<sparkle:minimumSystemVersion>10.15</sparkle:minimumSystemVersion>
<enclosure url=" " sparkle:version="1" sparkle:shortVersionString="2.0" length="4377533" type="application/octet-stream" sparkle:edSignature=""/>
</item>
</channel>
</rss>

my sparkle:edSignature is different from the one in info.plist
i am using app not pkg

**Comment by kornelski** [comment]
Please try `generate_appcast` to make appcast with correct signatures. 

It's normal that `edSignature` is different than the one in Info.plist, because one is a signature, the other is a key.
