### ISSUE TITLE
Download .pkg file and update issue

### ISSUE THREAD

**Issue by yunmin1130** [sparkle-project/Sparkle#1588]
Hello

I have some question with .pkg file.
If I control SUUpdater's behavior by setup SUUpdater delegate method, could sparkle download .pkg file and archive it to .zip file in  user's mac ?? And could sparkle update with this .zip file??

There is some [SUUpdater delegate method](https://sparkle-project.org/documentation/customization/)
If this method is possible what delegate method should i use?

**Comment by kornelski** [comment]
I don't understand the question. Why would you create archive client-side?

**Comment by yunmin1130** [comment]
@kornelski 
I updated my app succesfully with sparkle .zip file. But our deployment server couldn't service zip or tar archive file. So I have to service .pkg file and is there any method to auto update by using .pkg file??

**Comment by kornelski** [comment]
There is not. zip/tar/dmg is required.

**Comment by zorgiepoo** [comment]
You can as of >= v1.26.0
