### ISSUE TITLE
SUUpdateAlert odd behavior when Main App is full screen

### ISSUE THREAD

**Issue by R4N** [sparkle-project/Sparkle#1590]
Thanks very much for developing Sparkle. 

Currently SUUpdateAlert is set to the default "Inferred Behavior" for its window's collectionBehavior. This causes some undesired behavior when the Main Application is full screen. Specifically when checking for updates via a menu item (or automatically), the SUUpdateAlert is presented full screen with a large amount of black space around the centered SUUpdateAlert's content. It would be better to set the SUUpdateAlert window's collectionBehavior to `NSWindowCollectionBehaviorFullScreenAuxiliary` which would allow it to present on top of the Main Application's full screen.

I use Sparkle 1.22.0, but I've also confirmed this hasn't been adjusted in 2.x.

I'd be happy to issue a PR with this adjustment, just let me know which branch I should base it off of.

**Comment by kornelski** [comment]
Yes, please make a PR for it. If it's a small change, it'd be best to have it on both v1 and v2.

**Comment by R4N** [comment]
Great. I've just created the PRs:

v1 PR: https://github.com/sparkle-project/Sparkle/pull/1591
v2 PR: https://github.com/sparkle-project/Sparkle/pull/1592

It could potentially be desirable to do this to some of the other xib windows as well, but I don't use all of them so I didn't want to make those changes without trying the adjustment on them.

**Comment by kornelski** [comment]
Great, thanks!
