### ISSUE TITLE
Update fails with Error Domain=SUSparkleErrorDomain Code=3001

### ISSUE THREAD

**Issue by yanone** [sparkle-project/Sparkle#1594]
### Description of the problem

I think I followed all required steps in signing my apps:

* Build my .app
* Successfully signed and notarized it
* Stapled notarization to .app
* Created a separate .dmg for shipping, signed it with Apple ID
* Created appcast.xml (I’m using my own code to create appcast.xml, but the `sparkle:edSignature=""` and `length=""` values are identical to the appcast.xml created by your `generate_appcast`, I checked 100%
* Followed your troubleshooting guidelines ;)

The installation of the update fails with `Error Domain=SUSparkleErrorDomain Code=3001`.

Please note that the shipped .dmg contains like a background image and stuff. I hope that's not a problem, because we're talking about cryptography in the `edSignature` attribute, right?

### Do you use Sandboxing in your app?
No

### Version of `Sparkle.framework` in the latest version of your app
1.23

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
1.23

### Sparkle's output from Console.app
```
Type.World: Error Domain=SUSparkleErrorDomain Code=3001 "Beim Entpacken des Archivs ist ein Fehler aufgetreten. Bitte versuche es später erneut." UserInfo={NSLocalizedDescription=Beim Entpacken des Archivs ist ein Fehler aufgetreten. Bitte versuche es später erneut., NSLocalizedFailureReason=Das Update ist nicht ordnungsgemäß signiert.}
```

### Steps to reproduce the behavior

* Download app at https://storage.googleapis.com/typeworld2/downloads/guiapp/TypeWorldApp.0.1.7-alpha.dmg
* Follow app update procedure (There's also a menu item for it under "File")

The versions 0.1.7-alpha and 0.1.8-alpha are actually code-identical. I made the two versions just to test the update process.

**Comment by kornelski** [comment]
Does the console.log explain further what went wrong?

**Comment by yanone** [comment]
Ah yes, I should have posted that earlier:
`OK: EdDSA signature is correct`
`This app has a DSA public key, so a DSA signature is required too`
`There is no DSA signature in the update`
`The update has a public (Ed)DSA key, but the public key shipped with the update doesn't match the signature. To prevent future problems, the update will be rejected.`

Like, I don't understand.

The `Info.plist` has the public key I took from `generate_keys` like so:
```
	<key>SUPublicEDKey</key>
	<string>IqLvpa980dAYzn9P6ttJiBgMQTpI58G6lchzLC9Q8aA=</string>
```

And the `.dmg`’s corresponding DSA hash (or whatever it is) is in `appcast.xml` like so: `sparkle:edSignature="4Y0ZLRmAlXllapJ63LcHvSAwVlSksS2qYK5UigqvuxO6sil/AsV8bT1qjdWCCkdVUwVG48UPtGBGCJjlVUmUDw=="`

As far as I know, that’s all I need. Is it?

**Comment by yanone** [comment]
I see: There’s a mismatch here: The app shipped both the DSA and edDSA public keys, but the `appcast.xml` has only the `edSignature` attribute, not the old one.

Which does not explain this line:
`The update has a public (Ed)DSA key, but the public key shipped with the update doesn't match the signature. To prevent future problems, the update will be rejected.`

However, I will repeat without the old public key and report. The build process takes quite some time...

**Comment by yanone** [comment]
Nope: `EdDSA signature does not match. Data of the update file being checked is different than data that has been signed, or the public key and the private key are not from the same set.`

And then the same `The update has a public (Ed)DSA key, but the public key shipped with the update doesn't match the signature. To prevent future problems, the update will be rejected.`

**Comment by kornelski** [comment]
The reason is this:

> This app has a DSA public key, so a DSA signature is required too

You must also add signature for the old algorithm, so that old version can use it.

**Comment by yanone** [comment]
But wait, this project is unpublished. I'm preparing its first public release. There isn't really an old version. The versions are both the same, really, except separately built with different version numbers, and exist separately only to establish the update process.

That's why I wrote Sparkle version 1.23 for both old and new.
As far as I understand I don't need the old DSA signatures anymore at all. I could add them, but I'd rather get the forward looking technology running. 

What I need to try again (tomorrow) is to generate another set of keys and try again. Who knows what went wrong. Tho I only ever did it once, so I don't see how they could mismatch :/

**Comment by yanone** [comment]
After generating a new set of keys, the update now worked. I can't say what was wrong with the keys. I only ever generated the edDSA keys once (a little while back), so I didn't expect there to be a problem. Anyways...

Now I have only one problem left, as already described in https://github.com/sparkle-project/Sparkle/issues/1364, which is I need to automate the build process and therefore can't work with the keychain. If you could help here, that would be greatly appreciated.

Thank you!
