### ISSUE TITLE
How to add releaseNotesLink using generate_appcast

### ISSUE THREAD

**Issue by xp-xp-xp** [sparkle-project/Sparkle#1595]
How to add releaseNotesLink to updates.xml using generate_appcast？

**Comment by kornelski** [comment]
Link is not supported, but you can add `*.html` files with the same base name as the update.

**Comment by zorgiepoo** [comment]
Check generate_appcast help page for release notes support

**Comment by llothar** [comment]
How can we add  I18N and L17N to the referenced  release note links. 

This is all so full of disgusting bad hacks. Typical when you think about security but not what really matters, user experience.
