### ISSUE TITLE
Change Application ID and Team identifier

### ISSUE THREAD

**Issue by spearway** [sparkle-project/Sparkle#1600]
I am running a sandboxed application with Sparkle 2.x. The application is distributed as a dmg and is correctly notarized.

We have a version 14.x that has an identifier com.acme.foo.MyApplication with a team identifier ABCDEFGHIJ we now have a version 15 with an identifier com.acme.bar.MyApplication with a team identifier KLMNOPQRST.

Update 14.a to 14.b works fine as does 15.a to 15.b but updating from 14.x to 15.x give me an error:
"An error occurred while running the updater. Please try again later" 

Digging through the code There is only one place this occurs and the reason is "The remote port connection was invalidated from the updater'. I suspect that when updating because the sandbox is changing name the driver looses the connection. Not absolutely sure of that may be someone with more familiarity with the code could help?

Any idea on how to fix would be welcome. Unfortunately I cannot undo the id changes but I could reissue a 14.x if required.

Thank you

Pierre

**Comment by kornelski** [comment]
I don't think this will work.

Sparkle finds updates in the DMG mount by looking for a bundle with a matching identifier. Any bundles with a different identifier is skipped.

You may need to make an update with a pkg installer that launches a script to force-replace the app.

**Comment by spearway** [comment]
Thank you for the answer.

I suppose there is no way to force an intermediate step when the user in 14 select a 15 update?

So correct me if I am wrong, what you suggest is that I split the app cast with a new URL for 15 and the 15 upgrades. Then in the 14 app cast publish a final pkg upgrade to force the install of 15?

How is this going to work with the sandboxes? The error I have is an XPC connection reset. Will this be an issue?

**Comment by kornelski** [comment]
Sparkle (both v1 and v2) assumes bundle ID is a permanent identifier that will never change. It's never been tested or supported changing of bundle ID, so I can't even enumerate all the places where Sparkle will break if you try to change the bundle identifier.

I suggested pkg, because Sparkle doesn't see what pkg installers are doing. From Sparkle's perspective that will be like running a script that self-destructs the old app and installs some new unknown app that Sparkle never heard about.

**Comment by spearway** [comment]
So I did exactly that: separated the two feed one for the 14.x (the old feed) and one for the new one 15.x.

I then created a pkg installer with a 15.x version in it, signed it and notarized it. Then updated teh 14.x feed to offer the update, it download and come with an error "An error occurred while extracting the archive. Please try again later." But if I go to the cache and double click on the downloaded pkg it installs without warning.

Any idea what I am missing?

Thank you

Pierre

**Comment by kornelski** [comment]
Your Console.app's log has information what exactly went wrong when unarchiving.

**Comment by spearway** [comment]
Sorry I did not see the error but I don't understand 

 error	10:26:59.272394-0700	Autoupdate	Error: No valid unarchiver for /Users/pierre/Library/Caches/com.apple.maps.Alchemy/org.sparkle-project.Sparkle/Installation/Ycly2M2zj/MyApplication-14.5000.0.pkg

It is unarchived and valid and if I double click on that file it does install. Do I need to zip it?

**Comment by kornelski** [comment]
Put the pkg in a .zip file

**Comment by spearway** [comment]
This solved the issue but now I have another one:

error	20:17:49.976308-0700	Autoupdate	Could not read public DSA key
error	20:17:49.976346-0700	Autoupdate	DSA signature validation of the package failed. The update contains an installer package, and valid DSA signatures are mandatory for all installer packages. The update will be rejected. Sign the installer with a valid DSA key or use an .app bundle update instead.
error	20:17:49.976375-0700	Autoupdate	Error: update validation was a failure
error	20:17:49.976711-0700	Updater	Error: Agent Invalidating without having the chance to reply to installer

The pkg is signed and notarized!

**Comment by kornelski** [comment]
We don't pay attention to pkg signing or notarization. We require Sparkle's own DSA or EdDSA signature instead.

**Comment by spearway** [comment]
May be we should. Sparkle works well with signed dmg why not do the same with pkg? If they are not signed and notarized they will not function correctly anyway on modern OS.

Unfortunately this will not solve my problem anyway. Is there a way to specify a mandatory intermediate step in the appcast feed?

**Comment by kornelski** [comment]
I'm not saying you shouldn't sign pkg. I'm saying that in addition to all usual pkg requirements, Sparkle adds one more - DSA signature. Without it, no go.

Regardless of that, I suggest you should **not** change the bunlde ID. Revert that change and keep using the old bundle ID forever.

**Comment by howlium** [comment]
Can you clarify: if a package has already been signed, notarized, and stapled with Apple, should we then sign a second time with a Sparkle DSA signature? Or would that overwrite Apple's signature? Or should the DSA signing be done before the Apple sign/notarize/staple steps?

**Comment by kornelski** [comment]
If pkg installer is signed, notarized, stapled by Apple, and even has Tim Cook's autograph — none of it matters to Sparkle. Sparkle doesn't care and won't check any of it.

For pkg installers Sparkle wants one thing: it's own DSA or EdDSA signature. That's all that matters to Sparkle, and it's the only thing that is required, and must be provided for all pkg installers every time.

Sparkle's (Ed)DSA signatures apply to downloaded files, which must be zip/dmg/tar containing the pkg isntaller, so it's logically impossible to make a Sparkle signature for a pkg installer before Apple's steps that are embedded in the pkg file.

**Comment by spearway** [comment]
Do you know what this means?

error	17:52:48.106292-0700	Alchemy	Error: An error occurred while extracting the archive. Please try again later. (null) (URL (null))
error	17:52:48.106992-0700	Autoupdate	Invalidation on remote port being called, and installation is not close enough to completion!
error	17:52:48.107934-0700	Updater	Error: Agent Invalidating without having the chance to reply to installer


Here is what I have done:

in the 14.x branch I have created a new release with the the DSA key and a  "new"  appcast url. in the "old" appcast I have published the update and it did work no problem (using a dmg)
I have crafted a pkg installer with the new 15.x application signed it with the DSA key and pushed it on the "new" appcast. The application pick up the update download and run the pkg. This leads to a request for permission to install but the installation fails.

The pkg signature is correct and it has all the blessing from Apple I have a sparkle:installationType=package should I put sparkle:installationType=interactive-package

**Comment by spearway** [comment]
Could this be the issue?

error	06:11:51.456670-0700	tccd	Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for ACC:{ID: org.sparkle-project.Sparkle.Updater, PID[69532], auid: 501, euid: 501, binary path: '/Users/pierre/Library/Caches/com.acme.foo.MyApplication/org.sparkle-project.Sparkle/Launcher/i3fUh5Oub/Updater.app/Contents/MacOS/Updater'}, REQ:{ID: com.apple.appleeventsd, PID[3152], auid: 55, euid: 55, binary path: '/System/Library/CoreServices/appleeventsd'}

**Comment by spearway** [comment]
I got it working. Thank you for the help. To for try record this is how you can change the id of your application if you have to do it. 

My application is normally packaged as dmg signed and notarized so the DSA signature is not required and I did not have one (my faut)

The current version of the application is 14.x that has an identifier com.acme.foo.MyApplication with a team identifier ABCDEFGHIJ we now have a version 15 with an identifier com.acme.bar.MyApplication with a team identifier KLMNOPQRST. The current appcast is appcast.xml.rss.

1- I created a new version in the 14.nxbranch with the correct DSA key and a change in the appcast name to appcast-14-15.xml.rss. The change of name is to create a forced step update that would not be skipped. I published that version 14.x in the current appcast: appcast.xml.rss.

2- I created a pkg with the old app ID and a version 14.y but containing the new 15.x application with the new app ID and a appcast appcast15.xml.rss. I did sign and notarized the pkg and published the new appcast-14-15.xml.rss with just one entry for the pkg correctly signed with the DSA signature.

3- I created the new appcast appcast15.xml.rss where I can push updates the the 15.x branch and it all works

This looks a bit convoluted but it works, The only draw back is that the user sees 2 updates consecutively.

Cheers

Pierre
