### ISSUE TITLE
Sparkle causing ambiguous popup message

### ISSUE THREAD

**Issue by sandyleee** [sparkle-project/Sparkle#1601]
I am keep getting the popup message every 30min or so: "For security reasons, you need to code sign your application or sign your updates with a EdDSA key. See https://sparkle-project.org/documentation/ for more information."

I uninstalled a few apps yesterday, and auto-updater must have been broken when I went to uninstall something. Is there any way to fix it? Googling led to the thread I pasted below where it says the issue has been fixed, but I am still facing the same problem.

I have no idea which app is causing this problem. I went through and updated all the apps that are using Sparkle framework, but didn't find any luck

---
This has been fixed, but you can't see the fix, because you can't update to the fixed version.

I'm locking this, because even if million people add +1 to this thread, I still can't time travel to change it in the old version you have.

_Originally posted by @kornelski in https://github.com/sparkle-project/Sparkle/issues/1149#issuecomment-511599371_

**Comment by kornelski** [comment]
We've already added the name of the app to this error message.

**Comment by mateolan** [comment]
It's great that you fixed the error message in GitHub. Did you release this in production code? 
Please advise how we can get the latest version of Sparkle through App store or..?
Helpfulness beats snarkiness everyday of the week.

**Comment by michelf** [comment]
Sparkle is not an app you can update. It's a component application developers can include in their app. Each app contains its own copy of Sparkle, so if one copy is misbehaving you need to find which one, within which app. Then update the app. (Assuming the latest version of the app includes the latest version of Sparkle, which might not be the case.)

**Comment by kornelski** [comment]
There is nothing more we can do about this. I'm locking this and please don't open duplicate issues. I'll repeat:: **there is nothing more we can do about this**. NOTHING.
