### ISSUE TITLE
generate_keys error on Mac OS 10.12.6

### ISSUE THREAD

**Issue by xp19870106** [sparkle-project/Sparkle#1602]
‘’‘
nds-Mac-mini% /Users/nd/Documents/NetDragon/live-pc-push-qt/obs-studio-24.0.6/Package/Sparkle-1.24.0-alpha/bin/generate_keys ; exit;
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/nd/Documents/NetDragon/live-pc-push-qt/obs-studio-24.0.6/Package/Sparkle-1.24.0-alpha/bin/generate_keys
  Reason: image not found
zsh: abort    
’‘’

My system version is 10.12.6 with Xcode 8.3
I'm using Sparkle-1.24.0-alpha
How can I fix this problem

**Comment by Wevah** [comment]
It seems the Sparkle tools don't have embedded Swift runtimes in them, so they'll only work on macOS 10.14.4 or greater out of the box.

Try installing the Swift runtime libraries from https://support.apple.com/kb/DL1998.
