### ISSUE TITLE
Make it easier to access update notes, especially after an update has been downloaded/installed

### ISSUE THREAD

**Issue by saagarjha** [sparkle-project/Sparkle#1604]
I'm the user of many apps that integrate Sparkle for their automatic updates, and I'm often a bit curious to see what's new in each update. There's a changelog that shows up sometimes, but it's fairly difficult to actually pull up, to the point where I actually disable automatic updates for most of my apps so I can manually run the update checker, which lets me know if there are updates available, and more importantly, *show the changelog* before I install anything new. It'd be nice if Sparkle had a way to access this manually, so I didn't have to go through this hack just to get basic information about updates. The two specific cases which I think could be improved are:

1. If I leave automatic updates on, Sparkle will download the update in the background automatically and then prompt me to relaunch the app. The problem I have with this is that it doesn't let me see what I am installing! The alert just gives three options, which are basically cancel/install now/install when I restart, but I have no way of actually seeing what the update contains. If it's just a small bug fix, I might delay installing it a little, but if it fixes a major bug I've been hitting I might install it right away; but I can't make an informed decision without that context. In any case, I would like generally stay up-to-date with what's going on in the new version, and the alert makes this impossible.
2. Once I've installed an update, I'd like to see the past changelog. I have occasionally gone through the trouble of digging up the Sparkle feed from inside the app bundle, then looking there, but this is really a massive pain for something that could be much simpler…

Just a couple of suggestions–let me know what you think!

**Comment by kornelski** [comment]
Yes, I think that's a good idea. 

Over Sparkle's lifetime automatic updates have become the norm, so "install first - explain later" model makes sense.

However, Sparkle is in the process of switching from v1 to v2, so there's other work to be done first, and we can't do too many big changes at once.

**Comment by saagarjha** [comment]
Sure, no rush. Thanks for working on Sparkle!

**Comment by zorgiepoo** [comment]
Sparkle 2.x solves the first issue because the regular and automatic update alerts are merged and show release notes in both cases.
