### ISSUE TITLE
generate_appcast does not add edSignature automatically

### ISSUE THREAD

**Issue by RyanLiu6** [sparkle-project/Sparkle#1605]
### Description of the problem
I have configured my app and workflow based on the documentation [here](https://sparkle-project.org/documentation/). Specifically, I used both `./generate_keys` and `./generate_appcast`.

After generating two builds for testing, I see the following in `Console.app`
```
There is no EdDSA signature in the update, but the app is capable of verifying them
There is no DSA signature in the update
The update has a public (Ed)DSA key, but the public key shipped with the update doesn't match the signature. To prevent future problems, the update will be rejected
```

#### Fix ####
Manually running `./sign_update` and adding the signature to the generated `appcast.xml` fixes the issue, but it was not immediately clear from the get-go that there should've been an `edSignature` property on the item.

### Do you use Sandboxing in your app?
No

### Version of `Sparkle.framework` in the latest version of your app
1.23.0 (34-g962878b84)

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
N/A

### Sparkle's output from Console.app
As above.

Any ideas on where my configuration went wrong or how to fix this for future updates using `./generate_appcast`?

**Comment by kornelski** [comment]
That could happen if you denied access to the keychain to generate_keys. Do you get any warnings about it when you run it? 

Similarly, does generate_appcast warn about lack of keychain access?

Did you add public key to info.plist?

**Comment by RyanLiu6** [comment]
Thanks for the quick response! Greatly appreciate it!

As far as I could tell, `generate_keys` and `generate_appcast` don't have any warnings when I run them. 

I get the following when I run `generate_keys`:
```
This tool uses macOS Keychain to store the Sparkle private key.
If the Keychain prompts you for permission, please allow it.
OK! Read the existing key saved in the Keychain.

In your app's Info.plist set SUPublicEDKey to:
my_public_key
```

And the following when I run `generate_appcast`:
```
Written /some/path/appcast.xml based on 2 updates
```

I checked my keychain manually and I can see the entry Sparkle made under `Private key for signing Sparkle updates` so I believe that I gave permissions required.

And under my app's `Info.plist` file I have the following line:
```
<key>SUPublicEDKey</key>
<string>my_public_key</string>
```

So I'm not exactly sure where I went wrong.

**Comment by kornelski** [comment]
The log looks fine. Can double-check the appcast file on disk? Maybe your uploaded version is different or cached somewhere?

**Comment by RyanLiu6** [comment]
Oh, I played around with naming and generating appcasts but it looks like if my app name is `my_app` the zip has to be `my_app.zip`, and not say `my_app_v1.0.zip`. With the zip being `my_app.zip`, the newly generated appcast has edSignature attached.

I guess there's no way for me to name it a specific release? I'm pushing these zips and the appcast and hosting it on a server, so my builds and repo folder are the same. Would the correct approach be to have a separate builds folder to generate the appcast with one `my_app.zip` file and then just copy them over to my repo? 

In any case, I think we can close this issue since it looks like it was an user issue instead of a tool issue. Thanks for all your help!

**Comment by kornelski** [comment]
That's a caching issue. Each archive is decompressed once and only once, so you've probably had a different version of `my_app_v1.0.zip` that lacked public keys.

**Comment by RyanLiu6** [comment]
Ah I see, is there a way to clear the cache somewhere? I don't mind just dealing with the name changes for these two zip files knowing it'll work for the future.

**Comment by kornelski** [comment]
Delete `~/Library/Caches/Sparkle`

**Comment by RyanLiu6** [comment]
Perfect, thank you so much! Appreciate the help.
