### ISSUE TITLE
Timeout in testDeprecatedDownloader()

### ISSUE THREAD

**Issue by Wevah** [sparkle-project/Sparkle#1610]
`performPersistentDownloadTest()` in `testDeprecatedDownloader()` ends up timing out, presumably because it's trying to make the downloader perform two requests at once, so the second never succeeds.

Looks like a fix for similar was added to `testSessionDownloader()`; the same line also fixes the failing test. (PR coming shortly.)

**Comment by kornelski** [comment]
Thank you
