### ISSUE TITLE
What the correct way to manipulate the feed URL?

### ISSUE THREAD

**Issue by spearway** [sparkle-project/Sparkle#1613]
Now that SUUpdater is deprecated, what is teh correct way to set the feed URL at startup? We used to be able to do:
        SUUpdater.shared()?.feedURL = feedURL

I am not sure what the best way is. May be we should have a way to manipulate preferences independently from the Updater?

**Comment by kornelski** [comment]
The problem is that Sparkle wants to be an auto-starting singleton, but that is fundamentally incompatible with programmatic customization interface. Programmatic change of the feedURL has been deprecated, because it's prone to race conditions. If you don't have a fallback URL in Info.plist it may even prevent the app from updating.

Do you use this for anything else than selecting between stable and beta/nightly builds of the app?

**Comment by spearway** [comment]
No I don't but I would like to persevere the user selection when the URL itself change (see #1600) Do you think that manipulating the properties directly would work i.e.e retrieving the default from user default and setting it. I just would like to be able to examine the default and "fix" them at startup. Afterwards I am happy with the current solution it works really well.

**Comment by spearway** [comment]
I understand your concern about a singleton but could we make some of the preferences manipulation classes public? At the minimum the SUConstants should be public, or we could have a class to manipulate the preferences (better) that way we can preserve the API in the future.

**Comment by kornelski** [comment]
I was thinking about having different variants of the URL in the Info.plist, like `SUAppcastURL-Beta`, and then a preference for "Beta" URL. This would allow updates to change the URL without having to fix the preferences.

But that will have to wait.

**Comment by spearway** [comment]
I like this idea, but because people name their release differently I would suggest a dictionary with the release type as a key and the uRL as a value and key for the selected entry.
`SUAppcastURLs={
"release":"https://myapplication.com/appcast.xml.rss", "beta":"https://myapplication.com/appcast-beta.xml.rss",
"alpha":"https://myapplication.com/appcast-alpha.xml.rss"
}`
`SUAppcastSelected="beta"
`

**Comment by spearway** [comment]
I was thinking that there also should be an order or precedence. When you do a hot fix for the current release it would be nice not to have to regenerate the app cast. If someone is on the beta branch and we publish a more recent version (semantically) on the prod branch it should be offered.

**Comment by spearway** [comment]
I realize that this feature is becoming more complex by the minute.

**Comment by kornelski** [comment]
I like your idea with a dictionary. That's a better use of plist.

Sparkle understands that `-beta` version is lower than stable. I guess you could use a delegate to filter out beta versions from a single appcast.

**Comment by zorgiepoo** [comment]
There is a delegate method to specify the feed URL btw. (It's been around for a long time)

**Comment by zorgiepoo** [comment]
See https://sparkle-project.org/documentation/publishing/#publishing-an-update
