### ISSUE TITLE
Auto updating when app is closed

### ISSUE THREAD

**Issue by giladlu** [sparkle-project/Sparkle#1619]
Hello,

Can an app auto-update when its closed? is there some way to update it in the background without user interaction?

Thanks!

**Comment by kornelski** [comment]
Sparkle.framework can't do that. It can download in background and update on quit, which is similarly unobtrusive.

There are 3rd party apps that can update Sparkle-using applications externally.

**Comment by giladlu** [comment]
Thanks @kornelski 

Does the user have to click something in order for the update to start? or it will be downloading while the app is running and will be updated automatically after the user quit the app?

**Comment by kornelski** [comment]
If user opted in to automatic downloads, everything will update without user interaction.

**Comment by zeeshansuleman** [comment]
@kornelski can you please specify how it can be done. I dont want any user interaction to update the app. The app should be updated silently.

**Comment by zorgiepoo** [comment]
`SUAutomaticallyUpdate` - https://sparkle-project.org/documentation/customization/ - installed silently when user authorization isn't needed (most common case)

**Comment by zeeshansuleman** [comment]
> `SUAutomaticallyUpdate` - https://sparkle-project.org/documentation/customization/ - installed silently when user authorization isn't needed (most common case)

@zorgiepoo but this does not update the app silently after specified time interval if i do not open the app.

**Comment by zorgiepoo** [comment]
The automatic installation process will not start when the app is not running, yes.

**Comment by zeeshansuleman** [comment]
@zorgiepoo 
SUScheduledCheckInterval minimum bound is 1 hour, can i put this number in minutes to test automatic update. Also right now i have specified this in info.plist , is there any way to detect the update from code after an interval and install update silently from code.
