### ISSUE TITLE
Can't install Sparkle-1.23.0

### ISSUE THREAD

**Issue by martinblampied** [sparkle-project/Sparkle#1622]
Hi, 

I can't install Sparkle-1.23.0.tar.bz2 on my mac v10.15.4.  I get "Check with developer to make sure app works with this version of macOS" 

![image](https://user-images.githubusercontent.com/3713820/86124486-1d42bc00-bad3-11ea-8c69-184e9a2c2058.png)

What am I doing wrong?

**Comment by kornelski** [comment]
Have you compiled it yourself? Have you codesigned it?

**Comment by martinblampied** [comment]
I downloaded from https://github.com/sparkle-project/Sparkle/releases
