### ISSUE TITLE
Sparkle re-launch is launching part of old application from trash

### ISSUE THREAD

**Issue by rohanp-91** [sparkle-project/Sparkle#1624]
Hello,

I have a .NET application that uses Sparkle to do silent updates in the background. I am using the following update delegate method, in the following way, to trigger a re-launch for the app:

```
UpdaterWillRelaunchAppication(SUUpdater updater) {
                    Process process = new Process
                    {
                        StartInfo = new ProcessStartInfo(Assembly.GetEntryAssembly().Location)
                    };
                    process.Start()
}
```

This results in some of the app references being loaded from the old application from /Users/<username/.Trash folder. Is there a way that I can make sure that all references are loaded from the updated app version? 

Will the delegate method shouldPostponeRelaunchForUpdate be of any use in this case? Thanks!

**Comment by kornelski** [comment]
Sparkle stopped putting old apps in trash *years* ago. Are you sure you're using recent Sparkle version?

**Comment by rohanp-91** [comment]
We are using Sparkle 1.14.1.

**Comment by kornelski** [comment]
So this bug is probably already fixed. Please try the current version.
