### ISSUE TITLE
Accessibility permission lost when app is updated 

### ISSUE THREAD

**Issue by mschrage** [sparkle-project/Sparkle#1625]
Hi,

I'm using Sparkle to distribute a MacOS app that requires accessibility permissions in order to function. The updates are installed successfully, but it seems like the permissions are reset on each update. 

Is this the expected behavior?

The only guidance I have found online is from [this](https://stackoverflow.com/questions/29006379/accessibility-permissions-reset-after-application-update) StackOverflow post from 2015!

**Comment by kornelski** [comment]
I would expect this to happen to applications that aren't code-signed, or which changed signing identity between updates.

Are they preserved if you replace the app manually?

**Comment by Juju-Kairn** [comment]
Hi,

I have the same issue with my macOS app.
I use Sparkle to distribute it and all updates reset accessibility permissions.

If I replace the app manually I keep the permissions ...

Do you have an idea? Do you change a little bit the executable?

Thank you for your answer!
