### ISSUE TITLE
How do I customize the error message presented

### ISSUE THREAD

**Issue by spearway** [sparkle-project/Sparkle#1626]
I am aware of the SPUUpdaterDelegate that send me the error when something occurs but is there a way to suppress the standard error message and present my own?

Thank you

**Comment by zorgiepoo** [comment]
SPUStandardUserDriver presents the error to the user. There's no API today to allow customizing the presented error easily but it's not a hard task. However the real question is if this is even a good idea and what's the overall intent here. Some of the errors such as an improperly signed update can be very critical.
