### ISSUE TITLE
Sparkle conversion to Swift for 2.x/3.x

### ISSUE THREAD

**Issue by fedeci** [sparkle-project/Sparkle#1629]
Hi,
well, I had the crazy idea to convert the entire Sparkle project to Swift 🤯.
Would you accept a pull request or should I drop my idea?

Thanks.

**Comment by kornelski** [comment]
Swift-native Sparkle would be interesting, but you may be underestimating the amount of effort it requires. 

Make it a fork.

**Comment by fedeci** [comment]
Can I tag you when I'm finished?

**Comment by kornelski** [comment]
Sure
