### ISSUE TITLE
Pure C wrapper

### ISSUE THREAD

**Issue by abeMedia** [sparkle-project/Sparkle#1630]
Hi,

I'd like to contribute some Go bindings for Sparkle so I was wondering if I can find a pure C example (not using Xcode) somewhere?

Thanks!

**Comment by Wevah** [comment]
Someone would have to write C wrappers around the Objective-C objects and methods first.

**Comment by abeMedia** [comment]
I see. Might have a bash at that tomorrow...

**Comment by abeMedia** [comment]
I've started working on Go bindings using a C wrapper and have got it working for everything in `SUUpdater.h`.
I'm a little stuck on how to implement the delegates though (sorry total noob in Objective C).
How would I go about using the function pointer argument from my C wrapper function to override one of the delegate functions?

**Comment by kornelski** [comment]
Delegates will be tricky indeed. For delegates you need to have an object that supports appropriate selectors. 

* If you're compiling a bit of ObjC, you could create a proxy object that implements methods and forwards the calls to a C function callback.

* You could use objective C runtime API to create a new class and new methods from scratch. https://www.mikeash.com/pyblog/friday-qa-2010-11-6-creating-classes-at-runtime-in-objective-c.html

**Comment by abeMedia** [comment]
Thanks for the pointers! I had considered the first option but sounds like creating the methods using the runtime API is the more suitable approach.

**Comment by zorgiepoo** [comment]
All delegate methods are optional and also have a way to fall back to default behavior if implemented, so the introspection issue isn't a big deal.
