### ISSUE TITLE
Compile from source fails

### ISSUE THREAD

**Issue by lemkesoft** [sparkle-project/Sparkle#1637]
I get the following error upon make release:

** BUILD FAILED **

The following build commands failed:
	ExternalBuildToolExecution Distribution
(1 failure)
make: *** [release] Error 65

How can I avoid this?

**Comment by lemkesoft** [comment]
I solved the issue on the DTK now by:
1. Installing latest Big Sur
2. Installing latest Xcode 12
3. Removing in line 48 the xz compression in the .sh release file.

**Comment by aleksiy805** [comment]
Had the same problem in line 70. Removed | xz > ...

**Comment by zorgiepoo** [comment]
Probably fallout from ec15362770b85bc3b08e6ee7f011a9a730d1f810 - I don't think xz is a default tool but it's probably used to achieve better compression which can be important :|

But building without installing xz is also important. Should we have some sort of fallback @kornelski ?

**Comment by kornelski** [comment]
xz has a larger window (64MB?) than bzip2 (900K) and gzip (32K), so it dedupes Swift tools and debug files much better.

I forgot that macOS out of the box only supports decompressing xz.

Archive urls are referenced by the appcast, so be careful with the fallbacks.
