### ISSUE TITLE
Prevent update based on minimum OS requirement

### ISSUE THREAD

**Issue by XericDesign** [sparkle-project/Sparkle#1638]
Our app currently has a minimum requirement of OS 10.11. The next version will move this requirement to 10.12. I would like Sparkle to notify the user of the update, but not allow them to actually perform the update, indicating that they need a minimum OS of 10.12.

I was hoping there would be a way to put a minimum OS requirement in the Sparkle feed with sparkle:minimumSystemVersion, but still show the update is available to people if they upgrade their OS.

**Comment by kornelski** [comment]
minimumSystemVersion is supposed to do exactly that.

**Comment by XericDesign** [comment]
The docs say "If an update to your application raises the required version of macOS, you can only offer that update to qualified users."

Will it still open a window to say that an update is available, even if their OS won't support it?

**Comment by kornelski** [comment]
If user runs "Check for updates" manually, it'll say it's the latest version for their OS, but that there is a newer version for newer OS.
