### ISSUE TITLE
SUAutomaticallyUpdate doesn't seem to be picked up from Info.plist

### ISSUE THREAD

**Issue by trevordevore** [sparkle-project/Sparkle#1639]
Based on my reading of the [Customizing Sparkle](https://sparkle-project.org/documentation/customization/) page an app should be able to add the `SUAutomaticallyUpdate` key to the `Info.plist` and Sparkle will pick it up and return the value from `automaticallyDownloadsUpdates`. Based on my testing this doesn't seem to be accurate as `automaticallyDownloadsUpdates` always returns `NO` unless I manually set the defaults using `defaults write com.trevordevore.app-updater-macos SUAutomaticallyUpdate -bool YES`.

I looked at the 1.x source code for use of `SUAutomaticallyUpdateKey` to see how `SUAutomaticallyUpdateKey` is being used in `automaticallyDownloadUpdates`. I found the following line:

```
return [self.host boolForUserDefaultsKey:SUAutomaticallyUpdateKey];
```

If I'm reading the code correctly, `boolForUserDefaultsKey` doesn't attempt to use the `Info.plist`. Perhaps that line should be `[self.host boolForKey:SUAutomaticallyUpdateKey];`? I see that `SUFeedURLKey` is accessed using `[self.host objectForKey:SUFeedURLKey];` and that setting is properly picked up from my `Info.plist` file.

**Comment by kornelski** [comment]
I think originally the intention was to ask user first. But I don't mind if you change it to take the default from Info.plist (but ideally also respect when user opts out)

**Comment by trevordevore** [comment]
Okay. I'll work on a PR that changes it to use `[self.host boolForKey:SUAutomaticallyUpdateKey];`. That should allow the preference to override the Info.plist. In my case I'm working on applications that are connected to cloud services and need to always be kept up to date. I need the app to behave more like a web application wherein the user gets the lates version each time they log into the website.
