### ISSUE TITLE
Provide option to specify release notes url for generate_appcast

### ISSUE THREAD

**Issue by andalman** [sparkle-project/Sparkle#1642]
We have an app where the `SUFeedURL` points to a location on our own server. However, we prefer to host our updates and release notes on S3.

The `--download-prefix-url` argument ( #1569 ) to `generate_appcast` solves the first problem – where to find the updates – nicely. However, there currently isn't a way to specify a URL prefix for release notes.

It would be great if there were an argument, say `--release-notes-prefix-url`, that behaves like the "download prefix" argument, but works for release notes.

If you agree, I can submit the pull request.

**Comment by kornelski** [comment]
Yes, please make a PR

**Comment by yeahdongcn** [comment]
When can we release this? It looks very useful for us.
Thanks @andalman for providing the new feature.
