### ISSUE TITLE
Problem with order of version items in the appcast in 1.23?

### ISSUE THREAD

**Issue by lostminds** [sparkle-project/Sparkle#1643]
I just updates from 1.22 to 1.23 and I've discovered what might be a bug in 1.23, indicating it now seems to assume the items in the appcast are ordered in some way, or perhaps only looking at the first item.

I have my appcast set up with a number of versions for different <sparkle:minimumSystemVersion>. I had these in chronological release order, for example:
v 2.2.1 for macOS 10.10
v 2.2.9 for macOS 10.11
v 2.3.3 for macOS 10.12
Which worked fine in Sparkle 1.22 and seemed to find the right update (latest fitting the user OS).

However, after updating to 1.23 if I check for new versions with the latest version installed it now only seems to find the first version in the appcast (2.2.1 in the example), saying in the message that I'm up to date and that 2.2.1 is the latest available version. However, if I change my appcast to have the 2.3.3 item first, the sparkle message now says 2.3.3 is the latest version available. 

So, it seems that at least at some point Sparkle is now just looking at the first item in the list? Or could it be some other change between 1.22 to 1.23, for example regarding how dates or versions are expected to be formatted which means it's now failing to order the versions correctly to figure out which one is the newest? Below you can see an example of how I've formatted an item now. 

```
<item>
<title>Version 2.3.3</title>
<description>
(DESCRIPTION CUT OUT)
</description>
<pubDate>2020-08-27</pubDate>
<sparkle:minimumSystemVersion>10.12</sparkle:minimumSystemVersion>
<enclosure url="https://www.lostminds.com/versiondata/sparkle/downloads/patternodes2.3.3.dmg" sparkle:version="2.3.3" length="24222106" type="application/octet-stream"/>
</item>
```

**Comment by kornelski** [comment]
It was probably this change:

https://github.com/sparkle-project/Sparkle/commit/8f6c7ccdebf5b6a6d04fcb0dc88f95a541e37755

**Comment by lostminds** [comment]
Could well be, I'm not familiar enough with the code to know. Should be easy enough to test though, just set up a couple of test appcasts with the same version items in different order and see if they return the same latest version.

If they do, then something else must be causing the problem in my case and I'm willing to try other things if you have ideas to help figure out why changing the order mattered in my case. Been a while since 1.23 as well, so maybe it's time for a 1.24?

**Comment by kornelski** [comment]
Try using valid dates in the RSS feed. RSS dates are supposed to be in a crappy RFC1123 format, not the simple ISO 8601 format.

**Comment by lostminds** [comment]
When you write RSS feed dates, you mean the appcast <pubDate> field dates should be in RFC 1123 format?
And that is the full "D, d M Y H:i:s O"? like "Tue, 01 Sep 2020 08:49:37 GMT"

**Comment by kornelski** [comment]
yes

**Comment by lostminds** [comment]
Yeah, that seemed to do the trick. With the pubDate fields in full "Tue, 01 Sep 2020 08:49:37 GMT" format it now seems to find the latest version regardless of order in the appcast. Thanks for the quick help!

As I'm generating the appcast in php on the server based on data about the versions in another system (where the dates are in ISO format) that's fine with me as I just need to convert them. But I think it would be nice if Sparkle was a bit more lenient on the date formatting as the required format above is a bit of a pain to enter manually for people updating their appcasts manually. Also, shouldn't the version number take precedent over the dates regardless, and especially if Sparkle fails to read the dates because they're the wrong format? I mean version 2.3.3 should still be greater than 2.2.1 even if the dates aren't formatted properly?

**Comment by kornelski** [comment]
Yeah, it's the `[item.date compare:candidate.date] == NSOrderedAscending` part that breaks it when the date is `nil`. It should check if the date is not nil.

Can you submit a PR?

**Comment by lostminds** [comment]
Ah, good find. Unfortunately I'm not hooked up to the Sparkle git and don't have the source code downloaded, so I can't submit a pull request. I have this git-account for another project I'm involved in. So I'd appreciate it if you or someone else could do the change and pull request.

**Comment by zorgiepoo** [comment]
Sparkle really shouldn't be comparing dates at all. That's a step backwards. That should be unrelated to supporting SHAs

**Comment by zorgiepoo** [comment]
> Also, shouldn't the version number take precedent over the dates regardless...

I think you were using a version of Sparkle older than master which resolved that (#1572)

> and especially if Sparkle fails to read the dates because they're the wrong format

although as kornel says that might not be handled when identical versions exist. Small edge case.

**Comment by lostminds** [comment]
Ah, so it might already be resolved in the master then. As I wrote this was in the current latest release 1.23 just like the issue your referred to. If you can confirm this is already fixed, please close this issue.

I'm not sure what you mean with supporting SHAs. As I see it the items in the appcast should primarily be sorted by version number, but if that fails for whatever reason (same version, missing version, strangely formatted version) sparkle could fall back on publishing date instead to find the latest version by date. And in this situation it would be nice if it could accept dates that are in other formats than the full "Tue, 01 Sep 2020 08:49:37 GMT".

**Comment by zorgiepoo** [comment]
I just have the tiny opinion that it shouldn't even fall back on dates :). I tried to remove date comparison long ago for reasons like this, but it got contributed back for a strange not-so-valid case.

1.23.0 was released in Feb according to releases. That fix merged in May.

**Comment by lostminds** [comment]
Yeah, I guess that if it's difficult to compare dates correctly, perhaps not comparing them at all would be a better option.

Either way, since the original issue here already seems to be fixed in master back in May then I'll close this issue. Thank for all the help @kornelski and @zorgiepoo !
