### ISSUE TITLE
generate_appcast doesn't always update release notes when --release-notes-url-prefix is used

### ISSUE THREAD

**Issue by andalman** [sparkle-project/Sparkle#1647]
With the addition of `--release-notes-url-prefix` (#1642), it is now possible for multiple runs of `generate_appcast` to create differing release notes URLs for the same archive update. (Before this fix, the release notes URL was always determined by the archive's `SUFeedURL` and, therefore, was unlikely to change across `generate_appcast` runs.)

However, if the appcast file isn't deleted between runs, `generate_appcast` will *not* update the release notes URLs in  the appcast. Here's a (contrived) example:
- Run `generate_appcast --release-notes-url-prefix http://oops.com/ folder-of-archives/`
- Open the `appcast.xml` file and confirm that it contains items with release notes URLs that begin with `http://oops.com`
- Notice that you didn't mean to type `http://oops.com`
- Immediately re-run `generate_appcast` using the correct prefix
- Open the `appcast.xml` file and notice that the release notes URL prefixes still begin with `http://oops.com`

I have a fix, and can submit a PR if desired.

**Comment by kornelski** [comment]
Yes, please submit a fix
