### ISSUE TITLE
[Question] How does sparkle ensure that "usage statistics reports" are  sent by sparkle.

### ISSUE THREAD

**Issue by snktagarwal** [sparkle-project/Sparkle#166]
Hi,

My questions is much more of a information query. In the wiki about Usage Statistics you have said that Sparkle enabled client can trigger a GET request to the appcast url like: http://you.url/app.xml?cpu=...&.. ! What if a bot manually triggers such a request, won't that be a problem ?

**Comment by zorgiepoo** [comment]
I don't know of a way of tackling this and this hasn't been brought up since.
