### ISSUE TITLE
Swift Package Dependencies are not working

### ISSUE THREAD

**Issue by ProfDrLuigi** [sparkle-project/Sparkle#1663]
Tried to add Sparkle to SPD. I get this error:

![grafik](https://user-images.githubusercontent.com/45099401/95662163-40025900-0b35-11eb-848a-c5126b84fa9c.png)

**Comment by jaelsasser** [comment]
You can't pull the v1.23.0 Sparkle library down via SPD. Swift Package Manager support [only merged recently](https://github.com/sparkle-project/Sparkle/pull/1634) and isn't yet in any released versions of Sparkle.

**Comment by alex-taffe** [comment]
@jaelsasser do you happen to have a rough time estimate of 1.24.0 being available with that patch?

**Comment by thebluepotato** [comment]
@alex-taffe 1.24.0 has been released
