### ISSUE TITLE
Timed out while probing installer info data

### ISSUE THREAD

**Issue by JosephDuffy** [sparkle-project/Sparkle#1665]
I have setup my project with Sparkle 2 in a similar way to https://christiantietze.de/posts/2019/06/sparkle-xpc-setup/:

I have Sparkle added as a submodule with the Xcode project referenced in my project.

I link and embed the Sparkle.framework and embed the InstallerConnection, InstallerLauncher, InstallerStatus XPC services. At the end of the build phrases I have a script for the signing:

```sh
#!/bin/sh
# Signs the Sparkle XPC Services and Framework. This script expects to be run from within an Xcode build.
set -e

SPARK_FRAMEWORK_PATH="${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Sparkle.framework"

"${PROJECT_DIR}/Frameworks/Sparkle/bin/codesign_embedded_executable" "${EXPANDED_CODE_SIGN_IDENTITY_NAME}" "${BUILT_PRODUCTS_DIR}/${XPCSERVICES_FOLDER_PATH}"/org.sparkle-project.*.xpc
"${PROJECT_DIR}/Frameworks/Sparkle/bin/codesign_embedded_executable" "${EXPANDED_CODE_SIGN_IDENTITY_NAME}" "${SPARK_FRAMEWORK_PATH}/Versions/A/Resources/Autoupdate"
"${PROJECT_DIR}/Frameworks/Sparkle/bin/codesign_embedded_executable" "${EXPANDED_CODE_SIGN_IDENTITY_NAME}" "${SPARK_FRAMEWORK_PATH}/Versions/A/Resources/Updater.app"
"${PROJECT_DIR}/Frameworks/Sparkle/bin/codesign_embedded_executable" "${EXPANDED_CODE_SIGN_IDENTITY_NAME}" "${SPARK_FRAMEWORK_PATH}"
```

In my AppDelegate I create and store the updater:

```swift
let standardUserDriver = SPUStandardUserDriver(hostBundle: .main, delegate: self)
sparkleUpdater = SPUUpdater(
	hostBundle: .main,
	applicationBundle: .main,
	userDriver: standardUserDriver,
	delegate: self
)
try? sparkleUpdater.start()
```

This alone creates some logs:

```
[Sparkle] Timed out while probing installer info data
[Sparkle] Timed out while probing installer progress
```

I have a menu item that when selected calls `sparkleUpdater.checkForUpdates()`. This call correctly checks for updates but the update check progress alert does not appear until the appcast has been fully downloaded, at which point the progress alert flashes up for a second and then the changelog/install update window is shown.

None of the `SPUStandardUserDriverDelegate` methods appear to be called. Below is a full output from clicking a check for updates button when I log the delegate calls:

```
2020-10-15 20:20:50.069819+0100 AppName[44173:1311570] [Sparkle] Timed out while probing installer info data
2020-10-15 20:20:50.070491+0100 AppName[44173:1311570] [App Delegate] updater(_:willScheduleUpdateCheckAfterDelay:)
2020-10-15 20:20:52.540402+0100 AppName[44173:1311570] [Sparkle] Timed out while probing installer progress
2020-10-15 20:20:52.540798+0100 AppName[44173:1311570] [App Delegate] updater(_:shouldAllowInstallerInteractionFor:)
2020-10-15 20:20:52.541983+0100 AppName[44173:1311570] [App Delegate] updaterMayCheck(forUpdates:)
2020-10-15 20:20:52.544891+0100 AppName[44173:1311570] [App Delegate] feedParameters(for:sendingSystemProfile:)
2020-10-15 20:20:52.694354+0100 AppName[44173:1311570] [App Delegate] Updater loaded appcast
2020-10-15 20:20:52.694539+0100 AppName[44173:1311570] [App Delegate] bestValidUpdate(in:for:)
2020-10-15 20:20:52.694780+0100 AppName[44173:1311570] [App Delegate] versionComparator(for:)
2020-10-15 20:20:52.695228+0100 AppName[44173:1311570] [App Delegate] versionComparator(for:)
2020-10-15 20:20:52.695481+0100 AppName[44173:1311570] [App Delegate] updater(_:didFindValidUpdate:)
2020-10-15 20:20:52.695598+0100 AppName[44173:1311570] [App Delegate] updaterShouldDownloadReleaseNotes(_:)
```

Are these errors and the progress alert not being shown linked? Have I setup something incorrectly to cause this?

**Comment by zorgiepoo** [comment]
Does it work if you run the app outside of Xcode (don't debug it from Xcode)?

Or if you edit the scheme and disable the option that debugs XPC services.

**Comment by JosephDuffy** [comment]
> Does it work if you run the app outside of Xcode (don't debug it from Xcode)?
> 
> Or if you edit the scheme and disable the option that debugs XPC services.

Yep, it works in both of those scenarios! I have my own XPC service so will have to live with this as a minor UI bug during development 😊

I'm new to macOS development so sorry if this should've been obvious.

Feel free to close if this isn't worth/can't be fixed.

**Comment by zorgiepoo** [comment]
Mm, it's not obvious. I'm guessing it's a bug in Xcode. I submitted FB8808625 over to Apple with a sample project.

**Comment by vuvantoan95** [comment]
hi @JosephDuffy . In my AppDelegate.swift, but got this error. Please help!
![Uploading Screen Shot 2020-11-09 at 3.17.12 PM.png…]()

**Comment by JosephDuffy** [comment]
> hi @JosephDuffy . In my AppDelegate.swift, but got this error. Please help!
> ![Screen Shot 2020-11-09 at 3 17 12 PM](https://user-images.githubusercontent.com/16610569/98516533-38061800-229f-11eb-90f9-a6ac4f3c4938.png)

This was not intended to be copy/pasted and used in a project, but to show some context around the issue.

There are many issues this could be, from a missing `import Sparkle` to your app delegate not conforming to `SPUStandardUserDriverDelegate`, but it does not look related to the issue this topic is about.

**Comment by zorgiepoo** [comment]
The trigger / cause for this issue is documented now in https://sparkle-project.org/documentation/sandboxing/ under "Testing"

**Comment by zorgiepoo** [comment]
Errors are logged better and documentation is more up to date regarding this issue.
