### ISSUE TITLE
Which website is more reliable to put the XML/HTML file on?

### ISSUE THREAD

**Issue by CloseServer** [sparkle-project/Sparkle#1666]
I think someone put it on raw.githubusercontent.com, why not use GitHub?

**Comment by kornelski** [comment]
Theoretically any URL will work if it can handle enough traffic for the number of users your app has, and since it's just a static file, that's not difficult.

However, I think GitHub doesn't like people using `raw.githubusercontent.com` as their website. You can use github.io site.

**Comment by CloseServer** [comment]
@kornelski 
Okay, thank you!
