### ISSUE TITLE
error from app using Sparkle

### ISSUE THREAD

**Issue by metropical** [sparkle-project/Sparkle#1669]
I had installed CheatSheet which apparently used Sparkle to update.
But Ive uninstalled Cheatsheet and I'm getting an error from Sparkle.

"For security reasons, CheatSheet needs to be code-signed or its updates need to be signed with an EdDSA key. See https://sparkle-project.org/documentation/ for more information."

I guess when I deleted CheatSheet with App Delete, it either dumped too much or not enough.

Would someone please help me lose this intermittent error?
I can't find anything in any of the libraries that related to either Sparkle or CheatSheet.

There this from Activity Monitor.
https://live.staticflickr.com/65535/50575258798_4be0e8e520_z.jpg
Obviously, only part of the log.

**Comment by invariant** [comment]
Based on the screenshot, Cheat Sheet is in your trash and it is running from there. 

I recommend a reboot and an emptying of the trash.

**Comment by metropical** [comment]
appreciate you're input, but alas that ain't it.
I do that on a daily basis.  Nothing in the trash.

**Comment by pilotmoon** [comment]
The screenshot you posted indicates there is something at the path /Users/fritz/.Trash/CheatSheet.app

**Comment by metropical** [comment]
yup, can't figure it out.  Did a show/hide as well.  Nothing there.
Launched Activity Monitor again to see if it turns up again.
I'll post more info when it does.

**Comment by metropical** [comment]
I unhide files.  Still saw nothing.  Secure emptied the trash for a 2nd time. Restarted.
So far, so good.  Weird.

**Comment by mcsrainbow** [comment]
Just because the CheatSheet.app was not stopped before the uninstallation. 

```
❯ ps aux | grep -i cheatsheet
... /Applications/CheatSheet.app/Contents/MacOS/CheatSheet

❯ pkill -kill -f CheatSheet.app
```

**Comment by jakobhviid** [comment]
> Just because the CheatSheet.app was not stopped before the uninstallation.
> 
> ```
> ❯ ps aux | grep -i cheatsheet
> ... /Applications/CheatSheet.app/Contents/MacOS/CheatSheet
> 
> ❯ pkill -kill -f CheatSheet.app
> ```

This worked for me. Thank you.
