### ISSUE TITLE
Update Error!

### ISSUE THREAD

**Issue by ghost** [sparkle-project/Sparkle#167]
Great Tool!
thx so much for making this!
I'm a newbie and was still able to follow the instructions to get it up and running......8)

Well, for the most part.  I did hit one snag.
I got every thing going down to checking for the AppCast.xml and it shows that I have an update and displays my list of changes.
But when I hit "Update" I get   "An error occurred while downloading the update. Please try again later."
I tripple checked and the download link inside the .xml is valid and I did follow the instructions on how to sign it and added that string into the .xml also.

Any ideas of what else to check for to get this final step to work?

thx!

Steve

**Comment by cherpake** [comment]
Having issues as well:

2016-06-10 06:17:55 +0000: Error: An SSL error has occurred and a secure connection to the server cannot be made. (null) (URL https://tiny.cc/macrc)
2016-06-10 06:17:55 +0000: Error: An SSL error has occurred and a secure connection to the server cannot be made. (null) (URL https://tiny.cc/macrc)
 
Their cert. seems OK, and the site it redirects as well (wordpress.com)
