### ISSUE TITLE
Breakage 1.23 - "Remind me later" button not visible when SUEnableAutomaticChecks is set dinamically

### ISSUE THREAD

**Issue by nicolasbosi95** [sparkle-project/Sparkle#1671]
**Observed in Release:** 1.23.0

**First observed in Release:** 1.23.0

**Description**

- There's a non-critical update available for my app.
- Key SUEnableAutomaticChecks is either set to NO or just not set in Info.plist.
- Key SUEnableAutomaticChecks is set in runtime to YES by calling -[SUUpdater setAutomaticChecksEnabled:BOOL]

**Expected behavior:** In this scenario, when showing the Update Alert, I expect the "Remind me later" button to be available (As it was in previous releases).

**Actual behavior:** When showing the Update Alert, button "Remind me later" is hidden.

**Context**

This was a breaking change introduced by #1480 .
I have pointed out the reason why this is happening in [this comment](https://github.com/sparkle-project/Sparkle/pull/1480#issuecomment-724157172).
This issue is created to formally keep track of this broken behavior, and to track its fix in next releases as well.

**Comment by kornelski** [comment]
Could you make a PR with the fix?

**Comment by nicolasbosi95** [comment]
I tried, but couldn't push the side branch.

> remote: Permission to sparkle-project/Sparkle.git denied to nicolasbosi95.
> fatal: unable to access 'https://github.com/sparkle-project/Sparkle.git/': The requested URL returned error: 403

Local repo config:

[remote "origin"]
	url = https://nicolasbosi95:*****@github.com/sparkle-project/Sparkle.git
	fetch = +refs/heads/*:refs/remotes/origin/*

**Comment by kornelski** [comment]
Use github's Fork feature and push to your repo

**Comment by nicolasbosi95** [comment]
PR created: https://github.com/sparkle-project/Sparkle/pull/1672
