### ISSUE TITLE
XPC Services for Apple Silicon?

### ISSUE THREAD

**Issue by guidedways** [sparkle-project/Sparkle#1675]
Happy to see Apple Silicon support, is this coming to the UI separation branch?

**Comment by kornelski** [comment]
It should already work in 2.x too.

**Comment by guidedways** [comment]
I'm sorry, I couldn't find anything on this in the documentation. So 2.x works for sandboxed apps without the need for XPC services? I don't see any XPC outputs in 2.x. I only see these in the UI-seperation branch. That seems to work if I compile the project for Apple silicon myself.

**Comment by kornelski** [comment]
ui-separation-branch is 2.x. It works with sandbox. It is built using XPC.

Apple Silicon requires no changes. It just works as-is if you build it using Xcode 12.2.
