### ISSUE TITLE
Source code misses ed25519 sources

### ISSUE THREAD

**Issue by hofman** [sparkle-project/Sparkle#1678]
The ed25519 sources are still missing in the sources of the releases. This makes it impossible to compile Sparkle myself.

**Comment by fedeci** [comment]
Have you tried running 'git clone' with the '--recursive' flag?

**Comment by hofman** [comment]
I am not talking about the git repository, but the distribution.

Christiaan

Op do 19 nov. 2020 20:10 schreef Federico Ciardi <notifications@github.com:

**Comment by kornelski** [comment]
The source code .zip created by GitHub is broken. I've reported the bug to them. They like it broken like this, and I have no option to hide the links to buggy archives they make.

Please use recursive clone, and never rely on zips or tarballs created by GitHub.
