### ISSUE TITLE
Determine what app is throwing error

### ISSUE THREAD

**Issue by gajahduduk** [sparkle-project/Sparkle#1680]
Periodically I am getting this dialog on MacOS Mojave (10.14.6):

"You must specify the URL of the appcast as the SUFeedURL key in either the Info.plist or the user defaults!"

It only has a cancel button. 

How do I determine what app is throwing that error??  It is coming up maybe 2x per day?

**Comment by zorgiepoo** [comment]
In more recent versions we include the name of the app in the message.
