### ISSUE TITLE
Sparkle framework bundled twice when installed via SPM

### ISSUE THREAD

**Issue by Eitot** [sparkle-project/Sparkle#1689]
I noticed in two projects that Sparkle is bundled twice in the app bundle when installed as a binary target using SPM. In one project it is copied to both Contents/Frameworks and to Contents/SharedSupport, in another to Contents/Frameworks and Contents/Resources. I am not sure why there is a difference, though the first project uses the SharedSupport directory already.

This not just wastes some space, but it also causes weird build issues in Xcode that can only be resolved by clearing the build folder and/or reopening the Xcode project:
![image](https://user-images.githubusercontent.com/15073177/100521776-f7b2ff00-31a5-11eb-90aa-bf4cbca630f5.png)

Is this something that can be resolved on Sparkle’s end or is this an issue with Xcode?

**Comment by kornelski** [comment]
@thebluepotato can you help?

**Comment by gregcotten** [comment]
Eeeek this is a known issue with Swift Package Manager and Xcode... You have to manually remove these frameworks with a Build Phase Script like they are [doing with Firebase](https://github.com/firebase/firebase-ios-sdk/issues/6472), as an example.

**Comment by WowbaggersLiquidLunch** [comment]
> this is a known issue with Swift Package Manager and Xcode

Is there a ticket on Swift Jira? I tried searching for it, but couldn't find any.

**Comment by Eitot** [comment]
I found this bug report, which seems to cover it: https://bugs.swift.org/browse/SR-13840

**Comment by WowbaggersLiquidLunch** [comment]
Kevin Bui on the Swift Forums provided a workaround 2 weeks ago: https://forums.swift.org/t/swift-package-binary-framework-issue/41922/3

**Comment by Eitot** [comment]
This appears to be resolved by Xcode 12.5 (see the links above). It no longer occurs in my projects.
