### ISSUE TITLE
"Damaged app" in Big Sur being caused by Sparkle

### ISSUE THREAD

**Issue by chockenberry** [sparkle-project/Sparkle#1691]
We've been getting reports from customers about downloads of our app being "damaged" after being downloaded and opened for the first time.

Today, I tracked this issue down to something in Sparkle (we're using version 1.18.1). It appears that two files in the signed framework are causing the issue.

```
% codesign -vvvv ./Sparkle.framework/ 
./Sparkle.framework/: a sealed resource is missing or invalid
file added: /Users/CHOCK/Downloads/xScope.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/._fr_CA.lproj
file added: /Users/CHOCK/Downloads/xScope.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/Updater.app/Contents/Resources/._fr_CA.lproj
file added: /Users/CHOCK/Downloads/xScope.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/Updater.app/Contents/Resources/._pt.lproj
file added: /Users/CHOCK/Downloads/xScope.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/._pt.lproj
```

Both of these files are symlinks to other localization resource (French Canadian to French, Portuguese to Brazilian Portuguese). Note also that the files that are breaking the signature begin with "._" - these are files used to store extended attributes, such as com.apple.FinderInfo.

What's weird about this issue, and why we didn't see it in our testing, is that it only happens in Google Chrome. Safari is doing something (like maybe ignoring/removing extended attributes) before the signature check.

Our workaround for customers is to tell them to use Safari for the download, but it would be much better to fix the issue at the source.

**Comment by chockenberry** [comment]
Thanks to @danielpunkass for helping me dig into the cause of this issue!

**Comment by chockenberry** [comment]
The best solution here would probably be an additional build step that removes any unnecessary attributes. Something along the lines of

`$ ditto Sparkle.framework Sparkle-clean.framework`

(This technique can also be used to fix the app so it passes the code signing checks.)

**Comment by chockenberry** [comment]
Another piece of information: it appears the culprit is actually Archive Utility - Safari has it's own ZIP extraction for "safe download" and this circumvents the system utility.

If you turn off Safari's safe downloads feature, you'll see the same damaged app as with Chrome.

**Comment by kornelski** [comment]
We've removed that symlink years ago. Please use a recent version of Sparkle.

**Comment by kornelski** [comment]
I thought that I've got rid of that symlink :/ It used to cause problems even in Sparkle 1.5.

**Comment by kornelski** [comment]
Gone in d4d4c68ad2e11ecdf21b2a71d45710cec4834c0c

**Comment by danielpunkass** [comment]
Kudos @kornelski for folllowing up so quickly on this!

**Comment by chockenberry** [comment]
👍 Thanks for the quick response here.

**Comment by zorgiepoo** [comment]
Just a late fyi, this was addressed in `2.x` in #1722 (paths here look like they *might* be using 2.x)
