### ISSUE TITLE
No callback when cancel fetch Appcast

### ISSUE THREAD

**Issue by colin1994** [sparkle-project/Sparkle#1692]
```
- (void)appcastDidFinishLoading:(SUAppcast *)ac
{
    if (self.isCanceled)
    {
        [self abortUpdate];
        return;
    }
    [self closeCheckingWindow];
    [super appcastDidFinishLoading:ac];
}
```

During the **fetchAppcastFromURL** process, if cancel is clicked, it will abort directly. There is no callback.

We want to get this status, is it feasible? 
Thank you!

**Comment by zorgiepoo** [comment]
There's a delegate method when the user driver session ends but not specifically for this. I don't think there should be a strong need for this unless there's some good reason I'm missing.
