### ISSUE TITLE
bz2 gone from 1.24.0 release?

### ISSUE THREAD

**Issue by mat007** [sparkle-project/Sparkle#1693]
~~It looks like https://github.com/sparkle-project/Sparkle/releases does not list 1.24.0 anymore.
Also the tag for 1.24.0-spm suspiciously says 1.24.0~~

Was this intended?

**Comment by kornelski** [comment]
I see 1.24.0 there. 

GitHub's UI presents releases in their own way, which isn't configurable, and they sometimes do weird things with hiding tags. Don't treat GitHub's UI as authoritative. When in doubt, check actual tags in a git client.

Same goes for GitHub's source tarballs in releases — they're broken, and we can't fix them. Only the git protocol can be trusted.

**Comment by mat007** [comment]
Sorry, my initial comment was wrong, I skimmed the releases page too hastily.

The reason I was asking was because our CI used to download https://github.com/sparkle-project/Sparkle/releases/download/1.24.0/Sparkle-1.24.0.tar.bz2 but it seems to have vanished about 10h ago or so.
It’s fine we switched to the .xz now but I was wondering if this was intentional or not.

**Comment by kornelski** [comment]
The switch was intentional. It's going to be .xz from now on. That bz2 existed, because I've accidentally uploaded a bz2 version *and deleted it* from GitHub's UI. I guess they've had it cached anyway.

**Comment by mat007** [comment]
Right, thanks for the clarification!
