### ISSUE TITLE
Lost private key, can't get updates to work

### ISSUE THREAD

**Issue by clementukn** [sparkle-project/Sparkle#1695]
I reinstalled my system and I've lost the private key (_k1_) I've been using as the **SUPublicEDKey** on my app. Latest version of the app that used _k1_ is A.

I read this [thread](https://github.com/sparkle-project/Sparkle/issues/1070) so I generated a new key (_k2_), added _k2_ public in the Info.plist of the app and got version _B_ notarized.

When running _A_ and checking for updates I do see "New version _B_ available" but when I download and install it I get an error "Update error. Failed to extract update".

What can i do?

**Comment by invariant** [comment]
The problem is that all of your app instances "in the wild" have your old public key, so they see your new updates as invalid even though you signed them with the new private key.

You are going to have to ask your users to manually install the new version.

(We've all done this once in our career, I think. Some of us more than once...)

**Comment by clementukn** [comment]
thanks @invariant, yeah that's what I saw in the other thread that could change of the two. Unfortunately it doesn't seem to work for me and I'm wondering why. 
Not sure if there's something particular to do when you change the EdDSA signature while keeping the same Apple code-sign.

**Comment by invariant** [comment]
I had a dive into the code. The crucual secion is here:
https://github.com/sparkle-project/Sparkle/blob/02d0d749a006752403a2ab0120033af7912d063f/Sparkle/SUUpdateValidator.m#L186

It looks like as long as the new update is correctly signed with the new key, and both apps are correctly Apple codesigned with the same codesigning identitier, you should be good to go.

**Comment by clementukn** [comment]
oh nice, thanks for that. I need to look at what is behind the passedCodeSigning, maybe there's something I'm missing there but since it's notarized by Apple I thought it'd be enough.

**Comment by invariant** [comment]
Looking at `+[SUCodeSigningVerifier codeSignatureAtBundleURL:matchesSignatureAtBundleURL:error:]`, the new version has to be signed using the exact same certificate as the old version. (It doesn't check notarization.) If you generated a new code signing certificate after reinstalling your system, this could explain the problem.

1: https://github.com/sparkle-project/Sparkle/blob/04dbde7b8d436b50b421c5262fc65c2ef8a05aed/Sparkle/SUCodeSigningVerifier.m#L19,

**Comment by clementukn** [comment]
Forgot to update this, it worked as expected: I signed the new version of my app with my regular Apple certificate and a newly created Sparkle key. The old version was able to pick the update even if the Sparkle keys were different since the Apple certificate was the same.

Thanks again @invariant for your help!

**Comment by AmyXS** [comment]
Hmm I'm struggling to get this to work.. I used a new Sparkle key, and signed the .app and the installer (.dmg) with my existing certificate. And distributing the .dmg file. Do I need to code sign the .delta file to get Sparkle to pick up the code sign?

**Comment by zorgiepoo** [comment]
if the .app bundle of the new and old updates is signed with the same Apple Developer ID certificate (typically used for release/deployment), it will work.
