### ISSUE TITLE
Sparkle framework 1.24 - Apple Silicon support

### ISSUE THREAD

**Issue by MajuMadhusudanan** [sparkle-project/Sparkle#1700]
Hi,

How do I integrate sparkle framework into my Xcode project? I tried to integrate it using Swift Package Manager  and it throws error.

The following steps are used for integrating it:

1. Open Xcode 12.2
2. Click on File -> Swift Packages -> Add Package Dependency 
3. Put the following URL - https://github.com/sparkle-project/Sparkle.git

4. Click on Next button, Xcode throws error

Please find the attached screenshot. I'm seeing the attached error when I try to link sparkle framework using packages dependency option in Xcode.,

<img width="729" alt="Screenshot 2020-12-18 at 5 36 03 PM" src="https://user-images.githubusercontent.com/23079368/102612856-838dca80-4157-11eb-8803-4fcd899514be.png">

How  do I fix this issue? I want to integrate sparkle framework which supports universal app.

**Comment by MajuMadhusudanan** [comment]
Here are the steps for replicating it:

- Open Xcode 12.2
- Click on File -> Swift Packages -> Add Package Dependency
- Put the following URL - https://github.com/sparkle-project/Sparkle.git
- Click on Next button, Xcode throws 'Package Resolution Failed' error

**Comment by kornelski** [comment]
Yes, this is a known issue: https://github.com/sparkle-project/Sparkle/issues/1674#issuecomment-727639670

**Comment by MajuMadhusudanan** [comment]
@kornelski : Any fix for this issue? what is the alternate way to resolve this issue?
