### ISSUE TITLE
Build of 1.24.0 fails with ld: library not found for -lbsdiff

### ISSUE THREAD

**Issue by jeremyhu** [sparkle-project/Sparkle#1716]
This is a continuation of #1534.  As mentioned in that ticket, the ticket was closed despite this being an issue.  I just reproduced this myself with a fresh build from the 1.24.0 tag.

Linking of Sparkle fails with:

     ld: library not found for -lbsdiff

Because bsdiff is not listed as a dependency of Sparkle in the Xcode project.  ed25519 is similarly not listed.

**Comment by jeremyhu** [comment]
Trivial to fix.  Just add bsdiff and ed25519 to the target dependencies of Sparkle.

**Comment by kornelski** [comment]
I'm having a deja-vu. I thought I've seen this problem already, and added them.

**Comment by grit96** [comment]
Looks like this was fixed in https://github.com/sparkle-project/Sparkle/commit/d5b0804b4a659ccb78c02acf56576fb08ce5d4d7 but not released yet.

I ran into the same issue trying to build generate_appcast with Carthage on v1.24.0.

**Comment by zorgiepoo** [comment]
This should be fixed in top of master (or 1.25.0 when it's released).
