### ISSUE TITLE
Can't add Sparkle to SPM

### ISSUE THREAD

**Issue by KrisConrad** [sparkle-project/Sparkle#1718]
When trying to add Sparkle as a Swift Package I receive the following error:

```
artifact of binary target 'Sparkle' failed download: invalid status code 404
```

![Screen Shot 2021-01-07 at 10 11 04 AM](https://user-images.githubusercontent.com/20546595/103922364-dca2ab80-50d0-11eb-82fa-96c87a35ecbe.png)

**Comment by kornelski** [comment]
This is a known issue, which will be fixed in the next release. For now use the master branch as the version to fetch.
