### ISSUE TITLE
Instructions for properly using .pkg files for updates

### ISSUE THREAD

**Issue by zgerrard** [sparkle-project/Sparkle#1721]
Hi, 

README mentions that installation of `.pkg` files is supported. However, `generate_appcast` does not work with `.pkg` files because there is not enough meta information, such as version, short version, etc.  (i.e. there is no `Info.plist` for `.pkg` files: https://github.com/sparkle-project/Sparkle/blob/0c8b7f1d25e1e9d0410001bb075234d04ef4ba30/generate_appcast/ArchiveItem.swift#L88). Therefore, I was wondering what is the proper way to setup everything, so that I can distribute my updates via `.pkg` files? Am I missing something?

Thank you so much for your help in advance.

**Comment by zorgiepoo** [comment]
I don't think generate_appcast supports pkg. You'll need to zip/archive the pkg file, sign it, and write the appcast yourself. This page should be helpful https://sparkle-project.org/documentation/publishing/#publishing-an-update

**Comment by kornelski** [comment]
Indeed. `generate_appcast` doesn't support pkg, because it doesn't know how to get `Info.plist` out of a pkg file.
