### ISSUE TITLE
"Couldn't read values in CFPrefsPlistSource" during update extraction

### ISSUE THREAD

**Issue by zgerrard** [sparkle-project/Sparkle#1724]
Hi,

I am getting the following error when extracting update on 2.x:

> Couldn't read values in CFPrefsPlistSource<0x7ff5a7609650> (Domain: kCFPreferencesAnyApplication, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes): accessing preferences outside an application's container requires user-preference-read or file-read-data sandbox access

Any ideas?

Thank you in advance.

**Comment by zorgiepoo** [comment]
#1615
