### ISSUE TITLE
Unable to downgrade to a lower version

### ISSUE THREAD

**Issue by alamathe1** [sparkle-project/Sparkle#1738]
I am running into an issue where my  application on a higher version is not able to downgrade to a lower version, even though the AppCast points to a lower version and I have turned on the config to enabled downgrades at https://github.com/sparkle-project/Sparkle/blob/c3c1b1af9980d08a723d7f9925c7ed0ccd8da7d0/Configurations/ConfigCommon.xcconfig#L11.

After this Sparkle framework was complied by using `make release` and the tar contents were uploaded to the project.

The application is present with the message from : https://github.com/sparkle-project/Sparkle/blob/65eb63f1d79f9343b7a622982728276ec1baa738/Sparkle/SUUIBasedUpdateDriver.m#L134 which indicates that I am on a higher version that the latest version.

**Comment by kornelski** [comment]
Since downgrades are not supported by default, and AFAIK don't have tests, it's possible that this ability has bitrotten since we've added new features to "latest" version selection.

**Comment by zorgiepoo** [comment]
That option appears to have always been about installation not app cast selection. I don't really understand the motivation behind the flag. You might be able to "lie" in the app cast selection to get a downgrade.

**Comment by alamathe1** [comment]
@zorgiepoo Any pointers on how to achieve the downgrade?

**Comment by zorgiepoo** [comment]
Set your `sparkle:version` to something higher than your last shipping version, your `sparkle:shortVersionString` to the version string you want to display to users, then cross your fingers.

**Comment by zorgiepoo** [comment]
I don't know if this worked or not but we're not supporting downgrades in the future.
