### ISSUE TITLE
Force updating application without any prompt

### ISSUE THREAD

**Issue by alamathe1** [sparkle-project/Sparkle#1739]
I am trying to invoke a **forced** update on my application in order to avoid all the prompts thrown by Sparkle by using the following:

```
[[SUUpdater sharedUpdater] checkForUpdatesInBackground];
[[SUUpdater sharedUpdater] resetUpdateCycle];
[[SUUpdater sharedUpdater] installUpdatesIfAvailable];
```

I believe the update is successfully downloaded. But for reason it does not work without an app quit and always breaks at:

```
- (void)updater:(SUUpdater *)updater willInstallUpdateOnQuit:(SUAppcastItem *)item immediateInstallationInvocation:(NSInvocation *)invocation;
```

Any suggestions on how to handle this use-case (i.e don't throw any prompts) ?

**Comment by zorgiepoo** [comment]
If I recall correctly, `installUpdatesIfAvailable` is one of those APIs that should never be used (there are past issues on this).

If you want silent updates when it's possible (not possible eg when updates require authorization), you should turn on automatically downloading updates (`SUAutomaticallyUpdate` or `. automaticallyDownloadsUpdates`) and then check for updates in background.

Then you can use this more modern delegate method, and invoke the block to immediately perform the update.

`- (void)updater:(SUUpdater *)updater willInstallUpdateOnQuit:(SUAppcastItem *)item immediateInstallationBlock:(void (^)(void))installationBlock;`
