### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#1749]
@zorgiepoo OK to release?

**Comment by zorgiepoo** [comment]
Think we can get the non-archived pkg's? It's the last significant adoptive change I care about getting in 1.x.

WKWebView might be biggest exposed change, not sure if you're planning to do a pre-release for a bit or want to release directly.

Other than those two things, I don't see an issue.

**Comment by kornelski** [comment]
I haven't tested the pkg change, and I'd prefer to hold off with it. I'll make an RC release.

**Comment by kornelski** [comment]
https://github.com/sparkle-project/Sparkle/releases/tag/1.25.0rc1
