### ISSUE TITLE
The version tag 1.25.0rc1 is not readable by SwiftPM

### ISSUE THREAD

**Issue by WowbaggersLiquidLunch** [sparkle-project/Sparkle#1750]
SwiftPM is only able to understand semantic versioned tags. It's not able to understand the latest tag `1.25.0rc1`, but it should be able to understand `1.25.0-rc1`.

**Comment by kornelski** [comment]
I've renamed the tag. Did that help?

**Comment by thebluepotato** [comment]
Renaming the tag should help SPM but it seems the release script I wrote is not correctly updating the version number in Package.swift... It uses that number to construct the URL for the appropriate ZIP file so it's going to complain. I'll fix it ASAP

**Comment by thebluepotato** [comment]
Submitted a PR. Once merged, you should tag `1.25.0-rc2`, run `make release` and push to remote and SPM should *finally* work!
