### ISSUE TITLE
1.24 fails to link on Yosemite (due to code signing?)

### ISSUE THREAD

**Issue by herf** [sparkle-project/Sparkle#1752]
Here is a crash log from a f.lux user on Yosemite (10.10.5) with Sparkle 1.24--no problems with El Capitan or later (10.11+). We are using XCode 12.4's code signing and notarization.

Dyld Error Message:
  Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/USER/Desktop/Flux.app/Contents/MacOS/Flux
  Reason: no suitable image found.  Did find:
	/Users/.../Desktop/Flux.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle: code signature invalid for '/Users/.../Desktop/Flux.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/A/Sparkle'

Binary Images:
    0x7fff694f9000 -     0x7fff6952f92f  dyld (353.2.4) <3C068A0D-69D5-3AD6-86D9-6261D3B1564E> /usr/lib/dyld
    0x7fff8de1c000 -     0x7fff8de1cfff  com.apple.Cocoa (6.8 - 21) <EAC0EA1E-3C62-3B28-A941-5D8B1E085FF8> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa

**Comment by kornelski** [comment]
Does `codesign -vvv --strict` say anything about it?

**Comment by herf** [comment]
codesign -vvv --strict Sparkle.framework/
Sparkle.framework/: valid on disk
Sparkle.framework/: satisfies its Designated Requirement

Headers -> Versions/Current/Headers
Modules -> Versions/Current/Modules
PrivateHeaders -> Versions/Current/PrivateHeaders
Resources -> Versions/Current/Resources
Sparkle -> Versions/Current/Sparkle
Current -> A
fr_CA.lproj -> fr.lproj
pt.lproj -> pt_BR.lproj

**Comment by kornelski** [comment]
In the past we've had trouble with the .lproj symlinks. Try deleting them and see if it helps.

**Comment by herf** [comment]
This seems to be a code signing problem overall, from Xcode 12.4 to Yosemite. 

I found a Yosemite machine and my app failed to open entirely. I only got the above error after turning off Gatekeeper - then, the app's signing was bypassed but apparently the Framework was checked.

Closing this issue as it's not due to Sparkle, and I expect Sparkle signing to work once app signing works again.

**Comment by herf** [comment]
Confirmed that re-signing on an Intel machine (10.14) makes .app and Sparkle signing work again on Yosemite. May be due to SHA-1 certs in the older codesign, but not a Sparkle issue anyway.

**Comment by zorgiepoo** [comment]
If you were developing on M1, you may have been [hitting this](https://developer.apple.com/forums/thread/673323) (which resonates with code signing, sha, and < 10.11)
