### ISSUE TITLE
generate_appcast -f command line argument doesn't work

### ISSUE THREAD

**Issue by lovette** [sparkle-project/Sparkle#1763]
## Summary

Using the `-f` command line argument should work like this:

	generate_appcast -f /path/to/appcast.private.pem /path/to/updates

This results in an error:

	Error generating appcast from directory /path/to/appcast.private.pem 
	Error Domain=NSCocoaErrorDomain Code=256 "The file “appcast.private.pem” couldn’t be opened." UserInfo={NSUserStringVariant=(Folder), NSURL=file:///path/to/certs/appcast.private.pem/, NSFilePath=/path/to/certs/appcast.private.pem, NSUnderlyingError=0x7fec1bc338e0 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}}

## Possible Fix

Change the order `parseCommandLineOptions()` removes the `-f` arguments 

From:

	arguments.remove(at: privateDSAKeyOptionIndex)
	arguments.remove(at: privateDSAKeyOptionIndex + 1)

To:

	arguments.remove(at: privateDSAKeyOptionIndex + 1)
	arguments.remove(at: privateDSAKeyOptionIndex)

## Version

1.x master branch

**Comment by kornelski** [comment]
Thanks for debugging this. Can you make a PR?
