### ISSUE TITLE
fr_CA and pt translations aren't signing right

### ISSUE THREAD

**Issue by vadi2** [sparkle-project/Sparkle#1764]
### Description of the problem
I'm signing the app that includes Sparkle 1.24 with `codesign --deep -s "$IDENTITY" "${app}"`, and while the signing completes successfully, verification is throwing these errors: 

```
% codesign -vv --deep-verify Mudlet-4.10.1-testing-pr4746-2592d773.app 
Mudlet-4.10.1-testing-pr4746-2592d773.app: a sealed resource is missing or invalid
In subcomponent: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-2592d773.app/Contents/Frameworks/Sparkle.framework
file added: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-2592d773.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/Sparkle.strings
file added: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-2592d773.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUAutomaticUpdateAlert.nib
file added: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-2592d773.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUUpdateAlert.nib
file added: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-2592d773.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUUpdatePermissionPrompt.nib
file added: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-2592d773.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/Sparkle.strings
file added: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-2592d773.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUAutomaticUpdateAlert.nib
file added: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-2592d773.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUUpdatePermissionPrompt.nib
file added: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-2592d773.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUUpdateAlert.nib
file missing: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-2592d773.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj
file missing: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-2592d773.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj
```

Even when I delete the `fr_CA.lproj` and `pt.lproj` folders prior to codesigning, verification is failing:

```
./Mudlet-4.10.1-testing-pr4746-b17ae072.app: a sealed resource is missing or invalid
file missing: /Users/runner/work/Mudlet/b/ninja/Mudlet-4.10.1-testing-pr4746-b17ae072.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj
file missing: /Users/runner/work/Mudlet/b/ninja/Mudlet-4.10.1-testing-pr4746-b17ae072.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj
In subcomponent: /Users/runner/work/Mudlet/b/ninja/Mudlet-4.10.1-testing-pr4746-b17ae072.app/Contents/Frameworks/Sparkle.framework
```

What could be the issue?

### Do you use Sandboxing in your app?
No
### Version of `Sparkle.framework` in the latest version of your app
1.24

**Comment by kornelski** [comment]
They've been deleted in c91257e3

**Comment by vadi2** [comment]
Is that available on Cocoapods?

Tried rolling back to an earlier version that works but all of them give either this error, or complain about app/framework ambiguity.

**Comment by kornelski** [comment]
The symlinks are as old as 1.6 from many many years ago, so no amount of rolling back is going to help. They've been broken by changes in macOS.

**Comment by vadi2** [comment]
I'm using Sparkle as part of a C++ project. Is a package manager for Swift relevant?

**Comment by kornelski** [comment]
SPM is where Apple seems to be moving to. This is an Obj-C project, and yet it publishes a "Swift" package.

**Comment by vadi2** [comment]
Alright thanks. I don't see SPM being offered in [Github Actions](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#package-management) so that presents an adoption barrier, will wait until it's more mainstream in the development ecosystem.

I did try to delete the symlinks myself as seen in the original issue but then it says:

```
./Mudlet-4.10.1-testing-pr4746-b17ae072.app: a sealed resource is missing or invalid
file missing: /Users/runner/work/Mudlet/b/ninja/Mudlet-4.10.1-testing-pr4746-b17ae072.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj
file missing: /Users/runner/work/Mudlet/b/ninja/Mudlet-4.10.1-testing-pr4746-b17ae072.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj
In subcomponent: /Users/runner/work/Mudlet/b/ninja/Mudlet-4.10.1-testing-pr4746-b17ae072.app/Contents/Frameworks/Sparkle.framework
```

Is the information stored elsewhere that I need to wipe?

**Comment by zorgiepoo** [comment]
You'd need to re-sign the framework after deleting the symlinks.

**Comment by vadi2** [comment]
Agreed, but that's what I've been doing all along. My code to be exact:

```sh
# Remove fr_CA and pt translations because macOS broke those:
# https://github.com/sparkle-project/Sparkle/issues/1764
echo "Purging problematic fr_CA and pt translations from Sparkle..."
BAD_SYMLINKS="fr_CA pt"
for i in $BAD_SYMLINKS; do
  rm -rf "${app}/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/$i.lproj"
  rm -rf "${app}/Contents/Frameworks/Sparkle.framework/Resources/$i.lproj"
  rm -rf "${app}/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/$i.lproj"
done

pushd "${app}/Contents/Frameworks/Sparkle.framework"
find .
popd

# Sign everything now that we're done modifying contents of the .app file
# Keychain is already setup in travis.osx.after_success.sh for us
if [ -n "$IDENTITY" ] && security find-identity | grep -q "$IDENTITY"; then
  codesign --deep -s "$IDENTITY" "${app}"
  echo "Validating codesigning worked with codesign -vv --deep-verify:"
  codesign -vv --deep-verify "${app}"
fi
```

Output: https://paste.ubuntu.com/p/svSB43kXHz/

Anything else I can do to get this to work? One workaround I see is [cocoapods-patch](https://github.com/DoubleSymmetry/cocoapods-patch/blob/master/README.md), but I'm entirely unfamiliar with how XCode works. Would applying the patch at https://github.com/sparkle-project/Sparkle/commit/d4d4c68ad2e11ecdf21b2a71d45710cec4834c0c be enough, or will it run too late in the process to have effect?

**Comment by zorgiepoo** [comment]
This works for me manually with an older version of the Sparkle Test App if it helps any (I don't want to debug a bash script):

```
rm -f Sparkle\ Test\ App.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj
rm -f Sparkle\ Test\ App.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj
codesign -f -s "-" Sparkle\ Test\ App.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
codesign -f -s "-" Sparkle\ Test\ App.app
codesign --verify --deep -vvv Sparkle\ Test\ App.app
```

If you go this temporary route, ideally you'd fix up Sparkle.framework before copying it over to your app and before signing your app.

**Comment by vadi2** [comment]
That's doesn't seem like good test - it works even without the `rm -f` commands. 

```
Sparkle-1.24.0.tar.xz: extracted to `Sparkle-1.24.0.tar' (multiple files in root)
Mac-1613759142735:Sparkle runner$ cd Sparkle-1.24.0.tar
Mac-1613759142735:Sparkle-1.24.0.tar runner$ codesign -f -s "-" Sparkle\ Test\ App.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
Sparkle Test App.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle: replacing existing signature
Mac-1613759142735:Sparkle-1.24.0.tar runner$ codesign -f -s "-" Sparkle\ Test\ App.app
Sparkle Test App.app: replacing existing signature
Mac-1613759142735:Sparkle-1.24.0.tar runner$ codesign --verify --deep -vvv Sparkle\ Test\ App.app
--prepared:/Users/runner/Sparkle/Sparkle-1.24.0.tar/Sparkle Test App.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
--validated:/Users/runner/Sparkle/Sparkle-1.24.0.tar/Sparkle Test App.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
Sparkle Test App.app: valid on disk
Sparkle Test App.app: satisfies its Designated Requirement
Mac-1613759142735:Sparkle-1.24.0.tar runner$
```

Any ideas? Aren't other Sparkle users running into this?

**Comment by vadi2** [comment]
Switched to fetching 1.25rc archive using CMake and it works 'fine':

```
% codesign -vv --deep-verify Mudlet-4.10.1-testing-pr4746-210f88bd.app 
Mudlet-4.10.1-testing-pr4746-210f88bd.app: bundle format is ambiguous (could be app or framework)
In subcomponent: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-210f88bd.app/Contents/Frameworks/Sparkle.framework
```

Nonetheless the application opens. 1.18 gave the same error by the way.

Thanks for the assistance!

**Comment by zorgiepoo** [comment]
> That's doesn't seem like good test - it works even without the rm -f commands.

It is supposed to, since nothing was changed except the signature.

> % codesign -vv --deep-verify Mudlet-4.10.1-testing-pr4746-210f88bd.app 
Mudlet-4.10.1-testing-pr4746-210f88bd.app: bundle format is ambiguous (could be app or framework)
In subcomponent: /Users/Vadim/Desktop/Mudlet-4.10.1-testing-pr4746-210f88bd.app/Contents/Frameworks/Sparkle.framework

I've not seen that error, maybe the Sparkle.framework bundle isn't being copied or built correctly however you're doing it. It doesn't show up like that in the Test App.

**Comment by vadi2** [comment]
> It is supposed to, since nothing was changed except the signature.

Then the problem with `fr_CA` and `pt` translations was not in the test - I don't see how it was applicable here.

> I've not seen that error, maybe the Sparkle.framework bundle isn't being copied or built correctly however you're doing it. It doesn't show up like that in the Test App.

The issue was using `cp -r` instead of `cp -R`. All good now.

**Comment by zorgiepoo** [comment]
If you take a version of the Test App that is affected (from eg 1.24.0 release) which has the symlinks, it should be as applicable here, at least that's what I was trying to demonstrate. The issue in #1691 is partly due to zip being a bad file format and depends on various factors like OS version, method of zip creation, which implementation of unzipping is used (a couple different ones exist).

**Comment by imcooder** [comment]
I understand that this is because the upgrade package is in zip format, and Sparkle did not retain syslink when unpacking the zip file. There are the following methods:

1. When packaging, remove the syslink, then repackage, sign, and authenticate it. This has obvious drawbacks: the upgrade package will become larger

2. Upgrade the package using the DMG package, and there is no unzip process test in between to solve this issue.
I still hope Sparkle can upgrade to support retaining syslink capability when unzipping

**Comment by zorgiepoo** [comment]
This issue was addressed a long time ago. We don’t symlink the language resources anymore.
