### ISSUE TITLE
generate_appcast -s command line argument usage help is incorrect

### ISSUE THREAD

**Issue by lovette** [sparkle-project/Sparkle#1766]
## Summary

generate_appcast usage help for `-s` command line argument is currently:

> "provide the path to the private EdDSA key"

It actually needs to be the EdDSA private key itself.

This is how I invoke the tool:

	generate_appcast -s "$(</path/to/private.key)" /path/to/updates

## Possible Fix

Change usage help to:

> "provide the private EdDSA key, 128-characters"

## Version

master branch and 2.x branch

**Comment by zorgiepoo** [comment]
I think it should really be a file path instead to match generate_keys's export option and not encourage passing the string raw on a terminal. Also that is what the DSA option does.

**Comment by kornelski** [comment]
We could support both, but I've intentionally implemented it as string value, not a file. This is because CI platforms usually have an option to store encrypted secrets as variables.

**Comment by lovette** [comment]
I'd prefer to keep `-s` as-is so not to break existing integrations. I agree with using variables as secrets but am not opposed to adding another option analogous to `-f` to provide an EdDSA key file path. I'm happy to submit a pull request to update the usage text if keeping `-s` as-is.

**Comment by kornelski** [comment]
Yes, please fix the docs. We can add file support later.
