### ISSUE TITLE
SUFileManager + SULog

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#1779]
1.x (at 6471af1bbff890c7c91e225654af4175d9f99086) doesn't build:

```
Undefined symbols for architecture arm64:
  "_SULog", referenced from:
      -[SUFileManager _removeQuarantineWithAuthenticationAtRootURL:error:] in SUFileManager.o
      -[SUFileManager copyItemAtURL:toURL:error:] in SUFileManager.o
      -[SUFileManager moveItemAtURL:toURL:error:] in SUFileManager.o
      -[SUFileManager changeOwnerAndGroupOfItemAtRootURL:toMatchURL:error:] in SUFileManager.o
      -[SUFileManager updateModificationAndAccessTimeOfItemAtURL:error:] in SUFileManager.o
      -[SUFileManager makeDirectoryAtURL:error:] in SUFileManager.o
      -[SUFileManager removeItemAtURL:error:] in SUFileManager.o
```

**Comment by zorgiepoo** [comment]
Uh, weird. I noticed that issue in https://github.com/sparkle-project/Sparkle/pull/1771 from the unit tests but I thought I fixed it.  And CI is passing on it. May need to see if I can repro.

**Comment by kornelski** [comment]
I was building via make release. Maybe it builds differently?

**Comment by zorgiepoo** [comment]
Yeah we weren't testing release config in CI which.. I dunno offhand why it's different there for the Test app. But I put PRs up to fix this.
