### ISSUE TITLE
SPM not working with 1.25.0

### ISSUE THREAD

**Issue by Sam-Spencer** [sparkle-project/Sparkle#1783]
## Summary
Sparkle 1.25 doesn't work with Swift Package Manager. The `Swift.package` file requires 1.26.0 and the latest release is 1.25.0. Xcode is incredibly confused. Additionally, even with some massaging, the latest binary issue patch doesn't seem to be working.

## Version
1.25.0

**Comment by gregcotten** [comment]
It will be a glorious day once there is a Sparkle release that actually works with Swift Package Manager! Until then, you should use 891afd44c7075e699924ed9b81d8dc94a5111dfd.

**Comment by nikolaeu** [comment]
@kornelski Sparkle-for-Swift-Package-Manager.zip is missing in [release](https://github.com/sparkle-project/Sparkle/releases/tag/1.25.0).

**Comment by nikolaeu** [comment]
@gregcotten think you can use something more fresh, like 4853c187ae741add65c89366cd08a52d72a10677

**Comment by gregcotten** [comment]
@nikolaeu I'm a little scared to use a version of Sparkle that isn't version tagged 😬

**Comment by fmoraes74** [comment]
How about version 1.26.0-a1 ? It seems to be properly constructed. I can't try it yet but it should work from the little I know.

**Comment by gregcotten** [comment]
@fmoraes74 I just can't risk using an alpha build in a production environment, is all!

**Comment by nikolaeu** [comment]
@fmoraes74 think `1.26-a1` fails because of invalid check sum

**Comment by fmoraes74** [comment]
I know `1.24.0-spm` works. I didn't have any success moving to 1.25.0 so I am staying there and hopefully 1.26.0 fixes it.

**Comment by kornelski** [comment]
Sorry, this chicken-egg tag-change-retag dance is fragile :/
