### ISSUE TITLE
generate_keys puts private key in passwords vs keys

### ISSUE THREAD

**Issue by XericDesign** [sparkle-project/Sparkle#1788]
When I use generate_keys, why does the resulting private key "Private key for signing Sparkle updates" not appear in the Keys section of the Keychain app? Rather, it appears under password but the kind still shows as private key.

**Comment by kornelski** [comment]
This is because macOS keychain doesn't support ed25519 keys.

**Comment by XericDesign** [comment]
So for a new project, should I busing the ed25519/keychain method? How long will the older DSA public/private keys be supported? I have used DSA keys for years but now work is starting on a new major version of one of my products.

**Comment by kornelski** [comment]
DSA is dead. Please use only EdDSA.

**Comment by zorgiepoo** [comment]
Website has migration docs now.
