### ISSUE TITLE
Sparkle: DSA signature validation failed

### ISSUE THREAD

**Issue by xybertom** [sparkle-project/Sparkle#1797]
I'm Sorry this is a support request, not an Issue...

### Description of the problem
An error occur while extracting the archive.
Checking the console, the following log is recorded.
```
Sparkle: DSA signature validation failed. The update has a public DSA key and is signed with a DSA key, but the public key doesn't match the signature. The update will be rejected.
```

### Do you use Sandboxing in your app?
No

### Version of `Sparkle.framework` in the latest version of your app
2.0...?
In appcast.xml it says 2.0.

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
old version is none.
I'm trying to use Sparkle from the next version.

### Sparkle's output from Console.app
```
Sparkle: Error: An error occurred while extracting the archive. Please try again later. The update is improperly signed. (URL (null))
```
```
Sparkle: Extracting using '/usr/bin/ditto' '-x' '-k' '-' < '/Users/tomitayuki/Library/Caches/com.zerofield.QaseeClient/org.sparkle-project.Sparkle/QaseeClient 2.0/QaseeClient.zip' '/Users/tomitayuki/Library/Caches/com.zerofield.QaseeClient/org.sparkle-project.Sparkle/QaseeClient 2.0'
```
```
Sparkle: DSA signature validation failed. The update has a public DSA key and is signed with a DSA key, but the public key doesn't match the signature. The update will be rejected.
```
```
Sparkle: Error: An error occurred while extracting the archive. Please try again later. The update is improperly signed. (URL (null))
```
### Steps to reproduce the behavior
- Ran `generate_keys` to create private and public keys.
- The private key is kept under `~/` and the public key is included under `app_bundle/Contents/Resources`
- Build the app and sign it with the Developer ID.
- Compress with `ditto -c -k --sequesterRsrc --keepParent QaseeClient.app QaseeClient.zip`
- Sign with `../../../SparkleSharp/Sparkle/3rdparty/Sparkle/bin/sign_update QaseeClient.zip ~/dsa_priv.pem` and got pub_key signature(?)
- Check the length with `wc -c < QaseeClient.zip`
- Update the `url`, `length` and `sparkle:dsaSignature` in `appcast.xml` as follows
```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:dc="http://purl.org/dc/elements/1.1/">
    <channel>
        <title>Your Great App's Changelog</title>
        <description>Most recent changes with links to updates.</description>
        <language>ja</language>
        <item>
            <title>Version 2.0 (2 bugs fixed; 3 new features)</title>
            <sparkle:releaseNotesLink>
                http://you.com/app/2.0.html
            </sparkle:releaseNotesLink>
            <pubDate>Wed, 09 Jan 2006 19:20:11 +0000</pubDate>
            <enclosure url="https://url.to.update.zip" sparkle:version="2.0" length="9657416" type="application/octet-stream" sparkle:dsaSignature="[filtered]" />
            <sparkle:minimumSystemVersion>10.7</sparkle:minimumSystemVersion>
        </item>
    </channel>
</rss>
```
- In this state, execute the following code in the app
```
var updater = new SUUpdater();
updater.AutomaticallyChecksForUpdates = false;
updater.CheckForUpdates(new NSObject());
```

### What I'm wondering
- The pub_key signature that I get when I run sign_update is multiple instead of single as in many examples on the internet. 
Which one should I put in sparkle:dsaSignature?
```
MEQCIGq+b9Kw5Uebds/GATS1nj1PkExaw9YVI6cTtQu0opYNAiAEkcT/IH/0HTpL
/ycG037xwj2gOAHGfTlWc8HhRu2mcg==
```
(I replaced it with something random.)

- I have signed the app with a Developer ID, but many of the Sparkle binaries it contains are in error when notarized by Apple.
```
"severity": "error",
"code": null,
"path": "QaseeClient_1.7.9rc.dmg/QaseeClient.app/Contents/Frameworks/Sparkle.framework/Sparkle",
"message": "The signature of the binary is invalid.",
"docUrl": null,
"architecture": "x86_64"
```
The following binary has the same error.
`Contents/Frameworks/Sparkle.framework/Versions/Current/Sparkle`
`Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle`
`Contents/MacOS/QaseeClient`

What should I do?

**Comment by zorgiepoo** [comment]
I don't know if you're actually using version 2.0 (which is in beta/development; latest GitHub release is 1.26). Try to get info on the framework in Finder to check the version.

You should use EdDSA signatures (Sparkle 1.21 onwards supports this). DSA signatures are only for migrating from older versions of Sparkle. We've some documentation using them at https://sparkle-project.org/documentation/ . It's not clear to me if you still need to support DSA and coming from a version that didn't support EdDSA.

The signature shouldn't ever be multi-line, that may be an illusion of what you're seeing in the Terminal.

If you're having code signature issues, try running `codesign --verify --deep -vvv path-to-app`

**Comment by xybertom** [comment]
Thank you for your kind answer. I'll take that as a reference.
