### ISSUE TITLE
org.sparkle-project.Downloader crashing only while running in Xcode in os_unfair_lock

### ISSUE THREAD

**Issue by mikejurka** [sparkle-project/Sparkle#1805]
### Description of the problem

We are using Sparkle 2.x (built from d102a50f66563b9004842d81c7fcdef982a3ec93) in our app, and when running inside xcode we see the following crash in the Sparkle downloader (`org.sparkle-project.Downloader`)

`BUG IN CLIENT OF LIBPLATFORM: Trying to recursively lock an os_unfair_lock`

<img width="852" alt="Screen Shot 2021-03-23 at 7 25 06 PM" src="https://user-images.githubusercontent.com/440407/112245090-7c220580-8c0d-11eb-9405-072922546bdf.png">

### Do you use Sandboxing in your app?

Yes

We don't see this crash if XPC-Services are not included.

### Version of `Sparkle.framework` in the latest version of your app

Sparkle 2.x (built from d102a50f66563b9004842d81c7fcdef982a3ec93)

### Sparkle's output from Console.app

I didn't see any Sparkle output other than what's above

```

```

### Steps to reproduce the behavior

1. Launch Xcode project for our app that uses Sparkle2 and auto updating enabled (based off https://github.com/tillhainbach/SwiftUISparkleTestApp)
2. Command - R to run
3. On startup, you will see the error `BUG IN CLIENT OF LIBPLATFORM: Trying to recursively lock an os_unfair_lock` in `org.sparkle-project.Downloader`

**Comment by zorgiepoo** [comment]
Is there a backtrace? Try running `thread backtrace` in the console.

`org.sparkle-project.Downloader` is not in the project in https://github.com/tillhainbach/SwiftUISparkleTestApp. Where did you get or how did you build it? We provide a binary signed with the hardened runtime but this is incompatible with the Debug XPC Services option in Xcode on a system that has SIP enabled. More information [here](https://sparkle-project.org/documentation/sandboxing/).

The Sparkle Test App in our repo also uses the downloader service and we haven't seen this issue there.

**Comment by zorgiepoo** [comment]
Also the stack trace of what the other threads are doing would be helpful too.

**Comment by mikejurka** [comment]
I built Sparkle from source using the instructions here: https://github.com/tillhainbach/SwiftUISparkleTestApp#build-sparkle-2x

Thanks for the link to the XPC Services docs. After re-reading them, I realized we don't need the Downloader service since we already request the `com.apple.security.network.client` entitlement.

Backtraces:
```
(lldb) thread backtrace all
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
  * frame #0: 0x00007fff6fb6863c libsystem_platform.dylib`_os_unfair_lock_recursive_abort + 23
    frame #1: 0x00007fff6fb63a23 libsystem_platform.dylib`_os_unfair_lock_lock_slow + 256
    frame #2: 0x00007fff35805e5d CoreFoundation`__CFGetConverter + 96
    frame #3: 0x00007fff35805def CoreFoundation`CFStringEncodingGetConverter + 9
    frame #4: 0x00007fff35805d67 CoreFoundation`CFStringGetSystemEncoding + 91
    frame #5: 0x00007fff35803885 CoreFoundation`__CFInitialize + 1024
    frame #6: 0x00000001129cdf63 dyld`ImageLoaderMachO::doImageInit(ImageLoader::LinkContext const&) + 319
    frame #7: 0x00000001129ce5d3 dyld`ImageLoaderMachO::doInitialization(ImageLoader::LinkContext const&) + 29
    frame #8: 0x00000001129c8ffb dyld`ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 493
    frame #9: 0x00000001129c8f66 dyld`ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 344
    frame #10: 0x00000001129c8f66 dyld`ImageLoader::recursiveInitialization(ImageLoader::LinkContext const&, unsigned int, char const*, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 344
    frame #11: 0x00000001129c70b4 dyld`ImageLoader::processInitializers(ImageLoader::LinkContext const&, unsigned int, ImageLoader::InitializerTimingList&, ImageLoader::UninitedUpwards&) + 188
    frame #12: 0x00000001129c7154 dyld`ImageLoader::runInitializers(ImageLoader::LinkContext const&, ImageLoader::InitializerTimingList&) + 82
    frame #13: 0x00000001129b568a dyld`dyld::initializeMainExecutable() + 169
    frame #14: 0x00000001129babba dyld`dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 6667
    frame #15: 0x00000001129b4227 dyld`dyldbootstrap::start(dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 453
    frame #16: 0x00000001129b4025 dyld`_dyld_start + 37
(lldb) 
```

Happy to close this bug out since removing the downloader service solves this for me.

**Comment by zorgiepoo** [comment]
Yeah, the backtrace is in dyld / CoreFoundation and isn't in our code at all. It might have worked if the XPC Service wasn't debugged / out of Xcode. Seems like a configuration issue either way and you didn't end up needing the service.
