### ISSUE TITLE
Unable to update the app silently, which is installed via package installer.

### ISSUE THREAD

**Issue by zeeshansuleman** [sparkle-project/Sparkle#1806]
hello guyz,
I am using sparkle 1.x and i want to implement silent download and install update without showing any sparkle ui. Right now i have implemented timer inside my app which executes after 2 hour and check if update is available from sparkle. if update is available i dont know how can i install it silently. I do not want to specify automatic downloads in .plist file, As i want to do it programmatically.

**Comment by zorgiepoo** [comment]
https://sparkle-project.org/documentation/customization/

`SUEnableAutomaticChecks` (API equivalent is `setAutomaticallyChecksForUpdates:`) controls whether automatic checks for updates are enabled or not (default YES)

`SUAutomaticallyUpdate` (API equivalent is `setAutomaticallyDownloadsUpdates:`) controls whether updates are downloaded silently or not (default NO)

Specifying keys in your plist is preferable unless you need to dynamically decide which to choose.

I don't know why you are implementing your own timer instead of using Sparkle's timer. Regarding your previous thread, Sparkle stores its last update check time in `SULastCheckTime` user default.

Eg, just for testing purposes you can manipulate it:
```
defaults read app-bundle-id SULastCheckTime
defaults delete app-bundle-id SULastCheckTime
defaults write app-bundle-id SULastCheckTime "2021-03-26 07:38:23 +0000"
```

**Comment by zorgiepoo** [comment]
Ah yes, and `-checkForUpdatesInBackground` is the API Sparkle uses to check for updates in the background, which its scheduler does if you use it.

**Comment by zeeshansuleman** [comment]
@zorgiepoo As you mentioned above settings i will look into these, But right now if specify these settings in my .plist my update does not gets install on quit. I have specified SUFeedURL = "my app cast url", SUAutomaticallyUpdate = true , SUScheduledCheckInterval = 3600.
But the app does not get updated on quit. Is there anything i need to specify ? Also can i provide SUScheduledCheckInterval less than an hour. I checked that its mentioned in the doc that minimum time bound is 1 hour.

**Comment by zorgiepoo** [comment]
The app needs to be running at the point the update check occurs and I guess you should confirm that manual update check works too. You need to set up a sparkle updater object otherwise Sparkle doesn't run at all.

Only debug builds of Sparkle (eg if you build Sparkle from Xcode in Debug) have minimum time bound to 1 minute.

**Comment by zeeshansuleman** [comment]
Alright . @zorgiepoo how can i disable this alert to show. I don't want to show this alert in my app.
<img width="434" alt="Screen Shot 2021-03-29 at 5 21 58 PM" src="https://user-images.githubusercontent.com/12757747/112836440-08bc4000-90b4-11eb-8c96-402966cd0d06.png">

**Comment by zorgiepoo** [comment]
Set `SUEnableAutomaticChecks` to YES in Info.plist, refer to customization docs above. Initially it's actually "unset" which brings up this permission dialog on 2nd launch.

**Comment by zeeshansuleman** [comment]
@zorgiepoo the problem is that i dont want to check for updates automatically, i am doing all this manually with `checkForUpdateInformation` function. In this case i also want to disable all the ui alerts related to update as i am updating the app silently, So  specifying `SUEnableAutomaticChecks` in info.plist will check for updates automatically which i dont want to do. In this case how can i disable ui alerts to show

**Comment by zorgiepoo** [comment]
Set it to NO instead of YES.

**Comment by zeeshansuleman** [comment]
> Set it to NO instead of YES.

specifying this to NO , still display me the alert.

**Comment by zorgiepoo** [comment]
Ah, we only check user defaults of that key not Info.plist, which I consider a bug on our end.

Set `automaticallyChecksForUpdates` property on the updater to `NO` then on app launch.

**Comment by zeeshansuleman** [comment]
@zorgiepoo sure i will implement the delegate and check results if it works for me.

**Comment by zorgiepoo** [comment]
> Ah, we only check user defaults of that key not Info.plist, which I consider a bug on our end.
> 

Actually taking a closer look at the code, setting `SUEnableAutomaticChecks` in the Info.plist should have indeed worked. In fact it does for me in the test app.

**Comment by zeeshansuleman** [comment]
@zorgiepoo i have installed the app on another machine and the update does not work, is there any way to check logs for the error ? i am not sure where can i get the error logs .

**Comment by zeeshansuleman** [comment]
@zorgiepoo i am using below lines to update the app in background.
```
let updater = SUUpdater.shared()
updater?.feedURL = URL(string: Constant.appcastURL)
updater?.delegate = self
updater?.automaticallyDownloadsUpdates = true
updater?.checkForUpdatesInBackground()
```
but it does not download any update and i am not able to see any error as well, i have implemented the delegates for error but they does not call either.

**Comment by zeeshansuleman** [comment]
@zorgiepoo basically this is happening when i embed my .app in package file and install the package in my system, The package move this application to /Applications folder. If i try by installing the app directly then auto update works, by adding it in package installer it does not gets updated.

**Comment by zorgiepoo** [comment]
If the application is installed such that it requires root for authorization to replace (eg often the case when installed via a pkg installer), an authorization dialog needs to be presented to the user at some point to install the update. In this case, automatic installation of updates is actually disabled and you can't get a silent update.

However in that case, checkForUpdatesInBackround() should still present an updater dialog if an update is found. the code snippet you posted above works on my end, so you might have to debug the issue further. (Do note setting properties like feedURL and automaticallyDownloadsUpdates persists in the user defaults of the app).

**Comment by zeeshansuleman** [comment]
@zorgiepoo after installion i checked the permissions of .app and these are same as of installing it without package. Should not it work and update silently? Also checkforupdatesinbackground not showing any authorization alert and neither any error i can get in delegates. Looks like after calling this function sparkle freezes.

**Comment by zeeshansuleman** [comment]
@zorgiepoo please i need a quick solution of updating app silently with installer package. Is there any option i can try to authorize it in the code instead of ui alert.

**Comment by zorgiepoo** [comment]
> after installion i checked the permissions of .app and these are same as of installing it without package. Should not it work and update silently?

If you try to delete the app in Finder (after being installed from a pkg), does Finder ask you permission to authorize? That's probably a decent test if a silent update can be done or not. The ownership / group that matters.

Does -checkForUpdates: still result in a UI dialog? What OS version are you on, is do not disturb on? See anything in Console.app, or you'll have to try stepping into Sparkle's code with the debugger.

Be mindful I'm not obliged in any way for responding / assisting.

**Comment by zeeshansuleman** [comment]
@zorgiepoo can you specify which permission set is required for the app in order to install update silently. I am thinking about writing a script in my package to give necessary permission's so that my silent update work. Right now it contains sytem(read,write),everyone(read,write). Or if there is any other way to authorize the app before sparkle actually goes to update it, that can be tried as well.

**Comment by zorgiepoo** [comment]
I suspect you may need some chown and/or chgrp commands or something in a post-install script (searching for issues here I see #1219). I would generally try to avoid using pkg to begin with.

**Comment by zeeshansuleman** [comment]
@zorgiepoo which group is required to assign to .app to bypass the authorization alert?

**Comment by zorgiepoo** [comment]
owner is user, group is user. just check the unix owner and group of other files or apps on your computer that you can move to trash without auth

**Comment by PauliusPetru** [comment]
I have very similar problem. I ma trying to implement silent update and it works then I run it form xcode. If I export build it doesnt updates on quit. I read all this thread and thinking maybe user have to allow something 🤔

**Comment by zorgiepoo** [comment]
Closing since this is more of a troubleshoot thread rather than anything actionable to be done here.
