### ISSUE TITLE
generate_appcast crashes with SIGTRAP on Apple Silicon

### ISSUE THREAD

**Issue by kode54** [sparkle-project/Sparkle#1807]
## Summary

When attempting to run either Sparkle 1.25.0 or 1.26.0 generate_appcast, in my usual manner, whether or not I specify my dsa private key, and include my imported keychain entry, the appcast tool crashes with SIGTRAP.

## Possible Fix

It would be nice to not have to rsync my builds folder over to my Intel machine just to run generate_appcast.

## Version

1.25.0
1.26.0

**Comment by zorgiepoo** [comment]
Please attach a crash report / log from Console applicationn.

Does generate_appcast run or crash without providing any arguments?

**Comment by kode54** [comment]
Okay, I figured it out. Keybase truncated my attempt to copy my ed25519 base64 string out of its text file viewer, and thus the Keychain entry that I reconstructed had a truncated password, and crashed the code that attempted to subscript the data field for at least 64 bytes of data.

User error.
