### ISSUE TITLE
Install new update failed...

### ISSUE THREAD

**Issue by nastasiupta** [sparkle-project/Sparkle#1816]
### Description of the problem
So I have 2 versions of my app (v1.0.0 - initial release and v1.1.0 - few modifications to test out the app update)
I made the Apple Notarizing step for both builds.
I installed the first version and I launch the app.
Version v.1.1.0 is also in a zip, on the server - After notarizing, I exported the new app, archive it and include it on the server and add the details in the appcast.xml file.
It founds the new update (v1.1.0), downloads it zip file from server, unpacks, but during the "Installing update..." phase I get the following issue:
Update Error! An error occurred while extracting the archive. Please try again later. (and the Cancel Update button)

Both versions have to following in the Info.plist:
`=<key>SUAutomaticallyUpdate</key>
<true/>
<key>SUEnableAutomaticChecks</key>
<true/>
<key>SUFeedURL</key>
<string>https://mediasync.s3.amazonaws.com/MediaSyncAppcast.xml</string>
<key>SUPublicEDKey</key>
<string>LAbG9o1ZCDWNofWg+b4kUxFB6pXiAfXXmuUIHQ6NH1A=</string>`

As you can see the public EDKey is in my Info.plist file, but also in the MediaSyncAppcast.xml

### Do you use Sandboxing in your app?
No

### Version of `Sparkle.framework` in the latest version of your app
1.26 (using SPM)
  s.name        = "Sparkle"
  s.version     = "1.26.0"
### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
Both versions (1.0.0 and 1.1.0) has the same Sparkle version.

### Sparkle's output from Console.app
```
[Sparkle] There is no EdDSA signature in the update, but the app is capable of verifying them
[Sparkle] The update has a DSA signature, but it can't be used, because the old app doesn't have a DSA public key
[Sparkle] The update has a public (Ed)DSA key, but the public key shipped with the update doesn't match the signature. To prevent future problems, the update will be rejected. 
```

**Comment by zorgiepoo** [comment]
It looks like you aren't signing your updates correctly.

Please check:
https://sparkle-project.org/documentation/
https://sparkle-project.org/documentation/publishing/#publishing-an-update

To reduce errors, try to use the generate_appcast tool.

Particularly you need to use `sparkle:edSignature` not `sparkle:dsaSignature` in your appcast, and the signature is not the same as the public one in your app's Info.plist. Rather, it is a signed signature generated by `sign_update` applied to your update (again, generate_appcast automatically handles this).

**Comment by nastasiupta** [comment]
Thanks, @zorgiepoo  - my mistake :). Works like a charm.

**Comment by kornelski** [comment]
@zorgiepoo maybe we should remove dsa documentation? I assume everyone who uses it already has it integrated and doesn't need the docs any more, and everyone adding/changing sparkle integration shouldn't be using it.

**Comment by zorgiepoo** [comment]
Yeah, just a small clean up task. I think the SampleAppcast.xml we distribute is the only thing left remaining with dsaSignature references.
