### ISSUE TITLE
Info.plist  configuration not working

### ISSUE THREAD

**Issue by nastasiupta** [sparkle-project/Sparkle#1817]
### Description of the problem
I want to enable automatic updates with the Info.plist configuration but is not working.
This is what I have in the Info.plist
`	<key>SUAutomaticallyUpdate</key>
	<true/>
	<key>SUAllowsAutomaticUpdates</key>
	<true/>
	<key>SUEnableAutomaticChecks</key>
	<true/>
	<key>SUScheduledCheckInterval</key>
	<real>86400</real>
	<key>SUFeedURL</key>
	<string>https://mediasync.s3.amazonaws.com/MediaSyncAppcast.xml</string>
	<key>SUPublicEDKey</key>
	<string>LAbG9o1ZCDWNofWg+b4kUxFB6pXiAfXXmuUIHQ6NH1A=</string>`

Having all those, nothing happens when I launch the app.
Did I miss anything in my Info.plist?

But, if I use the following:
`    func applicationDidFinishLaunching(_ aNotification: Notification) {
        SUUpdater.shared().delegate = self
        SUUpdater.shared().installUpdatesIfAvailable()
    }`
Everything works ok, but the `installUpdatesIfAvailable()` function is deprecated.

Even if I replace the call of that function as follows, the app updating is not triggered:
`    func applicationDidFinishLaunching(_ aNotification: Notification) {
        SUUpdater.shared().delegate = self
        SUUpdater.shared().automaticallyDownloadsUpdates = true
    }`

### Do you use Sandboxing in your app?
No

### Version of `Sparkle.framework` in the latest version of your app
1.26

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
1.26

**Comment by zorgiepoo** [comment]
https://sparkle-project.org/documentation/customization/

Sparkle by default automatically checks for updates after an interval of 24 hours have passed since the last check. i.e, doesn't check for updates on every launch. And you even have `SUScheduledCheckInterval` set in your Info.plist to 86400 seconds (24 hours).

-checkForUpdatesInBackground forces triggering an update check.
