### ISSUE TITLE
Update from Sandboxed application. Any workaround at all?

### ISSUE THREAD

**Issue by lmcd** [sparkle-project/Sparkle#1824]
We shipped our application with the App Sandbox enabled, and it *seems* (though not  confirmed to be the exact cause) to have broken app updates. Users are stuck at 'Installing update'. Checking the console, I think it's in issue with the quarantine flag, and moving to the /Applications directory.

Is there any workaround to this at all, or is it just screwed, and users must now download the app manually through a browser?

Thanks

**Comment by zorgiepoo** [comment]
Right, Sparkle 1 does not support sandboxing. Sparkle 2 under development does support sandboxing however.

As for what you can currently do for your stuck update, you can post an informational update. Check [Downloading from a website section](https://sparkle-project.org/documentation/publishing/#publishing-an-update).
