### ISSUE TITLE
Separate releases for different macOS versions

### ISSUE THREAD

**Issue by jonaski** [sparkle-project/Sparkle#1834]
This is just a question, but I didn't find any place to ask this.

I use homebrew dependencies to build releases for a Qt 6 based music player, Strawberry. For some reason the Mojave or Catalina built releases do not work on Big Sur so I need to provide a separate release for Big Sur.
Currently I have not updated the Sparkle feed for the new releases because I'm unsure how to specify different files for each macOS version.
Can I have separate item tags with different minimumSystemVersion? Or can you just have one?
The XML is here: https://www.strawberrymusicplayer.org/sparkle-macos

**Comment by zorgiepoo** [comment]
Generally, different item tags are supposed to correspond to a different application version and Sparkle picks the latest supported version. Ones with a `sparkle: minimumSystemVersion` or `sparkle:maximumSystemVersion` that don't match the OS should be filtered out. It might work with a single appcast item with different minimum/maximum requirements on each item, but different appcasts would work too.

As for maintaining apps on macOS, maintaining different versions for different OS's is pretty undesirable and out of the norm. Normally developers just either a) distribute a build that supports/deploys to Big Sur, Catalina, Mojave or b) cut off a min OS requirement in their newest app release.

**Comment by jonaski** [comment]
Thanks. I will try adding multiple items with different min / max versions.
Unfortunately I don't even have a mac to debug the issue, or test different builds, so it's either keeping it like it is, or dropping macOS releases altogether.
