### ISSUE TITLE
Sparkle 2.0.0 crash with "Invalid parameter not satisfying: aBundle"

### ISSUE THREAD

**Issue by lmparppei** [sparkle-project/Sparkle#1842]
My sandboxed app crashes when it detects an update to the bundle, using Sparkle 2.x (apparently any build). The Sparkle framework is the same in both of the apps, 2.0.0.

Here is the cleaned error report:
```
2021-04-30 20:17:39.530951+0300 Beat[17621:1088248] *** Assertion failure in -[SUHost initWithBundle:], SUHost.m:47
2021-04-30 20:17:39.531831+0300 Beat[17621:1088248] [General] An uncaught exception was raised
2021-04-30 20:17:39.531863+0300 Beat[17621:1088248] [General] Invalid parameter not satisfying: aBundle
2021-04-30 20:17:39.531941+0300 Beat[17621:1088248] [General] (
	0   CoreFoundation                      0x00007fff332d4b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6c11e5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff332fdd08 +[NSException raise:format:arguments:] + 88
	4   Sparkle                             0x00000001005b38ed -[SUHost initWithBundle:] + 784
	5   Sparkle                             0x00000001005a642d -[SPUUpdaterSettings initWithHostBundle:] + 106
	6   Sparkle                             0x00000001005badc5 -[SUUpdateAlert initWithAppcastItem:host:versionDisplayer:] + 245
``` 

So, for some reason, `SUHost` crashes with the supplied `NSBundle` (`NSBundle.mainBundle`). I found no other similar reports, so I'm confused about where to start debugging this. 

I am creating the Sparkle instance programmatically because of my different targets.

```
self.userDriver = [[SPUStandardUserDriver alloc] init];
	self.updater = [[SPUUpdater alloc] initWithHostBundle:NSBundle.mainBundle applicationBundle:NSBundle.mainBundle userDriver:self.userDriver delegate:nil];
```

Unfortunately I've already distributed this version of the app, and those builds will now crash at startup whenever a new version is available, but such is life. It would be great to figure out how to fix the problem for further builds.

**Comment by lmparppei** [comment]
I should have looked at the Test Application source code to figure this out. My `SPUStandardUserDriver` didn't have the host application bundle set. Sorry for any inconvenience.

**Comment by zorgiepoo** [comment]
Ah sorry that happened and thank you for the report. I'm marking the init method as NS_UNAVAILABLE in #1843 so this won't happen in the future.
