### ISSUE TITLE
Error occurred when connecting to the installer

### ISSUE THREAD

**Issue by lmparppei** [sparkle-project/Sparkle#1851]
### Description of the problem

Update fails, because Sparkle is unable to connect to the installer after downloading, using any latest build. I'm using only `InstallerLauncher`, no other XPC components. Copy files phase is set up correctly and I'm using the pre-built ad hoc executable for InstallerLauncher. The Sparkle entitlements in the main app are also added correctly, according to the notarization info.

Others had problems with the XPC getting sandboxed by mistake, but it doesn't seem to be my case. However, when I have the XPC copied into the app, I get an additional step for signing the app and its every component. Could I be signing it wrong? I've tried signing the XPC manually with Developer ID, but get the exact same results.

Am I missing a step in the sandbox workflow, or doing something else completely wrong?

### Do you use Sandboxing in your app?

Yes.

### Sparkle's output from Console.app
```
09:15:55.334080+0300	App	Error: An error occurred while connecting to the installer. Please try again later. (null) (URL (null))
09:16:13.163705+0300	org.sparkle-project.InstallerLauncher	<NSXPCConnection: 0x7fcb16004820> connection on anonymousListener or serviceListener from pid 37109: Exception caught during decoding of received selector launchInstallerWithHostBundlePath:authorizationPrompt:installationType:allowingDriverInteraction:allowingUpdaterInteraction:completion:, dropping incoming message.
Exception: <NSXPCDecoder: 0x7fcb17008200> received a message or reply block that is not in the interface of the remote object (launchInstallerWithHostBundlePath:authorizationPrompt:installationType:allowingDriverInteraction:allowingUpdaterInteraction:completion:), dropping.
(
	0   CoreFoundation                      0x00007fff332d4b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6c11e5bf objc_exception_throw + 48
	2   Foundation                          0x00007fff358b21a7 -[NSXPCDecoder _startReadingFromXPCObject:] + 0
	3   Foundation                          0x00007fff358fd3ba -[NSXPCDecoder _decodeMessageFromXPCObject:allowingSimpleMessageSend:outInvocation:outArguments:outArgumentsMaxCount:outMethodSignature:outSelector:interface:] + 33
	4   Foundation                          0x00007fff358fc186 -[NSXPCConnection _decodeAndInvokeMessageWithEvent:flags:] + 483
...
)

```

### Steps to reproduce the behavior

I followed the Sparkle 2.x installation guide. I'm using automatic signing

**Comment by zorgiepoo** [comment]
What version of the framework and what version of the XPC Service are you using? This looks more likely a mismatch between the XPC Service & framework than a signing issue. They must match. (I don't have error reporting yet to log if the framework and XPC Service versions are the same, but the git commit change sets they were built from are different).

**Comment by lmparppei** [comment]
To be honest, I couldn't find any other version identifier than `2.0.0`, but I now updated to the latest workflow run, `3cafb68` / `#305`. Still facing the exact same error. Should I build Sparkle myself to get matching versions?

**Comment by zorgiepoo** [comment]
I thought we were using the git hash somewhere for the framework, but I guess I'm not seeing it. I can reproduce your issue if I intentionally use unaligned framework & xpc service binaries, but I can't say, reproduce it in a sample sandboxed app using the [`#305`](https://github.com/sparkle-project/Sparkle/actions/runs/805028032) run.

This selector:
`launchInstallerWithHostBundlePath:authorizationPrompt:installationType:allowingDriverInteraction:allowingUpdaterInteraction:completion:`

changed to:
`launchInstallerWithHostBundlePath:updaterIdentifier:authorizationPrompt:installationType:allowingDriverInteraction:allowingUpdaterInteraction:completion:`

in #1832 (two weeks ago). Check the selectors that are logged in the message again, which should tell you which one the framework is trying to use.

**Comment by lmparppei** [comment]
Error happens in the old selector: `launchInstallerWithHostBundlePath:authorizationPrompt:installationType:allowingDriverInteraction:allowingUpdaterInteraction:completion:`

It must be a mismatch then. I removed everything related to sparkle and rebuilt everything, but the mismatch still happens. This is a user error in my project management, I guess. Thank you.

**Comment by lmparppei** [comment]
Something was cached somewhere. Cleaning build folder and removing & re-adding the framework fixed the issue. Sorry for the trouble and a big thank you!

**Comment by zorgiepoo** [comment]
This error will now be reported as part of #1854
