### ISSUE TITLE
Extended attributes were lost from my app after Sparkle updates my app

### ISSUE THREAD

**Issue by exceptioncatcher91** [sparkle-project/Sparkle#1857]
### Description of the problem
I have an application which has extended attributes on it. After i update the application to new version with Sparkle, the extended attributes are lost. How can i preserve the extended attributes after an update?

### Do you use Sandboxing in your app?
No.
### Version of `Sparkle.framework` in the latest version of your app
Yes. (1.26.0)
### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
N/A

**Comment by zorgiepoo** [comment]
I guess this is presently expected behavior? The extended attributes attached to the new application that is unarchived are used I believe. This is not really intentional though and preserving extended attributes is flaky. What are you using extended attributes for? Sparkle does preserve Finder tags for example.

**Comment by exceptioncatcher91** [comment]
Hi @zorgiepoo 

Thanks for the quick response. If i am not mistaken, Sparkle replaces the app bundle and thats why the extended attributes are lost. I hoped that `(void)updaterWillRelaunchApplication:(SUUpdater *)updater` or `(void)updater:(SUUpdater *)updater didExtractUpdate:(SUAppcastItem *)item` gives me a file url to the new application bundle and i can easily copy the extended attributes from the current app to the new one.

I use extended attribute to store a unique url. My app downloads the newest app settings from this url at every app start. 
I tried to solve this problem with the following:
I saved the extended attribute url from the current app in `(void)updaterWillRelaunchApplication:(SUUpdater *)updater` into UserDefaults, and at the next app start (when the updated app starts) in `int main()`, i read it from UserDefaults and put back to the updated application as an extended attribute. What do you think about this? Do you have a better idea/solution for this?

**Comment by zorgiepoo** [comment]
> I hoped that (void)updaterWillRelaunchApplication:(SUUpdater *)updater or (void)updater:(SUUpdater *)updater didExtractUpdate:(SUAppcastItem *)item gives me a file url to the new application bundle and i can easily copy the extended attributes from the current app to the new one.

For varying reasons, this will not ever be supported or be feasible.

Extended attributes is not a good place for your app to store essential data onto itself. I imagine they can also get lost when transferred across different mounts that may not support extended attributes, or when the app is archived/unarchived in certain ways.

I suggest storing your unique URL you need to in your user defaults or application support directory.

Users can also update your app manually from your website, outside of Sparkle.

**Comment by zorgiepoo** [comment]
Do you give your users a unique private download URL too that has that extended attribute set on the app once unarchived? If that's the case, I suggest reading the extended attribute and storing it to a better storage (user defaults, app support directory)

Your app cannot rely on writing extended attributes to its own app bundle itself (as app bundle is treated as immutable entity, your app may not have permission to do so; think eg of a non-admin user that installs the app in /Applications).
