### ISSUE TITLE
I can not find the Sparkle logs

### ISSUE THREAD

**Issue by exceptioncatcher91** [sparkle-project/Sparkle#1861]
### Description of the problem
I  got an error during update: Failed to extract update. I tried to get the logs from the Console.app, but I did not find any Sparkle related message. Where can I get them? What do I do wrong?

### Sparkle's output from Console.app
```

```

**Comment by zorgiepoo** [comment]
If you have Console.app open before reproducing the issue, and reproduce the issue, if you filter for Sparkle or the name of your app something relevant should show up in addition to the UI error you saw.

"Failed to extract update" probably implies it failed on a binary delta update, or the type of archive/update is unknown. If it failed on the binary delta update, then probably signature verification failed. But you'll need to find the logs.
