### ISSUE TITLE
CDATA Release notes are not displayed to user

### ISSUE THREAD

**Issue by bryanc-nz** [sparkle-project/Sparkle#1864]
### Description of the problem
Since Sparkle 1.26.0 I am no longer seeing the release notes from a CDATA section in the appcast file

### Do you use Sandboxing in your app?
No

### Version of `Sparkle.framework` in the latest version of your app
1.26.0

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
1.26.0

### Sparkle's output from Console.app
```

```

### Steps to reproduce the behavior
My appcast file is attached
[cpusetterappcast.xml.txt](https://github.com/sparkle-project/Sparkle/files/6573393/cpusetterappcast.xml.txt)

**Comment by zorgiepoo** [comment]
I'm not sure what's wrong here but the Sparkle Test App uses CDATA for release notes too and it works there, at least on my machine. When I put in the `<description></description>` you use in your feed into the test app, it still works for me.

Any Sparkle or WebKit logs in the Console? Does the test app in the 1.26 release distribution work for you? And does Sparkle 1.25 work?

**Comment by bryanc-nz** [comment]
The test app from 1.26 is working correctly.

I saw these 2 messages in the Console log after 'Check for update' in the application:

<code>
found no value for key NSApplicationFunctionRowControllerIsWebKitPluginProcess in CFPrefsSearchListSource<0x600002bd0480> (Domain: net.whatroute.CPUSetter, Container: (null))
</code>
<code>
found no value for key NSViewIsWebKitPluginProcess in CFPrefsSearchListSource<0x600002bd0480> (Domain: net.whatroute.CPUSetter, Container: (null))
</code>

**Comment by zorgiepoo** [comment]
I don't think those messages are relevant and I don't believe there's anything wrong that I can see with your appcast. 

There might be something specific with the environment your app is in (or OS or system language perhaps), if the test app works fine. if you build the test app from source (on `master` branch), you can alter `sparkletestcast.xml` by putting your `CDATA` release notes in and I'm suspecting it will work.

Sparkle 1.25 and onwards also transitioned to using WebKit2. You can see if Sparkle 1.24 is also affected.

On your website it looks like you have switched to Sparkle 1.26 for your WhatRoute app a couple releases ago, does the issue not persist for that app?

If I alter the test app to target CPUSetter in Sparkle 2 (and alter the app to make it look like it needs to be updated), the release notes are shown for me, albeit this is not the same as running the updater in your app which I haven't tried.

<img width="748" alt="Screen Shot 2021-06-01 at 10 37 47 AM" src="https://user-images.githubusercontent.com/857267/120367188-698b1300-c2c5-11eb-8823-65aa42ad79ec.png">

**Comment by bryanc-nz** [comment]
I have found the reason for the lack of release notes in my application, but I am not sure what to about it.

`2021-06-02 06:29:09.070597+1200 CPUSetter[74976:560472] [Nib Loading] Failed to connect (releaseNotesView) outlet from (SUUpdateAlert) to (WebView): missing setter or instance variable`

**Comment by zorgiepoo** [comment]
That sounds like the xib and the framework are out of alignment. Try downloading/replacing a version of 1.26 Sparkle.framework again.

Specifically, `releaseNotesView` outlet was removed in Sparkle 1.25 but the error indicates you're using a xib that still references it.

**Comment by bryanc-nz** [comment]
I have re-installed 1.26 and the release notes are being displayed. How very odd. I know I downloaded the correct release at the time (back in March) but I guess something has changed since then.

Anyway - I'll close this issue. Thank you for your help.
