### ISSUE TITLE
Safe to instantiate SUUpdater twice?

### ISSUE THREAD

**Issue by XericDesign** [sparkle-project/Sparkle#1874]
In 1.26, is it safe to instantiate SUUpdater twice? I think it needs to be in my main nib, but then I want a "check for update" button in a separate nib-based window that may or may not be opened by the user. Is it safe then to instantiate SUUpdater in multiple nibs within the same app?

I know it is a singleton - or is supposed to be. I just want to be sure this won't have weird side effects.

**Comment by zorgiepoo** [comment]
Hm I think so. But Sparkle 2 forgoes a singleton approach so if you want to save yourself work from the future instantiate the updater once and pass it around. The updater can be instantiated programmatically; it doesn't have to be in the main nib.

**Comment by XericDesign** [comment]
At what point will Sparkle 2 but production ready as my understanding is that it is still beta?

**Comment by zorgiepoo** [comment]
Development has shifted over to Sparkle 2, and sandboxed apps have been using it in production for quite some time now. I won't make promises on a more official release schedule..

For Sparkle 1, instantiating the updater in multiple nibs is a bit weird. I would still only instantiate the updater once, use a reference/outlet, and pass it to where your app needs it.

**Comment by XericDesign** [comment]
Is there a current stable build of v2 or do I just grab the latest build?

**Comment by zorgiepoo** [comment]
There isn't an official/stable build. Latest build from repo can be grabbed from read me. If you want a stable/official build you can still continue to use Sparkle 1.

**Comment by zorgiepoo** [comment]
The answer to original question by the way is no it’s not safe and not supported. #2107
