### ISSUE TITLE
Sparkle 2 beta with Sandboxing (catalyst): Cannot sign or notarize Updater.app and XPC: Missing provisioning profiles

### ISSUE THREAD

**Issue by imWildCat** [sparkle-project/Sparkle#1885]
### Description of the problem

Hello, I followed the [_Sandboxing with Sparkle_](https://sparkle-project.org/documentation/sandboxing/) guide and can have a valid local build to perform updates with Sparkle and it is really amazing. Thanks all the contributors! You're doing a great job.

However, when I was trying to sign and notarize my macOS (Catalyst) app, both the Xcode Organizer and fastlane command line complained.

- Xcode Organizer: no valid provisioning profile can be found. I attached the screenshot below:
    <img width="729" alt="image" src="https://user-images.githubusercontent.com/2396817/124950665-34e94480-e045-11eb-8878-a0074f1d250b.png">
    - I tried to create an App ID on App Store Developer portal but the bundle ID `org.sparkle-project.Sparkle.Updater` already exists:
        <img width="482" alt="image" src="https://user-images.githubusercontent.com/2396817/124951655-1d5e8b80-e046-11eb-80c3-e7747ca0e62f.png">
- Build and distribute using Fastlane:
    ```
    $ xcodebuild -exportArchive -archivePath ./tmp/mac_archive.xcarchive -exportOptionsPlist InfoFlow/ExportOptions_catalyst.plist -exportPath ./tmp/exported_archive
    23:31:28.028 xcodebuild[35829:1125230] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/ms/nlh9vdw512b1ptc6z0tlc2gw0000gn/T/InfoFlow_2021-07-08_23-31-28.026.xcdistributionlogs'.
    error: exportArchive: "InfoFlow.app" requires a provisioning profile with the App Groups, iCloud, and Push Notifications features.
    Error Domain=IDEProvisioningErrorDomain Code=9 ""InfoFlow.app" requires a provisioning profile with the App Groups, iCloud, and Push Notifications features." UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription="InfoFlow.app" requires a provisioning profile with the App Groups, iCloud, and Push Notifications features., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}
    error: exportArchive: "InfoFlowShareExtension.appex" requires a provisioning profile with the App Groups feature.
    Error Domain=IDEProvisioningErrorDomain Code=9 ""InfoFlowShareExtension.appex" requires a provisioning profile with the App Groups feature." UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription="InfoFlowShareExtension.appex" requires a provisioning profile with the App Groups feature., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}
    ** EXPORT FAILED **
    ```
    However, I can using the same stack to build and distribute (including notarization) my app perfectly.

I also checked several apps in production of my `/Applications` folder and they don't use XPC.

#### Detailed of my integration

Since it is a Catalyst app and it cannot access AppKit directly, I created a macOS bundle (Plugin) target to load Sparkle.
It would look like: `Main app (Catalyst) ---contains---> Plugin(bundle) ---contains---> Sparkle.framework`

### Do you use Sandboxing in your app?

Yeah.

### Version of `Sparkle.framework` in the latest version of your app

2.0 beta

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)

N/A

### Sparkle's output from Console.app
```
N/A, not a runtime issue of Sparkle
```

### Steps to reproduce the behavior
N/A, very specific issue.

### Appendix (the export options of my app)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>destination</key>
	<string>export</string>
	<key>iCloudContainerEnvironment</key>
	<string>Production</string>
	<key>method</key>
	<string>developer-id</string>
	<key>signingStyle</key>
	<string>automatic</string>
	<key>teamID</key>
	<string>[Redacted]</string>
</dict>
</plist>
```

**Comment by zorgiepoo** [comment]
When I try to notarize a normal app through Xcode, I don't have to select a profile for any Sparkle binaries and it just works using my Dev ID cert for "Distribution Certificate". Maybe try seeing if you can notarize a blank plain macOS app first, then a plain Catalyst app. So we can rule out whether it's specific to this environment or not.

I assume the App Store Developer portal is only for apps on the (Mac) App Store, which would rule out an app using Sparkle (I could be wrong, maybe there's some other purpose..)

The fast lane error output doesn't look Sparkle related.

Out of curiosity are you using the installer launcher and status services because you can't apply the entitlements mentioned in the docs you linked?

Optionally you can remove the Updater.app/Autoupdate binaries in Sparkle.framework if using the Installer Launcher xpc service like the docs mention. But I'm not sure it would help here, since they are contained in the XPC service anyway.

**Comment by imWildCat** [comment]
Thanks a lot for your help, @zorgiepoo!

> Maybe try seeing if you can notarize a blank plain macOS app first, then a plain Catalyst app. So we can rule out whether it's specific to this environment or not.

I will do this later today. Thanks for the suggestion!

> I assume the App Store Developer portal is only for apps on the (Mac) App Store, which would rule out an app using Sparkle (I could be wrong, maybe there's some other purpose..)

Yeah, totally make sense! The App ID stuff shouldn't apply for Sparkle.

> Out of curiosity are you using the installer launcher and status services because you can't apply the entitlements mentioned in the docs you linked?

Thanks for the suggestion. I noticed that "The Installer Launcher Service is required. This service bundles a copy of Sparkle’s helper tools Autoupdate and Updater.app."
Will remove the other two XPCs once I got a valid build. Currently I just want to put as many dependencies in my app bundle to get a MVP to run.

> Optionally you can remove the Updater.app/Autoupdate binaries in Sparkle.framework if using the Installer Launcher xpc service like the docs mention. But I'm not sure it would help here, since they are contained in the XPC service anyway.

Thank you! I've removed it. Currently I use an internal git repository to store The XPC and Sparkle.xcframework binaries. I removed Updater.app/Autoupdate binaries in Sparkle.framework before uploading to the git repository.

**Comment by imWildCat** [comment]
@zorgiepoo Actually I have one question: Are you using the Xcode Organizer to export the macOS app?
Or command line? If it's command line, would you mind sharing the code snippet of it?

**Comment by zorgiepoo** [comment]
> Thanks for the suggestion. I noticed that "The Installer Launcher Service is required. This service bundles a copy of Sparkle’s helper tools Autoupdate and Updater.app."

Typo, I meant the connection services but yeah.

I'm using the Xcode organizer.

**Comment by imWildCat** [comment]
@zorgiepoo Thank you! I can narrow down this issue into code sign of the xpc.

If I signed xpc before Archive, it will have an export issue.
If it doesn't have codesign, no issue will show.

I will confirm this tomorrow with my main project.

Will append my findings in this thread.

**Comment by zorgiepoo** [comment]
As the guide you linked notes, you may not need to sign them before Archive. Is there a particular reason you are?

**Comment by imWildCat** [comment]
Sorry, it's my fault do codesign it before Archive.

Maybe we could make the "Code Signing" a bit clearer? For example, "Code Signing (optional)".

**Comment by imWildCat** [comment]
Thanks a lot for your help, @zorgiepoo! 

I can fix this issue now. And got deep understanding of how it works for sandboxed apps.
