### ISSUE TITLE
Not working with M1 chip

### ISSUE THREAD

**Issue by jdeepsingh** [sparkle-project/Sparkle#1911]
Hi All,

I am trying to build my application for latest Mac system and **getting this error** :- 
<img width="818" alt="Screenshot 2021-07-30 at 7 27 06 PM" src="https://user-images.githubusercontent.com/12411304/127664207-63c79bf1-7ba0-4ecd-b481-70fd3c754a21.png">

Is there any way to build for **M1 chip system** . I have tried with your latest version - 1.26.0

**Comment by kornelski** [comment]
We build it as universal binary, so I don't know why your Xcode isn't seeing it:

```bash
file Sparkle-1.26.0/Sparkle.framework/Sparkle
Sparkle-1.26.0/Sparkle.framework/Sparkle: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
Sparkle-1.26.0/Sparkle.framework/Sparkle (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
Sparkle-1.26.0/Sparkle.framework/Sparkle (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

**Comment by kornelski** [comment]
Oh, I see. You're using CocoaPods. That's probably why. Use our builds instead.

**Comment by jdeepsingh** [comment]
It works, if I build for Rosetta but for M1 chip same architecture is used i.e.. x86_64. I have attached a screenshot also.
<img width="914" alt="Screenshot 2021-07-30 at 8 25 59 PM" src="https://user-images.githubusercontent.com/12411304/127672149-baab3eb0-64d6-4d15-83d6-12c2fdeffca1.png">

**Comment by zorgiepoo** [comment]
Our cocoa pods package is a binary/prebuilt package that should be pointing to Sparkle 1.26 release.

Look at the actual Sparkle.framework on disk and do the file command that Kornel suggested. And look at the version in the Info.plist of the framework or get info on the framework in Finder and see the version.

1.26 is built with arm64 and x86. Something is broken about your configuration.

**Comment by jdeepsingh** [comment]
Thanks @zorgiepoo and @kornelski , I have added sparkle manually using steps mentioned in your [doc](https://sparkle-project.org/documentation/) .

Thanks for you help.
