### ISSUE TITLE
There are no files in /Vendor/ed25519. Builds fail.

### ISSUE THREAD

**Issue by scottha** [sparkle-project/Sparkle#1912]
### Sparkle's output from Console.app
```

```

**Comment by kornelski** [comment]
You need to run

```bash
git submodule update --init --recursive
```

or clone again, but with `--recursive` flag.

**Comment by scottha** [comment]
Thank you very much, I’m new to github. I’m accessing github through Xcode. I don’t know how to set a recursive flag within Xcode. And I don’t know where to enter these commands:
git clone https://github.com/sparkle-project/Sparkle
git checkout 2.x
git submodule update --init --recursive
Any advice?

**Comment by kornelski** [comment]
Don't use Xcode. Clone from the command line (Terminal).

**Comment by scottha** [comment]
Thank you, I’ll give it a try.
