### ISSUE TITLE
[Question] Private key rollover

### ISSUE THREAD

**Issue by gpoitch** [sparkle-project/Sparkle#1933]
## Summary

My private key is gone. I reformatted the computer and the key was in the login keychain instead of iCloud so there is absolutely no backup.  

If I generate new EdDSA keys, I assume existing users will get errors when attempting to update?
Or can I just update the new public key in the build and it still work?
Or Is my only option to reach out to them and manually send them the next update with the new keys?
I do have backups of the old app versions. Is there a way to somehow pull the old private key out of them?

Thanks for your time and apologies for the non-issue.

## Version

2.0.0-beta.1

**Comment by gpoitch** [comment]
It ended up working fine by just changing the public and private key.  
Couldn't think of a way to test it besides trying it live.
I do see that this is documented now:

> If you both code-sign your application and include a public EdDSA key for signing your update archive, Sparkle allows issuing a new update that changes either your code signing certificate or your EdDSA keys. Note however this is a last resort and should only be done if necessary (like if you lose access to one of them or need to change keys).

Potential improvement:
- Have generate_keys prompt (or generate a file that you click) that opens the system prompt asking which keychain to store it instead of automatically putting it in local login.

**Comment by zorgiepoo** [comment]
> You can use the -x private-key-file and -f private-key-file options to export and import the keys respectively when transferring keys to a new Mac. Otherwise we recommend keeping the keys inside your Mac’s keychain.

generate_keys can also export/import keys to/from a file. I'm not too sure about the utility of storing it in an alternate keychain  (though I believe this has been brought up).

Glad you figured out the key rotation though.
