### ISSUE TITLE
'SUUpdater' is deprecated: Deprecated in Sparkle 2. Use SPUStandardUpdaterController instead, or SPUUpdater if you need more control.

### ISSUE THREAD

**Issue by iHTCboy** [sparkle-project/Sparkle#1946]
Sparkle 1：

```swift
 func applicationDidFinishLaunching(_ aNotification: Notification) {
          SUUpdater.shared()?.checkForUpdatesInBackground()
}
```

Sparkle 2：

 SPUStandardUpdaterController no find method `checkForUpdatesInBackground()`.

> `- (instancetype)initWithStartingUpdater:(BOOL)startUpdater updaterDelegate:(nullable id<SPUUpdaterDelegate>)updaterDelegate userDriverDelegate:(nullable id<SPUStandardUserDriverDelegate>)userDriverDelegate;` There are many parameters in these examples, which are too complicated for novices to understand.

I just want to simply call to check for updates in the background, what should I do?

Or is there a sample Demo? No sample code or documentation was found. thanks~

**Comment by zorgiepoo** [comment]
It's on SPUUpdater, SPUStandardUpdaterController has [updater property](https://sparkle-project.org/documentation/api-reference/Classes/SPUStandardUpdaterController.html#/c:objc(cs)SPUStandardUpdaterController(py)updater)

**Comment by iHTCboy** [comment]
> It's on SPUUpdater, SPUStandardUpdaterController has [updater property](https://sparkle-project.org/documentation/api-reference/Classes/SPUStandardUpdaterController.html#/c:objc(cs)SPUStandardUpdaterController(py)updater). SPUStandardUpdaterController is just a standard and nib-friendly wrapper. Check the class reference docs.
> 
> The website docs in the basic setup guide explain how to set up an updater (in a nib or programmatically). However I can add clarification about accessing the updater.

Sparkle 2：

```swift
class AppDelegate: NSObject, NSApplicationDelegate, SPUStandardUserDriverDelegate, SPUUpdaterDelegate {

    var mainWindow: NSWindow?

    func applicationDidFinishLaunching(_ aNotification: Notification) {
      
        SPUStandardUpdaterController(updaterDelegate: self, userDriverDelegate: self).updater.checkForUpdatesInBackground()

    }
}
```

Is this okay？

**Comment by zorgiepoo** [comment]
Store the SPUStandardUpdaterController in a property to strongly hold on to it and it will be, besides the lack of menu item validation. The [programmatic sample](https://sparkle-project.org/documentation/programmatic-setup/) goes over that.

Or you can stick the SPUStandardUpdaterController in the main nib and connect an outlet to it, and that will handle menu item validation.

**Comment by iHTCboy** [comment]
@zorgiepoo ok, thanks~

**Comment by zorgiepoo** [comment]
In hindsight, this issue reminds me that I really need to add a cautionary note about how calling `checkForUpdatesInBackground` manually and especially at launch is usually not a good idea, due to interfering with Sparkle's default scheduling of background update checks.
