### ISSUE TITLE
Valid update found but is not downloaded

### ISSUE THREAD

**Issue by nickkhod** [sparkle-project/Sparkle#1951]
### Description of the problem

When sending app to production and running checkForUpdatesInBackground - Sparkle finds valid update but doesn't start downloading it.
However if I run app from Xcode - valid update is found and then is downloaded (delegate methods willDownload/didDownload are triggered)
I have enabled automaticUpdates and automaticDownloads in Info.plist and code

### Do you use Sandboxing in your app?
No
### Version of `Sparkle.framework` in the latest version of your app
1.26
### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
N/A

**Comment by zorgiepoo** [comment]
Are you using a debug version of Sparkle when you are "running the app from Xcode"? This depends on how you are integrating Sparkle (if you are compiling it yourself as a subproject you may be using a debug build, or if you using a pre-packaged binary distribution / cocoa pods / SPM you're likely using a release build).

In your production version, are you verifying that valid update delegate method is triggered?

I see nothing between `-updater:didFindValidUpdate:` and `-updater:willDownloadUpdate:withRequest:` delegate methods that would cause the update to be aborted.

`-checkForUpdatesInBackground` does not need to be called if automatic checking of updates is enabled. Sparkle periodically checks for updates in the background based on the `-lastUpdateCheckDate` (backed by `SULastCheckTime` default).

The update cycle logic is also reworked in Sparkle 2.

**Comment by nickkhod** [comment]
I use Sparkle installed using Carthage. 
In the prod version I do verify that didFindValidUpdate is triggered. I even set UI notification for each delegate method.

I event tried to launch app from Xcode with the release scheme - and after didFindValidUpdate method is triggered - willDownloadUpdate also triggered and update is downloaded

**Comment by zorgiepoo** [comment]
> I use Sparkle installed using Carthage.
> In the prod version I do verify that didFindValidUpdate is triggered. I even set UI notification for each delegate method.

Carthage probably integrates Sparkle as a subproject and it's probably being built in Debug at least in Debug schemes (only some default time interval values are different in Debug as far as I remember..)

> I event tried to launch app from Xcode with the release scheme - and after didFindValidUpdate method is triggered - willDownloadUpdate also triggered and update is downloaded

I don't know why being ran out of Xcode would be "different". You may be able to insert logging to see what's happening outside of your Xcode environment. Check -[SUBasicUpdateDriver didFindValidUpdate] and -[SUBasicUpdateDriver downloadUpdate] if you want to go that path. A quick glance at the code shows that the former calls the latter without anything tooo interesting happening in between.

**Comment by zorgiepoo** [comment]
One more thing, if authorization is required (this may depend where the app is installed and if the user is an admin or not), Sparkle 1 will use a UI based driver, instead of the automatic update driver that downloads/installs the update silently. Sparkle 2 will still download the update in the background and then start a UI based driver to let the user resume installing it.

**Comment by nickkhod** [comment]
Tried to make Build-> Archive -> Export and run the app. THe update is found and is downloaded. The issue persists when creating build from CI

**Comment by nickkhod** [comment]
Finally figured out that issue is related to access restrictions. If the app is installed in /Applications folder - silent updates do not work, otherwise it work

**Comment by zorgiepoo** [comment]
That is the authorization note I mentioned above. That depends on the writability of /Applications on the particular system and the application bundle in question. For example, on most systems admin users are allowed to write into there. Another scenario is a package installer making an app bundle in /Applications only writable by root user.

In this case, the update was likely found by the UI scheduled driver.
