### ISSUE TITLE
Building with c++20 results in conflicts related to module support

### ISSUE THREAD

**Issue by dingari** [sparkle-project/Sparkle#1952]
## Summary

The Sparkle.framework headers for macOS all wrap the system header imports with this check

```
#if __has_feature(modules)
@import Foundation;
#else
#import <Foundation/Foundation.h>
#endif
```

When switching to C++20 support, the compilation fails with this error:
```
fatal error: module 'Foundation' not found
@import Foundation;
 ~~~~~~~^~~~~~~~~~
1 error generated.
```

The project compiles fine with C++17.

## Possible Fix

I'm not well versed in how Objective-C module imports work, but I can't find any way to disable module support. 

## Version

1.26.0

**Comment by zorgiepoo** [comment]
I don't see any issues on my end setting the C++ Language Dialect to -std=c++20 with Xcode Version 13.0 beta 5 (13A5212g)  from a .mm file importing Sparkle. Obj-C modules are gated by `CLANG_ENABLE_MODULES` I believe so might be worth toggling that, or see if the issues get fixed when you do an `#import` .. but the reason we have these guards and not always use `#import` is to avoid compiler warnings.

**Comment by dingari** [comment]
Thanks for taking a look. I'm using CMake to build my project instead of XCode. I did already add the `-fmodules` flag to my build settings, but I'll look at `CLANG_ENABLE_MODULES` and see if that does the trick.

**Comment by JamesHallowell** [comment]
Hit the same problem building with CMake, couldn't get `CLANG_ENABLE_MODULES` to work, did you have any luck @dingari?

**Comment by dingari** [comment]
I didn't look more into it at the time. I gave up and am just sticking with C++17 on macOS for now.

**Comment by JamesHallowell** [comment]
Thanks for the update. I'll let you know if we happen to get it working.

**Comment by zorgiepoo** [comment]
Using `@import` in Sparkle frameworks to suppress `-Wauto-import` [was probably a mistake](https://github.com/llvm/llvm-project/commit/381fcaa1365b4fd8f9682a6a1e09f5b3fd4bbfc2). Feel free to open a PR to remove `@import` usage from our headers. Then probably C++20 will be happy.
