### ISSUE TITLE
Verifying built app properly updates from old to new, and from new to newer

### ISSUE THREAD

**Issue by digitalmoksha** [sparkle-project/Sparkle#1953]
## Summary

I'm always looking for an easier way to test whether or not Sparkle is working correctly in my app, particularly when I update Sparkle.

The documentation mentions editing the `Info.plist` to tweak the `CFBundleVersion`.  But you can't do this once the app has been signed - the app won't launch.

I've done it before by putting the new version in a test directory on my server, along with an updated `releases.xml`, and then pointing `SUFeedURL` to it:

```
  defaults write com.mycompany.mayapp SUFeedURL "https://mycompany.com/releases/testing/releases.xml"
```

This tests that the old -> new version updated.  But I realize it doesn't test the new -> newer update.

Is there anyway to test this better, or automate it in some fashion?  Is `sparkle-cli` of any use here?

Either way, it would be helpful to have more detailed testing instructions in the documentation.

## Possible Fix

More detailed testing instructions for an app built with Sparkle, and possibly a better procedure to automate it or make it easier.

## Version

I'm concerned with 2.x, but could also apply to 1.x

**Comment by zorgiepoo** [comment]
> The documentation mentions editing the Info.plist to tweak the CFBundleVersion. But you can't do this once the app has been signed - the app won't launch.

Right this is meant for development / debug workflow.

> I've done it before by putting the new version in a test directory on my server, along with an updated releases.xml, and then pointing SUFeedURL to it:

In conjunction with this approach you can create a dummy build with a CFBundleVersion that is forever "far out in the future". You will be updating to a build that is likely older but it's probably sufficient for testing the update process on new versions of your app.

I don't think sparkle-cli would sufficiently test the updating logic from your own app.

**Comment by digitalmoksha** [comment]
Good idea, creating a far future one.  My initial test doing that seems to work 👍
