### ISSUE TITLE
SPM support yet again broken for 1.27.0

### ISSUE THREAD

**Issue by gregcotten** [sparkle-project/Sparkle#1955]
Updating to 1.27.0 with Swift Package Manager in Xcode causes this compile-time error:

```artifact of binary target 'Sparkle' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)```

What do we need to do to squash this problem once and for all?

**Comment by zorgiepoo** [comment]
The Swift Package actually works on my system / Xcode (macOS 11.5.2 (20G95) / Version 13.0 beta 5 (13A5212g)) in a sample project so it doesn't seem universally broken.

The artifacts URL is https://github.com/sparkle-project/Sparkle/releases/download/1.27.0/Sparkle-for-Swift-Package-Manager.zip which also extracts fine on my system.

**Comment by zorgiepoo** [comment]
> If you receive an artifact of binary target 'NewRelic' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.) error when extracting the package, please close Xcode, delete the Derrived Data folder, re-open Xcode, and try again.

https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/installation/spm-installation/

Found another source hitting this error suggesting this.
