### ISSUE TITLE
Updater delegate don’t fire

### ISSUE THREAD

**Issue by orranbass** [sparkle-project/Sparkle#1957]
Hi,
I’m implementing Sparkle 2.0 on my Sandboxing app.
I created an updater programmatically like here: https://sparkle-project.org/documentation/programmatic-setup/ and set updater delegate:
updaterController.updaterDelegate = self
The update work fine but the delegate methods don’t fire.
What can be wrong?
Thanks

**Comment by zorgiepoo** [comment]
The delegate must be set in the initializer if creating it programatically. The API documentation states this but I should make this more obvious / log a warning otherwise.

**Comment by zorgiepoo** [comment]
This has been improved in #1958 (and integrated in 2.0.0-beta.3) - these setters are no longer accessible programmatically, only via connecting outlets in Interface Builder.
