### ISSUE TITLE
Multiple alert popups to download and install new version

### ISSUE THREAD

**Issue by abdullahselek** [sparkle-project/Sparkle#1960]
## Summary

When there is an update available, Sparkle asks users to download and install a new version twice. After user clicks to download new version Sparkle starts downloading and then asks for the user permission to install the update, user gives permission and when installation is on progress Sparkle asks to download new version once more.

If user clicks to download button once more, Sparkle starts downloading again and try to install on top of latest version. As a result Sparkle shows an error popup.

I'm using Sparkle 2.0.0-beta.3 with CocoaPods, when I check the code sign of our app it looks fine.

## Possible Fix

I think the bug might be related to showing `SUUpdateAlert` more than once because of a wrong state.

## Version

2.x

**Comment by zorgiepoo** [comment]
Are you by any chance instantiating multiple instances of SPUUpdater or SPUStandardUpdaterController?

**Comment by abdullahselek** [comment]
Hi @zorgiepoo I checked our custom class that initiates `SPUStandardUpdaterController` and found out that our custom class was initiated twice so that SPUStandardUpdaterController. I fixed the problem and gave it go a few times more with following the steps:

- I started downloading new version then allowed it to install.
- Installation starts, just before the latest version launches completely Sparkles shows the alert again.

I gathered some logs from our custom class

```
CUSTOM_SINGLETON_THAT_MANAGES_SPUStandardUpdaterController: May check for updates: Yes
CUSTOM_SINGLETON_THAT_MANAGES_SPUStandardUpdaterController: Feed URL being requested
CUSTOM_SINGLETON_THAT_MANAGES_SPUStandardUpdaterController: Feed URL being requested
CUSTOM_SINGLETON_THAT_MANAGES_SPUStandardUpdaterController: Will download update
CUSTOM_SINGLETON_THAT_MANAGES_SPUStandardUpdaterController: Will install update
```

 After I see `Will install update` installation starts and before our app launches again. Our custom class that manages SPUStandardUpdaterController initiates again in AppDelegate and Sparkle shows an alert to let user an update available.

```
CUSTOM_SINGLETON_THAT_MANAGES_SPUStandardUpdaterController: Initiated
CUSTOM_SINGLETON_THAT_MANAGES_SPUStandardUpdaterController: Feed URL being requested
CUSTOM_SINGLETON_THAT_MANAGES_SPUStandardUpdaterController: Updating allowed changed to: Yes
```

Do you have any other ideas?

**Comment by zorgiepoo** [comment]
Can you log the instances of SPUStandardUpdaterController and make sure they correspond to the same pointer?

I can guess some of them but I don't know exactly what delegate methods you are observing corresponding to all those logs so this is not easy to follow.

If you're looking at `-updater:willInstallUpdate:` for `Will install update`, the installer has sent a quit event to the application. The update cycle should not end before the application is terminated, contrary to your logs, I believe.

**Comment by abdullahselek** [comment]
Sorry for the delay, I'll gather the logs and share with you as soon as possible.

**Comment by abdullahselek** [comment]
Thanks for your support @zorgiepoo I managed to update my app without additional popups. I fixed my class that manages SPUStandardUpdaterController and also enabled EdDSA signature.
