### ISSUE TITLE
There is no DSA signature in the update

### ISSUE THREAD

**Issue by quyvx07** [sparkle-project/Sparkle#1964]
I convert the app from .app to .pkg. Then pack the .pkg into .dmg.
I signed with .dmg with [sign_update]
When updating, an error is appearing [There is no DSA signature in the update]

Case: Don't switch to .pkg. Packing .app into .dmg is working properly

Can you please help me where I am wrong or guide me to update with .pkg? Thanks a lot

**Comment by zorgiepoo** [comment]
What version of Sparkle is your old app using to update? Does your old app use DSA or EdDSA or both (it needs to use one of them for package based update to work).

If your app is using DSA keys, please see the [migration guide for using EdDSA keys](https://sparkle-project.org/documentation/eddsa-migration/).

To sign updates with legacy DSA, which you may still need to do, you need to use sign_update in bin/old_dsa_scripts/

In general, applications should prefer not using pkg by the way.

**Comment by quyvx07** [comment]
I'm trying this library. So no old apps.
Thanks for your support

**Comment by zorgiepoo** [comment]
Ok, what version of Sparkle are you using?

In that case you should be using EdDSA in your app and appcast item, and not DSA. The error message almost sounds like EdDSA isn't properly configured.

**Comment by zorgiepoo** [comment]
New apps should also just sign and serve the pkg directly, not put the pkg in a dmg.

**Comment by quyvx07** [comment]
I am using Sparkle version 1.27.0
I have done it successfully with .app to .dmg
Please help me if using .app to .pkg is it correct to do the same?

**Comment by quyvx07** [comment]
I also tried .app to .pkg same error

**Comment by zorgiepoo** [comment]
Show what you put in your app's Info.plist and what you put in your appcast feed.

**Comment by quyvx07** [comment]
I added the following fields
Info.plist
SUPublicEDKey String "key public obtained when running generate_keys"
SUFeedURL String "url download"

**Comment by zorgiepoo** [comment]
Your appcast item enclosure needs the edSignature (obtained from sign_update) too. Eg

```
<enclosure url="http://sparkle-project.org/myupdate.zip" sparkle:version="2" type="application/octet-stream" sparkle:edSignature="ify59pDIuduaZcLnLvQjGqNQIAqi4dVgeA3L/e7I7xaqn9pVdiVZH7Na3v+Gp4ElAKJfX4Pfq8cgElfXmZc4Cg==" length="1879795" />
```

**Comment by quyvx07** [comment]
Sorry, I said missing. I have added edSignature to the appcast.xml file as you said

**Comment by zorgiepoo** [comment]
It works for me so I don't know, must be something on your end; you're not really pasting verbatim what you're using which isn't helping.

This is what I use (roughly) and it works with Sparkle 1.27.

Info.plist:
```
	<key>SUFeedURL</key>
	<string>https://mysite.com/myfeed.xml</string>
	<key>SUPublicEDKey</key>
	<string>motgYIwmnS1wa1Q/5SUDXnOVdKujkprFym/D7DJM77k=</string>
```

My feed:

```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" xmlns:myapp="https://zgcoder.net/myapp" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Sparkle Test App Changelog</title>
    <link>http://sparkle-project.org/files/sparkletestcast.xml</link>
    <description>Most recent changes with links to updates.</description>
    <language>en</language>
      <item>
        <title>Version 1.0</title>
        <sparkle:releaseNotesLink>
          https://mysite.com/releasenotes.html
        </sparkle:releaseNotesLink>
        <pubDate>Thur, 19 May 2014 15:20:11 +0000</pubDate>
		    <enclosure url="https://mysite.com/myupdate.pkg" sparkle:version="1" type="application/octet-stream" sparkle:edSignature="ify19pDIuduaZcLnPvQjGqNQIAqi4dVgeA3L/e7I7xaqn9pVdjVZH7Ta3v+Gp4ElAKJfK4Nfq8cgElfXmZc4Cg==" length="1879795" />
      </item>
  </channel>
</rss>
```

**Comment by quyvx07** [comment]
when creating the .pkg file, I used the following command:
`pkgbuild --root ./Applications --component-plist ./app.plist --scripts ./pkg/scripts --identifier com.myapp --version 1.0 --install-location /Applications/AppUpdateTest ./pkg/AppUpdateTest.pkg`

file XML:
```
<?xml version="1.0" standalone="yes"?>
<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
    <channel>
        <title>AppUpdateTest</title>
        <item>
            <title>1.2</title>
            <sparkle:version>1.2</sparkle:version>
            <sparkle:shortVersionString>1.2</sparkle:shortVersionString>
            <sparkle:minimumSystemVersion>11.0</sparkle:minimumSystemVersion>
            <enclosure url="https://mysite.com/myupdate1.2.pkg" sparkle:edSignature="Jlc4freTuKHMwW2xdYw7zb+6UrUCixFzgQLJD0ppShuPn10AOC8u0WLPNfBGWjggvIWV/1s4XiUd5dVm5AeVAg==" length="895296" type="application/octet-stream"/>
        </item>
        <item>
            <title>1.0</title>
            <sparkle:version>1.0</sparkle:version>
            <sparkle:shortVersionString>1.0</sparkle:shortVersionString>
            <sparkle:minimumSystemVersion>11.0</sparkle:minimumSystemVersion>
            <enclosure url="https://mysite.com/myupdate1.0.pkg" sparkle:edSignature="2YN8nROgVw6HB9A6jGAGWCRx2zXvytsq2j2C1hdmV6ZXGTDvHmglt46futFmbqngZHAlXP2FTalXBbpKA+DBDQ==" length="5330210" type="application/octet-stream"/>
        </item>
    </channel>
</rss>
```

**Comment by zorgiepoo** [comment]
As far as I can see that looks ok. Can you copy and paste all the error messages in the console logs verbatim? If you are getting “There is no DSA signature in the update” that code should only be hit when there is no edSignature and no SUPublicEDKey present..
