### ISSUE TITLE
`SPUUpdater.canCheckForUpdates` not compatible with SwiftUI

### ISSUE THREAD

**Issue by tillhainbach** [sparkle-project/Sparkle#1966]
## Summary

Recent refactoring (2.x branch) of the `SPUUpdater` and `SPUUserDriver` broke compatibility with SwiftUI.

### In Detail

A couple of months ago, there used to be a `SPUUserDriver`-method which was called, every time the `.canCheckForUpdates`-property changed. This method was removed. Lately, `.canCheckForUpdates` was changed to be a computed property which is not KVO-compliant (2f783e01f0a847f0bdc1f0a3ac994caa4ed2336d). 

### Why is this important?

`SPUpdater.canCheckForUpdates` should be used to enable/disable UI-elements (e.g. update button) signalling whether or not a user can check for updates. However, SwiftUI-elements are only re-rendered if they are notified of state-changes by a publisher. Therefore it's the updaters responsibility to signal to any interested party, that its `.canCheckForUpdates`-state has changed, which was possible due to the user-driver's method or by using the fact, that obj-c class-properties can be converted to Combine publishers using `.publisher<Value>(for keyPath: KeyPath<Root, Value>)`
[docs](https://developer.apple.com/documentation/combine/performing-key-value-observing-with-combine). However, if computed properties should be KVO-compliant extra work is needed (e.g. [see this question](https://stackoverflow.com/questions/36555492/kvo-on-swifts-computed-properties)). 

## Possible Fix

make `SPUUpdater.canCheckForUpdates` KVO compliant by implementing `+ (NSSet<NSString *> *)keyPathsForValuesAffectingValueForKey:(NSString *)key;`
[docs](https://developer.apple.com/documentation/objectivec/nsobject/1414299-keypathsforvaluesaffectingvaluef?language=objc)

Properties which affect `.canCheckForUpdates`:
- `self.startedUpdater`
- `self.driver.showingPermissionRequest`
- `self.driver.showingUpdate`
- `self.sessionInProgress`

## Version

from Sparkle2.00-beta.1

**Comment by zorgiepoo** [comment]
Indeed, we should make this property KVO compliant as sessionInProgress is (and document it).

**Comment by zorgiepoo** [comment]
@tillhainbach Please check #1968
