### ISSUE TITLE
Check for update on relaunch

### ISSUE THREAD

**Issue by orranbass** [sparkle-project/Sparkle#1967]
Hi,
I’m implementing Sparkle 2.0 on my Sandboxing app.
After installation and app relaunch with the updated version, the Sparkle automatically run check for update again.
The check is always failed with reading feed error.
How can I stop Sparkle to do it?
Thanks

**Comment by zorgiepoo** [comment]
Release distributions of Sparkle are only configured to check for new updates once a day (by default) automatically. And when Sparkle automatically schedules update checks, it doesn't notify the user of errors (although it may log errors).

I don't know enough of your setup and the error you are hinting is too vague to help. Copy paste your code / setup, logs, errors, etc, verbatim.
