### ISSUE TITLE
Version History String Translation

### ISSUE THREAD

**Issue by R4N** [sparkle-project/Sparkle#1971]
## Summary

French speaking user of our application noticed the Version History button string wasn't translated into French. After looking at the strings files, I notice that it's present in the Base.lproj/Sparkle.strings file but not the fr.lproj/Sparkle.strings file.

For reference here are the files:

SPUStandardUserDriver (where the translation is used when creating the button): https://github.com/sparkle-project/Sparkle/blob/6639feaafc21cb57c5d3cb4c897bb7e6ef52cbe3/Sparkle/SPUStandardUserDriver.m#L279

Base.lproj/Sparkle.strings: https://github.com/sparkle-project/Sparkle/blob/2.x/Sparkle/Base.lproj/Sparkle.strings#L147

fr.lproj/Sparkle.strings: https://github.com/sparkle-project/Sparkle/blob/2.x/Sparkle/fr.lproj/Sparkle.strings

## Possible Fix

Add French translation for Version History to fr.lproj/Sparkle.strings file.

## Version

2.0.0

**Comment by zorgiepoo** [comment]
This is a new string that never got translated, so yeah, potential fix is to provide a translation & pull request.
