### ISSUE TITLE
Unable to generate deltas when using Cocoapod version

### ISSUE THREAD

**Issue by digitalmoksha** [sparkle-project/Sparkle#1972]
## Summary

I'm using the version of Sparkle 2 from Cocoapods, which is currently `2.0.0-beta.3`.

When I generate the appcast, I get the error 

```
Could not create delta update .../_sparkle_updates/releases/v2/Versatil Markdown748-738.delta 
Error Domain=NSCocoaErrorDomain Code=256 "Invalid file permissions after-tree on file 
.../Library/Caches/Sparkle_generate_appcast/77f957523b3b84552976bdcd9bd8d9c95da7cb1146140bc48950e3588ac17d21/Versatil Markdown.app/Contents/Frameworks/Sparkle.framework/Versions/A/Headers/SPUDownloadData.h 
(only permissions with modes 0755 and 0644 are supported)" UserInfo={NSLocalizedDescription=Invalid file permissions after-tree on file 
.../Library/Caches/Sparkle_generate_appcast/77f957523b3b84552976bdcd9bd8d9c95da7cb1146140bc48950e3588ac17d21/Versatil Markdown.app/Contents/Frameworks/Sparkle.framework/Versions/A/Headers/SPUDownloadData.h 
(only permissions with modes 0755 and 0644 are supported)}`
```

When I take a look at my app's `.../vendor/Pods/Sparkle/Sparkle.framework/Headers` directory, sure enough all the files are set to `-r--r--r--`.  

When I pull down the source listed in the podspec

```
  "source": {
    "http": "https://github.com/sparkle-project/Sparkle/releases/download/2.0.0-beta.3/Sparkle-2.0.0-beta.3.tar.xz"
  },
```

the headers there are `-rw-r--r--`.  I guess the act of generating the Pod somehow changes the permissions, which I assume is normal.

## Possible Fix

I don't think creating deltas should require any header file to have higher permissions than `-r--r--r--`.  I can think of no reason why write access would be needed for a header file.

## Version

Cocoapods Sparkle version `2.0.0-beta.3`

**Comment by zorgiepoo** [comment]
It might be an issue that CocoaPods is changing the header file permissions..

In general anyway, you want Xcode to strip/remove the framework headers when it copies the framework into your app and before it re-signs it. So that is another issue that is not working correctly.

**Comment by digitalmoksha** [comment]
You're right, I verified with both the Sparkle pod and Paddle pod in a new XCode project.  Both had their headers stripped out of the final build of the frameworks.

RubyMotion is currently copying the entire framework into the application. I'll see if I can effect some change there, but in the worst case it only keeps the deltas from being generated.

Thanks @zorgiepoo.  Closing this issue.

**Comment by zorgiepoo** [comment]
I'm removing this file permission check in https://github.com/sparkle-project/Sparkle/pull/2051 as we support diff'ing file permissions regardless of this.
