### ISSUE TITLE
Code sign issue

### ISSUE THREAD

**Issue by Swapnali-Kulkarni** [sparkle-project/Sparkle#1979]
Hi,

I am have integrated sparkle 1.24.0 in project using pods.

I am trying to sing following executables from sparkle framework using codesign command

.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle 
.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/MacOS/fileop 
.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/Autoupdate.app/Contents/MacOS/Autoupdate  

and then sign .app but when I check code sign status of .app files it shows following result 

app: a sealed resource is missing or invalid
In subcomponent: .app/Contents/Frameworks/Sparkle.framework
file added: .app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/Sparkle.strings
file added: .app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUAutomaticUpdateAlert.nib
file added: .app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUUpdatePermissionPrompt.nib
file added: .app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj/SUUpdateAlert.nib
file added: .app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/Sparkle.strings
file added: .app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUAutomaticUpdateAlert.nib
file added: .app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUUpdatePermissionPrompt.nib
file added: .app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj/SUUpdateAlert.nib
file missing: .app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj
file missing: .app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/pt.lproj

I can see fr_CA.lproj and pt.lproj file in its location, not sure why it is showing files as missing 

It is perfectly working in Xcode but while signing it is showing error.

any help would be appreciated

Thanks.

**Comment by zorgiepoo** [comment]
This should have been fixed in more recent versions of Sparkle. Please upgrade. 1.27.0 is on cocoa pods.
