### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by gooswa** [sparkle-project/Sparkle#1985]
### Description of the problem

When attempting to use Sparkle 2.x using Swift Package Manager or even through one of the release builds on the website it finds the module just fine but then Xcode gives me this Error:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SPUStandardUpdaterController", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64

### Version of `Sparkle.framework` in the latest version of your app

2.beta-4

### Sparkle's output from Console.app
```

```

**Comment by tonyarnold** [comment]
I'm seeing the same - how did you end up resolving this, @gooswa?

**Comment by zorgiepoo** [comment]
The error message here was initially "Undefined symbols for architecture **arm64e**:" then later it was edited to `arm64` then later issue was closed. It is expected Sparkle is not built as arm64e.

**Comment by zorgiepoo** [comment]
That's a different issue, you need to set the delegate in the initializer or connect the outlet in interface builder (#1957). That was exposed but it never worked that way. And setting it to nil is kind of redundant.

**Comment by tonyarnold** [comment]
Ah, yep, our use of the initialiser was… not standard. Fixed it by changing to a more supported method. 

Thanks, Zorgie!
