### ISSUE TITLE
Latest version isn't being detected

### ISSUE THREAD

**Issue by robenkleene** [sparkle-project/Sparkle#2017]
### Description of the problem

The latest version isn't being detected, I've deployed a new version in the `appcast.xml`, and verified that it's in the response body using networking traffic sniffing, but still the pop-up saying `You're up-to-date` is showing.

### Do you use Sandboxing in your app?

No

### Version of `Sparkle.framework` in the latest version of your app

1.26.0

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)

1.23.0

### Sparkle's output from Console.app

Searching for `Sparkle` in Console.app with my device selected in the left-hand panel provides no output. (Am I doing something wrong here?)

```
```

### Steps to reproduce the behavior

Here's the relevant section of the `appcast.xml` (this was sniffed using Proxyman). Version `0.8.0` isn't being detected, and a pop-up appears saying `0.7.1` is the latest version.

```
    <item>
      <title>0.7.1</title>
      <pubDate>Mon, 06 Sep 2021 13:20:29 -0400</pubDate>
      <description>&lt;p&gt;Added a Node runtime&lt;/p&gt;
</description>
      <sparkle:minimumSystemVersion>10.15</sparkle:minimumSystemVersion>
      <enclosure url="https://download.repla.app/repla/Repla%200.7.1.zip" sparkle:version="422" sparkle:shortVersionString="0.7.1" length="58783262" type="application/octet-stream" sparkle:edSignature="wkbecShqa9+fKJvp6b4mMmjUaXMPLtRnULyXaVHGVVNHF59AtlOzjjwcQdpbvx05bCHemuy7AMSO17VADlrfBQ=="/>
      <sparkle:deltas>
        <enclosure url="https://download.repla.app/repla/Repla422-416.delta" sparkle:version="422" sparkle:shortVersionString="0.7.1" sparkle:deltaFrom="416" length="24260204" type="application/octet-stream" sparkle:edSignature="QwAM8i9nO1gd9HM69Xb/2/HWxab6eY7Dy2T3rPZt535/CfR8jx3rGi+EYifnq6YWsvdv2U0Xxs6VDPfUDnFtAg=="/>
        <enclosure url="https://download.repla.app/repla/Repla422-407.delta" sparkle:version="422" sparkle:shortVersionString="0.7.1" sparkle:deltaFrom="407" length="24322551" type="application/octet-stream" sparkle:edSignature="3T63oRbJgYneS9KRfs8LrLqqxYiEuSqttgIKxrN5I6Sk8Xs3b7EVxrs8q7PQE+fJMQota9DNBNXmnEMmWzowCg=="/>
        <enclosure url="https://download.repla.app/repla/Repla422-410.delta" sparkle:version="422" sparkle:shortVersionString="0.7.1" sparkle:deltaFrom="410" length="24308658" type="application/octet-stream" sparkle:edSignature="19Sk1p9X0vRWTKzHyukBqwY+selE1qTR8bJE46/1GzIykfxyjeGG7s5rVS2w+59Voa0XypijhRSt0hsCR0aADA=="/>
        <enclosure url="https://download.repla.app/repla/Repla422-406.delta" sparkle:version="422" sparkle:shortVersionString="0.7.1" sparkle:deltaFrom="406" length="24322993" type="application/octet-stream" sparkle:edSignature="tbw1w+cvai5Xn5p5fw/cpLsRfTlcmJw/uFze4tcbUZZjp4gitRjwat9rW8W6HT2eSS8BEBtQ92UmBH6sYwNvAA=="/>
        <enclosure url="https://download.repla.app/repla/Repla422-401.delta" sparkle:version="422" sparkle:shortVersionString="0.7.1" sparkle:deltaFrom="401" length="35980310" type="application/octet-stream" sparkle:edSignature="BM0/Tvyi5W7cEp9891yWKPZSf3+6EHsgW818Xxh5Jc++B16qPz/hrNSgdKnvxH76pKBUWOnWUBXUvJFqw9lMBQ=="/>
        <enclosure url="https://download.repla.app/repla/Repla422-387.delta" sparkle:version="422" sparkle:shortVersionString="0.7.1" sparkle:deltaFrom="387" length="38232093" type="application/octet-stream" sparkle:edSignature="q4BqrBCLgbUbB8pEgVpZXChLjJGxdkN+E5yo+fVkpINzgE4J12RNlLwF6SvyEj/3rGs2vnKGvfdhnNNDVQQDAA=="/>
      </sparkle:deltas>
    </item>
    <item>
      <title>0.8.0</title>
      <pubDate>Wed, 10 Nov 2021 06:56:54 -0500</pubDate>
      <description>&lt;ul&gt;
&lt;li&gt;Added support for a JSON plugin format&lt;/li&gt;
&lt;/ul&gt;
</description>
      <sparkle:minimumSystemVersion>11.1</sparkle:minimumSystemVersion>
      <enclosure url="https://download.repla.app/repla/Repla%200.8.0.zip" sparkle:version="423" sparkle:shortVersionString="0.8.0" length="58807576" type="application/octet-stream" sparkle:edSignature="wSeg4Mi+x+h5vQ1J0k1a3zlnrqhxv270Lk8shZAn5qxWZPWTgsaYCVBhvoBatNUd6xw/NsiaqJoPHeXxa/E3DA=="/>
      <sparkle:deltas>
        <enclosure url="https://download.repla.app/repla/Repla423-422.delta" sparkle:version="423" sparkle:shortVersionString="0.8.0" sparkle:deltaFrom="422" length="1971479" type="application/octet-stream" sparkle:edSignature="Dys4C99dpY18FP/8MiWjq24breoYBABFRYL4Ymo2UV5yDTKmu32HD0g6r5yjLdzV+pYok4QGEtvvCmRYEZk2Bw=="/>
        <enclosure url="https://download.repla.app/repla/Repla423-416.delta" sparkle:version="423" sparkle:shortVersionString="0.8.0" sparkle:deltaFrom="416" length="25155492" type="application/octet-stream" sparkle:edSignature="8+pWOFaopD4ecIEvSJQa8hvHTXD8PwSD3nANJ5fTCkhn7xzqYP7NVO11SyibJhl7p/aF8cdYj/HOnp7qug47Dw=="/>
        <enclosure url="https://download.repla.app/repla/Repla423-410.delta" sparkle:version="423" sparkle:shortVersionString="0.8.0" sparkle:deltaFrom="410" length="25195170" type="application/octet-stream" sparkle:edSignature="0freZYWU57W5O0XxPCm9VoMlGTO5vsXyXlCWZrLGT9ozO/5X1flE1pnUfOdUntPDTS7PwlaKu208csBBjnH9CA=="/>
        <enclosure url="https://download.repla.app/repla/Repla423-407.delta" sparkle:version="423" sparkle:shortVersionString="0.8.0" sparkle:deltaFrom="407" length="25205144" type="application/octet-stream" sparkle:edSignature="1DATjNmf2SZRIMstQQyuUiyVR8Q1LeR87miIxEHmN0YrxqivA8M2l4T+/RYj/iPjz5jalLrH4ReNWEATH9FgAQ=="/>
        <enclosure url="https://download.repla.app/repla/Repla423-406.delta" sparkle:version="423" sparkle:shortVersionString="0.8.0" sparkle:deltaFrom="406" length="25202033" type="application/octet-stream" sparkle:edSignature="bd26FgF+fV6cmcWFHuj5QTrXyEJ4jBt/pFr4rtGZkvAzzCrWuxdrOcfCASWvhqUtQdfVRdeWfTVcVsj1IhpaBA=="/>
        <enclosure url="https://download.repla.app/repla/Repla423-401.delta" sparkle:version="423" sparkle:shortVersionString="0.8.0" sparkle:deltaFrom="401" length="36860541" type="application/octet-stream" sparkle:edSignature="KLjHvpsriCqBhUIgKb013WInZpd1dY8WdzYgXmMo3b1Jvu2MzUWYAJDw/w2fWZ4OyE9wAMnuuwbsoH3wtQkdDw=="/>
      </sparkle:deltas>
    </item>
```

**Comment by robenkleene** [comment]
It appears this is fixed by using `1.27.0`. But I'll have to fully deploy the build to know for sure. I'll update this again after I've done so.

**Comment by zorgiepoo** [comment]
The problem is the `sparkle:minimumSystemVersion`. You're building your app with an old SDK (`10.15.6`) that is reporting its OS version as `10.16.0` for compatibility reasons. Upgrade your SDK / Xcode that you're building your app or change the minimum system version to 10.16.0 (we recommend always using three components for minimum/maximium OS requirements).

**Comment by robenkleene** [comment]
Hi @zorgiepoo thanks for the reply! I'll apologize in advance for the potentially bone-headed question, but I've read your response a few times and it sounds like you're talking about `<sparkle:minimumSystemVersion>10.15</sparkle:minimumSystemVersion>`, which is the old version (`0.7.1`) that's already been deployed.

Are you saying I should re-compile the old version of my app (`0.7.1`) with a newer SDK? Then re-generate the feed (which I guess may update the `sparkle:minimumSystemVersion` for the *older* version(`0.7.1`)?). And then users *of the existing* `0.7.1` binary will be able to use Sparkle to automatically update to `0.8.0`?

**Comment by zorgiepoo** [comment]
No, I'm talking about `<sparkle:minimumSystemVersion>11.1</sparkle:minimumSystemVersion>`

Don't bother recompiling your old app, your users are already stuck with an old version of your app, so forget that.

What is happening, is because your old app (0.7.1) is built with the `10.15.6` SDK, the system decides to report the current operating system version as 10.16.0 (this is unrelatedly so a bunch of old apps don't break due to making incorrect version comparison assumptions)

`10.16.0` is < `11.1` so of course your old app doesn't see the update. Because the running system is "too old"

Next steps:
1. When you distribute 0.8.0 or any *newer* versions, make sure you build your application using a more recent SDK version.
2. You can change the `sparkle:minimumSystemVersion` in your feed from `11.1` to `10.16.0` so your old apps can update. Granted you cannot distinguish between `11.0` and `11.1` here but this is not a huge dealbreaker IMO and this is also why you should also do step 1 in the future, so it won't get worse in the future.

**Comment by zorgiepoo** [comment]
I forgot to mention, but the SDK version can be independent from the OS deployment target version. So generally developers should try to adopt latest SDK version when possible (eg currently 12.0) and set the minimum OS deployment target to whatever they want (eg 11.1)

**Comment by robenkleene** [comment]
Thanks @zorgiepoo! PS per your suggestion, I was able to fix this by manually changing `sparkle:minimumSystemVersion` from `11.1` to `10.16.0` for the newest version (`0.8.0`).
