### ISSUE TITLE
Where does generate_appcast get its sparkle:version from?

### ISSUE THREAD

**Issue by yspreen** [sparkle-project/Sparkle#2031]
It seems like it's definitely not the bundle's version string, it might be the build number? It's not really documented anywhere as far as I can tell. I spend a bunch of time trying to figure out why my new version in the appcast actually didn't show as a new version in the app, until I took a long look at the XML and figured that sparkle:version might be the issue here. What's going on there? I'm really confused

**Comment by zorgiepoo** [comment]
It’s supposed to be the CFBundleVersion; the build version.

**Comment by zorgiepoo** [comment]
It is mentioned that CFBundleVersion is used here https://sparkle-project.org/documentation#5-publish-your-appcast but I suppose it could use more clarification.

**Comment by yspreen** [comment]
@zorgiepoo that's great to know!

My habit is to reset the build no to 1 with every new version, which is probably a bad idea, but what I'm used to.

Then the problem I had was that I didn't see any new updates. It always told me an outdated version was up to date. When I started looking for issues in this repo, I found a ton of people with sparkle versions like 1.2.3 or 0.0.1, and I didn't stop to see if my version string was adapted into the sparkle version for my XML. Wouldn't it make more sense to put the full version string in there, and compare by date for the builds instead of the single build number? 🤔

**Comment by zorgiepoo** [comment]
No, comparing by date does not make sense. A bug fix update to 1.9.1 could be released after 2.0 is released for example and in this case 2.0 is still the latest version.

If you have multiple builds of your app on your system, the way the system (LaunchServices specifically) knows which build is later is by the CFBundleVersion. This matters for things like which app should be a default handler for things. So even absent of Sparkle it is important to get it right. The CFBundleVersionString (or sparkle:shortVersionString) is for the marketing / human-readable version of your application.

**Comment by yspreen** [comment]
Got it. Well I completely misunderstood the docs then. It's also a bit misleading that most issues on the repo seem to have short version strings in the sparkle:version field

**Comment by yspreen** [comment]
Feel free to close, or keep open to track documentation changes

**Comment by zorgiepoo** [comment]
CFBundleVersion and CFBundleShortVersionString or its Sparkle equivalents can be in the same "format", and sometimes some people set them to same value. But their purposes are different.

**Comment by zorgiepoo** [comment]
Added slight more documentation clarity here in the linked section.
