### ISSUE TITLE
mayPerformUpdateCheck doesn't have a return value in Swift

### ISSUE THREAD

**Issue by yspreen** [sparkle-project/Sparkle#2032]
I'm not sure how to override this method. in all the docs, there is a boolean return mentioned, but that doesn't exist in the swift signature:

objective c
```objc
/**
 Returns whether to allow Sparkle to check for updates.
 
 For example, this may be used to prevent Sparkle from interrupting a setup assistant.
 Alternatively, you may want to consider starting the updater after eg: the setup assistant finishes
 
 @param updater The updater instance.
 @param updateCheck The type of update check that will be performed if the updater is allowed to check for updates.
 @param error The (optionally) populated error object if the updater may not perform a new update check.
 @return @c YES if the updater is allowed to check for updates, otherwise @c NO
*/
- (BOOL)updater:(SPUUpdater *)updater mayPerformUpdateCheck:(SPUUpdateCheck)updateCheck error:(NSError * __autoreleasing *)error;
```

swift
```swift
func updater(_ updater: SPUUpdater, mayPerform updateCheck: SPUUpdateCheck) throws {
    return // can't return bool
}
```

docs
![image](https://user-images.githubusercontent.com/12631527/144757555-39eac740-a520-416c-9fd1-c7881e0278d6.png)

**Comment by yspreen** [comment]
same for shouldProceedWithUpdate

**Comment by zorgiepoo** [comment]
If you don't throw an error that is equivalent to returning YES.

Swift transforms a method that returns a BOOL and takes an error out pointer, into a non-returning function that can throw an error.

**Comment by yspreen** [comment]
My app was crashing whenever I threw an error instead of just returning... do I have to handle these errors somewhere? Trying to catch them on updater.start didn't help

**Comment by zorgiepoo** [comment]
It's not supposed to crash, and if it does, a backtrace / crash information would be helpful. Try throwing an NSError, though.

```
throw NSError(domain: "MyDomain", code: 1, userInfo: [NSLocalizedDescriptionKey: "Some description why operation cannot be performed"])
```

**Comment by zorgiepoo** [comment]
Swift convention is documented better otherwise insufficient info / cannot reproduce regarding crash
