### ISSUE TITLE
Support Proper Carthage Integration

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#2035]
Sparkle doesn't properly support Carthage because Carthage builds Sparkle with code signing disabled (instead of using an ad-hoc signature), resulting in a bad product absent of retaining entitlements and hardened runtime options. The standard workflows we recommend rely on these flags being preserved, rather than forcing developers to hack on additional code-signing scripts.

Additionally Sparkle 2 moves the tools from Resources into a directory expecting auxiliary executables, and Xcode fails to compile/integrate Sparkle in this case if the helper tools are not code signed.

We can support Carthage properly by providing the `.tar.xz` binary distribution of Sparkle like we already do with CocoaPods and SPM, and by forbidding source compilation from Carthage.

**Comment by DivineDominion** [comment]
What'd the user experience for devs be when they have "master" set as the ref in Carthage? Would be weird if sometimes you get working binary releases, sometimes broken source releases.

**Comment by zorgiepoo** [comment]
For 1.x (master) branch it shouldn't be that bad. Likely developers use a script to re-sign the auxiliary tools with hardened runtime enabled in that case, for notarization.

**Comment by zorgiepoo** [comment]
Working Carthage setup is now live on http://sparkle-project.org
