### ISSUE TITLE
Error when Installing Update

### ISSUE THREAD

**Issue by jaxony** [sparkle-project/Sparkle#2037]
### Description of the problem
My app can detect that a new version exists, and after clicking Install Update, the following error occurs:
![image](https://user-images.githubusercontent.com/12774152/145675731-0d0f420d-ac31-47e7-a458-9e14fbd33cc8.png)

### Do you use Sandboxing in your app?
Yes

### Version of `Sparkle.framework` in the latest version of your app
https://github.com/sparkle-project/Sparkle/commit/831e9b4eb7e871a9c072469fb14049614fc92810

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
N/A

### Sparkle's output from Console.app
```
error	21:59:24.019493+1000	kernel	Sandbox: Action Annotator(56376) deny(1) mach-lookup com.jacksonhuang.actionannotator-spki
...
default	21:59:29.723895+1000	org.sparkle-project.Downloader	nw_flow_disconnected [C2.1.1 IPv4#da273eba:443 cancelled socket-flow ((null))] Output protocol disconnected
default	21:59:29.724334+1000	org.sparkle-project.Downloader	nw_connection_report_state_with_handler_on_nw_queue [C2] reporting state cancelled
default	21:59:29.724745+1000	org.sparkle-project.Downloader	Connection 2: done
...
error	21:59:31.035712+1000	Autoupdate	Error: Timeout: installation data was never received (null) (URL (null))
error	21:59:31.142652+1000	Action Annotator	Timeout: Installer never started archive extraction
error	21:59:34.089871+1000	Action Annotator	Error: An error occurred while running the updater. Please try again later. The remote port connection was invalidated from the updater. For additional details, please check Console logs for Autoupdate. If your application is sandboxed, please also ensure Installer Connection & Status entitlements are correctly set up: https://sparkle-project.org/documentation/sandboxing/ (URL (null))
error	21:59:34.090331+1000	kernel	Sandbox: Action Annotator(56376) deny(1) mach-lookup com.jacksonhuang.actionannotator-spks
```

### Steps to reproduce the behavior

Appcast with links to DMGs for reproduction: https://jyzhuang.s3.ap-southeast-2.amazonaws.com/appcast.xml

More info:
- using DMGs to distribute app, DMGs created from https://github.com/sindresorhus/create-dmg
- I think I'm signing EdDSA correctly as the appcast contains the EdDSA signature for deltas and DMGs.
- I have double checked the correctness of `SUPublicEDKey` in the `Info.plist`
- `SUEnableInstallerLauncherService` is set to true in `Info.plist`
- `SUEnableDownloaderService` is set to true in `Info.plist` and the app does not request the network client entitlement

**Comment by zorgiepoo** [comment]
Please see "Installer Connection & Status Services" in https://sparkle-project.org/documentation/sandboxing/ and apply the `com.apple.security.temporary-exception.mach-lookup.global-name` mentioned there on your main app. This timeout error looks like your app doesn't have access to communicate to the Sparkle tools.

**Comment by zorgiepoo** [comment]
Note the error message already suggests/points to this:

```
Error: An error occurred while running the updater. Please try again later. The remote port connection was invalidated from the updater. For additional details, please check Console logs for Autoupdate. If your application is sandboxed, please also ensure Installer Connection & Status entitlements are correctly set up: https://sparkle-project.org/documentation/sandboxing/ (URL (null))
```

**Comment by jaxony** [comment]
I didn't read the instructions carefully, I thought those entitlements were optional 🤦🏼 
It all works now, thanks @zorgiepoo!

**Comment by zorgiepoo** [comment]
Clarified sandboxing documentation page on this slightly better.
