### ISSUE TITLE
Keep support for signed .dmg updates and verify them on download like EdDSA signed updates

### ISSUE THREAD

**Issue by lostminds** [sparkle-project/Sparkle#2042]
## Summary

While trying out 2.0.0rc1 I ran into a new warning saying updates not signed with EdDSA may not be supported in the future. As I understand it (from #2041 ), this includes signed .dmg files that offer similar tampering protection, since Sparkle can't validate the signatures. 

I sympathize with the ambition of requiring code-signing to establish safe updates, but for me since I already have signed .dmg I need to generate for each version for downloads it's very convenient to be able to use the same files for my Sparkle updates. This lets me package and sign one update I can upload to my automated version management system that then generates and serves downloads, version change logs and Sparkle appcasts. If signed .dmgs were no longer supported by Sparkle in a future update I would have to make and separately sign two packages for each version, one for downloads (still needs to be the apple signed .dmg) and one for sparkle (maybe a EdDSA-signed zip), which would be a more steps and additional things that could go wrong.

I realize this may not be a common way of using Sparkle, but I wanted to let you know of it and the utility of supporting signed .dmg updates has for me before you make a decision on removing this support.

## Possible Fix

Using the system codesign -dvvv tool you can inspect the signing on a dmg and get the apple signing team identifier and signing authority. This could be compared to the the signature of the currently updating app to ensure the dmg is signed with the same signature. I'm guessing this is similar to what Sparkle already does with the signature on the app.

## Version

2.0.0rc1

**Comment by zorgiepoo** [comment]
> If signed .dmgs were no longer supported by Sparkle in a future update I would have to make and separately sign two packages for each version, one for downloads (still needs to be the apple signed .dmg) and one for sparkle (maybe a EdDSA-signed zip), which would be a more steps and additional things that could go wrong.

This is not correct; you do *not have to* make two separate packages to use Sparkle's keys. Support for disk images is not going away. What Sparkle supports today is signing archives like disk images or zips with EdDSA. What Sparkle doesn't do today is using or caring about the Apple code signing signature on archives like dmg (if there's one). This is a non-trivial feature request to validate those signatures.

We happen to not strongly recommend serving disk images over to Sparkle but the reason for this is unrelated to signing. It's more related to performance and reliability thus we think Sparkle's handling of disk images may lead to a worse user experience compared to tarballs or zips.

> Using the system codesign -dvvv tool you can inspect the signing on a dmg and get the apple signing team identifier and signing authority. This could be compared to the the signature of the currently updating app to ensure the dmg is signed with the same signature. I'm guessing this is similar to what Sparkle already does with the signature on the app.

We use the code signing APIs from the Security framework directly (we'll never shell out to codesign). It is technically possible to validate/match the necessary designated requirement, but it is a little trickier and likely more hardcode-y than the APIs we use today which assume the identifiers match.

Another motivation for Sparkle's keys is fallback in case anything ever happens to your Dev ID cert, or support for additional features.

That said, I sympathize a little bit here and will leave this open long-term for feedback and as a possible feature enhancement.

**Comment by lostminds** [comment]
Thank you for the reply. I understand you might have other reasons not to do this, I just wanted to describe my use-case for your consideration. 

Using the shell codesign tool might then not be a solution, but I figured it would indicate that information about the signature could be inspected from dmgs, and that the signature identity would be the same as for the application. As for the performance of dmgs, my downloads and updates are quite small (10-20MB) so speed is not really an issue, and I've had no problems regarding reliability. 

> This is not correct; you do not have to make two separate packages to use Sparkle's keys. Support for disk images is not going away. What Sparkle supports today is signing archives like disk images or zips with EdDSA.

Just to clarify what I meant (which may be a misunderstanding) is that I believe I still need to have the dmgs codesigned by Apple to make sure macOS will consider them safe and not quarantine web downloads. And I expect that if I also codesign the dmg with EdDSA using Sparkle's sign_update tool (as indicated [here](https://sparkle-project.org/documentation/publishing/#publishing-an-update)) macOS will not be able to validate that this is a properly signed dmg. So while you're correct that it would could be the same dmg, I expect I'd have to have two differently codesigned versions of it, one for download with apple codesign and one for sparkle with the EdDSA signature? Or can the codesignatures both be applied to the same dmg file and still work in both contexts?

**Comment by zorgiepoo** [comment]
Sparkle's tools do not alter the files you sign. Instead, it gives you a signature to tack on in your appcast item. So both Apple and Sparkle signing can be applied to the same dmg or archive file.

The system doesn't do a whole lot today to favor signed disk images over unsigned ones. If you sign it, it won't App Translocate your app inside the disk image, and it will validate the signature. But otherwise unsigned ones aren't rejected and still common in the wild. Anyway, this is not too related here :).

**Comment by lostminds** [comment]
Ah, that's good news. I guess it still means an extra signing key and signing step for each update, (and some changes to my version management system to keep track of the update signatures) but it feels a lot more doable for the future.

Related to this, I think it would be a good idea to write a new more detailed description of this signing and security process. I had a hard time finding the information about how this was supposed to work ([here](https://sparkle-project.org/documentation/#3-segue-for-security-concerns) and [here](https://sparkle-project.org/documentation/publishing/)), and obviously still misunderstood some parts of this. If it's going to be required in the future I guess I'm not going to be the only one trying to figure out how to do this properly.

**Comment by zorgiepoo** [comment]
I think you had second guessed a little bit that signing with EdDSA would alter the archive files (this could never work). Documentation is always under an iterative process. You write the docs and thinks it sufficiently explains things, but then someone reads and sometimes skims or not follow the steps and comes to a different interpretation.

The distributing your app section noted:

> Sparkle supports updating from ZIP archives, tarballs, disk images (DMGs), and installer packages. While you can reuse the same archive for distribution of your app on your website, we recommend serving ZIPs or tarballs (e.g. tar.bz2) for updates because..

The publishing page for using sign_update manually noted:

> To manually generate signatures for your updates, Sparkle includes a tool to help you make a EdDSA signature of the archive. From the Sparkle distribution:

> ./bin/sign_update path_to_your_update.zip
> The output will be an XML fragment with your update’s EdDSA signature and (optional) file size.
> ...
> You’ll add these attributes to your enclosure in the next step.

I have clarified the latter section slightly more by inlining the sign_update output, before going to the next section where it shows the attributes in the appcast too.

**Comment by lostminds** [comment]
Yes. I think the main misunderstanding on my part was that I assumed the sparkle ./bin/sign_update tool would modify the file adding some sort of signature, as that's the way the apple codesign tool works. And then following that it would be incompatible with also using codesign to sign the same file. 

However, regardless of this misunderstanding, my original point still stands I think: That if you like me use codesigned dmgs for your downloads already, it would be convenient if they could just be used as they are for sparkle updates as well. If their signatures could be verified for integrity by Sparkle, it would provide a comparable level of security to the EdDSA signatures, but with no extra signing steps needed for the developer.

**Comment by zorgiepoo** [comment]
Yep, I'm generally leaving this issue open to assess and collect feedback regarding this feature request to validate dmg signatures before going such a route.

--

It's nice for the developer to maintain one less thing, it has comparable security, not necessarily nice for the user (eg no delta updates, and less reliable/slower disk image updates; this may be *fine for you or your app*, but it doesn't mean it's fine for us to recommend and spend effort in maintaining overall), doesn't allow fallback/rotation if you lose your Dev ID keys or need to change them, it will need a security review (key verification is our most critical/difficult part of the codebase to review) and be integrated into our comprehensive testing for signing verification, should have changes to key rotation to allow dropping Ed(DSA) from existing apps for completeness in a secure way, and a good implementation to test the designated requirement (eg, `codesign -dvvv` is a bad one)

Regarding implementation we just call `SecCodeCopyDesignatedRequirement()` today on the old bundle to get its designated requirement. Then we match that with the new bundle. On my machine, the string representation of one of my apps is roughly:

```
anchor apple generic and identifier "com.myorg.myapp" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = MY_TEAM_ID)
```

The `and identifier ...` part is a problem because the app bundle ID is not likely the same as the identifier in the signed dmg. So we have to do something *more complicated* to support validating dmg's, perhaps either hardcoding these certificate leafs/subject.OU in a newly created string, or parsing/stripping the identifier from an existing string the API gives us. Neither of these two approaches at glance sound *good enough* to ship and not be fragile in case anything changes in the future.

**Comment by hstriepe** [comment]
Would you sign and notarize a PKG installer the "Apple Way" and then sign the zip with EdSA?

**Comment by zorgiepoo** [comment]
Yes except you may not need to zip the pkg. https://sparkle-project.org/documentation/package-updates/

Any further questions about that should be in a separate discussion thread as this is unrelated.

**Comment by zorgiepoo** [comment]
I don't think keeping this issue open is actionable.

Using apple signing checks for DMGs is probably never going to happen for reasons stated above.

Not signing archives with EdDSA is not recommended.

At least for a long time however, non-signed archives will have to be supported for compatibility/legacy.
