### ISSUE TITLE
Cannot add Sparkle through SPM in newest Xcode version

### ISSUE THREAD

**Issue by yspreen** [sparkle-project/Sparkle#2043]
![image](https://user-images.githubusercontent.com/12631527/146404897-bfaa70a6-13c8-4a0e-82a5-ff220ba2409c.png)

This is Version 13.2 (13C90)

**Comment by yspreen** [comment]
okay wow it seems like the app store build of xcode is just broken. thanks apple. keeping this open if other's have the same issue. 

https://appleinsider.com/articles/21/12/14/app-store-version-of-xcode-132-causing-problems-for-developers

**Comment by zorgiepoo** [comment]
Xcode 13.2.1 release notes seem to indicate this is fixed now.
