### ISSUE TITLE
Foo.mkpg can't be installed because its digital signature is invalid.

### ISSUE THREAD

**Issue by ghazel** [sparkle-project/Sparkle#205]
When trying to install an update on OS X 10.8 (Sparkle 1.5 b6), the installer for the update fails inside Installer.app with a dialog that says:

```
Foo.mkpg can't be installed because its digital signature is invalid.

The package may have been corrupted or tampered with. Get a new copy of the package and try again.
```

This mpkg is certainly signed properly with productsign and runs and installs properly when downloaded manually.

**Comment by pornel** [comment]
This is about Sparkle 1.5. We've changed a lot since, so please test with the latest version and reopen if it's still a problem.
