### ISSUE TITLE
Cannot run from source, archiving and exporting works

### ISSUE THREAD

**Issue by ezfe** [sparkle-project/Sparkle#2056]
### Description of the problem

If I use Product > Archive and prepare a release version of my app, Sparkle works as expected.

If I use Product > Run (release or debug configuration, with or without "debug executable" checked), the app fails to launch:

### Do you use Sandboxing in your app?

No.

### Version of `Sparkle.framework` in the latest version of your app

2.0.0

### Sparkle's output from Console.app
```
dyld[8434]: Library not loaded: @rpath/Sparkle.framework/Versions/B/Sparkle
  Referenced from: /Users/ezekielelin/Library/Developer/Xcode/DerivedData/M1Craft_UI-bkyiznndhqeunjedapiebccjniun/Build/Products/Debug/M1Craft UI.app/Contents/MacOS/M1Craft UI
  Reason: tried: '/Users/ezekielelin/Library/Developer/Xcode/DerivedData/M1Craft_UI-bkyiznndhqeunjedapiebccjniun/Build/Products/Debug/Sparkle.framework/Versions/B/Sparkle' (code signature in <B255A964-CEDF-36AD-B61B-3D5A8F41179E> '/Users/ezekielelin/Library/Developer/Xcode/DerivedData/M1Craft_UI-bkyiznndhqeunjedapiebccjniun/Build/Products/Debug/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/ezekielelin/Library/Developer/Xcode/DerivedData/M1Craft_UI-bkyiznndhqeunjedapiebccjniun/Build/Products/Debug/PackageFrameworks/Sparkle.framework/Versions/B/Sparkle' (no such file), '/Users/ezekielelin/Library/Developer/Xcode/DerivedData/M1Craft_UI-bkyiznndhqeunjedapiebccjniun/Build/Products/Debug/M1Craft UI.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <B255A964-CEDF-36AD-B61B-3D5A8F41179E> '/Users/ezekielelin/Library/Developer/Xcode/DerivedData/M1Craft_UI-bkyiznndhqeunjedapiebccjniun/Build/Products/Debug/M1Craft UI.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/ezekielelin/Library/Developer/Xcode/DerivedData/M1Craft_UI-bkyiznndhqeunjedapiebccjniun/Build/Products/Debug/M1Craft UI.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <B255A964-CEDF-36AD-B61B-3D5A8F41179E> '/Users/ezekielelin/Library/Developer/Xcode/DerivedData/M1Craft_UI-bkyiznndhqeunjedapiebccjniun/Build/Products/Debug/M1Craft UI.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Library/Frameworks/Sparkle.framework/Versions/B/Sparkle' (no such file), '/System/Library/Frameworks/Sparkle.framework/Versions/B/Sparkle' (no such file)
```

### Steps to reproduce the behavior

I've attached a copy of the app from the DerivedData folder so that it exhibits the problem:

[M1Craft UI.app.zip](https://github.com/sparkle-project/Sparkle/files/7835911/M1Craft.UI.app.zip)

Source project:

https://github.com/ezfe/m1craft

**Comment by zorgiepoo** [comment]
This has to do with hardened runtime's library validation. It wants Sparkle to be signed with the same signature as your app (which the Product > Archive process will do in the export process). It *should* work if Sparkle is set to Embed & Sign in the target settings but I notice your project doesn't have that any Embed options available, so I wonder if Xcode broke something recently.. Another workaround is disabling library validation only for debug/development.

**Comment by zorgiepoo** [comment]
I'm also on a broken Xcode build actually, so I'm going to try upgrading and check again (#2043)

**Comment by zorgiepoo** [comment]
Alright there's nothing broken about Xcode, just that a new blank project doesn't have hardened runtime automatically enabled.

I think you've two choices:
1. Sign your project for Development instead of Sign to run Locally (for "Signing Certificate" under Signing & Capabilities). Ad-hoc signature (local signing) does not suffice when library validation is enabled.
2. Disable library validation only for Debug/development.

**Comment by ezfe** [comment]
I disabled Library Validation for debug only and that worked. Thanks!
