### ISSUE TITLE
Spanish localization errors

### ISSUE THREAD

**Issue by miliuco** [sparkle-project/Sparkle#206]
Hello, Andy, and thanks for your work. There are a few errors in the spanish localization.

---

There is a string that is not the same in the Sparkle.strings file from En.lproj and Es.lproj:

// TEXT IN Sparkle.strings FROM En.lproj
"Should %1$@ automatically check for updates? You can always check for updates manually from the %1$@ menu." = "Should %1$@ automatically check for updates? You can always check for updates manually from the %1$@ menu.";

// TEXT IN Sparkle.strings FROM Es.lproj
"Would you like %@ to check for updates on startup? If not, you can initiate the check manually from the %@ menu." = "¿Quiere que %1$@ compruebe si hay actualizaciones al arrancar? También podrá comprobarlo desde el menú %1$@.";

The text in Sparkle.strings from Es.lproj should be:

"Should %1$@ automatically check for updates? You can always check for updates manually from the %1$@ menu." = "¿Quiere que %1$@ compruebe si hay actualizaciones al arrancar? También podrá comprobarlo desde el menú %1$@.";

---

There is a missed string:

// TEXT IN Sparkle.strings FROM En.lproj, MISSED IN Es.lproj
"Checking for updates..." = "Checking for updates…";

It should be added into spanish Sparkle.strings:

"Checking for updates..." = "Comprobando actualización…";

---

There is a clipped textbox in SUUpdatePermissionPrompt.nib, see the image:

http://miliuco.es/pub/sparkle.png

---

Here I put a zip containing both corrected spanish files (Sparkle.strings and SUUpdatePermissionPrompt.nib.

http://miliuco.es/pub/sparkle-es.zip

Kind regards, Emilio P. Egido.

**Comment by Eitot** [comment]
This issue has been resolved. Both strings are localised in es.lproj.
