### ISSUE TITLE
SUFeedURL set using `defaults write` seems to be ignored

### ISSUE THREAD

**Issue by digitalmoksha** [sparkle-project/Sparkle#2064]
## Summary

It doesn't seem like the overridden `SUFeedURL` is being honored.  Usually you can override `SUFeedURL` by using `defaults write`:

```
defaults write com.mycompany.myapp SUFeedURL "https://example.org/releases/testing/releases.xml"
```

Using the previous version on my app (2.1.4), it detects the updated `SUFeedURL`, recognizes there is a new update (2.5) and installs it.

After updating, when I run the "Check for updates", I get the dialog "You're up to date" (which is correct), but the message is

> MyApp 2.1.4 is currently the newest version available. (You are currently running version 2.5.)

which is incorrect.

I then set the `SUFeedURL` to point to a special appcast that has a far future version, so I can test the update from the new version to an even newer version.

```
defaults write com.mycompany.myapp SUFeedURL "https://example.org/releases/testing/far_future_release.xml"
```

The "Check for update" gives me the exact same message as above.  I should have gotten the message that version 999 was available.

## Version

2.0

**Comment by zorgiepoo** [comment]
It will not get honored if your app happens to implement the [delegate feed URL method](https://sparkle-project.org/documentation/api-reference/Protocols/SPUUpdaterDelegate.html#/c:objc(pl)SPUUpdaterDelegate(im)feedURLStringForUpdater:) or uses setFeedURL: and overrides the user defaults. I would check these two things, I don't think anything related to this has changed recently.

**Comment by digitalmoksha** [comment]
Hmm, I'm not using the delegate method nor `setFeedURL`.  And my app has been sandboxed for quite a while now.

The version of Sparkle I previously used was built from this commit: https://github.com/sparkle-project/Sparkle/commit/438f4a21d5b52596b899d9931525c02a691b2287, back in Aug 2020.

This is the first version of my app shipping using the most recent Sparkle.

I do see I'm still using `SUUpdater` for my `checkForUpdates`.  Not sure if that makes a difference or not, but I should convert it to `SPUUpdater`.

I also notice that my licensing is borked for some reason after the upgrade. So maybe that's an indication something else is going on, making the user defaults not work.

**Comment by digitalmoksha** [comment]
I'm closing this since I think something went sideways in building. I'll re-open if needed.

**Comment by zorgiepoo** [comment]
> Hmm, I'm not using the delegate method nor `setFeedURL`. And my app has been sandboxed for quite a while now.
> 
> The version of Sparkle I previously used was built from this commit: [438f4a2](https://github.com/sparkle-project/Sparkle/commit/438f4a21d5b52596b899d9931525c02a691b2287), back in Aug 2020.

Ah, that was a long time ago. But indeed I cannot reproduce this issue in a test app, so I'd go about trying to debug your app.
