### ISSUE TITLE
checkForUpdateInBackground shows UI when up-to-date

### ISSUE THREAD

**Issue by qeude** [sparkle-project/Sparkle#2083]
### Description of the problem

I'm trying to use Sparkle 2.0 in my SwiftUI app. Something is not clear though, I wanted to use [`checkForUpdateInBackground`](https://sparkle-project.org/documentation/api-reference/Classes/SPUUpdater.html#/c:objc(cs)SPUUpdater(im)checkForUpdatesInBackground) when my app is starting. I was expecting that it wouldn't show any pop-up when my app is up-to date. But it opens this pop-up on every launch. Is there anything I am missing ? 

<img width="372" alt="Screenshot 2022-01-30 at 21 49 46" src="https://user-images.githubusercontent.com/19294297/151717296-ca4bdaa1-669d-4d32-916e-bd1834761615.png">

I am actually triggering it explicitly to ensure that updates are checked on launch.

### Do you use Sandboxing in your app?
No

### Version of `Sparkle.framework` in the latest version of your app
2.0.0
### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
2.0.0

**Comment by zorgiepoo** [comment]
Your expectation is correct, that it shouldn't show anything when there's no new update found. However I cannot reproduce your issue in a sample app, so either more investigation is needed (eg make sure checkForUpdates isn't also called at some point) or a repro case.

**Comment by qeude** [comment]
@zorgiepoo you might be able to reproduce using [this branch](https://github.com/qeude/Swush/tree/feature/check-updates-in-background) of my project. You should be able to build it easily since it's not a big project. The last version available in the app cast should be 0.2.2-4.

**Comment by zorgiepoo** [comment]
I checked out the branch and I don't think I'm able to repro the issue still. I do see a background check being done (after I turned on update checks in your app) but I don't see it falsely notifying me that no update is available on your app's launch.

Some suggestions, not sure if any are relevant to this problem, but maybe worth trying to see if it changes anything:

* Sparkle [prefers setting options via Info.plist](https://sparkle-project.org/documentation/customization/), and only programmatically if the user needs to change an option. This keeps as many settings away from using the user defaults of your app (`defaults read com.qeude.Swush` in your case) as possible. If update check interval is not customizable, it should not be set programatically. Defaults persist even if for example, you no longer want to customize the check interval (to make changes here you may need to delete/reset your user defaults).
* When properties need to be set programatically they should be set by user demand. i.e, `automaticallyChecksForUpdates =` setter should not be called every `init()`, only when the user changes the default upon a preference change. These setters have logic to reset the updater cycle after a short delay which is only well suited for user interaction, plus you may be making persistent changes to user defaults unnecessarily. The default state can be set in the Info.plist (or when not set, Sparkle will ask user permission if it wants update checks on 2nd launch of your app).
* If you're going to check for updates in background on every launch, you might consider disabling automatic checks in the Info.plist unless you still want the automatic scheduler to be running during the app's lifetime (this depends on the app and what you want).

**Comment by qeude** [comment]
Hm, that's weird, I'm almost sure that I got this behaviour with `checkForUpdatesInBackground`. Thanks for the few tips though, I will try to use the `checkForUpdatesInBackground` version on a longer period of time. If the problem persist I'll reopen this issue 🙌🏼
