### ISSUE TITLE
How can i make a silent update without user's permission

### ISSUE THREAD

**Issue by hieplee2997** [sparkle-project/Sparkle#2088]
I want Sparkle to start silent update without alert. I see updater.checkForUpdateInBackgroud but it still show alert when found an update(even sometime this method doesn't working).
Can i do this? Thank

**Comment by zorgiepoo** [comment]
https://sparkle-project.org/documentation/customization/
SUAutomaticallyUpdate Info.plist key

**Comment by hieplee2997** [comment]
> https://sparkle-project.org/documentation/customization/ SUAutomaticallyUpdate Info.plist key. Installed when app quits. Prefer Sparkles automatic scheduler instead of calling checkForUpdateInBackgroud directly

i am confusing between SUEnableAutomaticChecks, SUAllowsAutomaticUpdates, SUAutomaticallyUpdate. Do i must set all these value? Any conflig between these key if i set all of them to TRUE

**Comment by zorgiepoo** [comment]
Set SUEnableAutomaticChecks to YES if you don’t want to ask users permission on whether Sparkle can check for updates automatically. If you don’t set it, Sparkle will ask the user permission if it can check for updates. If you set it to NO, Sparkle will not automatically check for new updates

SUAllowsAutomaticUpdates. Ignore it. It’s for developers that want to disable automatic downloading/installing of updates. You want the opposite. 

SUAutomaticallyUpdate. Set to YES to automatically download/install updates silently on quit when possible.

**Comment by hieplee2997** [comment]
I understand, thank you

**Comment by hieplee2997** [comment]
@zorgiepoo I want to ask a bit. Why the prompt notify lastest version alway front of main app, but the alert notify have an update can be backward. How can i set the alert update alway front of main app as the prompt?

**Comment by hieplee2997** [comment]
@zorgiepoo can i build a custom sparkle from code in github, how can do this?

**Comment by hieplee2997** [comment]
@zorgiepoo If i set SUAutomaticallyUpdate is TRUE, it will auto check for update and download, then it automatically install on quit, right? So, how can i trigger quit and relaunch programmatically?

**Comment by zorgiepoo** [comment]
Possibly [this method](https://sparkle-project.org/documentation/api-reference/Protocols/SPUUpdaterDelegate.html#/c:objc(pl)SPUUpdaterDelegate(im)updater:willInstallUpdateOnQuit:immediateInstallationBlock:)
