### ISSUE TITLE
"Declaration of instance variables in the interface is deprecated" in SPUStandardUpdaterController.h

### ISSUE THREAD

**Issue by Wevah** [sparkle-project/Sparkle#2093]
## Summary

Sometimes when building I get warnings about instance variables in the header being deprecated. These are `IBOutlet` variables.

(Not urgent, just gets my perfectionism going.)

## Possible Fix

Replace the header ivars with `@property`s:

```objc
@property (weak) IBOutlet id<SPUUpdaterDelegate> updaterDelegate;
@property (weak) IBOutlet id<SPUStandardUserDriverDelegate> userDriverDelegate;
```

## Version

2.1.0

**Comment by zorgiepoo** [comment]
The correct fix is surrounding the ivar block with pragma ignores on the appropriate compiler warning (maybe `-Wobjc-interface-ivars`). This is one of those pedantic compiler warning that isn't turned on by default.

Sparkle cannot use properties here. That will allow developers to support setting them after initialization which we don't support. At the same time we want them to be connectable outlets, so ivars is the middle ground of both of those.

**Comment by Wevah** [comment]
That makes sense, though I'd have preferred documenting that setting them after initilization is unsupported.

I did try adding those pragmas in my own code (around the framework impor) before filing this, but it didn't make a difference, so I'm assuming it'd need to be in `SPUStandardUpdaterController.h` as you mentioned.

**Comment by zorgiepoo** [comment]
People didn’t read the documentation. It’s better now that it’s not possible and a compiler error.

**Comment by zorgiepoo** [comment]
Yeah that could potentially work too.

**Comment by gnachman** [comment]
IBOutlets don't have to be in a header file. You can do
```
@implementation MyClass {
  @IBOutlet NSView *_whatever;
}
```

**Comment by zorgiepoo** [comment]
Neither of those approaches work here. The IBOutlet is not an implementation detail, it’s an interface intended to be consumed by clients using the framework. A class extension only works when you’ve the source code to that class at compile time.

A read only marked IBOutlet property with some setter backed or ivar synthesized private implementation might work (I haven’t tested it)
