### ISSUE TITLE
InstallerLauncher bundle identifier visible on macOS Monterey

### ISSUE THREAD

**Issue by Frexas** [sparkle-project/Sparkle#2095]
### Description of the problem
`org.sparkle-project.InstallerLauncher` bundle identifier is visible in authorization (AuthorizationRightSet) prompt (on macOS Monterey only)

https://prnt.sc/zvNF4baRXVCM

### Do you use Sandboxing in your app?
Yes

### Version of `Sparkle.framework` in the latest version of your app
2.0.0-rc1

**Comment by zorgiepoo** [comment]
This will probably be "fixed" in #2096
