### ISSUE TITLE
Validation of Developer ID Distribution fails with AutoUpdate/Updater/Installer Launcher not having sandbox enabled

### ISSUE THREAD

**Issue by leisurehound** [sparkle-project/Sparkle#2098]
### Description of the problem
Building my App with Xcode 13.2.1 on Monterey 12.2.1 is failing validation.  Everything works fine on my development machine and I have no non-development machine, but when I try to validate the archive in Xcode I get the following error that the Sparkle binaries are not sandboxed.
```
App sandbox not enabled. The following executables must include the "com.apple.security.app-sandbox" entitlement with a Boolean value of true in the entitlements property list: 

[( "....app/Contents/Frameworks/Sparkle.framework/Versions/B/Autoupdate", 
"....app/Contents/Frameworks/Sparkle.framework/Versions/B/Updater.app/Contents/MacOS/Updater", "....app/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/org.sparkle-project.
InstallerLauncher.xpc/Contents/MacOS/org.sparkle-project.InstallerLauncher" )] Refer to App Sandbox page at https://developer.apple.com/documentation/security/app_sandbox for more information on sandboxing your app.
```
While I have referred to that page on app sandbox, its unclear why my app is sandboxed but not the sparkle portions.
Note I have followed the instructions https://sparkle-project.org/documentation/sandboxing/ but alas still can validate the app nor customers can't install.
### Do you use Sandboxing in your app?
yes
### Version of `Sparkle.framework` in the latest version of your app
2.0
### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
n/a
### Sparkle's output from Console.app
```

```

**Comment by zorgiepoo** [comment]
I don't think anybody here has tried/used validation. When you notarize your app, it validates your app for notarization anyway. That might be a thing only applicable for App Store apps so I'm not sure this report is even valid. For example it's totally sensible today to ship a completely non-sandboxed & notarized app.

**Comment by zorgiepoo** [comment]
And Sparkle needs unsandboxed components even in a Sandboxed app.

Closing as I believe you're using the wrong workflow.

**Comment by leisurehound** [comment]
hmm...so what is the correct workflow?  Here is what I'm doing:

1. Archive build the app
2. Distribute app from the Xcode organizer using Developer ID
3. Upload (for Apple Notary Signing)
4. Select Automatically Manage Signing
5. Upload
6. Receive Successful notarization alert
7. Select Archive in organizer -> Show in Finder -> Show Package Contents on xcarchive file -> compress Products/Applications/<APP>.app file
8. Distribute zipped .app file to customer
9. Customer receives 'App cannot be opened because Apple cannot check it for malicious content.  The software needs to be updated. Contact Developer' (user has 'Allow apps downloaded from App Store & Identified Developers' selected in System Preferences). There is no 'Run Anyway' option.
10. Customer complains
11. I take the same archive from Xcode organizer and Validate.
12. Receive the error presented at the top of this issue.

I have since removed all references of Sparkle from the target (code and library) and archive, distribute, auto sign, compress, distribute zipped file and the user reports no issues.

So obviously I'm doing it wrong, but its unclear what is the right way to ship a notorized sandboxed app on Monterey (app's minimum target is 12).

**Comment by zorgiepoo** [comment]
Step 7 is wrong. The archive organizer window should have an option to Export the notarized app (after it has become notarized successfully). You shouldn't have to wrangle inside a xcarchive file yourself.

Step 9 shouldn't be the expected outcome in any case. I hope you're verifying it on your system first before the customer does (i.e, downloading your app from your web server).

You should also check:

> You can diagnose code signing problems with codesign --deep -vvv --verify <path-to-app> for code signing validity, spctl -a -t exec -vv <path-to-app> for Gatekeeper validity, and by checking logs in the Console.app. See Apple’s [Code Signing in Depth](https://developer.apple.com/library/archive/technotes/tn2206/_index.html) for more code signing details.
