### ISSUE TITLE
Making Sparkle easier to use for every developer - proposal and request for feedback.

### ISSUE THREAD

**Issue by johncclayton** [sparkle-project/Sparkle#2101]
## Summary

None of the pre-requisites for getting a working appcast going are particularly difficult, yet it still takes quite a bit of work to get everything running smoothly, as developers need to: organize a webserver (for the app cast and assets), a way to integrate builds + changelogs, think about the signing key security and potential shared access, work out how they'll support multiple channels. 

I've written up an idea / proposal to help solve this - but before I start writing code I'd love to get some feedback.  I would greatly appreciate honest feedback about the usefulness of the proposal, in particular from the app developers.  Where might these creatives be hanging out?

The suggestion and GitHub discussion page is located here: https://github.com/johncclayton/Necklace/discussions/3

If anyone knows where I might a bunch find developers that use Sparkle - please drop me a line so I can investigate and potentially post my question further into the community.  Thank  you.

## Possible Fix

Implement the suggestion :-)

## Version

Not related to a specific version.

**Comment by zorgiepoo** [comment]
Some of the problems like storage space and having a web server are problems Mac developers need set up independently/regardless of Sparkle.

From maintainers perspective I’d rather focus on making any improvements to generate_appcast than yet another service/docker/ layer. I’m also weary about additional layers supporting a full feature set now, and in the future. 

I’d probably not store private keys on the same machine hosting the web server btw.

I also don’t know how common winsparkle/netsparkle + sparkle apps actually are in practice.

Lastly this isn’t entirely the appropriate forum for this (not really something for us to implement and not an issue)

**Comment by johncclayton** [comment]
Hi @zorgiepoo 

I appreciate the feedback - and I'm aware that this isn't the right place to implement the project, nor discuss it in detail.  I wouldn't see this project as the responsibility of __any__ Sparkle framework provider; rather as something built on top (as you mention). 

Nice point about private key storage; although there are plenty of ways to make that more secure than it is now - e.g. Key Vault, or similar mechanisms.   In my pipelines for example I'm referencing the secret via a parameter group that in turn is synced to a Key Vault - depending on the day I wake up it feels like overkill -or- I feel happier because the thing isn't on a single machine.  As a solo-dev my other choice is to copy the file onto my local machine and store it in something like 1Password.  I'd be interested in seeing what other devs do. 

So, yes - I agree this isn't the place to discuss it in detail - that'd be the Necklace github page or other community forums where the actual end users are hanging out - and it feels a touch odd when I can't answer that question myself, I suppose I could look on various discord channels ... 

Have a great day!
