### ISSUE TITLE
Is mapping of version numbers between Xcode & Sparkle working as expected?

### ISSUE THREAD

**Issue by pradeepb28** [sparkle-project/Sparkle#2104]
## Summary

Hello, I am trying to test the iterative updates on Sparkle. To make that happen, I updated the version number on Xcode from 1 to 1.1.0, here is an example
![CleanShot 2022-03-14 at 17 39 30@2x](https://user-images.githubusercontent.com/6823101/158169280-64981411-7fde-4de0-80d8-ff9305d9b784.png)

and in info.plist, I just left it as is 
![CleanShot 2022-03-14 at 17 40 12@2x](https://user-images.githubusercontent.com/6823101/158169404-d42fb038-4717-41d1-a07e-a7cbcc5fb7e0.png)

in appcast file this is how it was generated, **_is this correct?_**
![CleanShot 2022-03-14 at 17 42 01@2x](https://user-images.githubusercontent.com/6823101/158169671-4966364f-eefa-4a7f-a8de-a43a2822f923.png)

at the same time I was looking at pubDate tag it doesn't show the time when the latest appcast was generated rather it shows the time when the v1 appcast was generated, is this correct?

All I am asking this because, when I click on "Check for updates" button in the app, it shows me 1 instead of 1.1.0 on the sparkle popup. Although I am successfully able to update it, the UI makes it little confusion. After updating the app, I clicked "check for updates" again, the popup shows there is a latest update(despite I am already on the latest update).

Any guidance is highly appreciated. Thanks!

## Version

Sparkle 2

**Comment by zorgiepoo** [comment]
The problem is you have to increment the Build  / CFBundleVersion too. You have to do that anyway even if you weren’t using Sparkle
