### ISSUE TITLE
Same SUPublicEDKey among different projects

### ISSUE THREAD

**Issue by pradeepb28** [sparkle-project/Sparkle#2105]
## Summary

Hello Sparkle team,

I am integrating Sparkle into a new project when I try to generate keys, I've received the following message in terminal 

![CleanShot 2022-03-23 at 15 56 54@2x](https://user-images.githubusercontent.com/6823101/159679026-dac52d1c-b155-4811-a2a2-9461c1d0d9a1.png)

I've following question:
-  That key I am currently using for another project, so was it suppose to generate new key for every project or one key among different projects are fine?

**Comment by zorgiepoo** [comment]
It’s your choice. Most would use same key for different projects unless it’s a different organization. Akin to how you’re likely using same Apple Developer ID for both apps.

**Comment by pradeepb28** [comment]
Thanks @zorgiepoo, the app I am working on is for a different org,  how could we generate a different key?

**Comment by zorgiepoo** [comment]
All the tools have an --account option as of 2.1. Check the --help on the tools.
