### ISSUE TITLE
Exception crash - This coder is expecting the replaced object 0x60000071f300 to be returned from NSClassSwapper.initWithCoder instead of <SUUpdater: 0x60000071f840>

### ISSUE THREAD

**Issue by PierL** [sparkle-project/Sparkle#2107]
I'm using Sparkle 1.27.1 and when the deployment target was set to 10.9 I had no issues.

I tried to change the target to 10.11 and now the app crashes at launch with the following exception:

2022-04-07 00:23:18.984230+0100 MyApp[25130:1879019] [General] This coder is expecting the replaced object 0x60000071f300 to be returned from NSClassSwapper.initWithCoder instead of <SUUpdater: 0x60000071f840>
2022-04-07 00:23:18.994010+0100 MyApp[25130:1879019] [General] (
	0   CoreFoundation                      0x00000001c174eb08 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x00000001c1499e14 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001c174e954 +[NSException exceptionWithName:reason:userInfo:] + 0
	3   UIFoundation                        0x00000001c512fba0 UINibDecoderDecodeObjectForValue + 804
	4   UIFoundation                        0x00000001c512f864 -[UINibDecoder decodeObjectForKey:] + 324
	5   AppKit                              0x00000001c41fe350 -[NSNibConnector initWithCoder:] + 112
	6   AppKit                              0x00000001c4203544 -[NSNibControlConnector initWithCoder:] + 84
	7   UIFoundation                        0x00000001c512fb3c UINibDecoderDecodeObjectForValue + 704
	8   UIFoundation                        0x00000001c512fd68 UINibDecoderDecodeObjectForValue + 1260
	9   UIFoundation                        0x00000001c512f864 -[UINibDecoder decodeObjectForKey:] + 324
	10  AppKit                              0x00000001c41fd084 -[NSIBObjectData initWithCoder:] + 172
	11  UIFoundation                        0x00000001c512fb3c UINibDecoderDecodeObjectForValue + 704
	12  UIFoundation                        0x00000001c512f864 -[UINibDecoder decodeObjectForKey:] + 324
	13  AppKit                              0x00000001c41fce50 loadNib + 324
	14  AppKit                              0x00000001c41fc3dc +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 800
	15  AppKit                              0x00000001c43e589c -[NSWindowController loadWindow] + 332
	16  AppKit                              0x00000001c43e55e0 -[NSWindowController window] + 96
	17  MyApp                       0x0000000102c16f90 -[PreferencesController initWithUserData:] + 2380
	18  MyApp                        0x0000000102c25b48 -[AppDelegate applicationWillFinishLaunching:] + 1220
	19  CoreFoundation                      0x00000001c16c2ddc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
	20  CoreFoundation                      0x00000001c1767578 ___CFXRegistrationPost_block_invoke + 52
	21  CoreFoundation                      0x00000001c17674e4 _CFXRegistrationPost + 456
	22  CoreFoundation                      0x00000001c1691a74 _CFXNotificationPost + 732
	23  Foundation                          0x00000001c254ee48 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
	24  AppKit                              0x00000001c421c964 -[NSApplication finishLaunching] + 360
	25  AppKit                              0x00000001c421c560 -[NSApplication run] + 292
	26  AppKit                              0x00000001c41edda8 NSApplicationMain + 1132
	27  MyApp                       0x0000000102c23d3c main + 88
	28  dyld                                0x0000000102d49088 start + 516
)

Any ideas? I'm on macOS 12 (Monterey).

**Comment by zorgiepoo** [comment]
SUUpdater is a singleton class. If it is instantiated in a nib you will need to ensure that SUUpdater hasn’t been instantiated beforehand, either programmatically or from being instantiated in another nib. I believe Cocoa is showing some enforcement opting you in some optimized path after bumping your deployment target; that’s my best guess.

Sparkle 2 also forgoes singletons so it would also be in your best interest to instantiate SUUpdater once and pass it around elsewhere long term.
