### ISSUE TITLE
Allow fingerprint authentication when upgrading

### ISSUE THREAD

**Issue by sandercox** [sparkle-project/Sparkle#2108]
## Summary

When sparkle downloads the new installer and tries to execute this we need to provide administrator credentials. On a regular direct install with the latest M1 macBooks you can use the fingerprint reader to authenticate. We'd like to be able to support this for our in-app updater experience too.

Upgraded to the latest Sparkle 2.1 version hoping that would fix the issue but doesn't seem to have changed anything yet.

We use installer packages (`.pkg` files) for distribution of our software and updates.

**Comment by zorgiepoo** [comment]
See  #1040
