### ISSUE TITLE
Not all strings localized in automatic update windows in Sparkle v1

### ISSUE THREAD

**Issue by 4or5trees** [sparkle-project/Sparkle#2109]
## Summary

The automatic update windows shown when prompted by `SUUpdater.installUpdatesIfAvailable()` are not all properly localized.

<img width="351" alt="checking-for-updates" src="https://user-images.githubusercontent.com/31886148/163364396-658399cb-9810-465f-bc5c-3ad211e0775e.png">
<img width="352" alt="downloading-update" src="https://user-images.githubusercontent.com/31886148/163364428-577ff874-ba14-4c2b-bfdf-762e2feebf0a.png">
<img width="351" alt="extracting-update" src="https://user-images.githubusercontent.com/31886148/163364437-ab367bd8-8447-4044-b35d-8954862f10e7.png">

Only the last screen (`"Installing updates..."`) is localized properly for my OS language (Dutch). This screen also appears in a different location compared to the earlier screens.

<img width="351" alt="installing-update" src="https://user-images.githubusercontent.com/31886148/163364451-85e6f613-79ee-48fa-9449-f4713c26b082.png">

## Possible Fix

I am not a proper macOS developer and am using Sparkle via Xamarin.Mac bindings, but maybe you could nudge me in the right direction (I know Sparkle 1.x will not be updated unless there is a regression/security issue).

The `"Checking for updates"` string seems to come from `SUUserInitiatedUpdateDriver.m:53`:

```objective-c
[self.checkingController beginActionWithTitle:SULocalizedString(@"Checking for updates...", nil) maxProgressValue:0.0 statusText:nil];
```

The `SUUIBasedUpdateDriver` has three invocations of `beginActionWithTitle:SULocalizedString()`:

```objective-c
//SUUIBasedUpdateDriver.m:209
[self.statusController beginActionWithTitle:SULocalizedString(@"Downloading update...", @"Take care not to overflow the status window.") maxProgressValue:0.0 statusText:nil];

//SUUIBasedUpdateDriver.m:294
[self.statusController beginActionWithTitle:SULocalizedString(@"Extracting update...", @"Take care not to overflow the status window.") maxProgressValue:0.0 statusText:nil];

//SUUIBasedUpdateDriver.m:339
[self.statusController beginActionWithTitle:SULocalizedString(@"Installing update...", @"Take care not to overflow the status window.") maxProgressValue:0.0 statusText:nil];
```
However, the `"Installing update..."` string also appears in `Autoupdate.m:138`:
```objective-c
[self.statusController beginActionWithTitle:SULocalizedString(@"Installing update...", @"")
```

It seems the localization works properly for `Autoupdate`, but not in `SUUIBasedUpdateDriver` and `SUUserInitiatedUpdateDriver`. 

The localizations for checking/extracting/downloading for the Dutch language _are_ present: https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/nl.lproj/Sparkle.strings#L47 

## Version

1.27.1

## Kudos

Sparkle provides an excellent developer experience for automatic updates on Mac. Major thanks for all your hard work!

**Comment by zorgiepoo** [comment]
installUpdatesIfAvailable is a deprecated API and removed in Sparkle 2.

Regardless I can't reproduce the issue in Sparkle 1 or 2 with the test app when checking for updates manually using dutch language, which as far as UI goes should be taking the same path.
