### ISSUE TITLE
Release Notes url 404 err stops update

### ISSUE THREAD

**Issue by jdde** [sparkle-project/Sparkle#2117]
## Summary
When you try to install an update on macOS and sparkle tries to load the release-notes from an invalid url(or just not existing url) the update won't work.

## Possible Fix
Ignore 404 errors when running update process.
Or even better: ignore all http errors from release-notes url. From my perspective it should be possible to install an update, even when the release-notes url is not available. A downtime of a website should not block the update process of an application.

## Version
Sparkle 2, newest version

**Comment by zorgiepoo** [comment]
Need additional diagnostics, debugging, or a sample 404 URL and/or sample project.

The intended behavior is 404 release notes URL does not stop downloading or installing an update, only that release notes view is empty; and this is what I reproduce with these test app modified to use a 404 release notes link

I can't reproduce your issue.
