### ISSUE TITLE
generate_appcast with channel recommended workflow

### ISSUE THREAD

**Issue by jessegrosjean** [sparkle-project/Sparkle#2125]
I'm using `generate_appcast` to generate my feed from a collection of `dmg` and `html` files. I would like to support releasing beta versions of my app using the channel feature. I'm not quite sure how best to do this.

Lets say I have a new build and I want to:

1. Release it in beta channel.
2. Wait a few days for testing.
3. Remove beta channel tag so that it's available to everyone.

Is that sequence reasonable?

Here's what I'm thinking, but I'm not sure.

1. I should always run `generate_appcast --channel beta` for new builds.
2. When I'm ready to make that build public I should manually remove the channel tag.

Is that right?

**Comment by zorgiepoo** [comment]
That should work, assuming your stable build is equivalent to the last beta release you published.

**Comment by jessegrosjean** [comment]
Thanks for your help.

**Comment by zorgiepoo** [comment]
also if you have release notes that differ between beta users and stable users you may need to update that too.
