### ISSUE TITLE
upgrade error

### ISSUE THREAD

**Issue by mYCBS** [sparkle-project/Sparkle#2127]
I use sparkle 1.0 project and want to configure and upgrade to the project using sparkle 2.0. At present, an error will be reported. The error message is as follows, what should I do?
![image](https://user-images.githubusercontent.com/11468900/168530173-31adbb45-9dd7-4b78-a42a-bc9034d624fa.png)

**Comment by zorgiepoo** [comment]
Check the console logs for more detailed information on the error. Did you sign the download archive and specify the edSignature in the appcast? Did you follow the website documentation?
