### ISSUE TITLE
Version number/ Build Number

### ISSUE THREAD

**Issue by raghavnaphade** [sparkle-project/Sparkle#2128]
### Description of the problem
Can we get latest version number or build number of application so that we can check current version number with latest one?

### Do you use Sandboxing in your app?
No
### Version of `Sparkle.framework` in the latest version of your app
Yes

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
N/A

[The more information provided and pasted verbatim, the easier it will be to diagnose an issue. If you can provide the affected application/binary and XML feed to reproduce an issue, share them]

**Comment by zorgiepoo** [comment]
I don’t quite understand your question. What problem are you actually trying to solve that Sparkle doesn’t do for you automatically?

**Comment by raghavnaphade** [comment]
Yes according to my understanding, sparkle does check it once in a while and I want functionality like when a user opens the application, the application should check the version number from the XML file which we have uploaded on the server(latest app) and I want to send notification like the update is available you can download it manually.

**Comment by raghavnaphade** [comment]
> I don’t quite understand your question. What problem are you actually trying to solve that Sparkle doesn’t do for you automatically? If you give full context you may get a better response.

Yes according to my understanding, sparkle does check it once in a while and I want functionality like when a user opens the application, the application should check the version number from the XML file which we have uploaded on the server(latest app) and I want to send notification like the update is available you can download it manually.

**Comment by zorgiepoo** [comment]
> Yes according to my understanding, sparkle does check it once in a while and I want functionality like when a user opens the application, the application should check..

Yes there is [checkForUpdatesInBackground](https://sparkle-project.org/documentation/api-reference/Classes/SPUUpdater.html#/c:objc(cs)SPUUpdater(im)checkForUpdatesInBackground) if you need to manually kick off an update check in the background.
