### ISSUE TITLE
Install on quit handler block does not install or relaunch the application

### ISSUE THREAD

**Issue by sherryshao** [sparkle-project/Sparkle#2130]
## Summary

👋 Hello! We've implemented this following function to catch auto-download cases and execute the install and relaunch path at a later time with our own UI:

```
func updater(_ updater: SPUUpdater, willInstallUpdateOnQuit item: SUAppcastItem, immediateInstallationBlock immediateInstallHandler: @escaping () -> Void) -> Bool {
	// Saves this handler
        installAndQuitHandler = immediateInstallHandler

        // Do things to update our UI that'll trigger `installAndQuitHandler` at a later time
        return false
}
```

In this case, our delegate holds onto the `immediateInstallHandler` block and when a user triggers a UI provided by us, we'd then execute this handler - relying on the framework to then, install and relaunch immediately.

However, what we've observed so far is that the handler doesn't install or relaunch the app - and we also don't get any further callbacks in terms of errors or failure from Sparkle (and so we wouldn't be able to revert some animations we'd like to provide our users when we're about to relaunch)

## Possible Fix

So, to note - we can successfully install and relaunch via a custom driver (implements `showReadyToInstallAndRelaunch:`, which goes through this codepath:

```
- (void)installerDidFinishPreparationAndWillInstallImmediately:(BOOL)willInstallImmediately silently:(BOOL)__unused willInstallSilently
{
    if (!willInstallImmediately) {
        [self.userDriver showReadyToInstallAndRelaunch:^(SPUUserUpdateChoice choice) {
            dispatch_async(dispatch_get_main_queue(), ^{
                [self.coreDriver finishInstallationWithResponse:choice displayingUserInterface:YES];
            });
        }];
    }
}
```
We're then able to execute the reply block there and get a successful install and relaunch.

The codepath that we're not able successfully install and relaunch goes through this:
```
            // SPUAutomaticUpdateDriver.m in `installerDidFinishPreparationAndWillInstallImmediately:`
            __weak SPUAutomaticUpdateDriver *weakSelf = self;
            installationHandledByDelegate = [updaterDelegate updater:self.updater willInstallUpdateOnQuit:self.updateItem immediateInstallationBlock:^{
                [weakSelf.coreDriver finishInstallationWithResponse:SPUUserUpdateChoiceInstall displayingUserInterface:NO];
            }];
```

Which seems to use the same path on the `SPUCoreBasedUpdateDriver` - `finishInstallationWithResponse:displayingUserInterface:`

Curious if the automatic update driver is already deallocated further down the road and so we're not able to actually trigger the reinstallation path. Also curious if this was not the intended usage of this code path - if so, is there a way for us to be able to trigger this same codepath with another API?

Any help would be greatly appreciated!

## Version

We're on Sparkle 2.1.0

**Comment by zorgiepoo** [comment]
it may not be documented well but if you want to use the installation block you need to return true, not false (typing this in a rush)

**Comment by sherryshao** [comment]
Thanks for such a quick turnaround! Will try that out this weekend - just to make sure - is this the expected way a block should be treated? (i.e. us holding onto it until the user triggers our UI at a later time)?

**Comment by zorgiepoo** [comment]
The way the block is treated is fine.

I think that's a reasonable approach. Returning true in that method interrupts Sparkle's update cycle instead of ending it and allows the delegate to invoke the installation block. Returning false is equivalent to not implementing the method. In either case, Sparkle will install the update when the app terminates.

An alternative approach, technically, is allowing Sparkle's update cycle to end so later the update can be resumed and you'd get Sparkle's UI for showing the update (-checkForUpdatesInBackground would bring it up programmatically, -checkForUpdates would from the user explicitly checking. If you do nothing and Sparkle automatically checks for updates, Sparkle will wait a week before presenting the ready update if they hadn't terminated the app by then).

**Comment by sherryshao** [comment]
Sounds good - we'll keep in mind the alternatives! As an update - I am able to trigger the install and relaunch behaviour now! Thanks a bunch for such quick responses. Closing!
