### ISSUE TITLE
[Bug] showUpdateInFocus not bring "Checking for update.." to front

### ISSUE THREAD

**Issue by hieplee2997** [sparkle-project/Sparkle#2146]
## Summary

I am using Sparkle 2.0. When i use method `updaterController?.userDriver.showUpdateInFocus()`, the "Checking for update" not be to focus, other alert working fine. Is it bug? I discovery this behavior when internet connection is low or loss.

<img width="420" alt="Screen Shot 2022-06-09 at 18 10 26" src="https://user-images.githubusercontent.com/55306649/172834070-017ac3ba-5ab8-4908-af3f-2b0720f111ac.png">

**Comment by zorgiepoo** [comment]
It's a bug. I forgot about bringing the `checkingController` back in focus.

Note it's preferred to call `checkForUpdates(_)` on the updaterController which should do this if a session is in progress.

**Comment by hieplee2997** [comment]
@zorgiepoo thank you for this. i always use `checkForUpdates(_)` on the updateController.
