### ISSUE TITLE
sign_update should support passing in signing keys as files

### ISSUE THREAD

**Issue by jeremyhu** [sparkle-project/Sparkle#2161]
This should work:

    $ ./build/Release/sign_update -s priv.key /path/to/my.dmg
     ERROR! key not found in the argument. Please provide a valid key.

We're instead required to pass it as the argument and not as a file containing the key:

    $ ./build/Release/sign_update -s $(cat priv.key) /path/to/my.dmg

This is a security vulnerability because it places the signing key into argv  which could be captured by a rogue process on the system looking at command line arguments of processes that are running.

**Comment by zorgiepoo** [comment]
It does. Use the -f flag. Use sign_update from 2.x

```
  -f <private-key-file>   Path to the file containing the private EdDSA (ed25519) key. 
```

**Comment by jeremyhu** [comment]
Can we cherry-pick that into 1.27?

**Comment by zorgiepoo** [comment]
It doesn't have to be ported over. Using sign_update from 2.x doesn't make you have to use Sparkle 2 framework.

**Comment by jeremyhu** [comment]
Yes, but it needlessly complicates build pipelines by needing to manage two different versions.

**Comment by zorgiepoo** [comment]
I would just store the tools binaries to whatever repo/pipeline you're using..

You can potentially open a PR for adding it if to 1.x branch (`master`) if you want but I will not likely tag a release for that, and I also don't want to bring SPM / ArgumentParser dependency over to 1.x

**Comment by jeremyhu** [comment]
Yeah, I was just checking that out, and the overall changes are a bit heavy for 1.27.x.

I'm mainly concerned about the security implications here, and the issue still pertains to 2.x which continues to support `-s`.  Can we get that marked as (deprecated) and slate it for removal at some point to discourage its use?

**Comment by zorgiepoo** [comment]
The original rationale (not by me) by the way for the `-s` option is here: https://github.com/sparkle-project/Sparkle/issues/1766#issuecomment-782012814 which was considering CI platforms.

**Comment by zorgiepoo** [comment]
It would be easier to implement it in 1.x than it would be to cherry-pick a change from 2.x, in this case.

**Comment by jeremyhu** [comment]
Well, CI that want to pass in the key could be supported in a secure way using stdin, eg:

     <thing that outputs the key to stdout> | sign_update -f - /path/to/dmg

**Comment by jeremyhu** [comment]
Also for CI  (in my case), I'd prefer to use `openssl(1)` to do this (like I have been doing for DSA), but I'm having issues (https://github.com/sparkle-project/Sparkle/discussions/2160) and decided to try using sign_update instead

**Comment by zorgiepoo** [comment]
CI Platforms like GitHub support adding tokens/secret keys/strings which is more aligned with the `-s` option. In this case you don't want a file to be left at rest somewhere or I guess ` <thing that outputs the key to stdout>` in this case.

**Comment by zorgiepoo** [comment]
#2168 for deprecation/removal consideration of command line flag.
