### ISSUE TITLE
German wording in Greek translation

### ISSUE THREAD

**Issue by aonez** [sparkle-project/Sparkle#2175]
Just reported by a user. I'm not good either or German or Greek, so here it goes.

The offending part is the last one: `Die derzeit installierte Version ist`

https://github.com/sparkle-project/Sparkle/blob/c33a416b53d06c52c9fc67f3924be855419141e2/Sparkle/el.lproj/Sparkle.strings#L5

**Comment by zorgiepoo** [comment]
I have no idea what's wrong about it when piping it through google translate 😄

Does the user have a suggestion what the string should be?

@core-code might have translated this.

**Comment by zorgiepoo** [comment]
Okay, google translate was actually misdirecting me.. This is definitely German, the Greek translation it's giving me is like

> Αυτήν τη στιγμή εκτελείτε την έκδοση %3$@.

So maybe see if that makes sense to a Greek speaking person..

**Comment by aonez** [comment]
I asked to the user that actually is translating Keka to Greek, so most probably he will do it. I'll (or he) pull it here.

**Comment by core-code** [comment]
i remember adding the support for letting the user know if he is running a *newer* version than what is in the appcast, which is what this string about. 

i don't remember adding any translations for the string though. and certainly not into greek, i don't speak it.

i can confirm that "Die derzeit installierte Version ist" is German for "You are currently running version", but what the proper Greek string should be, sorry, no clue...

**Comment by zorgiepoo** [comment]
> So maybe see if that makes sense to a Greek speaking person.. Either way, it will be better than the current translation.

Going to go with this translation for now, feel free to open a PR if it's wrong.
