### ISSUE TITLE
Crash: -[SUInstallerStatus probeStatusInfoWithReply:]

### ISSUE THREAD

**Issue by hdimessi** [sparkle-project/Sparkle#2176]
### Description of the problem
I had this seemingly "random" crash (did not happen on my machine), and I can't figure out where it stems from, I would really appreciate any pointers on where I should look.
```
EXC_BAD_ACCESS KERN_INVALID_ADDRESS
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x74b0 objc_retain + 16
1  Sparkle                        0x302d8 -[SUInstallerStatus probeStatusInfoWithReply:] + 60
2  Sparkle                        0x127f4 +[SPUProbeInstallStatus probeInstallerUpdateItemForHostBundleIdentifier:completion:] + 364
3  Sparkle                        0x1c81c __72-[SPUUpdater scheduleNextUpdateCheckFiringImmediately:usingCurrentDate:]_block_invoke + 236
4  Sparkle                        0x1c70c -[SPUUpdater scheduleNextUpdateCheckFiringImmediately:usingCurrentDate:] + 440
5  Sparkle                        0x1e498 __72-[SPUUpdater checkForUpdatesWithDriver:updateCheck:installerInProgress:]_block_invoke.348 + 232
6  Sparkle                        0x73e8 __86-[SPUBasicUpdateDriver abortUpdateAndShowNextUpdateImmediately:resumableUpdate:error:]_block_invoke + 100
7  libdispatch.dylib              0x2604 _dispatch_call_block_and_release + 32
```
### Do you use Sandboxing in your app?
No

### Version of `Sparkle.framework` in the latest version of your app
2.1.0

### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
N/A

### Steps to reproduce the behavior
No idea

**Comment by zorgiepoo** [comment]
Do you have the full crash log?

**Comment by zorgiepoo** [comment]
I have an idea of what's going on with potential fix in https://github.com/sparkle-project/Sparkle/pull/2178 however it would still be good to look at a full crash report with backtraces of other threads, register info, bad memory address accessed, etc.

Code is from 2016 so likely it's rare issue and not sure what order of events is happening here.
