### ISSUE TITLE
Update window goes haywire during resize when release notes are hidden

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#2200]
The update window goes haywire if you try to resize it when release notes are hidden, somehow. Any help on trying to debug this is welcome :).

Maybe we shouldn't even allow resizing? I don't know if that's a good idea.

**Comment by jzau** [comment]
I can see that the whole window moves up when resizing horizontally but vertical resizing is disabled.

**Comment by zorgiepoo** [comment]
I think resizing should be disabled anyway on second reflection. Zoom'ing the window (green button) expands the window horizontally in a kind of silly way.
