### ISSUE TITLE
Add option to automatically download/install new updates in permission prompt

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#2209]
From discussion #2208, in the permission prompt I think we should consider adding a checkbox option that reflects `SUAutomaticallyUpdate` / `-setAutomaticallyDownloadsUpdates:` (i.e, an option to automatically download/install new updates).

Current permission prompt:
<img width="549" alt="Screen Shot 2022-07-18 at 9 03 05 PM" src="https://user-images.githubusercontent.com/857267/179662199-5b156852-1c24-43af-b89c-d78df35757e6.png">

**Comment by core-code** [comment]
does this also mean re-adding the checkbox from Sparkle 1.x? or is there already some way to get that one back?
<img width="614" alt="Screenshot 2022-08-29 at 21 10 19" src="https://user-images.githubusercontent.com/1261954/187279392-ec76ed3e-a24c-449d-a9b5-3057d31f948c.png">

**Comment by zorgiepoo** [comment]
That shouldn't have changed. This is for the permission prompt. That checkbox on the update prompt window in particular may not show up when automaticallyChecksForUpdates is NO or when SUAllowsAutomaticUpdates is NO (I think, or something like that, not looking at the code/docs at the moment, off top of my head)

**Comment by core-code** [comment]
> That shouldn't have changed

i just can't confirm that. the button was there with Sparkle 1.x and its gone in Sparkle 2.x - nothing was changed except upgrading the framework.

looking at the source code i can't see how it would work either:

`        _allowsAutomaticUpdates = updaterSettings.allowsAutomaticUpdates && updaterSettings.automaticallyChecksForUpdates && !item.informationOnlyUpdate;
`

so the button is only there if the user has already checked the button (huh!?) or if `SUAllowsAutomaticUpdatesKey` is true. but we don't want to set SUAllowsAutomaticUpdatesKey to true, since automatic updates should be off by default and only on if the user activated it himself. but the user can't that without seeing the button. chicken and egg :-)

i changed the line to 

`        _allowsAutomaticUpdates = (updaterSettings.allowsAutomaticUpdates || updaterSettings.automaticallyChecksForUpdates) && !item.informationOnlyUpdate;
`

which seems to work fine for me.

**Comment by zorgiepoo** [comment]
A little misunderstanding I think but yes there's a potential issue.

`_allowsAutomaticUpdates` refers to allowing user to opt into automatic downloading/installing of updates.
`automaticallyChecksForUpdates` refers to Sparkle's automatic checking of new updates, which you seem to not use and have set to NO (?)
`SUAllowsAutomaticUpdatesKey` defaults to `true`. It's for developers that want to set it to `false` that want to not provide the user the option to automatically download/install updates.

If `automaticallyChecksForUpdates` is set to NO, Sparkle doesn't know the developer wants to schedule update checks themselves (not always the case, sometimes a user/developer may not want to schedule automatic update checks at all..). In this scenario, providing an option to automatically download/installing updates is a bit unsound because automatic checking is NO.

However this also breaks, which you may have found out, if the developer wants to disable Sparkle's scheduler and check for updates themselves automatically, and also provide the user the option to opt into allowing automatic installing/downloading of updates. I think this is your case but let me know if I'm wrong.

**Comment by core-code** [comment]
> and also provide the user the option to opt into allowing automatic installing/downloading of updates. I think this is your case but let me know if I'm wrong.

yes this is exactly my case. the one that used to work but doesn't anymore :-)

> automaticallyChecksForUpdates refers to Sparkle's automatic checking of new updates, which you seem to not use and have set to NO (?)

i can confirm that. its set to no because we schedule all update checks ourselves and don't want Sparkle to "ask users on second launch for permission if they want automatic update checks enabled"

**Comment by zorgiepoo** [comment]
Change on your end for that issue will be to set SUAllowsAutomaticUpdates to YES in Info.plist with https://github.com/sparkle-project/Sparkle/pull/2266

**Comment by core-code** [comment]
thanks! i'll try that, and hope it won't have any other consequences besides showing that checkbox :)

**Comment by zorgiepoo** [comment]
it's only for the UI to allow changing automatic downloading/installing updates setting and it's only used in the update alert for hiding/showing the control / managing some UI constraints.

**Comment by zorgiepoo** [comment]
Adding this change in #2285
