### ISSUE TITLE
Sparkle 1.27.1: [SUStatusController loadWindow]: Failed to load 'SUStatus'

### ISSUE THREAD

**Issue by QuangPeterNguyen** [sparkle-project/Sparkle#2225]
### Description of the problem
Sparkle 1.27.1: [SUStatusController loadWindow]: Failed to load 'SUStatus'

### Do you use Sandboxing in your app?
NO
### Version of `Sparkle.framework` in the latest version of your app
1.27.1
### Version of `Sparkle.framework` in the old version of app that your users have (or N/A)
1.20.0
### Sparkle's output from Console.app
```
[SUStatusController loadWindow]: Failed to load 'SUStatus'
```

### Steps to reproduce the behavior

[The more information provided and pasted verbatim, the easier it will be to diagnose an issue. If you can provide the affected application/binary and XML feed to reproduce an issue, share them]

**Comment by zorgiepoo** [comment]
Misconfiguration issue. Maybe files like SUStatus.nib are missing from the Sparkle framework you downloaded. No other sufficient information here.
