### ISSUE TITLE
update errors in 'Ventura' showing 'APPNAME (Autoupdate) is damaged and can't be opened'

### ISSUE THREAD

**Issue by core-code** [sparkle-project/Sparkle#2240]
our app is fully code-signed using a proper developer-id signature is also notarized

we've basically seen zero issues with Sparkle self-updates on 10.13 to 12

however we've got two reports from users on 'Ventura' where our app is unable to update itself with a message like this:

<img width="269" alt="Screenshot 2022-08-25 at 5 29 28 AM" src="https://user-images.githubusercontent.com/1261954/186721858-a4ce1b40-fcd5-4bd4-abbe-954674bfad99.png">

whats weird here is that the "damaged" dialoge usually refers to a missing or damaged code-signature. which should be impossible because our app definitely is proper signed. it must be some new Ventura bug?

we've been unable to reproduce the issue, but would like to start investigating this before 'Ventura' becomes more widespread.

we are still using Sparkle 1.27.0. is this a known issue which can be resolved by updating to a newer version of Sparkle?

thanks!

**Comment by zorgiepoo** [comment]
It may help to ask affected users to zip up and send you their copies of the app so you can examine if anything is indeed damaged/missing/deep verify the code signature etc. Also maybe ask them if they have any cleaner apps installed.

Ventura beta 6 was released within the last day or so. I'm guessing they're on beta 6? Maybe it's a new regression? Not otherwise a known issue as far as I'm aware.

**Comment by zorgiepoo** [comment]
Also worth mentioning Sparkle 1.x [copies this Autoupdate app](https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/SUBasicUpdateDriver.m#L645) to `~/Library/Caches/app-bundle-id/org.sparkle-project.Sparkle/app-name (Autoupdate).app` before trying to launch it.

**Comment by zorgiepoo** [comment]
So Ventura is [stricter about notarized apps being correctly signed](https://mjtsai.com/blog/2022/08/18/gatekeeper-changes-in-macos-ventura/) even if they are not quarantined.

Here's a little experiment:

1. Download an old version of an app that uses Sparkle
2. Launch the app. Quit the app.
3. Find Autoupdate.app in Sparkle.framework inside the app (in Sparkle 2 this is Updater.app)
4. Inside Autoupdate.app add a newline to one of the localization files. (Note a shallow codesign verify check of the main app bundle will still succeed, but a deep verify check will now fail).
5. Launch the main app again. Check for updates. Install the update.

On Ventura you will get the failure dialog that is reported here when trying to install an update. On Monterey, the update will still succeed to install.

For this issue, I think we should first rule out whether or not the apps failing to update have been modified in an invalid way.

**Comment by core-code** [comment]
thanks for the info.

the report was on earlier beta versions. and actually looking more carefully it seems both reports about this were submitted by the same user. so i'd say lets close this until there are more affected users (from our apps or from other vendors).

i'll forward your troubleshooting tips to the affected user if he sees is again. thanks again.

**Comment by core-code** [comment]
i'd kind of rule out the "binary was modified" theory, as our app refuses to start if it is not universal anymore (e.g. stripped by a so called "cleaner" ) or if the signature was replaced. also, it refuses to work if the checksum ain't right. 

in any case, no point digging deeper until we see this more often.
