### ISSUE TITLE
The update is improperly signed. -Developer ID-

### ISSUE THREAD

**Issue by modusCell** [sparkle-project/Sparkle#227]
Hi Guys,
With using Apple’s code signing tools, i have signed my app and exported from Xcode however still i am getting the warning when i try to upgrade my app with Sparkle framework. 
here is the my "appcast" XML file content. 

```
     <item>
        <title>Version 2.0 (2 bugs fixed; 3 new features)</title>
        <pubDate>Wed, 09 Jan 2006 19:20:11 +0000</pubDate>
        <enclosure url="http://192.168.1.64/sparkleTEST.zip" sparkle:version="2.0" length="1623481" type="application/octet-stream" />
     </item>
```

could you please review and advise what could cause the issue?
Many thanks.

**Comment by EggsBlue** [comment]
@richie5um Thanks for your reply, it is true that the original version is not correctly signed, although I do not know why
