### ISSUE TITLE
make release fails

### ISSUE THREAD

**Issue by zakarumych** [sparkle-project/Sparkle#2274]
## Summary

Build fails when doing `make release`.
Dependency package `swift-argument-parser v0.4.3` supports target versions starting from 10.13 and Sparkle default target version seems to be 10.11

## Possible Fix

Specify minimal version as 10.13
Or do something with `swift-argument-parser`

## Version

2.1.0

**Comment by zorgiepoo** [comment]
I only recently changed the Package file in #2245, and that change was targeted for 2.3 which already requires macOS 10.13 as minimum version. It's possible this could also happen if you're using Xcode 14 because Xcode 14 drops supporting deployment targets before 10.13 too.

**Comment by zakarumych** [comment]
So solution for my issue is updating to 2.3?

**Comment by zorgiepoo** [comment]
Yes, sure. Why not?

There are other things you can do if you want to use 2.1, like use Xcode 13.x (if the issue is with Xcode 14.x), use our precompiled binary distributions on our Github Releases page, bump the deployment target yourself in `ConfigCommon.xcconfig` before compiling, etc.

**Comment by zakarumych** [comment]
Thank you for suggestions

**Comment by zakarumych** [comment]
I tried updating to 2.3.0 and it crashes in tests.

<details>
  <summary>Crash report</summary>
  -------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               SparkleTest [4952]
Path:                  /Users/USER/*/SparkleTest.app/Contents/MacOS/SparkleTest
Identifier:            
Version:                (1.2.3)
Code Type:             ARM-64 (Native)
Parent Process:        Python [2673]
Responsible:           Terminal [41266]
User ID:               502

Date/Time:             2022-10-21 09:56:16.9719 +0300
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        63783844-5D27-3FF7-9049-0528A75F381F

Sleep/Wake UUID:       49088A88-F003-424F-BD9C-142E0BB63A59

Time Awake Since Boot: 250000 seconds
Time Since Wake:       218 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@rpath/Sparkle.framework/Versions/B/Sparkle'
Referenced from: '/Users/USER/*/SparkleTest.app/Contents/MacOS/SparkleTest'
Reason: tried: '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x1042b3e98 __abort_with_payload + 8
1   dyld                          	       0x1042bb024 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x1042bb058 abort_with_payload + 16
3   dyld                          	       0x104272a28 dyld4::halt(char const*) + 580
4   dyld                          	       0x10426dfb8 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3644
5   dyld                          	       0x10426d06c start + 488


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016bd56388   x3: 0x00000000000000f4
    x4: 0x000000016bd55f88   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x00000000000002e0
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x000000016bd55fde  x11: 0x0000000000000109
   x12: 0x0000000000000000  x13: 0x0000000000000034  x14: 0x000000025bdc9a93  x15: 0x0000000000000000
   x16: 0x0000000000000209  x17: 0x000000010426b14c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016bd55f88  x21: 0x00000000000000f4  x22: 0x000000016bd56388  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000016bd55f88  x26: 0x0000000000000400  x27: 0x0000000000000389
   x28: 0x0000000000000168   fp: 0x000000016bd55f50   lr: 0x00000001042bb024
    sp: 0x000000016bd55f10   pc: 0x00000001042b3e98 cpsr: 0x00001000
   far: 0x00000001041bc000  esr: 0x56000080  Address size fault

Binary Images:
       0x104268000 -        0x1042c7fff dyld (*) <38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 5
    thread_create: 0
    thread_set_state: 370

VM Region Summary:
ReadOnly portion of Libraries: Total=640K resident=0K(0%) swapped_out_or_unallocated=640K(100%)
Writable regions: Total=9216K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9216K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                              32K        2 
__DATA_CONST                       112K        2 
__LINKEDIT                         240K        2 
__TEXT                             400K        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                             65.8M       12 



-----------
Full Report
-----------

{"app_name":"SparkleTest","timestamp":"2022-10-21 09:56:17.00 +0300","app_version":"","slice_uuid":"8eed4fb3-1c13-344d-a7e8-4db74825d02a","build_version":"1.2.3","platform":1,"bundleID":"","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"263CB5FA-96BA-49E8-85B8-AAF48D8328C7","name":"SparkleTest"}
{
  "uptime" : 250000,
  "procLaunch" : "2022-10-21 09:56:16.7055 +0300",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro17,1",
  "procStartAbsTime" : 6190378623448,
  "coalitionID" : 31151,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2022-10-21 09:56:16.9719 +0300",
  "incident" : "263CB5FA-96BA-49E8-85B8-AAF48D8328C7",
  "bug_type" : "309",
  "pid" : 4952,
  "procExitAbsTime" : 6190384966163,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "SparkleTest",
  "procPath" : "\/Users\/USER\/*\/SparkleTest.app\/Contents\/MacOS\/SparkleTest",
  "bundleInfo" : {"CFBundleShortVersionString":"","CFBundleVersion":"1.2.3","CFBundleIdentifier":""},
  "storeInfo" : {"deviceIdentifierForVendor":"13498980-6E2B-5F6D-8F82-98B51D0E8B4F","thirdParty":true},
  "parentProc" : "Python",
  "parentPid" : 2673,
  "coalitionName" : "com.apple.Terminal",
  "crashReporterKey" : "63783844-5D27-3FF7-9049-0528A75F381F",
  "responsiblePid" : 41266,
  "responsibleProc" : "Terminal",
  "wakeTime" : 218,
  "sleepWakeUUID" : "49088A88-F003-424F-BD9C-142E0BB63A59",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '@rpath\/Sparkle.framework\/Versions\/B\/Sparkle'","Referenced from: '\/Users\/USER\/*\/SparkleTest.app\/Contents\/MacOS\/SparkleTest'","Reason: tried: '' (no such file), '' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":370,"task_for_pid":5},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":4371937,"threadState":{"x":[{"value":6},{"value":1},{"value":6104114056},{"value":244},{"value":6104113032},{"value":0},{"value":0},{"value":736},{"value":32},{"value":9},{"value":6104113118},{"value":265},{"value":0},{"value":52},{"value":10131118739},{"value":0},{"value":521},{"value":4364611916,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6104113032},{"value":244},{"value":6104114056},{"value":1},{"value":6},{"value":6104113032},{"value":1024},{"value":905},{"value":360}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4364939300},"cpsr":{"value":4096},"fp":{"value":6104112976},"sp":{"value":6104112912},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4364910232,"matchesCrashFrame":1},"far":{"value":4363894784}},"frames":[{"imageOffset":310936,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":340004,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":340056,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":43560,"symbol":"dyld4::halt(char const*)","symbolLocation":580,"imageIndex":0},{"imageOffset":24504,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3644,"imageIndex":0},{"imageOffset":20588,"symbol":"start","symbolLocation":488,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4364599296,
    "size" : 393216,
    "uuid" : "38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 7045087232,
  "size" : 3144744960,
  "uuid" : "049b583e-d4dc-3b2b-88da-e52d6e18313d"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=640K resident=0K(0%) swapped_out_or_unallocated=640K(100%)\nWritable regions: Total=9216K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9216K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                              32K        2 \n__DATA_CONST                       112K        2 \n__LINKEDIT                         240K        2 \n__TEXT                             400K        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                             65.8M       12 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000504
    },
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro17,1, BootROM 7459.141.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Mar 23 2022 19:57:59 version 18.60.27.0.7.8.129 FWID 01-570be953
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: USB2.0 Hub
USB Device: YubiKey FIDO+CCID
USB Device: USB-C Digital AV Multiport Adapter
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
  
</details>

**Comment by zorgiepoo** [comment]
That doesn't look like Sparkle's own tests.It looks like you aren't embedding the framework correctly. Our website documentation has instructions on including Sparkle.
