### ISSUE TITLE
Failed to execute pkg installer.

### ISSUE THREAD

**Issue by hstriepe** [sparkle-project/Sparkle#2276]
## Summary

With the latest version our existing project suddenly ends up with an error after download: "Failed to execute package installer."
The build scripts have not changed and we have used this approach tens of times. I reverted to the older Xcode but it does not make s difference. The same client app can update itself with the previous update by changing revs in plist.

Log entry:
`error	13:05:45.214517-0700	Autoupdate	Failed to perform final installation Error: Error Domain=SUSparkleErrorDomain Code=4005 "Failed to execute package installer." UserInfo={NSLocalizedDescription=Failed to execute package installer., NSUnderlyingError=0x600003144270 {Error Domain=SUSparkleErrorDomain Code=4001 "Failed to run authorization tool /Users/xxx/Library/Caches/com.heartmath.emwave/org.sparkle-project.Sparkle/emWave Pro (Autoupdate).app/Contents/MacOS/fileop (error code -60031)." UserInfo={NSLocalizedDescription=Failed to run authorization tool /Users/xxx/Library/Caches/com.heartmath.emwave/org.sparkle-project.Sparkle/emWave Pro (Autoupdate).app/Contents/MacOS/fileop (error code -60031).}}}
`
## Version

v2.1.0

**Comment by hstriepe** [comment]
The installer has been signed and notarized. Manually downloading it works like a charm.

**Comment by zorgiepoo** [comment]
Sparkle 2.1 is not the latest release, and these logs are indicating you are actually using Sparkle 1 (which uses fileop and is more unreliable). Retry with Sparkle 2.3.

**Comment by zorgiepoo** [comment]
Also technically it should still work with Sparkle 1.. Make sure your build scripts are actually copying Sparkle correctly, that all the executables inside are present, symlinks are present, etc.

**Comment by hstriepe** [comment]
Somebody on the team changed the payload name so it was not matching the app to be updated. Solved.
For some reason, the old Sparkle updater can only handle interactive installers on the newer versions of macOS.
We will be updating the system to bring it onto the present.
