### ISSUE TITLE
Strange sparkle error after calling new event loop

### ISSUE THREAD

**Issue by bdaush** [sparkle-project/Sparkle#2277]
We are developing a Qt-Project, that uses the sparkle framework for updates. With sparkle 2.2.1 we are running in a problem, when calling exec() after checking for available updates (checkForUpdatesInBackground) and getting an answer (updaterDidNotFindUpdate / didFindValidUpdate).
The Qt exec() starts a new eventloop, which causes a _dispatch_call_block_and_release from the os. 
After that, the following callstack is shown in xcode:
#4	0x0000000118dd0900 in __86-[SPUBasicUpdateDriver abortUpdateAndShowNextUpdateImmediately:resumableUpdate:error:]_block_invoke at /Users/runner/work/Sparkle/Sparkle/Sparkle/SPUBasicUpdateDriver.m:276
#3	0x0000000118de904c in __72-[SPUUpdater checkForUpdatesWithDriver:updateCheck:installerInProgress:]_block_invoke.352 at /Users/runner/work/Sparkle/Sparkle/Sparkle/SPUUpdater.m:758
#2	0x0000000118de8ca8 in __72-[SPUUpdater checkForUpdatesWithDriver:updateCheck:installerInProgress:]_block_invoke at /Users/runner/work/Sparkle/Sparkle/Sparkle/SPUUpdater.m:683
#1	0x0000000118e05b18 in -[SUUpdater updater:didAbortWithError:] at /Users/runner/work/Sparkle/Sparkle/Sparkle/SUUpdater.m:494

The error that is thrown is "SUSparkleErrorDomain" - code: 1001, but the NSLocalizedDescription is: 'Sie sind auf dem neuesten Stand!' (localized of 'You're up-to-date!').

We do not use sandboxing.

**Comment by zorgiepoo** [comment]
Is this a crash? Please copy/paste full details in verbatim as much as possible. It looks like details are missing here. Don't know what thread this is occurring on. If there is a full crash log generated that would be better.

> The error that is thrown is "SUSparkleErrorDomain" - code: 1001, but the NSLocalizedDescription is: 'Sie sind auf dem neuesten Stand!' (localized of 'You're up-to-date!').

This is a normal error result passed but it's not suppose to raise an issue but this bug report is vague in why it's showing the call stack.

Make sure any Sparkle API usage you are calling is done on the main thread and not a background thread.

**Comment by zorgiepoo** [comment]
> when calling exec() after checking for available updates (checkForUpdatesInBackground) and getting an answer (updaterDidNotFindUpdate / didFindValidUpdate)

I wonder if the check for updates is done too soon. Maybe you need to wait later. Sparkle normally schedules background checks itself on periodic interval and it will do it one runloop cycle later.

**Comment by zorgiepoo** [comment]
I didn't see anything strange locally in a sample/test Qt app I have for testing Sparkle. Otherwise this is insufficient information.
