### ISSUE TITLE
finish_installation.app for bundle doesn't work in 10.8 since it's quarantined

### ISSUE THREAD

**Issue by yllan** [sparkle-project/Sparkle#230]
I use Sparkle to update a bundle inside iPhoto.app.

It works on 10.7 but fails on 10.8. 
After some investigation, I found that it might be caused by the quarantined attribute. 

11/28/12 1:46:08.000 PM kernel[0]: exec of /Users/me/Library/Containers/com.apple.iPhoto/Data/Library/Application Support/Hypo/finish_installation.app/Contents/MacOS/finish_installation denied since it was quarantined by iPhoto and created without user consent, qtn-flags was 0x00000006

Although there is releaseFromQuarantine: method in Sparkle's code, it did not lift the quarantine attribute successfully. errno=3.

Does that means we cannot update bundle in sandboxed 10.8 app?

**Comment by pornel** [comment]
That code has been refactored. Please reopen if it still happens.
