### ISSUE TITLE
quiet-automatic-update not working with Qt application

### ISSUE THREAD

**Issue by cdemel** [sparkle-project/Sparkle#232]
When I set the application to run in quiet mode, installWithToolAndRelaunch doesn't get called until an NSApplicationWillTerminateNotification happens. But I'm integrating Sparkle using the code from here:
http://el-tramo.be/blog/mixing-cocoa-and-qt/

and NSApplicationWillTerminateNotification doesn't seem to get sent. What's the best way to send this? Or should I tweak the Sparkle code to listen for something else?

**Comment by zorgiepoo** [comment]
Note Sparkle 2 doesn't need posting of `NSApplicationWillTerminateNotification` anymore. Please don't do this with Sparkle 2.
