### ISSUE TITLE
Show "Install on Quit" if update was downloaded and requires user authorization

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#2426]
Currently we only show "Install on Quit" if the update was downloaded and does not require user authorization (so installation already started). We could also show "Install on Quit" if update was only downloaded and let the user authorize. We may either need to tell the update driver to not send user driver events, or hide UI from the standard user driver in such a case. Not sure which one is better, may be leaning towards latter. I'll exclude this change for package-based updates.

**Comment by george-continua** [comment]
In the case of my app (iTerm2) users often do not quit until it's time to reboot the machine, which is an awful time to install an update. "Install on Next Launch" would seem to be less obtrusive.
