### ISSUE TITLE
Sparkle crashes mysteriously when updating a multi-Gigabyte application.

### ISSUE THREAD

**Issue by SevenBits** [sparkle-project/Sparkle#245]
No error messages, nothing. Oddly this happens in release configuration only, so I don't get the luxury of the Xcode debugger to find out what the problem is.

**Comment by kainjow** [comment]
This is old now and should probably be closed unless it's reproducible.

I'd suggest for next time:
- Post which version/commit you're using
- Post the crash report
- Attempt to symbolize the crash report to get a basic stack trace

**Comment by pornel** [comment]
Yup. Hopefully changes we've made in the meantime have improved the situation.
