### ISSUE TITLE
Time for some spring cleaning? Version 2.0?

### ISSUE THREAD

**Issue by samdeane** [sparkle-project/Sparkle#248]
I'm not very familiar with the code, but from what I've seen, it looks like it could do with a little spring-cleaning, as the inevitable result of developing over a number of years whilst maintaining full backwards compatibility.

I'd like to see a version of the source code that is 64-bit, modern runtime, sandboxing friendly (and as a result of all of this, 10.7+ only):

Seems to me that adding sandbox support might be an opportunity to perform this more radical cleanup. For one thing, sandboxing (and code signing) naturally makes some things obsolete. For another thing, without a clean break, sandboxing is going to introduce parallel code paths into an already fairly complicated picture. This is going to do nothing to help with long-term maintainability.

I'd suggest:

- remove old #ifdef'd code supporting earlier systems
- remove everything but code signing as a way of verifying the download
- remove dmg archive support since it won't work for sandboxed apps
- assume the modern runtime, and use automatically synthesized ivars
- adopt the modern syntax for enumeration, collections, etc
- remove any other obsolete code / ui
- use NSURL instead of NSString where appropriate
- not sure, but possibly... ARC

On a related note, although not strictly code changes:
- clear up the folder structure for the project, move code and localised resources into subdirectories
- document the design :) (maybe this is somewhere already and I've missed it)

**Comment by pornel** [comment]
We've done most of that spring cleaning.

**Comment by samdeane** [comment]
Awesome...
