### ISSUE TITLE
Download-less updates not working

### ISSUE THREAD

**Issue by billymeltdown** [sparkle-project/Sparkle#249]
In Issue #227 Andy was kind enough to point out that if one just wants to provide the update notice so the user can download and install the update herself (a "download-less" update) (e.g. you're a sandboxed app that can't do the install step for the user), you can modify the appcast `item` entry such that you remove the enclosure, and instead provide `<sparkle:version>version.number</sparkle:version>`, and Sparkle should present the user with the update notice, sans "Install and Relaunch" capability. Unless I misunderstood. 

I can't seem to get this to work, nor find any mention of it in past issues, or in the wiki. Here's what I initially tried:

```
<item>
  <title>Version 1.2.4</title>
  <sparkle:releaseNotesLink>http://foo.bar/release_notes_test.html</sparkle:releaseNotesLink>
  <pubDate>Mon, 28 Jan 2013 14:30:00 +0500</pubDate>
  <sparkle:version>1.2.4</sparkle:version>
</item>
```

When version 1.2.3 looks at this appcast file using Sparkle, it reports, "you're up to date!" (paraphrasing) I thought maybe I had the tag wrong or misunderstood, so I tried some variants:

```
<item>
  <title>Version 1.2.4</title>
  <sparkle:releaseNotesLink>http://foo.bar/release_notes_test.html</sparkle:releaseNotesLink>
  <pubDate>Mon, 28 Jan 2013 14:30:00 +0500</pubDate>
  <sparkle:version>1.2.4</sparkle:version>
  <sparkle:versionString>1.2.4</sparkle:versionString>
  <sparkle:shortVersionString>1.2.4</sparkle:shortVersionString>
</item>
```

Then I noticed that if I put the enclosure tag back in, an update would be detected—so it looks like that without the `<enclosure>` tag, Sparkle will not detect your update : (  I did try using an `<enclosure>` that had the version number and no url, but the same scenario occurs—Sparkle reports there is no update:

```
<item>
  <title>Version 1.2.4</title>
  <sparkle:releaseNotesLink>http://foo.bar/release_notes_test.html</sparkle:releaseNotesLink>
  <pubDate>Mon, 28 Jan 2013 14:30:00 +0500</pubDate>
  <sparkle:version>1.2.4</sparkle:version>
  <sparkle:versionString>1.2.4</sparkle:versionString>
  <sparkle:shortVersionString>1.2.4</sparkle:shortVersionString>
  <enclosure sparkle:version="1.3.0 beta 4" sparkle:shortVersionString="1.3.0b4" />
</item>
```

I can't seem to get this to work, and I've tried combing through the code to figure out why—it seems to only work if I provide an enclosure with a url attribute. In SUAppcastItem's initWithDictionary:failureReason:, it looks like enclosure and item have been flattened, so sparkle:version should have been captured, but no update is produced for me, I only get "your version is up to date!" I'm going to try stepping through with a debugger next—none of the SULog messages in the code seem to be output in the lib's Debug build configuration—is there a special flag for enabling this facility? I haven't located it just yet.

If this is an obvious/simple problem, I apologize in advance, but it would be good to have an authoritative explanation of how to do this somewhere. If anybody knows, much obliged!

**Comment by iacas** [comment]
Unfortunately, this does not seem to work. I have copied (and modified to have a later version # than my existing application) and I get the same behavior as in the OP: users are told they're up to date and are not taken to a web page.

**Comment by MattyAyOh** [comment]
I had the same problem, got it fixed.
Had to **also** put in the <sparkle:shortVersionString> tag in as well

```
    <item>
       <title>Version $SHORT_VERSION</title>
       <sparkle:releaseNotesLink xml:lang="en">${RELEASENOTES_URL}</sparkle:releaseNotesLink>
       <sparkle:releaseNotesLink xml:lang="de">${RELEASENOTES_URL}</sparkle:releaseNotesLink>
       <pubDate>$PUBDATE</pubDate>

       <sparkle:version>80433</sparkle:version>
       <sparkle:shortVersionString>1.2.4</sparkle:shortVersionString>
       <link xml:lang="en">$EN_REDIRECT_URL_HERE!</link>
       <link xml:lang="de">$DE_REDIRECT_URL_HERE!</link>
      <sparkle:minimumSystemVersion>$MINIMUM_SYSTEM_VERSION</sparkle:minimumSystemVersion>
    </item>
```

This was tested and verified to work on our application.  I think the documentation: https://sparkle-project.org/documentation/publishing/ ("Downloading from a Web Site") should just be updated to note that you must include the shortVersionString, and this issue can be closed
