### ISSUE TITLE
Xcode building problem

### ISSUE THREAD

**Issue by lanamelach** [sparkle-project/Sparkle#251]
Hello, I am trying to implement the automatic updater for my C++ application by means of Sparkle framework. I've downloaded  Sparkle 1.5 b6, added the framework to the xcode project, also added copy files build step to copy the framework to the bundle. When I try to build it, it fails with the following errors:

cp: /Users/<username>/Documents/projects/MyProject/01/MyProject/MyProject/DerivedData/MyProject/Build/Products/Debug/MyProject.app/Contents/Frameworks/Sparkle.framework/Resources/fr.lproj/fr.lproj: No such file or directory
cp: /Users/<username>/Documents/projects/MyProject/01/MyProject/MyProject/DerivedData/MyProject/Build/Products/Debug/MyProject.app/Contents/Frameworks/Sparkle.framework/Resources/fr_CA.lproj: No such file or directory
cp: /Users/<username>/Documents/projects/MyProject/01/MyProject/MyProject/DerivedData/MyProject/Build/Products/Debug/MyProject.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr.lproj/fr.lproj: No such file or directory
cp: /Users/<username>/Documents/projects/MyProject/01/MyProject/MyProject/DerivedData/MyProject/Build/Products/Debug/MyProject.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr_CA.lproj: No such file or directory
cp: /Users/<username>/Documents/projects/MyProject/01/MyProject/MyProject/DerivedData/MyProject/Build/Products/Debug/MyProject.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr.lproj/fr.lproj: No such file or directory
cp: /Users/<username>/Documents/projects/MyProject/01/MyProject/MyProject/DerivedData/MyProject/Build/Products/Debug/MyProject.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/fr_CA.lproj: No such file or directory

What am I doing wrong?

**Comment by pornel** [comment]
Please reopen if it's still a problem with 1.9.
