### ISSUE TITLE
Release note style doesn't update on light/dark appearance change

### ISSUE THREAD

**Issue by kdrag0n** [sparkle-project/Sparkle#2581]
## Summary

A light/dark release notes stylesheet is selected when the updater windows is opened, but not updated when the system light/dark theme later changes (e.g. due to sunset/sunrise-based theming): (https://github.com/orbstack/orbstack/issues/1264)

![image](https://github.com/sparkle-project/Sparkle/assets/7930239/970325df-0f8e-408f-b9b6-0ac5c867b7f9)

## Possible Fix

Update stylesheet on `viewDidChangeEffectiveAppearance`.

## Version

2.4.2

**Comment by zorgiepoo** [comment]
Please try the latest release (2.6.3 currently). See also #2542.

**Comment by kdrag0n** [comment]
Ah sorry, I did a quick search for `viewDidChangeEffectiveAppearance` and didn't find anything. v2.6.3 works fine.
