### ISSUE TITLE
generate_appcast uses up a lot of RAM

### ISSUE THREAD

**Issue by latenitefilms** [sparkle-project/Sparkle#2620]
Maybe related to #1719 - but when I run `generate_appcast` it uses up a LOT of RAM.

I'm currently using this in my build script:

```bash
"$BINARY_FILES_PATH/generate_appcast" --maximum-versions 0 --download-url-prefix "$DOWNLOAD_URL_PREFIX" --release-notes-url-prefix "$FULL_RELEASE_NOTES_URL" --full-release-notes-url "$FULL_RELEASE_NOTES_URL" --link "$WEBSITE" -o "$APPCAST_PATH" "$SPARKLE_FOLDER_PATH"
```

My Sparkle folder is about **45.22GB**. Each release is about **1.45GB**.

Any ideas?

![image](https://github.com/user-attachments/assets/8290c128-35d7-4a86-bebf-4608f4b2678f)

![image](https://github.com/user-attachments/assets/10424057-6d95-4413-ae0e-a891b0d7c286)

**Comment by zorgiepoo** [comment]
How many items are in your appcast? https://github.com/sparkle-project/Sparkle/issues/1719 is supposed to help prune/move aside old items so they don't grow indefinitely in there.

Which versions of generate_appcast are you using, and which versions of Sparkle is being used in your app updates?

What files are taking the largest amount of space in your generated app updates (of the 1.45GB)? Is your app large? Delta updates can take a significant amount of memory and time.

**Comment by zorgiepoo** [comment]
> How many items are in your appcast? https://github.com/sparkle-project/Sparkle/issues/1719 is supposed to help prune/move aside old items so they don't grow indefinitely in there.

`--maximum-versions 0` may override this and preserve all versions though. You can try not passing that.

**Comment by latenitefilms** [comment]
I have 31 builds, all around 1.45GB each. All builds are listed in my appcast.

I'm not actually sure how you tell what version of `generate_appcast` I'm using - the version should probably be added to the `--help`? But I'm pretty sure it's the latest - or at least within the last month. Will try making sure I'm using the latest.

Will try removing `--maximum-versions`.

```
  --maximum-versions <maximum-versions>
                          The maximum number of versions to preserve in the
                          generated appcast for each branch point (e.g. with a
                          different minimum OS requirement). If this value is
                          0, then all items in the appcast are preserved.
                          (default: 3)
```

**Comment by latenitefilms** [comment]
Confirmed, I was using `v2.6.4` of `generate_appcast`. Will try setting `--maximum-versions` back to 3.

Thank you!
