### ISSUE TITLE
Show progress for .DMG files

### ISSUE THREAD

**Issue by lanamelach** [sparkle-project/Sparkle#263]
I would like to avoid creating additional zip packages for the updater as long as I distribute my application in .DMG files. Sparkle seems to work fine with DMG, only it doesn't show the progress indicator. Is it possible to download DMG and still show the progress fill level?

**Comment by pornel** [comment]
This has been added in 1.16. The progress isn't fine grained, because we don't have detailed information from the underlying tools, but at least something is there.
