### ISSUE TITLE
Error: Private key not found in the argument. Please provide a valid key.

### ISSUE THREAD

**Issue by YoavGro** [sparkle-project/Sparkle#2670]
### Description of the problem

Using sparkle in Github actions, copied the private key to the secrets.
Using this to copy the private key to a file
```
  echo "$SPARKLE_PRIVATE_KEY" > sparkle_private_key
  echo -n "$SPARKLE_PRIVATE_KEY" > ./Sparkle/sparkle_private_key
```

And using this to update the appcast with a new item
```
      ./Sparkle/generate_appcast \
          --ed-key-file Sparkle/sparkle_private_key \
          --phased-rollout-interval 86400 \
          -o Sparkle/appcast.xml \
          artifacts/<appName>
```

Getting this error 
"Error: Private key not found in the argument. Please provide a valid key."

### Version of `Sparkle.framework` in the latest version of your app 
I'm currently using a hardcopy of the generate_appcast file from my latest build

### Sparkle's output from Console.app
```

```

### Steps to reproduce the behavior

[The more information provided and pasted verbatim, the easier it will be to diagnose an issue. If you can provide the affected application/binary and XML feed to reproduce an issue, share them]

**Comment by zorgiepoo** [comment]
generate_appcast doesn't think the key is a valid base64 encoded string. Please check the contents of the file.

The error message is a bit misleading which I suppose we can use this issue for improving.

If you can it's better to pass the key via standard input (this is taken from generate_appcast's help page for the `--ed-key-file` option):

```
echo "$SPARKLE_PRIVATE_KEY" | ./Sparkle/generate_appcast --ed-key-file - --phased-rollout-interval 86400 -o Sparkle/appcast.xml artifacts/<appName>
```

**Comment by YoavGro** [comment]
Do I need to base 64 encode the key in the secrets?

**Comment by zorgiepoo** [comment]
If you're getting the private key from exporting via `generate_keys -x` it should already be base64 encoded. I think the tools always deal with reading/storing a base64 encoded representation, so I would check the contents of the key..

**Comment by zorgiepoo** [comment]
Clarified error message better in #2675, nothing else actionable here otherwise.
