### ISSUE TITLE
How to localize the sparkle framework?

### ISSUE THREAD

**Issue by Fibonacci-Solucoes-Ageis** [sparkle-project/Sparkle#268]
I'm new to mac development and I don't know how to localize the sparkle dialogs to brazilian portuguese. I looked the files pt_BR.lproj, but i don't know how to configure.
What do i need to do?

**Comment by manishjain999** [comment]
I have the same question. How Do I get the Default Sparkle Strings in Spanish? I have included the latest framework in my SWIFT project.

**Comment by zorgiepoo** [comment]
The app project in question also needs to enable the localization for that project, to use localizations that Sparkle offers.
