### ISSUE TITLE
can't install and launch, got the extract error

### ISSUE THREAD

**Issue by redjersey** [sparkle-project/Sparkle#275]
I'm having some problem with sparkle. 

When I select "Check for updates..." it downloaded the zip file properly, however once I pressed the "Install and launch" I got the error message saying:

An error occurred while extracting the archive. Please try again later

I looked at my console and I got the following error:

2013-05-28 3:07:34.942 PM mdworker[2828]: zip importer encountered an error (2) scanning "/Users/myusername/Library/Application Support/MyApp/MyApp 1.2/MyApp-v1.1.zip".

I used the default mac program to zip the file.

**Comment by hp011235** [comment]
Did someone got any update on this? I am facing the same problem. The dmg extracts fine if I try it myself. But, if I try doing with Sparkle then it shows this error "Update Error!  An error occurred while extracting the archive. Please try again later."

**Comment by liaogang** [comment]
A had the some problem just minutes ago.    
 But I solved the problem with this step:  
* clean all old files  
* compression the app to a zip file and sign it again

**Comment by chess92** [comment]
what do you mean by clean the old files?
