### ISSUE TITLE
Release notes documentation?

### ISSUE THREAD

**Issue by JetForMe** [sparkle-project/Sparkle#299]
Where is it documented how release notes are presented? Do I need to provide complete HTML? It seemed sufficient to stick some bodyless markup in the file. But if I do want to provide full HTML (html and body tags), does that work?

**Comment by pornel** [comment]
We pass the string to the webview as-is, but we configure a default font in the webview. It'll be fine either way (`<html>` and `<body>` start and end tags are *optional* in HTML).
