### ISSUE TITLE
Add param to BinaryDelta tool to not delta certain files

### ISSUE THREAD

**Issue by abarnert** [sparkle-project/Sparkle#301]
It would be nice if the same binary delta file could be applied to multiple slightly different variations of the bundle.

For example, let's say you have 106 different variants of MyApp-1.2.3 out there that differ only in a line of text in Contents/Info-plist.strings and the corresponding code signature in Contents/_CodeSignature/CodeResources. It would be nice to not have to generate 106 different deltas (or to have to come up with some way to select the right delta based on the variant the user has).

It looks like the only thing that would be needed is to add a new parameter to `BinaryDelta`, like `--skip-delta=REGEXP`, and check each path against that pattern before calling `shouldSkipDeltaCompression`. Nothing has to be changed on the apply side, in `BinaryDelta` or in `Sparkle.framework`; the generated deltas will still be perfectly valid.

I'll play around with this on a fork and make sure it's as easy as I think it is.

**Comment by zorgiepoo** [comment]
Won't happen.
