### ISSUE TITLE
Either a bug or a feature: I put the wrong value in SUPublicDSAKeyFile and updates still worked

### ISSUE THREAD

**Issue by webcracy** [sparkle-project/Sparkle#305]
I realised I'd put the wrong value for the SUPublicDSAKeyFile in one of my projects and assumed I'd broken updates, because Sparkle would be unable to figure out the signatures (FWIW, I actually used the same URL as the appcast xml as the value).

But (thankfully!) updates still worked.

So, if this a bug, here's the report. If this a feature, I'd love to have it confirmed :)

Thanks for Sparkle, love it!

**Comment by pornel** [comment]
Sparkle deliberately allows change of DSA key if Code Signing matches.

**Comment by zorgiepoo** [comment]
Just for historical reference, this may have been a bug in Sparkle that should have been fixed in 1.11 (both DSA and apple's code signing need to be valid if present).
