### ISSUE TITLE
“Not now” behaviour is intrusive when the computer was left unattended

### ISSUE THREAD

**Issue by oscherler** [sparkle-project/Sparkle#316]
1. A software update prompt dialogue appears while I’m not at my desk;
2. Two days later I dismiss the prompt with “Not now”;
3. A new software update prompt appears immediately.

It means that the “Ask again later” delay calculation incorrectly uses the prompting date instead of the dismissing date to calculate the date of the next prompt.

**Comment by zorgiepoo** [comment]
This was resolved recently.
