### ISSUE TITLE
Updating Helper and Daemon

### ISSUE THREAD

**Issue by shallad** [sparkle-project/Sparkle#317]
My Mac application consists of a .app and a helper. I am also  having daemon running background. I would like to add auto update capabilities to all these components. Currently it is installed through pkg. Is there any way using sparkle or any other tool to auto update these components individually.

**Comment by Gayatri-N** [comment]
@kornelski :
I am also facing a similar issue.

We have a .pkg file which consists of a command line tool (runs as a root) and a cocoa app (runs in a user space). We have integrated Sparkle.framework in a cocoa app to update the .pkg file.
While updating the .pkg file, it always asks user for password. 

Does Sparkle supports non GUI application? (The reason being asked is, we are thinking to integrate Sparkle.framework in command line tool app)
Is there any way to update the .pkg file silently (i.e. without asking password)?

**Comment by kornelski** [comment]
We don't support non-GUI applications. We don't support pkg installations without asking for password.

You should put the command line tool in the app bundle in `.app/Contents/MacOS/` and if it has to be elsewhere, then copy or symlink it from the running app.
