### ISSUE TITLE
Sparkle logs: How to include logs for update process in Sparkle

### ISSUE THREAD

**Issue by ReddySanthosh** [sparkle-project/Sparkle#321]
I am using Sparkle framework in my Project for Autoupdate feature. Here my requirement is to include the logs for update process, i.e for update failure / update success, etc 

If the update fails for some reason, need to log the error description to a file for better debugging.

**Comment by mherrmann** [comment]
On recent macOS and Sparkle versions, Sparkle's logs can be watched from the command line via:

    log stream | grep -i sparkle
