### ISSUE TITLE
/tmp folder cleanup

### ISSUE THREAD

**Issue by scottsturges** [sparkle-project/Sparkle#333]
When I was updating Quickbooks at the office Thursday, I left during download (slow connection) and came back Monday and clicked the Install & Relaunch button. However since the /tmp folder had been cleaned automatically over the weekend, the application became corrupted.

I realize that this is a very specific circumstance, but possibly it would be good to include a timeout on the install window.

/etc/defaults/periodic.conf defines removing files 3 days after creation.

```
daily_clean_tmps_days="3"
```

**Comment by kolpanic** [comment]
Yeah, I've been digging into it a bit too. Our app is sandboxed, so the cache is in `~/Library/Containers/<container-id>/Data/Library/Caches/<container-id>/`. However, I got the app to the Install & Relaunch window and checked both there and in `$TMPDIR`, and there's no downloaded update.
