### ISSUE TITLE
Write test driver and test feeds

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#36]
_**Andy Matuschak (andymatuschak)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/229413) on' 2008-05-12:*

Sparkle is really rickety right now without any formal testing
procedures. Using the new driver framework, we should be able to
implement a driver that will perform a test installation and return
whether it was successful; we can then generate a number of test feeds,
spanning various appcast options and archive formats, to ensure that
everything's working as expected.

**Comment by pornel** [comment]
This is done
