### ISSUE TITLE
Change between update check progress and result windows is not smooth

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#365]
If you invoke "Check for updates" you see:
1. Checking for updates window with a progress bar
2. Progress window closes, focus momentarily switches to the host app
3. "(No) updates available" window pops up and gets focus

The step 2 causes a visual glitch.

iTunes has a very similar interface, but somehow they manage to jump from 1 to 3 without a glitch caused by window re-opening animation.

**Comment by zorgiepoo** [comment]
Not sure this is still an issue.
