### ISSUE TITLE
Replace CFPreferences code with NSUserDefaults

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#367]
In SUHost.m there's a fallback for NSUserDefaults and comments mention Tiger. We should check if that still applies, or whether half of that code can be deleted.

Related #366

**Comment by zorgiepoo** [comment]
It still applies if bundle ID is different than main bundle ID however NSUserDefaults with initWithSuiteName: can probably be used instead, which would need to be tested.
