### ISSUE TITLE
Layout does not collapse when release notes are hidden

### ISSUE THREAD

**Issue by pornel** [sparkle-project/Sparkle#369]
Views that are hidden still participate in autolayout, so hidden release notes just leave a massive gap in the window :(

![screen shot 2014-07-07 at 01 37 55](https://cloud.githubusercontent.com/assets/72159/3490513/0be21818-056f-11e4-897e-8fb486961078.png)

**Comment by soaurabh** [comment]
@pornel @ReddySanthosh , Is there any why i can use sparkle framework without editing it's code and still avoid this issue, any public reference to this window so that i can resize?
