### ISSUE TITLE
Ability to run Install.app without user interface

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#38]
_**Peter Speck (speck)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/272216) on' 2008-09-19:*

I would like to be able to run Installer.app without using the GUI but
simple running the command line version.

Using the GUI results in the Window-esque click-ok click-ok click-ok
sequence.

The proposed patch adds a delegate callback which enables the host app
to run the installation itself instead of calling the Installer.app.
Sparkle still does the rest of the process.

I need to use the Installer.app instead of simple download install to
have the stuff installed correctly.

**Comment by pornel** [comment]
This is done
