### ISSUE TITLE
Allow HTTPS with self-signed certificates if SUPublicDSAKeyFile provided

### ISSUE THREAD

**Issue by taoeffect** [sparkle-project/Sparkle#386]
Reviving [14](https://github.com/pornel/Sparkle-fork/issues/14) with the slight twist of allowing self-signed certs if `SUPublicDSAKeyFile` is provided.

This is just as secure as CA-signed certs. Only difference is that it doesn't require developers to shell out $$$ to CAs.

**Comment by pornel** [comment]
Is that still needed given we have Let's Encrypt, and also ATS restrictions?
