### ISSUE TITLE
Changed App name won't update?

### ISSUE THREAD

**Issue by zsszatmari** [sparkle-project/Sparkle#400]
Dear All,

I have a problem. I have an app, call itt Awesome.app. rename it 'Awesome update test.app'. Then I'd like to release a new version with different name 'Awe-some.app'. I zip it, update the updater xml, and get  

Sparkle Error (continued): Couldn't find an appropriate update in the downloaded package.

I don't really need it to be renamed for old users, but I'd like to see the update to work... 
If I rename the same new version bundle to Awesome.app, and zip it, the update works flawlessly.

So my question is, how do I have an 'appropriate update' in the downloaded package? I read that Sparkle can find the .app by bundle id (in the Info.plist), but it does not seem to be true, am I missing something?
Thank You for your help!

I am on Sparkle 1.5b6

**Comment by pornel** [comment]
Does #469 help here?

**Comment by zorgiepoo** [comment]
Tracking better app rename changes with #62 (although it's more for app bundles, not pkgs..)
