### ISSUE TITLE
setObjectForKey: object cannot be nil (key: teamid)

### ISSUE THREAD

**Issue by silentcloud** [sparkle-project/Sparkle#406]
**I get this message and my app crash, how can I fix it**

> **\* setObjectForKey: object cannot be nil (key: teamid)

0   CoreFoundation                      0x00007fff8b6cfbec __exceptionPreprocess + 172
    1   libobjc.A.dylib                     0x00007fff9180270e objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff8b5b7d26 -[__NSDictionaryM setObject:forKey:] + 1174
    3   Sparkle                             0x00000001000b343c +[SUCodeSigningVerifier logSigningInfoForCode:label:] + 366
    4   Sparkle                             0x00000001000b32a1 +[SUCodeSigningVerifier codeSignatureIsValidAtPath:error:] + 393
    5   Sparkle                             0x00000001000b10b6 -[SUBasicUpdateDriver validateUpdateDownloadedToPath:extractedToPath:DSASignature:publicDSAKey:] + 107
    6   Sparkle                             0x00000001000b157e -[SUBasicUpdateDriver installWithToolAndRelaunch:displayingUserInterface:] + 155
    7   Sparkle                             0x00000001000bb88b -[SUUIBasedUpdateDriver installWithToolAndRelaunch:] + 170
    8   libsystem_trace.dylib               0x00007fff8cf28bf7 _os_activity_initiate + 75
    9   AppKit                              0x00007fff8bfa5fa8 -[NSApplication sendAction:to:from:] + 410
    10  AppKit                              0x00007fff8bfa5dd0 -[NSControl sendAction:to:] + 86
    11  AppKit                              0x00007fff8c17717c __26-[NSCell _sendActionFrom:]_block_invoke + 131
    12  libsystem_trace.dylib               0x00007fff8cf28bf7 _os_activity_initiate + 75
    13  AppKit                              0x00007fff8bfee309 -[NSCell _sendActionFrom:] + 144
    14  AppKit                              0x00007fff8c15ed17 -[NSButtonCell _sendActionFrom:] + 39
    15  libsystem_trace.dylib               0x00007fff8cf28bf7 _os_activity_initiate + 75
    16  AppKit                              0x00007fff8c0089f1 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2453
    17  AppKit                              0x00007fff8c007d66 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 491
    18  AppKit                              0x00007fff8c007339 -[NSControl mouseDown:] + 714
    19  AppKit                              0x00007fff8c504ea7 -[NSWindow _reallySendEvent:] + 12827
    20  AppKit                              0x00007fff8bf8c334 -[NSWindow sendEvent:] + 368
    21  AppKit                              0x00007fff8bf3e0cc -[NSApplication sendEvent:] + 2148
    22  AppKit                              0x00007fff8bdcc6b8 -[NSApplication run] + 711
    23  AppKit                              0x00007fff8bdb7b2e NSApplicationMain + 1778
    24  GetTest                            0x0000000100005272 main + 34
    25  libdyld.dylib                       0x00007fff921885c9 start + 1

**Comment by BogatyrevM213** [comment]
@silentcloud @fernandomorgan How exactly I include my private key in the build? Where should I do that?

**Comment by kornelski** [comment]
Careful! You should *never ever* include your *private* key in the build. It's *private* and has to stay in a secret location on your machine, not shared with anyone!

Only the **public** part is supposed to be in the app.
