### ISSUE TITLE
Encourage the use of HTTPS for update URL amongst developers

### ISSUE THREAD

**Issue by prvcy** [sparkle-project/Sparkle#408]
With the recent revelations of the NSA conducting man in the middle binary replacement attacks, we should educate developers on this matter, since Sparkle is used by many in their applications. Most of these developers are checking for updates insecurely via HTTP. I understand the binary is signed, however to fully migrate these attacks, the best course of action is to enable TLS.

This issue is described here: https://firstlook.org/theintercept/2014/08/15/cat-video-hack/

And more technically here: https://citizenlab.org/2014/08/cat-video-and-the-death-of-clear-text/

**Comment by kainjow** [comment]
Apps built with 10.11 will require Info.plist exceptions to use http now, so I don't think Sparkle needs to go out of its way to do anything as Apple will enforce this.

**Comment by pornel** [comment]
Thanks, Apple.
