### ISSUE TITLE
Check For Updates is disabled for some users

### ISSUE THREAD

**Issue by crairdin** [sparkle-project/Sparkle#413]
I have Sparkle integrated into my app and it's working fine -- for most users. I have a very small number who claim that "Check For Updates" is always grayed out. The only way around this is for them to manually install the program from the last version they actually downloaded. Once they do that, Check For Updates works fine and they can get the latest version.

This doesn't seem to be something that happens to everyone, but rather there are certain people to whom it happens all the time. (Or, rather, it works for a while then becomes disabled -- after which point in time nothing they do re-enables it.)

I followed the instructions in the documentation to hook up the menu item. And again, it works great for most people. So I suspect it's not just a configuration problem on my part.

I didn't scour the source code (the reason I'm using Sparkle is precisely because I don't want to have to learn everything about how a program like this works!) but one thing I noticed is that it appears that the menu item will be disabled if the app is actively checking for an update. But these users aren't saying anything about an update being downloaded at the time.

Any suggestions? Thanks!

**Comment by zorgiepoo** [comment]
Likely resolved by #872
