### ISSUE TITLE
Problem with uBar

### ISSUE THREAD

**Issue by Etienne-Grosjean** [sparkle-project/Sparkle#418]
I have a problem with uBar (it quit after few seconds) and they told me it is due to sparkle. Here is a view of my console and one of their message. What I got to do? How to find out any software blocking network communication? I upgraded sparkle just in case. (Mac with 10.9.4)

"Ahh,

So it is the Sparkle Update framework crashing for some reason. That explains why it takes a few minutes.

Do you have any software blocking network communications? Sparkle is what the auto-update checking is based on.

Edward

On Aug 19, 2014, at 6:31 PM, Etienne Grosjean <etienne.grosjean@bell.net> wrote:

Here is the console log, if it may help. It is called "uBar-2014-08-19-163220-server.crash"

Process:         uBar [44618]
Path:            /Applications/uBar.app/Contents/MacOS/uBar
Identifier:      ca.brawer.uBar
Responsible:     uBar [44618]
5   uBar                                0x0000000109147ee7 uBar + 122599
6   uBar                                0x00000001091463b8 uBar + 115640
12  ca.brawer.uBar                	0x0000000109147ee7 0x10912a000 + 122599
13  ca.brawer.uBar                	0x00000001091463b8 0x10912a000 + 115640
       0x10912a000 -        0x109158ff7 +ca.brawer.uBar (2.1.8 - 218) <158422E7-EF6F-3956-A9C1-C19B39FEEE8E> /Applications/uBar.app/Contents/MacOS/uBar
       0x109179000 -        0x10919cff7 +org.andymatuschak.Sparkle (1.7.0 - 07a6893) <E3DE233C-2222-3570-B3CF-6072F6A914C5> /Applications/uBar.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
 

Etienne Grosjean
etienne.grosjean@bell.net"

**Comment by pornel** [comment]
Feel free to reopen if you get a response.
