### ISSUE TITLE
"image not found" when building from head

### ISSUE THREAD

**Issue by gnachman** [sparkle-project/Sparkle#420]
I'm trying to upgrade to the latest Sparkle, but I get this error when I try to run my program:

dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/gnachman/SparkleTest/Build/Debug/SparkleTest.app/Contents/MacOS/SparkleTest
  Reason: image not found

Steps to reproduce:
1. Build the Release version of the Distribution target of Sparkle
2. Create a new Xcode project. Select Cocoa Application.
3. Unzip the Sparkle bz2 in the new project's folder
4. Rick click on Frameworks, select Add files
5. Select Sparkle.framework
6. Build and run

I also tried adding Sparkle.framework to the Copy Bundle Resources phase, as well as adding a new Copy Files phase with the Frameworks destination.

Sparkle 1.5b did not use @rpath. otool -L on a binary linked with 1.5b shows:
    @loader_path/../Frameworks/Sparkle.framework/Versions/A/Sparkle (compatibility version 1.5.0, current version 1.5.0)

while otool -L on a program linked with the latest shows:

```
@rpath/Sparkle.framework/Versions/A/Sparkle (compatibility version 1.6.0, current version 1.8.0)
```

I'm not sure where the @rpath is coming from, but that seems to be problematic.

**Comment by besi** [comment]
I had that problem too. Then I checked out another branch in Git, checked out the original branch again, built the project and the problem was gone.

Very Weird. I agree with @pornel that this is a bit weird in therms of reproducibility.

**Comment by ConfusedVorlon** [comment]
I'm hitting this problem now with the podspec for 1.10

I can fix it by following the instruction (not in the cocoapods instructions) to add

 In Build Settings tab set “Other Linker Flags” to -Wl,-rpath,@loader_path/../Frameworks.

I'm guessing the podspec should be handling this, but if not, then the documentation should list the step.

**Comment by sanfords** [comment]
1. You can use otool -L Sparkle (inside the framework bundle) to see what the framework's path is.
2. You can change to @rpath to @executable_path/../Frameworks in xcconfig.
Then your framework can live in /Frameworks in your app bundle.  In this case be sure:
  a. Build Phases -> Link Binary with Libraries and the Copy Files Frameworks areas are set up.
  b. You may have to add the path to the framework to your Framework Search Paths in build settings.
This above worked for me for upgrading today.  Don't know what will happen tomorrow.  ;-)

**Comment by jakepetroules** [comment]
> <strike>You can change to @rpath to @executable_path/../Frameworks in xcconfig.</strike>

Do not do that. The correct solution is to set

    LD_RUNPATH_SEARCH_PATHS = @loader_path/../Frameworks

in your app's build settings (which adds `-Wl,-rpath,@loader_path/../Frameworks` to your app's Other Linker Flags) as suggested above. You should not change Sparkle.

**Comment by sanfords** [comment]
Will that affect the other frameworks I'm linking?

**Comment by jakepetroules** [comment]
Obviously, but that's how you should be linking *all* frameworks, not just Sparkle.

**Comment by sanfords** [comment]
I understand @rpath is the new and shiny toy.  But your recommendation dismisses backwards compatibility with complex source bases.  The reality of budgets and schedules sometimes demand something else.  I have no problem with @rpath where the former do not interfere.  :-)

**Comment by jakepetroules** [comment]
@rpath isn't new, it's been part of macOS since 2007. I don't expect you to have any problems.
