### ISSUE TITLE
How to avoid repeating updates of the same release?

### ISSUE THREAD

**Issue by wurzer** [sparkle-project/Sparkle#422]
Beta testers of our apps have reported, that Sparkle is providing the same update again and again. Maybe I have created a wrong app cast file:
- The documentation says, that the app must have the same name. Is it also true for the zip file?
- The documentation doesn’t specify the xml attribute „length“. Is it the size of the app or the zip file?
- Do I have to remove the previous items in the app cast, if i publish a new release? 
- I use code signing, but add the dsaSignature, because of a thread in this forum. Is that correct?
- I use release numbers with three digits like 1.1.9. Is that possible? Or do I have to use only two digits?

Thanks for your help.

**Comment by aleclarson** [comment]
https://github.com/sparkle-project/Sparkle/issues/422#issuecomment-55598932

These tips would be useful in the docs.

Also, if I append commit SHAs to beta versions (eg: `1.0.0-eb34ac1`), will Sparkle use the publish date to determine the next update, or will it incorrectly sort them instead?

**Comment by kornelski** [comment]
Sparkle doesn't support git versions (it can't, they can't be compared without access to the repository), so it's likely to do something undesirable in that case. Use sortable versions, e.g. build numbers in the way recommended by Apple.

**Comment by aleclarson** [comment]
No problem, I've added it myself in this commit: https://github.com/aleclarson/sparkle/commit/21c581dd4df56dd6bf12311667aff8543547fe13

It falls back to comparing publication dates when versions are equal apart from their commit SHAs.

**Comment by kornelski** [comment]
That's a nifty change. Could you make a pull request for it?
