### ISSUE TITLE
[SUHost appSupportPath] should support bundle-id-named app support dir

### ISSUE THREAD

**Issue by jlj** [sparkle-project/Sparkle#424]
The return value of `-[SUHost appSupportPath]`  is based on the bundle name, returning something like `/Users/user-name/Library/Application Support/MyApp/.Sparkle`.

While this is OK for many apps out there, this is not inline with Apple naming recommendations (e.g. in https://developer.apple.com/library/mac/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html) that say:

> Application Support [...] All content in this directory should be placed in a custom subdirectory whose name is that of your app’s bundle identifier or your company.

**The result**, for an application complying with the recommendation above and using Sparkle, is to have at the end two app support directories for the same application - `.../Application Support/MyApp` and `.../Application Support/com.mycompagny.MyApp`, which can be really confusing for the end user.

**The solution** could be to add a new SUUpdaterDelegate method `-(NSString*)applicationSupportDirNameForUpdater:(SUUpdater *)updater;`. If this method is implemented, the application support dir name could be passed to the SUHost initializer; otherwise SUHost will return the same appSupportPath as it does today.

**Comment by pornel** [comment]
Fixed in #442
