### ISSUE TITLE
Idea: add JSON as an alternative update file format

### ISSUE THREAD

**Issue by kainjow** [sparkle-project/Sparkle#427]
I've never been a fan of using RSS/XML for the update file, it always seemed way too verbose to me. I can never remember the exact XML layout either. I guess the one use is people can subscribe to them in their RSS feeders, but does anyone do that?

I'm not sure which parts of the RSS feed Sparkle actually uses, but it seems the basics would be minimum. Here's an example:

```
[
  {
    "releasenotes": "http://...",
    "url": "http://...",
    "version": "102",
    "shortVersion": "1.0.2",
    "dsaSignature": "MC0F..."
  },
  {
    "releasenotes": "http://...",
    "url": "http://...",
    "version": "101",
    "shortVersion": "1.0.1",
    "dsaSignature": "MC0F..."
  }
]
```

NSJSONSerialization is part of 10.7 so no third-party code would be required.

**Comment by pornel** [comment]
Sparkle 1.16 comes with a tool to generate appcast automatically from files on disk. Hopefully with it there are fewer reasons to touch XML at all, so it won't bother you that much :)

**Comment by kainjow** [comment]
https://jsonfeed.org/2017/05/17/announcing_json_feed :)
