### ISSUE TITLE
Controlling when to launch the Installer pkg

### ISSUE THREAD

**Issue by vikasyv** [sparkle-project/Sparkle#428]
Hi 

 We are using Sparkle with an Installer pkg in our application with silent downloads. If an update is available, after downloading, the package is launched when we quit the application. Is it possible to control this behavior in such a way that the Pkg installer is launched on the next launch of the app rather than at the time of quitting? Please let me know if an API is present.

If there is no API method for this, In Sparkle Codebase, can you point me towards the code which I need to look for changing this? I was looking at Autoupdate.m file in the functions parenthasquit, install and relaunch and was playing around with them a bit but could not get this to work correctly. Appreciate your help on this.

Thanks and Regards
Vikas

**Comment by pornel** [comment]
I've merged a pull request for silent launch of the installer (without UI). Does that help?
