### ISSUE TITLE
Codesigning Sparkle Framework for Mac OS 10.9.5 and later

### ISSUE THREAD

**Issue by vikasyv** [sparkle-project/Sparkle#433]
Hi,

 I am including Sparkle Framework in my app.During signing of the app using V2 signature, I need to sign the Sparkle Framework as well. I am using the following command to sign Sparkle Framework. 
codesign --verbose --force --sign "Developer ID Application: Company Name" AppName.app/Contents/Frameworks/Sparkle.framework/Versions/A

When I verify the signature, it looks fine and valid. However, when I download the app from a web server and double click on the first time, I am getting an "Unidentified Developer" Message on Mac 10.9.5. On checking the  code sign details, I see the error:
"bundle format is ambiguous (could be app or framework) In Subcomponent: <Path to Sparkle.Framework"

On previous versions of Mac OS, it is mostly fine though the error has appeared in a couple of instances.

Has anybody else faced this problem? Please let me know what all I need to sign for Sparkle framework to get rid of this error.

Thanks 
Vikas

**Comment by cazoobi** [comment]
I had this problem randomly and it turned out that moving my project around from machine to machine via USB caused a corruption in the Sparkle framework at some point. 

My simple fix was to delete the framework from the project folder and simply paste it back in. After that it all worked fine with regard to downloading from a server. I must stress, delete the original framework file first, it took me about an hour to figure this out as pasting it in over the original didn't seem to work I've no idea why!

**Comment by ManiaChamp** [comment]
When I am trying to archive my application ,It shows me Developer ID can't be confirmed. After removing sparkle its woking fine. Is any body can tell there is specifically we need to sign sparkle framework because in Xcode it automatically sign on copy.

**Comment by pornel** [comment]
You don't need to manually codesign Sparkle if Xcode correctly signs it on copy (with Xcode I find it's a lottery though, so I have a post-build script that checks signatures and re-signs everything if Xcode screwed it up).

**Comment by ManiaChamp** [comment]
Can you please tell me the script?

**Comment by ManiaChamp** [comment]
Can you please tell me the procedure how to sign it manually too . If possible ,It will be great help.

**Comment by pornel** [comment]
@ManiaChamp it's in [ImageOptim's](https://github.com/pornel/ImageOptim) project file.

**Comment by btjones** [comment]
@ManiaChamp here is how I codesign Sparkle from a shell script.

```
# grab code signing id from the keychain
codeSignID=$(security find-identity -v -p codesigning | grep ".*Developer ID Application: MyCompany.*")

# codesign all frameworks including sparkle
codesign --verbose --force --sign "$codeSignID" "/absolute_path/MyApp.app/Contents/Frameworks/Sparkle.framework"

# codesign app executable and app itself
codesign --verbose --force --sign "$codeSignID" "/absolute_path/MyApp.app/Contents/MacOS/MyAppExecutable"
codesign --verbose --force --sign "$codeSignID" "/absolute_path/MyApp.app"
```
