### ISSUE TITLE
Sparkle 1.9

### ISSUE THREAD

**Issue by grouchal** [sparkle-project/Sparkle#435]
I can see that there are currently 4 issues setup for 1.9.

Is this list complete or are there other things planned?

One of the issues related to sandboxed apps I would dearly love to see in a stable released version of Sparkle so I am keen to know when 1.9 might be completed.

As ever I am happy to help with this - but not sure how best to contribute.

**Comment by pornel** [comment]
Sigh, the proper sandboxing has turned out to be really hard. I guess it was a mistake to promise it for a specific version. I'll try to release current master, as it already has lots of good fixes.

**Comment by tonyarnold** [comment]
Any chance #446 can be included in this release?

**Comment by pornel** [comment]
I've merged #446.

@jakepetroules @MaddTheSane OK to make a release?

**Comment by MaddTheSane** [comment]
Everything looks good to me.

**Comment by jakepetroules** [comment]
:+1:

**Comment by pornel** [comment]
I've uploaded the build, give it a try:

https://github.com/sparkle-project/Sparkle/releases/tag/1.9.0rc1

**Comment by grahammiln** [comment]
Any plan to merge #377?

**Comment by pornel** [comment]
@grahammiln That's a super useful feature, but 1.9 is overdue. I'll merge that for the next release.
