### ISSUE TITLE
Many “Unable to quarantine: 93” messages

### ISSUE THREAD

**Issue by codecaffeine** [sparkle-project/Sparkle#452]
I have a FooBar.app. When I autoupdate, I get a bunch of messages saying `Unable to quarantine: 93`. Is this anything I should be concerned about? This is occurring on OS X Yosemite with the latest 1.8.0 release from CocoaPods.

```
11/7/14 5:38:50.294 PM FooBar[13648]: Sparkle: ===== FooBar.app =====
11/7/14 5:38:50.823 PM FooBar[13648]: updater:0x608000240420 didFinishLoadingAppcast:<SUAppcast: 0x61000065a670>
11/7/14 5:38:50.824 PM FooBar[13648]: New Update Found: 1.8.8.1.9. Installing…
11/7/14 5:38:52.409 PM FooBar[13648]: Sparkle: Extracting /Users/matt/Library/Application Support/FooBar/.Sparkle/FooBar 1.8.8.1.9/FooBar.1.8.8.1.9.app.zip using 'ditto -x -k - "$DESTINATION"'
11/7/14 5:38:52.560 PM FooBar[13648]: updater:0x608000240420 willInstallUpdateOnQuit:<SUAppcastItem: 0x6080004c4ad0> immediateInstallationInvocation:<NSInvocation: 0x610000663f80>
11/7/14 5:38:52.562 PM FooBar[13648]: updater:0x608000240420 didCancelInstallUpdateOnQuit:<SUAppcastItem: 0x6080004c4ad0>
11/7/14 5:38:52.656 PM FooBar[13648]: updaterShouldRelaunchApplication:0x608000240420
11/7/14 5:38:52.657 PM FooBar[13648]: updater:0x608000240420 shouldPostponeRelaunchForUpdate:<SUAppcastItem: 0x6080004c4ad0> untilInvoking:<NSInvocation: 0x600000469600>
11/7/14 5:38:52.658 PM FooBar[13648]: updater:0x608000240420 willInstallUpdate:<SUAppcastItem: 0x6080004c4ad0>
11/7/14 5:38:52.000 PM kernel[0]: FooBar[13648] Unable to quarantine: 93
11/7/14 5:38:52.000 PM kernel[0]: FooBar[13648] Unable to quarantine: 93
11/7/14 5:38:52.000 PM kernel[0]: FooBar[13648] Unable to quarantine: 93
...
11/7/14 5:38:52.697 PM FooBar[13648]: updaterWillRelaunchApplication:0x608000240420
11/7/14 5:38:52.699 PM FooBar[13648]: FooBar 1.8.8.1.8 shutting down. Later!
11/7/14 5:38:52.000 PM kernel[0]: Autoupdate[15614] Unable to quarantine: 93
11/7/14 5:38:52.000 PM kernel[0]: Autoupdate[15614] Unable to quarantine: 93
11/7/14 5:38:52.000 PM kernel[0]: Autoupdate[15614] Unable to quarantine: 93
...
11/7/14 5:38:52.845 PM Autoupdate[15614]: Sparkle: mdimporting
11/7/14 5:38:53.399 PM FooBar[15616]: FooBar 1.8.8.1.9 started. Booyah!
```

First the `kernel[0]: FooBar[13648] Unable to quarantine: 93` occurs around 64 times. After the app shuts down, `kernel[0]: Autoupdate[15614] Unable to quarantine: 93` occurs about 400 times.

So far, it only seems to be a log issue. The actual app itself seems to be updating and relaunching fine.

**Comment by jt70471** [comment]
I am having the same issue except my app *is* failing to autoupdate.

**Comment by fwenzel** [comment]
Good hint, maybe I'll try rolling a slightly older version of Sparkle. Not like my users care what version it is so long as it works.

**Comment by jt70471** [comment]
Hi, I did some additional testing and found that I had a plist file that had a downlevel CFBundleVersion value. Not sure why it worked with 1.8.0 and not with 1.9.0, but I have confirmed that the autoupdate works with both 1.8.0 and 1.9.0 with the updated CFBundleVersion in the plist.

Sorry for the report that 1.9.0 was not working!

**Comment by akac** [comment]
So what is the answer here - is it to roll back to 1.80, or is it just something that needs to be fixed? 

I'm seeing MANUAL "check for update" -> update working just fine. Its only the automatic update (Automatically download and install updates) that I'm seeing the same problem with. 

Another thing I see is the "Check for updates" menu is consistently greyed out when this happens. Quitting the app and restarting the app shows that the update worked.

I don't care if we're using an older Sparkle…but I do want to make sure it works properly.

**Comment by jt70471** [comment]
1.9.0 works fine for me, the messages don't seem to prevent auto-update from occurring.

**Comment by pornel** [comment]
We've changed implementation details. Please reopen if it's still a problem.
