### ISSUE TITLE
Update to new version with different bundle identifier

### ISSUE THREAD

**Issue by raffael** [sparkle-project/Sparkle#462]
Hey guys,

I had to change the bundle identifier of my app sightly from version 1.0.5 to 1.1.0.
Now, when the update is downloaded, I'm getting a
```An error occurred while extracting the archive. Please try again later.```.

The console is showing:
```mdworker[6674]: zip importer encountered an error (3) scanning "[...]"```

When I check the folder where the ZIP is downloaded, I see both the ZIP and the extracted .app.

I assume that the changed bundle identifier is the problem.
Is there anything I can do to make the process work again?

**Comment by phranck** [comment]
Had the same problem. Any solutions out there?

**Comment by raffael** [comment]
I couldn't find one. I had to go on with the old bundle identifier.

**Comment by phranck** [comment]
Not me. I'll keep the new identifier and will go on this way:
![screen shot 2015-03-16 at 10 10 00](https://cloud.githubusercontent.com/assets/871198/6663229/c31874e8-cbc4-11e4-8657-cadb3c2f20a7.png)

**Comment by raffael** [comment]
Ha, yes, I thought about a similar approach, but it didn't want to annoy my users. In your case, the developers will understand though. Nice app, by the way!

**Comment by grahammiln** [comment]
You could use a [guided package](https://github.com/sparkle-project/Sparkle/wiki/Package-Updates) to install your new application; see #377 for details.

I used this technique to update a family of applications from a single Sparkle aware application.

Apple's `productbuild` and `pkgbuild` make creating an installer package for a single application reasonably straight forward. The installer package can include pre and post flight scripts to perform tidying up or other tasks.
