### ISSUE TITLE
Autoupdate (1.8.0).app keeps asking for admin privileges, then adds a copy of itself to trash? (OSX)

### ISSUE THREAD

**Issue by jaldmn** [sparkle-project/Sparkle#470]
So this is a bit of an odd one and it's taken some time to track down Sparkle as the cause (I think)

Essentially, a few days ago I started getting prompts for elevated privileges for Autoupdate.app, with no context about what app was being updated. I refused the first few of these, then got curious and did some googling - no hits. Couldn't find any 'autoupdate.app' files on my HDD so got bored and granted access. 

Even when I provided elevated rights via the prompt, the prompts kept coming; always starting at about 01:00 GMT.

Today I noticed my trash is full of various iterations of 'Autoupdate (1.8.0).app'; diving into the package contents I found a few references to Sparkle, hence my posts here.

Is this some fault with Sparkle? If so, how do I fix it? It's a bit disconcerting to constantly have prompts popping up asking for admin access...!
![ap](https://cloud.githubusercontent.com/assets/3884136/5550603/5cdf59d4-8ba1-11e4-8c19-ffc5c780603a.png)
![ao](https://cloud.githubusercontent.com/assets/3884136/5550602/5cdf5d30-8ba1-11e4-9614-da78ac148cd2.png)

**Comment by jonchui** [comment]
Just had this happen with me. At first i was worried "Autoupdate" was a cleverly-named trojan program or something. 

It also is moving old Autoupdate's into trash:
http://cl.ly/image/3Q2z0n1r2o3b

However, i don't have duet installed. So it must be another program?

iMac 27" (late 2009 model) 
10.10.5 Yosemite

**Comment by pornel** [comment]
In 1.12+ this part of process has been refactored, so it should behave better.

As for the "Autoupdate" name itself, that's the default name for a helper app that performs installation. Developers have ability to customize that name in "ConfigCommon.xcconfig".
