### ISSUE TITLE
Sparkle takes system's language by default how do I explicitly set language as part of localisation

### ISSUE THREAD

**Issue by ReddySanthosh** [sparkle-project/Sparkle#477]
In one of my project I am using Sparkle framework for autoupdate which is working well, except localization. 
I have requirement where I need to set language explicitly so I that I can show below screen in the language which I want.
Where as Sparkle supports localization for User's machine language by default. How to override it?

![screen shot 2015-01-15 at 8 58 48 pm](https://cloud.githubusercontent.com/assets/6426852/5760349/dac02fae-9cf9-11e4-9197-40149c5f2172.png)

**Comment by pornel** [comment]
We don't have such option. We depend on OS X to choose the right nib file. If you've modified your app to use another mechanism, you'll need to apply the same modifications to Sparkle's source and build your own version.
