### ISSUE TITLE
Updater window launch timing

### ISSUE THREAD

**Issue by macmule** [sparkle-project/Sparkle#479]
Hi there,

I've been using this great updater for a project of mine: [https://github.com/macmule/AutoCasperNBI] (https://github.com/macmule/AutoCasperNBI)

It's an AppleScript Objective-C app. 

Issue is, when an update is needed the updater come after showing the "Username & Password" prompt box. This box is called via applicationWillFinishLaunching_ & is called  checkPasswords_(me).

Ideally, i'd like to change the order so that the username & password box is shown AFTER the update window.. or that the update window appears in front of the username & password box.

Any ideas?

![screen shot 2015-01-20 at 14 21 45](https://cloud.githubusercontent.com/assets/2464974/5818926/688da996-a0b1-11e4-9de1-558c2ae25a0d.png)

**Comment by pornel** [comment]
Have a look at delegate methods:

https://github.com/sparkle-project/Sparkle/wiki/Customization

Sparkle calls them to let host app know what it's doing.

**Comment by macmule** [comment]
Thanks.. that page stumped me tbh, Especially as i have no explicit calls for SUUpdater.

BUT, someone pointed out that I'm asking for admin creds on my apps launch rather than before they are needed is odd. So amending my app rather than the SUUpdater call seems to have worked for me.

Should've thought about that really.

Thanks anyways, i'll be back!
