### ISSUE TITLE
Insecure update error on signed application, bundle removed from Applications

### ISSUE THREAD

**Issue by w00tnes** [sparkle-project/Sparkle#480]
Hi all,

I have a Qt application that uses sparkle for auto updating. It worked like a charm for quite some time, but in the last couple of weeks sparkle started to act a bit strangely. When I try to run the application, it pops up with the warning, that there's an insecure update error and immediately deletes the bundle from /Applications. The bundle in this case is in fact newer than the one hosted on the update URL, so I don't know why it would even attempt to update it.

The weirder part is, if I run the same application bundle from anywhere else (from ~/Desktop for example), there is no popup - BUT, if I copy the bundle to /Applications and run it from ~/Desktop, it still deletes it from /Applications (no popup though).

The app bundle and all the frameworks are signed with a developer certificate, if I run:
spctl --assess --type execute -vvvv on the bundle, it says that it's accepted and prints out the developer certificate details.

I've checked the ~/Library/Logs/SparkleUpdateLog.log, but there's nothing there to suggest any updating was done... are there any other log files that I can check? Has anyone had any similar issues perhaps?

Sparkle version is 1.8.0, if I can provide any more info please let me know.

**Comment by samir-aguiar** [comment]
What Qt version are you using? Version 5.4 is not working here because it's not finding the .plist file and thus not adding it to the bundle. Version 4.8 works fine though.

**Comment by w00tnes** [comment]
We're using 5.3.2, which plist file can't be found in your case?

**Comment by samir-aguiar** [comment]
The Info.plist file. We are setting it through QMAKE_INFO_PLIST, but there's a warning when compiling saying that it was not found. It added a default .plist file which didn't contain the keys required by Sparkle. Strangely using qmake 4.8 works fine.
Are you also using QMAKE_INFO_PLIST?

**Comment by w00tnes** [comment]
Yes, we've got it set as: 
QMAKE_INFO_PLIST = Resources/Info.plist

The plist is copied to the bundle without any warnings and all the keys are present.
