### ISSUE TITLE
Failed copying Sparkle.framenwork

### ISSUE THREAD

**Issue by H725-79** [sparkle-project/Sparkle#485]
It seems really strange what I'm about to say, simply because it never happened before to me.
After working a long time with Sparkle, lately Xcode seems to lose the ability to copy the sparkle framenwork using "Add copy Files Build Phase"...while this has worked before.. --->Yes, got it right!
Working in Yosemite, after some time, xcode has stopped copying the framenwork, and this happened while I was consecutively pressing on "build" button in xcode, within the same session. Practically this did not happen after closing Xcode or after the system restarts. Very strange.
I took this as a bug in Yosemite and Xcode 6.1, initailly...

Ok, my system has also Mavericks installed, where I used as an alternative to compile my application.
You know what happened? ---> The same thing: after a few sessions Xcode has stopped copying sparkle framenwork.

I also have the INPopoverController.framework that is included in ../Contents/Framenwork folder, but this still works ok.

For now I solved using "run script" phase, in this way:

exec > >(tee -a "$PROJECT_DIR/buildlog") 2>&1
echo "============================================"
SPARKLE="$PROJECT_DIR/MyApp/Frameworks/Sparkle.framework"
TARGET="$TARGET_BUILD_DIR/$FULL_PRODUCT_NAME/Contents/Frameworks"
CP_PROG="`which cp`"
mkdir -p "${TARGET}"
echo "---------- Sparkle.framework ---------------"
"$CP_PROG" -R            "$SPARKLE" "${TARGET}/"
echo "Sparkle.framework  copied:”
ls -a "$TARGET"
echo "============================================"

Think you know what happens? it's a Apple bug?
Sparkle is compiled separately (problem with both 1.8 and 1.9), Xcode 6.1 in 10.9.5 and 10.10/.1/.2

Thank You

**Comment by pornel** [comment]
Try `cp -p`. Sparkle requires symlinks to work, and code signing may require xattrs to work too. 

I suggest using Xcode's `Copy Files` build phase which will ensure these are preserved correctly.

**Comment by H725-79** [comment]
Ok for "cp -p", but "Copy Files" no longer works...that's why I'v opened this issue..

**Comment by MaddTheSane** [comment]
I use cp -a, but that might be too verbose.

**Comment by H725-79** [comment]
Thanks guys. however, I did not understand why this happens and what is due ..
