### ISSUE TITLE
Too many directories?

### ISSUE THREAD

**Issue by vaibhav-kaushal** [sparkle-project/Sparkle#486]
I am using Duet app on mac which uses Sparkle. The app is 4.5 MB approx and there are a hell lot of directories which are created inside ~/Library/Application Support/duet/.Sparkle with names **duet 1.2.5 X** where X is a number from 1 to 504. I guess they are updates. But the problem is - there are just too many of them. 

My question is - can I safely delete them?

**Comment by pornel** [comment]
Yes, you can delete them.

The latest version of Sparkle uses `Caches` directory and hopefully won't accumulate junk.

**Comment by vaibhav-kaushal** [comment]
Thanks :)
