### ISSUE TITLE
can't install Sparkle 1.9 via cocoapods (dyld: Library not loaded)

### ISSUE THREAD

**Issue by mackuba** [sparkle-project/Sparkle#488]
When I upgrade Sparkle in my Podfile to 1.9 and install it, the app fails with this error on startup:

```
dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/psionides/Library/Developer/Xcode/DerivedData/Hive-ehpvnsioiljackeaesxdinvgysge/Build/Products/Debug/Hive.app/Contents/MacOS/Hive
  Reason: image not found
```

If I downgrade it to 1.8 and do `pod install` again, it starts working again.

I can't find any instructions for installing Sparkle with CocoaPods, do I need to add anything extra manually? Usually CocoaPods configures everything in Xcode automatically (with other pods)...

(CocoaPods 0.36.0.beta.2, Xcode 6.1.1, OSX 10.9.5)

**Comment by pornel** [comment]
Oh, it's the `SKIP_INSTALL` again :/

#446 #409 #skip

**Comment by pornel** [comment]
@jakepetroules Should we have a separate branch for Cocoapods? Maybe we can develop some horrible hack, like a script that modifies Sparkle's xcconfig file?

**Comment by jakepetroules** [comment]
Pretty sure our podspec can have a post-install action or something like that if necessary, no need for a separate branch.
