### ISSUE TITLE
Should Sparkle provide localized versions of "Check for Updates"?

### ISSUE THREAD

**Issue by kainjow** [sparkle-project/Sparkle#494]
I noticed Sparkle doesn't actually contain the localized string "Check for Updates" and this seems to be the standard phrasing that most apps used.

What if Sparkle actually provided this, in the Sparkle.strings file? Then apps could call `NSLocalizedStringFromTableInBundle()`, possibly wrapped in a convenience function provided by Sparkle, e.g. `SUCheckForUpdatesLocalizedString()` to be used in menus, buttons, etc. It would be one less string each app would have to worry about localizing, and then this would consolidate all update localizations into Sparkle.

I could start off by providing several localizations from my various projects.

**Comment by pornel** [comment]
I'm not convinced about having an API for this. Applications typically have this string in their nib or strings files, and adding a different programmatic interface for just one string is probably not worth it.

I wouldn't mind providing default translations as a guide for the translators to ensure consistency across apps though.
