### ISSUE TITLE
Link 1.9 from main website

### ISSUE THREAD

**Issue by jjconti** [sparkle-project/Sparkle#495]
http://sparkle-project.org/ offers me 1.8. Is this an error and needs update or is 1.8 a stable release and 1.9 is not?

**Comment by pornel** [comment]
Sorry, oversight on our part

**Comment by grahammiln** [comment]
See [sparkle-project.github.io/pull/4](https://github.com/sparkle-project/sparkle-project.github.io/pull/4) for an approach to avoid needing to update the web site with every release.
