### ISSUE TITLE
Sparkle sending empty system-profile array

### ISSUE THREAD

**Issue by narner** [sparkle-project/Sparkle#497]
In my project that uses Sparkle, I have 'SUSendProfileInfo' and 'SUEnableSystemProfiling' set to YES in my Info.plist file. However, the array of system-profile information sent by Sparkle to our server is empty. 

Is this because Sparkle only sends SystemProfile information once a week? If so, how would I change the time interval for testing? Thank you!

**Comment by narner** [comment]
I think the reason is because (per a client's request), I set the HTTP method type to be POST instead of GET in `SUAppcast.m`, re-compiling Sparkle, and then adding the framework to the project again. Does anyone know if this is possible to do, or am I completely wrong?

**Comment by pornel** [comment]
As you can see we haven't tested using `POST`. Why did you find that change necessary?

**Comment by narner** [comment]
My client was worried that system-profile information could be seen by anyone packet-sniffing while users use the software, so they requested I try to change the HTTP request type Sparkle uses from `GET `to `POST`.

**Comment by pornel** [comment]
If you're concerned about packet sniffing there is no other way than using HTTPS (and over HTTPS method used doesn't matter).

POST does not affect packet sniffing at all. The data is still all in the clear, only a few lines later.

**Comment by narner** [comment]
I see, that does make sense. One other question...based on my understanding of REST, shouldn't information requests be done using  `GET`, and information submission be done with `POST`? 

Thanks again!

**Comment by pornel** [comment]
[REST doesn't care as it's supposed to be protocol-independent](http://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven), but more often then not it's misunderstood as merely "using HTTP properly".

As far as HTTP goes it's a borderline case. The purpose of this request is mostly to get the feed, and that works safely and idempotently. Stats collection is usually a negligible side-effect.

**Comment by narner** [comment]
I see, thank you kindly! 
I was able to get system-profiling information sent via POST per my client's request, so will close this issue now. Thank you for your help.
