### ISSUE TITLE
How does the updater handle Install on Quit for large apps?

### ISSUE THREAD

**Issue by edwardsanchez** [sparkle-project/Sparkle#498]
If my application is 1.5gb and I run install on quit - I then quit the application and immediately turn off my computer. Could I end up with a corrupt install? Meaning, if it takes the machine 5 minutes to update, but I turn off the machine before it completes the update, does Sparkle have any way to prevent corruption?

**Comment by alexrinass** [comment]
I might have a similar problem and I think it is independent of the application bundle size.

If the application is scheduled for installation on quit and the “quit“ is initiated by a system shutdown, it seems that the application bundle will not get properly installed and will get corrupted. We had several cases from users which indicates that this occurred.

There is an event called `NSWorkspaceWillPowerOffNotification` which might help to prevent installing the update on quit but there might be other strategies to handle this, of course.

**Comment by pornel** [comment]
Overwrite is not done by the application itself, but by a helper Autoupdate.app launched by Sparkle. The host app is already quit when the update is moved on disk.

**Comment by zorgiepoo** [comment]
I think they are talking about after the auto-update app is launched and the auto-update app being interrupted while it's running (shut down, crash, etc). They are asking if their updated app can be corrupted, which I think the answer is yes because the auto-update's copy operation is not atomic.
