### ISSUE TITLE
Does Sparkle support App Sandbox?

### ISSUE THREAD

**Issue by ghost** [sparkle-project/Sparkle#499]
I've decided to distribute some Mac apps outside the MAS (finally). I read some old posts that Sparkle does not support App Sandbox. If I remember correctly, the info I found was a bit old so I figured I'd just ask. Does Sparkle by default support App Sandboxing? 

For the majority of my apps I plan to distribute outside the MAS, I'd like to enable sandboxing.  

Thanks all.

**Comment by grahammiln** [comment]
Sandbox support is planned for v2.0 and is not currently supported. See #363 for the problems to yet to overcome.

**Comment by AT2014** [comment]
Ah, cool. Thanks for replying. Look forward to that 2.0 update...I'd much rather distribute sandboxed apps. 

I imagine it should be possible to migrate the Sparkle code to a helper application to support sandboxed apps.

**Comment by IngmarStein** [comment]
#363 hasn't been updated since January and it's currently the only issue scheduled for 2.0. Is anyone currently working on it?
