### ISSUE TITLE
Document pod support

### ISSUE THREAD

**Issue by ConfusedVorlon** [sparkle-project/Sparkle#501]
It's great that you now have a pod.

However, using is is slightly non-standard as the framework doesn't seem to be automatically signed.

I resolved this with a build script phase

`
LOCATION="${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"
IDENTITY="Developer ID Application: Hobbyist Software"
codesign --verbose --force --sign "$IDENTITY" "$LOCATION/Sparkle.framework/Versions/A"
`

I'm not sure if this is the best solution - but either way it would be great to see an update to the wiki page on how this should be handled.

thanks for one of the most useful projects!

**Comment by grahammiln** [comment]
Please feel free to update the wiki – click **Edit** at the top of the appropriate page.

If others know of better solutions, they can rewrite or improve upon your contribution. Until then your insight will help others. :+1:

**Comment by ConfusedVorlon** [comment]
done - I didn't realise the wiki was open.
