### ISSUE TITLE
Is it possible to update Russian translation to make it more accurate?

### ISSUE THREAD

**Issue by Auralien** [sparkle-project/Sparkle#502]
Hi!

I'd like to update strings file for Russian translation? If so, what is the best way to do that? :)

Max

**Comment by pornel** [comment]
You can fork and edit [strings file](https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/ru.lproj/Sparkle.strings) even via github.

If strings that you want to edit are a part of .xib file, then you'll need to clone and edit it using Xcode.
