### ISSUE TITLE
Updater Window sometimes hidden by main application window

### ISSUE THREAD

**Issue by ndpmurphy** [sparkle-project/Sparkle#503]
If the Updater Window (with 'Install Update' Button) is visible and I use cmd tab (or other means) to change to a different application, then when I come back to my app the Updater Window  is behind my main window. Some users never notice the window is open and are confused that 'Check for Updates' menu item is disabled. 
Sparkle almost has the code to solve this because it has an applicationDidBecomeActive: call-back. However this callback is only set if the application is out of focus when the updater window was originally opened,and the notification function clears the observer after the first time is is called.
I could not reproduce this in the test application, and I am not sure what is special about my application that the window order changes when application focus changes - maybe setting the window level could fix it. I am not sure if others will hit this problem, but they could if they have any special window handling. Even for applications that do not push the sparkle window to the back, I think always bringing the updater window to the front makes sense since the user should decide to skip or instal before they continue using the application.  They can still use the main window if they want to by clicking directly on that window and taking focus away from the UpdaterWindow, but at least they get more of a hint if the Updater Window is brought to the front every time the application gets focus.

There are 3 changes in the diff below - 
We now register the observer always ( old code only did it if the application was out of focus).
We do not clear the observer when the notification is called.
We do clear the notification in finishedWithChoice because at that point the user has pressed one of the buttons on the window, so we no longer want to bring the window to the front.

I could summit this as a pull request (without the SULOG statements) if you think you might use it.

  @interface SUUIBasedUpdateDriver ()

---

**\* 54,64 ****
      // Only show the update alert if the app is active; otherwise, we'll wait until it is.
      if ([NSApp isActive])
          [[self.updateAlert window] makeKeyAndOrderFront:self];
!  
!     // we do not want the updater window to get hidden if our application
!     // goes out of focus and comes back
!     SULog(@"addObserver applicationDidBecomeActive");
!     [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(applicationDidBecomeActive:) name:NSApplicationDidBecomeActiveNotification object:NSApp];
  }
- (void)didNotFindUpdate
  --- 55,62 ----
    // Only show the update alert if the app is active; otherwise, we'll wait until it is.
    if ([NSApp isActive])
        [[self.updateAlert window] makeKeyAndOrderFront:self];
  !     else
  !         [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(applicationDidBecomeActive:) name:NSApplicationDidBecomeActiveNotification object:NSApp];
  }
- (void)didNotFindUpdate
  ---
  
  **\* 78,93 ****
- (void)applicationDidBecomeActive:(NSNotification *)__unused aNotification
  {
  -     SULog(@"applicationDidBecomeActive start");
    [[self.updateAlert window] makeKeyAndOrderFront:self];
    !     SULog(@"applicationDidBecomeActive end");
    }
- (void)updateAlert:(SUUpdateAlert *)__unused alert finishedWithChoice:(SUUpdateAlertChoice)choice
  {
  !  
  !     [[NSNotificationCenter defaultCenter] removeObserver:self name:NSApplicationDidBecomeActiveNotification object:NSApp];
  !     self.updateAlert = nil;
    [self.host setObject:nil forUserDefaultsKey:SUSkippedVersionKey];
  switch (choice)
  {
  --- 76,89 ----
- (void)applicationDidBecomeActive:(NSNotification *)__unused aNotification
  {
      [[self.updateAlert window] makeKeyAndOrderFront:self];
  !     [[NSNotificationCenter defaultCenter] removeObserver:self name:NSApplicationDidBecomeActiveNotification object:NSApp];
  }

**Comment by mmulcair** [comment]
Diff with version 1.12
![screen shot 2015-09-23 at 12 48 03](https://cloud.githubusercontent.com/assets/13002376/10044268/71de75c8-61f1-11e5-9a9f-f4ce9ff7043a.png)

**Comment by zorgiepoo** [comment]
#551 is possibly related.

> Even for applications that do not push the sparkle window to the back, I think always bringing the updater window to the front makes sense since the user should decide to skip or instal before they continue using the application.

This view might not be shared with everyone.

**Comment by zorgiepoo** [comment]
We [disabled hide on deactivate](https://github.com/sparkle-project/Sparkle/pull/1804) which was causing issues.
