### ISSUE TITLE
Sparkle: Error: An error occurred while extracting the archive. Please try again later.

### ISSUE THREAD

**Issue by hetal-patadia** [sparkle-project/Sparkle#505]
Hi folks,

I am trying to integrate Sparkle framework into my application and I am getting this error where it download the archive but couldn't extract it. There is nothing showing up in my ~/Library/Logs/SparkleUpdate.log. However, when I see console.log, it throws following things:

Mar 26 12:52:52 macName.local AppName[55874]: Sparkle: Error: An error occurred while extracting the archive. Please try again later. (null)
Mar 26 12:53:12 macName.local: Sparkle: Extracting /Users/$user/Library/Containers/com.xxx.yyy/Data/Library/Caches/com.xxx.yyy/Sparkle/AppName 010301/AppName.dmg as a DMG
Mar 26 12:53:12 macName.local sandboxd[138]([55994]): hdiutil(55994) deny sysctl-write
Mar 26 12:53:12 macName.local diskimages-helper[55996]: ERROR: couldn't connect to framework.
Mar 26 12:53:12 macName.local diskimages-helper[55996]: DIHelper: setupConnectionToFrameworkWithUUID: failed
Mar 26 12:53:12macName.local AppName[55874]: Sparkle: hdiutil failed with code: 1 data: <<hdiutil: attach failed - No child processes
    >>
Mar 26 12:53:12 macName.local AppName[55874]: Sparkle: Can't mount DMG /Users/$user/Library/Containers/com.xxx.yyy/Data/Library/Caches/com.xxx.yyy/Sparkle/AppName 010301/AppName.dmg
Mar 26 12:53:12 macName.local sandboxd[138]([55994]): hdiutil(55994) deny sysctl-write
Mar 26 12:53:12 macName.local sandboxd[138]([55994]): hdiutil(55994) deny file-read-data /
Mar 26 12:53:12 --- last message repeated 1 time ---
Mar 26 12:53:12 macName.local sandboxd[138]([55996]): diskimages-helpe(55996) deny mach-lookup 116FF629-2030-415F-92C5-2B3A3AFB60FA

I changed some content from the log, hope this log helps. Please help me as I am not able to figure out what's going wrong. I followed all the steps as mentioned on the website.
@andymatuschak @pornel - Any help is highly appreciated

**Comment by hp011235** [comment]
Seems like an App Sandbox problem. I turned off the Sandboxing on my app and it went through perfectly fine. Can someone tell, whats the expected release period for v2.0 which will have App Sandbox support?

**Comment by maniac-coder** [comment]
Any updates on this. I am also having my app sandboxed. 

Can you guide me how to test Sparkle 2.0 alpha version?
