### ISSUE TITLE
Should Sparkle call LSRegisterURL?

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#508]
LSRegisterURL() registers or updates an application into Launch Service's database - should Sparkle use this after a plain or delta update of an application?

I found this bug, but perhaps it was not reported:
https://jira.atlassian.com/browse/SRCTREE-985

I see no reference to this function in Sparkle's source code. Note that this function can't be called from a sandboxed application (https://developer.apple.com/library/mac/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxDesignGuide.pdf).

**Comment by michelf** [comment]
Sparkle calls the `mdimport` command line tool [here][1]. I'd tend to believe that would register whatever is in the Info.plist file, but perhaps not.

[1]:  https://github.com/sparkle-project/Sparkle/blob/bc99dbd560356aab8de86d6d5548d29efd36d647/Sparkle/SUInstaller.m#L144

**Comment by pornel** [comment]
That's interesting. I thought that launching a newly updated app would be enough. I think we can add it.

**Comment by pornel** [comment]
Fixed, thanks @grahammiln
