### ISSUE TITLE
integrate with Carbon app?

### ISSUE THREAD

**Issue by davecotter** [sparkle-project/Sparkle#512]
can Sparkle be integrated with carbon apps?
i have some cocoa third party stuff integrated, so it may work?
i've heard of CarbonSparkle but can't seem to find it anywhere
also, my app runs on 10.4 and forward (up to 10.10), since many of my users run it on old hardware

**Comment by MaddTheSane** [comment]
You will have to use an older release, as the current version target 10.7 and 64-bit Intel.

I *think* 1.5 will work with 32-bit apps and older OS X releases.
