### ISSUE TITLE
Info messages are issued to stderr in SUBinaryDeltaTool.m

### ISSUE THREAD

**Issue by jduquennoy** [sparkle-project/Sparkle#516]
Non error messages like "processing …" are issued on stderr in SUBinaryDeltaTool.m".
Here is a proposal of a patch to fix that :

```
From d261ade133b0a7bc9edd4c3434fe8b6093b88c16 Mon Sep 17 00:00:00 2001
From: JDuquennoy <jerome.duquennoy@wanadoo.fr>
Date: Tue, 7 Apr 2015 09:55:23 +0200
Subject: [PATCH] Stdout used for non error outputs


---
 Sparkle/SUBinaryDeltaTool.m | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/Sparkle/SUBinaryDeltaTool.m b/Sparkle/SUBinaryDeltaTool.m
index bede8ba..c13e011 100644
--- a/Sparkle/SUBinaryDeltaTool.m
+++ b/Sparkle/SUBinaryDeltaTool.m
@@ -159,7 +159,7 @@ int main(int __unused argc, char __unused *argv[])
             return 1;
         }
 
-        fprintf(stderr, "Processing %s...", [oldPath UTF8String]);
+        fprintf(stdout, "Processing %s...", [oldPath UTF8String]);
         FTSENT *ent = 0;
         while ((ent = fts_read(fts))) {
             if (ent->fts_info != FTS_F && ent->fts_info != FTS_SL && ent->fts_info != FTS_D) {
@@ -184,7 +184,7 @@ int main(int __unused argc, char __unused *argv[])
             newTreeState[key] = [NSNull null];
         }
 
-        fprintf(stderr, "\nProcessing %s...  ", [newPath UTF8String]);
+        fprintf(stdout, "\nProcessing %s...  ", [newPath UTF8String]);
         sourcePaths[0] = [newPath fileSystemRepresentation];
         fts = fts_open((char* const*)sourcePaths, FTS_PHYSICAL | FTS_NOCHDIR, compareFiles);
         if (!fts) {
@@ -215,7 +215,7 @@ int main(int __unused argc, char __unused *argv[])
 
         NSString *afterHash = hashOfTree(newPath);
 
-        fprintf(stderr, "\nGenerating delta...  ");
+        fprintf(stdout, "\nGenerating delta...  ");
 
         NSString *temporaryFile = temporaryPatchFile(patchFile);
         xar_t x = xar_open([temporaryFile fileSystemRepresentation], WRITE);
@@ -269,7 +269,7 @@ int main(int __unused argc, char __unused *argv[])
         unlink([patchFile fileSystemRepresentation]);
         link([temporaryFile fileSystemRepresentation], [patchFile fileSystemRepresentation]);
         unlink([temporaryFile fileSystemRepresentation]);
-        fprintf(stderr, "Done!\n");
+        fprintf(stdout, "Done!\n");
 
         return 0;
     }
-- 
1.7.12.4 (Apple Git-37)
```

Optionally, a -q (--quiet) option could be added to suppress those outputs.

**Comment by zorgiepoo** [comment]
Alternatively, a verbose option could be added (with additional output suppressed by default). Either way, I agree that having an option to disable the extra info messages, or remove them entirely is probably a good idea. Changes would have to applied to SUBinaryDeltaApply.m too in any case.

**Comment by pornel** [comment]
I think messages output to stderr are typical. You can silence these messages with `2>/dev/null`.

**Comment by jduquennoy** [comment]
In my situation, binaryDelta will be used in a continuous build system.
I need to have error messages if an error occurs, but I'd rather don't have information messages on every builds. For that, I either use the quiet option of the tools I use, or redirect stdout to the big black hole with >/dev/null. This is no longer possible if everything is written to stderr.
Moreover, stderr outputs appears in red in the logs of my system, having information messages on the error output makes the analysis of the log much harder : you have to read everything to find the diagnostic messages hidden in the middle of the information messages.

I can confirm that on the huge majority of CLI tools I use, those rules are applied :
- information message are issued to stdout
- messages printed when something is going wrong, causing the tool to misbehave are issued to stderr

(see http://en.wikipedia.org/wiki/Standard_streams for more details)

**Comment by zorgiepoo** [comment]
Yeah, info and error messages should not be printed to the same stream. The info messages are hardly useful now which is why I was putting out the idea to remove them. To make them more useful, we could add an optional verbose flag and also print out what files are being diff'ed as well.

**Comment by pornel** [comment]
I see. Good point.

**Comment by zorgiepoo** [comment]
I put out a simple pull request for jduquennoy's changes as well as changes to the apply tool. I think a verbose flag with more info or a quiet flag could always be considered later.

@ jduquennoy - As a tip of advice, I recommend incorporating applying in your build system to make sure applying the patch actually works.

**Comment by pornel** [comment]
Done

**Comment by jduquennoy** [comment]
Wise advice zorgiepoo. I'll set that up :-).

Thanks :-)
