### ISSUE TITLE
Publish update with different Developer ID

### ISSUE THREAD

**Issue by tunabelly** [sparkle-project/Sparkle#517]
I have a someone unique situation in that I now have a different Developer ID and I need to use the new one to issue app updates.  Obviously I can't just use the new one since Sparkle is smart enough to realize this could be a malicious update.

Is there some other mechanism I can use?  Has anyone else done this successfully?

Just to clarify, I had Developer ID A and used that to publish an app and subsequent updates.  I now have Developer ID B and need to use it instead.  I still have access to Developer ID A for a while longer in case that helps.

**Comment by zorgiepoo** [comment]
Having looked at this [particular piece of code](https://github.com/sparkle-project/Sparkle/blob/bc99dbd560356aab8de86d6d5548d29efd36d647/Sparkle/SUBasicUpdateDriver.m#L222) before, I believe you need to provide a DSA signature to do this. Sparkle needs the download to be DSA signed OR the application needs to be signed by an Apple developer ID for the download to be validated. This is one of the several reasons I personally believe one should always DSA-sign even if they have a developer ID certificate.

So in theory, what you would do is that if you already haven't generated a private key, you would generate the private-public key pair, stick the public key into your app as the Sparkle wiki instructs, ship an update with dev ID A, then later on ship an update with dev ID B. On the other hand, if you already generated the DSA stuff before, you can just distribute an update with dev ID B.

May want to wait for someone to confirm what I've said is right, or you can try for yourself to see.

**Comment by tunabelly** [comment]
Thanks so much for the reply and for your idea, it sounds like a good one. I'll give it a shot!

**Comment by pornel** [comment]
Yes, @zorgiepoo is right. The path is Dev ID -> DSA -> different Dev ID.
