### ISSUE TITLE
Sparkle displays UI elements without a means to disable that

### ISSUE THREAD

**Issue by pupeno** [sparkle-project/Sparkle#521]
At the moment, when creating a SUUpdater by running code such as:

``` Objective-C
[SUUpdater updaterForBundle: someBundle];
```

a dialog might be open (by running NSRunAlertPanel) and there's no way to prevent that.

From a library design point of view I don't see why that is a better way of communicating information to the developer than an exception and/or NSLog.

From a more pragmatic point of view, the library is assuming a dialog can be displayed at all times and that's not true. I'm using SUUpdater on a screensaver and calling NSRunAlertPanel completely blocks the computer to the point in which only a hard reboot allows you to unlock it.

Can you please offer a simple clean way of running UI-less?

**Comment by kainjow** [comment]
Looks like it'd be easy to add a delegate method updaterShowModalAlert that could be implemented by clients to provide custom alert functionality (or disable them completely by doing nothing). Take a look at `showModalAlert:`

**Comment by pornel** [comment]
Yes, that's indeed a problem.

Before adding delegate methods I suggest separating UI and update code in Sparkle itself, e.g. adding some private delegate-like object that implements the UI for Sparkle. This way UI code will be in one place and could be replaced with another subclass provided by the app.

In the future that may also be on a barrier between a secure external process helper and the host app, so the API should avoid complex objects that can't be sent between processes.

**Comment by zorgiepoo** [comment]
This is addressed in my [fork](https://github.com/zorgiepoo/Sparkle) via the `SPUUserDriver` protocol, for controlling what kind of UI can show, and I also added a `startUpdater:` method that returns an NSError if something is configured incorrectly.

**Comment by suy** [comment]
@zorgiepoo Thanks for the update! Sadly, I had to go other route, and use a different updater, but is good to know this is achieved for my future projects.
