### ISSUE TITLE
Sparkle Test App Fails to Relaunch

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#525]
The test app does not relaunch after updating on my Mac. I traced down the problem and it's due to: https://github.com/sparkle-project/Sparkle/commit/a7d11f88c7c5e6378d69670a63fe2619aadb73b9 (Issue #508)

Commenting out the registration call makes the test app wore properly. Or if I add a sleep(10) after the launch service registration call, the app will relaunch. Apparently it takes some time for LaunchServices to update the app, not allowing Sparkle to re-launch it immediately? Perhaps the app should make the call after it's launched.

Possibly related to issue #459

**Comment by zorgiepoo** [comment]
Looks like if I substitute the -[NSWorkSpace openFile:] call with a NSTask invoking `open` it works, but this is really odd.. The process seems to think the executable for the app does not exist (NSBundle's executablePath returns nil for the app, but the executable file does exist).

**Comment by michelf** [comment]
Not sure if that's related to this problem, but note that NSBundle cache values. If an NSBundle instance exists for a given path, the same instance is reused for the same path later on. If you swap it for something different in the file system, most properties of the bundle will keep their previous values. I discovered that a while ago and wrote about [the problem] it caused me and its [solution].

Should keep this in mind while writing an updater.

[this]: https://michelf.ca/blog/2010/pref-pane-update-problem/
[followup]: https://michelf.ca/blog/2010/killer-private-eraser/

**Comment by zorgiepoo** [comment]
Calling `_CFBundleFlushBundleCaches` actually does make the app open, but it doesn't open in the foreground. I was familiar with bundle caching but didn't know such a function existed; good to know!

I'm still thinking an `open` task like how the [package installer works](https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/SUPackageInstaller.m#L17) might be the best idea currently rather than a private API.

**Comment by michelf** [comment]
Indeed, it probably is more robust to call `open` than to rely on a private API.

**Comment by pornel** [comment]
Perhaps it would be safest to call `registerWithLaunchServices` couple of seconds after relaunch of the app?

**Comment by zorgiepoo** [comment]
Regarding the test app not showing its dialog window in the foreground, I have a feeling that might have to do with the way the test application is written. The source code to the test app (after you update it) is not available to my knowledge.

**Comment by pornel** [comment]
> The source code to the test app (after you update it) is not available to my knowledge.

Sorry! Fixed that in b02a65974d237fed0bb93c0da32d44bfd8ff34bf

**Comment by pornel** [comment]
For now I've reverted LSRegisterURL. It'll require another approach :/
