### ISSUE TITLE
Suggested update to Cocoapods instructions: Generic Identities

### ISSUE THREAD

**Issue by revprez** [sparkle-project/Sparkle#528]
**Issue**: The Run Script phase suggested in the [Cocoapod instructions](https://github.com/sparkle-project/Sparkle/wiki/Cocoapod-install) has a fragile dependency on an environment variable IDENTITY.  Developers have to change the value of IDENTITY to match their identity, which makes life difficult.

**Solution**: The environment variable `CODE_SIGN_IDENTITY` is already available and is an appropriate input to the `--sign` flag for `codesign`.  Unless I'm missing something, it might make sense to update the suggested script to this:
```
LOCATION="${BUILT_PRODUCTS_DIR}"/"${FRAMEWORKS_FOLDER_PATH}"
codesign --verbose --force --sign "${CODE_SIGN_IDENTITY}" "$LOCATION/Sparkle.framework/Versions/A"
```

**Caveats**: Builds can still give rise to an *ambigious match* errors in codesigning, especially for developers attached to two or more teams/accounts that tend to use wildcard identity resolution.  Work around is to pin code signing to a specific identity in *Build Settings*.

**Testing**: Tested this solution against Mac Apple Store and Developer ID identities.

**Comment by pornel** [comment]
I've changed it. Thanks for the suggestion. If it's still not right, feel free to fix it further.

**Comment by revprez** [comment]
Thanks.

**Comment by harryworld** [comment]
It shows `Message from debugger: Terminated due to code signing error` to me, and the app is not launching, any idea?

**Comment by pornel** [comment]
No idea. Maybe try Xcode 8, which is supposed to fix some of this mess?
