### ISSUE TITLE
If update fails, re-trying should try already-downloaded update first

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#53]
_**Chris Hanson (eschaton)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/325600) on' 2009-02-05:*

When an update is downloaded but installing the update fails (say with a
crash), the next time you try to update Sparkle should first attempt to
use the already-downloaded update if it still exists, is still the
latest, and its signature is intact.

**Comment by pornel** [comment]
We can do that as part of #607
