### ISSUE TITLE
After Cocoapods install, XPC service crashes without manual setup

### ISSUE THREAD

**Issue by kujenga** [sparkle-project/Sparkle#530]
I just added Sparkle to my project, which consists of a main application with an embedded UIElement Application that runs as a menu bar item. That embedded application has an XPC service. I am using Cocoapods to handle dependencies.

The setup process went well using the instructions for a Cocoapods install for the main and embedded applications, but the XPC service would immediately crash with the error message:

```
dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/ataylor/Library/Developer/Xcode/DerivedData/App-gysrgcphenmskcbcffutldhvdpdb/Build/Products/Debug/AppHelper.app/Contents/XPCServices/AppService.xpc/Contents/MacOS/AppService
  Reason: image not found
```

I was able to solve the issue by following the normal setup instructions just for the XPC service, but now I have two copies of the framework in my project, one of which must be manually updated. I'm no expert on how Cocoapods works, but would it be possible to have Sparkle setup XPC services as well?

**Comment by jakepetroules** [comment]
Your XPC service should set an rpath pointing to the main app bundle's frameworks directory. For example, in the build settings for your XPC service:

    LD_RUNPATH_SEARCH_PATHS = $(inherited) @loader_path/../../../../Frameworks

This is labeled "Runpath Search Paths" in the GUI.
