### ISSUE TITLE
Missing SUPublicDSAKey in info.plist?

### ISSUE THREAD

**Issue by genericptr** [sparkle-project/Sparkle#531]
I just released an app and deleted the SUPublicDSAKey in the info.plist by accident without knowing. The app doesn't report any errors but I think it's going to give errors when I release a new version and users try to download. Is that correct or will Sparkle find the dsa_pub.pem file in the /Resources directory by itself?

Thanks!

**Comment by pornel** [comment]
No, it will not. The app won't update.

**Comment by michelf** [comment]
@genericptr Is your app signed with a Developer ID certificate? My reading of [`-[SUBasicUpdateDriver validateUpdateDownloadedTo:extractedToPath:DSASignature:publicDSAKey:]`][1] is that both apps signed with the same code signing certificate would be enough for Sparke to accept the update. Although perhaps there is something else requiring the DSA signature that I am missing.

[1]: https://github.com/sparkle-project/Sparkle/blob/d4843c90e8fb1ca38833985484e8c1e39d4b7b0a/Sparkle/SUBasicUpdateDriver.m#L222

**Comment by genericptr** [comment]
Thanks for your responses. The bundle is code signed but I thought SUPublicDSAKey was something specific to Sparkle? The location is always in /Resources and the default name the tool produces is dsa_pub.pem so I would assume Sparkle would just find this if it wasn't included in the info.plist. I'm a little confused what code signing the bundle with a Developer ID has to do with it.

**Comment by michelf** [comment]
Sparkle has two way to validate a download: either the code signature is the same as the older version of the app, or alternatively it checks for a valid DSA signature. If the installed version and the downloaded updated app have the same bundle ID and are code-signed using the same certificate, the update should pass validation.

**Comment by genericptr** [comment]
Thanks, I'll see what happens when I release the update.
