### ISSUE TITLE
Crash while delta update

### ISSUE THREAD

**Issue by antonc27** [sparkle-project/Sparkle#536]
**Problem:**
I playing around with "1.10.0rc1" and found that application is crashed during delta applying stage. For example, you can get crash if tries to apply delta update from 1.5 to 2.0 of "Sparkle test app".

**Proposed solution:**
In `SUUnarchiver.h` type of `updateHostBundlePath` property must be changed from `weak` to `copy`:
```
@property (copy, readonly) NSString *updateHostBundlePath;
```
Otherwise `source` arg in `applyBinaryDelta` becomes `nil`.

P.S. Maybe it is also a good idea to verify `source`, `destination` and `patchFile` args of `applyBinaryDelta` method in `SUBinaryDeltaApply.m` in order to prevent crashes like this one.

**Comment by zorgiepoo** [comment]
I see neither -[SUBasicUpdateDriver extractUpdate] nor -[SUPipedUnarchiverTest testBlah] hold a strong reference to the allocated SUUnarchiver. Could this be a problem as well?

**Comment by pornel** [comment]
They don't hold strong reference to the unarchiver indeed, but the unarchiver won't be freed while it's running — nsthread keeps it alive.
