### ISSUE TITLE
Support for flat .pkg files that are not compressed

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#54]
_**martoche (martin-ottenwaelter)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/342901) on' 2009-03-14:*

Mac OS X 10.5 introduced flat .pkg files that are already compressed. It
doesn't make sense to .zip or .tar.gz a flat .pkg file, they can be
downloaded as-is.

Sparkle assumes that all downloaded files should be unarchived, which is
not the case for a flat .pkg file.

Attached to this report is a patch that solves the problem. The patch
consists in one new class "SUNoOpUnarchiver" which is a SUUnarchiver
subclass that registers itself as the unarchiver for flat .pkg files,
but does nothing when asked to unarchive the file.

**Comment by kornelski** [comment]
Feature request closed after 11 years 11 months and 24 days!
