### ISSUE TITLE
add new Sparkle statistics server to the wiki

### ISSUE THREAD

**Issue by mackuba** [sparkle-project/Sparkle#542]
Hi,

I wrote a Ruby on Rails server for gathering and displaying Sparkle profiling info statistics: https://github.com/mackuba/sparkler

Example installation: http://sparkle.psionides.eu/feeds/gitifier/statistics

Could you add it to the list here? https://github.com/sparkle-project/Sparkle/wiki/System-Profiling#known-backends

**Comment by grahammiln** [comment]
You can edit the wiki page by clicking the **Edit** button at the top-right of the page. Please do add your new server implementation.
