### ISSUE TITLE
Make DSA Signatures Mandatory

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#543]
I strongly believe that DSA signatures should be required.

From my observations:

**Code Signing** ensures the _System_ can verify that the content inside the application came from the developer.

**DSA Signatures** ensures _Sparkle_ can verify that the archive is downloaded exactly as the developer created it.

To show how these are different, one needs to realize that code signing _intentionally_ allows changes to the app that doesn't break the application's signature.

Specifically, removing localization files, removing architectures from a mach-o binary, and allowing code inside the application to be replaced with other code signed by the same developer. The last point (which I quickly tested myself) implies someone could take an old executable and insert/replace it into a new application's update.

In the past, code signing also allowed resource rules to exclude certain files from being checked. Code signing also presently allows file permission changes (rdar://20835014).

Currently, validation code ignores DSA signatures if applications are signed (see issue #534). Sparkle also _does not_ perform a deep code signature validation of an application, which makes Sparkle not being able to detect plenty of bad changes (see issue #523).

Further, even if we could perform a deep check of an app's signature, we may not want to because of how CPU intensive/time consuming it can be for large applications. Ironically, I believe that unsigned applications that use Sparkle are the ones that have a more secure updating process.

Not requiring a DSA signature, or at least a public key in the app, is also inconsistent with how Sparkle deals with other mechanisms (packages, system prefpanes, whatever else), and it's also a burden if anyone wants to transition to delta updates which we should encourage more use towards in the some-time future.

It is true requiring a DSA signature is slightly more inconvenient when making an update. But if it's a whole lot more inconvenient, this just means the developer hasn't automated their update creation process. And this could even be thought of as a favor for making them do that..

Lastly, this is not to say basic code signing validation is completely useless, since it may catch cases where the application isn't archived or unarchived properly that may go otherwise unnoticed. But thinking of DSA signatures as the "old" or not recommended way as this wiki suggests seems to be quite dangerous (and in many cases inefficient) to me.

Thoughts?

**Comment by zorgiepoo** [comment]
Alternatively, serving over https might work as well as an alternative over Sparkle's DSA signatures. That might even be a little more secure since it would also prevent an attacker inserting newer updates from a beta appcast into a stable one for example. I have the feeling Sparkle handled https at one point but doesn't do that anymore.

**Comment by pornel** [comment]
Thanks for starting the discussion. You make good points.

In the short term we probably have to improve verification of Apple Code Signing anyway, since it's already supported. 

My assumption is that if Code Signing is good enough for Apple, it should be good enough for us. Although it is slightly less robust than DSA, since we can't verify it without extracting the archive first, so there's a larger attack surface.

In the long term perhaps it could be dropped if there's a better alternative available.

However, in general signatures and good key management are painful black magic. Apple's Code Signing is de-facto required, so we sort-of get that for "free", but we have to teach people how to generate and use DSA keys, which adds friction to the process.

Another concern I have is having a backup verification method. Having two methods allows recovery from a forgotten DSA key or change of Apple's code signing identity.

HTTPS would definitely be great on top of these mechanisms, but I'm not sure if it could be used _instead_:

* HTTPS only secures transport, but not files at rest, so a compromised server/CDN could send any update (e.g. HTTPS on CloudFlare can be MITMed, since CloudFlare allows origin to be unencrypted).

* I'm thinking how sandboxed support could be architected. With DSA signatures the host could still handle downloads and then give archive + destination path to the sandboxed helper, and the helper can then independently read keys and verify integrity. If HTTPS is trusted, then in sandboxed architecture the helper would also have to perform download by itself and store the downloaded file securely.

**Comment by michelf** [comment]
> I'm thinking how sandboxed support could be architected. With DSA signatures the host could still handle downloads and then give archive + destination path to the sandboxed helper, and the helper can then independently read keys and verify integrity.

Note that this would require a sandboxed host application to have an entitlement for outgoing network connections. Many apps don't need it.

**Comment by zorgiepoo** [comment]
I want to stress my main point:

Sparkle's use of code signing and DSA signatures are designed to solve *different* problems. To reiterate, code signing is designed to validate that the content inside an application came from someone (which means replacing and removing some types of content can be perfectly OK and desirable as long as the content inside is still by the same person; this works as intended). DSA signatures are designed to validate that the application is downloaded on disk the same way as the developer distributed it.

Pitting them against each other, i.e, by saying one is a standard, and the other is more robust, *doesn't make much sense*. You want both of these in an app updating system.

Code signing in Sparkle right now performs as a double duty, doing one thing it's intended to do, and another that it is not.

Quoting from Apple's Code Signing guide:

    Code signing has three distinct purposes. It can be used to:
    * ensure that a piece of code has not been altered
    * identify code as coming from a specific source (a developer or signer)
    * determine whether code is trustworthy for a specific purpose (for example, to access a keychain item).
    ...
    ...
    ...
    Note that code signing deals primarily with running code. Although it can be used to ensure the integrity of stored code (on disk, for example), that's a secondary use.

Apple documents it all the way at the bottom as a "secondary" use but to me it's a pretty bad and non-intended one at that; note that it should now make sense why Apple makes deep checking of content as an *option*, and why it can be sane to not do a deep test.

We can't just assume that code signing is good enough for Apple by the way. Apple distributes applications for developers (App Store), and for all we know could very well be using something like DSA signatures or something else on top of code signing for making sure the archive is downloaded properly.

I'll take your word on https stuff since I'm not too knowledgeable about it.

I'm not sure if having a backup solution is good from a security point of view.. Many people right now probably haven't generated a public DSA key, so if they could no longer use their Apple ID, they would be screwed anyway ;).

--
Another idea to think about would be signing the archive with a Developer ID which could be similar to a DSA signature in concept.. You'd then have to extract the code signature metadata from the archive, post or link it somewhere (like in the app cast), apply and validate it to the archive, and validate it against the old app's code signature to make sure it's the same. Not sure how well/reliable this would be, or if it'd be worth the trouble. Again, not really what Apple's code signing is intended for doing.

**Comment by pornel** [comment]
Do I understand correctly that the vulnerability is that a downgrade attack can be performed? (and other variants of this based on making a mashup of developer-signed files?)

Would it be satisfactory to have an option to disable code signing for users who prefer DSA-only updates? 

Alternatively reduce downgrade risk by only allowing code signing when HTTPS is used for the appcast and the download?

I agree that DSA is much more secure, but code signing does two important things much better:

* Xcode manages keys and puts them properly in the Keychain. Current Sparkle tool for DSA is an unfriendly shell script that dumps an unprotected private key somewhere on the disk.

* The difficult step of getting signature in place is already done for Apple, and it's Apple's problem to provide good tools and documentation. There's no extra work for Sparkle, and when signing doesn't work, all hate is directed towards Apple, not Sparkle :)

**Comment by zorgiepoo** [comment]
> Do I understand correctly that the vulnerability is a downgrade attack? (and other variants of this based on making a mashup of developer-signed files?)

To my knowledge, Sparkle currently correctly uses code signing to verify the identity (what it's intended for) of an application update. It incorrectly uses code signing to verify the update stored on disk is correct (not what code signing is intended for). Eg: missing or altered files due to no deep verification (biggest problem!). Other cases that wouldn't be caught even with deep verification on would be localizations being removed, architectures being stripped out from binaries, and one other case mentioned in the 1st post. Of course, this is intended from code signing's point of view so users can strip apps, and developers can replace binaries inside of them.

> Would it be satisfactory to have an option to disable code signing for users who prefer DSA-only updates?

No this doesn't make sense. Like I said before, you want both types of verification. DSA-only is less secure than DSA + code signing (for example you archive the application in an 'corrupted' way such the system doesn't consider the content inside to be yours anymore). I, personally, as a middle ground  would be happy if Sparkle made sure both the DSA and code signing are correct if both are provided. Currently Sparkle allows either to be incorrect which is a big hole. This should even address your backup verification concerns if code signing identity changes or if DSA private key is lost. This is discussed in issue #534; I'd be happy to continue testing the code in that issue if you give a nod...

> Alternatively reduce downgrade risk by only allowing code signing when HTTPS is used for the appcast and the download?

You said https doesn't secure files at rest.. So I don't see how this would help. Perhaps I shouldn't have brought up https, in any case I can't use https myself :|.

Apple wouldn't want to provide tools to an App Store competitor ;).

**Comment by zorgiepoo** [comment]
Now that Sparkle has proper DSA and code signing validation, and that Apple is changing the playing field by deprecating http, we should revisit this issue.

There are a few ways to ensure some sort of data integrity: dmg which I think uses CRC32 checksum (moderate for corruption, bad against attackers, pain to use otherwise), https which uses TLS to ensure confidentiality and integrity (great as long as the server is sending out the correct bytes), and DSA signatures applied to the archive.

I now agree with what has been alluded earlier: that is, deprecating serving over http *without* using a DSA key. We could either do this passively (e.g, log "Sparkle: Serving over http without providing a DSA key is deprecated and may not be possible in a future release"), or aggressively by disallowing it completely.

It would be silly to continue allowing a totally insecure way of distributing updates, without significant warning. It is also bad to recommend not using DSA too (which needs to be fixed up in the docs). Apple's code signing + https + DSA is really the best way to do an update using Sparkle.

Thoughts @pornel ?

**Comment by pornel** [comment]
Pushing for HTTPS makes sense.

I'm happy to deprecate and eventually drop support for HTTP + Code Signing-only combination.

**Comment by santhoshs5** [comment]
We are doing only code sign validation after download but we are getting sparkle error for the build which is built on 10.11.6 but  not on 10.10.5 .

Can I know the reason?

**Comment by zorgiepoo** [comment]
We would want more information than that. Please check the logs for specific errors, show what kind of UI errors may pop up, and please file a separate issue. This is not on topic with this thread.

**Comment by pornel** [comment]
I'd like to see if tool to auto-generate appcasts gets traction: #946 

if it does, then it'd take away most of the pain of DSA signatures, and we could push for them to be required.
