### ISSUE TITLE
Move Autoupdate.app out of Resources

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#546]
Helper Apps are not supposed to be in Resources. As it is currently, Autoupdate.app is in Resources and it can't or shouldn't be signed because it's in a directory that isn't supposed to contain signed files. It should be moved into the Executables directory or a Helpers directory according to the code signing guide. The former should be easier because Xcode doesn't provide a UI option for the latter.

After it's moved out to another location, the code that finds the Autoupdate.app path needs to slightly change. Then Sparkle being added to a new project that code signs Sparkle on copy needs to be tested, and verified that Autoupdate.app along with Sparkle's executable are both signed.

I would submit a pull request for this, but I've not had much luck with the last step because either something is screwed up with the project or I ran into an issue I didn't know how to resolve.

**Comment by kainjow** [comment]
I've used "Contents/Helpers" for helper apps in the main app bundle with success, but never done it with a framework. Can a framework support a "Helper" subdirectory? I don't see any information about this on Apple's website. If Autoupdate were to be stored in the main app bundle at Contents/Helpers, that would require a second Copy Files Phase and further complicate Sparkle's integration. However Sparkle could (and probably should) add checks at launch to see if Autoupdate exists at its required location so devs could fix the issue before even attempting to test Sparkle.

I'd first check to see if it would work inside the framework's Helper folder (and code signing passes and the app runs properly on 10.7-10.11), otherwise a move to the main bundle's Helpers folder may be necessary.

**Comment by zorgiepoo** [comment]
According to [Table 3](https://developer.apple.com/library/mac/technotes/tn2206/_index.html) of Apple's code signing article, the Autoupdate app can be in either a Helpers directory or the Executables directory (the latter which Xcode has a UI option for). Both are equally valid places.

Autoupdate need not be stored in the main app's bundle. We should be able to ship it inside of Sparkle's framework.

The problem is when I try changing the destination of Autoupdate to Executables, set a code signature for the test application, and try to build Sparkle's test application I receive this error:

```
CodeSign /Users/msp/Library/Developer/Xcode/DerivedData/Sparkle-fcwvfssfpluezdektysonoqniiqr/Build/Products/Debug/Sparkle\ Test\ App.app/Contents/Frameworks/Sparkle.framework/Versions/A
    cd /Users/msp/Desktop/Sparkle
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "Developer ID Application: Mayur Pawashe"

    /usr/bin/codesign --force --sign AC3251B5B9585F4D0AC1C0C59105D185A5E05069 --preserve-metadata=identifier,entitlements,resource-rules --requirements =designated\ =>\ anchor\ apple\ generic\ \ and\ identifier\ \"$self.identifier\"\ and\ ((cert\ leaf[field.1.2.840.113635.100.6.1.9]\ exists)\ or\ (\ certificate\ 1[field.1.2.840.113635.100.6.2.6]\ exists\ and\ certificate\ leaf[field.1.2.840.113635.100.6.1.13]\ exists\ \ and\ certificate\ leaf[subject.OU]\ =\ \"ZCK58M894E\"\ )) /Users/msp/Library/Developer/Xcode/DerivedData/Sparkle-fcwvfssfpluezdektysonoqniiqr/Build/Products/Debug/Sparkle\ Test\ App.app/Contents/Frameworks/Sparkle.framework/Versions/A

Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
/Users/msp/Library/Developer/Xcode/DerivedData/Sparkle-fcwvfssfpluezdektysonoqniiqr/Build/Products/Debug/Sparkle Test App.app/Contents/Frameworks/Sparkle.framework/Versions/A: code object is not signed at all
In subcomponent: /Users/msp/Library/Developer/Xcode/DerivedData/Sparkle-fcwvfssfpluezdektysonoqniiqr/Build/Products/Debug/Sparkle Test App.app/Contents/Frameworks/Sparkle.framework/Versions/A/Autoupdate.app
Command /usr/bin/codesign failed with exit code 1
```

Which makes zero sense to be especially considering I don't see resource rules set anywhere in the project. I have not been able to reproduce this issue in an isolated project however. I asked a friend to ask the Apple folk at WWDC about it, and ultimately they were confused and strongly recommended me to file a rdar which I may soon do.. Maybe we could figure out another way to automate this process; it shouldn't be very hard manually; the problem is Xcode.

**Comment by kainjow** [comment]
In the isolated project, did you mimic the same setup as Sparkle where a framework contains an embedded app?

I was able to get it to build completely by making sure Autoupdate.app was code signed in Xcode. Then the Sparkle Test App built and RB App Checker Lite reported no errors.

**Comment by zorgiepoo** [comment]
Apparently I didn't mimic the setup exactly the same in my isolated case. I had code signature set to "-" instead of "Don't Code Sign"; I have no idea what "-" is supposed to represent but it did code signing... So yeah, I can get Xcode to build the framework if I make sure Autoupdate.app is signed. However, this is not quite ideal because ideally the framework and the helper app inside of it should be unsigned, and when dropped into an application target that uses code signing, Xcode should be able to sign the framework and the helper tool as part of the build process.

**Comment by pornel** [comment]
I'd rather not change it. It seems that Frameworks don't fully support as many types of directories as app bundles.

In ImageOptim I've moved embedded executables from the app bundle to an embedded framework. I've tried using "Copy files destination: Executables", but Xcode just dumped executables in `Versions/Current`, without symlinks at the top level of the framework, and `pathForAuxiliaryExecutable:` wouldn't find them.

**Comment by zorgiepoo** [comment]
I finally decided to file an Apple bug report. rdar://21998371. Please feel free to also file a bug and link to my rdar, if you want these issues with Xcode to be fixed.

Never mind that the helper app in the wrong place, but as it is now many people aren't even signing it. To my understanding, code signing is important for #558 and sandboxing, so we wouldn't want to run into any potential hassles.

**Comment by JamesBucanek** [comment]
If anyone is thinking about changing how Autoupdate.app gets bundled, be aware that there's currently a bug in Xcode 7 that may prevent that. If you add an app bundle to the "Copy Helpers" build phase (so your app ends up in the Helpers folder), Xcode 7 performs an additional set of validation tests. Unfortunately, the tests it performs only apply to iOS apps distributed through the App store. Regular OS X apps fail this test, and the build dies.

I filed a bug on this and it was marked as a duplicate of rdar://21332924.

**Comment by pparekh7** [comment]
Why don't you move AutoUpdate.app to a new bin folder in the framework? Also, the fileop executable in AutoUpdate.app should be moved to a Helpers folder.

Making these 2 changes, I was able to codesign my app successfully.

**Comment by zorgiepoo** [comment]
Done in Sparkle 2.
