### ISSUE TITLE
Updater corrupts apps outside of /Applications

### ISSUE THREAD

**Issue by bdkjones** [sparkle-project/Sparkle#547]
If an app is running from somewhere other than `/Applications`, when Sparkle updates it, the app is missing key resources such as images, etc. This results in lots of exceptions and the app's main UI won't appear on screen.

At this point, the only fix is to delete the corrupted copy of the app and download a 100% fresh copy. 

A certain percentage of users typically runs things from, say, `~/Downloads`. This _seems_ to have become an issue only in Sparkle 1.9. I never had any reports of this behavior before updating Sparkle to 1.9 in my app. Since then, I've gotten a couple dozen reports of corrupted updates.

**Comment by zorgiepoo** [comment]
Possibly related to issue #441. Perhaps the helper Autoupdate.app crashed while Sparkle was copying over the new update?

**Comment by pornel** [comment]
I think we have atomic replacement now. Please reopen if it's still an issue.
