### ISSUE TITLE
Is Sparkle framework for Xamarin.Mac available ?

### ISSUE THREAD

**Issue by siva9sivaji** [sparkle-project/Sparkle#549]
I need to implement Mac Update using sparkle, but I have developed application in Xamarin.Mac, So far I didn't find Sparkle framework for Xamarin.Mac, Is there Sparkle framework supported for Xamarin.Mac?

**Comment by grahammiln** [comment]
There is no specific Xamarin build of Sparkle.

As [Xamarin can use standard Mac frameworks](http://developer.xamarin.com/guides/ios/advanced_topics/binding_objective-c/binding_objc_libs/) you can use Sparkle as is.

> ## [Binding Objective-C Libraries](http://developer.xamarin.com/guides/ios/advanced_topics/binding_objective-c/binding_objc_libs/)
>
> This document describes how to bind Objective-C APIs, if you are binding just C APIs, you should use the standard .NET mechanism for this, the P/Invoke framework. Details on how to statically link a C library are available on the Linking Native Libraries page.

The link above is for iOS, but I am assuming the "iOS linking to native frameworks" support is mirrored in Xamarin's Mac support.

You may want to [search or ask on the Xamarin forum](http://forums.xamarin.com/search?Search=sparkle) for others who have integrated Sparkle already; it appears possible.

If you are successful, please share your experience and approach on the [Sparkle wiki](https://github.com/sparkle-project/Sparkle/wiki)!

**Comment by chamons** [comment]
Over at the Xamarin.Mac forums, there is significant demand for binding to Sparkle. I have a preview binding here: http://forums.xamarin.com/discussion/50110/throw-it-over-the-wall-preview-sparkle-binding?new=1 . 

I'm the Lead Developer, so feel free to send Xamarin.Mac interest that way (or message me with problems).

**Comment by jakepetroules** [comment]
Given the high demand and minimal maintenance requirements I think we can maintain this ourselves. I encourage you to contribute this upstream via a pull request.
