### ISSUE TITLE
The notification window is not raising to front

### ISSUE THREAD

**Issue by Vernat** [sparkle-project/Sparkle#551]
I don't know about new version while I don't switch to my application. I need to bring it to front. (OS X Yosemite)

**Comment by grahammiln** [comment]
Consider implementing the delegate method [`-updater:didFindValidUpdate:item:`](https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/SUUpdater.h#L202) to learn when an update is available.

To inform the user about the update, issue a [NSUserNotification](https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSUserNotification_Class/index.html). These notification can appear even when your application is in the background.

**Comment by Vernat** [comment]
@grahammiln  my use case: user pressed check for updates from status menu. Showing NSUserNotification in this case is not well. Bring the main window to front is not good too. I need method like as  setBringUpdateAlertToFront(true/false default value)
I found in SUUIBasedUpdateDriver:
// Only show the update alert if the app is active; otherwise, we'll wait until it is.
    if ([NSApp isActive])
        [[self.updateAlert window] makeKeyAndOrderFront:self];
    else
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(applicationDidBecomeActive:) name:NSApplicationDidBecomeActiveNotification object:NSApp];

I would like  to add one flag and check if it is enabled here

**Comment by Vernat** [comment]
@grahammiln  another better way would be getting pointer to the update alert window and bring it to show or just method  bringUpdateAlertToFront();

**Comment by grahammiln** [comment]
In earlier versions of [Power Manager](https://www.dssw.co.uk/powermanager/), a status menu checked for updates.

When an update was found, the status menu did not show any user interface. Instead, the status menu launched Power Manager's application and the application handled the update user interface.

Is this approach possible for your situation?

**Comment by Vernat** [comment]
@grahammiln  the best way would be have ability to invoke bringing  the UpdateAlert window to front when I got notification about new available version

**Comment by grahammiln** [comment]
On Cocoabuilder,  [Bring app to front](http://www.cocoabuilder.com/archive/cocoa/209711-bring-app-to-front.html) talks about the same topic.

- Is your status menu within the application showing the update window?
- Would it be enough to add a Dock badge or make the Dock icon bounce? 
- Could you launch a separate small helper app to show a update window when the update is available?

You can always fork Sparkle and use you own custom variant. I have done this where Sparkle's default behaviour was not suitable.

**Comment by Vernat** [comment]
I know how to bring app to front. Probably there is misunderstanding. I don't want to bring the main window to front but I want to bring the update alert window to front when I got notification about new version after  my  click check for updates in menu of the system tray icon.

**Comment by grahammiln** [comment]
I believe I must misunderstand the situation.

- The status menu is a menu icon in the top-right of the menu bar.
- The Dock is the row of application icons, typically positioned at the bottom-center of the screen.

If you know where in Sparkle you need to change the code, consider forking. It will be the fastest way to a solution you can control.

**Comment by gnachman** [comment]
I've gotten reports that Sparkle's update notification window will appear behind a fullscreen window:
https://gitlab.com/gnachman/iterm2/issues/3727

**Comment by gnachman** [comment]
I am able to reproduce it; the window initially will appear visibly over a fullscreen window only if you're currently on the same Space as the fullscreen window. Switching spaces causes Sparkle's window to order back. The effect of this issue is that the automatic update checking is not useful if you use fullscreen windows because the user is very unlikely to see the notification window.

**Comment by zorgiepoo** [comment]
@gnachman The issue I can reproduce is this:

1) Sparkle checks for updates, finds one, and brings the update notification window up front.
2) When you switch spaces *and* switch to another application simultaneously or afterwards, and then switch back to the space you were on before that had the notification window, the notification window initially comes up front but then immediately orders back. This is irregardless whether there is a fullscreen window on the screen or not.

The situation I reproduced above is tied to using the "Hide on Deactivate" option on the notification window and switching spaces, and almost sounds like an OS X bug to me. Is there another issue or is this it?  By the way, the update window can probably still be accessed from the Window menu.

This poses perhaps another question. If you have a fullscreen window front, and the user gets the updater window prompted at them but decides to click back to their fullscreen window, then the notification window is ordered behind the fullscreen window. How should that scenario be addressed if at all?

**Comment by gnachman** [comment]
Yes, I think you're right regarding repro steps. Switching spaces often does switch to another application since it seems to pick something at random from your new space, esp. if my app only has fullscreen windows.

Probably the best way to fix it would be to post a notification to notification center. OS X makes strange choices with regard to window management, and other than changing the level I doubt we could prevent it from disappearing.

The issue users are hitting are that they don't know the window is there and they don't know they can get to it from the Window menu. The do see that "Check for Updates" is disabled. So it might be good to change "Check for Updates" to something else like "Install Update", but that's not a full solution since it's too common for the notification window to disappear.

**Comment by zorgiepoo** [comment]
We had fixed some window activation issues recently.
