### ISSUE TITLE
Update Issue : Sparkle Keeps giving popup for update

### ISSUE THREAD

**Issue by malavagile** [sparkle-project/Sparkle#553]
Hello,

I have used Sparkle framework for my mac app update functionality.
I used Sparkle Appcast Pixie to create appcast xml.
Here is the xml.

![screen shot 2015-05-29 at 11 23 38 am](https://cloud.githubusercontent.com/assets/10988932/7877251/dd679e12-05f5-11e5-9335-79f4a48d16bb.png)

Now the issue is User having version 1.0 will get the update says 1.1(1.0) is available. Now user update to version 1.1(1.0) till this it's good. But User again got update saying new version available 1.1(1.1). 

Here the second time update will have version 1.1(1.1) but I haven't upload this version on my server then why users getting this 1.1(1.1) update.

The zip file contains new version is also having version 1.1(1.0)

I am code signing my app so not used dsa signature

Please help me I am in big trouble due to this.

**Comment by pornel** [comment]
When Sparkle keeps showing an update over an over again it's because Info.plist in the app has older version number than the appcast.
