### ISSUE TITLE
Problem updating my app using Sparkle

### ISSUE THREAD

**Issue by RMartijnR** [sparkle-project/Sparkle#556]
Some info:
In my project I use a storyboard for my main view and the menu bar and I have added the SUUpdater object to the Application scene.
The app is signed using Developer ID Application identity.
I have made a test update app cast and zip file, I am not using the dosa signing.

When I try to test updating the application I get to the part 'Install and Relaunch' part.
After clicking the button, the update crashes:
2015-06-06 17:49:52.791 iHelp[60859:3392950] Couldn't posix_spawn: error 1
2015-06-06 17:49:52.793 iHelp[60859:3392950] (
	0   CoreFoundation                      0x00007fff8fa2403c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff883c076e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8fa23eed +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff8c4a4bbf -[NSConcreteTask launchWithDictionary:] + 3119
	4   Foundation                          0x00007fff8c64d159 +[NSTask launchedTaskWithLaunchPath:arguments:] + 194
	5   Sparkle                             0x0000000100467d2d -[SUBasicUpdateDriver installWithToolAndRelaunch:displayingUserInterface:] + 3880
	6   Sparkle                             0x0000000100476d52 -[SUUIBasedUpdateDriver installWithToolAndRelaunch:] + 403
	7   libsystem_trace.dylib               0x00007fff91ef6cd7 _os_activity_initiate + 75
	8   AppKit                              0x00007fff8d5dffb1 -[NSApplication sendAction:to:from:] + 452
	9   AppKit                              0x00007fff8d5f5a46 -[NSControl sendAction:to:] + 86
	10  AppKit                              0x00007fff8d5f5962 __26-[NSCell _sendActionFrom:]_block_invoke + 131
	11  libsystem_trace.dylib               0x00007fff91ef6cd7 _os_activity_initiate + 75
	12  AppKit                              0x00007fff8d5f58bf -[NSCell _sendActionFrom:] + 144
	13  libsystem_trace.dylib               0x00007fff91ef6cd7 _os_activity_initiate + 75
	14  AppKit                              0x00007fff8d5f3db3 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2821
	15  AppKit                              0x00007fff8d64c45f -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 770
	16  AppKit                              0x00007fff8d5f2466 -[NSControl mouseDown:] + 714
	17  AppKit                              0x00007fff8db5c2fc -[NSWindow _reallySendEvent:isDelayedEvent:] + 14125
	18  AppKit                              0x00007fff8d4ebd76 -[NSWindow sendEvent:] + 470
	19  AppKit                              0x00007fff8d4e8312 -[NSApplication sendEvent:] + 2504
	20  AppKit                              0x00007fff8d411c68 -[NSApplication run] + 711
	21  AppKit                              0x00007fff8d38e354 NSApplicationMain + 1832
	22  iHelp                               0x00000001000098d2 main + 34
	23  libdyld.dylib                       0x00007fff908c35c9 start + 1
)

I see the following in the console:
06-06-15 17:56:43,000 kernel[0]: AppName[61556] Unable to quarantine: 93
06-06-15 17:56:43,000 kernel[0]: exec of /Users/../Library/Containers/../Data/Library/Caches/../Sparkle/Autoupdate.app/Contents/MacOS/Autoupdate denied since it was quarantined by iHelp and not approved by Gatekeeper, qtn-flags was 0x00000002

I am using Sparkle 1.10 as a pod.

How can I solve this?

**Comment by grahammiln** [comment]
Given the error message includes `/Library/Containers/`, I am assuming your application is sandboxed.

If the application is sandboxed, then this will likely be the problem. Sparkle 1.10 supports code signed but not sandboxed applications.

See https://github.com/sparkle-project/Sparkle/issues/363 for experimental forks of Sparkle that support sandboxing.

**Comment by RMartijnR** [comment]
Thanks for the info!
I have 2 versions of my app, one for the App Store and one for download from my website. For the one for my website I wanted to use Sparkle. I have disabled sandboxing for that version, and it is working  as expected now.

**Comment by grahammiln** [comment]
That is good to hear. If possible, please can you mark this issue as closed.
