### ISSUE TITLE
Support for Swift (2.0)

### ISSUE THREAD

**Issue by SamusAranX** [sparkle-project/Sparkle#557]
Getting Sparkle to work in an all-Swift project is still a major PITA.
Official support (or at least a comprehensive 'this is how you do it' list of steps) would be nice.

**Comment by MaddTheSane** [comment]
What, exactly, is missing? What is making it difficult?

**Comment by SamusAranX** [comment]
The fact that my project stops compiling once I add Sparkle.framework to it, for example.
And that is after following all of the steps below number 1 on this page: https://github.com/sparkle-project/Sparkle/wiki

**Comment by Aahung** [comment]
I had same issue too. code signing problem

**Comment by Aahung** [comment]
I just solve the problem and I am able to compile it in Xcode 7 beta

**Comment by SamusAranX** [comment]
It's not a code signing problem, as I'm not signing my app at all.

**Comment by pornel** [comment]
What Sparkle needs to change to be compatible?

**Comment by Aahung** [comment]
Right now it works for me perfectly. What's the error message in your case?

**Comment by SamusAranX** [comment]
After adding the framework to my project and correctly going through [all these steps](https://github.com/sparkle-project/Sparkle/wiki), I get this:
```
ld: framework not found Sparkle
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Also, I have no idea what should be changed. I'm an end user, not a Sparkle core developer.
I should maybe mention that I'm using Xcode 7 beta 1 and that my project is written in what seems to be the first beta of Swift 2.0.

**Comment by nLight** [comment]
I have the exactly same issue with Xcode 7 beta 3, unsigned app and Swift 2.0
Will try to dig more info for you guys.

**Comment by nLight** [comment]
I've found the issue. It's a bug in Xcode-beta: https://github.com/Carthage/Carthage/issues/536#issuecomment-111554205

After I've added a path where Sparkle.framework is located the problem was gone.

/cc @SamusAranX

**Comment by pornel** [comment]
Great.
