### ISSUE TITLE
Appcast DTD URL Invalid

### ISSUE THREAD

**Issue by lhauck** [sparkle-project/Sparkle#559]
Referring to your wiki page for 'Publishing An Appcast', in your sample appcast, the DTD URL of http://www.andymatuschak.org/xml-namespaces/sparkle redirects to http://sparkle-project.org/appcast, which returns a 404.

What is the DTD url we should be using in our appcasts?

**Comment by pornel** [comment]
If you mean the bit `xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle"` then it's not a DTD, but a XML namespace URI, and it's fine. 

It doesn't have to point to anything that exists. XML namespaces use URLs only as opaque identifiers, and clients are never supposed to even try to load anything from that URL.

As for DTD specifically (specified via DOCTYPE), it's a dead SGML-era technology we don't support.

**Comment by lhauck** [comment]
Okay - thanks for the info.  I tracked this down from the winsparkle project, and I think the problem is that the 404 causes an issue with expat on their end.  I'll take it up over there.

**Comment by vslavik** [comment]
To be fair to the OP, it *is* common practice to put some formal definition (be it XML Schema or RELAX NG for example) at the namespace's URI as a bit of self-documenting convenience (e.g. [this](http://www.wxwidgets.org/wxxrc) or [this](http://purl.org/dc/elements/1.1/)) and having an easily found schema does have *some* value…

**Comment by vslavik** [comment]
>  I tracked this down from the winsparkle project, and I think the problem is that the 404 causes an issue with expat on their end.

Let me correct this for the record: this is nonsense. As @pornel explained, it's just a unique identifier. No XML parser — not Expat nor WinSparkle — fetches that URI and it is absolutely not true that a non-200 response to a HTTP request to said URI (if anything actually made it in the first place) could cause any "issue" with WinSparkle. You're jumping to unsubstantiated conclusions.

**Comment by lhauck** [comment]
On 06/19/2015 08:40 AM, Václav Slavík wrote:
>     I tracked this down from the winsparkle project, and I think the
>     problem is that the 404 causes an issue with expat on their end.
>
> Let me correct this for the record: this is nonsense. As @pornel
> <https://github.com/pornel> explained, it's just a unique identifier. No
> XML parser — not Expat nor WinSparkle — fetches that URI and it is
> absolutely not true that a non-200 response to a HTTP request to said
> URI (if anything actually made it in the first place) could cause any
> "issue" with WinSparkle. You're jumping to unsubstantiated conclusions.

Sorry - I thought it was the same issue that I had tracked down last 
year that we had emailed about.

-- 
Leon Hauck - Progressive Computing
Phone:  602-380-3811
