### ISSUE TITLE
Install and Relaunch appears on top of Installer

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#56]
_**Carl Harris (ceharris414)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/398559) on' 2009-07-12:*

When updating using a package (.pkg) in a disk image, the Install and
Relaunch panel appears over top of the Installer itself.  This confuses
users -- they seem to expect that the install will happen automatically
since the Installer app isn't on top.

Sparkle 1.5b6

**Comment by pornel** [comment]
We support guided install now, so this can be best avoided by hiding the installer completely.
