### ISSUE TITLE
Update model translation plist

### ISSUE THREAD

**Issue by pornel** [sparkle-project/Sparkle#576]
Most recent models are from 2013.

**Comment by kainjow** [comment]
Maybe it should just be removed altogether? Sparkle will always be behind with this list, and it's not hard to just google it if a dev wants to know which model it is. It doesn't really seem like Sparkle should be responsible for maintaining this list.

**Comment by jakepetroules** [comment]
Yeah, makes sense to probably just get rid of it. As long as profiling sends the raw model number I think it's fine.

**Comment by pornel** [comment]
Googled:

```sh
system_profiler -xml SPHardwareDataType | fgrep -A1 machine_name
```

which does give human-readable name. There might be a nicer API for this, or we could use that to gather model names.

**Comment by pornel** [comment]
```sh
xpath XSMachineAttributes.plist '/plist/dict/key[following-sibling::dict[1]//key[contains(text(),"marketingModel")]]|//key[contains(text(),"marketingModel")]/following-sibling::string[1]'
```

**Comment by pornel** [comment]
https://support.apple.com/en-gb/HT201300
