### ISSUE TITLE
Guidance moving from DSA to Code Signed

### ISSUE THREAD

**Issue by PusherLabs** [sparkle-project/Sparkle#579]
We have existing applications we have been distributing with Sparkle + DSA. We are moving to Code Signing the apps and I wanted advice from others who have made the switch with in-the-wild apps.

Can a DSA app be updated with a Code Signed app?

TIA

**Comment by zorgiepoo** [comment]
Just do what you've been doing and in addition code sign your application with your Developer ID. You don't want to remove DSA signatures unless you want to decrease the security of your download.

**Comment by PusherLabs** [comment]
I suppose I was making the assumption that Sparkle would complain about updating a non-Code Signed with a Code Signed application?

I can leave DSA in place, I'm just wondering if there are any other gotchas I should expect.

**Comment by zorgiepoo** [comment]
You can update a non-code signed application to a code-signed application, provided that you DSA sign your update, and your update includes the public DSA key like usual. So you will be moving from DSA signing the download archive --> DSA signing download archive + Code Signing the application.

It is possible (but not on your first code signing update) to remove the DSA signing later, but I strongly don't recommend it. The documentation at the moment is misleading suggesting code signing and  DSA signing can't co-exist together, and that DSA keys is for those who are unable to code sign, but that's just really untrue.

**Comment by PusherLabs** [comment]
Perfect! 

Your answer is super helpful and really ideal actually.

Thanks!
