### ISSUE TITLE
sh generate_keys.sh doesn't work

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#580]
```
msp@Slim ~/D/S/bin> sh generate_keys.sh 
generate_keys.sh: line 11: syntax error near unexpected token `('
```

Is there a technical reason for this / way to fix it?

**Comment by jakepetroules** [comment]
Because it's a bash script, not an sh script. Process substitution is not supported in the latter.

**Comment by zorgiepoo** [comment]
It's was just not very intuitive to me that the command didn't work, especially when I looked at the file extension.

**Comment by zorgiepoo** [comment]
Why does it need the file extension if it's not a sh script?

**Comment by jakepetroules** [comment]
You can invoke it like `bash generate_keys.sh`. Both bash and sh scripts conventionally use the .sh extension (or no extension).

**Comment by zorgiepoo** [comment]
I think removing the extension would probably be better and reduce confusion.

**Comment by jakepetroules** [comment]
It's not confusing at all... bash scripts with a .sh extension is a universal practice.

Besides, you should be invoking it like `./generate_keys.h` and letting the shell choose the correct interpreter from the shebang within the file.

**Comment by zorgiepoo** [comment]
It's very confusing if you aren't familiar with UNIX practices ;). And I've never encountered a .sh file that has failed before via doing sh file.sh

If you should be invoking it like that, that's all more the reason to remove the extension.

**Comment by zorgiepoo** [comment]
http://askubuntu.com/questions/503127/should-i-save-my-scripts-with-the-sh-extension agrees.

**Comment by zorgiepoo** [comment]
To put in a similiar comparison, I've never seen a .rb or .py file that has failed if I ran ruby or python on the file. To see that .sh conventions are different from the "common practices" unix world is mind boggling. (Of course you can similarly remove the file extensions to hint that they should be invoked directly ./ as well)

**Comment by jakepetroules** [comment]
> Executables should have no extension (strongly preferred) or a .sh extension. Libraries must have a .sh extension and should not be executable.

Yeah, I kind of agree with that style actually. ca86ce0

**Comment by pornel** [comment]
Seems fixed now
