### ISSUE TITLE
Non xcode docs

### ISSUE THREAD

**Issue by JoshuaKolden** [sparkle-project/Sparkle#587]
I work in a Qt make/cmake environment.  I was following wiki instructions that I thought were part of this repo, but now there is no wiki.  Can anyone point me to docs for command line builds, and/or restore docs for Qt based builds?

I'd be happy to add docs for code signing, and macdeployqt. But the final steps, I'm not clear on.

**Comment by jakepetroules** [comment]
All documentation previously in the wiki is now at http://sparkle-project.org/documentation, however I don't remember ever having any documentation for Qt based builds. 

We'd be happy to accept additional documentation via a pull request (https://github.com/sparkle-project/sparkle-project.github.io)

**Comment by kainjow** [comment]
I have a macro I use for integrating a pre-built Sparkle.framework into a CMake target. I could look into adding this to the docs, or maybe to a contrib folder in the repo.

**Comment by JoshuaKolden** [comment]
I found what I was looking for, http://sparkle-project.org/documentation/publishing/.  I think an index of the pages available would be helpful, instead of inline links only. 

For those who come to this thread looking for information on how to build pkg distributions here are a few sources of info about building packages form the command line, in preparation for pushing application updates.

Create OS X packages from the command line.
[Step 1][1]
[Step 2][2]

A concise version of the above as an answer to a StackOverflow question.
[Making OS X Installer Packages like a Pro][3]

[1]: http://thegreyblog.blogspot.com/2014/06/os-x-creating-packages-from-command_2.html
[2]: http://thegreyblog.blogspot.com/2014/06/os-x-creating-packages-from-command.html
[3]: http://stackoverflow.com/questions/11487596/making-os-x-installer-packages-like-a-pro-xcode4-developer-id-mountain-lion-re

**Comment by JoshuaKolden** [comment]
This issue is related to issue #589, and I think it can be closed now.  Thx
