### ISSUE TITLE
Where's the wiki?

### ISSUE THREAD

**Issue by moubry** [sparkle-project/Sparkle#589]
https://github.com/sparkle-project/Sparkle/wiki/Publishing-An-Update

^ This link doesn't work anymore because there's no wiki. Am I missing something?

**Comment by jakepetroules** [comment]
http://sparkle-project.org/documentation/publishing

**Comment by pornel** [comment]
Can we restore the Wiki and add redirects? There may be a lot of links out there, and current redirect to github project page isn't helpful.

**Comment by jakepetroules** [comment]
Yeah, I guess we should.. I'll take care of that.

**Comment by pornel** [comment]
Thank you

**Comment by jakepetroules** [comment]
Completed.
