### ISSUE TITLE
Isn't there a smaller updater alert dialog?

### ISSUE THREAD

**Issue by statico** [sparkle-project/Sparkle#590]
If I omit release notes from my appcast, the update dialog displays a lot of blank space. Is there a way to get a narrower, more compact dialog?

![image](https://cloud.githubusercontent.com/assets/137158/9024423/980dd7ee-3883-11e5-9700-3f81180295b1.png)

**Comment by zorgiepoo** [comment]
Dupe of #369

**Comment by statico** [comment]
Ooops, thanks.

See also pull request https://github.com/sparkle-project/Sparkle/pull/368

**Comment by zorgiepoo** [comment]
This should be fixed in master now.

**Comment by statico** [comment]
@zorgiepoo Great. Thank you all for an awesome library!
