### ISSUE TITLE
Content of SUModelTranslation.plist taken from the web

### ISSUE THREAD

**Issue by GabrielUlici** [sparkle-project/Sparkle#594]
Can i change the code and make that the content of SUModelTranslation.plist is taken from the github repo, or else where, so in that way all the time the profile is accurate and there is no need the update the framework?

**Comment by pornel** [comment]
If you mean that the list would be downloaded from the Internet, then it may be difficult to do that in the framework:

- We don't want the framework to make requests to a 3rd party. Currently the framework only talks to an update server configured by the software developer. This ensures there's no single point of failure, and we don't have to worry about privacy implications of contacting somebody else's servers.

- We'd like to keep framework installation and hosting as simple as possible, so if we required developers to host and update the plist themselves, it'd be another installation step in the manual, and another thing to troubleshoot.

What we could do:

- Separate the plist into its own repo, to be maintained separately from Sparkle, and usable by other projects than Sparkle.
- Don't translate model name in Sparkle at all. Just send the raw identifier and make translation a responsibility of software that displays the stats.

**Comment by GabrielUlici** [comment]
I was thinking of getting the content directly from the github repo, not requiring the developer to host or update the file, but as you said you don't want that and i understand why.

On the things on separating i would say no because then the developers would have another step to do when building Sparkle.

On translating as i know Sparkle send the raw identifier to the server not a translation.

**Comment by pornel** [comment]
Ah, right. It's only for the permission prompt.

**Comment by pornel** [comment]
The list is up to date for now — closing.
