### ISSUE TITLE
return of 'image not loaded' bug

### ISSUE THREAD

**Issue by ConfusedVorlon** [sparkle-project/Sparkle#598]
this seems to be a return of an old bug.

dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
Referenced from: /Users/gnachman/SparkleTest/Build/Debug/SparkleTest.app/Contents/MacOS/SparkleTest
Reason: image not found

https://github.com/sparkle-project/Sparkle/issues/420

I get it for sparkle 1.10 with xcode 6.4 and 7 when using cocoapods

I can fix it by following the instruction (not in the cocoapods instructions) to add

>> In Build Settings tab set “Other Linker Flags” to -Wl,-rpath,@loader_path/../Frameworks.

I'm guessing the podspec should be handling this, but if not, then the documentation should list the step.

**Comment by jakepetroules** [comment]
Podspec should set `LD_RUNPATH_SEARCH_PATHS = @loader_path/../Frameworks`. I'll look into this later.

**Comment by jakepetroules** [comment]
This will get pushed in the next release.

**Comment by ConfusedVorlon** [comment]
thank you.

**Comment by jakepetroules** [comment]
This is present in the 1.11 Podspec.
