### ISSUE TITLE
Sparkle closes on program close

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#60]
_**HPShelton (parker-shelton)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/517388) on' 2010-02-05:*

Sparkle should behave in a more modal manner, prompting the user to
cancel the update or cancel closing the main application if the main
program was closed.
1. I close the program, forgetting Sparkle has downloaded an update
2. Sparkle comes to front, asking if I'm sure I want to close and offering the option to continue updating or close the program.

This affects all applications that use Sparkle, and has been highly
annoying to me.

**Comment by pornel** [comment]
We'll fix it by resuming/reusing downloaded update #957 #71

**Comment by zorgiepoo** [comment]
You can think of this as a different issue. My fork always installs an update if it has been downloaded & extracted, for instance, even if the user terminates the app without hitting "Install & Relaunch"
