### ISSUE TITLE
fr_CA symlinked to incorrect path

### ISSUE THREAD

**Issue by homebysix** [sparkle-project/Sparkle#603]
Long time fan, first time issue-opener!

While I was packaging Sparkle-enabled apps with [AutoPkg](https://autopkg.github.io/autopkg/) recently, I noticed that two unrelated apps gave me the same packaging error:

```
The following recipes failed:
    PretendApp.pkg.recipe
        Error in com.github.homebysix.pkg.PretendApp: Processor: PkgCreator: Error: Can't lchown /tmp/tmpNDFVsd/PretendApp/Applications/PretendApp.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr_CA.lproj: [Errno 2] No such file or directory: '/tmp/tmpNDFVsd/PretendApp/Applications/PretendApp.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr_CA.lproj'
```

Digging deeper, I found that in both cases, the file in the Sparkle-enabled app at the following path:
```
PretendApp.app/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/fr_CA.lproj
```
is actually a symlink to this path:
```
/Users/andym/Development/Build Products/Release (GC dual-mode; 10.5-only)/Sparkle.framework/Resources/fr.lproj
```

Seems to me like a minor bug, but it's currently preventing AutoPkg from packaging affected apps. It'd be great to see that fixed. Thanks much!

**Comment by pornel** [comment]
I think that error only happened in the old Sparkle 1.5. In the current 1.10/1.11rc2 this symlink appears to be correct.

**Comment by homebysix** [comment]
So in other words, the developers of the two apps I tried to package will need to update the version of Sparkle they're using? I can reach out to them, if so.

**Comment by pornel** [comment]
Yes, the apps should upgrade Sparkle they use.

**Comment by homebysix** [comment]
Great, thanks!
