### ISSUE TITLE
1.5b5 error Symbol not found: _kSecBase32Encoding

### ISSUE THREAD

**Issue by generalPurpose** [sparkle-project/Sparkle#606]
Please close -- sorry for the noise. Found the cause elsewhere.

**Comment by jakepetroules** [comment]
No problem. By the way, 1.5b5 is very old; you should use the current version 1.11 if possible.

**Comment by generalPurpose** [comment]
Thanks Jake

I’m using the old build because I’m trying to support some users still on 10.6.8, but god I wish they’d upgrade! Spent weeks trying to make my app update compliant with SL and still having problems!!


Best

Phil

BatteryAlert - keep track of your Magic Mouse, Keyboard and Trackpad. More info on sqwarq.com/batteryalert
OSXClock - big, beautiful alarm clock and timer for your mac. More info on sqwarq.com/osxclock

http://applehelpwriter.com
http://sqwarq.com - apps for OS X & iOS
