### ISSUE TITLE
Failing to applying a binary delta does not log anything

### ISSUE THREAD

**Issue by mz2** [sparkle-project/Sparkle#608]
I have tried to put together binary deltas for an app I've developed, and got it to a stage now where I've got the delta enclosures in the appcast, correct DSA signatures for the builds and the deltas (the app is Developer ID signed so they weren't there before). However, the delta update simply fails silently and the update proceeds with a full download. Nothing is logged in Console in this event, so I'm at a loss about what I should change.

**Comment by pornel** [comment]
It's hard to guess. The delta files in the appcast aren't tagged in the way Sparkle recognizes?

**Comment by mz2** [comment]
I got the source of the failure to extract the new version from the patch figured out eventually (I'd prepared patches that had the .app contained in a directory… doh!) … I figured it out by attaching a debugger and stepping through the delta unarchiver calls. 

However, the reason I opened this issue is more that it would be very helpful if Sparkle logged some more diagnostics out (such as the hash mismatch that helped me figure out that I should try applying the patches by hand again once more to replicate exactly what was being done by Sparkle). The output of that unarchiver seems to not be logged into either system log or the SparkleUpdate.log. I wonder where its stderr gets redirected?

**Comment by zorgiepoo** [comment]
Ah, I think stderr is nuked to /dev/null since 10.9 or 10.10 (I forget which one), which would explain this problem :/.

This can be fixed my turning the apply & create functions into returning a BOOL and out NSError instead of logging the error inside and deciding to use SULog or fprintf, which I can take a look at later.

**Comment by mz2** [comment]
SULog would be a great start and should be a simple change.

**Comment by zorgiepoo** [comment]
@mz2 this should now be fixed.

**Comment by mz2** [comment]
Thanks!
