### ISSUE TITLE
Necessary to parse pubDate?

### ISSUE THREAD

**Issue by kainjow** [sparkle-project/Sparkle#609]
`<pubDate>` is parsed and stored, but the data is never actually used. Is it necessary to keep this code? I see it used in examples too, but it doesn't affect any of Sparkle's functionality.

I suppose maybe some custom third-party code uses it and that would be the only reason to retain the code. Otherwise, I think examples shouldn't be using it.

**Comment by zorgiepoo** [comment]
It appears to be used for sorting appcast items (yep, this wasn't that easy for me to find either; curse stringly typed info):

https://github.com/sparkle-project/Sparkle/blob/fb9b4a4f359857b1e3c7566079546488ee5dd49f/Sparkle/SUAppcast.m#L226

**Comment by kainjow** [comment]
Ah, good find.

**Comment by alanhamlett** [comment]
#756 means no longer using `pubDate` for sorting appcast items.
