### ISSUE TITLE
Swift Unit Tests

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#610]
Can we re-write or write new tests using Swift? I don't presume we have strong backwards compatibility requirements for unit tests.

**Comment by pornel** [comment]
I'm all for it!

**Comment by MaddTheSane** [comment]
I have some ported over in one of my own branches. Although they're probably written against Swift 1.2.

**Comment by jakepetroules** [comment]
/me grumbles something about backwards compatibility.

Realistically though, you should only be *building* against the latest SDK (regardless of deployment target), so I think this is fine.

**Comment by pornel** [comment]
It's been done more or less!
