### ISSUE TITLE
Allow some kind of "appcast-relative" enclosure URLs

### ISSUE THREAD

**Issue by Kampfgnom** [sparkle-project/Sparkle#616]
I want to publish my appcasts via a dockerized nginx serving simple static files.

Since we have several environments, where the appcast-container will have different URLs, I wondered if it would be possible to allow "appcast-relative" enclosure and release-notes URLs.

I am aware, that this would make the appcast no longer conform to the RSS specification, which does not allow relative enclosure URLs. But I am of the opinion, that containarized appcasts would be a great benefit and I don't see how else I would solve the issue.

At the moment I pass the container its base-url via env-variable and it seds the appcast on first run. I do not like that solution, since it I it either makes the container instance un-movable (flocker...), or I would have to add more logic to it.

Thank you for any thoughts on this :)

**Comment by jakepetroules** [comment]
Honestly, dynamically generating the appcast would be a much better idea. Let's not subvert standards.

**Comment by pornel** [comment]
I agree with Jake. If your environment is too complex to create a text file with a hostname, then it's a problem of your environment :)
