### ISSUE TITLE
Does Sparkle fully support IPv6?

### ISSUE THREAD

**Issue by LunaticoCR** [sparkle-project/Sparkle#617]
Hi Guys,

We're in the process of making our app fully capable of doing IPv6, does Sparkle support IPv6?

Thanks!
Daniel.

**Comment by pornel** [comment]
Yes. Sparkle doesn't handle any IPs by itself, so it supports IPv6 if OS X supports IPv6.

**Comment by LunaticoCR** [comment]
So it uses OSX API's then? That means that it does support IPv6 then.

Thanks a lot!
