### ISSUE TITLE
Automatic Updates with Insufficient Write Permissions

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#624]
I don't think this has been given too much thought, but if you have automatic updates enabled, then Sparkle tries to install the update when the app is terminating. If the app doesn't have permission to write (e.g, non-admin user updating an app in /Applications/), then AutoUpdate will prompt for an authorization dialog requesting for permission after the app has been terminated (normally where we wouldn't expect Sparkle to show any UI at all).

Few options I can think of approaching this:
1. Do nothing - leaves user confused why an updater is asking for a password
2. Make an educated guess by looking at the app's ownership, so that we never allow automatic updates to happen if we don't have sufficient write permissions before authorizing
3. Make an educated guess and prompt on app termination if the user wants to install the update - a bit intrusive in my opinion - and what about machine being powered off?
4. Make an educated guess, keep the update around, and automatically install on next launch - potentially tricky since we may have to validate the update again, and not sure if it's safe to do this without the host app's knowledge.

Maybe there are some other options I'm missing.. This should probably be addressed somehow anyway.

**Comment by pornel** [comment]
In the short term I think option 2 makes sense. I assume "not allowing automated updates" means doing updates, but displaying UI anyway.

**Comment by pornel** [comment]
BTW: the UI has "automatically install in the future". If the app is write-protected, then:

a) don't display the checkbox?

b) change file owner/write permissions to make auto updates possible?

**Comment by zorgiepoo** [comment]
I don't think b) is viable. For a) we can simply use NSFileManager's isWritableAtPath: method. What is really the difficult part hiding the check box. I assume we should be doing that if the developer specifies SUAllowsAutomaticUpdatesKey to false anyway?

**Comment by gaocan1992** [comment]
How can I change file owner/write permissions to make auto updates possible?
I have a similar issue [#1219](https://github.com/sparkle-project/Sparkle/issues/1219)
