### ISSUE TITLE
Is it possible to push out an update when Autoupdate.app is missing?

### ISSUE THREAD

**Issue by sveinbjornt** [sparkle-project/Sparkle#625]
Hello, I accidentally pushed out an update of an app containing a new version of Sparkle, but without the Autoupdate.app contained within the framework (!). These users now get an error if they try to install an update via Sparkle.

Is there any way to push a new, fixed version to these users, e.g. by using a .pkg or some code path that updates without using Autoupdate.app??

**Comment by pornel** [comment]
You can post an information-only update that will open a web page - make an RSS feed item with a `<link>`, but without an update file enclosed.
