### ISSUE TITLE
Minimum requirements of Sparkle.framework?

### ISSUE THREAD

**Issue by DagAgren** [sparkle-project/Sparkle#626]
I can't seem to find the minimum requirements of Sparkle.framework itself documented anywhere.

It seem to not work on 10.6.8, as I am getting complaints form users on that version. I'd at least like to be able to document the minimum version of my app properly, so I need to know.

**Comment by kainjow** [comment]
yeah, that probably needs to be better documented.

10.7 is the minimum currently. For 10.6 and below see the bottom of the [Releases](https://github.com/sparkle-project/Sparkle/releases) page.

**Comment by pornel** [comment]
It's the first thing mentioned in the readme: https://github.com/sparkle-project/Sparkle#changes-since-15b

and on the front page of the homepage:

> supports OS X versions 10.7 through 10.11 and Xcode 5.0 through 7.0.

**Comment by pornel** [comment]
I've added big warnings to download pages
