### ISSUE TITLE
Xcode 7 Test Coverage

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#636]
We should use Xcode 7 test coverage: http://stackoverflow.com/questions/31096924/how-to-use-code-coverage-in-xcode-7

Also can we remove or do something about coveralls? It never works properly (possibly because of Swift) and haven't found it particularly helpful.

**Comment by jakepetroules** [comment]
Yes, using the Xcode 7 functionality is a good idea. We can remove Coveralls in favor of that, but I'd still like a way to show the results on the readme if possible.

**Comment by ZevEisenberg** [comment]
@jakepetroules did you ever find a way to do this? Trying to add coverage reporting to [my own project](https://github.com/Raizlabs/BonMot/issues/3).

**Comment by jakepetroules** [comment]
No, haven't had time to look into it lately.
