### ISSUE TITLE
App Transport Security

### ISSUE THREAD

**Issue by galambalazs** [sparkle-project/Sparkle#644]
https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/index.html#//apple_ref/doc/uid/TP40016240”

Does this mean that updates served via HTTP feed (and the app file download also from the same HTTP) will stop working with El Capitan?

**Comment by pornel** [comment]
Yes. Sparkle is subject to all usual app rules. 

We recommend using HTTPS for both the feed and the downloads.

**Comment by zorgiepoo** [comment]
Only if you built with the 10.11 SDK and didn't add an exception to your http domain.

**Comment by galambalazs** [comment]
@zorgiepoo that seems like new info to me.

So does it mean that an app built with 10.10 SDK can still connect to HTTP servers, and so is able to update to a newer version even on El Capitan?

It matters because otherwise users would get stuck on an app version where automatic updates fail and you can't introduce new HTTPS urls for them even if you wanted to.

**Comment by invariant** [comment]
Apps built with 10.10 SDK are not subject to ATS and so can still update.

Apps built on 10.11 SDK are subject to ATS.

Source is my own experience.

(I recommend thoroughly testing your update mechanism if you switch10.11 SDK. It's not just HTTP. Certain things like the SSL version, and features like prefect forward secrecy are also important. Crucially, amazon cloudfront servers do not currently meet ATS criteria, requiring that you add an exception to the forward secrecy requirement.)

**Comment by galambalazs** [comment]
@invariant Thanks for the heads up. Good to know about Cloudfront caveats.

**Comment by galambalazs** [comment]
The documentation could be updated to reflect El Capitan requirements related to Sparkle.  
(it seems other people are running into this as well)

**Comment by frankrei** [comment]
You can still deliver updates without using HTTPS by simply by including:

`<key>NSAppTransportSecurity</key>`
`<dict>`
`	<key>NSAllowsArbitraryLoads</key>`
`	<true/>`
`</dict>`

in your info.plist on both OS X 10.11 and iOS 9.

**Comment by zorgiepoo** [comment]
If you want to opt out of ATS, you should add an exception to your specific domain(s), not add an exception to everything - unless your app really needs it.

**Comment by zsszatmari** [comment]
Hi!

Have similar problem. Don't want to allow arbitrary loads, really, that's a non-solution.
.xml is on cloudfront https, and Sparkle can download it just fine. But the update .zip file itself is on the same cloudfront domain, and I get:

```
Sparkle: Error: An error occurred while downloading the update. Please try again later. An SSL error has occurred and a secure connection to the server cannot be made.
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)
```

It didn't work with url pointing to amazon s3 bucket (https) either. 
Do you have any idea about how and why this can be?
Thanks!

**Comment by zsszatmari** [comment]
I'd also like to say that adding NSAllowsArbitraryLoads is a very bad idea, unless your app really needs it and you thought it over (e.g. you're developing a web browser or an rss reader). It's an unnecessary compromise for security.
You can get a free ssl cert at startssl.com, or if you wait a few weeks, with the debuting letsencrypt.org . And you can add the generated cert to your cloudfront distribution, see https://joshemerson.co.uk/blog/secure-your-site .
Hope this helped someone :)

**Comment by pornel** [comment]
We have documentation and plenty of warnings for this now.
