### ISSUE TITLE
10.11 Finder not reflecting new update

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#645]
I updated to 10.11 on my main machine just today, and noticed issues where Finder wouldn't update the short version field after an app has been updated (unless you force relaunch Finder). However I think I noticed this with apps using both old and new versions of Sparkle, and noticed this in Xcode's clean and re-build as well, so this could be a bug in OS X out of our control. Will need to investigate this more to see if that's the case..

**Comment by zorgiepoo** [comment]
It looks like an 10.11 bug to me which [I've reported](http://openradar.appspot.com/radar?id=6312615324155904).

**Comment by zorgiepoo** [comment]
Radar was duped to 22272394

**Comment by pornel** [comment]
Good to know

**Comment by zorgiepoo** [comment]
This is fixed in 10.11.4.
