### ISSUE TITLE
Sparkle causing app submission problems?

### ISSUE THREAD

**Issue by GoldenJoe** [sparkle-project/Sparkle#646]
I have a project in which Sparkle appears to work when running and testing in Xcode, but when I try to submit the build, I get an error saying something about the bundle being invalid because of Sparkle. I've posted a screenshot of the error on SO:

http://stackoverflow.com/questions/32914108/error-itms-90279-invalid-bundle

Can anyone offer some guidance? Is this a problem with Sparkle, the new Xcode, or my project?

**Comment by MaddTheSane** [comment]
Having Sparkle in a Mac App Store app is redundant, as the App Store has its own update mechanism.

**Comment by jakepetroules** [comment]
Yeah, there's nothing we can do about this. They block our bundle ID outright. Interesting that they block the org.sparkle-project based bundle ID, too. I wonder if it's just a simple match for `*sparkle*` or they actually keep up to date with us. If so, shows to our popularity. :)

**Comment by GoldenJoe** [comment]
Yes, you're right. I can submit if I remove it, but I was just wondering why it blew up. Since it is redundant, Apple probably does blacklist it.
