### ISSUE TITLE
Guided install produces error

### ISSUE THREAD

**Issue by dokterdok** [sparkle-project/Sparkle#656]
We're currently testing the Sparkle [guided install](http://sparkle-project.org/documentation/package-updates/) feature for our pkg, but we seem to randomly get a "SUSparkleErrorDomain error 4005" popup, right after hitting "Install and relaunch" and entering the admin credentials. I couldn't identify a pattern to reproduce it, although it happens approximately 50% of the time.

<img width="532" alt="sparkle error" src="https://cloud.githubusercontent.com/assets/5354424/10386736/09b0aa0e-6e5b-11e5-8f7b-560fbd42482d.png">

Any ideas what could be causing this?

A few additional details: 
- we could reproduce it with Sparkle 1.10 and 1.11
- we're getting this under OS X El Capitan. We haven't tested this under Yosemite yet.
- our PKG installer is included in a DMG
- we haven't noticed that issue with the regular, non-guided installation

**Comment by zorgiepoo** [comment]
Perhaps worth checking if a more detailed error is logged in the console?

**Comment by dokterdok** [comment]
According to the OS X error code 4005 description on this [site](http://krypted.com/commands/comprehensive-list-of-mac-os-x-error-codes/), it could be related to a "cantLoadPackage" error.
Here's one extract from the console around the time the error happened. I've to admit that I'm not too sure what is directly related to that error or to Sparkle. Let me know if there's something else I could check.

```
08/10/15 13:21:13.175 TripMode[631]: Sparkle: ===== TripMode =====
08/10/15 13:21:13.175 TripMode[631]: Sparkle: Extracting /Users/ddewit/Library/Caches/ch.tripmode.TripMode/Sparkle/TripMode 221/TripMode-1.0.4-220.dmg as a DMG
08/10/15 13:21:16.000 kernel[0]: hfs: mounted TripMode on device disk2s1
08/10/15 13:21:16.176 mds[68]: (Volume.Normal:2464) volume:0x7f84630af000 ********** Bootstrapped Creating a default store:1 SpotLoc:(null) SpotVerLoc:(null) occlude:0 /Volumes/75FB4EE2-B9D2-4E66-88B9-378B60FAE4B5
08/10/15 13:21:17.196 TripMode[631]: Sparkle: copyItemAtPath:/Volumes/75FB4EE2-B9D2-4E66-88B9-378B60FAE4B5/.Trash toPath:/Users/ddewit/Library/Caches/ch.tripmode.TripMode/Sparkle/TripMode 221/.Trash
08/10/15 13:21:17.197 TripMode[631]: Sparkle: copyItemAtPath:/Volumes/75FB4EE2-B9D2-4E66-88B9-378B60FAE4B5/TripMode.sparkle_guided.pkg toPath:/Users/ddewit/Library/Caches/ch.tripmode.TripMode/Sparkle/TripMode 221/TripMode.sparkle_guided.pkg
08/10/15 13:21:17.274 mdworker[606]: (ImportBailout.Error:1325) Asked to exit for Diskarb
08/10/15 13:21:17.275 mdworker[605]: (ImportBailout.Error:1325) Asked to exit for Diskarb
08/10/15 13:21:17.277 mdworker[610]: (ImportBailout.Error:1325) Asked to exit for Diskarb
08/10/15 13:21:17.278 mdworker[628]: (ImportBailout.Error:1325) Asked to exit for Diskarb
08/10/15 13:21:17.279 mdworker[640]: (ImportBailout.Error:1325) Asked to exit for Diskarb
08/10/15 13:21:17.282 mdworker[639]: (ImportBailout.Error:1325) Asked to exit for Diskarb
08/10/15 13:21:17.283 mdworker[708]: (ImportBailout.Error:1325) Asked to exit for Diskarb
08/10/15 13:21:17.000 kernel[0]: hfs: unmount initiated on TripMode on device disk2s1
08/10/15 13:21:17.685 deleted[435]: __38-[CacheDelete updateInFlight:set:add:]_block_invoke:293 trying to add "com.apple.activity_tracing.cache-delete", which is already inFlight
08/10/15 13:21:18.302 deleted[435]: __38-[CacheDelete updateInFlight:set:add:]_block_invoke:293 trying to add "com.apple.activity_tracing.cache-delete", which is already inFlight
08/10/15 13:21:18.827 com.apple.xpc.launchd[1]: (com.apple.quicklook[725]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
08/10/15 13:21:18.988 launchservicesd[84]: SecTaskLoadEntitlements failed error=22
08/10/15 13:21:19.062 lsd[272]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
08/10/15 13:21:19.062 lsd[272]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
08/10/15 13:21:19.064 launchservicesd[84]: SecTaskLoadEntitlements failed error=22
08/10/15 13:21:19.067 launchservicesd[84]: SecTaskLoadEntitlements failed error=22
08/10/15 13:21:19.256 appleeventsd[58]: SecTaskLoadEntitlements failed error=22
08/10/15 13:21:19.315 com.apple.xpc.launchd[1]: (com.apple.auditd[728]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.auditd
```

**Comment by zorgiepoo** [comment]
That 4005 error code could also be Sparkle's custom one, which is just *SUInstallationError*. You may have to peek further, say in SUGuidedPackageInstaller.m to see where the error is thrown. I don't see anything unusual from the logs and can't reproduce the problem myself under master.

**Comment by MattTimmons** [comment]
Seeing this as well in current download (1.13.0) Did anyone file a solution?

**Comment by zorgiepoo** [comment]
Looking at this issue again and at the screenshot, the error must occur when `AuthorizationExecuteWithPrivilegesAndWait()` fails (because error userInfo is nil), but I'm not sure for what kind of failure is happening inside it. I created #816 for improving our handling of it.

@MattTimmons @dokterdok do you recall if the update was installed or not on disk despite of the error alert showing up?

**Comment by MattTimmons** [comment]
I do not fully recall, but I do not think the update completed. Ran the update again and many times it would work.

**Comment by zorgiepoo** [comment]
We recently pushed code to master for improving the authorization execution code. Hopefully that may fix the issue in this thread.

**Comment by pornel** [comment]
We've had multiple improvements since, in both installation and error reporting. Please re-test with the latest version and reopen if it's still a problem.
