### ISSUE TITLE
Question: How does Sparkle handle enclosure URL quoting?

### ISSUE THREAD

**Issue by homebysix** [sparkle-project/Sparkle#659]
Hello Sparkle team,

I'm in the process of troubleshooting an [issue](https://github.com/autopkg/autopkg/issues/231) for another project, and I'd love to know how Sparkle handles enclosure URL quoting.

- It looks like Sparkle leaves quoted URLs as-is: `http://updates.pretendco.com/Super%20App%202.dmg`
- But does it actively quote unquoted URLs? `http://updates.pretendco.com/Super App 2.dmg`
- How does it prevent quoting an already quoted URL? `http://updates.pretendco.com/Super%2520App%25202.dmg`

Sorry if my terminology isn't quite correct, but I hope you get my meaning. Thanks!

**Comment by pornel** [comment]
It is kinda broken, because URL-decoding is applied :( 

https://github.com/sparkle-project/Sparkle/blob/93a87a4dfd89fbb2fbfbda4b0835b7d04a31001d/Sparkle/SUAppcastItem.m#L137

**Comment by homebysix** [comment]
Thank you!
