### ISSUE TITLE
How to correctly sign Sparkle.framework and Autoupdate.app with Xcode 7 on 10.11 El Capitan

### ISSUE THREAD

**Issue by frankrei** [sparkle-project/Sparkle#667]
Hi,

It looks like a lot of things affecting how the framework should be signed in both Xcode 7 and Mac OS X 10.11 has changed recently, but the documentation has not been updated.

The new gatekeeper code checks signatures of resources bundles, symlinks, etc. much more rigorously and Xcode 7 has the "sign when copying" checkbox that does a lot of the framework signing itself. On top of that non-HTTPS delivery of the appcast and the updated archive are both subject to the new `NSAppTransportSecurity` info.plist key.

I'm using RBAppCheck, spctl and codesign to verify my app bundles but after a lot of mucking about, I'm still not 100% certain that I'm doing things right.

Could somebody who knows please update the documentation and describe the authoritative way of signing the framework as _everybody_ using it will have to make these changes.

Thanks for your time.

**Comment by pornel** [comment]
As far as I can tell:

1. Use HTTPS for everything
2. Sign on Copy still works, nothing has changed here.

**Comment by frankrei** [comment]
I've had a lot of problems signing Sparkle correctly over the past week.

I've used to sign Sparkle 1.5b6 for a long time now and I have always used a separate "Run Script" phase in Xcode, signing first the `relaunch` executable, then the rest of the framework. This has worked fine for years.

Recently, I was caught out by the new ATS HTTPS rules and shipped an Xcode 7/ SDK 10.11 non-sandboxed version just before El Capitan came out; this lead to that version not being able to auto-update at all since it couldn't make its HTTP connection.

I added the new key in the `Info.plist` file that allows all HTTP requests. You are of course right that it would be better to do this only for my “home” domain, but I didn’t actually know that this is possible.

After finding Hockenberry’s article about Sparkle1.5b6 El Capitan problems, I also learned that Sparkle is once more under active development. Thanks guys!

The new much stricter code signing rules, however, caused a lot of problems for me. Previously I had had problems with the symlinks for `fr_CA.lproj`, so in my copy of Sparkle I had just deleted this and built without the link.

After spending a day and a half trying to figure out what was going on with various code signing problems, I finally tracked down the source of *most* of my problems. My build script used `zip -r` to zip my app bundle for the app cast. This lead to the symlinks being treated incorrectly, and instead of having a symlink from `A` to `Current` for instance, there would be two identical copies of the directory when the archive was unzipped. This happened in Sparkle’s own code and was apparently fine with Mac OS X 10.6 to 10.10.

Now with 10.11 it caused validation errors. Unhelpfully enough, the error message that is generated by codesign and spctl point to “missing resources”, which lead me completely astray. I used Kaleidoscope to diff working and non-working versions of the program, but it didn’t find anything different!? As it turns out Kaleidoscope does not really know about symlinks either..

In the end, I found that my .dmg versions and .zip versions were actually different and then it was easy to find the problem. So now I zip with the `--symlink` option and *most* of my problems have magically disappeared.

    > spctl --raw --verbose=4 --assess --type execute /Users/frankreiff/Desktop/ReleaseBucket/dmg\ version/Vitamin-R\ 2.app

    /Users/frankreiff/Desktop/ReleaseBucket/dmg version/Vitamin-R 2.app: accepted
    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
    <key>assessment:authority</key>
    <dict>
        <key>assessment:authority:row</key>
        <integer>6</integer>
        <key>assessment:authority:source</key>
        <string>Developer ID</string>
    </dict>
    <key>assessment:remote</key>
    <true/>
    <key>assessment:verdict</key>
    <true/>
    </dict>
    </plist>

and

    > codesign --verify --strict --deep --verbose=4 /Users/frankreiff/Desktop/ReleaseBucket/dmg\ version/Vitamin-R\ 2.app

    --prepared:/Users/frankreiff/Desktop/ReleaseBucket/dmg version/Vitamin-R 2.app/Contents/Frameworks/ShortcutRecorder.framework/Versions/Current/.
    --validated:/Users/frankreiff/Desktop/ReleaseBucket/dmg version/Vitamin-R 2.app/Contents/Frameworks/ShortcutRecorder.framework/Versions/Current/.
    --prepared:/Users/frankreiff/Desktop/ReleaseBucket/dmg version/Vitamin-R 2.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
    --validated:/Users/frankreiff/Desktop/ReleaseBucket/dmg version/Vitamin-R 2.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
    /Users/frankreiff/Desktop/ReleaseBucket/dmg version/Vitamin-R 2.app: valid on disk
    /Users/frankreiff/Desktop/ReleaseBucket/dmg version/Vitamin-R 2.app: satisfies its Designated Requirement

now both work.

*However* RB App Checker Lite still complains about Autoupdate.app being unsigned.

This does not cause gatekeeper to reject the bundle, but that’s clearly only a matter of time. The next time gatekeeper gets stricter it will surely reject unsigned executables inside of the Resources folder.

Up to now, I signed “relaunch” in the “Run Script” phase before signing the Sparkle.framework and that satisfied codesign, spctl and RB App Checker Lite.

Using the “Sign on Copy” flag signs everything before the first script phase, so I’m breaking the signature by signing it later. On top of that I get validation errors if I re-sign Sparkle.framework *after* signing Autoupdate.app.

I have seen that you have already updated the documentation mentioning the App Transport Security changes in El Capitan. I think a mention on the http://sparkle-project.org/documentation/publishing/#publishing-an-update page to make sure that symlinks are properly compressed might help others from not repeating my mistake.

As far as the unsigned `Autoupdate.app` bundle is concerned:

1. is it okay to ship an update without this being signed?

and

2. what do you intend on doing about this long term?

**Comment by pornel** [comment]
Thanks for the writeup. I've added note about symlinks to the docs.

I'm not sure about the Autoupdate.app myself to be honest. Xcode code signing is rage-inducing and I've even been running in to crashes in codesign and spctl.

**Comment by billymeltdown** [comment]
Thanks for the write up @frankrei, glad to see I'm not alone! Have been trying to get Sparkle.framework signed properly and included in my apps for days with many of the same issues. Figured out the `zip -r` squashing symlinks thing just this morning. Still have other issues, not over the hump yet, I suspect resigning in Run Script might be borking things for me, since you mentioned it was for you. Updated docs on the Right Way would super fantastic.

> Xcode code signing is rage-inducing

+1000

@pornel the code signing will continue until morale improves!

**Comment by zorgiepoo** [comment]
You should not use zip for archiving apps. You should use ditto in the same manner that Finder creates archives. Don't have the usage for it on me at the moment.

Technically it's frowned upon for items to be signed and placed in the resources directory. Xcode's tooling sucks right now and doesn't allow us to change where we put AutoUpdate. See the code signing reference for more info. Code sign on copy should be adequate for the majority.

Btw, the best time to do code signing validation is right after you create your archive, trying to unarachive it and see if it still validates with spctl and/or codesign --deep

**Comment by frankrei** [comment]
Thanks for all the help! 

I'm going with the Autoupdate.app unsigned, but it looks like it's not quite yet the end of my troubles with Sparkle this time around.. I think I've found a bug affecting 10.10 and 10.11 updates, but I'm still working on. I'll post an issue if I confirm.

**Comment by zorgiepoo** [comment]
And the proper way to zip an app if you want to automate it is:

`ditto -c -k --sequesterRsrc --keepParent <src_path_to_app> <zip_dest>`

Which is specified in the ditto man page as an example.

**Comment by frankrei** [comment]
Thanks. I made the change 3 days ago upon your recommendation. I think it'd be great to put this into the documentation, complete with the command line example, so that other people won't run into the same problem.

Thanks again to everyone who replied, you are a very helpful bunch!

**Comment by dmccombs** [comment]
Oof. I've been running into these code signing change pains and was happy to finally come across some talk of similar issues. I don't use Xcode as an IDE for building my app, and instead just call `codesign` directly to sign things. Like others, I had been doing it this way for years including the `Sparkle.framework` in my app bundle without a problem, until 10.11.4. Argh.

At this point I'm not even as far as zipping up updates - or even signing my app itself - I'm not having success just signing the `Sparkle.framework` initially to include it in my app. Whether I do or don't sign the `AutoUpdate.app` bundle, and then sign the framework itself, `codesign --verbose=4 --strict --deep` says it's valid and satisfies requirements, yet `spctl -a` rejects it with an `obsolete resource envelope` message. This is with signing on 10.11.5 itself using Sparkle 1.14.0.

Does anyone have suggestions on how the heck to get past this? It's maddening.

**Comment by pornel** [comment]
Sorry, it is maddening. Please file a bug with Apple. I've seen similar bugs in codesign and to my surprise I got a helpful response to my bugreport, so Apple is paying attention to the pains it causes.

**Comment by zorgiepoo** [comment]
I don't think `spctl -a` is supposed to be used on frameworks.

**Comment by dmccombs** [comment]
Hmm - I'll try opening a bug ticket with Apple and see what it goes. As far as `spctl -a` not working on frameworks, if so, that's something new, as it accepted Sparkle on 10.11.3 and below.

**Comment by zorgiepoo** [comment]
If you take a look at the man page for `spctl`, the utility is for managing allowed code on a system (in other words, it's what Gatekeeper uses). This makes sense for applications and packages which users run, but it makes no sense for frameworks.

**Comment by dmccombs** [comment]
For anyone else who comes across this with a similar problem, I'll post what the solution was for me here. I ended up figuring it out by using Sparkle's `Autoupdater.app` as something I could sign that validated, and started switching out pieces with my own app to determine why I was getting the vague `Obsolete resource envelope` error on OS X 10.11.4+ even though the resource envelope version was 2.

It ties back into Gatekeeper on 10.11.4 no longer saying that things other than app bundles are valid, just like it no longer says the Sparkle Framework itself is valid when running `spctl -a` on it. My app's `Info.plist` was missing the `CFBundlePackageType` key, which defaults to a type that is not an OS X app if it's not found, causing Gatekeeper to reject it. Adding that in and setting it to `APPL` (and re-signing it of course) fixed the issue for me.

**Comment by zorgiepoo** [comment]
Since I found this on Apple's [docs](https://developer.apple.com/library/content/technotes/tn2206/_index.html), I thought I'd mention it for future reference:

> Important: spctl must only be run on top-level app bundles. If it is run against other bundles such as embedded helper apps or frameworks, the tool will return an error
