### ISSUE TITLE
Xcode 7.1 & Cocoapods: Include of non-modular header inside framework module 'Sparkle'

### ISSUE THREAD

**Issue by x2on** [sparkle-project/Sparkle#668]
Hi,

with Xcode 7.1 and CocoaPods 0.39.0 i get the following error:

```Include of non-modular header inside framework module 'Sparkle'```

My `Podfile`:

```ruby
platform :osx, '10.10'
use_frameworks!

pod 'Sparkle', '1.11.0'
```

**Comment by jakepetroules** [comment]
Interesting, given most OS X frameworks seem to use the former approach. Well, if the compiler says so...

**Comment by x2on** [comment]
Currently i added the following workaround to my `Podfile`:

```ruby
post_install do |installer|
	filename = "Pods/Sparkle/Sparkle.framework/Versions/A/Headers/Sparkle.h"
	outdata = File.read(filename).gsub(/(.*)<Sparkle\/(.*).h>/, '\1"\2.h"')
	File.open(filename, 'w') do |out|
 		out << outdata
	end  
end
```
