### ISSUE TITLE
Sparkle should really support bundles

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#67]
_**Hofman (cmhofman)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/257001) on' 2008-08-11:*

Sparkle is still not safe to be used in loadable bundles (plug-ins),
even though the web site advertises that 1.5 supports it.

Part of the problem is solved by having one updater per bundle.

The biggest problem currently is more fundamental: only one instance of
a framework can be loaded in a single program. So if several plug-ins
have Sparkle embedded, only one of the Sprakle frameworks will be
loaded, at best, or loading will simply fail and the app crashes. Even
if everything loads, the Sparkle version may differ, which can lead to
unexpected results, including crashes.

The only safe way I can think of to add Sparkle support to a loadable
bundle is to run Sparkle in a background app. Sparkle should have a
target for at least a bare bones agent to accomplish this.

**Comment by zorgiepoo** [comment]
This is addressed in my [fork](https://github.com/zorgiepoo/Sparkle) by aiding in moving Sparkle to another app (eg: see sparkle-cli). I am *pretty* convinced that plug-ins should definitely not load Sparkle.framework directly. Some plug-ins may not even need a custom UI for updating and just perform updates automatically.
