### ISSUE TITLE
Customizing autoupdate name and icon during system message.

### ISSUE THREAD

**Issue by DidierMalenfant** [sparkle-project/Sparkle#671]
I seem to remember there was an update allowing people to customize the name and icon used in the system message "autoupdate wants to make change..." which happens when the user updating the app is not admin.

Did I dream this? I can't seem to find a reference to it in the doc.

**Comment by pornel** [comment]
I don't think we have an option to customize the icon, but we do have an option to change name of Autoupdate.app to something else, if you build Sparkle yourself:

https://github.com/sparkle-project/Sparkle/blob/master/Configurations/ConfigCommon.xcconfig#L4

**Comment by DidierMalenfant** [comment]
Thanks. I updated it in the IDE instead of changing the config file by hand.

**Comment by pornel** [comment]
I'm afraid that just renaming the Autoupdate.app product in Xcode will break things, because Sparkle.framework needs to be *compiled* with knowledge of that app name, so that it can find it and launch it.

**Comment by DidierMalenfant** [comment]
I wasn't clear enough. I meant I changed ```SPARKLE_RELAUNCH_TOOL_NAME```'s value from the build settings of the project in the IDE instead of hacking the xcconfig text file.

**Comment by pornel** [comment]
:+1:
