### ISSUE TITLE
SUUpdateAlert broken due to invalid constraints

### ISSUE THREAD

**Issue by santigil** [sparkle-project/Sparkle#672]
When setting SUAllowsAutomaticUpdates to NO, the SUUpdaterAlert view tries to hide the checkbox using a NSLayoutConstraint.

We then get the following:
```*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:]: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs'```

It seems only the English xib has the proper outlets connected (releaseNotesContainerView and automaticallyInstallUpdatesButton in this case). The descriptionField outlet is also misconfigured.

**Comment by pornel** [comment]
To fix this I think we can re-generate all non-English XIB files from the English one. It's done with ibtool --export-strings-file and --import-strings-file

**Comment by zorgiepoo** [comment]
I can reproduce this now. We should fix this; it's a regression.

**Comment by wxiaoguang** [comment]
Would you consider about this issue #652 ? 

It seems that only English xib/strings are correct.

Other languages often have problems:
1. bad outlet references (eg: bad "description/descriptionField" references in SUUpdateAlert.xib) 
2. incorrect translations & out-dated translations

cocoa's multi-language processor with xib is really valueless. I think using NSLocalizedString to load translations from string files is a good choice for Sparkle, and the translations should be easy to be updated.
