### ISSUE TITLE
Autoupdate.app keeps asking for permissions [El Capitan]

### ISSUE THREAD

**Issue by rudyyroman** [sparkle-project/Sparkle#677]
It keeps bugging me, though I'm an admin and RB App checker says it is signed by me. And yet it doesn't do that on my another mac(admin user, El Capitan as well). Do you guys have any idea why it might be happening ? Any help would be very much appreciated.

**Comment by pornel** [comment]
Asking for permission is not related to code signing. It's dependent on write permissions of the app being updated. See if `chmod -R a+rwX the.app` fixes it.

**Comment by rudyyroman** [comment]
Hmm, it didn't fix it. Howerver I've been testing on other people's mac and it seems to be an issue solely on my mac. Looks like it's offtopic discussing here. 
Thanks for reply!
