### ISSUE TITLE
Pass Sparkle's guess for the best update to -updater:bestValidUpdateInAppcast

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#68]
_**dwood (dwood-karelia)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/264149) on' 2008-09-02:*

Some clients might want to perform logic for choosing an update based on
what Sparkle's guess it. Or under some circumstance, it might want to
fall back to the default choice.

Original:

"Not sure how to reproduce this, but I had a user running Sparkle (1.5b4
or b5-ish) from an slightly older version, and he was being informed
that his version was the latest version.    But it wasn't.   I get
reports like this from time to time.

it would be useful to have a hidden user default to log exactly what
appcast URL Sparkle is using, so we could diagnose this if we get
reports from user.

I've been looking through the source and it _seems_ like most URL
requests are correctly using the 'ignoring cache' policy.  There is on
in SUBasicUpdateDriver that  should probably use the cache-policy
variation: requestWithURL:cachePolicy:timeoutInterval:
- (void)downloadUpdate
  {
  download = [[NSURLDownload alloc] initWithRequest:[NSURLRequest requestWithURL:[updateItem fileURL]] delegate:self];  
  }

Sorry if this report seems to ramble -- mostly I'm  just trying to diagnose issues of the app thinking it's up to date when it really isn't."

**Comment by zorgiepoo** [comment]
This could be useful but I don't like expanding on this API which we try to discourage in most cases.
