### ISSUE TITLE
CocoaPod outdated?

### ISSUE THREAD

**Issue by mildm8nnered** [sparkle-project/Sparkle#682]
The CocoaPod link points to 1.11.0, but the latest stable version is 1.11.1

Any idea when this will be updated?

Alternatively, is there a straightforward way for us to build the CocoaPod locally?

**Comment by pornel** [comment]
@jakepetroules I keep forgetting to update the coocapod. I don't know what's the procedure for that - can you give me pointers?

**Comment by jakepetroules** [comment]
Very easy:

* Update version number on Podfile.spec
- $ cd <Sparkle repo>
- $ pod spec lint
- $ pod trunk push Sparkle.podspec

@pornel I need to add you as an owner to allow you to push updates. Can you please register a CocoaPods account (`pod trunk register`) and I'll add you? The @pornel.net address, I assume. I'll let you do the 1.11.1 release so you can make sure everything works.

**Comment by kainjow** [comment]
Maybe that should be a Makefile target?

**Comment by pornel** [comment]
I've registered

**Comment by pornel** [comment]
Released
