### ISSUE TITLE
An error occurred while relaunching <APP>. Couldn't find the relauncher

### ISSUE THREAD

**Issue by SilentChris** [sparkle-project/Sparkle#687]
Background:
 * Current version of the app uses a custom build of Sparkle (from commit 0ed83cf I believe, so after v1.5b6 but before v1.6)
 * The app updates fine on OSX 10.9, 10.10, and 10.11 (not changing Sparkle)
 * We are trying to update to a new custom build of Sparkle to get the latest-and-greatest as well as add some app-specific update features. Ideally, it would be based off one of the most recent release versions (1.11.1 or 1.12.0b1)

Unfortunately, whenever I try to update from a version of the app using the old Sparkle to a version built with a newer version of Sparkle, I get the following errors in the log:

```Sparkle Error: An error occurred while relaunching MyApp, but the new version will be available next time you run MyApp.```
```Sparkle Error (continued): Couldn't find the relauncher (expected to find it at /Users/myusername/Library/Application Support/MyApp)```

I've watched that directory as the update was taking place and it seems there is no difference between an update that fails (new Sparkle) and an update that succeed (unchanged/old Sparkle). Both of them extract the app to `/Users/myusername/Library/Application Support/MyApp/MyApp <build#>/` which contains both `MyApp.zip` and an unzipped `MyApp`

According to the code, it spits out that error when it can't find the relaunching tool. I initially suspected that there was something missing in the extraction directory, but considering that it has the same structure when an update *does* succeed, I'm not sure what to make of it.

Does anyone have any idea what could be going wrong or how to fix this issue? Does the relaunching tool get placed in some other directory not indicated by the log?

**Comment by pornel** [comment]
it looks like `finish_installation.app` is missing from the old app's Sparkle bundle's Resources.

If it's there, then it may be a bug where OS X finds newer Sparkle.bundle and uses it instead of the old one. Try compiling the new Sparkle with a different bundle ID.

**Comment by steveshepard** [comment]
I'm seeing this too. It does appear to be a bug in 10.11.1. In 1.5,

`- (void)installWithToolAndRelaunch:(BOOL)relaunch`

calls

`NSString *relaunchPathToCopy = [SPARKLE_BUNDLE pathForResource:@"finish_installation" ofType:@"app"];`

SPARKLE_BUNDLE is defined as follows:

`
#define SPARKLE_BUNDLE [NSBundle bundleWithIdentifier:@"org.andymatuschak.Sparkle"]
`

which returns the path to the newer, just created Sparkle.bundle. In my case:

`11/25/15 8:30:30.281 PM Storyist[20472]: SPARKLE_BUNDLE is NSBundle </Users/steve/Library/Application Support/Storyist/Storyist 3246/Storyist.app/Contents/Frameworks/Sparkle.framework/Versions/A> `

So I guess we either do as @pornel suggests and change the bundle identifier or ship a copy of finish_installation.app with 1.6.

-Steve

**Comment by pornel** [comment]
@SilentChris let me know if change of bundle id or adding finish_installation.app to the new Sparkle bundle fixes it for you.

I wonder if we need to do include such fix by default for everyone.

**Comment by SilentChris** [comment]
@pornel I changed the bundle ID and it seems to have solved the issue on 10.11 \o/

I wasn't sure exactly how to add finish_installation.app to the framework (building from the 1.12.0b1 tag), so I can't speak as to whether that works as well. I'm not sure which is the most "correct" fix.

I could roll with the bundle ID change for now, but would that limit me to needing to use a custom build if I ever wanted to update the framework in the future?

Thanks for the swift replies btw!

**Comment by steveshepard** [comment]
Changing the bundle id worked for me.

-Steve

**Comment by pornel** [comment]
Sparkle 1.11+ is immune to the problem (fixed in #571), so the workaround is only needed for upgrading from older versions. Once all your users are on version with Sparkle 1.11 or later, you can change the bundle ID back to default.

**Comment by jrhodes** [comment]
Hit this as well. My shipped version of the app was using a Sparkle version older than 1.11. The new version of the app was using 1.11. Installs failed on 10.11, but worked on 10.10.

Changing the framework's bundle ID to something unique like "org.andymatuschak.Sparkle1" worked for me too.
