### ISSUE TITLE
Is DSA mandatory?

### ISSUE THREAD

**Issue by devmod** [sparkle-project/Sparkle#691]
We are serving the code-signed app via HTTPS and the update fails due to no DSA signature. I had the impression that the signature was not mandatory- is that correct?  

Sparkle: There is no DSA signature to check
Sparkle: DSA signature validation of the package failed. The update will be rejected.

Thanks

**Comment by pornel** [comment]
For `.pkg` updates it's mandatory, since we have no other way to verify them.

We can only check Apple code signing on an `.app` bundle, but we can't get the bundle from a `.pkg` without allowing potentially-malicious installer scripts to run.

**Comment by pornel** [comment]
I've added longer error message in db3c9cb9c5b6a5d7334ef51423a6695c8ab82408

**Comment by devmod** [comment]
ohhh understood- Thanks!
