### ISSUE TITLE
System profile vs anonymity

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#697]
The "system profile" that Sparkle asks for permission to send contains:
- OS version
- OS language
- Mac Model
- CPU cores & frequency
- Memory

Safari sends with every HTTP request:
- OS version (in user-agent)
- OS language (in accept-language)

CFNetwork (e.g. helpd) also sends Mac Model in user-agent, from which range of possible CPUs and minimum amount of memory can be deduced.

So I wonder:
1. Do users still consider OS version and language a private information that should be hidden in updates? Can we send the same information as Safari by default?
2. Do users still consider CPU type and amount of memory a private information that should be hidden in updates? 
3. What is the purpose of hiding Mac Model and CPU/memory information from the update server? What creepy and nefarious things this information enables?

**Comment by zorgiepoo** [comment]
I think our current model is fine and I think what Apple sends by default nowadays has reduced (but I'm not sure of actual details). In 2.x we even have APIs for limiting the amount of info we collect/compute.
