### ISSUE TITLE
Can Sparkle be used to update complete folder contents?

### ISSUE THREAD

**Issue by aclight** [sparkle-project/Sparkle#698]
Our application is currently distributed as part of a folder containing the application bundle itself as well as lots of support files. To install, the user opens the .dmg file and drags the entire folder into /Applications.

    My Application Folder/
      My Application.app
      My Application64.app
      Help Files/
      Example Files/
      ...

The application comes in both a 32 and 64-bit version. I realize that the current version of Sparkle only supports 64-bit apps, so we would only integrate Sparkle in to the 64-bit version of our application.

As I understand it, Sparkle wouldn't support this use case, but I want to make sure before I rule it out since otherwise it looks like it would be great to use.

I realize that this is not a very Mac-like way to distribute an application these days, but the application has been around more than 20 years and putting all of the support files within the application bundle is not an appealing option at the moment.

Thanks.

**Comment by pornel** [comment]
You can send .pkg installer as an update, and make the installer do whatever you want.
