### ISSUE TITLE
Feature request: preserve app file label color

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#70]
_**Rob Lewis (rob51)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/323218) on' 2009-01-30:*

I'm a user, not a developer. But I know that many of my apps use
Sparkle.

I've been trying to get ready to clean out my Applications folder of
apps I no longer use. Step 1 is to color each app that I DO use with a
green label. So after a while, I'll be able to see which apps are
candidates for the trash (the ones that aren't green).

But I'm foiled by Sparkle, because every time I update an app with it, I
lose the label color.

Is there any way Sparkle could preserve this and apply it to the new
version?

Thanks.

**Comment by zorgiepoo** [comment]
I think the ideal way is to use `-[NSFileManager replaceItemAtURL:withItemAtURL:backupItemName:options:resultingItemURL:error` to preserve the original attributes, however the last time I've tested it, I found it a little buggy using it over network shares. We may need to not move the old version to the trash as well (#827).

**Comment by zorgiepoo** [comment]
We've had some workaround for this.
