### ISSUE TITLE
Implementing bestValidUpdateInAppcast can leave you without a nonDeltaUpdateItem to fall back on

### ISSUE THREAD

**Issue by santigil** [sparkle-project/Sparkle#700]
If the host implements the following method:
`- (SUAppcastItem *)bestValidUpdateInAppcast:(SUAppcast *)appcast forUpdater:(SUUpdater *)updater;`

And they return a delta update that eventually fails, there is no nonDeltaUpdateItem to fall back on, nor is there a way for the host to choose another item, therefore the update fails entirely.

Is this intended? 
Should nonDeltaUpdateItem in SUBasicUpdateDriver be set regardless of the delegate call?
Should there be a way for the delegate to provide another SUAppcastItem to fall back to?

**Comment by pornel** [comment]
Looks like an omission. I see a solution that would make it "just work": if a delta update fails, remove it from the list of available updates in the appcast, and ask the delegate again.

**Comment by santigil** [comment]
The proposed looks good to me, setting up for the delta and nondelta item from the delegate at the beginning.

**Comment by pornel** [comment]
Great!
