### ISSUE TITLE
How to check for an update on behalf of another app bundle?

### ISSUE THREAD

**Issue by JamesBucanek** [sparkle-project/Sparkle#705]
Greetings,

I've been using Sparkle since ... forever. It's an unbelievably useful product, and I wanted to just take a moment to say what a pleasure it has been to use and how much value it's added to my own product.

Now on to the questions/issues: I want one app (an LSUIElement agent app) to passively check to see if its main app (a Cocoa app that has both the Sparkle.framework and the embedded agent app) needs to be updated.

My application is a backup utility. It installs a bunch of system stuff and runs, more or less, unattended. This means that when everything is working as it should, the main app bundle might not be launched for weeks, even months, at a time. I want the UI agent app (that runs whenever the user is logged in) to periodically check to see if there's an update available and then nudge the user to open the main app (so it can update itself).

Here's what I've always done, but it doesn't appear to be working in the current version of Sparkle (1.13.0).
1. The agent app locates its app bundle.
2. The agent app is embedded in the main app, so it walks up the directories to find the main app's bundle.
3. The agent app locates and loads the Sparkle.framework in the main app's bundle.
4. Create an SUUpdater using [SUUpdaterClass updaterForBundle:mainAppBundle].
5. About twice a day, the agent app runs this code (approx):

```
if (sparkleUpdater.automaticallyChecksForUpdates) {
    NSDate* lastCheck = sparkleUpdater.lastUpdateCheckDate;
    NSTimeInterval checkInterval = sparkleUpdater.updateCheckInterval;
    if ( (lastCheck.timeIntervalSinceNow+checkInterval) < 0 ) {
        // The time for the next check is now in the past; time to check again
        [sparkleUpdater checkForUpdateInformation];
        // ... wait for -updater:didFindValidUpdate: or -updateDidNotFindUpdate:
```

This used to work, but now it doesn't and I'm not sure why. What happens is that the lastUpdate+checkInterval time is always in the future. The next time it checks, the lastUpdate time has changed so the combination is again, in the future. The end result is that the code never calls -checkForUpdateInformation. (I suspect that SUUpdater is probably running in the background checking for updates, but I'm not getting notified, nor is it updating anything, so nothing ever happens.)

Here are my questions:
(a) Should this work? If yes, any ideas of what I'm doing wrong?
(b) Is there a better/correct way to accomplish this?

**Comment by pornel** [comment]
It sounds like a good use case, and if it used to work, then we should fix it so it continues to work.

Can you try with older versions of Sparkle to narrow down which version broke this?

Apart from the `lastUpdateCheckDate`, does `checkForUpdateInformation` work? If so, as a workaround, you could ignore the interval check since you control a timer yourself anyway.

If only the `lastUpdateCheckDate` is wrong, then it might be because for some reason Sparkle is unable to save preferences.

**Comment by JamesBucanek** [comment]
As I dug into this, I found the problem—and it's been broken for some time. I suspect it broke when Sparkle was refactored to use `SUUpdateDriver` classes.

What I didn't mention earlier is that my delegate also implements `-updaterMayCheckForUpdates:` which always returned NO in order to prevent regularly scheduled updates from being attempted. This ultimately defeated my entire plan because all checks in the latest framework go through `-[SUUpdater checkForUpdatesWithDriver:]` and `-updaterMayCheckForUpdates:`. So I would request a version check with `-checkForUpdateInformation`, and then immediately deny the request. :(

I've got it working now, but it's a bit of a kludge, so I have some suggestions afterwards on ways to address this.

My solution is to not use my own timer or peek at the last update time, but just let `SUUpdater` do it's thing. When my delegate receives `-updaterMayCheckForUpdates:`, the code returns NO (to block the Sparkle initiated update), but then queues up a `-checkForUpdateInformation` that it allows. Here's the code (if you're sensitive to ugly code, you might want to cover your eyes):
````
@interface MonitorSparkleUpdateController : NSObject<SUUpdaterDelegate>
{
    ...
    BOOL            allowNextUpdateCheck;
    BOOL            passiveUpdateCheckQueued;
}

...

- (BOOL)updaterMayCheckForUpdates:(SUUpdater*)updater
{
    // Received when Sparkle decides it's time to check for an update.
    if (allowNextUpdateCheck)
        {
        // One shot: Allow this check, presumably because it was intiated by -checkForUpdateInformation
        allowNextUpdateCheck = NO;
        return YES;
        }
    
    // Update checks are not allowed.
    // Assume the Sparkle framework is periodically requesting a check.
    // Block this update request, but queue a passive check that will be allowed to run.
    if (!passiveUpdateCheckQueued)
        {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3*NSEC_PER_SEC)),dispatch_get_main_queue(), ^{
            // Begin a "probing" update that just determines what update is available and then stops
            allowNextUpdateCheck = YES;
            [updater checkForUpdateInformation];
            // The result will eventually send either -updater:didFindValidUpdate: or -updaterDidNotFindUpdate: ...
            passiveUpdateCheckQueued = NO;
            });
        passiveUpdateCheckQueued = YES;
        }

    return NO;
}
````
So far, it's working pretty well.

Thinking about this issue, it occurred to me that what I really need is a way to determine what *kind* of update is being performed, so that the delegate could distinguish which types to allow.

First, I suggest adding a symbolic "update classification" that would be defined by `SUUpdateDriver`:
````
typedef enum {
    SUUpdateCheckNone = 0,  // nil driver
    SUUpdateCheckScheduled,
    SUUpdateCheckUserInitiated,
    SUUpdateCheckAutomatic,
    SUUpdateCheckProbing,
} SUUpdateCheckType;

@interface SUUpdateDriver : NSObject <NSURLDownloadDelegate>
@property (readonly) SUUpdateCheckType type;
...
````
Then, I'd suggest one of two methods for exposing this information to the delegate. The first would be to define an alternate, more nuanced, delegate message:
````
@protocol SUUpdaterDelegate
@optional
- (BOOL)updaterMayCheckForUpdates:(SUUpdater*)updater;
- (BOOL)updater:(SUUpdater*)updater mayCheckForUpdatesOfType:(SUUpdateCheckType)checkType;
...

@implementation SUUpdater
...
- (void)checkForUpdatesWithDriver:(SUUpdateDriver *)driver
{
    ...
    // If the delegate implements either -updater:mayCheckForUpdatesOfType: or -updaterMayCheckForUpdates:, allow it to decide
    BOOL allow = YES;
    if ([self.delegate respondsToSelector: @selector(updater:mayCheckForUpdatesOfType:)])
        allow = [self.delegate updater:self mayCheckForUpdatesOfType:driver.type];
    else if ([self.delegate respondsToSelector: @selector(updaterMayCheckForUpdates:)])
        allow = [self.delegate updaterMayCheckForUpdates: self];
    if (!allow)
    {
        [self scheduleNextUpdateCheck];
        return;
    }
````
The delegate could implement the traditional `-updaterMayCheckForUpdates:` if it doesn't distinguish between update types, or `-updater:mayCheckForUpdatesOfType:` if it needs to.

Alternatively, the type of the active update driver could be exposed by `SUUpdater`:
````
@interface SUUpdater : NSObject
@property (readonly) SUUpdateCheckType checkType;
...

@implementation SUUpdater
- (SUUpdateCheckType)checkType { return self.driver.type; }
````
The delegate could then, for example, query `updater.checkType` to allow probing checks but disallow other types:
````
- (BOOL)updaterMayCheckForUpdates:(SUUpdater*)updater
{
    return ( updater.checkType==SUUpdateCheckProbing );
}
````

And there's probably a third, better, solution...

**Comment by pornel** [comment]
Thanks for investigating this. If you're responding `NO` to `updaterMayCheckForUpdates:` then I think Sparkle is right to bail out and not update the last check date.

Adding `checkType` seems like an OK solution, but I'd like to understand your usecase better.

I don't understand why you want to prevent regularly scheduled updates. Why not call `[updater checkForUpdateInformation];` unconditionally? Are you only trying to avoid extra server requests?

**Comment by JamesBucanek** [comment]
*Thanks for investigating this. If you're responding NO to `updaterMayCheckForUpdates:` then I think Sparkle is right to bail out and not update the last check date.*

Actually, the opposite happens. The code in `-[SUUpdater checkForUpdatesWithDriver:]` updates the last check date and *then* sends the delegate the `-updateMayCheckForUpdates:` message. This makes sense. If the delegate prohibits the check, Sparkle will check again at the next scheduled time.

*Adding `checkType` seems like an OK solution, but I'd like to understand your usecase better.*

Again, it's kind of odd scenario. I want to create a situation where the delegate blocks Sparkle from performing an update, but still lets it determine when the next check should occur and also allow `-checkForUpdateInformation` to work.

*I don't understand why you want to prevent regularly scheduled updates. Why not call `[updater checkForUpdateInformation];` unconditionally? Are you only trying to avoid extra server requests?*

Because I'm running Sparkle in a _different app_ than the one that needs to be updated. I've manually loaded the Sparkle framework and pointed it at the bundle of the client app that Sparkle will ultimately update. This means that Sparkle is using the client app's bundle, bundle identifier, and preferences, but it's not running in the app that needs to be updated. So I'm really trying to lobotomize Sparkle at runtime so it does everything it normally does (based on the user's preferences) but stopping just short of actually performing an update, all so I can detect when an update is available and prompt the user with a subtle "There's a new version of your app available..." message in my menubar UI. This prompt has a button that launches the client app, which will load Sparkle again, and (presumably) perform a normal update.

**Comment by JamesBucanek** [comment]
Considering other solutions, I know that there are lots of other delegate messages that get sent as the process proceeds (`-updater:didFinishLoadingAppcast:`, `-updater:didFindValidUpdate:`, and so on), but none of those provide a return value for stopping the process at that point.

Maybe a solution would be a new delegate message that gives the delegate a chance to bail on the actual update? Something like the following method, send just after the candidate item has been determined, but before the user is prompted to update or the update begins to download (in automatic mode).
````
@optional
- (BOOL)updater:(SUUpdater*)updater shouldUpdateToItem:(SUAppcastItem *)item;
````

**Comment by zorgiepoo** [comment]
Not sure I understand all the complexity done here to lobotomize Sparkle ;), but I wrote a [fork](https://github.com/zorgiepoo/Sparkle) that's designed to make remote updating (eg: sparkle-cli) and custom UI (a menu bar app in this case?) more natural.

**Comment by zorgiepoo** [comment]
2.x supports more updating on behalf another app, if case isn't addressed and still relevant re-open / file new issue.
