### ISSUE TITLE
Previous versions are not moved to trash

### ISSUE THREAD

**Issue by ababak** [sparkle-project/Sparkle#707]
I have a problem that any application that uses Sparkle framework is leaving previous versions with build numbers in brackets. Like this:

drwxrwxr-x+ 193 root   admin   6562 Jan  7 13:54 .
dr-xr-xr-x   32 root   admin   1156 Jan  6 08:48 ..
drwxr-xr-x@   3 babak  staff    102 Jan  1 07:09 Default Folder X (131).app
drwxr-xr-x@   3 babak  staff    102 Jan  5 02:26 Default Folder X (137).app
drwxr-xr-x@   3 babak  staff    102 Jan  7 11:30 Default Folder X.app

No errors in console, just I have to clean up my Applications folder from time to time.

I am using El Capitan 10.11.2 (15C50), not a clean install, just updated from 10.10. My user has admin privileges. Under freshly created admin user it works fine.

I'll be glad to make deep testing to help identify and fix this annoying problem. Thanks.

**Comment by pornel** [comment]
Default Folder X uses Sparkle v1.5, which is very out of date. Please ask them to update to 1.13.

**Comment by gotow** [comment]
Actually, he's using the beta of Default Folder X 5, which uses Sparkle 1.11. I'll pull 1.13 after the 5.0 release (it's too late in the beta cycle to introduce a major change). Is this issue something that's been fixed in the "Rewritten file operations for updating an app" in 1.12?

**Comment by pornel** [comment]
Oh, that's great. In that case could you try running an update and check `~/Library/Logs/SparkleUpdateLog.log` or Console.app for any errors?

**Comment by ababak** [comment]
The SparkleUpdateLog.log has been overwritten by Vectoraster update (it uses 1.8.0 framework, an old application was not deleted as well):
2016-01-07 15:19:55 +0000: ===== Vectoraster =====
2016-01-07 15:20:07 +0000: Extracting /Volumes/Macintosh/Users/babak/Library/Application Support/Vectoraster/.Sparkle/Vectoraster 6.2.5/Vectoraster6.2.5.app.zip using 'ditto -x -k - "$DESTINATION"'
2016-01-07 15:20:11 +0000: mdimporting

Here's the system log I've sent to Jon:
Jan  7 12:55:42 babak-pro Default Folder X[588]: Sparkle: ===== Default Folder X =====
Jan  7 12:55:42 babak-pro Default Folder X[588]: Sparkle: Extracting /Volumes/Macintosh/Users/babak/Library/Caches/com.stclairsoft.DefaultFolderX5/Sparkle/Default Folder X 141/DefaultFolderX-5.0b18.dmg as a DMG
Jan  7 12:55:43 babak-pro kernel[0]: hfs: mounted Default Folder X 5.0b18 on device disk4
Jan  7 12:55:43 babak-pro mds[73]: (Volume.Normal:2464) volume:0x7fb1bd063000 ********** Bootstrapped Creating a default store:1 SpotLoc:(null) SpotVerLoc:(null) occlude:0 /Volumes/DEC50425-9988-46A7-886E-408561DB6AA7
Jan  7 12:55:43 babak-pro 2BUA8C4S2C.com.agilebits.onepassword4-helper[1140]: 600003 [HELPER:(Main Thread):<OPHelperAppDelegate: 0x7f8558c051a0>] S workspaceDidMount: | workspaceDidMount
Jan  7 12:55:44 babak-pro diskimages-helper[2949]: *** -[NSMachPort handlePortMessage:]: dropping incoming DO message because the connection is invalid
Jan  7 12:55:44 babak-pro Default Folder X[588]: Sparkle: copyItemAtPath:/Volumes/DEC50425-9988-46A7-886E-408561DB6AA7/.background toPath:/Volumes/Macintosh/Users/babak/Library/Caches/com.stclairsoft.DefaultFolderX5/Sparkle/Default Folder X 141/.background
Jan  7 12:55:44 babak-pro Default Folder X[588]: Sparkle: copyItemAtPath:/Volumes/DEC50425-9988-46A7-886E-408561DB6AA7/.DS_Store toPath:/Volumes/Macintosh/Users/babak/Library/Caches/com.stclairsoft.DefaultFolderX5/Sparkle/Default Folder X 141/.DS_Store
Jan  7 12:55:44 babak-pro Default Folder X[588]: Sparkle: copyItemAtPath:/Volumes/DEC50425-9988-46A7-886E-408561DB6AA7/.fseventsd toPath:/Volumes/Macintosh/Users/babak/Library/Caches/com.stclairsoft.DefaultFolderX5/Sparkle/Default Folder X 141/.fseventsd
Jan  7 12:55:44 babak-pro Default Folder X[588]: Sparkle: copyItemAtPath:/Volumes/DEC50425-9988-46A7-886E-408561DB6AA7/Applications toPath:/Volumes/Macintosh/Users/babak/Library/Caches/com.stclairsoft.DefaultFolderX5/Sparkle/Default Folder X 141/Applications
Jan  7 12:55:44 babak-pro Default Folder X[588]: Sparkle: copyItemAtPath:/Volumes/DEC50425-9988-46A7-886E-408561DB6AA7/Default Folder X.app toPath:/Volumes/Macintosh/Users/babak/Library/Caches/com.stclairsoft.DefaultFolderX5/Sparkle/Default Folder X 141/Default Folder X.app
Jan  7 12:55:44 babak-pro Default Folder X[588]: Sparkle: copyItemAtPath:/Volumes/DEC50425-9988-46A7-886E-408561DB6AA7/Read Me.rtfd toPath:/Volumes/Macintosh/Users/babak/Library/Caches/com.stclairsoft.DefaultFolderX5/Sparkle/Default Folder X 141/Read Me.rtfd
Jan  7 12:55:44 babak-pro mdworker[2305]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Jan  7 12:55:44 babak-pro mdworker[2306]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Jan  7 12:55:44 babak-pro mdworker[2313]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Jan  7 12:55:44 babak-pro mdworker[2327]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Jan  7 12:55:44 babak-pro mdworker[2328]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Jan  7 12:55:44 babak-pro mdworker[2499]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Jan  7 12:55:44 babak-pro mdworker[2554]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Jan  7 12:55:44 babak-pro mdworker[2940]: (ImportBailout.Error:1325) Asked to exit for Diskarb
Jan  7 12:55:44 babak-pro kernel[0]: hfs: unmount initiated on Default Folder X 5.0b18 on device disk4
Jan  7 13:08:54 babak-pro Default Folder X[588]: <AXFileDialog: 0x7f9226b03300> dealloc
Jan  7 13:08:54 babak-pro Default Folder X[588]: Unreleased observers:
Jan  7 13:08:57 babak-pro Autoupdate[2994]: Sparkle: ===== Autoupdate =====
Jan  7 13:08:57 babak-pro Autoupdate[2994]: Sparkle: mdimporting

**Comment by pornel** [comment]
Thanks for the log. Unfortunately, it doesn't reveal what could be causing this.

@gotow Yes, 0.12+ has a much improved logic for replacing app bundles, so it's possible that it solves this issue.

**Comment by ababak** [comment]
I'd like to mention that Evernote that uses Sparkle Framework 1.12.0 was updated from 6.3 to 6.4 without leaving the old application! It is successfully moved to trash.

**Comment by ababak** [comment]
All the applications that switch to new framework versions seem to update fine.

Thanks for taking your time.

Regards,
Andrey.
