### ISSUE TITLE
sparkle unit tests project failed to build

### ISSUE THREAD

**Issue by dhs227** [sparkle-project/Sparkle#708]
With Xcode 7.2, OS X 10.11.2. After convert to XCTest, the error message says:
```<XCTest/XCTest.h> file not found ```

**Comment by pornel** [comment]
Why do you convert to XCTest? That shouldn't be necessary. Just run the tests (cmd+U).

**Comment by dhs227** [comment]
Sorry I didn't describe the issue precisely. I did pulled the source tried to make a clean build but reproduced this error message with SUVersionComparisonTest.m:

```<XCTest/XCTest.h> file not found

**Comment by pornel** [comment]
This header should be available out of the box. Do you use a recent version of Xcode?

**Comment by dhs227** [comment]
Yes, I am using Xcode 7.2 (7C68) with OS X 10.11.2

**Comment by dhs227** [comment]
I fixed this issue by adding an new empty unit test file. Issue closed.
