### ISSUE TITLE
Sparkle via CocoaPods, still needs a custom code sign build phase ?

### ISSUE THREAD

**Issue by vincedev** [sparkle-project/Sparkle#709]
I use Xcode 7.2 (7C68), and Sparkle is added to my project via CocoaPods 0.39.0.
I followed [instructions](http://sparkle-project.org/documentation/cocoapods/) to sign Sparkle framework.

Recently (after updating Xcode I suppose), on first build after a clean, build log outputs errors when it comes to sign Sparkle (it complains it doesn't find Sparkle). But build ultimately succeed.
Subsequent builds don't produce those errors.

In the Podfile, Sparkle is added via this simple line :

`pod 'Sparkle', :configurations => ['Debug', 'Release']`

No big deal here.. We get latest Sparkle.

I tried verifying code signature on the command line using `codesign --verify --deep --verbose=2 MyApp.app`
After first build app signature is valid (I guess Xcode handles this properly).
Running the same command after another build reveals a broken signature :

```
MyApp.app: nested code is modified or invalid
file modified: /Users/vince/Library/Developer/Xcode/DerivedData/MyApp-bvceztplqcxqntaxihebrdyicjcq/Build/Products/Debug/MyApp.app/Contents/Frameworks/Sparkle.framework
```

Strangely, removing the custom Code Sign build phase altogether, just works. The build log no longer outputs errors, neither on first build, nor on subsequent builds, and signature is always valid.

Does importing Sparkle via CocoaPods still requires this custom build phase ?

**Comment by zorgiepoo** [comment]
To be honest, the cocoa pod instructions linked there confuse me. I don't have a Mac on me right now to investigate but here are my thoughts:

1. The Sparkle framework need not be signed if the app is not signed. Signing the app is highly encouraged of course but not required.

2. Signing the framework should be left up to the project using Sparkle, and should be left to Xcode and not a custom run script. Its not that cocoa pods doesn't handle this, but probably that it *shouldn't* handle it.

3. The article referenced from our documentation page is old and therefore not in my opinion trustworthy. Possibly it was written before Xcode had a 'Code Sign on Copy' option for copying frameworks.

**Comment by zorgiepoo** [comment]
> Does importing Sparkle via CocoaPods still requires this custom build phase ?

So I quickly created a sample project, created a Podfile, and executed 'pod install' and as far as I can see, no, everything seems to be handled properly.

We really shouldn't be suggesting a custom run script if this is the case.

**Comment by vincedev** [comment]
@zorgiepoo : Thank you for experimenting this.
I also had similar results, code signing by Xcode alone works as expected, no custom build phase required.

In my case, the application needs to be sandboxed, so no choice but sign the app :)
And that custom build phase broke the signature, and thus the app wasn't sandboxed.

As for suggesting the build phase, I wonder if it depends on the Xcode version used (and/or CocoaPods ?). I remember having issues with code signing at first, that were resolved by adding it.

Anyway, my current configuration doesn't need it anymore :)
Again, thank you for commenting and testing.
