### ISSUE TITLE
Where is the sparkle.framework located?

### ISSUE THREAD

**Issue by dhs227** [sparkle-project/Sparkle#714]
Xcode said the build was successful but I couldn't locate where the sparkle.framework is. 

I am asking because Sparkle doc says the first step of adding the sparkle framework to my project is to drag Sparkle.framework into the Frameworks folder of your Xcode project...

**Comment by pornel** [comment]
If you're building a custom one, it's in your build products directory. You can find it in Xcode's sidebar under Products.

[See how ImageOptim integrates it](https://github.com/pornel/ImageOptim).
