### ISSUE TITLE
Does not work with Unity3d applications

### ISSUE THREAD

**Issue by greenjeffreym** [sparkle-project/Sparkle#718]
I'm trying to get sparkle to update a Unity game. Unity does not create an xcode project for the mac standalone app so I could not set the set “Runpath Search Paths” to @loader_path/../Frameworks. 

Instead I created a native unity plugin for my app and put sparkle in the plugin bundle. After following the instructions for a bundle I pointed my appcast to an update pkg file that contained my entire .app bundle. When sparkle ran the updater, it only updated my plugin, not the entire app. How is this possible when the pkg contains the full app?

**Comment by SevenBits** [comment]
@greenjeffreym Sparkle updates the package it's contained in. If Sparkle is within a bundle, then you need to configure it to update the parent app instead of the bundle.

**Comment by hexuallyactive** [comment]
@greenjeffreym were you able to make this work reliably in a Unity game?  I've been looking into this as well and have been struggling a little on the plugin I'm trying to author - any pointers?
