### ISSUE TITLE
Sparkle Website https

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#727]
https should probably be set up for the main website. [Let's Encrypt](https://letsencrypt.org) is one such possibility but I'll leave that decision up to someone else.

**Comment by reedloden** [comment]
Let's Encrypt doesn't help when GitHub Pages is being used (as it is in this case).

For a free and simple option, CloudFlare could be used to front the domain and then just pass through to https://sparkle-project.github.io transparently. That doesn't require anything separate to be done to host the website or proxy the SSL/TLS cert (such as you would need to do with Let's Encrypt).

**Comment by jakepetroules** [comment]
Done. In future please open website related issues on the actual website repo (https://github.com/sparkle-project/sparkle-project.github.io)
