### ISSUE TITLE
Crash with "launch path not accessible"

### ISSUE THREAD

**Issue by Dejal** [sparkle-project/Sparkle#730]
Sparkle is having an exception in `-[SUBasicUpdateDriver installWithToolAndRelaunch:displayingUserInterface:]` with the exception "launch path not accessible".

Googling around, this seems to be a fairly common error, typically caused by incorrect permissions on the Autoupdate app.  But in my case, as far as I can tell the permissions are correct (executable).

This is in a sandboxed app.  The new version of the app is successfully extracted (within the sandbox container).

This was with Sparkle 1.8.  I've updated to the latest revision, but I'm hesitant to update my app until I understand this issue.  As it is, I'll have to tell my customers to manually update; I don't want to have to do that more than once.

Here's a crash report:

```
Date/Time:             2016-02-02 20:36:30.297 -0800
OS Version:            Mac OS X 10.11.3 (15D21)
Report Version:        11
Anonymous UUID:        E23B03A8-8EAA-3014-261A-0171B645591C


Time Awake Since Boot: 120000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Crashing on exception: launch path not accessible

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff99e30ae2 __exceptionPreprocess + 178
1   libobjc.A.dylib                     0x00007fff842b873c objc_exception_throw + 48
2   CoreFoundation                      0x00007fff99e3098d +[NSException raise:format:] + 205
3   Foundation                          0x00007fff95572492 -[NSConcreteTask launchWithDictionary:] + 476
4   Foundation                          0x00007fff95721764 +[NSTask launchedTaskWithLaunchPath:arguments:] + 194
5   Sparkle                             0x000000010cf8bebd -[SUBasicUpdateDriver installWithToolAndRelaunch:displayingUserInterface:] + 3307
6   Sparkle                             0x000000010cf99e1a -[SUUIBasedUpdateDriver installWithToolAndRelaunch:] + 261
7   libsystem_trace.dylib               0x00007fff9410a07a _os_activity_initiate + 75
8   AppKit                              0x00007fff8a4e351d -[NSApplication sendAction:to:from:] + 460
9   AppKit                              0x00007fff8a4f8486 -[NSControl sendAction:to:] + 86
10  AppKit                              0x00007fff8a4f83b0 __26-[NSCell _sendActionFrom:]_block_invoke + 131
...
```

Is there anything else that could cause this?  Any solution?

**Comment by pornel** [comment]
Does it happen with Sparkle 1.13 too? Older versions had a problem finding their own bundle, which could cause them to look for autoupdate.app in a wrong place.

Also, we don't support sandboxed apps. AFAIK when Sparkle works with a sandboxed app it necessarily has to create a backdoor in the sandbox.

**Comment by Dejal** [comment]
@pornel thanks for the reply.  I haven't tested 1.13 yet.

Sandboxed apps are quite common nowadays.  What do I need to do to make it work?

**Comment by pornel** [comment]
You may need to disable disable sandbox. Some people have reported that zip files work, but dmg files don't. Please note that Sparkle forks that are compatible with sandbox may not have the most recent security patches.

**Comment by Dejal** [comment]
I really don't want to disable the sandbox, as the app will be distributed both directly and via the Mac App Store, so I want the two editions as similar as possible.

I distribute via zip files.  Can you point me to a fork that is compatible with sandboxing; I'll try to figure out what's different and put that in my own fork off the latest version.

**Comment by pornel** [comment]
See yahooxpc branch in the repo. Be sure to merge 1.13.1 into it. More discussion in #363

**Comment by Dejal** [comment]
Thanks.  I tried using the yahooxpc branch, without merging from master, just to see if it works.  Unfortunately, it doesn't. 

Firstly there's a bug in the code so it doesn't use the XPC helper at all (maybe it intends the code to be used directly instead of as a framework?):

    BOOL useXPC = running10_7 && inSandbox &&
                  [[NSFileManager defaultManager] fileExistsAtPath: [sparkleBundle.bundlePath stringByAppendingPathComponent:[NSString stringWithFormat:@"Contents/XPCServices/%@.xpc", @(SPARKLE_SANDBOX_SERVICE_NAME)]]];

should be:

    BOOL useXPC = running10_7 && inSandbox &&
                  [[NSFileManager defaultManager] fileExistsAtPath: [sparkleBundle.bundlePath stringByAppendingPathComponent:[NSString stringWithFormat:@"Versions/Current/XPCServices/%@.xpc", @(SPARKLE_SANDBOX_SERVICE_NAME)]]];

But even fixing that, I get a quarantine error: "Autoupdate denied since it was quarantined by Time Out and created without user consent" and XPC helper crash (my app is named Time Out):

````
2016-02-05 16:39:11.765 Time Out[78796]: Sparkle: installWithToolAndRelaunch - using xpc=1
2016-02-05 16:39:12.000 kernel[0]: exec of /Users/dejal/Library/Containers/com.dejal.timeout/Data/Library/Application Support/Time Out/.Sparkle/Autoupdate.app/Contents/MacOS/Autoupdate denied since it was quarantined by Time Out and created without user consent, qtn-flags was 0x00000006
2016-02-05 16:39:12.014 org.sparkle-project.Sparkle.SandboxService[78883]: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Couldn't posix_spawn: error 1'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff9fedfae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8a36773c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9fedf98d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff9b621ef4 -[NSConcreteTask launchWithDictionary:] + 3134
	4   Foundation                          0x00007fff9b7d0764 +[NSTask launchedTaskWithLaunchPath:arguments:] + 194
	5   org.sparkle-project.Sparkle.SandboxService 0x0000000104c957a7 peer_event_handler + 1831
	6   org.sparkle-project.Sparkle.SandboxService 0x0000000104c95074 __event_handler_block_invoke + 36
	7   libxpc.dylib                        0x00007fff9dfba396 _xpc_connection_call_event_handler + 35
	8   libxpc.dylib                        0x00007fff9dfba00f _xpc_connection_mach_event + 2198
	9   libdispatch.dylib                   0x00007fff9a5c54ca _dispatch_client_callout4 + 9
	10  libdispatch.dylib                   0x00007fff9a5c593c _dispatch_mach_msg_invoke + 555
	11  libdispatch.dylib                   0x00007fff9a5c2134 _dispatch_queue_drain + 1207
	12  libdispatch.dylib                   0x00007fff9a5c4293 _dispatch_mach_invoke + 735
	13  libdispatch.dylib                   0x00007fff9a5bd33f _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00007fff9a5c11cf _dispatch_root_queue_drain + 1890
	15  libdispatch.dylib                   0x00007fff9a5c0a34 _dispatch_worker_thread3 + 91
	16  libsystem_pthread.dylib             0x00007fff98bf668f _pthread_wqthread + 1129
	17  libsystem_pthread.dylib             0x00007fff98bf4365 start_wqthread + 13
)
2016-02-05 16:39:12.014 Time Out[78796]: XPC XPCErrorDescription: Connection interrupted
2016-02-05 16:39:12.014 diagnosticd[175]: error evaluating process info - pid: 78883, puniqueid: 78883
2016-02-05 16:39:12.014 Time Out[78796]: XPC launch error
2016-02-05 16:39:12.014 com.apple.xpc.launchd[1]: (org.sparkle-project.Sparkle.SandboxService[78883]) Service exited due to signal: Abort trap: 6
2016-02-05 16:39:12.036 com.apple.xpc.launchd[1]: (com.apple.ReportCrash[78885]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
````

Any idea how to fix this?

**Comment by pornel** [comment]
Yahooxpc branch is super old and abandoned. Without merging from master it won't be usable.

**Comment by pornel** [comment]
Currently the best bet for XPC sparkle is: https://github.com/zorgiepoo/Sparkle/tree/ui-separation-and-xpc

**Comment by digitalmoksha** [comment]
@pornel is there any effort to move Sparkle to this new model?  It would be great to finally have a single branch that is fully secure and works both in sandboxed and non-sandboxed apps.

As always, thanks for the huge work (and many recent updates) you guys do...

**Comment by pornel** [comment]
Yes, we're working towards it.
