### ISSUE TITLE
Requiring DSA signatures over insecure HTTP (Code Signing only over HTTPS)

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#731]
I'm proposing removing ability to use _only_ Apple Code Signing as a method of verification when delivering applications over insecure HTTP. 

Apps using HTTP can still deliver updates signed with DSA. Without DSA apps will need to use HTTPS for the appcast and the update archive for Apple Code Signing to be accepted.

Reasons for the limitation:
- Code Signing verification increases attack surface area, because Sparkle has to decompress an untrusted archive first.
- Code Signing guarantees verification of developer identity, but it does not guarantee deep integrity check.
- HTTPS is not as burdensome as it was a decade ago. Modern TLS is fast, [HTTPS certificates are free](https://letsencrypt.org), and github pages offer free HTTPS hosting on github.io (and DSA signing remains an option for those stuck with insecure HTTP).
- Apple has deprecated insecure HTTP in the latest OS X/iOS, so we'd like to gradually move away from it too.

**Comment by SevenBits** [comment]
@pornel This seems like a good idea. It's time to start hammering the nails in the coffin of insecure HTTP.

**Comment by zorgiepoo** [comment]
Yeah we already deprecated it so we may as well remove supporting it. The alternative of removing it is simply requiring DSA everywhere but I suspect that may not go over well ;). Hope removing it is not tricky though.

**Comment by zorgiepoo** [comment]
Been done for while
