### ISSUE TITLE
[Question] Delaying call to `startUpdateCycle`

### ISSUE THREAD

**Issue by aprilnoren** [sparkle-project/Sparkle#734]
We currently have a fork of Sparkle that has been modified to expose the `startUpdateCycle` call and remove the current `performSelector` call of it in the `initForBundle` function.  We had found issues with it popping up while some of our things we still loading.

Is this functionality already available with some other options?  I see `resetUpdateCycle`, but not entirely sure how that works with things.

If not is this something other clients might be interested in for me to share it back?

Thanks.

**Comment by zorgiepoo** [comment]
Hm. An alternative solution without exposing that method may be to defer the instantiation for `SUUpdater`, which may mean to not stick it in a nib. This may mean a little glue to hook up the "Check for Updates" action & menu item validation, although it's the approach I personally prefer.

**Comment by aprilnoren** [comment]
Thanks, we no longer have this in the xib and init it when we call the `SUUpdater` shared instance call.  Closing this.
