### ISSUE TITLE
Sparkle does not update when using delegate updaterShouldRelaunchApplication

### ISSUE THREAD

**Issue by greenjeffreym** [sparkle-project/Sparkle#736]
For my app I have configured sparkle to update the application silently in the background without any user prompts on close by using the delegate:

- (void)updater:(SUUpdater *)updater willInstallUpdateOnQuit:(SUAppcastItem *)item immediateInstallationInvocation:(NSInvocation *)invocation;

So that it's not confusing to the user to am trying to tell sparkle to not relaunch the application after the update via this delegate:

- (BOOL)updaterShouldRelaunchApplication:(SUUpdater *)updater;

However if I return NO, Sparkle does not do the update at all. I would expect Sparkle to do the update, but not relaunch the application based on the name and documentation of this delegate.

**Comment by pornel** [comment]
Yeah, the name is misleading. If you return `NO`, then the update is aborted.

The reasoning for it is that replacing the bundle while the app is running can break the app in subtle ways — some resources may be cached, some open files can still see the old files, so when the app loads or runs anything from the bundle you don't know what you'll get.

If you enable automatic install Sparkle will download in the background without bothering the user and install when the app is quit.

**Comment by greenjeffreym** [comment]
I have enabled automatic install but Sparkle is not updating when the user quits for me without some added steps. I believe this is because I'm running a Unity3d application where Unity (or mono) is blocking whatever delegate Sparkle is listening for for the application to close. Unity does however provide a MonoBehavior for OnApplicationQuit(), in which I can invoke the NSInvocation passed in by the updater delegate I mentioned earlier. I have to explicitly invoke the update otherwise it doesn't happen for me in a Unity app. But I also need this to happen on the closing of the application, without any user prompts, and without relaunching the application.

**Comment by zorgiepoo** [comment]
Just want to note, as far as I recall, the automatic updates don't happen if the user doesn't have write permission to the app either because that currently would result in confused users (eg: non-admin users updating from /Applications/).
