### ISSUE TITLE
How about stripping binaries for release + get rid of localizations

### ISSUE THREAD

**Issue by sveinbjornt** [sparkle-project/Sparkle#738]
In the current official Sparkle release (Sparkle-1.13.1.tar.bz2), Sparkle.framework is 2.271.357 bytes in size.

Stripping the Sparkle and Autoupdate.app binaries (using strip -x) reduced their size as follows:

```
Sparkle: 466.940 --> 321.932 (-31%)
Autoupdate: 166.964 --> 145.132 (-13%)

Total resulting size is now 2.137.301 (-6%)
```

It so happens that I'm only supporting english localization for the project I'm working on so I got rid of the unneeded language lproj files:

```
Sparkle.framework with localizations removed: 757.637 (-67%)
```

So basically by stripping the binaries and getting rid of localization files (something which XCode does not automatically do when you add the framework and make a release), I was able to reduce the size of the Sparkle framework from about 2.3 MB to 750 KB, or by about two thirds.

Wouldn't it make sense to offer a slimmed down version of Sparkle?  Those extra 1.5 MB add up to a lot of unnecessary bandwidth which I think a lot of people are unnecessarily shipping with their apps.

This is true even if you account for the typical zip compression:

```
Original Sparkle zipped: 1.3 MB
Binary and localization-stripped Sparkle: 370KB
```

Anyway, just a thought from someone who cares about the size of software packages.

**Comment by pornel** [comment]
The list of languages supported varies, so it'd be ideal to have a tool that only removes languages that the host app doesn't have.

We're including symbols by default, because it improves crash reports. It's easier to strip during debug process than to add the symbols :)

If bandwidth is a problem, try Delta Updates.

**Comment by MaddTheSane** [comment]
Would .dSym bundles be a better choice for release builds?

**Comment by zorgiepoo** [comment]
I anticipate some of the size can be chopped off the day we can have a single nib for multiple languages..

**Comment by zorgiepoo** [comment]
I enable stripping of debug symbols recently (#2286) for the framework binary (other binaries were being stripped); I think it was a "bug" we weren't doing this honestly (it was stripped if you used a particular / not most common workflow of integrating Sparkle). For localizations, we ought to leave that up to the app.
