### ISSUE TITLE
Switching branches breaks Sparkle

### ISSUE THREAD

**Issue by derekharasen** [sparkle-project/Sparkle#739]
I just updated to the newest version of Sparkle, after about 2 years, and I get this message whenever I switch branches via Xcode:

'Sparkle.framework/Versions/A/Resources/SUStatus.nib/classes.nib' appears as both a file and a directory (-1)

At that point it deletes a bunch of files. Anybody have any ideas whats going on?

**Comment by pornel** [comment]
That looks like an old file. Delete it before compiling the new version.

**Comment by derekharasen** [comment]
Deleting it breaks sparkle (no longer updates the app). Its also from the newest framework, I deleted the old one out of the app first.

**Comment by pornel** [comment]
Oh, sorry. I've confused it with files in the source tree (where we use xibs and don't expect nib)
