### ISSUE TITLE
Maybe silly question from a non-developer

### ISSUE THREAD

**Issue by thotha** [sparkle-project/Sparkle#740]
What is the reason, that Sparkle will not be developed the way that it will install into /Library/Frameworks/ so any app which uses/needs it does use the most actual version available and also doesn't have to update itself every time a new Sparkle Framework Version is up for use?

**Comment by thotha** [comment]
To the developers of Sparkle.
Really think about my question.
Right now, out of my approx. 50 apps which use Sparkle Framework, I have now to contact approx 90% of them to ask them about this vulnerability if they still use HTTP instead of HTTPS.
This ends up in a f..k long long week of talks and ...

Would be nice to hear from the development team.

**Comment by pornel** [comment]
The reasons for bundling Sparkle are:

- it doesn't require users to install Sparkle on their system ahead of time. For every app, it always works out of the box.
- Apps don't have to ask for permissions to write to ~/Library, and when you delete an .app, there's nothing left behind.
- Apps can have customized versions of Sparkle, and ship Sparkle that supports all systems and architectures the app is built for.
- One app can't break updates for other apps. If somebody released one app that wrote buggy Sparkle to shared ~/Library you'd suddenly be left with all apps broken and unable to update.

Whether libraries should be shared or static/bundled is an old question. Both solutions have downsides and upsides. OS X generally encourages bundling.

**Comment by thotha** [comment]
@pornel Thank you for your explanation of this.

Then just an other non-professional question or maybe two.
Wouldn't it be a solution to split the framework into basic framework for all app's including all stuff which is security related and the other stuff which is individual for each app and OS related?

That way, if you, from the sparkle development team

## **(THANK YOU ALL OF YOU FOR YOUR WORK YOU DO FOR THIS COMMUNITY)**##

do have updates, security fixes, bug fixes and improvements for the basics, not all program developers who use Sparkle have to implement this fixes to their own application(s), only if they need new features of the additional framework part.

This does make Sparkle in a shorter time more saver for all users.
Specially if someone uses a specialized program which doesn't have to be updated all the time but maybe the Sparkle framework it uses needs security updates...
Also if you split basic features from specialized ones, there is no problem for apps break usability for other apps because of update the basic Sparkle framework.

Right now I have to contact about 45 developers and ask them about the Sparkle bug and how it does affect their programs and I have to use Little Snitch (or any other tool alike) to see and control what application does access what server with what protocol (http or https) and block or allow the access.

For novice users this could be a problem and most of the basic users even don't know they're in risk for to be get "taken-over" be intruders.

As I said, it's just an mentioning of an non-programming user of mine.

**Comment by pornel** [comment]
The current situation is very unfortunate, sorry.

This security issue was in code that we didn't suspect to be security-sensitive. If we had a split in Sparkle between some "serious" parts and less important app-specific parts we'd probably leave displaying of the release notes to the apps (since that's UI they may want to customize) and it wouldn't have saved us. 

Even partially shared code already has all the problems of shared code. 

Going forward we'll be pushing hard for HTTPS, so that network-based attacks are mitigated even before Sparkle touches any data.

**Comment by thotha** [comment]
@pornel 
Thank you again for your feedback.
YES that's true and can happen.
Hope all program developers are doing their job to fix their programs with the integration of the new Sparkle framework fast and seriously.
