### ISSUE TITLE
How to figure if secure connection is really used

### ISSUE THREAD

**Issue by thotha** [sparkle-project/Sparkle#745]
I did a network traffic sniff during querying the update server of the applications AppDelete 4.2.4 and Exhibeo 1.1.4 with Little Snitch as network traffic control software and WireShark to visually watch the data of that sniffing.
Some question about the update secure procedure or better asked, shouldn't it run on the TLSv1.2 protocol instead of the HTTP one?

The first picture is from the updated application AppDelete 4.2.4. I only see TCP traffic and one HTTP transfer. No secure HTTPS or TLSv1.2 traffic.
![bildschirmfoto 2016-02-13 um 23 21 21](https://cloud.githubusercontent.com/assets/17160749/13030407/dbf15c2c-d2a9-11e5-991a-a54b6bcfa05f.png)

The second one is from Exhibeo 1.1.4. Here it first does some HTTP and TCP traffic but then it switches over to TLSv1.2 traffic and you can see it does exchange some certificate data between the app and the secure serve.
![bildschirmfoto 2016-02-13 um 23 21 41](https://cloud.githubusercontent.com/assets/17160749/13030412/46e80cec-d2aa-11e5-8e4c-f0231bcbc3e4.png)
Can someone please explain it more clearly how to check for sure that the update process is running safely?

**Comment by pornel** [comment]
These screenshots look like requests are made over insecure connection (a redirect from HTTP to HTTPS is not secure against MITM).

For most apps it's enough to check `SUFeedURL` in their Info.plist.

**Comment by thotha** [comment]
So then in AppDelete it's like this.
```
<key>SUFeedURL</key>
<string>http://www.reggieashworth.com/AD4Appcast.xml</string>
<key>SUPublicDSAKeyFile</key>
<string>dsa_pub.pem</string>
```

And in Exhibeo like this.
```
<key>SUFeedURL</key>
<string>http://download.softpress.com/sparkle/sparkle.php?app=exhibeo&amp;amp;current=1.1.4</string>
<key>SUPromptUserOnFirstLaunch</key>
<true/>
<key>SUPublicDSAKeyFile</key>
<string>dsa_pub.pem</string
```
So there must be something else which can be checked by the user or must be done by the developer, I guess.

**Comment by pornel** [comment]
The developers should use HTTPS for SUFeedURL. Sparkle isn't a user-facing library, so we don't really have anything that users could do.

**Comment by thotha** [comment]
@pornel 
Ok, thank you for your feedback.
Have a nice weekend.

**Comment by pornel** [comment]
No problem.

I wrote a script in case you wanted to find all vulnerable apps:

https://gist.github.com/pornel/e50af6990f9b24a130af
