### ISSUE TITLE
What to answer to the developer on his feedback about the MITM bug?

### ISSUE THREAD

**Issue by thotha** [sparkle-project/Sparkle#746]
"Thanks for the email.  Yes AppDelete and I’m sure others still serve over HTTP, but the vulnerability in the updater is fixed:
https://github.com/sparkle-project/Sparkle/releases/tag/1.13.1"

As much as I do understand is that a developer HAS TO switch to HTTPS to be safe.
Or isn't this true?

**Comment by zorgiepoo** [comment]
Developers can patch the vulnerability found in Sparkle's update checker without serving over https. 

But https is still better to serve over in terms of general security.
