### ISSUE TITLE
FeedURL checked before set

### ISSUE THREAD

**Issue by maxsz** [sparkle-project/Sparkle#747]
Hi, 

first of all, many thanks for the great work on Sparkle, it's an awesome framework!

I just wanted to report a regression in the latest version. We used to initialise the updater like this:
`
SUUpdater * updater = [SUUpdater sharedUpdater];
updater.feedURL = getUpdateFeedURL();
[updater checkForUpdateInformation];
`
Now it throws an "SUNoFeedURL" exception if the user has a fresh installation or removes their user defaults for the app (and no SUFeedURL key is set in the Info.plist, which we're not doing, as it is dynamically created). This happens because of a `checkIfConfiguredProperly` call, which is run before one is able to set the feedURL. It's not such a big deal, because we can write the user defaults ourselves. Still, it might make sense to allow setting the properties _before_ they are checked :)

**Comment by pornel** [comment]
By the latest version do you mean 1.14? It has a fix that should make it less problematic.

**Comment by maxsz** [comment]
Sorry, cocoapods only gave me the stable release. It appears to be fixed with the 1.14.0rc1 🍻
