### ISSUE TITLE
Disable Javascript?

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#751]
Has disabling javascript or making it opt-in in the web view been given any thought? I scavenged through several apps and wasn't able to find any release notes that couldn't function without it.

**Comment by pornel** [comment]
:+1: I couldn't find any appcasts using it.

**Comment by jakepetroules** [comment]
Off by default and public API to enable it? And/or Info.plist key.

**Comment by pornel** [comment]
That's done
