### ISSUE TITLE
Appcast Parser Broken for Multiple Items

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#753]
@pornel - The recent changes (after v1.13.1) broke the way the appcast is supposed to be parsed.

1. Open up the Test Application.
2. Open `~/Library/Caches/org.sparkle-project.SparkleTestApp/sparkletestcast.xml` in a text editor
3. Create a 2nd appcast item with a different version, description, title into the xml file.
4. Set a breakpoint in `-[SUAppcast downloadDidFinish:]` after `appcastItems` is initialized
5. Check for updates in the Test Application
6. Examine `appcastItems` in the debugger and note that both appcast items are exactly the same

Not reproducible in v1.13.1. Testing by hand seems to always be a worthwhile exercise.

**Comment by pornel** [comment]
Fixed by #760
