### ISSUE TITLE
Update bundle but not relaunch the app?

### ISSUE THREAD

**Issue by jkbullard** [sparkle-project/Sparkle#754]
I would like my app to use Sparkle to update bundles (which are external to my app) separately from the app. This brings up two questions, which may be related:
- Is there a way to have the bundle updated but not relaunch the app? (Perhaps an update:shouldRelaunchApp delegate method?
- Is there a way to know the bundle has been updated?

**Comment by zorgiepoo** [comment]
My [fork](https://github.com/zorgiepoo/Sparkle) is designed to handle this better. There isn't an updater delegate callback for when the update has been finished installing yet, but it shouldn't be difficult to add (the UI is currently notified of it however).
