### ISSUE TITLE
Autoupdate launched twice

### ISSUE THREAD

**Issue by kettch** [sparkle-project/Sparkle#757]
I'm seeing something weird in my app, when downloading an update automatically, then selecting the option to 'Install on Quit'.

When the app is quit by the user, I end up in [NSApplication terminate:], which will in turn throw an applicationWillTerminate notification, and trigger the update mechanism. Then, after the files have been copied and the update is done (launching Autoupdate.app in the process), Sparkle will call - [NSApp terminate:].
It looks like that call throws another applicationWillTerminate, that tries to do the update a second time.

In practical terms, this means that Autoupdate.app is launched twice in this case, with the second instance having no files to copy, and thus producing an error log that the files cannot be installed.

An easy fix would be to not call terminate: from Sparkle, but it's probably needed by other cases where the user chooses to update and Sparkle has to terminate the app to complete the update.

**Comment by zorgiepoo** [comment]
I can reproduce the issue. Actual cause seems to be that we add the same applicationWillTerminate: notification more than once, but maybe we shouldn't call `-[NSApp terminate:]` in this scenario anyway.
