### ISSUE TITLE
Qt app + Sparkle. Update in background doesn't work. Nothing is happening on app quit

### ISSUE THREAD

**Issue by Vernat** [sparkle-project/Sparkle#758]
I see in output that new version is downloaded in background and dmg mounted, all filers are copied, the dmg is unmounted and ejected. 
Is there any subtle point?

**Comment by pornel** [comment]
Any clues in the console or Sparkle log?

**Comment by Vernat** [comment]
no

**Comment by Vernat** [comment]
Is it possible to call update directly on quit?

**Comment by Vernat** [comment]
How the update process invoking after download when c++ application is going to quit?

**Comment by Vernat** [comment]
Probably I found what I need. - installUpdatesIfAvailable.  it was missing of my version of Sparkle. Sorry for disturb.
