### ISSUE TITLE
SUScheduledCheckInterval set to 1 minute in latest version?

### ISSUE THREAD

**Issue by taoeffect** [sparkle-project/Sparkle#759]
We updated our app's Sparkle and a user told us that it's now checking for updates every minute now. We confirmed this. Our app doesn't set `SUScheduledCheckInterval` in the Info.plist and just goes with what should be the default of 86400.

Is this possibly a bug in the latest version?

Manually setting the prefs using `defaults` fixes the problem.

**Comment by zorgiepoo** [comment]
https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/SUConstants.m#L21 - looks like for debug mode, it's set at 1 minute. Did you build a debug version of Sparkle yourself?

This does make me think that having this kind of code is not a good idea.

**Comment by taoeffect** [comment]
Looks like that's probably the culprit, thanks @zorgiepoo!
