### ISSUE TITLE
Mandatory Updates

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#76]
_**Karl Moskowski (kolpanic)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/407398) on' 2009-07-31:*

There should be a way to make Sparkle updates mandatory, so the Skip and
Remind buttons are invisible, either programmatically, or via settings
in the appcast (or both).

Programmatically, you could add public API in SUUpdater to hide and show
the buttons. In the appcast, a new mandatory-update flag could be added
to a particular update entry, and the buttons would be automatically
hidden.

(This is more of a wish-list item for a future release.)

**Comment by pornel** [comment]
BTW, adding `<sparkle:criticalUpdate>` is supported and it causes update prompt to be displayed immediately with a notice that it's an important update.
