### ISSUE TITLE
App icon scaling incorrect in SUUpdateAlert

### ISSUE THREAD

**Issue by nriley** [sparkle-project/Sparkle#763]
My app icon is a solid colored rectangle, so there's no point in making a larger icon.  Almost everything handles this correctly — except Sparkle’s update window.

![tiny icon](https://cloud.githubusercontent.com/assets/68303/13197286/5a2fdd22-d7b7-11e5-962f-14fe0cf660b0.png)

I'm happy to fix this since it seems pretty simple by changing the image cell scaling to `NSImageScaleProportionallyUpOrDown`.  I couldn't figure out if Sparkle had a way of automatically producing the xibs, or if I should edit each localized xib individually.

Thanks.

**Comment by pornel** [comment]
We don't generate XIBs. I suppose it can be done with find'n'replace on all XML files.

**Comment by nriley** [comment]
Thanks, done.
