### ISSUE TITLE
Production app using old version 1.5b uses development version cached appcast?

### ISSUE THREAD

**Issue by ghmrs356** [sparkle-project/Sparkle#765]
On my development machine I keep the current production version of my app, which I update through Sparkle after we do a release.

This time we upgraded to the current Sparkle version and for testing purposes used an appcast URL different from the production feed URL. With the release, we deleted the debug appcast from the server.

Then my production app using a sparkle version from 2 years ago would no longer update. Somehow it still tried to access the now defunct debug version of the appcast, even though it never had known that URL. 

How can that be? Where is that kind of stuff cached? How can the caching be stopped?

Regards
Markus

**Comment by pornel** [comment]
What URL is in that app's Info.plist?

**Comment by ghmrs356** [comment]
The production URL that is still on the server. The debug URL no longer is. The update fails (failed) on my development machine, on a different machine the update worked fine. 

Somewhere on my system the debug and defunct URL is stored and (the old version of) Sparkle uses that instead of what is in its own Info.plist.

**Comment by pornel** [comment]
Did you have code that set custom feed URL programmatically? (e.g. via delegate?)

Sparkle doesn't have any caching.

**Comment by ghmrs356** [comment]
No, not in that build.

I went into the new debug version, changed the URL to the production feed and ran it once. Then my old production app (unchanged from before) did load the correct feed.

Maybe the old Sparkle version did some caching (or the system did in its behalf).

**Comment by hstriepe** [comment]
I have been fighting a similar issue for the last 48 hours with 1.5b6, which is being upgraded. The dev/test URL somehow "sticks" and is used by the production app part of a different bundle. Switching users and running the same app bundle fixes it. But this makes testing the system a bear! We have a complex version set and history, there are some 50 XMLs involved...
Any hint on where this caching happens would be useful.

Example: production appcast is in URL/appcasts/appname_xxx_yyy.xml
            development appcast is in URL/appcasts-36/appname_xxx_yyy.xml
Run the production app - all is right. Run the dev app, it goes to the developer appcast. Run the production app and it get the developer appcast - yikes.

Note: Production app is Sparkle 1.5b6, development is 1.13.1

A lost a night's sleep over this.

**Comment by zorgiepoo** [comment]
From what I can see, Sparkle picks the feed URL by:

1. Using the updater's delegate to ask what URL to use (not applicable to older versions of Sparkle)
2. Sees if SUFeedURL is set in the app's user defaults (this is only set if you write into the user defaults yourself or invoke the updater's setFeedURL: method)
3. Otherwise uses the URL provided in the app's info.plist

**Comment by hstriepe** [comment]
Okay, after much searching I identified what is going on. Sparkle is writing the last used SUFeedURL to the application preferences plist. This then takes precedence.

Something to be mindful of in testing and revision management. Going forward works fine - e.g. testing upgrades in sequence. But you cannot go back. If you reinstall the oldest version without deleting the prefs plist, it will immediately update to the latest version used for that user. Quite a feature, if you do not rely on incremental behavior.

It also means that once you switch to a test appcast directory sequence, it will stay on that track until you do a default delete DOMAIN SUFeedURL. As long as you know, this actually makes some testing easier.

Hope that helps.

**Comment by zorgiepoo** [comment]
@hstriepe The delegate method takes highest precedence. If you don't want to muck with user defaults for newer versions, I'd recommend using that.

Again, the user defaults is only set if you invoke the setURLFeed: method on SUUpdater. At this point I'm somewhat thinking even having this method available is a bad idea.

Keep note when dealing with user defaults, *never* look at the plist file as it may not reflect the current defaults. Always use the *defaults* command.

**Comment by ghmrs356** [comment]
@hstriepe thanks so much for digging into this, that explains what happened in my case. 

@zorgiepoo setURLFeed: is handy for different debug/release appcasts for testing purposes. The suggestion to use a delegate method makes no sense, I already told SUUpdater which URL to use, why does it have to use the delegate, then? I don't even set or use the delegate in my app. 

That a bug, clear as day.

**Comment by zorgiepoo** [comment]
Yeah, I'm arguing that "being able to tell the SUUpdater which URL to use" is a bad idea but that's just my take on the matter.

**Comment by zorgiepoo** [comment]
And the delegate method can achieve the same task, it just doesn't persist around the system. Think of it as removing a global variable, so to speak.

**Comment by hstriepe** [comment]
We use the setURLFeed for OS specific XMLs. We check, whether they are available. This is to retire versions like Snow Leopard and make them update only to the highest supported version.

in other words:
- We look at the feed URL in Info.plist
- We get the OS version and append it to the file name - name_vkey_1011.xml for El Cap
- We probe, whether this exists. If yes, we use it with setURL for the update.
- If it is not there, we let the Sparkle use its default behavior.

It looks like Sparkle 1.5b6 ends getting stuck with the first successful update feed for the user doing the update. It does not see anything else, if the user updates the OS.

But Sparkle 1.13.1 seems to behave as expected. Need to do more empirical testing and look to see, whether there is an alternate way to handle it.

**Comment by pornel** [comment]
BTW: you can hide updates from Snow Leopard using `<sparkle:minimumSystemVersion>10.7</sparkle:minimumSystemVersion>` tag.

**Comment by hstriepe** [comment]
Great - is that new?

**Comment by zorgiepoo** [comment]
It's been around since 1.5.0-beta1 according to Sparkle's CHANGELOG

**Comment by hstriepe** [comment]
Thanks!
