### ISSUE TITLE
"You must specify the URL of the appcast" incompatible upgrade

### ISSUE THREAD

**Issue by kainjow** [sparkle-project/Sparkle#767]
I didn't see this mentioned as an incompatible change in Sparkle, but this new check for SUFeedURL breaks apps that programmatically set the feed URL instead of specifying the URL in Info.plist.

I have a Qt app with a tiny Objective-C++ Sparkle wrapper that creates `[SUUpdater sharedUpdater]` in its constructor and then later calls `setFeedURL`. We don't have a URL set in the plist.

However, as of 1.13.1, Sparkle throws an exception if the URL is invalid, but it checks this at init where we haven't set the URL yet:

    +[NSException raise:format:]
    -[SUUpdater feedURL]
    -[SUUpdater initForBundle:]
    +[SUUpdater updaterForBundle:]
    +[SUUpdater sharedUpdater]

Maybe the URL should only be checked on checkForUpdates?

**Comment by pornel** [comment]
True, this is fixed in 1.14 :/

**Comment by pornel** [comment]
Fix released
