### ISSUE TITLE
Appcast containing cyrillics is not being parsed

### ISSUE THREAD

**Issue by dangelov** [sparkle-project/Sparkle#768]
While trying to push an update for my app, I was getting "Unable to parse update feed." in Sparkle. Took a few hours to pinpoint the issue, but I believe the inclusion of Cyrillic text to be a problem.

When I point the appcast URL to:
https://resttimer.com/media/with-cyrillic.xml
the update check fails.

when I point it to:
https://resttimer.com/media/without-cyrillic.xml
the update check succeeds.

Both XML files were validated using an online validator, none of them showed a problem.

Anyone else experiencing this?

**Comment by pornel** [comment]
Try adding 

```xml
 <?xml version="1.0" encoding="UTF-8"?>
```

at the top of the file

**Comment by ksuther** [comment]
I have seen a similar problem with Japanese characters, even with the correct encoding specified.

I don't currently have an active appcast that's exhibiting the error, just putting a +1 here to say I've seen it. I'll update with more info if I run into the problem again.

**Comment by pornel** [comment]
With Japanese you'd probably have to be careful to use UTF-8 rather than Shift-JIS or other Japanese encoding.

If you believe there's a bug in Sparkle, please help us diagnose it by quoting errors from Sparkle log.

**Comment by dangelov** [comment]
So after giving this a try again (sorry for the long delay!) it works, even with Cyrillic characters.

I already had

    <?xml version="1.0" encoding="UTF-8"?>

at the top of the appcast files, as well as the code that automatically generates them. But just for the fun of it, I tried removing it from the files and running a Sparkle update check and it works even without that line.

Anyway, not sure what to make of the above, but if you'd like to close the issue, feel free as at least on my end it no longer seems to be a problem.

**Comment by pornel** [comment]
So another place to check for would be your server configuration. It may be sending `charset` in `Content-Type` header that overrides encoding declaration in the file.
