### ISSUE TITLE
Request to obtain the profileinfo array

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#77]
_**Mark (markjallan)_\* [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/412679) on' 2009-08-12:*

Further to the question here
https://answers.edge.launchpad.net/sparkle/+question/79782 I'm filing a
bug report about my request.

I'd like to obtain the profileInfo array so that I can display the exact
same table which Sparkle shows during the startup prompt.

Currently, I'm allocating my own SUHost object (by copying the private
header file) and sending it the [host systemProfile] message.

Many thanks
Mark

**Comment by zorgiepoo** [comment]
I think we do this now.
