### ISSUE TITLE
Sparkle needs an hardcoded namespace prefix to find sparkle:version in appcast.xml

### ISSUE THREAD

**Issue by pierredavidbelanger** [sparkle-project/Sparkle#771]
It seems Sparkle only properly works if the `<enclosure>` `sparkle:version` attribute namespace prefix is hardcoded to `sparkle`.

Example from a - what seems valid - computer generated (Jersey JAXB) `appcast.xml`:

Here, in the `<rss>` element:

```
xmlns:ns3="http://www.andymatuschak.org/xml-namespaces/sparkle"
```

And later into an `<enclosure>` element:

```
ns3:version="0.0.42"
```

Will make my app spit this warning when it checks for update:

```
Sparkle: warning: <enclosure> for URL 'https://.../mybinary.zip' is missing sparkle:version attribute. Version comparison may be unreliable. Please always specify sparkle:version
```

**Comment by pornel** [comment]
True, Sparkle only looked at node name
