### ISSUE TITLE
PUA.OSX.Adware reported in Sparkle 1.13.1

### ISSUE THREAD

**Issue by tleish** [sparkle-project/Sparkle#774]
The latest Sparkle-1.13.1.tar.bz2 build is being reported on VirusTotal as having PUA.OSX.Adware.

See: https://www.virustotal.com/en/file/82cd7f675fa4f4a9f97943478afd7b0839767e479abe6bbd05ec67c0cc5b8056/analysis/1456979763/

**Comment by tleish** [comment]
Looks like VirusTotal: ikarus is reporting the adware starting in:

Release: 1.8.0 - adware detected
https://www.virustotal.com/en/file/6c9cba4fe36db405ed0b2591c49df40d8cddf7fedaacd1adef7ffe1a94191557/analysis/1404840259/

Release: 1.7.1 - no adware detected
https://www.virustotal.com/file/6c9cba4fe36db405ed0b2591c49df40d8cddf7fedaacd1adef7ffe1a94191557/analysis/1404840259/

**Comment by pornel** [comment]
"File Detail" on that page doesn't show any particular file as infected. PUA is "potentially unwanted application", and the detection doesn't actually point to any application in the archive.

In fact, Virus Total doesn't even know that Sparkle.framework contains executable code. The file listing shows everything inside the framework and the test app as unknown file type.

So I suspect the most likely answer is that Virus Total is crap. It runs 50 crappy detection engines, which makes it 50 times more likely tho show a false positive.

**Comment by tleish** [comment]
Must've been a false positive.  Rescanned today and it's now showing as clean.

https://www.virustotal.com/en/file/82cd7f675fa4f4a9f97943478afd7b0839767e479abe6bbd05ec67c0cc5b8056/analysis/1457024751/
