### ISSUE TITLE
Crashes on 10.7

### ISSUE THREAD

**Issue by kleuter** [sparkle-project/Sparkle#776]
Example (SUFileManager.m:269): 
```
NSDictionary *rootAttributes = [_fileManager attributesOfItemAtPath:rootURLPath error:nil];
NSString *rootType = rootAttributes[NSFileType]; // CRASH
```

Result:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSFileAttributes objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fbc2a2239c0'

Doesn't crash on 10.8+. 
Doesn't crash if I change it to
```
NSString *rootType = [rootAttributes objectForKey:NSFileType];
```

Compiler: XCode 6.1 on 10.9.5

**Comment by zorgiepoo** [comment]
It's likely we are using subscripting in other places too, which means we'd need to find a way to grep all of those.

**Comment by pornel** [comment]
There must be something special about that object, no? Otherwise we wouldn't even be able to parse the appcast on 10.7.

**Comment by zorgiepoo** [comment]
Ah, yes you're half right. I didn't realize the documentation completely lied about it returning a NSDictionary (when in fact it returns NSFileAttributes). In that case we have to grep for everywhere subscripting is used in conjunction with `attributesOfItemAtPath:`

But any sort of subscripting (NS(Mutable)Array, NS(Mutable)Dictionary) is only documented to be available on 10.8 or later, so we'd be better off not using subscripting at all to support 10.7. Who knows if other private proxy classes like that exist. Apple probably implemented the subscripting methods on 10.7 for some classes privately.

**Comment by pornel** [comment]
I've grepped for uses of `attributesOfItemAtPath`. 

Not being able to use subscripts at all is a bummer. Since we know it mostly works on 10.7, and 10.7 won't change, I think we can cautiously continue to use them.

**Comment by zorgiepoo** [comment]
Yeah, I agree, as unfortunate as this situation is.. @pornel you missed one instance in `SUPipedUnarchiver.m`

**Comment by kleuter** [comment]
Thanks for the fast feedback and fixed. One more problem at SUOperatingSystem.m
https://github.com/sparkle-project/Sparkle/pull/778

I also think there could be more subscript related code, i didn't check it all

**Comment by zorgiepoo** [comment]
Thanks for pinpointing these.

On second thought, my mind has changed about this. If we feel strongly about supporting 10.7, then we should put an effort to purge away all obj-c subscripting usage. Relying on undocumented behavior and fixing these on a case by case basis when somebody reports a crash would be the wrong thing to do (and rather unsafe / difficult to be cautious) when we can try to eliminate this practice from our code base until we feel the need to drop 10.7.

**Comment by tullera** [comment]
Sorry to add to this late, you should be able to subscript just fine on 64-bit for NSArray and NSDictionary back to 10.6 (I do this in my app):

https://developer.apple.com/library/mac/releasenotes/ObjectiveC/ObjCAvailabilityIndex/index.html

I'll bet private classes that implement the same methods as NSArray/NSDictionary that are returned didn't get the subscript methods added until later. So if you know for a fact (if you create them explicitly), that the objects are NSArray's/NSDictionary's you should be good.

**Comment by zorgiepoo** [comment]
Thank you for the reference and tip. Just want to clarify this isn't a 32-bit issue since Sparkle only builds for 64-bit these days. I'll open a PR shortly with removing subscripting in a couple scenarios that "could" be unsafe.
