### ISSUE TITLE
What's the meaning of "If you require 10.6 support, then switching to HTTPS is the only option." in change log.

### ISSUE THREAD

**Issue by Janl989** [sparkle-project/Sparkle#784]
I want to make the framework support 10.6 and with the MITM bug fixed, But I have no I idea about how to do this.
Sparkle 1.5 is not compatible with OS X 10.11 El Capitan. Is Sparkle 1.6.1 still work?

**Comment by pornel** [comment]
I haven't checked if 1.6.1 works. It might.

If you use Sparkle in any version older than 1.13.1:

* you *MUST* use HTTPS for appcast URL (`SUFeedURL`)
* if your appcast has external release note links they *MUST* be HTTPS (`<sparkle:releaseNotesLink>https://`)

**Comment by Janl989** [comment]
Thanks for help, I will have a test with Sparkle 1.6.1 on OS X 10.11.
