### ISSUE TITLE
Question: Silent and Force update

### ISSUE THREAD

**Issue by mdhari** [sparkle-project/Sparkle#787]
Saw this in the issues log:

https://github.com/sparkle-project/Sparkle/issues/162

Using the current released version 1.14.0 I have this in my code:

```
func applicationDidFinishLaunching(aNotification: NSNotification) {
        
        let updater = SUUpdater.sharedUpdater()
        updater.automaticallyChecksForUpdates = true
        updater.automaticallyDownloadsUpdates = true
        updater.checkForUpdatesInBackground()
}
```

The app does recognize an update is available and pop the dialog, but my goal is to force an update whenever it is available and not allow them to skip or delay installation once Sparkle has downloaded the update in the background. 

Is there any way to suppress the dialog and force the app to install the update right away? Can I accomplish this with just the Sparkle.framework or do I need to modify the original code? Where should I inject my changes if any?

**Comment by pornel** [comment]
The regular option to do automatic updates does this.

**Comment by mdhari** [comment]
Do you mean the user has to check that option on the dialog before this functionality is enabled? The "Automatically download and install updates" checkbox?

**Comment by pornel** [comment]
That's the option. If I remember correctly, you can set it to on with `setAutomaticallyDownloadsUpdates`

**Comment by mdhari** [comment]
If I just want to force the update right away, should I just call the action that the "Install Update" is hooked up to so I can just trigger it right away? My goal is again to force updates on the user.

**Comment by pornel** [comment]
There's `[updater installUpdatesIfAvailable]` that starts the install right away. 

We also have `<sparkle:criticalUpdate />` tag that marks updates as urgent and prompts user to install it right away.

**Comment by mdhari** [comment]
```[updater installUpdatesIfAvaliable]``` unfortunately pops a "Checking for updates" window even if there isn't an update. The flow I'm looking for is automatically downloading an update in the background (which there is code already) and then updating the app when the download is done.

The reason I don't think I can rely on automatically downloading and installing the update with ```updater.automaticallyChecksForUpdates = true``` and ```updater.automaticallyDownloadsUpdates = true``` is because you mentioned it only works when the app quits normally. I think my users just put their Macs to sleep with the app running and the app never goes to a quit state. Do correct me if I'm wrong on how the AppDelegates termination method gets called.

Thanks for answering my questions by the way. Really helpful.

**Comment by pornel** [comment]
We do have a timer to pop up a reminder if user doesn't quit the app in a while.
