### ISSUE TITLE
SUEnableAutomaticChecksKeyOld and SUCheckAtStartup obsolete?

### ISSUE THREAD

**Issue by Eitot** [sparkle-project/Sparkle#788]
Are these variables still in use? A search has not turned up anything aside from where they are defined and I think that [this](https://github.com/sparkle-project/Sparkle/commit/c2672cf89ca8fa8327e8f1a30f170354f13d885a?diff=unified#diff-ed0e176891bb32f61956fa411b2a6be8L162) was the commit that removed the last reference.

The only two remaining references are these:
[Sparkle/SUConstants.h#L46](https://github.com/sparkle-project/Sparkle/blob/0d52e27968f4896f49916767ccaba6fa24cabbe5/Sparkle/SUConstants.h#L46)
[Sparkle/SUConstants.m#L41](https://github.com/sparkle-project/Sparkle/blob/0d52e27968f4896f49916767ccaba6fa24cabbe5/Sparkle/SUConstants.m#L41)

I was looking for `SUCheckAtStartup`, because it was still used in a project’s preferences panel and not doing anything anymore. Probably easier to get rid of it to make it clear.

**Comment by pornel** [comment]
Yes, looks like they are
