### ISSUE TITLE
Recommendations for speeding up Extracting Update off a delta?

### ISSUE THREAD

**Issue by mdhari** [sparkle-project/Sparkle#792]
Is there anything I can do to speed the Extracting Update process? Compared to the actual download of the delta versus extraction, there seems to be a big difference. Here are benchmarks I have so far:

Up to date app (3.0) is 1.33 GB in size.  
              App Size | Delta Size (to 3.0) | Time to Download | Time to Extract
App 2.0  1.33 GB  |  33.5 MB               | 3 secs                   |  24 secs 
App 1.0  1.26 GB  |  51.3 MB               | 4 secs                   |  30 secs

**Comment by zorgiepoo** [comment]
We could incorrectly guess what may be most "expensive" but it may just be better to try building and profiling the BinaryDelta tool for your use case to see what's up. Off the top of my head, delta applying involves decompression, [bspatch](http://www.daemonology.net/bsdiff/), making a copy of the old app, and deep hash verification of the old and final app.

For what it's doing, 20-30 seconds for an app over 1 GB may not actually be "bad". Measuring time to download is kind of unrelated as that depends more on your internet connection... I wish my internet was as fast as yours, though :).

**Comment by mdhari** [comment]
Thanks for the reply. Does Sparkle have a flag I can set to enable BinaryDelta logging? 

I can agree that the patching process isn't actually that bad, pretty cool how it works.

**Comment by pornel** [comment]
I don't think we have so detailed logging for binary delta. Your best bet would be to use the standalone `BinaryDelta` tool under a profiler.

**Comment by mdhari** [comment]
Reopening with another question on this. I can somewhat tell that the BinaryDelta code is patching files sequentially. Is there any possibility of doing it in parallel? 

Right now we are noticing the delta patching time is almost exactly the same as downloading the entire application. So we aren't benefiting from the delta patch process as much as we would want to.

**Comment by pornel** [comment]
There is some room to parallelize, e.g. hashing of file contents. 

However, patching is also doing lots of I/O (to read all files and compare/verify them), and this won't benefit from parallelism as much (and on HDD I'd expect to be even slower than sequential reads).

Can you profile the binary delta tool and see if it's more CPU bound or I/O bound?

**Comment by mdhari** [comment]
It was very memory and CPU hungry. Didn't see a lot of hits on the hard disk.

**Comment by mdhari** [comment]
I might have to take a look at this because of some users having very long patch times. I'm assuming this hasn't been looked at in any forked versions. Let me know otherwise.

**Comment by zorgiepoo** [comment]
Not as far as I'm aware. Let us know what the biggest bottleneck is if you're able to find out from profiling BinaryDelta.

**Comment by mdhari** [comment]
Hmm, looks like its the extraction from the xar file over the bspatch call.

<img width="522" alt="screen shot 2016-10-26 at 11 29 55 pm" src="https://cloud.githubusercontent.com/assets/810521/19756864/61a5f7ee-9bd4-11e6-8cda-9c7561d8716d.png">

**Comment by jkbullard** [comment]
FWIW, after updating from Sparkle 1.5b6 to the latest version, the extraction/installation time for my **non-delta** update has increased considerably. It is now very noticeable: about six seconds, up from one or two seconds with Sparkle 1.5b6.

The app is on a 7 MB signed .dmg and is about 14 MB in 300 folders/files when fully expanded.

When I looked into it briefly, about half of the six seconds was probably spent opening the .dmg. Finder takes two or three seconds to open the .dmg after double-clicking it, including a "verifying" step which I assume is verifying the digital signature of the .dmg. It appears that however 1.5b6 extracted the .dmg, it didn't verify the signature of the .dmg, and more recent Sparkles do verify the .dmg, but that's really just a guess.

It's bearable, though, so I have been ignoring it and haven't investigated further.

**Comment by pornel** [comment]
If you care about speed, please only use .zip or .tar.gz. The .dmg format is an ugly hack all around.

**Comment by zorgiepoo** [comment]
Yeah, I only use dmg for website distribution but not for updates. The recent dmg slowness could likely be attributed to system changes, not necessarily Sparkle.

@mdhari Try altering SUBinaryDeltaCreate.m to use "gzip" (fast speed/low memory/larger size) or "lzma" (somewhere in between) instead of "bzip2" (small size/slow/memory hungry) and see if creating a new patch and applying it significantly improves.

**Comment by mdhari** [comment]
Just to confirm, you mean replacing the xar code?

**Comment by zorgiepoo** [comment]
Just a single line. grep for the string "bzip2" in that source file (on my phone)

**Comment by mdhari** [comment]
I guess I need to understand the tradeoffs. This is a good start, thanks @zorgiepoo (lzma blew up to 2 GB, haha). 

![screen shot 2016-10-27 at 10 49 13 am](https://cloud.githubusercontent.com/assets/810521/19779014/2371c7c2-9c34-11e6-9891-7859207a08f1.png)


I was also going to try putting the xar_extract and bsdiff/bspatch functions in multiple threads to see if I get those gains that I want.

**Comment by zorgiepoo** [comment]
Just in case: be sure not to compare a build with optimizations against an unoptimized build.

While we're on topic, I'd like to mention [Apple's article](https://developer.apple.com/library/content/qa/qa1779/_index.html) for tips on making delta updates work nicely, which equally applies here. It specifically warns against bundling large monolithic files.

**Comment by mdhari** [comment]
Yeah I'll try moving some data around so that pretty constant data stays as its own file.

I was also trying to figure out how to parallel this block of code, but I realized it may take some work. I actually thought using NSOperation would be pretty neat, but it looks like that API is are only useful around macOS Yosemite (10.10) and I think Sparkle is set at a minimum requirement of 10.7

```
    NSFileManager *fileManager = [[NSFileManager alloc] init];
    xar_file_t file;
    xar_iter_t iter = xar_iter_new();
    for (file = xar_file_first(x, iter); file; file = xar_file_next(iter)) {
        NSString *path = @(xar_get_path(file));
        NSString *sourceFilePath = [source stringByAppendingPathComponent:path];
        NSString *destinationFilePath = [destination stringByAppendingPathComponent:path];

        // Don't use -[NSFileManager fileExistsAtPath:] because it will follow symbolic links
        BOOL fileExisted = verbose && [fileManager attributesOfItemAtPath:destinationFilePath error:nil];
        BOOL removedFile = NO;
        
        const char *value;
        if (!xar_prop_get(file, DELETE_KEY, &value) ||
            (!hasExtractKeyAvailable && !xar_prop_get(file, DELETE_THEN_EXTRACT_OLD_KEY, &value))) {
            if (!removeTree(destinationFilePath)) {
                if (verbose) {
                    fprintf(stderr, "\n");
                }
                if (error != NULL) {
                    *error = [NSError errorWithDomain:NSCocoaErrorDomain code:NSFileWriteUnknownError userInfo:@{ NSLocalizedDescriptionKey: [NSString stringWithFormat:@"%@ or %@: failed to remove %@", @DELETE_KEY, @DELETE_THEN_EXTRACT_OLD_KEY, destination] }];
                }
                return NO;
            }
            if (!hasExtractKeyAvailable && !xar_prop_get(file, DELETE_KEY, &value)) {
                if (verbose) {
                    fprintf(stderr, "\n❌  %s %s", VERBOSE_DELETED, [path fileSystemRepresentation]);
                }
                continue;
            }
            
            removedFile = YES;
        }

        if (!xar_prop_get(file, BINARY_DELTA_KEY, &value)) {
            if (!applyBinaryDeltaToFile(x, file, sourceFilePath, destinationFilePath)) {
                if (verbose) {
                    fprintf(stderr, "\n");
                }
                if (error != NULL) {
                    *error = [NSError errorWithDomain:NSCocoaErrorDomain code:NSFileWriteUnknownError userInfo:@{ NSLocalizedDescriptionKey: [NSString stringWithFormat:@"Unable to patch %@ to destination %@", sourceFilePath, destinationFilePath] }];
                }
                return NO;
            }
            
            if (verbose) {
                fprintf(stderr, "\n🔨  %s %s", VERBOSE_PATCHED, [path fileSystemRepresentation]);
            }
        } else if ((hasExtractKeyAvailable && !xar_prop_get(file, EXTRACT_KEY, &value)) ||
                   (!hasExtractKeyAvailable && xar_prop_get(file, MODIFY_PERMISSIONS_KEY, &value))) { // extract and permission modifications don't coexist
            
            if (xar_extract_tofile(x, file, [destinationFilePath fileSystemRepresentation]) != 0) {
                if (verbose) {
                    fprintf(stderr, "\n");
                }
                if (error != NULL) {
                    *error = [NSError errorWithDomain:NSCocoaErrorDomain code:NSFileWriteUnknownError userInfo:@{ NSLocalizedDescriptionKey: [NSString stringWithFormat:@"Unable to extract file to %@", destinationFilePath] }];
                }
                return NO;
            }
            
            if (verbose) {
                if (fileExisted) {
                    fprintf(stderr, "\n✏️  %s %s", VERBOSE_UPDATED, [path fileSystemRepresentation]);
                } else {
                    fprintf(stderr, "\n✅  %s %s", VERBOSE_ADDED, [path fileSystemRepresentation]);
                }
            }
        } else if (verbose && removedFile) {
            fprintf(stderr, "\n❌  %s %s", VERBOSE_DELETED, [path fileSystemRepresentation]);
        }
        
        if (!xar_prop_get(file, MODIFY_PERMISSIONS_KEY, &value)) {
            mode_t mode = (mode_t)[[NSString stringWithUTF8String:value] intValue];
            if (!modifyPermissions(destinationFilePath, mode)) {
                if (verbose) {
                    fprintf(stderr, "\n");
                }
                if (error != NULL) {
                    *error = [NSError errorWithDomain:NSCocoaErrorDomain code:NSFileWriteNoPermissionError userInfo:@{ NSLocalizedDescriptionKey: [NSString stringWithFormat:@"Unable to modify permissions (%@) on file %@", @(value), destinationFilePath] }];
                }
                return NO;
            }
            
            if (verbose) {
                fprintf(stderr, "\n👮  %s %s (0%o)", VERBOSE_MODIFIED, [path fileSystemRepresentation], mode);
            }
        }
    }
    xar_close(x);
```

**Comment by zorgiepoo** [comment]
Needs to be reevaluated with latest delta support
