### ISSUE TITLE
1.14 reported as 1.13.1 git-2afc553

### ISSUE THREAD

**Issue by XericDesign** [sparkle-project/Sparkle#793]
If I put the sparkle framework in a folder called "sparkle" I see version 1.14 as 1.13.1 git-2afc553. If I change the folder name or move it, it shows 1.14 again. I think the OS has somehow cached the version number or there is a symbolic link that is pointing somewhere else on my system.

What would cause this?

**Comment by pornel** [comment]
Sparkle uses symlinks internally, but I think that shouldn't affect framework version. 

How are you checking the version?

**Comment by XericDesign** [comment]
Using Get Info from the Finder on the Sparkle.framework file.

**Comment by pornel** [comment]
You can try bypassing Finder from command line:

```sh
defaults read path/to/Sparkle.framework/Resources/Info.plist CFBundleVersion
```

if that gives the expected verison, then it's probably just Finder acting odd.

**Comment by pornel** [comment]
I'm assuming it was glitch a in Finder. Please reopen if Sparkle needs to change something.
