### ISSUE TITLE
How to use custom update drivers?

### ISSUE THREAD

**Issue by mdhari** [sparkle-project/Sparkle#796]
Hi All,

I basically want to customize the update flow quite a bit without modifying Sparkle source. I found a hint on the documentation page when I saw this:

> If these methods aren’t enough to do what you need, you’re going to have to dig into Sparkle’s code. You might start by creating a different update driver: check out SUBasicUpdateDriver.h to get an idea.

But how do I pass in a custom UpdateDriver? I looked up the source for SUUpdater, and it looks like 
`- (void)checkForUpdatesWithDriver:(SUUpdateDriver *)d` is private. How would Sparkle want to be passed a custom driver?

Thanks.

**Comment by zorgiepoo** [comment]
Maybe add a method that invokes checkForUpdatesWithDriver: with your own custom driver. To avoid altering Sparkle's source, only way I can think of is to a subclass SUUpdater, but I'm not sure how far you'll get without having to fork Sparkle. Subclassing isn't a very elegant or lifelong approach either though.

I am currently working on a XPC fork of Sparkle, which incidentally allows a much greater deal of customization too. What are you trying to customize exactly?

**Comment by mdhari** [comment]
I have a flow where I let the user click a update button and it instructs them that its updating in the background (where there is no release notes ui, download progress ui or extracting update ui). When the update is done (after downloading and extracting) the Install and Relaunch window comes to the front. That's the only time a user will be able to update the App.

**Comment by mdhari** [comment]
I basically want to push the updating process to the background when a user hits update and be notified when it's past the extraction part so I can pop the window when its ready so the user knows that they can relaunch. I want the update process to be as non-intrusive as possible UI wise.

**Comment by zorgiepoo** [comment]
For the current version of Sparkle, I think you'd want to subclass `SUBasicUpdateDriver` and create something similar to `SUUIBasedUpdateDriver`. Though keep in mind `SUUIBasedUpdateDriver` isn't directly used by Sparkle; its subclasses (scheduled and user initiated drivers) are. Like I said before you'd probably add/extend/override a method that calls `checkForUpdatesWithDriver:` with your new driver.

My [XPC/Sandbox branch](https://github.com/zorgiepoo/Sparkle/tree/ui-separation-and-xpc/), although still incomplete and API subject to change, is supposed to make this kind of thing easier. If interested, check out `SUUserDriver.h`, `SUUserDriverCoreComponent.h`, and as examples `SUStandardUserDriver.h`, `SUPopUpTitlebarUserDriver.h`. The architecture is more protocol than subclassing oriented and is quite different than the master branch of Sparkle.

**Comment by mdhari** [comment]
Hmm, looks like I can't subclass SUBasicUpdateDriver from the framework in the Sparkle 1.14.0 build because it's not exposed in the headers. I'll just get the source and try to subclass from there. If it's too much of a pain like you mentioned, I'll just start hacking away, thanks!
