### ISSUE TITLE
BinaryDelta performance on large binary files?

### ISSUE THREAD

**Issue by mdhari** [sparkle-project/Sparkle#799]
I'm getting killed on time generating a delta. I found out there is a verbose mode on the BinaryDelta tool. 

The culprit is probably a 2 GB binary sqlite db that I use in my App. The amount of change is probably 5-20% The net is claiming that bsdiff does poorly on large binary files. Have you guys had any ways around this issue?

**Comment by zorgiepoo** [comment]
Creating a binary diff can indeed be [computationally expensive](http://www.daemonology.net/bsdiff/). Perhaps the patching time is acceptable, but creating the diff may hurt you..

I recommend following the guidelines taken directly from [Apple's technical page](https://developer.apple.com/library/ios/qa/qa1779/_index.html):

> To optimize the size of your app updates, you should consider two tips:

> * Do not make unnecessary modifications to files. Compare the contents of the prior and new versions of your app with diff or another directory comparison tool and verify that you've only changed what you expect within your app bundle.

> * Content that you expect to change in an update should be stored in separate files from content that you don't expect to change. This reduces the size of the update package and increases its install speed.

Otherwise I'm not sure what can be done to improve efficiency. You may have to reconsider if including a single 2 GB database file is a good idea.

**Comment by zorgiepoo** [comment]
..with that said, it may be an interesting / worthwhile experiment to see if xdelta performs better than bsdiff and adequately. I get the impression that it may at least be faster at creating diffs. Download xdelta & bsdiff / bspatch, try creating a patch, applying it, and compare times and patch sizes.

**Comment by mdhari** [comment]
Hmm, having a lot of trouble compiling xdelta3 on my Mac. I'll try it out though.

**Comment by zorgiepoo** [comment]
If I recall and for what it's worth, I think it can be installed pretty easily via homebrew.

**Comment by zorgiepoo** [comment]
We're exploring a new container format for binary deltas #2051 #1902. There's some perf difference although we're not changing bsdiff right nwo.

**Comment by zorgiepoo** [comment]
We will support more compression formats, some favor speed over size, etc. And change the default to lzma.
