### ISSUE TITLE
Sparkle: Completely broken?

### ISSUE THREAD

**Issue by bdkjones** [sparkle-project/Sparkle#802]
Hi guys. I'm pretty sure Sparkle has just stranded tens of thousands of users of my app and I'm a little frustrated.

A couple months ago, I shipped an update to my app that included the then-current version of Sparkle: 1.13.1.

The version of my app was `2.7.1`. Today, I shipped an update for version `2.8` and updated my `appcast.xml` file with the following entry:

```
<item>
            <title>Version 2.8</title>
            <sparkle:releaseNotesLink>https://incident57.com/codekit/sparkleversionhistory.html</sparkle:releaseNotesLink>
            <pubDate>Friday, 29 April 2016 18:15:00 -0700</pubDate>
            <enclosure url="https://incident57.com/codekit/files/codekit-19120.zip" sparkle:version="19120" sparkle:shortVersionString="2.8" length="52007267" type="application/octet-stream"/>
            <sparkle:minimumSystemVersion>10.8</sparkle:minimumSystemVersion>
        </item>
```

However, when I check for updates in `2.7.1`, Sparkle reports that the latest version of my app that is available is `2.7.1`. I have verified that the correct XML file is being downloaded. 

What's going on here? And PLEASE tell me I can fix it...

**Comment by bdkjones** [comment]
Sparkle is not logging anything to console.app when I check for updates. 

This really doesn't look good, guys. I'm incredibly worried that I've now shipped a version of my app that I can never update because Sparkle is silently failing. What can I provide to figure out what's going on?

**Comment by bdkjones** [comment]
My app is signed with a valid Apple Developer Certificate and as you can see in my `item` entry above, I'm delivering the download and release notes via `https`. Additionally, the old version of my app (2.7.1) and the new version both have `NSAllowsArbitraryLoads` set to `YES`, which allows using HTTP connections.

**Comment by pornel** [comment]
Sparkle reports user-friendly version to the user, but checks against `sparkle:version="19120"` you've specified. Is that higher than your `CFBundleVersion` in the old app?

**Comment by bdkjones** [comment]
Yes. The old app is 19115.

**Comment by pornel** [comment]
I'm looking into it

**Comment by bdkjones** [comment]
If you'd like, the old version (2.7.1) of my app is available at http://incident57.com/codekit/files/codekit-19115.zip

The new version is http://incident57.com/codekit/files/codekit-19120.zip

The location of the appcast.xml file and related resources is in the `item` entry above. Thanks for the help!

**Comment by bdkjones** [comment]
Do you think there's any hope of fixing the problem from where I am, or do I need to start looking at how to contact my customers and let them know they need to manually update to the latest release of my app?

**Comment by zorgiepoo** [comment]
Is the appcast on your server up to date? Going to https://incident57.com/codekit/appcast/ck2appcast.xml , I don't see the entry for 2.8

**Comment by bdkjones** [comment]
@zorgiepoo What's your physical location in the world? When I visit that URL I get the updated XML with the 2.8 item. That's the very first thing I checked, before I opened this issue. I will re-verify, but I currently don't have any caching enabled on my server so it should not be serving an old version to anyone.

**Comment by zorgiepoo** [comment]
U.S. EST. It's not serving the new version for me then.

**Comment by bdkjones** [comment]
@zorgiepoo You're right. When I access the URL through my VPN, I get a different version of the file depending on what location I'm accessing from. There's something funky going on with caching at my hosting provider. 

You know, I TRY not look like a moron before I open an issue on GitHub and, invariably, I look like a moron every time I open an issue on GitHub. This really WAS the first thing I checked when the problem appeared. I'll see what the heck is going on with my hosting provider and that will clear this up, I'm sure. 

Sorry for the false alarm; just a stressful few hours. In my next life, I will choose literally any other career than software development.
