### ISSUE TITLE
How to sign application with embedded Sparkle Framework ?

### ISSUE THREAD

**Issue by zucher** [sparkle-project/Sparkle#805]
Hi,

I want to sign my application with latset 1.14.0 SF, unfortunatly I get at the en or signing every tie the same failure:

codesign --verbose=4 --deep --strict MyApplication.app/
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtCore.framework/Versions/Current/.
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtCore.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtDBus.framework/Versions/Current/.
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtDBus.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtGui.framework/Versions/Current/.
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtGui.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtMacExtras.framework/Versions/Current/.
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtMacExtras.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtNetwork.framework/Versions/Current/.
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtNetwork.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtPrintSupport.framework/Versions/Current/.
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtPrintSupport.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtQml.framework/Versions/Current/.
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtQml.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtQuick.framework/Versions/Current/.
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtQuick.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtWebChannel.framework/Versions/Current/.
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtWebChannel.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtWebEngineWidgets.framework/Versions/Current/.
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtWebEngineWidgets.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtWidgets.framework/Versions/Current/.
--validated:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/QtWidgets.framework/Versions/Current/.
--prepared:/xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/Sparkle.framework/Versions/Current/.
MyApplication.app/: a sealed resource is missing or invalid
In subcomponent: /xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/Sparkle.framework
file added: /xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/Autoupdate.app/Contents/_CodeSignature/CodeResources
file modified: /xxxxxxxxxxxxxx/MyApplication.app/Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/Autoupdate.app/Contents/MacOS/Autoupdate

How get out this siging error ?

**Comment by zorgiepoo** [comment]
`codesign --deep` should *not* be used for signing. It does not sign bundles recursively inside-out only looking at directories that should contain signed code like Xcode's "Code Sign on Copy" does. See [OS X Code Signing in Depth](https://developer.apple.com/library/mac/technotes/tn2206/_index.html) for more info. I'm not familiar enough with Qt but perhaps `macdeployqt -codesign` may work.

**Comment by zucher** [comment]
Finally I use the https://github.com/aurelien-rainone/macdeployqtfix.git and it's fine working

**Comment by jakepetroules** [comment]
Things like https://github.com/aurelien-rainone/macdeployqtfix.git really should not be necessary. If you encounter bugs in macdeployqt, please report them at https://bugreports.qt.io. At least in Qt 5.6.x, some of the bugs mentioned in that tool should be fixed by now.

**Comment by mbsanchez** [comment]
I have the same trouble, but i don't want to use a third party app like macdeployqtfix, perhaps i need to switch to qt 5.6 because i can't find any other solution to this trouble.

In my case, this trouble only happens with Sparkle.framework. When I remove it, the app is signed and verified with no issues.
