### ISSUE TITLE
Can not compile using Carthage

### ISSUE THREAD

**Issue by bmichotte** [sparkle-project/Sparkle#808]
When using carthage to build, I got this error

```
The following build commands failed:
	PhaseScriptExecution Run\ Script:\ Set\ Git\ Version\ Info /Users/benjamin/Library/Developer/Xcode/DerivedData/Sparkle-cybyotvfqsowcrcyigkrulwumxva/Build/Intermediates/Sparkle.build/Release/Autoupdate.build/Script-14652F7B19A945D600959E44.sh
```

Looks like there's something wrong in `Configurations/set-git-version-info.sh`. After I `sed -e 's/^M//g'` the file, the script does not fail again. I can't commit this change because git does not find any change :/

**Comment by pornel** [comment]
The file uses LF. Your local git is probably configured to replace LF with CRLF.

**Comment by bmichotte** [comment]
I forgot I add to `git config --global core.autocrlf true` to work with some teammates.

Thanks and sorry for this
