### ISSUE TITLE
Users complaining about "Opening Application for the first time"

### ISSUE THREAD

**Issue by mdhari** [sparkle-project/Sparkle#809]
I have an issue where my users are saying they are seeing this sort of message every time they update the app.

http://apple.stackexchange.com/questions/30177/excessive-opening-application-for-the-first-time-dialogs

I think it's occurring when Sparkle determines a full dmg needs to be downloaded and installed from the AppCast, but I'm scratching my head on why they are seeing this message. Has the sparkle team had this issue before? I know from searching on the net, its relating to the com.apple.quarantine flag not being cleared, but I feel like its getting reset on every full update.

I'm starting to wonder if I shouldn't be time stamping my dmgs as well, like:

app_05_06_16.dmg
app_05_07_16.dmg

Maybe the OSX operating system is flagging them just based on filename?

**Comment by pornel** [comment]
Try using a proper archive format like zip or tarball. Handling of DMG is slow, hacky and complicated, and I wouldn't be surprised if it was flawed in some (or many) ways.

**Comment by zorgiepoo** [comment]
I ran into this issue recently with one of my test apps. It happened every time I launched the app. Launch services never remembered my decision; I had to reboot my Mac to fix it. It's not quarantine related, and probably not dmg related either.

**Comment by mdhari** [comment]
I honestly included a hack in my app where I run "xattr -d apple.com.quarantine <appname>" in the applicationDidFinishLaunching method and my users say they don't see the issue anymore. :)
