### ISSUE TITLE
critical update 

### ISSUE THREAD

**Issue by MichelePannacci** [sparkle-project/Sparkle#812]
Hi, I'm attempting to sign an update as critical with no success, this is what I'm doing:
`<item>
            <title>r3.540</title>
            <sparkle:tags>
                <sparkle:criticalUpdate />
            </sparkle:tags>
            <sparkle:minimumSystemVersion>10.9.0</sparkle:minimumSystemVersion>
            <description><![CDATA[
....`
I'm missed something? Thanks

**Comment by H725-79** [comment]
Forgot to mention that I'v just update sparkle to latest v1.14.0

**Comment by pornel** [comment]
Please check messages that Sparkle outputs in console.app. You should say there why signing didn't work and what you should do.

**Comment by H725-79** [comment]
Hi pornel and thanks to respond to me. I did not say that signing is not working, in fact the auto-update is working well, only, the update is not signed as critical.
In console I can see that:
19/05/16 14:12:41,677	Autoupdate[1411]	Sparkle: ===== Autoupdate.app =====
19/05/16 14:12:41,679	Autoupdate[1411]	Sparkle: mdimporting
looks ok..

**Comment by H725-79** [comment]
Sorry, got it, for "sign" I was meant "mark" the update as critical.... my bad English ..I'm Italian :-)

**Comment by pornel** [comment]
Ah, I see. Your tag for critical update looks OK.

Are you using Italian version of Sparkle by any chance? Maybe we don't have translation for the UI, so it falls back to text we have for regular updates.

**Comment by H725-79** [comment]
The app is in English only and sparkle is compiled from source, but I should test with the System in en. Ok two minutes.. the time to reebot and let you know..

**Comment by H725-79** [comment]
looks the same with the System in English.

**Comment by pornel** [comment]
Great you're compiling from source. Try adding `NSLog` in SUAppcastItem initWithDictionary. The `dict` should contain all tags found, so you'll see if Sparkle parsed the appcast as intended.

**Comment by H725-79** [comment]
the tag is there:
[All Messages.log.zip](https://github.com/sparkle-project/Sparkle/files/272610/All.Messages.log.zip)

**Comment by pornel** [comment]
Hmm, in that case I don't see why it doesn't work :/

**Comment by H725-79** [comment]
did not work even returning Yes in - (BOOL)isCriticalUpdate.
I will play with sparkle and let you know..if can, thanks anyway.

**Comment by zorgiepoo** [comment]
Looks like Sparkle only uses the "critical marked" property if the user (or developer) opted into automatically downloading updates in the background, in which case the update alert is prompted right away and has the text reflecting it's important.

**Comment by H725-79** [comment]
Hi zorgiepoo, thanks. I'm far from my Mac and cannot try, but in this case I hope that auto-downloading/install update will not wait all the time user has set in the preferences.

**Comment by tempelmann** [comment]
I just ran into this bug myself and found that the code in `[SUAppcast downloadDidFinish:]` does not collect child tags correctly. Therefore, any tags inside <sparkle:tags> get ignored. I wonder if this code has ever worked, i.e. ever been tested to work. I'll see if I can fix this and submit a fix.

**Comment by zorgiepoo** [comment]
The appcast parsing works for me. Make sure the tags are in the `<item></item>` like the original poster posted.

What Sparkle doesn't currently do is change any of the subtle text for updates that aren't downloaded & installed automatically, if the update is critical. I fixed that in my fork after merging the automatic and non automatic update alerts together.

**Comment by tempelmann** [comment]
I've submitted a merge request for my test case: https://github.com/sparkle-project/Sparkle/pull/999

**Comment by gaocan1992** [comment]
<sparkle:tags><sparkle:criticalUpdate /></sparkle:tags>
Doesn't work for me

**Comment by bdkjones** [comment]
I had no idea "critical updates" were even a thing with Sparkle. I just stumbled into this while trying to find a way to disable the "Skip This Version" button. 

I looked through the documentation at "Getting Started" (and the various things it links to) and found no reference to this capability.
