### ISSUE TITLE
Exclude Files from Sparkle?

### ISSUE THREAD

**Issue by mdhari** [sparkle-project/Sparkle#813]
Is there a way to exclude certain files from being managed by Sparkle? It's related to #810 in the sense that we want to maintain large files over 2GB on our own through other methods.

**Comment by zorgiepoo** [comment]
I think through own methods usually implies do not bundle those files in your app. Having the delta tool exclude your large files would make using the tool pretty useless in the first place.

**Comment by pornel** [comment]
I suggest:

- release update that does both: a) change appcast URL to a new one, b) moves the large file to Application Support

- under new appcast URL provide update that doesn't have the large file, but updates it in Application Support dir instead

**Comment by mdhari** [comment]
We found a way to split the file up so it's under the limit and Sparkle can maintain it. Thanks all.
