### ISSUE TITLE
coveralls.io hasn't updated since September

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#815]
coveralls.io integration is broken. I don't have login to check what's causing it.

**Comment by jakepetroules** [comment]
It fails because the coverage is so low.

**Comment by pornel** [comment]
When I click the icon it gives me this page:

https://coveralls.io/github/sparkle-project/Sparkle?branch=master

which shows latest build as 380, from 19 Sep 2015. I'd expect it to contain more up to date builds.

**Comment by zorgiepoo** [comment]
It's probably because of swift code. I'm in favor or removing it; it's broken.

**Comment by zorgiepoo** [comment]
Also see #636

**Comment by kainjow** [comment]
I had problems using Coveralls for my project. I switched to [https://codecov.io](Codecov) and it was much easier to integrate.

**Comment by zorgiepoo** [comment]
Sounds like it may be a better option if it relies on Xcode 7's code coverage data. If it doesn't, then we'd be just adding an additional 3rd party layer to our build integration. Travis has some trouble keeping up with Apple's stack already.
