### ISSUE TITLE
Codesigning macOS app on Travis CI

### ISSUE THREAD

**Issue by iosdeveloper** [sparkle-project/Sparkle#824]
I'm trying to integrate Sparkle with the open source menu bar app [BitBar](https://github.com/matryer/bitbar). I have decided to add Sparkle as a submodule and build the framework from source.
The latest pre-release ([v2.0.0-beta5](https://github.com/matryer/bitbar/releases)) includes Sparkle for the first time but it is not passing RB App Checker (as recommended on the project website) and appears damaged. The previous releases without Sparkle (e.g. v2.0.0-beta4) are passing RB App Checker just fine. The [Travis CI build script](https://github.com/matryer/bitbar/blob/master/.travis.yml#L25) uses `xctool build` and `codesign --deep --force` to sign the app. Any help is really appreciated.
<img width="532" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/655921/16161956/8731e59c-34d0-11e6-8756-a992f6e32466.png">
![bildschirmfoto 2016-06-17 um 21 27 20](https://cloud.githubusercontent.com/assets/655921/16162211/566bec3a-34d2-11e6-859c-9d8b1030e822.png)
![bildschirmfoto 2016-06-17 um 21 20 58](https://cloud.githubusercontent.com/assets/655921/16162090/75b0eda8-34d1-11e6-9d6e-6c6fb4fbb959.png)

**Comment by zorgiepoo** [comment]
The Sparkle framework in your app seems to be missing files and symlinks, perhaps you didn't archive the app properly?

The way I recommend creating a zip which is the same way Finder's Compress option works:

`ditto -c -k --sequesterRsrc --keepParent <src_path_to_app> <zip_dest>`

See the ditto man page.

**Comment by iosdeveloper** [comment]
@zorgiepoo Thanks! That and passing `CODE_SIGN_IDENTITY` to xctool instead of using `codesign --deep --force` seem to work: https://github.com/matryer/bitbar/commit/e4763aed886689b4743a9904567a59a02534e170
