### ISSUE TITLE
How could I use sparkle to install an already downloaded update ?

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#829]
I have developed an app that could download any available update into the user's download folder.
I want Sparkle to just install this already downloaded update - Is this possible ?

**Comment by pornel** [comment]
It's not possible out of the box. We assume Sparkle will download updates itself, and expect Sparkle appcast to be present, so we can look for DSA signature to verify the downloads are correct and secure.

**Comment by prasha6** [comment]
Thanks a lot!
