### ISSUE TITLE
Silent installer using -store option?

### ISSUE THREAD

**Issue by barrettc0de** [sparkle-project/Sparkle#830]
I'd like to make my installer as silent as possible. [The package installer tool provides a "-store" option which allows for silent installs.](https://stackoverflow.com/questions/28315383/how-to-silently-install-a-pkg-file-in-mac-os-x)

I'm wondering if I fork Sparkle and add some code to add this option to the list of arguments that are eventually fed into AuthorizationExecuteWithPrivileges(), is there anything preventing this from working? It doesn't seem like Sparkle ever supported this, so it would be helpful to know if anyone has looked into this before.

This is where the "installer" command originates from:
https://github.com/sparkle-project/Sparkle/blob/bb624ffa5950966bb738dd83f973d3aad907324b/Sparkle/SUFileManager.m#L1025

**Comment by pornel** [comment]
Are you using Sparkle's guided install option?

**Comment by barrettc0de** [comment]
@pornel Somehow I missed that option, I'll try it right now. Looks to be what I need. Thanks.

**Comment by barrettc0de** [comment]
Guided install option works like a charm.
