### ISSUE TITLE
Can I disable a part of the Sparkle UI ?

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#831]
Hi,
I have already developed UI for a part of my app's upgrade workflow; For the remaining part I want to leverage the Sparkle updater UI.

I do not want the "Release notes/updates available" sparkle UI:
![image](https://cloud.githubusercontent.com/assets/8802054/16508005/5097d3f8-3ee3-11e6-91cd-9c2df06f2c88.png)

But I do want all the sparkle UI that comes after the above UI, such as "Downloading the update" "Extracting the update" "Install and relaunch".

Is it possible to suppress the UI where sparkle comes up with release notes and asks the user whether they want to install the update/skip this version ?

**Comment by pornel** [comment]
If you don't specify any release notes in the appcast, then you'll get a small window with just skip/remind/install buttons.

You can also enable automatic updates by default via Info.plist setting, and then users generally won't see Sparkle's UI.

If that's not enough, you can edit XIB files and *prompt controllers to achieve UI you'd like.
