### ISSUE TITLE
Support GitHub releases as alternative to App Cast

### ISSUE THREAD

**Issue by fulldecent** [sparkle-project/Sparkle#833]
Our project uses GitHub releases to release the software. The binaries are signed and the release information is secure (GitHub releases uses HTTPS).

Our project has good release information already with https://github.com/fulldecent/kibitz/releases.atom

From a feature perspective, this would update the requirement on Sparkle's homepage from

> HTTPS server for serving updates (see App Transport Security)

to

> HTTPS server for serving updates (see App Transport Security) or project on GitHub

Related: https://github.com/fulldecent/kibitz/issues/16

**Comment by zorgiepoo** [comment]
Check out issue #648

**Comment by fulldecent** [comment]
Thank you. Closing as duplicate of #648.
