### ISSUE TITLE
Sparkle Update looking for a DSA signature even when one is not provided

### ISSUE THREAD

**Issue by ctaylor04** [sparkle-project/Sparkle#840]
I am trying to update to the latest version of sparkle, and am running into issues when I am testing.

I am on  commit 3f637c96748c2a80bee257398ba1f41eb3e78d06

the error messages that I am seeing are the following:

Sparkle: There is no DSA signature to check
Sparkle: DSA signature validation failed. The update has a public DSA key and is signed with a DSA key, but the public key doesn't match the signature. The update will be rejected.

I do Have a public key in my application's info.plist, I am not changing it. and I do not have a DSA key specified in my feed.

```
        <item> 
          <title>Version 5.0.7</title> 
            <description>https://MyURL.com/Path/description.html</description> 
             <pubDate>Mon, 28 Mar 2016 8:00:00 +0500</pubDate>
            <enclosure sparkle:version="15000"
             sparkle:shortVersionString="5.0.7"
             url="https://MyURL.com/Path/newApplication.zip"
             length="104306199"
             type="application/octet-stream"/>
      </item> 

```

 I believe that the SUBasicUpdateDriver.m lines 324-330 are the issue. 

```
if (newPublicDSAKey != nil) {
    if (![SUDSAVerifier validatePath:downloadedPath withEncodedDSASignature:DSASignature withPublicDSAKey:newPublicDSAKey]) {
        SULog(@"DSA signature validation failed. The update has a public DSA key and is signed with a DSA key, but the %@ doesn't match the signature. The update will be rejected.",
              dsaKeysMatch ? @"public key" : @"new public key shipped with the update");
        return NO;
    }
}
```

and specifically since the DSASignature is empty it fails the verifier test. However it seems to me like since I did not specify a DSASignature in the feed it should not be trying to verify it.

I do not want to remove the publicDSAKey in case I need to update via a pkg file at some point but I try to keep to zipped app files.

**Comment by zorgiepoo** [comment]
Sparkle doesn't consider the feed to be trusted so we can't have "not specify DSA signature in feed" lead to "skip DSA verification when performing update." I recommend DSA signing your zip and providing a signature in your feed, which will also add extra security.
