### ISSUE TITLE
Multiple Instantiation of SUUpdater ?

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#841]
Hi,

I see the following in the documentation:
"The SUUpdater object is the main controller for the updating system in your app. There is a singleton instance of this class for each bundle being updated. If you’re trying to update the running .app, you can retrieve the appropriate SUUpdater by calling [SUUpdater sharedUpdater]"

If that's the case, Is the following possible?

if (some condition)
  {
     SUUpdater updater = new SUUpdater();
     updater.CheckForUpdatesInBackground ();
  }
else
{
     SUUpdater updater = new SUUpdater();
     updater.FeedURL = url-address;
     updater.AutomaticallyDownloadsUpdates = true;
     updater.CheckForUpdatesInBackground ();
}

I am instantiating two SUUpdater instances. Depending on the condition, I want the Sparkle UI to be turned on/off. Am I following the right approach ?

**Comment by pornel** [comment]
You can use `sharedUpdater` and optionally set `updater.AutomaticallyDownloadsUpdates = some condition` instead.

Multiple instances are supposed to be used only for multiple products, like plug-ins. Running multiple instances for the same app may cause problems.

**Comment by prasha6** [comment]
Is it fine to make calls to sharedUpdater outside the main thread ?

**Comment by pornel** [comment]
Unfortunately it's not thread-safe.
