### ISSUE TITLE
Does Appcast remember SUUpdater's AutomaticallyDownloadsUpdates?

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#842]
I had a weird situation:

I have 2 apps with the same appcast.xml.

App1 had AutomaticallyDownloadUpdates = true; App 2 had nothing set for AutomaticallyDownloadUpdates.

I ran App1 first and as expected Sparkle UI was disabled. Then, I ran App2 - I was expecting Sparkle UI, but however the sparkle UI was disabled. 

Why would I experience such a situation ?

**Comment by pornel** [comment]
Did you run the apps more than once? 

The very first run of an app does nothing. That's on purpose to avoid having popups for new users.

**Comment by prasha6** [comment]
Yes, I did run the apps more than once.
Please note that this is "AutomaticallyDownloadUpdates" and not "AutomaticallyCheckForUpdates".

**Comment by zorgiepoo** [comment]
Using that setter changes the user defaults of the application. Do the apps share the same user defaults?

**Comment by prasha6** [comment]
How do I know if they share the same user defaults ? I'm sorry, I do not know what User defaults is.
