### ISSUE TITLE
Bundles Helper app isn't restarted on update

### ISSUE THREAD

**Issue by mountsi** [sparkle-project/Sparkle#844]
I have an application bundle which contains a helper application.
After updating the application bundle (which includes an updated helper application) the old helper version still runs until logout/login.
Sending a HUP signal to the helper application would solve the problem but there seems to be no way to run some kind of post-update script.

**Comment by pornel** [comment]
Your delegate can listen to `willInstallUpdate` and tell the helper to quit (not reload). Restarted host app should relaunch the helper.

https://github.com/sparkle-project/Sparkle/blob/1ced9c428a4a7c62f898e8e95dabb10e228e77d5/Sparkle/SUBasicUpdateDriver.m#L505

**Comment by mountsi** [comment]
While delegates are working fine, the helper isn't restarted when host app is relaunched.
A "post update" delegate method would do the thing but I did not find any in the documentation 
https://sparkle-project.org/documentation/customization/

**Comment by jkbullard** [comment]
Your app will be relaunched after the update is completed. You could have your app "HUP" the helper each time it is launched (via applicationDidFininshLaunching or similar).

You can do the HUP only when the app is updated by having your updaterShouldRelaunchApplication: Sparkle delegate set a user default that says the app has been updated, and then test that default and only HUP the helper if it is set (and then clear it).

I think you could create an Installer package with a post-flight script to HUP your helper instead, but I think that's a lot more work.

**Comment by zorgiepoo** [comment]
Keep in mind the user can update your app bundle manually without going through Sparkle, which you probably want to take in account too.

**Comment by mountsi** [comment]
So an appropriate solution would be saving the bundle version each time the app quits (using application delegates) and compare this to the current bundle version at startup. 
As this works independently from sparkle I'll close this issue.
Thank you for your help.
