### ISSUE TITLE
What if certificate got expired

### ISSUE THREAD

**Issue by zaigham-mt** [sparkle-project/Sparkle#852]
I need to confirmed how to get app update if certificate got expired. In that case we generate new certificate.But new certificate will not conform with already integrated certificate inside app.

**Comment by pornel** [comment]
If your new certificate has the same developer identity (you've renewed certificate with Apple instead of closing your Apple account and registering a new one), then it will continue to work.

**Comment by zaigham-mt** [comment]
I am talking about dsa signature that is generated via private key for each build inside envelope.

**Comment by pornel** [comment]
The DSA private key does not expire. But if you lose the key, you'll lose ability to send updates.
