### ISSUE TITLE
Does Install Update restart the app cleanly with patching?

### ISSUE THREAD

**Issue by mdhari** [sparkle-project/Sparkle#854]
Trying to track down an issue one of my users is having. He is experiencing that the app starts to slow down and become sluggish after so many days of updating the app. He never actually closes the app, he just updates every time he is able to. You can assume he doesn't shut down his machine too. 

I went through the source and I can see there is a NSTask to terminate the current app and launch the new patched one. I just wanted to see if its something you guys have experienced. Maybe it's a a shared resource on my end not getting cleaned up to, so I'm continuing to investigate.

**Comment by pornel** [comment]
The actual installation (patching, copying) starts only when the app is terminating. AFAIK during normal operation we only fetch things from the network. 

If I remember correctly your updates were GB in size, so maybe saving tmp files for downloads in background causes some trashing, but I don't expect it to have long, noticeable effect.

**Comment by mdhari** [comment]
Sorry, I probably meant the point of time when you tell the user to restart the app for the changes to take effect, does that restart have any possible side effects. 

Does it really patch as it terminates? I was under the assumption that Sparkle copies the app to a tmp directory, applies the patch on top of that, and then prompts the user to restart. When the user does click that button, then a copy of the patched app goes to the /Applications directory and terminates the current running app and launches the new app.

By the way, we were able to keep the patch size under 40 MB by splitting the file up.

**Comment by zorgiepoo** [comment]
@mdhari You're right - the patching is done before Sparkle starts the task to wait for the application to terminate. When the user clicks that button, Sparkle also tries to terminate the application it is inside.

If the user has automatic updates enabled (which are silent), the patching will be done in the background on a separate thread after the update is downloaded, and the task will be started as the application is about to terminate.

One idea is using Instruments to see is any/significant amount of memory is consumed or leaked after applying a delta update.
