### ISSUE TITLE
Developer ID Codesign

### ISSUE THREAD

**Issue by overtake** [sparkle-project/Sparkle#856]
Hi. I want sign Application with Developer ID. But i can't sign Sparkle.framework 

"bundle format is ambiguous (could be app or framework)"

How to fix this?

**Comment by pornel** [comment]
Are you using xcode 8 beta?  #822

**Comment by overtake** [comment]
@pornel  no. 7.3.1

**Comment by overtake** [comment]
resolved. thanks ;)
