### ISSUE TITLE
Doesn't build for distribution if cocoapods not installed

### ISSUE THREAD

**Issue by sanfords** [sparkle-project/Sparkle#860]
The offending line of make-release-package.js:

`spec_version=$(printf "require 'cocoapods'\nspec = %s\nprint spec.version" "$(cat "$SRCROOT/Sparkle.podspec")" | LANG=en_US.UTF-8 ruby)`

Thank you!

**Comment by zorgiepoo** [comment]
@jakepetroules is it possible to print a warning if cocoa pods is not installed or some such instead of failing? `Gem::Specification::find_all_by_name('cocoapods').any?` may work as a test (from this [SO thread](http://stackoverflow.com/questions/1032114/check-for-ruby-gem-availability)).

**Comment by kolpanic** [comment]
I'm trying to do a release build of the `ui-separation-and-xpc` branch, and I'm seeing this too. The culprit is "sanity check" [here](/sparkle-project/Sparkle/blob/master/Configurations/make-release-package.sh#L5).

**Comment by kornelski** [comment]
`which pod` may also work on Bash level. 

Does anyone want to make a pull request for this?

**Comment by kolpanic** [comment]
@kornelski According to [this answer](https://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script#677212), `which` should be avoided for this kind of thing. I created #1170 using the preferred approach mentioned there.

**Comment by kornelski** [comment]
Thanks for the PR.

**Comment by kolpanic** [comment]
@kornelski My pleasure. Thanks for you work.

BTW, my PR was to` ui-separation-and-xpc`. I don't know how you want to get this fix onto `master`—possibly by cherry-picking?
