### ISSUE TITLE
Sparkle uses host app identity to verify bundle updates

### ISSUE THREAD

**Issue by sergeche** [sparkle-project/Sparkle#863]
I’m building a TextMate 2 custom plugin (e.g. bundle) and want to add plugin autoupdate feature.

Here’s init code for updater from my bundle:

```swift
let bundle = NSBundle(forClass: self.dynamicType)
updater = SUUpdater(forBundle: bundle)
updater.checkForUpdates(self)
```

Update check works fine: it displays my bundles’ icon, name and version; downloads and extracts update. The problem is in “Install & Relaunch” phase: instead of checking codesign identity of my bundle, it uses identity of host app (e.g. TextMate 2) which, of course, differs from mine and there’s no way to install bundle update.

Am I missing something? How can I tell Sparkle to use bundle’s identity?

**Comment by zorgiepoo** [comment]
I think you can get by if you use DSA signatures described on the [documentation page](https://sparkle-project.org/documentation/), although it does point out a flaw in the verification process.

**Comment by sergeche** [comment]
I did, but it doesn’t help: Sparkle still uses host app’s codesign identity to verify my bundle

**Comment by zorgiepoo** [comment]
If DSA keys are available and match, it should then [not match](https://github.com/sparkle-project/Sparkle/blob/master/Sparkle/SUBasicUpdateDriver.m#L335) the Apple code signatures.

**Comment by sergeche** [comment]
Yes, it worked, but only after I disabled bundle codesigning. If bundle is codesigned it still tries to compare identities.

Thanks!

**Comment by zorgiepoo** [comment]
@sergeche we just merged in changes that should resolve this by using your bundle instead of the host app.
