### ISSUE TITLE
Bug: Calling installUpdatesIfAvailable will disable checkForUpdates

### ISSUE THREAD

**Issue by denniss** [sparkle-project/Sparkle#864]
Hi guys,

I am building a background app and in `applicationDidFinishLaunching`, I am doing the following: 

```
let updater = SUUpdater.sharedUpdater()
if updater.automaticallyChecksForUpdates && updater.automaticallyDownloadsUpdates {
    updater.installUpdatesIfAvailable()
}
```

However, I think doing this will put the updater in a bad state. When it does not find any update to download or install, calling `checkForUpdates:_` will just just return because this line in `checkForUpdatesWithDriver` will always return true:

`if ([self updateInProgress]) { return; }`

**Comment by denniss** [comment]
My current hacky solution to this:

```
class UpdaterController : NSObject, SUUpdaterDelegate {
    
    static let sharedInstance = UpdaterController()
    
    func updaterDidNotFindUpdate(updater: SUUpdater!) {
        if let driver = updater.valueForKey("driver") {
            driver.performSelector(Selector("abortUpdate"))
        }
    }
}
```

It looks like the behavior I mentioned above happens because of this method

```
- (void)didNotFindUpdate
{
    if ([[self.updater delegate] respondsToSelector:@selector(updaterDidNotFindUpdate:)])
        [[self.updater delegate] updaterDidNotFindUpdate:self.updater];
    [[NSNotificationCenter defaultCenter] postNotificationName:SUUpdaterDidNotFindUpdateNotification object:self.updater];

    if (!self.automaticallyInstallUpdates) {
        NSAlert *alert = [[NSAlert alloc] init];
        alert.messageText = SULocalizedString(@"You're up-to-date!", "Status message shown when the user checks for updates but is already current or the feed doesn't contain any updates.");
        alert.informativeText = [NSString stringWithFormat:SULocalizedString(@"%@ %@ is currently the newest version available.", nil), [self.host name], [self.host displayVersion]];
        [alert addButtonWithTitle:SULocalizedString(@"OK", nil)];
        [self showAlert:alert];
        [self abortUpdate];
    }
}
```

I am setting `automaticallyInstallUpdates` to true and because of that, `[self abortUpdate];` does not get called.

**Comment by zorgiepoo** [comment]
Looks like a bug that `abortUpdate` is not called. Good catch!

I'd really like to argue for removing `-installUpdatesIfAvailable` instead of fixing it though.. because I think it's implemented in a pretty hacky way (passing a boolean flag around everywhere), and because I think it exposes a poor user interface :/.

You may want to do something like this instead:

```swift
let updater = SUUpdater.sharedUpdater()
if updater.automaticallyChecksForUpdates {
    // If the updater is set to automatically download updates and is allowed to,
    // this will download the update silently in the background.
    // In that case you can use -[SUUpdaterDelegate updater:willInstallUpdateOnQuit:immediateInstallationInvocation:]
    // to expedite the installation without disrupting the user.
    // If the updater is not allowed to automatically download updates (i.e. it's disabled or
    // user needs to be presented permission to authenticate), then the release notes will show up
    updater.checkForUpdatesInBackground()
}
```

**Comment by denniss** [comment]
I'd say that this feature is pretty nice for background apps. Ideally it shouldn't show a modal when checking for update or installing. Everything should just happen in the background transparently for the user.

**Comment by zorgiepoo** [comment]
The issue with `-installUpdatesIfAvailable` is:

* It presents UI even when Sparkle has sufficient privileges to install the update silently without disrupting the user. Please see the tactic I mentioned above for doing what you want.
* When it's impossible to install updates silently because Sparkle has insufficient privileges or the developer/user has not opted into it, it really annoys the user, and they can always decide to cancel the installation if it requires authentication anyway.

What you want is possible when sufficient privileges are available, but you can't use `-installUpdatesIfAvailable` to achieve it.

**Comment by denniss** [comment]
@zorgiepoo Thanks for the help and sorry for not responding sooner. Do you happen to know a method that I can call that will automatically close and re-install the app? It looks like this

`[SUUpdaterDelegate updater:willInstallUpdateOnQuit:immediateInstallationInvocation:]`

Or does doing `[invocation invoke]` launches the install and restart?

**Comment by denniss** [comment]
Nevermind just tried it and it works! Thanks!

**Comment by zorgiepoo** [comment]
To clarify, it will install on quit if you don't invoke the invocation. That method will only be called if the update is downloaded in the background silently. That may not happen if the user does not have write permissions to your app however (eg: say a non-admin updating an app in /Applications/), in which case the normal update alert will pop up, which I think is reasonable.
