### ISSUE TITLE
Prevent accidental installation

### ISSUE THREAD

**Issue by gnachman** [sparkle-project/Sparkle#866]
Sparkle's window comes up at random times, possibly while the user is typing. If they happen to press enter at just the wrong moment, then a new version gets installed.

When Sparkle's "new update available" alert appears not because of a user-initiated action, it should not have a default action for a second or two to prevent the user from accidentally initiating an update.

**Comment by pornel** [comment]
Yes, that's a good idea. Are you able to implement it?

**Comment by iosdeveloper** [comment]
Can you not prevent it from doing that from one of the delegate methods?

**Comment by gnachman** [comment]
I'll take a look when I get a chance, may be a while. I don't think the right delegate interfaces are there (it's tricky to distinguish user-initiated vs automatic updates)

**Comment by pornel** [comment]
I don't think delegates can do that. It would be easier to modify Sparkle's own xibs/controllers.

**Comment by iosdeveloper** [comment]
Return `NO` from `
-[SUUpdaterDelegate updaterMayCheckForUpdates:]` while editing?

**Comment by pornel** [comment]
I've was thinking about the suggestion to disable the default action button for a second or two.

**Comment by gnachman** [comment]
> Return NO from -[SUUpdaterDelegate updaterMayCheckForUpdates:] while editing?

That's a blunt instrument. Would be much nicer to notify the user of an update but narrowly tailor a solution to fix the accidental update issue, like disabling the default status of the button for a bit as @pornel says.

**Comment by pornel** [comment]
I wonder if we could check if app's focus is in a text field, or maybe count time since last key press and mouse click, and delay update alert for a minute if user seems active.

**Comment by zorgiepoo** [comment]
I think the easiest short term solution would be to disable default action for a second or two. Perhaps you can use idle time there to detect if the action should be disabled, but not necessary. Most optimal solution may  have a UI where this doesn't matter but we don't have that.

**Comment by gnachman** [comment]
Default behavior should be to disable default action briefly for non-user-initiated updates. Optional delegate method can specify whether to disable and duration of disablement.

**Comment by zorgiepoo** [comment]
Sounds good-ish. However I wouldn't want a delegate method added until/if somebody has a need for it. There is an edge case of a schedule update showing up right on launch as well - perhaps it should not be disabled if the app has been running for a second or few.

**Comment by zorgiepoo** [comment]
Implemented but we should fix this so we don't disable default action near launch. #924
