### ISSUE TITLE
Provide a "prompt" for authorization

### ISSUE THREAD

**Issue by gnachman** [sparkle-project/Sparkle#868]
When Sparkle needs to get authorization to install over the host bundle, it pops an auth dialog:

![image](https://cloud.githubusercontent.com/assets/427546/17833304/2aea7558-66ce-11e6-8115-8993fd6ff7ff.png)

It would be nice to customize this dialog by providing a custom prompt explaining what's going on. For an example, see cocoasudo here: https://github.com/performantdesign/cocoasudo

The change to `-[NSFileManager _copyPathWithForcedAuthentication:toPath:error:]`'s call to `AuthorizationCreate` would be something like:

```
    AuthorizationEnvironment myAuthorizationEnvironment;
    AuthorizationItem kAuthEnv[1];
    myAuthorizationEnvironment.items = kAuthEnv;

    const char *prompt = "Sparkle needs permission to upgrade <application name>.";
    kAuthEnv[0].name = kAuthorizationEnvironmentPrompt;
    kAuthEnv[0].valueLength = strlen(prompt);
    kAuthEnv[0].value = prompt;
    kAuthEnv[0].flags = 0;

    myAuthorizationEnvironment.count = 1;
    authStat = AuthorizationCreate(NULL, &myAuthorizationEnvironment, kAuthorizationFlagDefaults, &auth);
```

This produces a nicer prompt, like this:

<img width="555" alt="screen shot 2016-08-20 at 12 08 37 pm" src="https://cloud.githubusercontent.com/assets/427546/17833316/db3280e0-66ce-11e6-86d0-01b93cff50a6.png">

**Comment by zorgiepoo** [comment]
Yeah, I handled this for my [fork](https://github.com/zorgiepoo/Sparkle). Somewhere days/months ago in the repo history is code that passes authorization prompt info to the `SUFileManager`, that was more compatible with the deprecated authorization API the official branch uses. There are some edge cases to handle with getting the app icon to show up, and have it work on older systems (eg: 10.8).

**Comment by zorgiepoo** [comment]
Done in Sparkle 2 (and maybe was done in 1 but don't remember).
