### ISSUE TITLE
What's the difference between UpdaterWillInstallUpdateOnQuit and UpdaterWillInstallUpdate in the SUUpdaterDelegte ?

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#869]
What's the difference between UpdaterWillInstallUpdateOnQuit and UpdaterWillInstallUpdate in the SUUpdaterDelegte ?

At what stage would each be called ?

**Comment by pornel** [comment]
`willInstallUpdateOnQuit` is poorly named. It's called when an update is scheduled to be installed later.

`willInstallUpdate` is called immediately before the actual installation.

**Comment by prasha6** [comment]
Thanks!
