### ISSUE TITLE
New Update available when there is pending update yet to be installed

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#870]
How does Sparkle handle the following scenario:

When AutomaticallyDownloadUpdates is turned on, Sparkle downloads the update in background and schedules it for installation when the app quits.
What if the user doe not quit the app for a long time, and there is a new update available ? Would Sparkle download this new update or would it skip ?

**Comment by zorgiepoo** [comment]
Sparkle prompts the user that an update is available if a week has gone by without them quitting the application after downloading the update in the background automatically.

**Comment by prasha6** [comment]
Thanks Mayur!
Scenario:
8AM: Update 1 gets downloaded automatically in the background
11AM: I release a new update - Update2
1PM: The user quits the app - Would update 1 be installed or update 2 be installed ?

Thanks,
Prashanth

**Comment by zorgiepoo** [comment]
Update 1 would be installed, the app won't know about update 2.

I should mention that the update is canceled if the system is powering off.

**Comment by prasha6** [comment]
Yes! This is exactly my problem.
How can I have sparkle download update 2 ? Do you have any idea ?

**Comment by zorgiepoo** [comment]
Ah, okay, I see now. You can speed up installing update 1 by handling `-updater:willInstallUpdateOnQuit:immediateInstallationInvocation:` and rebooting the app, but this may only work nicely for backgrounded apps where the user may not easily notice.

Or the user can trigger manually check for updates, which should check for the latest update (as a consequence this may re-download the update if there is no newer update).

Not sure if there's another way.

**Comment by prasha6** [comment]
Yes, I want to do the second approach, where the user can  manually trigger check for updates.
However, i see that Sparkle does not find a valid update even though a newer update is available.

I did the following test:
I had sparkle:version = 4.0 in the appcast.xml and the update was downloaded.
After the update was downloaded, I changed sparkle:version = 5.0 in the appcast.xml
Now I trigger the manual check for updates from the app; I am expecting sparkle to download version 5.0, but it doesn't download.

**Comment by zorgiepoo** [comment]
It works for me using the Sparkle Test App. If you're interested, it stores the appcast xml somewhere in `~/Library/Caches/org.sparkle-project.SparkleTestApp/` (path may slightly differ depending on if you're building from master or not).

**Comment by zorgiepoo** [comment]
In fact, you don't need to even change the version in the appcast. If the user triggers a manual check for updates, the previous update downloaded in the background is aborted, and sparkle should check for the update again, and let the user download it.

**Comment by prasha6** [comment]
oh Really! This is exactly the behavior that I wanted. For some reason, this doesn't happen in my app. I'll spend some more time to see what's wrong.

Are you sure the previous download gets aborted and sparkle checks for the update again ? I invoke CheckForUpdatesInBackground() to check for updates.

**Comment by prasha6** [comment]
Do you mean with each call to CheckForUpdatesInBackground(), a new update check happens that deletes the previously downloaded update and  re-downloads the latest update ?

**Comment by zorgiepoo** [comment]
Ah, `-checkForUpdatesInBackground` is not a user initiated check. I was talking about `-checkForUpdates:`. `-checkForUpdatesInBackground` will stop if an update has been downloaded in the background.

**Comment by prasha6** [comment]
oh!! All the update checks in my app are done programmatically through "CheckForUpdatesInBackground". Is there a way I can get the behavior using CheckForUpdatesInBackground?

**Comment by zorgiepoo** [comment]
Not in a way that we directly support, as far as I know. Any reason you are not using `-checkForUpdates:`? `-checkForUpdatesInBackground` can be called by Sparkle periodically, and it might be a waste to remove the download.
