### ISSUE TITLE
Check for updates is disabled if an update is already downloaded

### ISSUE THREAD

**Issue by danielchasehooper** [sparkle-project/Sparkle#871]
We've had a lot of bug reports/customer support questions from people trying to update but couldn't because the file > check for updates was greyed out. From what we can tell, it's greyed out because the update had already been downloaded, and would install on next launch. This is very misleading: people believe an update isn't available when it has actually already downloaded.

I'll leave it up to you to decide how to deal with it, but on our project we worked around this by always enabling "check for updates" and if the update is already downloaded, it gives the user the choice to install it now or install it on next launch.

**Comment by pornel** [comment]
Yes, that may be a better approach.

**Comment by zorgiepoo** [comment]
As far as I know, the current behavior is *supposed* to still allow a user initiated check for updates. See https://github.com/sparkle-project/Sparkle/issues/870 . Could be a bug in the menu item validation, will take a look at it later.

**Comment by zorgiepoo** [comment]
A simple fix is submitted in #872. It may not be ideal but it matches the behavior of what this code intended for.

**Comment by danielchasehooper** [comment]
@pornel @zorgiepoo So in the case that the update is still downloading in the background, the behavior is the same as before? ("check for updates" is greyed out?) This is problematic if the update takes a long time to download (large update or slow connection) - is it possible to give better feedback in this situation? Maybe show a download progress window?

**Comment by zorgiepoo** [comment]
It might be possible to have the automatic update driver interruptible and aborted even while the update is downloaded... still kind of an unfortunate situation. I don't believe the code would be easy to change such that UI shows up in the middle of the downloader/extraction progress.

One thing I'd personally look into is [delta updates](https://sparkle-project.org/documentation/delta-updates/) for smaller downloads.

**Comment by danielchasehooper** [comment]
It seems like the UI/updater separation you're doing on your fork could help with this.

Our updates are already ~5mb. I'd to fix the root problem, otherwise there will always be that unfortunate person that checks for updates during the 2 seconds it's downloading in the background and the option is disabled, so they email us - making a bad experience for everyone.

**Comment by zorgiepoo** [comment]
My fork doesn't have "interrupting", so while it saves the user from downloading 5 MB again, the user can't do much while it's downloading in the background.

I think the simple fix I submitted, while not perfect, may significantly reduce the number of reports you may be get.

**Comment by zorgiepoo** [comment]
Resolved at some point, except for small window while update is still downloading.
