### ISSUE TITLE
launch path not accessible

### ISSUE THREAD

**Issue by Riste196** [sparkle-project/Sparkle#880]
Hello,

I added Sparkle library to my project but I see some issues so if you can guide me I would appreciate it. Here are the steps that I am doing.

I have Developer ID Application Certificate, I created a Developer ID provisioning profile to use Apple services with the Developer ID signed applications. 
I am downloading the Profile and installing it. When going in XCode I don't see the Provisioning profile under Code Signing Identity in Build Settings, so I am downloading from Xcode>Preferences>Accounts.
Next I am selecting the Provisioning profile but when I am building I am getting error: 
Your build settings specify a provisioning profile with the UUID "some number" however, no such provisioning profile was found. I am clicking fix issue and I am able to start the application. 

I added appcast to our server, created pem files I added DSA signature.

Than created one archive that I added on the server and I am starting the application from XCode
Everything from Sparkle is ok, every pop up is shown, except the last step when I click “Install and Relaunch” I get this error:
“Sparkle: Failed to release quarantine on /Users/name/Library/Containers/bundleID/Data/Library/Caches/bundleID/Sparkle/Autoupdate.app with error Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={NSLocalizedDescription=Failed to remove file quarantine on Autoupdate.app.}
launch path not accessible
“

Thanks
Riste

**Comment by pornel** [comment]
The title of the issue quotes a different error than what you quote in the issue. Did you get signing work in the end?

"Failed to release quarantine" itself shouldn't be a big deal. The error you quote suggests that your system doesn't have `/usr/bin/xattr` or that the app is somehow blocked from running it.

**Comment by Riste196** [comment]
Yes sorry about the title, I changed now. I think that the signing and DSA is now ok.
I checked and I found /usr/bin/xattr from finder, so that is existing. I have OSX El Capitan 10.11.3 It is not locked.

**Comment by zorgiepoo** [comment]
Are you trying to sandbox your app? If you are (I see a /Library/Containers/ path), see issue #363

**Comment by Riste196** [comment]
It worked, just changed sandbox flag to NO and it is ok now. Thank you for your help.
