### ISSUE TITLE
Reboot after guided pkg install

### ISSUE THREAD

**Issue by ghost** [sparkle-project/Sparkle#887]
Hi,

Thanks for Sparkle. It's been a huge help. I wonder if there's any way Sparkle could honor the reboot flag in a macOS pkg file when doing a guided install, and prompt the user to reboot? Doesn't seem to do it at the moment.

**Comment by pornel** [comment]
Currently it's not possible. 

I'm not sure how to add it, because our standard UI already has a "Restart" button, and it would be an unpleasant surprise if it restarted *all* applications and the entire system.
