### ISSUE TITLE
Doesn't compile on El Cap

### ISSUE THREAD

**Issue by bumblebritches57** [sparkle-project/Sparkle#890]
`The following build commands failed:
    Ld /var/folders/0w/mtvq0y_j557dbpw77yfpzhfm0000gn/T/Sparkle.ojGjqH/Build/Products/Release/Sparkle.framework/Versions/A/Sparkle normal x86_64
    GenerateDSYMFile /var/folders/0w/mtvq0y_j557dbpw77yfpzhfm0000gn/T/Sparkle.ojGjqH/Build/Products/Release/Sparkle.framework.dSYM /var/folders/0w/mtvq0y_j557dbpw77yfpzhfm0000gn/T/Sparkle.ojGjqH/Build/Products/Release/Sparkle.framework/Versions/A/Sparkle
    Ld /var/folders/0w/mtvq0y_j557dbpw77yfpzhfm0000gn/T/Sparkle.ojGjqH/Build/Products/Release/Sparkle\ Test\ App.app/Contents/MacOS/Sparkle\ Test\ App normal x86_64
    GenerateDSYMFile /var/folders/0w/mtvq0y_j557dbpw77yfpzhfm0000gn/T/Sparkle.ojGjqH/Build/Products/Release/Sparkle\ Test\ App.app.dSYM /var/folders/0w/mtvq0y_j557dbpw77yfpzhfm0000gn/T/Sparkle.ojGjqH/Build/Products/Release/Sparkle\ Test\ App.app/Contents/MacOS/Sparkle\ Test\ App
    Ld /var/folders/0w/mtvq0y_j557dbpw77yfpzhfm0000gn/T/Sparkle.ojGjqH/Build/Products/Release/BinaryDelta normal x86_64
    GenerateDSYMFile /var/folders/0w/mtvq0y_j557dbpw77yfpzhfm0000gn/T/Sparkle.ojGjqH/Build/Products/Release/BinaryDelta.dSYM /var/folders/0w/mtvq0y_j557dbpw77yfpzhfm0000gn/T/Sparkle.ojGjqH/Build/Products/Release/BinaryDelta
    ExternalBuildToolExecution Distribution
(7 failures)
make: *** [release] Error 65`

**Comment by pornel** [comment]
Do you use beta version of Xcode?

Have you tried cleaning build folder?

**Comment by bumblebritches57** [comment]
I'm using the App store version of Xcode 8.

I just emptied the DerivedData folder, and now it's complaining about XCTest. I've added that framework to every target because why not?

Removing XCTest from all but the test targets fixed it.
