### ISSUE TITLE
Downloading newer updates when AutomaticallyDownloadUpdates is enabled

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#891]
Assume my app has AutomaticallyDownloadUpdates enabled.
For the following situation:

Day 1: I roll out an update to my app (Update #1). Sparkle automatically downloads this update, and schedules for installation on app quit.
Day 3: I roll out another update to my app (Update #2).The user hasn't quit the app until now.

Day 4: when the user quits the app, the update #1 gets installed.

However, I want Update #2 to be installed. 
Would setting SUScheduledCheckInterval to 86400 seconds allow the app to install the update #2 ?

Currently, my app does not have any setting for the SUScheduledCheckInterval.

**Comment by pornel** [comment]
No, check interval doesn't change that behavior. The user must restart the app first.

**Comment by prasha6** [comment]
So, Unless the user manually checks for updates, how could Sparkle support this scenario of downloading a later update when a previous update has already been downloaded ?

**Comment by zorgiepoo** [comment]
There isn't support for that currently. #244 is also related with this.

I don't think this would be easy to change onto the current architecture, for it to be worth considering. This is an edge case that isn't dealt with too badly currently.
