### ISSUE TITLE
Any way to set the updater windows level

### ISSUE THREAD

**Issue by orklann** [sparkle-project/Sparkle#893]
My app creates a top-most fullscreen window which has `NSMainMenuWindowLevel`, and when there is an update available, the updater window is below my top-most window and can not be clicked, I want to know is there any way to set the updater windows level, so that it can sit above my top-most window?

**Comment by pornel** [comment]
We don't have such option currently. Maybe you could use delegate methods to detect when we show update window, and quit full screen?

We're also considering using system notifications #924. Do they show up when your app is in full screen?

**Comment by zorgiepoo** [comment]
Our windows (at least in 2.2) collection behavior is set to fullscreen auxiliary, so they should show up in normal fullscreen mode.
