### ISSUE TITLE
Doesn't compile under Xcode 8

### ISSUE THREAD

**Issue by alex-techlab** [sparkle-project/Sparkle#894]
Every time I try to compile my app I get this error:
```
ProcessProductPackaging "" /Users/****/Library/Developer/Xcode/DerivedData/****-awxjijlsawaqzfelmynfcqkcmtqo/Build/Intermediates/****.build/Debug/****.build/Sparkle.framework.xcent
    cd "/Users/****/Desktop/swift projects/****_sources"
    builtin-productPackagingUtility -entitlements -format xml -o /Users/****/Library/Developer/Xcode/DerivedData/****-awxjijlsawaqzfelmynfcqkcmtqo/Build/Intermediates/****.build/Debug/****.build/Sparkle.framework.xcent

error: The data couldn’t be read because it isn’t in the correct format.  
```
This happens with Sparkle 1.14.0 downloaded from sparkle-project.org
- XCode 8.0 (8A218a)
- macOS 10.12
- The project was converted from Swift 2.2 to Swift 2.3

It used to work with XCode 7.3 on 10.11. 
Just to be sure I re-downloaded the framework and re-added it to my project.

**Comment by sebarina** [comment]
I have the same issue, have you solved it?

**Comment by pornel** [comment]
I can't reproduce the problem on my machine. Perhaps it's caused by some old temporary files from the previous version of Swift? Product -> Clean Build Folder (press Alt if the option is hidden) might help.
