### ISSUE TITLE
Relaunch for Automatic updates

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#895]
Hi,
I want to support the following scenario using Sparkle framework:
"If an automatic update has been downloaded in the background and scheduled for installation, I have a custom notification banner like UI that has a restart button - the user can click the button, and the app should relaunch with the updated bits." How could I use sparkle to enable the Relaunch logic for auto updates.

I am thinking of 2 approaches here:

First Approach: In my application code - I could just restart the app(new ProcessStartInfo(app)), when the user closes the app and there is a downloaded update that is ready to be installed.

But, the drawback in this is that I am assuming sparkle would have completed installation before I relaunch the app; there is no contract between my app and sparkle, where sparkle lets my app know that the installation is complete and a relaunch would actually launch the updated app.

Second Approach:  I considered using the delegate UpdaterShouldRelaunchApplication and make this return true; but this doesn't make the app relaunch.

Do you have any suggestions on how I could use sparkle to enable such a scenario ?

**Comment by zorgiepoo** [comment]
See https://github.com/sparkle-project/Sparkle/issues/850 for the delegate method you'd be interested in. This delegate method is only invoked for updates downloaded in the background silently.
