### ISSUE TITLE
Detecting that we're quitting for an update

### ISSUE THREAD

**Issue by koralcem** [sparkle-project/Sparkle#899]
Not an issue per se, but I couldn't find a way to ask a question to all maintainers. If there is a way, please let me know and just close this issue.

Our app asks the user to confirm whether they'd like to quit in `applicationShouldTerminate:`. This is normally fine, but it becomes awkward when you're about to do an update. You're prompted by Sparkle whether you'd like to quit & restart, you say "Yes", then we ask whether you'd like to quit since execution now got to `applicationShouldTerminate:` 😒 

Is there a way to detect whether we're quitting because of a pending update, so we can avoid asking the user again?

It occurs to me as I write this that we could ask the user to confirm quitting in the handling of the quit menu item, and not put anything on the `terminate` path... And that might work, but I'm still curious to hear your suggestions for dealing with this issue.

**Comment by pornel** [comment]
There are delegate methods `updaterWillRelaunchApplication` `updater:willInstallUpdateOnQuit:immediateInstallationInvocation:`.

**Comment by koralcem** [comment]
Perfect! Thanks a lot.
