### ISSUE TITLE
How to determine if a didNotUpdate occurred from sparkle:minimumSystemVersion

### ISSUE THREAD

**Issue by mdhari** [sparkle-project/Sparkle#900]
I seem to be having a lot of trouble capturing when an update isn't occurring because of the minimum macOS requirement I put in the appcast. Is there some way I can capture this? I want to be able to message my users that they need to upgrade their macOS before updating to the latest app version.

Since I am extending the SUBasicUpdateDriver class, I thought overriding this function would be appropriate:

`override func itemContainsValidUpdate(ui: SUAppcastItem!) -> Bool`

But ui is being passed nil. Is there someway I can do this with the delegate from SUUpdater?

**Comment by zorgiepoo** [comment]
#689 is related and might give you some insight. Personally I would give some thought into if alerting the user that is hostile or not.

**Comment by mdhari** [comment]
Thanks for sharing that. 👍 

Too bad it hasn't been merged yet. Guess I'll hack away a little bit.
