### ISSUE TITLE
UX: Default behaviour interrupts my workflow, makes me wait and then demands restart?

### ISSUE THREAD

**Issue by joeytwiddle** [sparkle-project/Sparkle#901]
My only experience of Sparkle is through MacVim. ([See the issue raised there.](https://github.com/macvim-dev/macvim/issues/390))

I don't know if MacVim is using the default Sparkle configuration or not. But here is why the process bugs me:
- It tells me there is an update randomly **in the middle of using the app**, while I am working.
- I would like the option of "OK cool, auto-update later, when the app next closes or opens" but I am instead given the options "Update now" or "Remind me later".
- If I select "Remind me later" then I just get the same experience at some point in future.
- If I select "Now" I then have to **wait a short while for the download** to happen (during which time I can still use the app).
- When the download completes, a dialog box appears which **demands that I restart the app**, and it cannot be closed! But I don't want to restart, because I want to keep the current state of the app. (Fortunately I can still use the app. I just have to leave the restart dialog on my desktop for hours/days/weeks until I am finished on the project!)

Here is what I think would be better:
- <strike>Sparkle checks for update on startup (rather than in the middle of my workflow).</strike> (*)
- I am given the option to "Download in the background and apply on next restart". (Ask this before, not after the download.)
- I am also given the option to "Do that automatically and silently in future".

Although the current process does work, I think these additional improvements to the UX could make it just perfect. Cheers!

(*) Happily I found the option for this in MacVim's preferences. Perhaps there is a good reason you don't make that a default ... to spread server load around the clock perhaps? I am happy to forgo this feature if the others are available.

**Comment by zorgiepoo** [comment]
MacVim is probably using a default configuration of Sparkle. I agree that the user experience can be a little intrusive for some use cases.

Some apps I use do only check for updates on launch (mostly backgrounded apps). Developers would have to opt into / implement that themselves though. The default is to assume that users that never quit an app should probably be alerted of updates else they may never update.

In the software update prompt that shows the release notes, there should be a checkbox to download updates in the background silently and automatically. This option is not available if administrator privileges are required to perform updates however (in which case the user needs to be prompted a password dialog to install an update).

The other points raised would be solved by having a better installation logic and by showing a better/customized user interface (#127). My [fork](https://github.com/zorgiepoo/Sparkle) of Sparkle provides the means of handling that, but alas, it's unofficial.

**Comment by zorgiepoo** [comment]
Handling more gentle reminders in #924
