### ISSUE TITLE
DSA Signatures Break If Update Archive Keeps The Same Name

### ISSUE THREAD

**Issue by bdkjones** [sparkle-project/Sparkle#904]
Hi Sparkle. This one just cost me about 3 hours of my life. Details:

### Summary

Sparkle appears to incorrectly select the DSA signature to use when two entries in the update feed share the same archive name.

### Demo

Example Appcast File entries:

```
<item>
    <title>Version 3.0.1</title>
    <sparkle:releaseNotesLink>https://codekitapp.com/updates/sparkle.html</sparkle:releaseNotesLink>
    <pubDate>Saturday, 29 October 2016 20:00:00 -0700</pubDate>
    <enclosure url="https://codekitapp.com/binaries/codekit.zip" sparkle:version="25390" sparkle:shortVersionString="3.0.1" length="56306769" sparkle:dsaSignature="MCwCFBlqWiHWGyDD0uqOAXyDb1thfZF2AhQ9jatXdAArqH+mWlozpe8Bpk/vyg==" type="application/octet-stream"/>
    <sparkle:minimumSystemVersion>10.11</sparkle:minimumSystemVersion>
</item>

<item>
    <title>Version 3.0</title>
    <sparkle:releaseNotesLink>https://codekitapp.com/updates/sparkle.html</sparkle:releaseNotesLink>
    <pubDate>Wednesday, 26 October 2016 18:00:00 -0700</pubDate>
    <enclosure url="https://codekitapp.com/binaries/codekit.zip" sparkle:version="25378" sparkle:shortVersionString="3.0" length="56305734" sparkle:dsaSignature="MCwCFDl/hM1o3DeBQw6RlPP8XKlLIGzwAhQ+lqH3I6pCOXmb9naBKm/siMTnTg==" type="application/octet-stream"/>
    <sparkle:minimumSystemVersion>10.11</sparkle:minimumSystemVersion>
</item>
```

### Explanation

Above, I have two entries in my appcast that point to `codekit.zip`. When I test this update from build `25378` (the older of the two entries), Sparkle correctly informs me that an update is available (`3.0.1`) and it downloads `codekit.zip` and unarchives the zip file. 

However, it then tells me that an update error occurred and if I look in the Sparkle logs, I see that the DSA signature did not match. Well, the DSA signature is absolutely valid for that latest entry in my update feed. If I do either of these things:

1. Use a different archive filename for each entry

or

2. Delete the older feed entry

Then the update works correctly. This implies that Sparkle is, somehow, pulling the DSA signature from the *older* entry in the feed, but using the *newer* entry in the feed for everything else (version numbers, etc.)

### Still a Bug

I used a shared archive name to keep things simple. Since there's no change in the minimum system version, my thought was: "Sparkle will see that this latest update (`3.0.1`) overrides the older one for everyone; there's no case where Sparkle would ever serve that older update."

When it became necessary to maintain an older release (such as when I bump the minimum system version) I would have chosen a different archive name. 

But regardless, this is still a bug. Sparkle isn't choosing the correct DSA signature to verify the archive.

**Comment by zorgiepoo** [comment]
Hi, this sounds really bizarre. I can't reproduce the issue in the test app in master, nor can I actually reproduce the issue using your own application. I created a [custom appcast](https://zgcoder.net/zfw/codekitttttt.xml) for codekit with all the archive names being the same, and pointed your app (at version 3.0) to it, and it seemed to update just fine.

Is there a chance the server was serving the wrong archive? I recall you had similar issues in #802

**Comment by bdkjones** [comment]
It is *possible* that Sparkle was pulling down a cached version. But one of the first things I tested was downloading `codekit.zip` and verifying that it was the `3.0.1` version. I downloaded it via browser. Perhaps there is a difference in how Sparkle is pulling?

**Comment by zorgiepoo** [comment]
I don't know how it exactly works, but In #802, I thought you noticed a difference when a file was downloaded in Sparkle (using `NSURLDownload`) versus from inside your web browser.

By the way, when I first downloaded code kit from your main website using Safari, I had downloaded version 3.0, but now I see it's serving 3.0.1 over there, although I don't know if you had changed anything recently (the page always showed "Version 3.0.1 (25390)" as far as my unreliable memory can tell though).

**Comment by bdkjones** [comment]
Fair enough; I suppose I could take a look at the file sparkle downloads to its temp location, but I'll take your word on the difference.
