### ISSUE TITLE
SUFeedURL in Info.plist or dynamically setting it

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#909]
Hello,

I am using Sparkle 1.14.0. My app has been public for the last few months and I have been rolling out updates through sparkle without any problem. 

However, recently I am having users encounter the following crash:

> _Crashed thread: 0
> uncaught ObjC exception, reason: You must specify the URL of the appcast as the SUFeedURL key in either the Info.plist or the user defaults!_

I have been setting the SUFeedURL  programmatically, instead of info.plist, like the following:
SUUpdater.SharedUpdater.FeedURL = my url;

The thing I can't understand is - while most of the users can successfully update, why are a few users encountering this crash ? Do you have any idea/thoughts/suggestions ?

**Comment by zorgiepoo** [comment]
> I have been setting the SUFeedURL programmatically, instead of info.plist, like the following:
SUUpdater.SharedUpdater.FeedURL = my url;

When in your application's state are you doing this? (in what callback)

**Comment by prasha6** [comment]
hi mayur,
The Update logic for my application is 2 layers: When Layer 1 returns true, then I initiate Sparkle updater.

Example:

> Layer 1: bool GetUpdate()
if this returns true, then I call Layer 2 which in initializing Sparkle Updater.

> Layer 2: InitializeSparkleUpdater()
            SUUpdater.SharedUpdater.Delegate = new UpdaterDelegate();
            SUUpdater.SharedUpdater.FeedURL = new Uri(UpdateUri);

Layer 1 gets called once every 12 hours - So there are chances when InitializeSparkleUpdater() is called multiple times during the lifetime of the application.

**Comment by zorgiepoo** [comment]
Ok. Is your `SUUpdater` instance being instantiated inside a nib? And if so, can the nib be awoken quite a bit before `InitializeSparkleUpdater()` is invoked for the first time? I'm presuming you didn't disable automatic update scheduling anywhere?

**Comment by prasha6** [comment]
No, SUUpdater is not being instantiated in a nib. However, at certain situations, I do call CheckForUpdates(sender).

Example:

> If(updateType == optional)
> SUUpdater.SharedUpdater.CheckForUpdates(sender)
> else if(updateType == Auto)
> SUUpdater.SharedUpdater.AutomaticallyDownloadsUpdates = true;
> SUUpdater.SharedUpdater.CheckForUpdatesInBackground();

**Comment by zorgiepoo** [comment]
Well, I was trying to reason if the `SUUpdater.SharedUpdater` could be invoked a significant amount of time before setting the feed URL (that is, probably before `InitializeSparkleUpdater`). When you set the feed url (as well as other properties like `automaticallyDownloadsUpdates`), that setting is persisted in your application's user defaults, so you can see what happens if you try to clear the `SUFeedURL` defaults key at some point (which I guess an evil user can try to do). There is also some discussion in #898, although I'm not sure my delegate recommendation would help here.

**Comment by prasha6** [comment]
Don't you think the delegate method should always work ? doesn't it get called each time before the update check, whenever the updater requires the feedURL ? 
If I return my appcast url in this delegate method, then likely there won't be any error like " You must specify the URL of the appcast as the SUFeedURL key in either the Info.plist or the user defaults!"

**Comment by prasha6** [comment]
Additionally, would setting the appcast URL in the setFeedUrl delegate method also handle the error case when the settings in user defaults is deleted ?

**Comment by zorgiepoo** [comment]
(See #898 for the continued discussion)
