### ISSUE TITLE
SUInstaller shouldn't check for aliases to folders

### ISSUE THREAD

**Issue by andymatuschak** [sparkle-project/Sparkle#91]
***Hofman (cmhofman)** [reported (on Launchpad)](https://bugs.launchpad.net/sparkle/+bug/504373) on' 2010-01-07:*

SUInstaller checks for alias folders when enumerating the download
folder. First of all, this check is wrong, because FSIsAliasFile does
not return folder info about the target (because for that you need to
resolve the alias, see the docs). Secondly, the check is unnecessary,
because NSDirectoryEnumerator treats aliases to folders as ordinary
files, i.e. it does not enumerate the contents of the target.

**Comment by pornel** [comment]
This code has been refactored.
