### ISSUE TITLE
Empty SUFeedURL

### ISSUE THREAD

**Issue by prasha6** [sparkle-project/Sparkle#910]
How does Sparkle handle empty SUFeedURL ? Is it ok to use empty SUFeedURL for error handling purposes ?

**Comment by zorgiepoo** [comment]
I would not set it to be empty. It looks like to me that passing `nil` to `-setFeedURL:` should remove the persisting user default, falling back to the feed url specified in your app's Info.plist (if available) or the updater's delegate.
