### ISSUE TITLE
Sparkle not updating the feed url that it searches

### ISSUE THREAD

**Issue by CapSkyHook** [sparkle-project/Sparkle#912]
I changed my SUFeedURL in my info.plist but sparkle seems to be searching for my appcast at the old location. I have searched my project for any mention of me setting it explicitly but I can not find anything.

Is there something I need to do beyond changing the value in my info.plist? Thanks!

edit: I managed to get the value to change by setting it programmatically and having it do one successful update and after that it seems to be going to the right url but not related to my info.plist

**Comment by zorgiepoo** [comment]
Yeah, this trips people up.. If you set the feed URL programmatically via the feedURL property, Sparkle will persist that setting in your app's user defaults.

When Sparkle tries to retrieve the feed url, it checks:

1. if the delegate implements `-feedURLStringForUpdater:` or
2. if the feed url is available in the user defaults, or
3. if the feed url is in the app's Info.plist

..in that order of priority.

To remove the persisting user default setting and have Sparkle use your Info.plist feed URL, you can set the feedURL property to nil as soon as the updater is instantiated. Or you can choose to implement the delegate method that supplies the feed url and that will override anything else.

IMO, the feed URL should never be set programmatically via the feedURL property :\.

**Comment by CapSkyHook** [comment]
OK, awesome! Thank you so much!
