### ISSUE TITLE
Query Regarding Release Link in Appcast.xml file

### ISSUE THREAD

**Issue by Ankur0713** [sparkle-project/Sparkle#913]
Hi Team 
Thanks for the great work. We are using version 1.6 due to application requirements

I have below queries , can you guys please reply on the same

1. We are adding html link in the release notes of the appcast.xml file  , when the update pop up 
comes to update the version  a separate pop up also get open and we have to press cancel on the same to return the focus to app. Attaching the screen shot for the same. 

Can you guys  please suggest how to prevent the pop up from coming,  it only comes when we 
add the html link in release notes. 

Thanks in advance

![screen shot 2016-11-09 at 4 21 55 pm](https://cloud.githubusercontent.com/assets/23356392/20135945/5fc7fb4c-a698-11e6-8dc1-c10f25ef7a36.jpg)

**Comment by pornel** [comment]
If you have to use 1.6, *you MUST* apply security patches:

https://sparkle-project.org/documentation/security/

All versions older than 1.13.1 are *UNSAFE*.

The patch also happens to change how the release window behaves. We don't support that version of Sparkle any more, so if it doesn't work (after security patching!) then I suggest you don't use release notes feature, or not use Sparkle at all.

**Comment by zorgiepoo** [comment]
I'll just note you may also want to consider changing your application versioning requirements, especially if it's a new app, which would give less of an incentive to target much older systems.

Release notes can also be [embedded](https://sparkle-project.org/documentation/publishing/) in the appcast.
