### ISSUE TITLE
-[NSThemeFrame lockFocus] failed with window

### ISSUE THREAD

**Issue by mdhari** [sparkle-project/Sparkle#920]
Some of my users are saying when they update, they sometimes see the standard Apple crash reporter show up indicating a crash like so:

Date/Time:             2016-11-15 17:42:23.788 -0500
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12
Anonymous UUID:        3291AAA0-60C4-B721-0E89-DACABBE1CFD6

Sleep/Wake UUID:       C1354AB9-4539-412F-B34D-D48B3EE13E3F

Time Awake Since Boot: 67000 seconds
Time Since Wake:       950 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
Crashing on exception: -[NSThemeFrame(0x7fee9c431190) lockFocus] failed with window=0x6000003f8600, windowNumber=-1, [self isHiddenOrHasHiddenAncestor]=0

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff8dfd148b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffa2733cad objc_exception_throw + 48
2   CoreFoundation                      0x00007fff8dfd6192 +[NSException raise:format:arguments:] + 98
3   Foundation                          0x00007fff8fa09390 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
4   AppKit                              0x00007fff8bd23724 -[NSView lockFocus] + 247
5   AppKit                              0x00007fff8bd21866 -[NSView _displayRectIgnoringOpacity:isVisibleRect:rectIsVisibleRectForView:] + 1159
6   AppKit                              0x00007fff8bd1d662 -[NSView displayIfNeeded] + 1748
7   AppKit                              0x00007fff8bd1cf73 -[NSWindow displayIfNeeded] + 230
8   AppKit                              0x00007fff8c407c2f ___NSWindowGetDisplayCycleObserver_block_invoke.6219 + 277
9   AppKit                              0x00007fff8bd1ca51 __37+[NSDisplayCycle currentDisplayCycle]_block_invoke + 454
10  QuartzCore                          0x00007fff93a611ba _ZN2CA11Transaction19run_commit_handlersE18CATransactionPhase + 46
11  QuartzCore                          0x00007fff93b68e10 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 160
12  QuartzCore                          0x00007fff93a5fd55 _ZN2CA11Transaction6commitEv + 475
13  AppKit                              0x00007fff8bff2c69 __37+[NSDisplayCycle currentDisplayCycle]_block_invoke.31 + 323
14  CoreFoundation                      0x00007fff8df66ec7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
15  CoreFoundation                      0x00007fff8df66e37 __CFRunLoopDoObservers + 391
16  CoreFoundation                      0x00007fff8df47ad9 __CFRunLoopRun + 873
17  CoreFoundation                      0x00007fff8df47514 CFRunLoopRunSpecific + 420
18  HIToolbox                           0x00007fff8d4e4fbc RunCurrentEventLoopInMode + 240
19  HIToolbox                           0x00007fff8d4e4df1 ReceiveNextEventCommon + 432
20  HIToolbox                           0x00007fff8d4e4c26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
21  AppKit                              0x00007fff8bbceb79 _DPSNextEvent + 1093
22  AppKit                              0x00007fff8c2e41c3 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
23  AppKit                              0x00007fff8bbc353d -[NSApplication run] + 926
24  AppKit                              0x00007fff8bb8e1ad NSApplicationMain + 1237
25  MyApplication                       0x00000001011eff04 main + 84
26  libdyld.dylib                       0x00007fffa3012255 start + 1

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.AppKit              	0x00007fff8bf2caee -[NSApplication _crashOnException:] + 109
1   com.apple.AppKit              	0x00007fff8bff2dea __37+[NSDisplayCycle currentDisplayCycle]_block_invoke.31 + 708
2   com.apple.CoreFoundation      	0x00007fff8df66ec7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
3   com.apple.CoreFoundation      	0x00007fff8df66e37 __CFRunLoopDoObservers + 391
4   com.apple.CoreFoundation      	0x00007fff8df47ad9 __CFRunLoopRun + 873
5   com.apple.CoreFoundation      	0x00007fff8df47514 CFRunLoopRunSpecific + 420
6   com.apple.HIToolbox           	0x00007fff8d4e4fbc RunCurrentEventLoopInMode + 240
7   com.apple.HIToolbox           	0x00007fff8d4e4df1 ReceiveNextEventCommon + 432
8   com.apple.HIToolbox           	0x00007fff8d4e4c26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
9   com.apple.AppKit              	0x00007fff8bbceb79 _DPSNextEvent + 1093
10  com.apple.AppKit              	0x00007fff8c2e41c3 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
11  com.apple.AppKit              	0x00007fff8bbc353d -[NSApplication run] + 926
12  com.apple.AppKit              	0x00007fff8bb8e1ad NSApplicationMain + 1237
13  com.me.MyApplication         	0x00000001011eff04 main + 84
14  libdyld.dylib                 	0x00007fffa3012255 start + 1

When they start the App again, it is updated properly. 

Strangely, it just seems like the App was just trying to start after clicking the Install and Restart button. The only thing I've noticed is this effects only Sierra users. Has this been brought up before?

**Comment by zorgiepoo** [comment]
Haven't heard of this issue before and don't see something that looks Sparkle related in your backtrace. Focusing on NSThemeFrame, does your app customize the titlebar to any of its windows by e.g. adding a custom view?

**Comment by mdhari** [comment]
If you mean the bar that has the close, minimize and expand buttons, then
no. Sounds like maybe the initial storyboard view is causing this?

**Comment by zorgiepoo** [comment]
Yeah that's what I meant. Or make sure you're not doing UI stuff or anything updater related on the non-main thread. I'm just taking a wild guess at this point.

**Comment by pparekh7** [comment]
We recently integrated Sparkle into our application and saw this crash once so far. Not reproducible after that though.

I'm sure we don't do updater related stuff or UI stuff on the non-main threads. 

Does anyone have any ideas?

**Comment by kornelski** [comment]
We've fixed a bunch of related issues in 1.20. Please test it.

**Comment by pparekh7** [comment]
Thanks! I was finally able to reproduce this (although not reliably) with a debug build of my product and see that its related to one of the fixes made in 1.20.0. We've moved to this version of Sparkle and hopefully its been fixed. I say, hopefully, because we don't have a reliable, reproducible case.and hopefully its been fixed. I say, hopefully, because we don't have a reliable, reproducible case.
