### ISSUE TITLE
Is it possible to have the updater launch a sub-app on restart?

### ISSUE THREAD

**Issue by alexflint** [sparkle-project/Sparkle#921]
My app bundle contains a sub-app in its Resources dir:

```
Top.app/
  Contents/
    Resources/
      Sub.app
...
```

I wish to use Sparkle to update the whole `Top.app` bundle, but when my app bundle restarts after an update, I would like it to launch `Sub.app` not `Top.app`. Is this possible?

(Also, is there somewhere else I should be asking this?)

**Comment by zorgiepoo** [comment]
This is the correct place to ask questions.

What if the user updates your application manually without the assistance of Sparkle? The user would try to launch Top.app -- is that expected? Should using Sparkle really differ?

p.s. Sub.app should probably be in Contents/Helpers/ or Contents/MacOS/

**Comment by alexflint** [comment]
Yes if the user launches `Top.app` manually then that's fine in my context, but in the case that the restart is triggered within the app and goes via sparkle, and assuming that the nested app is under `Top.app/Contents/MacOS/Sub.app`, is it possible to have sparkle launch `Sub.app`?

**Comment by zorgiepoo** [comment]
You can try implementing `-[SUUpdaterDelegate pathToRelaunchForUpdater:]`, although it was intended to be used by plugins.
