### ISSUE TITLE
Touch Bar Support

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#922]
Sparkle's UI should support the Touch Bar and present additional button options for the update alert window, automatic update alert window, update permission prompt window, and the status window. Anything that uses NSAlert is already handled by the system automatically. No touch bar customization should be allowed.

Note an additional method may need to be added to `SUOperatingSystem.m` to detect if the touch bar is available (if we *have to* detect if it's available that is). Because Apple publicly released two builds of 10.12.1, one which has support for the touch bar, and one that doesn't, we can't query for the OS version - we must use the runtime and do a `NSClassFromString("NSTouchBar") != nil` check.

**Comment by pornel** [comment]
Regarding the OS, we can probably wait for 10.12.2 that has the class and just start supporting from there (the .1 build will eventually become history), assuming the disappearing class is not on purpose.

In general I wonder whether it's something users actually want. Is there a risk of creating a problem similar to focus stealing? i.e. if user was busy using the app and pressing app-specific touchbar buttons, would we cause problems by suddenly replacing app buttons with Sparkle buttons?

**Comment by zorgiepoo** [comment]
> Regarding the OS, we can probably wait for 10.12.2 that has the class and just start supporting from there (the .1 build will eventually become history), assuming the disappearing class is not on purpose.

Much of supporting the touch bar is implementing a method in the window controllers that becomes visible in the responder chain, so there's the possibility we may not even need system detection. Either way, we should avoid a scenario where only *some* of the functionality is available in the more recent 10.12.1 build.

> In general I wonder whether it's something users actually want. Is there a risk of creating a problem similar to focus stealing? i.e. if user was busy using the app and pressing app-specific touchbar buttons, would we cause problems by suddenly replacing app buttons with Sparkle buttons?

This is already a problem and not a new one that the touch bar introduces. Sparkle can prompt the software update window while the user is in the middle of some other task. Chances are if we don't implement touch bar support, the touch bar will transition into an empty-boring state rather than retain whatever it was showing before. Our sparkle update prompt becomes first responder, after all.

**Comment by pornel** [comment]
OK.

BTW, this reminds me that we're not using Notifications yet, but maybe we should: #924

**Comment by ksuther** [comment]
Regarding the comments about 10.12.1 and 10.12.2, basic Touch Bar support doesn't require any runtime checks. If you implement `makeTouchBar` on a responder and then implement the `NSTouchBarDelegate` method then it'll be called automatically by Touch Bar systems and ignored otherwise.

**Comment by zorgiepoo** [comment]
We have a status window controller that changes the button titles and actions. I think we can just get the `NSButton` references that we use for the touch bar and initially set them to nil if the touch bar isn't implemented, and that may work fine. We don't want touch bar customization, so we could indeed probably get away without runtime checks.
