### ISSUE TITLE
Check For updates option is Disabled 

### ISSUE THREAD

**Issue by Ankur0713** [sparkle-project/Sparkle#925]
HI Team ,

The "Check For updates" option in menu item is getting disabled once we install the latest version.

Cant we have it in enabled form and on tapping the same it should show pop up with message " Up 

to date" . Please suggest.

**Comment by zorgiepoo** [comment]
It should be doing what you describe. If not, then it's a bug. Please try reproducing with a prerelease for 1.15 to see if the issue persists.

**Comment by Ankur0713** [comment]
Hi Zorgiepoo 

I have checked on latest version it is showing the checkForUpdates option ,however on tapping the same we are not getting a "Up to Date Pop up." We are getting the log 

"Sparkle Error: An error occurred in retrieving update information. Please try again later.
2016-12-02 07:49:11 +0000: Sparkle Error (continued): Could not connect to the server."

Can you please suggest on the same. Thanks

**Comment by zorgiepoo** [comment]
It sounds like Sparkle could not connect to your web server at the time you tried checking for updates? But the error message doesn't look very descriptive (was that the entire message?)

You may also want to check out [App Transport Security](https://sparkle-project.org/documentation/app-transport-security/).

**Comment by Ankur0713** [comment]
We are able to successfully download the latest version . the scenario above i discussed is that 
"When we tap on the check updates after that instead of showing the pop up that version is up to date its showing the error: "Sparkle Error: An error occurred in retrieving update information. Please try again later.
2016-12-02 07:49:11 +0000: Sparkle Error (continued): Could not connect to the server."

**Comment by Ankur0713** [comment]
Hi Team ,
Hope you understand the issue we are facing we are successfully able to download the latest version .However on tapping the same again we are not receiving the "Version up to date pop up".
We are getting the above error / log . Please suggest on the same.

**Comment by zorgiepoo** [comment]
> We are able to successfully download the latest version

Using what? Downloading from your web browser can be very different than from connecting inside your application. Is your appcast feed URL or download URL served over http or https? The easiest way for us to reproduce may be if you uploaded a tiny test project (with code) that reproduces the issue.

**Comment by Ankur0713** [comment]
Versions are  getting downloaded easliy from the download url mentioned in Appcast xml.
I am simply saying that when my app is update means upto the latest version than on tapping "CheckForUpdates" option . Instead of showing the pop up that your app is up to latest version. 
It is showing the error.

**Comment by pornel** [comment]
We can't reproduce it. Feel free to reopen if you have new information.
