### ISSUE TITLE
set-git-version-info.sh breaks Carthage builds

### ISSUE THREAD

**Issue by slavikus** [sparkle-project/Sparkle#926]
Recent commit ( fb22a01a088558f5e914d580bb295795fdc32098 ) breaks Carthage builds as `git describe` produces "fatal: No names found, cannot describe anything." (Carthage checks out sources without git directory). Previous version of set-git-version-info.sh didn't suffer from this issue.

**Comment by pornel** [comment]
Thanks for the report. Hopefully fixed.
