### ISSUE TITLE
pkg file auto update

### ISSUE THREAD

**Issue by XinyuHou** [sparkle-project/Sparkle#930]
Firstly, sorry for posting a service request in your Github issue tracker. I couldn't find another way to contact you :(

>　Can install .pkg files for more complicated products.

It says Sparkle support pkg installers. Does it mean I can use Sparkle to auto update my product which is distributed with pkg file?

The main reason I need to use pkg is it has better customization for installing daemon.

Please give me some guild or doc for using Sparkle with pkg files.

**Comment by pornel** [comment]
Yes, pkg is supported. Instead of zip file, use the pkg.

https://sparkle-project.org/documentation/publishing/

Note that if you have customization, you will not be able to use "guided" option that hides the installer, so every update will launch an ugly installer.

**Comment by XinyuHou** [comment]
> Note that if you have customization, you will not be able to use "guided" option that hides the installer, so every update will launch an ugly installer.

@pornel 
Thanks for the quick reply.

If I added some steps for stop and start daemon, does this mean the auto update is much like reinstalling from a normal pkg file?

**Comment by pornel** [comment]
Yes. If you proivde pkg as the update archive we just run standard OS X installer, as if the user double-clicked the pkg file. 

This is obviously not a great user experience, so if you can, try updating the .app. 

If your app also contains another daemon app, put the daemon inside the app bundle, stop the daemon before update (we have delegate method callbacks), and then start the daemon on your app startup.

**Comment by XinyuHou** [comment]
> If your app also contains another daemon app, put the daemon inside the app bundle,
I was trying to find some doc about how to do it.  Do you have any recommendation? Thanks.

**Comment by pornel** [comment]
See how Sparkle does it - in build phases add copy phase, and copy the daemon to your app's resources or executables folder. Launch it with https://developer.apple.com/reference/foundation/nsbundle/1411412-urlforauxiliaryexecutable?language=objc

**Comment by zorgiepoo** [comment]
You should look into `SMJobBless()` and `EvenBetterAuthorizationSample` which handles installing and updating daemons securely. Don't mimic what Sparkle does ;) (it doesn't currently have a daemon anyway). Also don't rely on Sparkle's delegate method callbacks in such a way that your app can't be updated not through Sparkle.

**Comment by XinyuHou** [comment]
@zorgiepoo @pornel 
Thank you guys. I will look into those resources. Wish you guys have a great Xmas.
