### ISSUE TITLE
Keep some files in App Bundle

### ISSUE THREAD

**Issue by roblabla** [sparkle-project/Sparkle#931]
I'd like to keep some files that are distributed inside the .app, but are different for each user. The use-case is, I'm writing a software that will be bundled inside a USB Drive. The app will contain an identifier linked to the USB, and I need this identifier to never change (at least not accidentally).

I'd like to use Sparkle to auto-update this app. However, it seems that sparkle completely replaces the .app. I was wondering what was the best course of action to keep some files from the original app bundle. Is there a place I could put some custom logic in the installation process ?

**Comment by pornel** [comment]
This is not possible, and we deliberately do not allow this.

It's inappropriate to store user-specific files inside the .app bundle. You should move these files to Application Support folder.

**Comment by roblabla** [comment]
The user may have multiple different USBs, each with its own credentials. Moving those files to App Support is unfortunately not an option. I guess I could store the credentials in a hidden file next to the app itself, but that solution feels dirty.

I don't understand why it would be inappropriate to store config files which are never going to change inside the app bundle. Could you elaborate on why is it such a bad idea ?

**Comment by pornel** [comment]
That's the design principle of the OS — data files are supposed to be separated, and the apps themselves are treated as immutable. This leads to design choices all over the place, e.g. non-admin user may not have permissions to modify /Applications, and code signing checks are getting stricter.

For us the practical reason is ability to do an atomic replacement of the app, as well as ability to verify integrity of the whole directory structure when doing delta updates. Preserving of lose files in the app would add more complexity to the code that already has to handle lots of edge cases.

**Comment by roblabla** [comment]
I see, okay. I guess I'll ship the creds in a file outside the bundle then.

Thanks for taking the time to explain why it works this way :).
