### ISSUE TITLE
Exception installing update on 10.12

### ISSUE THREAD

**Issue by genericptr** [sparkle-project/Sparkle#932]
I've never had this problem before and I'm not sure what changed in my development system. I'm on 10.12 and using Sparkle 1.5 Beta 6 according to the Get Info Finder window (I haven't been able to update to the newest version yet due to a linker problem).

After the update downloads and I click the Install & Relaunch button I get this exception. Any ideas why?

2016-12-10 15:23:10.112 TaskCard[26762:961429] *** Terminating app due to uncaught exception 'NSGenericException', reason: '-[NSAlert runModal] may only be invoked from the main thread. Behavior on other threads is undefined.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff8b0c452b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff9f79ccad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff8b142a0d +[NSException raise:format:] + 205
	3   AppKit                              0x00007fff894eab44 _NSRunModal + 103
	4   AppKit                              0x00007fff88f9e57d -[NSAlert runModal] + 270
	5   Sparkle                             0x00000001003ff047 load_dsa_key + 25886
	6   Sparkle                             0x00000001003ffbd4 load_dsa_key + 28843
	7   Sparkle                             0x00000001003fbec9 load_dsa_key + 13216
	8   Sparkle                             0x00000001003fbfab load_dsa_key + 13442
	9   Foundation                          0x00007fff8ca4830d __NSThread__start__ + 1243
	10  libsystem_pthread.dylib             0x00007fffa0290abb _pthread_body + 180
	11  libsystem_pthread.dylib             0x00007fffa0290a07 _pthread_body + 0
	12  libsystem_pthread.dylib             0x00007fffa0290231 thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by pornel** [comment]
We know Sparkle 1.5 beta 6 is broken, incompatible and insecure. Please update Sparkle to a current version, which has these issues fixed.

**Comment by genericptr** [comment]
I got my linker problems fixed and installed the new framework.  Now I'm getting this error which is terminating the process. I don't see why I can't upgrade to 107 from 96 unless the numbers need to be consecutive (I hope not!). Thanks for your support.

2016-12-10 18:38:20.023 TaskCard[28589:1064268] Sparkle: ===== TaskCard =====
2016-12-10 18:38:20.024 TaskCard[28589:1064268] Sparkle: Extracting using '/usr/bin/ditto' '-x' '-k' '-' < '/Users/ryanjoseph/Library/Caches/com.alchemistguild.TaskCard2/org.sparkle-project.Sparkle/TaskCard 197/TaskCard2.0.6.zip' '/Users/ryanjoseph/Library/Caches/com.alchemistguild.TaskCard2/org.sparkle-project.Sparkle/TaskCard 197'
Ryans-MacBook-Pro:Updating ryanjoseph$ 2016-12-10 18:38:22.908 Autoupdate[28604:1064307] Sparkle: ===== Autoupdate =====
2016-12-10 18:38:22.909 Autoupdate[28604:1064307] Sparkle: Installation Error: Error Domain=SUSparkleErrorDomain Code=4006 "Sparkle Updater: Possible attack in progress! Attempting to "upgrade" from 107 to 96. Aborting update." UserInfo={NSLocalizedDescription=Sparkle Updater: Possible attack in progress! Attempting to "upgrade" from 107 to 96. Aborting update.}

**Comment by pornel** [comment]
Yes, new version MUST be greater than the old version.

Otherwise, if you ever had a security vulnerability in your application, even after you fix it, attackers could use your old Sparkle feed to downgrade your app and make your users vulnerable again.

**Comment by genericptr** [comment]
Oh the problem was the appcast key "sparkle:version" didn't match the bundle version of the package (which I did for testing).  Is the sparkle:version key still in use in the new version or can I remove it?

**Comment by pornel** [comment]
It is still in use and it is required.

**Comment by zorgiepoo** [comment]
For future reference, this exception is raised in 1.5b6 because `SUPlainInstaller` doesn't ensure `_finishInstallationWithResult:host:error:delegate:` is executed on the main thread.

**Comment by genericptr** [comment]
Do you have any idea why I started getting this now? I need to update Sparkle in other apps now and the updating may be broken but I haven't had problems until just now.

**Comment by zorgiepoo** [comment]
NSAlert didn't always have an assertion check to ensure `-runModal` was being invoked on the main thread. You can better your chances by not packaging the update incorrectly.

**Comment by genericptr** [comment]
I must have been getting an error an triggering the NSAlert. Thanks again.
