### ISSUE TITLE
Incompatible library version?

### ISSUE THREAD

**Issue by genericptr** [sparkle-project/Sparkle#935]
I'm updating Sparkle in my projects (which worked for one after setting  the @rpath) but now I'm getting this error. Is this Sparkle related or something generally related to the linker or compiler? I don't understand why I'm getting this error specifically with this app and not the other.

The code compiles and links but when launched I get this runtime error. Version of what? Thanks again for your support.

=====

dyld: Library not loaded: @rpath/Sparkle.framework/Versions/A/Sparkle
  Referenced from: /Users/ryanjoseph/Desktop/Projects/FPC/iCloudStatus/iCloudStatus.app/Contents/MacOS/iCloudStatus
  Reason: Incompatible library version: iCloudStatus requires version 1.6.0 or later, but Sparkle provides version 1.5.0

**Comment by pornel** [comment]
Sorry, I haven't seen that error before.

Is it possible that you're linking to Sparkle twice? Is 1.6.0 a version of Sparkle you're updating to?

**Comment by genericptr** [comment]
Sorry I had to take a break on this but I got it figured. Yes, something regarding to linking twice before the new library was copied into the bundle by the builder and linking with a 32 bit binary. Misleading error message also. Thanks for your time.
