### ISSUE TITLE
Can’t be updated when it’s running from a read-only volume like a disk image or an optical drive

### ISSUE THREAD

**Issue by datinc** [sparkle-project/Sparkle#936]
Our app currently is displaying an error that reads

```
Update Error!

AppName  can’t be updated when it’s running from a read-only volume like a disk image or an optical drive. Move AppName to your Applications folder, relaunch it from there, and try again.
```

However the application is in the application folder.

We are seeing this on macOS 10.12.1

**Comment by datinc** [comment]
Looks to be a duplicate of https://github.com/sparkle-project/Sparkle/issues/923

**Comment by pbadeer** [comment]
I had this issue as well (running a old version of Sketch, so no need to reopen), solved by CMD+dragging (so that it moves the app instead of making a shortcut) the app back to the downloads folder and then dragging it back to the applications folder. For anyone who's here from google.

**Comment by rstudner** [comment]
Just wanted to comment (for the 1% chance it helps anyone) - if by chance a) you are on a mac and b) you are using pathfinder -- don't drag apps from DMG's to Applications folder with PathFinder.  There is a bug.

**Comment by digitalmoksha** [comment]
Yes, I've also had this problem with PathFinder

**Comment by vishvish** [comment]
Just to echo @rstudner, this is a real problem. Opening the DMG with Finder instead of Path Finder and dragging to Applications made the application work properly again.

**Comment by pornel** [comment]
Is PathFinder aware of this? Did you report the bug to them?

**Comment by barrettj** [comment]
You can fix it for apps it's already happened to with the following:

Quit App
Run command: xattr -dr com.apple.quarantine /Applications/Your.app
Re-launch app


https://apple.stackexchange.com/questions/254684/macos-sierra-missing-app-icon-in-dock-and-check-for-updates-fails-for-certa/283500#283500

**Comment by piotrekzawada** [comment]
@barrettj thanks! It worked for me

**Comment by sfordin** [comment]
barrettj's suggestion did the trick for me. Thanks very much!

**Comment by Gummibando** [comment]
Yep, removing the quarantine xattr did the trick.

**Comment by JohnONolan** [comment]
"Sketch can't be updated when it's running from a read-only volume like a disk image or an optical drive. Move Sketch to your Applications folder, relaunch it from there, and try again."

Purely adding this ^ error so that future people googling find this issue. barretj's solution above worked for me too. Not sure why Sketch got stuck randomly, I don't use PathFinder and hadn't experienced any issues previously.

**Comment by kornelski** [comment]
We've already changed this message, but it will take years before everyone updates to newer versions of software.

**Comment by IterationCorp** [comment]
If you're using macOS X Mojave you have to give full disk access to the app. Open System Preferences / Security & Privacy / Privacy tab / Select Full disk access on the left, add you app to the list (drag and drop or "+")

**Comment by kornelski** [comment]
No, Mojave does not require any changes in System Preferences. Please copy the app to Applications using Finder, and don't change any Preferences.

**Comment by antistandard** [comment]
> I had this issue as well (running a old version of Sketch, so no need to reopen), solved by CMD+dragging (so that it moves the app instead of making a shortcut) the app back to the downloads folder and then dragging it back to the applications folder. For anyone who's here from google.

THIS WORKS. You can also move sketch.app to the desktop and then back into Applications folder as an alternative (same thing really.)

**Comment by michaelaye** [comment]
it is very un-macOS-ic to force apps only running in /Applications. At the very LEAST, ~/Applications should be fine as well, but in principle, apps should run everywhere, just not from read-only or temporary mounts.

**Comment by kornelski** [comment]
@michaelaye I agree, but we have absolutely no say in this. It's 100% imposed by Apple and can't be changed or disabled by developers.

**Comment by Jason7shi** [comment]
Move VScode from download folder to application folder is work to me Thanks.

**Comment by firenzelei** [comment]
this solution my problem
thanks

**Comment by r0039** [comment]
this solved my issue. 
`MacBook-Pro:~ tien$ xattr -dr com.apple.quarantine /Applications/Visual\ Studio\ Code.app/`

**Comment by ilivestrong** [comment]
Thanks a gazillion

**Comment by bitmanic** [comment]
I've been running into this intermittently with Atom for the past year. It was driving me wild so I tried switching to Visual Studio Code...but the same thing happened today with VS Code. I've googled the heck out of the issue but this is the first time I've seen this specific thread. `pbadeer`'s suggestion worked for me. Thanks!

**Comment by mulili** [comment]
> If you're using macOS X Mojave you have to give full disk access to the app. Open System Preferences / Security & Privacy / Privacy tab / Select Full disk access on the left, add you app to the list (drag and drop or "+")

thanks，you save my life

**Comment by vivekb26** [comment]
> Our app currently is displaying an error that reads
> 
> ```
> Update Error!
> 
> AppName  can’t be updated when it’s running from a read-only volume like a disk image or an optical drive. Move AppName to your Applications folder, relaunch it from there, and try again.
> ```
> 
> However the application is in the application folder.
> 
> We are seeing this on macOS 10.12.1
> 
> ⚠️ **To fix this problem: quit the app, and use Finder to copy it to Applications folder** ⚠️
> 
> macOS does not allow updating apps in Downloads folder. This message has already been improved in the newer version.


For permanent solution

Disable Gatekeeper in macOS Sierra from Terminal using a command

To disable Gatekeeper (i.e., set it to “Anywhere”) from the command line, open a new Terminal window then enter the following command:

sudo spctl --master-disable

https://www.techjunkie.com/gatekeeper-macos-sierra/#:~:text=Disable%20Gatekeeper%20in%20macOS%20Sierra,choice%20of%20%E2%80%9CAnywhere%E2%80%9D%20missing.

**Comment by kornelski** [comment]
I don't recommend disabling Gatekeeper. It may be annoying, but it is a security feature.

**Comment by prinzprithvi** [comment]
not only for mentioned applications, going forward this applies to all app's 👯

**Comment by zorgiepoo** [comment]
This discussion isn't being very productive and some bad advice (full disk access, disabling SIP) is being given here. VS Code and Atom don't even use Sparkle.

If you are using Path Finder and it's still an issue, go report this bug and thread to them.

Like others mentioned you can move the app to one place in Finder and move it back.

Or you can [clear the quarantine attribute](https://github.com/sparkle-project/Sparkle/issues/936#issuecomment-308441227).

If you are developer, consider shipping a dmg for website distribution to decrease your chances.

Sparkle is not set up to automatically notify users that it can't update an app. If that occurs, it's a bug with the app and you should report the issue to them.
