### ISSUE TITLE
Verifiable transparency of updates

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#937]
https://blog.torproject.org/blog/technology-hostile-states-ten-principles-user-protection

> We are particularly troubled by the trend towards the use of App Stores to distribute security software and security updates. When each user is personally identifiable to the software update system, that system becomes a perfect vector for backdoors. Globally visible audit logs like [Google's General Transparency](https://github.com/google/trillian) are one possible solution to this problem. Additionally, the anonymous credentials mentioned in Principle 7 provide a way to authenticate the ability to download an app without revealing the identity of the user, which would make it harder to target specific users with malicious updates.

Sparkle is already doing well by providing anonymous updates, but still developers could be coerced (or have their keys stolen) to send backdoored updates to users identified by an IP address.

Can we do better? Is it feasible for us to provide an equivalent of Certificate Transparency for updates?

As far as I understand the goal is to ensure that existence of every version of the app is public and clients won't install some secret one-off build.

**Comment by pornel** [comment]
Firefox is doing it by piggybacking on certificate logs: 

https://wiki.mozilla.org/Security/Binary_Transparency

**Comment by zorgiepoo** [comment]
Updates are signed with EdDSA and we prevent downgrades. Worst case is user upgrades to some build that is not entirely latest or beta but I don't think that is a big concern.
