### ISSUE TITLE
Cocoapods out of date?

### ISSUE THREAD

**Issue by zorgiepoo** [sparkle-project/Sparkle#939]
https://cocoapods.org/?q=sparkle

..shows version 1.14.0. Indeed when I try creating a cocoa pods project, and adding Sparkle to the Podfile, it downloads 1.14.0.

cc @pornel

**Comment by pornel** [comment]
I thought I pushed it…

Anyway, I'm on a shitty proxied internet now, and I can't use cocoapods here. Can you or @jakepetroules push it?

**Comment by zorgiepoo** [comment]
I'm not a pod maintainer for Sparkle, so I can't do it right now. I just created an account however using my zorgiepoo gmail email address. I could be added via [Adding other people as contributors](https://guides.cocoapods.org/making/getting-setup-with-trunk.html).

Maybe another `pod trunk push` invocation needs to be done to update the spec?

**Comment by pornel** [comment]
OK, I've added you. I've pushed the pod too.
