### ISSUE TITLE
Ignore automatic download setting if automatic download fails

### ISSUE THREAD

**Issue by pornel** [sparkle-project/Sparkle#957]
Ignore automatic download setting if automatic download fails (e.g. fails *n* times, or fails for *n* days)

The problem is that when silent automatic update happens the user is unaware of it, and user may quit the app before download finishes (this is realistic scenario for ImageOptim, which is sometimes used as part of automated process).

Hopefully, if the automatic download setting is ignored after failure(s), the next update will alert the user, and the user will take more care to follow through with the update.

**Comment by zorgiepoo** [comment]
Alternatively support resuming downloads that have been aborted (#607), but I don't think either of these problems should be tackled at this time.

A current workaround in ImageOptim's case is not starting the updater if it's ran in an automated way (seems like this may be a good idea anyway).

**Comment by pornel** [comment]
Good point. Resuming downloads will largely solve that problem.
