### ISSUE TITLE
generate_appcast should decompress to tmp dir that is derived from hash of the archive

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#959]
Currently destination directory for decompression is based on source file's filename. It won't update decompressed version if the source file changes without changing filename.

**Comment by digitalmoksha** [comment]
This bit me today.  After having run `generate_appcast` on a set of archives, I changed the build number (the version number) while leaving the short version the same (and hence the archive filename) and replaced in the archive folder.  This caused the original values of the appcast (from the previously expanded archive in the `.tmp` folder) to be used.  The update then fails with only a `Service exited with abnormal code: 1` error in the log file.
