### ISSUE TITLE
generate_appcast should protest if it finds private DSA key in the archive directory

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#974]
From tool's perspective the archive directory is for uploading to the server, and uploading a private key would ruin security. Banning *.pem files in the archive dir is probably enough.

**Comment by zorgiepoo** [comment]
DSA isn't used anymore. While generate_keys can export an EdDSA key to disk, it's not the default approach, and I don't think there's a specific file extension one may use there.
