### ISSUE TITLE
Update Download Request Being Shown to First Time Users of Application

### ISSUE THREAD

**Issue by CapSkyHook** [sparkle-project/Sparkle#975]
Hi,

I am running into an issue where first time users are downloading our native MacOS application and are being presented with a modal dialog asking if they would like to download the new update. This occurs without an explicit call to check for updates. This does not happen on any nth time launch of the application.

I have set updaterShouldPromptForPermissionToCheckForUpdates in the delegate to return NO.

Is there something else I should set to stop sparkle from showing that dialog on app launch? 

Thank you so much for the help!

**Comment by pornel** [comment]
This is the code for it:

https://github.com/sparkle-project/Sparkle/blob/4636588e76d476a49854528a1adca1e2ed27e002/Sparkle/SUUpdater.m#L198,L205

Is your selector spelled exactly like it should?

Do you have `SUPromptUserOnFirstLaunchKey` config set? (in plist or in user defaults?)

Do you have `SUHasLaunchedBeforeKey` set in user defaults?

Is it possible that you call Sparkle twice?

**Comment by CapSkyHook** [comment]
Hi Pornel,

The only on first time situation appeared to be a red herring. It was related to the last checked time in the user defaults and the minimum check interval time. We want to manually trigger all of our update checks so I have currently fixed the problem but setting a very large SUScheduledCheckInterval.

Is there a way to completely disable automatic checking. Based on examining the SUUpdater file, I see that I could possibly set SUEnableAutomaticChecks to NO or set SUScheduledCheckInterval to 0, taking advantage of the automaticallyChecksForUpdates method. However, when I set SUEnableAutomaticChecks to NO it triggers a prompt asking the user if the application should automatically check for updates which is not desired for our user experience.

Is it correct for me to set the SUScheduledCheckInterval to 0 or is there another way to completely disabled sparkle's interval based update check?

Thank you for all the help!
