### ISSUE TITLE
'Skip this version' callback or disable

### ISSUE THREAD

**Issue by peterpaulis** [sparkle-project/Sparkle#976]
- there should be a BOOL delegate callback, to ask if 'Skip this version' should be enabled... in cases of critical or forced updated, you don't want the 'Skip this version'... so the decision should be left to the deleagte

**Comment by pornel** [comment]
We do have `<sparkle:criticalUpdate/>` for this.

**Comment by peterpaulis** [comment]
But when <sparkle:criticalUpdate/> is present, the 'Skip this version' is present too

**Comment by pornel** [comment]
OK, let's fix *that* then :)
