### ISSUE TITLE
xar doesn't seem to support lzma

### ISSUE THREAD

**Issue by pornel** [sparkle-project/Sparkle#981]
I've tried to improve compression of binary delta files by changing compression from bzip2 to LZMA, but:

```c
xar_opt_set(x, XAR_OPT_COMPRESSION, XAR_OPT_VAL_LZMA);
```

seems to produce uncompressed archives. Is this unsupported? bug?

**Comment by zorgiepoo** [comment]
See also #792 where "lzma" worked poorly; perhaps it's buggy, not sure.

**Comment by pornel** [comment]
I've tried bogus values, and they cause uncompressed archive to be created. Perhaps lzma is simply not supported in the built-in library (even though headers and CLI xar include the option).

**Comment by pornel** [comment]
In case of ImageOptim uncompressed xar followed by separate bzip2 compression of the whole delta gives about 40% reduction in file size compared to xar with bzip2 internally. I guess xar compresses each file individually, and doesn't eliminate cross-file redundancy.

**Comment by pornel** [comment]
Maybe one day I'll make format v3 with all the extras… #979
