### ISSUE TITLE
Failure to download delta update file aborts update instead of falling back to full download

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#994]
If appcast contains a suitable delta update, but the update is a 404 on the server, then the entire update process will fail.

In other case, if the delta doesn't apply cleanly, we fall back to downloading the full update. I think it'd make sense to fall back to full update in all cases.

**Comment by zorgiepoo** [comment]
I think it's a low priority enhancement. Would also want to spit out a warning that it's 404.
