### ISSUE TITLE
generate_appcast can't work with app names that have spaces

### ISSUE THREAD

**Issue by shmidt** [sparkle-project/Sparkle#995]
For ex.:

`Sparkle: Extracting using '/usr/bin/ditto' '-x' '-k' '-' < '/Users/dshmidt/Documents/Sparkle/snoop_archives/.tmp/My Dog-0.0.1.zip.tmp/My Dog-0.0.1.zip' '/Users/dshmidt/Documents/Sparkle/snoop_archives/.tmp/My Dog-0.0.1.zip.tmp'
Illegal instruction: 4
`

**Comment by pornel** [comment]
Thanks for the report. Fortunately that was minor mistake, surprisingly (and fortunately) not related to escaping of commands.

**Comment by shmidt** [comment]
@pornel Thanks for your great work.

**Comment by digitalmoksha** [comment]
This problem still occurs when generating the delta XMLNode:

```
XMLNode.attribute(withName: "url", stringValue: URL(string: delta.archivePath.lastPathComponent, relativeTo: update.archiveURL)!.absoluteString) as! XMLNode,
```

should be, I think

```
XMLNode.attribute(withName: "url", stringValue: URL(string: delta.archivePath.lastPathComponent.addingPercentEncoding(withAllowedCharacters: CharacterSet.urlPathAllowed)!, relativeTo: update.archiveURL)!.absoluteString) as! XMLNode,
```

**Comment by pornel** [comment]
Yes, indeed. Can you make a pull request?

**Comment by digitalmoksha** [comment]
no problem, added pull request #1028
