### ISSUE TITLE
Testing with self-signed https

### ISSUE THREAD

**Issue by drootang** [sparkle-project/Sparkle#997]
Is there a way to test sparkle updates with an appcast from an apache server on localhost with a self-signed certificate?

I keep running into errors such as:
`NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)`
which leads to:
`Sparkle: Error: An SSL error has occurred and a secure connection to the server cannot be made. (null) (URL https://localhost/rss/cast.xml)`

Is it strictly necessary to get a certificate from a trusted CA even for internally testing https?

**Comment by pornel** [comment]
Are you using it in node or browser?

In browser, like Chrome, there's a about:flags setting that allows invalid certs on localhost.

In Node, that's icky. There's a setting that disables all security for all connections, which I'm not a fan of. 
If you have a certificate self-signed by your own CA, you can set your ca using `.ca()` command (we support most of the options [documented here](https://nodejs.org/api/https.html#https_https_request_options_callback))

**Comment by pornel** [comment]
*edit: sorry, I've confused repos and my previous reply was off-topic :)*

We don't have any special provision for trusting localhost. Since we're using `NSURLConnection`, I presume a system-wide settings should work. Try marking your certificate as always trusted via Safari's dialogs or Keychain Access.

Personally I use a test URL on a server with Let's Encrypt cert.

**Comment by drootang** [comment]
I was wondering what the heck you were talking about!

Your suggestion is sensible, but adding the site's certificate as always trusted in my keychain had no effect on the errors logged by NSURLSession and Sparkle. ATS seems to be pretty restrictive, which is probably a good thing overall.

My solution, which others may find useful, is to tell the app to allow insecure connections on the local network in Info.plist, and change the SUFeedURL to an http version. For release, remove the security exceptions and change SUFeedURL back to https.

In Info.plist add `NSAppTransportSecurity`. By default, this is a dictionary. Then add the boolean `NSAllowsLocalNetworking` and set it to YES.
