### ISSUE TITLE
Failures to apply delta

### ISSUE THREAD

**Issue by kornelski** [sparkle-project/Sparkle#998]
In my server logs I see 8%-15% of users download both delta and a full update, which I'm assuming means the delta failed to apply.

e.g.

> 1.1.1.1 - - [13/Jan/2017:09:49:07 +0000] "GET /ImageOptim1.7.0a1-1.6.5a3.delta HTTP/1.1" 200 650558 "-" "ImageOptim/1.6.5a3 Sparkle/1.15.1 (Mac OS X 10.12.2)"
> 1.1.1.1 - - [13/Jan/2017:09:49:08 +0000] "GET /ImageOptim1.7.0a1.tar.bz2 HTTP/1.1" 200 1394498 "-" "ImageOptim/1.6.5a3 Sparkle/1.15.1 (Mac OS X 10.12.2)"

If it was just 1-2% I'd assume people modified the app, but 15% is a bit much. I'm seeing the failures consistently across many versions of my app, so it's not a problem with any particular update. And I can't reproduce the failure on my machine.

Does anyone else see the problem?

What could be the cause?

Shall we add some form of delta-crash-report sending?

**Comment by zorgiepoo** [comment]
One suspect I have is that people install apps to strip away files to save hard disk space. In particular, I'd suspect removing localizations and removing unused architectures from binaries because those changes may not break Apple's code signing.

I have not been keeping track of such statistics on my end. I'm not sure what "delta-crash report sending" would entail.

**Comment by pornel** [comment]
If the error rate was closer to 1%, I'd also suspect app stripping, but 15% seems too much. It must be something more common (maybe permissions/quarantine/location of the app?)

**Comment by zorgiepoo** [comment]
1-2% is what I'd expect if a user altered the application themselves. On the other hand, if there is a popular Mac app out there that helps users clean up their Mac, I'd expect the % to increase significantly.

Extended attributes (i.e. quarantine) aren't hashed, but permissions are. I would do some manual testing across admin vs non-admin users, and who ownership of the app is. I wasn't able to reproduce anything that'd cause a failure.

**Comment by zorgiepoo** [comment]
If I were in your shoes, if you could send back to your server if "only one localization is present" vs "more than one localization is present", those numbers may be interesting to look at.

**Comment by zorgiepoo** [comment]
We've fixed a lot more edge case issues and skip applying delta updates when they're ineligible in some cases now so this may be worth re-verifying.
